### ISSUE TITLE
fontbakery-fix-dsig.py 

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1001]
Hello,

In [checklist.md](https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md) a dsig is required. 

Is there a reason why this script was deleted?

Cheers,
Marc

**Comment by felipesanches** [comment]
The main script fontbakery-check-ttf.py handles the dsig checking and hotfixing.

**Comment by felipesanches** [comment]
I'm not sure we have ever had this as a standalone script.

**Comment by davelab6** [comment]
There was for sure a `fontbakery-fix-dsig.py` because I have it from the pip install.

**Comment by davelab6** [comment]
@felipesanches please bring it back :)

**Comment by felipesanches** [comment]
ok, thanks.
