### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1003]
I'm getting concerned I may start breaking things whenever I do a pr.

I see we have functional tests which is cool. However, I'd love to have tests for complex functions. I just did some regex stuff so tests for these areas would be useful.

Cheers,
Marc

**Comment by davelab6** [comment]
I'm supportive of this but I'm not sure its a hi priority for the next few
weeks.

**Comment by vmesel** [comment]
What unit tests should be available?

**Comment by m4rc1e** [comment]
@vmesel Once we have #1155 sorted, unit tests for these would be great.

**Comment by davelab6** [comment]
#1155 was merged... This seems like a big effort!

**Comment by davelab6** [comment]
Closing as this is under way
