### ISSUE TITLE
check-ttf.py: Vertical Metrics check

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1007]
The implementation to check vertical metrics is out of date and imo incorrect.

`ERROR    Vertical metrics. Changes that must be applied to this font: hhea ascent from 950 to 1000 | OS/2 sTypoAscender from 811 to 1000 | OS/2 usWinDescent from 250 to 0 | OS/2 sTypoLineGap from 139 to 0`

We had a mega discussion in Kalapi's Google Font's Work [thread](https://groups.google.com/d/msg/googlefonts-discuss/W4PHxnLk3JY/MYgVlQMjAwAJ).

We decided on using @khaledhosny schema for old fonts. I also have a [script](https://github.com/m4rc1e/mf-glyphs-scripts/blob/master/Google%20Fonts/test_khaled_metrics.py) to check this schema is implemented correctly in GlyphsApp.

I propose we check the following:

winAscent is at least higher than bbox yMax
winDescent is abs(bbox yMin)

hheaTypo == os/2Typo and > family ascender
hheaDesc == os/2Typo and <  family descender

Since Kalapi's schema will be used on newer fonts. We should get a notice if 
hheaLineGap and os/2LineGap != 0. Khaled's schemes uses 0 value LineGaps.

The legacy vert metrics test was to check whether all 3 metric sets were the same and greater than 125% of the font's upm. 

If we all agree, I don't mind implementing this.

Cheers,
Marc

**Comment by m4rc1e** [comment]
Well, I've submitted a pr, #1011, if you'd like to try this out.

Cheers,
Marc

**Comment by felipesanches** [comment]
#1011 was just merged into master.
