### ISSUE TITLE
postScriptName field ends with '-Regular'

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1016]
Hey,

I get the following error:
`ERROR    METADATA.pb postScriptName field ends with '-Regular'`

Our naming [spec](https://docs.google.com/spreadsheets/d/1ckHigO7kRxbm9ZGVQwJ6QJG_HjV_l_IRWJ_xeWnTSBg/edit#gid=0) has hyphens for the Postscript name.

Cheers,
Marc

**Comment by felipesanches** [comment]
* Which font did you use to get this?
* What was the expected result? / Why?

**Comment by felipesanches** [comment]
@davelab6 

The "METADATA.pb 'filename' matches 'postScriptName' ?" check  rejects a "-Regular" prefix in font filenames or in the postScriptName field of METADATA.pb files. I seem to recall that this check criteria was introduced after conversations about it here on the issue tracker.

On the other hand, the spreadsheet that @m4rc1e referenced to lists "Roboto-Regular" as a valid postScriptName. Maybe the spreadsheet is wrong ? Or maybe the precise check criteria is stil unclear.

**Comment by davelab6** [comment]
@m4rc1e what does glyphapp currently generate for the ID6 namerecord for a regular font?

**Comment by m4rc1e** [comment]
@davelab6  

id6 = Trocchi-Regular

**Comment by davelab6** [comment]
If that's what the latest beta build makes, we should change the FB check. I remember there was some problems we uncovered with glyphs name scheme a while ago.

**Comment by felipesanches** [comment]
ok, then. I'll adapt the check to accept this naming rule.

**Comment by felipesanches** [comment]
@m4rc1e Please review and reopen if you notice any problem.
