### ISSUE TITLE
Copyright notices should match the folowing pattern: 'Copyright 2016 Author Name (name@site.com)'

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1017]
Hey,

I've based my copyright name/OFL on our [spec](https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md#ofltxt)

I have the following:
`Copyright 2012 The Trocchi Project Authors (vern@newtypography.co.uk)`

our spec has:
`Copyright 2016 The Acme Project Authors (info@foundry.com)`

I think FB has an incorrect check for this.

ps
apologies, my commits are going to slow down on this project. I need to focus on releases for the time being.

**Comment by felipesanches** [comment]
I just merged a fix. Let me know if that's enough or if it still fails for any corner case you may find. :-)

**Comment by felipesanches** [comment]
@m4rc1e feel free to reopen the issue in case it may still need further tweaks.

**Comment by davelab6** [comment]
Sounds good
