### ISSUE TITLE
Generating CONTRIBUTORS.txt

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1031]
Hey folks,

I've written a script to look at git commits and make a CONTRIBUTORS.txt file. It works in the same manner as [add_font.py](https://github.com/google/fonts/blob/master/tools/add_font.py)

Shall I include this in FontBakery or GoogleFonts/tools?

@felipesanches @davelab6

**Comment by felipesanches** [comment]
Sounds like a generic tool that could have its own repo. But I would be OK with having a copy of it on Fontbakery repo as well.

**Comment by davelab6** [comment]
Here is better, thanks!
