### ISSUE TITLE
Status of Google Fonts 'name' table

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontbakery#1035]
Now that we have both a recommendation for correct `'name'` values and code to check it (hooray!), can you please run the name verification over the entire google fonts collection? - I'm eager to know how broken it is (or hopefully isn't).

Something like a csv of family, name field, # of problems (`Roboto, 1, 0` or `Roboto, fullname, 0` for Roboto with 0 fullname problems) would be ideal for my purposes. Or even just `family, # name problems`.

**Comment by davelab6** [comment]
@felipesanches please do this asap :)

**Comment by felipesanches** [comment]
I'm running a custom script locally to automatically test the full set of Google Fonts.
I'll probably have a general summary tomorrow.

**Comment by felipesanches** [comment]
I've got around 80% of the TTF files from google fonts git repo checked. These have generated log files in both markdown and json format which may (likely) include font errors. The other ~20% have some osrt of issue with fontbakery and did not even save a report.

Today I'm investigating what are these issues and I may open new tickets in this issue tracker to address those with the goal of reaching the 100% coverage of the full repo that we used to have a while ago.

I'll also create a new script to compile a single report with summarized/aggregated data from the full set of hundreds of fonts. The purpose is to make it easy for someone to generate this global report with the only requirement of spending some time for all the checks to be run. Nowadays, in addition to the time requirement we still have to do things manually, so I'm aiming at automating at least some of it now.

**Comment by davelab6** [comment]
@felipesanches what's the status of this? :)

**Comment by felipesanches** [comment]
I'm working on it.

For the few past hours I've been tweaking my setup locally and running and re-running the script.

it's not perfect but it's getting good. I'll provide an updated report here once I get a good summary of the aggregated check results.

**Comment by felipesanches** [comment]
61 of 856 fonts (roughly 7% of them all) still have issues with Fontbakery. ;yesterday we had ~20% of fonts with issues. I estimate that most of these 13% (aproximately 110 fonts) have non-canonical names. Due to the fix of issue #1036 and a few other tweaks to the script they don't crash the automated check of the full font repo anymore.

All have to tackle the remaining 7% tomorrow. I do have a list with their names, but I'll first try to fix some of the crashes before providing here a shorter final list of bad fonts.

**Comment by felipesanches** [comment]
A quick estimate:
```
felipe@guarana:~/fb-dev/check_results (master)*$ ack-grep "is not named canonically." -l|grep json|wc
    129     129    5665
```

And then we can get the full list of font files with non-canonical names this way:

```
felipe@guarana:~/fb-dev/check_results (master)*$ ack-grep "is not named canonically." -l|grep json | cut -d. -f1,2
specialelite/SpecialElite.ttf
wireone/WireOne.ttf
justmeagaindownhere/JustMeAgainDownHere.ttf
bevan/Bevan.ttf
redressed/Redressed.ttf
irishgrover/IrishGrover.ttf
novasquare/NovaSquare.ttf
kristi/Kristi.ttf
swankyandmoomoo/SwankyandMooMoo.ttf
imfellfrenchcanonsc/IMFeFCsc28P.ttf
dangrek/Dangrek.ttf
snippet/Snippet.ttf
metal/Metal.ttf
ptmono/PTM55FT.ttf
sunshiney/Sunshiney.ttf
holtwoodonesc/HoltwoodOneSC.ttf
angkor/Angkor.ttf
imfellenglishsc/IMFeENsc28P.ttf
justanotherhand/JustAnotherHand.ttf
megrim/Megrim.ttf
lovedbytheking/LovedbytheKing.ttf
koulen/Koulen.ttf
fontdinerswanky/FontdinerSwanky.ttf
suwannaphum/Suwannaphum.ttf
droidserif/DroidSerif.ttf
giveyouglory/GiveYouGlory.ttf
imfellenglish/IMFeENit28P.ttf
slackey/Slackey.ttf
gloriahallelujah/GloriaHallelujah.ttf
zeyada/Zeyada.ttf
imfelldwpica/IMFePIit28P.ttf
homemadeapple/HomemadeApple.ttf
candal/Candal.ttf
overtherainbow/OvertheRainbow.ttf
irishgrowler/IrishGrowler.ttf
annieuseyourtelescope/AnnieUseYourTelescope.ttf
cherrycreamsoda/CherryCreamSoda.ttf
meddon/Meddon.ttf
chenla/Chenla.ttf
oflsortsmillgoudytt/OFLGoudyStMTT.ttf
oflsortsmillgoudytt/OFLGoudyStMTT-Italic.ttf
reeniebeanie/ReenieBeanie.ttf
ultra/Ultra.ttf
michroma/Michroma.ttf
architectsdaughter/ArchitectsDaughter.ttf
gentiumbookbasic/GenBkBasB.ttf
novaoval/NovaOval.ttf
jomolhari/Jomolhari-alpha3c-0605331.ttf
comingsoon/ComingSoon.ttf
bigshotone/BigshotOne.ttf
novascript/NovaScript.ttf
monofett/Monofett.ttf
khmer/Khmer.ttf
moul/Moul.ttf
nothingyoucoulddo/NothingYouCouldDo.ttf
rocksalt/RockSalt.ttf
didactgothic/DidactGothic.ttf
aclonica/Aclonica.ttf
imfelldoublepicasc/IMFeDPsc28P.ttf
paytoneone/PaytoneOne.ttf
siemreap/Siemreap.ttf
craftygirls/CraftyGirls.ttf
neucha/Neucha.ttf
ruslandisplay/RuslanDisplay.ttf
novacut/NovaCut.ttf
sueellenfrancisco/SueEllenFrancisco.ttf
taprom/Taprom.ttf
dawningofanewday/DawningofaNewDay.ttf
siamreap/Siemreap.ttf
permanentmarker/PermanentMarker.ttf
indieflower/IndieFlower.ttf
ptsansnarrow/PT_Sans-Narrow-Web-Bold.ttf
pacifico/Pacifico.ttf
medievalsharp/MedievalSharp.ttf
novaflat/NovaFlat.ttf
tangerine/Tangerine_Bold.ttf
odormeanchey/OdorMeanChey.ttf
walterturncoat/WalterTurncoat.ttf
goudybookletter1911/GoudyBookletter1911.ttf
ptsans/PT_Sans-Web-Bold.ttf
kranky/Kranky.ttf
lateef/LateefRegOT.ttf
anton/Anton.ttf
novamono/NovaMono.ttf
metrophobic/Metrophobic.ttf
bangers/Bangers.ttf
pecita/Pecita.ttf
ptserif/PT_Serif-Web-Bold.ttf
imfellfrenchcanon/IMFeFCit28P.ttf
bokor/Bokor.ttf
sixcaps/SixCaps.ttf
ptserifcaption/PT_Serif-Caption-Web-Italic.ttf
labelleaurore/LaBelleAurore.ttf
imfelldwpicasc/IMFePIsc28P.ttf
freehand/Freehand.ttf
leaguescript/LeagueScript.ttf
novaround/NovaRound.ttf
carterone/CarterOne.ttf
imfelldoublepica/IMFeDPit28P.ttf
ptsanscaption/PT_Sans-Caption-Web-Bold.ttf
preahvihear/Preahvihear.ttf
imfellgreatprimer/IMFeGPit28P.ttf
imfellgreatprimersc/IMFeGPsc28P.ttf
coveredbyyourgrace/CoveredByYourGrace.ttf
waitingforthesunrise/WaitingfortheSunrise.ttf
droidsansjapanese/DroidSansJapanese.ttf
asset/Asset.ttf
sigmarone/SigmarOne.ttf
pollerone/PollerOne.ttf
maidenorange/MaidenOrange.ttf
droidsans/DroidSans.ttf
thegirlnextdoor/TheGirlNextDoor.ttf
chewy/Chewy.ttf
gentiumbasic/GenBasB.ttf
luckiestguy/LuckiestGuy.ttf
crushed/Crushed.ttf
francoisone/FrancoisOne.ttf
francoisone/FrancoisOne-Regular.ttf
sansitaone/SansitaOne.ttf
loveyalikeasister/LoveYaLikeASister.ttf
gfsneohellenic/GFSNeohellenic.ttf
moulpali/Moulpali.ttf
bayon/Bayon.ttf
novaslim/NovaSlim.ttf
schoolbell/Schoolbell.ttf
goblinone/GoblinOne.ttf
gravitasone/GravitasOne.ttf
shadowsintolight/ShadowsIntoLight.ttf
droidsansmono/DroidSansMono.ttf
```

**Comment by felipesanches** [comment]
@davelab6 @rsheeter It seems that the most common name issue is the lack of -Regular in the TTF filename.

Tomorrow I'll bring you further insight on the name-table related checks.

**Comment by felipesanches** [comment]
Pull request #1042 fixed the check of 9 fonts reducing from 61 to 52 (~6%) the total number of fonts that still crash fontbakery.

**Comment by felipesanches** [comment]
Pull request #1043 fixed the check of 27 fonts reducing from 52 to 25 (~3%) the total number of fonts that still crash fontbakery.

**Comment by davelab6** [comment]
Cool. It must be 0! :)

**Comment by felipesanches** [comment]
We'll soon reach full coverage. I'm working towards that goal :-)

**Comment by felipesanches** [comment]
The issue fixed by Pull request #1047 affected a single font file. So we're at 24 fonts still crashing fontbakery now... :-(

**Comment by felipesanches** [comment]
The issue fixed by Pull request #1049 affected 16 fonts. So we now have only 8 fonts still crashing fontbakery :-D

**Comment by felipesanches** [comment]
OK. No more crashers!
Now we've got full coverage of the Google Fonts collection! :-D

**Comment by felipesanches** [comment]
Next task: to generate a unified JSON (and/or Github Markdown) with the summary of which set of fonts triggered errors on each of fontbakery checks.

**Comment by felipesanches** [comment]
OK. I have created a script that summarizes the errors.
Here's an overview of how many files fail each of fontbakery checks:

```
* [   3 errors] 'Is this a propper HTML snippet ?'
* [  68 errors] 'METADATA.pb 'name' contains font name in right format ?'
* [ 101 errors] 'Fonts have equal numbers of glyphs?'
* [ 120 errors] 'Description strings in the name table (nameID = 10) must not contain copyright info.'
* [  91 errors] 'Whitespace glyphs have coherent widths?'
* [ 103 errors] 'Glyph names are all valid?'
* [  61 errors] 'Font has old ttfautohint applied?'
* [1011 errors] 'Assure valid format for the main entries in the name table.'
* [ 471 errors] 'Copyright notice does not contain Reserved Font Name'
* [  51 errors] 'METADATA.pb 'postScriptName' contains font name in right format ?'
* [ 183 errors] 'Checking fsSelection REGULAR bit'
* [   3 errors] 'Check if fontname is not camel cased.'
* [1160 errors] 'fontforge validation outputs error messages?'
* [ 124 errors] 'Font names are consistent across platforms?'
* [  47 errors] 'Monospace font has hhea.advanceWidthMax equal to each glyph's advanceWidth ?'
* [  86 errors] 'Metadata key-value match to table name fields?'
* [ 126 errors] 'Checking OS/2 fsType'
* [   1 errors] 'Checking that italicAngle <= 0'
* [ 117 errors] 'Version format is correct in NAME table?'
* [  57 errors] 'METADATA.pb 'filename' contains font name in right format ?'
* [   8 errors] 'Checking macStyle ITALIC bit'
* [ 402 errors] 'Check for points out of bounds'
* [  13 errors] 'Check font has a license'
* [ 246 errors] 'Fonts have equal glyph names?'
* [   1 errors] 'Fonts have equal unicode encodings?'
* [  16 errors] 'Checking fsSelection ITALIC bit'
* [1474 errors] 'Checking font version fields'
* [   4 errors] 'According GWF standards font should have Regular style.'
* [ 124 errors] 'METADATA.pb: Designer exists in GWF profiles.csv ?'
* [  74 errors] 'Font on disk and in METADATA.pb have the same family name ?'
* [ 437 errors] 'METADATA.pb 'fullName' matches 'postScriptName' ?'
* [ 617 errors] 'Checking OS/2 usWinAscent & usWinDescent'
* [1226 errors] 'Checking with pyfontaine'
* [   1 errors] 'Checking that italicAngle is less than 20 degrees'
* [   6 errors] 'Font has **proper** whitespace glyph names?'
* [ 657 errors] 'METADATA.pb subsets should be alphabetically ordered.'
* [  28 errors] 'METADATA.pb should contain at least 'menu' and 'latin' subsets.'
* [ 704 errors] 'Are there unwanted tables?'
* [ 181 errors] 'Does DESCRIPTION file contain broken links ?'
* [  24 errors] 'Copyright notice is the same in all fonts ?'
* [ 226 errors] 'Whitespace glyphs have ink?'
* [ 139 errors] 'Metadata weight matches postScriptName'
* [  64 errors] 'Checking if italicAngle matches font style'
* [  20 errors] 'Fonts have consistent underline thickness?'
* [ 649 errors] 'Font has a valid license url ?'
* [  41 errors] 'Checking OS/2 usWeightClass matches weight specified at METADATA.pb'
* [  51 errors] 'METADATA.pb: Fontfamily is listed in Google Font Directory ?'
* [ 782 errors] 'Digital Signature exists?'
* [  99 errors] 'Checking with ot-sanitise'
* [ 181 errors] 'Name table entries should not contain line-breaks'
* [  68 errors] 'METADATA.pb fonts 'name' property should be same as font familyname'
* [ 191 errors] 'Are there non-ASCII characters in ASCII-only NAME table entries ?'
* [ 654 errors] 'Copyright notice matches canonical pattern?'
* [  15 errors] 'METADATA.pb: Ensure designer simple short name.'
* [ 882 errors] 'Check if xAvgCharWidth is correct.'
* [  68 errors] 'METADATA.pb 'full_name' contains font name in right format ?'
* [ 156 errors] 'Font has post table version 2 ?'
* [ 245 errors] 'Font contains glyphs for whitespace characters?'
* [  81 errors] 'Checking fsSelection BOLD bit'
* [  85 errors] 'Checking OS/2 usWeightClass'
* [   3 errors] 'METADATA.pb font.style `normal` matches font internals?'
* [ 516 errors] 'Checking OS/2 achVendID'
* [ 133 errors] 'DESCRIPTION.en_us.html is less than 1000 bytes ?'
* [ 514 errors] 'Does GPOS table have kerning information?'
* [1048 errors] 'Font contains the first few mandatory glyphs (.null, CR, space)?'
* [ 123 errors] 'Font has 'EURO SIGN' character?'
* [ 103 errors] 'METADATA.pb font.style `italic` matches font internals?'
* [  97 errors] 'No glyph is incorrectly named?'
* [  97 errors] 'Font contains unique glyph names?'
* [  29 errors] 'METADATA.pb 'fullname' value matches internal 'fullname' ?'
* [ 598 errors] 'METADATA.pb lists fonts named canonicaly?'
* [  89 errors] 'substitute copyright, registered and trademark symbols in name table entries'
* [  72 errors] 'Checking macStyle BOLD bit'
* [ 134 errors] 'METADATA.pb 'filename' matches 'postScriptName' ?'
* [  12 errors] 'Filename is set canonically?'
* [ 297 errors] 'Description strings in the name table (nameID = 10) must not exceed 100 characters'
* [ 479 errors] 'Is GASP table correctly set?'
* [  10 errors] 'Does full font name begin with the font family name?'
* [  91 errors] 'DESCRIPTION.en_us.html is more than 200 bytes ?'
* [   8 errors] 'Fonts have consistent PANOSE family type?'
* [  33 errors] 'Checking unitsPerEm value is reasonable.'
* [  22 errors] 'Fonts have consistent PANOSE proportion?'
* [ 302 errors] 'Checking OS/2 Metrics match hhea Metrics'
* [   2 errors] 'METADATA.pb: check if fonts field only has unique 'full_name' values'
* [  59 errors] 'Checking if the font is truly monospaced'
* [  10 errors] 'Font styles are named canonically?'
* [ 638 errors] 'Check copyright namerecords match license file'
* [  19 errors] 'Checks METADATA.pb 'postScriptName' matches TTF 'postScriptName''
* [ 510 errors] 'Font contains magic code in 'prep' table?'
* [ 169 errors] 'Checking files are named canonically'
```

**Comment by felipesanches** [comment]
The same script can also explicitely list all files that have problems for each of the checks, but such list would bee too large to post here.

**Comment by felipesanches** [comment]
The automatically generated markdown looks like this, but it is way longer:

## Is this a propper HTML snippet ?
3 files with errors:
/home/felipe/devel/github_google/fonts/ofl/gfsdidot/DESCRIPTION.en_us.html
/home/felipe/devel/github_google/fonts/ofl/gfsneohellenic/DESCRIPTION.en_us.html
/home/felipe/devel/github_google/fonts/ofl/tenorsans/DESCRIPTION.en_us.html


## METADATA.pb 'name' contains font name in right format ?
68 files with errors:
/home/felipe/devel/github_google/fonts/ofl/cinzel/METADATA.pb
/home/felipe/devel/github_google/fonts/ofl/cantoraone/METADATA.pb
/home/felipe/devel/github_google/fonts/apache/robotomono/METADATA.pb
/home/felipe/devel/github_google/fonts/ofl/hindcolombo/METADATA.pb
/home/felipe/devel/github_google/fonts/ofl/ralewaydots/METADATA.pb
[...]

**Comment by felipesanches** [comment]
I have just published the full summarized report at https://gist.github.com/felipesanches/d0a0c47fd95b102c1b9a8808a5977cb1

**Comment by felipesanches** [comment]
@rsheeter is this useful info? Do you need the data to be presented in some other format ?

**Comment by davelab6** [comment]
@felipesanches good work :) Rod requested,

> Something like a csv of family, name field, # of problems (Roboto, 1, 0 or Roboto, fullname, 0 for Roboto with 0 fullname problems) would be ideal for my purposes. Or even just family, # name problems.

So, https://gist.github.com/felipesanches/d0a0c47fd95b102c1b9a8808a5977cb1#metadatapb-fullname-matches-postscriptname- shows 437 files with errors.

**Comment by davelab6** [comment]
Sorting this list is helpful; please add a sort to the default output. Eg,

* [1474 errors] 'Checking font version fields'
* [1226 errors] 'Checking with pyfontaine'
* [1160 errors] 'fontforge validation outputs error messages?'
* [1048 errors] 'Font contains the first few mandatory glyphs (.null, CR, space)?'
* [1011 errors] 'Assure valid format for the main entries in the name table.'
* [ 882 errors] 'Check if xAvgCharWidth is correct.'
* [ 782 errors] 'Digital Signature exists?'
* [ 704 errors] 'Are there unwanted tables?'
* [ 657 errors] 'METADATA.pb subsets should be alphabetically ordered.'
* [ 654 errors] 'Copyright notice matches canonical pattern?'
* [ 649 errors] 'Font has a valid license url ?'
* [ 638 errors] 'Check copyright namerecords match license file'
* [ 617 errors] 'Checking OS/2 usWinAscent & usWinDescent'
* [ 598 errors] 'METADATA.pb lists fonts named canonicaly?'
* [ 516 errors] 'Checking OS/2 achVendID'
* [ 514 errors] 'Does GPOS table have kerning information?'
* [ 510 errors] 'Font contains magic code in 'prep' table?'
* [ 479 errors] 'Is GASP table correctly set?'
* [ 471 errors] 'Copyright notice does not contain Reserved Font Name'
* [ 437 errors] 'METADATA.pb 'fullName' matches 'postScriptName' ?'
* [ 402 errors] 'Check for points out of bounds'
* [ 302 errors] 'Checking OS/2 Metrics match hhea Metrics'
* [ 297 errors] 'Description strings in the name table (nameID = 10) must not exceed 100 characters'
* [ 246 errors] 'Fonts have equal glyph names?'
* [ 245 errors] 'Font contains glyphs for whitespace characters?'
* [ 226 errors] 'Whitespace glyphs have ink?'
* [ 191 errors] 'Are there non-ASCII characters in ASCII-only NAME table entries ?'
* [ 183 errors] 'Checking fsSelection REGULAR bit'
* [ 181 errors] 'Name table entries should not contain line-breaks'
* [ 181 errors] 'Does DESCRIPTION file contain broken links ?'
* [ 169 errors] 'Checking files are named canonically'
* [ 156 errors] 'Font has post table version 2 ?'
* [ 139 errors] 'Metadata weight matches postScriptName'
* [ 134 errors] 'METADATA.pb 'filename' matches 'postScriptName' ?'
* [ 133 errors] 'DESCRIPTION.en_us.html is less than 1000 bytes ?'
* [ 126 errors] 'Checking OS/2 fsType'
* [ 124 errors] 'METADATA.pb: Designer exists in GWF profiles.csv ?'
* [ 124 errors] 'Font names are consistent across platforms?'
* [ 123 errors] 'Font has 'EURO SIGN' character?'
* [ 120 errors] 'Description strings in the name table (nameID = 10) must not contain copyright info.'
* [ 117 errors] 'Version format is correct in NAME table?'
* [ 103 errors] 'METADATA.pb font.style `italic` matches font internals?'
* [ 103 errors] 'Glyph names are all valid?'
* [ 101 errors] 'Fonts have equal numbers of glyphs?'
* [  99 errors] 'Checking with ot-sanitise'
* [  97 errors] 'No glyph is incorrectly named?'
* [  97 errors] 'Font contains unique glyph names?'
* [  91 errors] 'Whitespace glyphs have coherent widths?'
* [  91 errors] 'DESCRIPTION.en_us.html is more than 200 bytes ?'
* [  89 errors] 'substitute copyright, registered and trademark symbols in name table entries'
* [  86 errors] 'Metadata key-value match to table name fields?'
* [  85 errors] 'Checking OS/2 usWeightClass'
* [  81 errors] 'Checking fsSelection BOLD bit'
* [  74 errors] 'Font on disk and in METADATA.pb have the same family name ?'
* [  72 errors] 'Checking macStyle BOLD bit'
* [  68 errors] 'METADATA.pb fonts 'name' property should be same as font familyname'
* [  68 errors] 'METADATA.pb 'name' contains font name in right format ?'
* [  68 errors] 'METADATA.pb 'full_name' contains font name in right format ?'
* [  64 errors] 'Checking if italicAngle matches font style'
* [  61 errors] 'Font has old ttfautohint applied?'
* [  59 errors] 'Checking if the font is truly monospaced'
* [  57 errors] 'METADATA.pb 'filename' contains font name in right format ?'
* [  51 errors] 'METADATA.pb: Fontfamily is listed in Google Font Directory ?'
* [  51 errors] 'METADATA.pb 'postScriptName' contains font name in right format ?'
* [  47 errors] 'Monospace font has hhea.advanceWidthMax equal to each glyph's advanceWidth ?'
* [  41 errors] 'Checking OS/2 usWeightClass matches weight specified at METADATA.pb'
* [  33 errors] 'Checking unitsPerEm value is reasonable.'
* [  29 errors] 'METADATA.pb 'fullname' value matches internal 'fullname' ?'
* [  28 errors] 'METADATA.pb should contain at least 'menu' and 'latin' subsets.'
* [  24 errors] 'Copyright notice is the same in all fonts ?'
* [  22 errors] 'Fonts have consistent PANOSE proportion?'
* [  20 errors] 'Fonts have consistent underline thickness?'
* [  19 errors] 'Checks METADATA.pb 'postScriptName' matches TTF 'postScriptName''
* [  16 errors] 'Checking fsSelection ITALIC bit'
* [  15 errors] 'METADATA.pb: Ensure designer simple short name.'
* [  13 errors] 'Check font has a license'
* [  12 errors] 'Filename is set canonically?'
* [  10 errors] 'Font styles are named canonically?'
* [  10 errors] 'Does full font name begin with the font family name?'
* [   8 errors] 'Fonts have consistent PANOSE family type?'
* [   8 errors] 'Checking macStyle ITALIC bit'
* [   6 errors] 'Font has **proper** whitespace glyph names?'
* [   4 errors] 'According GWF standards font should have Regular style.'
* [   3 errors] 'METADATA.pb font.style `normal` matches font internals?'
* [   3 errors] 'Is this a propper HTML snippet ?'
* [   3 errors] 'Check if fontname is not camel cased.'
* [   2 errors] 'METADATA.pb: check if fonts field only has unique 'full_name' values'
* [   1 errors] 'Fonts have equal unicode encodings?'
* [   1 errors] 'Checking that italicAngle is less than 20 degrees'
* [   1 errors] 'Checking that italicAngle <= 0'

cc @m4rc1e to ruin his weekend ;p

**Comment by felipesanches** [comment]
What's the current plan to bring these thousands of errors to zero?
I hope you're not simply hotfixing TTFs on the repo, right?

**Comment by felipesanches** [comment]
FYI: If you want to generate this list yourself, you have to have a full checkout of the Google Fonts git repo, and then you can run:

```
sh test_all_gfonts.sh 
```
(you'll probably have to edit the first 3 lines in the test_all_gfonts.sh script though, as for now the gfonts repo path is hardcoded in there. I may later make it into a command line parameter)

This will create a folder called check_results and it will run fontbakery on every family from the gfonts git repo, thus generating individual per-font-file reports both in json and in ghmarkdown format. The reports are saved in subdirectories that have names of the families.

It took me 80 minutes to run the full test on the repo. And the resulting check_results folder has got 105Mbytes of json & md files :-P

To squeeze it all into a unified report you can run:

```
./fb_summary_report.py
```

and it will write to stdout.

If you rather preffer to save it to a file you can do something like:

```
./fb_summary_report.py > gfonts_check_summary.md
```

**Comment by felipesanches** [comment]
These scripts are avaiable on the current master branch of fontbakery git repo:

* test_all_gfonts.sh
* fb_summary_report.py
