### ISSUE TITLE
ttfautohint --dehint bails out with "This font has already been processed with ttfautohint."

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1045]
The message is logged by fontbakery, but it does not seem intuitive for the users. We need to figure out what it means and provide a better log message.

As of today, the issue affects 27 font files from the google fonts git repo.

See also:
* Issue #1043 
* https://github.com/googlefonts/fontbakery/issues/1035#issuecomment-249042982

**Comment by davelab6** [comment]
Why is fontbakery running tttfa --dehint?

**Comment by felipesanches** [comment]
It is used to infer the dehinted size and compare it with the hinted size

**Comment by felipesanches** [comment]
This is done on the "Show hinting filesize impact" check here:

https://github.com/googlefonts/fontbakery/blob/84742534b83ba06d5317ae1052ed62922c344db8/fontbakery-check-ttf.py#L2336

**Comment by davelab6** [comment]
Ah yes, right, cool.

**Comment by davelab6** [comment]
> The message is logged by fontbakery, but it does not seem intuitive for the users. We need to figure out what it means and provide a better log message.

@lemzwerg please comment

**Comment by felipesanches** [comment]
In other words, why can't I dehint a previously hinted font? And why do I get instead a message telling me that it the font "has already been processed" ?

**Comment by lemzwerg** [comment]
It's a bug, now fixed in the git repository of ttfautohint.

**Comment by felipesanches** [comment]
great! thanks!
