### ISSUE TITLE
Improving the output

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1071]
I want to follow up on @alexeiva 's comment on the gfd mailing list... 

@alexeiva could you attach the file you tested to this issue, to reproduce?

> ERROR    fsType is zero. Changes that must be applied to this font: OS/2 fsType from 1 to 0  

If fsType is zero, then why does it ask to change fsType from 1 to 0? lol

> ERROR    No license file was found. Please add an OFL.txt or a LICENSE.txt file.  
> ERROR    Valid licensing specified on NameID 13 (LICENSE DESCRIPTION) on platform 1 > (MACINTOSH) but a corresponding "OFL.txt" file was not found.  
> ERROR    Valid licensing specified on NameID 13 (LICENSE DESCRIPTION) on platform 3 > (WINDOWS) but a corresponding "OFL.txt" file was not found.  

The 2nd and 3rd errors are duplicative; I would make those 2 'INFO' level, because nothing is really wrong with NameIDs 13, and the real error is reported by itself.

> ERROR    fontforge did print these messages to stderr:
> The following table(s) in the font have been ignored by FontForge
>  Ignoring 'DSIG' digital signature table
  
Yeah, this is noisy... When we capture the output from FontForge, we should strip ` Ignoring 'DSIG' digital signature table` and then if there are no other tables, we should strip the first line too; and then evaluate if there was any "valid" printed messages, and if none, don't print this error. 

> ERROR    failed to parse font version entries in the name table.  

That seems serious, and mysterious! Isn't it a duplicate of the next message though, which is more informative?

> ERROR    Could not find any font versioning info on the head table or in the name table entries.  

OK, if this is true, its an error. Is it true?

> ERROR    Font is missing the following mandatory glyphs: .null (0x0000).  

Is this true? 

> ERROR    Font is missing the GASP table.  

OK, if this is true, its an error.  Is it true?

> ERROR    Failed to find correct magic code in 'prep' table.  

Well, if the font is not ttfautohinted, then this is an error. But is it TA'd?

> ERROR    Glyph 'uni0412' coordinates (447,703) out of bounds!  
> ERROR    Glyph 'uni0419' coordinates (316,927) out of bounds!  
> ERROR    Glyph 'uni0419' coordinates (516,927) out of bounds!  
> ERROR    Glyph 'uni0420' coordinates (469,703) out of bounds!  
> ERROR    Glyph 'Rcommaaccent' coordinates (471,703) out of bounds!  
> ERROR    Glyph 'uni04DB' coordinates (41,102) out of bounds!  
> ERROR    Glyph 'uni040E' coordinates (216,927) out of bounds!  
> ERROR    Glyph 'uni040E' coordinates (416,927) out of bounds!  

Is this true? 

> ERROR    Lora-Bold.ttf is missing a METADATA.pb file!  

OK, if this is true, its an error.  Is it true?

**Comment by davelab6** [comment]
I checked Alexei's email - https://groups.google.com/d/msg/googlefonts-discuss/OIBrUNekQlo/8xSE51MUBQAJ - and he is now in transit the rest of this week, so we won't hear from him until Monday.

The files for reproduction are at https://github.com/cyrealtype/Lora-Cyrillic/tree/master/fonts

**Comment by m4rc1e** [comment]
> If fsType is zero, then why does it ask to change fsType from 1 to 0? lol

This is a terrible bug we have in Glyphsapp. My script will set the font.customParameter['fsType'] = 0. However, it will export the font with 1 instead. I need to mention this on the glyhsapp forum. if you manually change this field by hand, it will be 0.

> ERROR Font is missing the following mandatory glyphs: .null (0x0000).

Glyphsapp exports this glyph with the name NULL. Both names are apparently fine.


> ERROR No license file was found. Please add an OFL.txt or a LICENSE.txt file.

FB needs to have the OFL.txt and the METADATA.pb in the same folder as the font files. I'm guessing this tool was made for checking these types of folders. 
![screen shot 2016-09-29 at 19 44 51](https://cloud.githubusercontent.com/assets/7525512/18965376/3bdee7e4-867d-11e6-8b11-1f7036f2d1d4.png)

Alexei is trying to use this tool on an upstream repo, which is fine. He just needs to make sure there is a temporary ofl and metadata file in there.

> ERROR Glyph 'uni0412' coordinates (447,703) out of bounds!

The out of bounds error occurs when points are not extremes. This happens a lot on the italics. Often placing points on extremes in the Italics does more harm than good, especially with rounded fonts.

> ERROR Failed to find correct magic code in 'prep' table.
That prep table error should be gone in the latest release. If he is still getting it, he is not exporting the fonts with autohinting
![screen shot 2016-09-29 at 19 47 42](https://cloud.githubusercontent.com/assets/7525512/18965453/9c6229be-867d-11e6-90ac-aa0c7f5f586f.png)
Glyphsapp uses ttfautohint. Enabling this option will also clear
> ERROR Font is missing the GASP table.

Hope that helps.

There are many false positives here. I'll try and create separate issues for each one. My fonts now have around 6 errors from FB which are false positives ;)

Cheers,
Marc

**Comment by felipesanches** [comment]
>> ERROR    fsType is zero. Changes that must be applied to this font: OS/2 fsType from 1 to 0  
>If fsType is zero, then why does it ask to change fsType from 1 to 0? lol

I think the original meaning of the string was: "**check** if fsType is zero" / "**assert that** fsType is zero"

I can rephase it as "The value of fsType must be zero."

**Comment by davelab6** [comment]
Felipe wrote, 

> I can rephase it as "The value of fsType must be zero."

Yes, please do :)

Marc wrote,

> > If fsType is zero, then why does it ask to change fsType from 1 to 0? lol
> 
> This is a terrible bug we have in Glyphsa

lol

> I need to mention this on the glyhsapp forum

Done, https://forum.glyphsapp.com/t/fstype-ui-confusing/4524/2

> > ERROR Font is missing the following mandatory glyphs: .null (0x0000).
> 
> Glyphsapp exports this glyph with the name NULL. Both names are apparently fine.

@felipesanches please add this to the list of acceptable glyph names :)
 
> Alexei is trying to use this tool on an upstream repo, which is fine. He just needs to make sure there is a temporary ofl and metadata file in there.

@felipesanches The error message should say this. 
 
> > ERROR Glyph 'uni0412' coordinates (447,703) out of bounds!
> 
> The out of bounds error occurs when points are not extremes. This happens a lot on the italics. Often placing points on extremes in the Italics does more harm than good, especially with rounded fonts.

@felipesanches please adjust this check to be a warning if the font is italic. 

> > ERROR Failed to find correct magic code in 'prep' table.
> 
> That prep table error should be gone in the latest release. 

Cool

> If he is still getting it, he is not exporting the fonts with autohinting, like this:
> 
> ![screen shot 2016-09-29 at 19 47 42](https://cloud.githubusercontent.com/assets/7525512/18965453/9c6229be-867d-11e6-90ac-aa0c7f5f586f.png)

@felipesanches The error message should say this. 

> > ERROR Font is missing the GASP table.
> 
> Glyphsapp uses ttfautohint. Enabling this option will also clear the above.

@felipesanches The error message should say this. 

> Hope that helps.

Thanks Marc!

> There are many false positives here. I'll try and create separate issues for each one. My fonts now have around 6 errors from FB which are false positives ;)

Thanks!

**Comment by davelab6** [comment]
@m4rc1e please use 

    Font.customParameters['fsType'] = []

**Comment by felipesanches** [comment]
>>> ERROR Font is missing the following mandatory glyphs: .null (0x0000).
>> Glyphsapp exports this glyph with the name NULL. Both names are apparently fine.
>@felipesanches please add this to the list of acceptable glyph names :)

Well... fontbakery looks for the glyph by its codepoint value. The .null in the error message is merely cosmetic. I can print something like: "glyphs missing: .null or NULL (0x0000)" and it doesn't change the fact that a glyph for the 0x0000 codepoint was not found by the check.

**Comment by khaledhosny** [comment]
If what is missing is a glyph for a certain code point, then the error
should just mention the code point (preferably using U+XXXX syntax), the
glyph name is irrelevant and even misreading.

**Comment by alexeiva** [comment]
so, 

[x] setting `fsType` via Marc's script on `version 2.4b (925)` — works
[x] `NULL` via  Marc's script on `version 2.4b (925)` — works

Generating a new `NULL` glyph in Glyphs App produces the same fb error because it does not have a `0000` unicode assigned.

Setting a custom `fstype` parameter manually in fontinfo to `installable` also doesn't pass fb because of a Glyphs bug.

**Comment by davelab6** [comment]
> If what is missing is a glyph for a certain code point, then the error should just mention the code point (preferably using U+XXXX syntax), the glyph name is irrelevant and even misreading.

I agree. @felipesanches please adjust

**Comment by davelab6** [comment]
> Generating a new NULL glyph in Glyphs App produces the same fb error because it does not have a 0000 unicode assigned.

Then that's user error, if the user has to assign it. 

> Setting a custom fstype parameter manually in fontinfo to installable also doesn't pass fb because of a Glyphs bug.

Could you tell me more about that?

**Comment by alexeiva** [comment]
1. Add a new custom Parameter like this:

<img width="310" alt="screen shot 2016-10-03 at 14 11 36" src="https://cloud.githubusercontent.com/assets/16634089/19048205/575eb6e0-8973-11e6-8be1-ca319ff7c03b.png">

Produces this result `New Parameter`

<img width="1117" alt="screen shot 2016-10-03 at 14 15 38" src="https://cloud.githubusercontent.com/assets/16634089/19048331/e9be4eba-8973-11e6-8159-b431d41c9f49.png">

The Workaround is to set `fstype` to any other value, i.e. `editable`, and then set back to `un set`. 
<img width="309" alt="screen shot 2016-10-03 at 14 23 28" src="https://cloud.githubusercontent.com/assets/16634089/19048587/fa136d4e-8974-11e6-878a-20c9b63fc0ed.png">

Then it will work properly:

<img width="250" alt="screen shot 2016-10-03 at 14 16 55" src="https://cloud.githubusercontent.com/assets/16634089/19048385/14d81018-8974-11e6-841c-712540ef35c9.png">

This sucks!

**Comment by felipesanches** [comment]
OK. I have just finished addressing all issues pointed out in this discussion.
