### ISSUE TITLE
Fontbakery error: Designer {NAME} is not listed in profiles.csv

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#1072]
This is for the font "VT323". I don't know if Mr. Hull has a G+ profile at all.

```
ERROR    METADATA.pb: Designer 'Peter Hull' is not listed in profiles.csv (at 'https://github.com/google/fonts/blob/master/designers/profiles.csv')  
```

Maybe this should rather be a warning?

**Comment by davelab6** [comment]
Hmm. Well, fonts.google.com doesn't link to G+ in the same way that google.com/fonts did, so this check can be commented out (as a similar check will be needed in future.)

**Comment by davelab6** [comment]
Warning is good.
