### ISSUE TITLE
Updating name check

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1073]
Per https://github.com/googlefonts/gf-docs/issues/9 update the name check to only prevent the first char of a family name from being a digit

**Comment by felipesanches** [comment]
@davelab6 I can't seem to find an check that validates family names based on the presence of digits at all. There's such kind of test for glyph names already.

Maybe I'm missing it. But then you're suggesting that we should add a new check for that kind of validation if there's still none?

**Comment by davelab6** [comment]
Yes; this should be checked for. I thought you went over the checklist doc and made checks for all those requirements. If you didn't, please do.

**Comment by felipesanches** [comment]
Is there any font that fails this test? I guess not. Then this test is only a safety net just in case an invalid familyname shows up in the future, right?

**Comment by davelab6** [comment]
> Is there any font that fails this test? I guess not. Then this test is only a safety net just in case an invalid familyname shows up in the future, right?

Yes
