### ISSUE TITLE
CamelCase Name rule doesn't like  "VT323"

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#1075]
Here is a stripped output of fontbakery for "VT323 Regular". Fontbakery doesn't like its CamelCase name:

```
ERROR    [FONT_FAMILY_NAME(1):MACINTOSH(1)] entry: expected 'V T323' but got 'VT323'  
ERROR    [FULL_FONT_NAME(4):MACINTOSH(1)] entry: expected 'V T323 Regular' but got 'VT323 Regular'  
ERROR    [FONT_FAMILY_NAME(1):WINDOWS(3)] entry: expected 'V T323' but got 'VT323'  
ERROR    [FULL_FONT_NAME(4):WINDOWS(3)] entry: expected 'V T323 Regular' but got 'VT323 Regular
```
This is a tough one ;-) We could allow consecutive uppercase letters to stick together, but that may lead to that we'd have more than one possible/expected form.

**Comment by davelab6** [comment]
Whitelist.

**Comment by graphicore** [comment]
> Whitelist. 

I didn't find an explicit whitelist.



This is a minimal and a bit crude way, but it helps:

```py
    def family_with_spaces(value):
      FAMILY_WITH_SPACES_EXCEPTIONS = {'VT323': 'VT323'}
      if value in FAMILY_WITH_SPACES_EXCEPTIONS :
        return FAMILY_WITH_SPACES_EXCEPTIONS [value]
      result = ''
      for c in value:
        if c.isupper():
          result += " "
        result += c
      return result.strip()
```

I inserted the three lines that contain `FAMILY_WITH_SPACES_EXCEPTIONS`.

That dict could be global.

It also could ne organized diferently, e.g. we could have something like:

```py
GLOBAL_EXCEPTIONS = {
  "function_name": {
    (function, specific, key): "return value"
  },
  "family_with_spaces": {
        "VT323" "VT323"
  }
}
```
Then come up with a decorator:

```py
@has_exception(key_function)
def family_with_spaces(value):
      result = ''
      for c in value:
        if c.isupper():
          result += " "
        result += c
      return result.strip()
```

But maybe that's overengineering?

**Comment by felipesanches** [comment]
yeah... at this point I think it is overengineering. I'll stick to the simple whitelist solution for now. If more similar issues pop up then we may consider other approaches, but for now I think that's pretty much enough for handling the issue.
