### ISSUE TITLE
Allow zero width glyphs in monospaced fonts

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#1076]
The error is:

```
ERROR    This is a monospaced font, so advanceWidth value should be the same across all glyphs, but 5.79 % of them have a different value. 
```
PR follows.

**Comment by felipesanches** [comment]
@davelab6 said:

> I think that we should be pessimistic, so the current code is - I think - what I want.
>
> We should make a note in the output that, if there are are non-$width glyphs, they should use set
> the glyphs that should be zero-width and 2x-$width to $width, then add a GPOS single pos lookups
> that zeros/doubles the widths. And we could even have an autofix for that, but its in the future
> (milestone v2.0.0)

Full discussion happened at https://github.com/googlefonts/fontbakery/pull/1077

**Comment by davelab6** [comment]
@felipesanches did you make a note in the output? When done then I suggest to close this

**Comment by davelab6** [comment]
@felipesanches did you make a note in the output? When done then I suggest to close this
