### ISSUE TITLE
deva-stats script is broken due to GWF website changes

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1081]
Google Web fonts website changed (probably a long time ago) and our implementation of the deva-stats script does not work anymore. We need to figure out where the info is made available within the website nowadays and use that info to fix the implementation of this script.

**Comment by felipesanches** [comment]
@davelab6 Is this script still important / useful / in use ?

There are two possible fixes:

* (1) drop it because it is not needed anymore
* (2) update/fix it because it is still needed & useful

**Comment by davelab6** [comment]
Drop it.
