### ISSUE TITLE
ERROR    Fonts have different glyph names

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1088]
Hello,

I keep getting the error message in check-ttfs, when I run multiple fonts together.

Run FB on this repo. [https://github.com/m4rc1e/Maven-Pro](https://github.com/m4rc1e/Maven-Pro)

I have my own glyphsapp script to check if [fonts contain different names and glyph counts](https://github.com/m4rc1e/mf-glyphs-scripts/blob/master/QA/test_missing_glyphs_across_fonts.py)

I get the following output:

Name: Regular, Glyphs: 722
Name: Medium, Glyphs: 722
Name: Black, Glyphs: 722
Name: Bold, Glyphs: 722
Regular - Regular set([])
Regular - Black set([])
Regular - Medium set([])
Regular - Bold set([])
Black - Regular set([])
Black - Black set([])
Black - Medium set([])
Black - Bold set([])
Medium - Regular set([])
Medium - Black set([])
Medium - Medium set([])
Medium - Bold set([])
Bold - Regular set([])
Bold - Black set([])
Bold - Medium set([])
Bold - Bold set([])

It seems the fonts share the same names and have the same glyph counts.

I'm terribly sorry I can't look deeper into this. I need to be on the autobahn releasing fonts.

Cheers,
Marc

**Comment by felipesanches** [comment]
@m4rc1e No worries. I'll take care of this. Thanks for reporting.

**Comment by felipesanches** [comment]
@m4rc1e Fontbakery only runs this check when a METADATA.pb file is found. There's no METADATA.pb in the fonts folder at your repo. Do you keep a copy of this file into the fonts dir only on your local working copy ?

**Comment by m4rc1e** [comment]
There's a METADATA.pb file in this repo.

You have to create a temp folder which replicate the [fonts/ofl structure](https://github.com/google/fonts/tree/master/ofl/mavenpro) for each family.

**Comment by felipesanches** [comment]
sure!

I think I fixed the problem. I'll commit it and then ask for your feedback in 5 minutes

**Comment by felipesanches** [comment]
ok. I merged this since it fixes the issue at my local working copy.
