### ISSUE TITLE
Some name table entries are supposed to be different between platforms.

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#1089]
```
ERROR    Entries in "name" table are not the same across specific platforms. 
```

This error could indicate problem but it is not an error. Some of the entries in the name table are expected to differ between platforms. 

Maybe make it a warning?

**Comment by khaledhosny** [comment]
There shouldn't be any differences between platforms AFAIK, or better yet just include name entries for Windows platform and Unicode encoding, nothing else should be needed.

**Comment by davelab6** [comment]
@graphicore the name table checks in FB should not be trusted, as they are pending my review of https://github.com/davelab6/glyphs-export/pull/1/files

**Comment by graphicore** [comment]
So how does it come that we can observe differences in files created by existing tools. In this case from Glyphs, which is used by many people.
These differences are also described here: https://docs.google.com/spreadsheets/d/1ckHigO7kRxbm9ZGVQwJ6QJG_HjV_l_IRWJ_xeWnTSBg/edit#gid=0 But I'm not sure if the sheet is up to date, just look at the name id 2. It describes what Glyphs exports.

My case, standard Glyphs export:

```
    <namerecord nameID="2" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Black
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Regular
    </namerecord>
```

**Comment by graphicore** [comment]
@davelab6 I'm not trusting it, just pointing at an issue.

**Comment by davelab6** [comment]
> There shouldn't be any differences between platforms AFAIK, 

There should - the Mac platform IDs 1 and 2 are different, and 16 and 17 aren't needed (but 18 may be.)

> or better yet just include name entries for Windows platform and Unicode encoding, nothing else should be needed.

This prevents the fonts from working for older but still widely used versions of Word for Mac.

**Comment by davelab6** [comment]
> My case, standard Glyphs export

Looks correct

**Comment by khaledhosny** [comment]
OK, those versions of Word on Mac never supported Arabic (and I guess other complex scripts) so I’m happily ignoring them, but I see others might not have this luxury. Still I don’t see why name id 2 has to be different.

**Comment by davelab6** [comment]
> why name id 2 has to be different

Windows GDI only supports 4 styles per family (RIBBI) but Mac supports many styles per family.

**Comment by khaledhosny** [comment]
This answers why you need name id 2 and name id 17 for Windows platform, but why not do the same for Mac platform even if not required, what harm would it cause, and are you sure those ancient Word versions don’t have the same limitation as GDI even on Mac?

**Comment by davelab6** [comment]
> why not do the same for Mac platform even if not required

Ideally users have more styles within less families

**Comment by felipesanches** [comment]
The check is pretty straightforward.

For each nameid, it expects that corresponding plat=Windows/lang=English_USA and plat=Mac/lang=Mac_english entries are all identical strings.

If that's not a reasonable thing to expect (as Lasse pointed out and Dave seem to have agreed), then this check should be dropped.

**Comment by felipesanches** [comment]
This is the check implementation:

https://github.com/googlefonts/fontbakery/blob/916659094da5b34d4535d532ed9efcd071352bbd/fontbakery-check-ttf.py#L2873-L2899
