### ISSUE TITLE
ERROR Glyph 'XXXX' coordinates (x,x) out of bounds!

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1099]
Hey,

Could we change this test to a WARNING message instead?

I'm dealing with handwritten fonts at the moment. It is nigh on impossible to get everything on extremes.

Cheers,
Marc

**Comment by felipesanches** [comment]
We made this into a Warning just when the style is Italic for a similar reason.
Should we make it a Warning unconditionally, @davelab6 ?
