### ISSUE TITLE
Remove --skip?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1105]
Could the `--skip` switch be automatic? Eg if there isn't a METADATA file, then make an warning and skip the related checks; and if there isn't a OFL file, then make a warning and skip related checks?

(Reference https://groups.google.com/d/msg/googlefonts-discuss/OIBrUNekQlo/w7JnJrsrBQAJ)

**Comment by felipesanches** [comment]
yes, it can.

The --skip switch skips all METADATA.pb checks but it also skips the "Is font em size (ideally) equal to 1000?" check, which does not deal with the protobuf file, but is GoogleFonts-specific.
