### ISSUE TITLE
error: can't copy 'data/test/merriweather/Merriweather-Black.ttx': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by alexeiva** [googlefonts/fontbakery#1115]
## Expected behaviour

I want to update fontbakery to latest

## Observed behaviour

[Full output](https://gist.github.com/alexeiva/6d394a4f220b723686fb2f2947654910)

```
error: can't copy 'data/test/merriweather/Merriweather-Black.ttx': doesn't exist or not a regular file
```

```
 Rolling back uninstall of fontbakery
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-n6k_Oh-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-VfgLTk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-n6k_Oh-build/
```

## How to replicate

`sudo -H pip install --upgrade git+https://github.com/googlefonts/fontbakery.git`

**Comment by alexeiva** [comment]
It works if I just pull the git repo instead of `install --upgrade` command.

**Comment by felipesanches** [comment]
ok, I can fix that. It seems that I mistakenly placed a TTX file in the setup.py file. I'll fix it right now.

**Comment by felipesanches** [comment]
OK. I just did it.

@alexeiva Can you please confirm that it is fixed now?

**Comment by alexeiva** [comment]
@felipesanches works now. Thank you!

**Comment by felipesanches** [comment]
you're welcome :-)
