### ISSUE TITLE
Checks that are not specific to a single fontfile should be logged in a separate family-wide report

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1116]
## Expected behaviour

There are some checks that are performed to validate that all fonts in a family have coherent metadata among them.

Examples of such checks are:
- "version info differs among font files of the same font project"
- "All files are in the same directory"
## Observed behaviour

These checks are currently being saved to the first fontfile check results report. They should be saved separately instead.
## How to replicate

Run fontbakery on any given set of font files belonging to a single family.

**Comment by davelab6** [comment]
Merging into #971
