### ISSUE TITLE
GASP table error - false positive

### ISSUE THREAD

**Issue by alexeiva** [googlefonts/fontbakery#1118]
## Expected behaviour

TTFs were exported from Glyphs Version 2.4b (926) with `ttfautohint` flag on. 
GASP table should be fine.

## Observed behaviour

```
ERROR    Font is missing the GASP table. Try exporting the font with autohinting enabled.  
```

I ran fix-GASP script, with the same result.

## How to replicate

Run fontbakery-check.ttf on TTFs here:
https://github.com/cyrealtype/Lora-Cyrillic/commit/001df291f4659a4ef67d90016489b9e70585740b

**Comment by felipesanches** [comment]
@alexeiva Try exporting the font with autohinting enabled. :-)

There's another thread in the issue tracker where this was explained. I'll try to find it. But the quick way to fix it is to mark a checkbox in the Glyphs settings to enable autohinting and then exporting the font.

**Comment by felipesanches** [comment]
Here's the comment from @m4rc1e : https://github.com/googlefonts/fontbakery/issues/1071#issuecomment-250544300

**Comment by alexeiva** [comment]
> Try
 exporting the font with autohinting enabled. :-)

TTFs were exported from Glyphs Version 2.4b (926) **with** ttfautohint flag on. 

@m4rc1e is stating that checking the ✓ ttfautohint in Glyphs will solve this.
> ERROR Font is missing the GASP table.
> Glyphsapp uses ttfautohint. Enabling this option will also clear the above.

But is currently doesn't

**Comment by felipesanches** [comment]
hmmm... maybe @m4rc1e or @schriftgestalt could help with Glyphs

**Comment by schriftgestalt** [comment]
The autohinting is deliberately disabled in the instances. So the checkbox in the export dialog is overwritten by a custom parameter. But the font has a GASP table, if I export it.

**Comment by felipesanches** [comment]
@alexeiva I'm closing this based on your comment on the googlefonts-discuss mailing list:
https://groups.google.com/d/msg/googlefonts-discuss/OIBrUNekQlo/ds_HS6tcCQAJ

**Comment by alexeiva** [comment]
That discussion isn't related to GASP. 

But please do close this. 
The error was on my part. I had this unchecked in instances, and kept thinking why does ttfautohinting does not work

![screen shot 2016-10-12 at 15 32 45](https://cloud.githubusercontent.com/assets/16634089/19330158/9a7c3342-9091-11e6-96c7-ce9f9680f4da.png)
