### ISSUE TITLE
check-ttf.py: ERROR    [FONT_FAMILY_NAME(1):MACINTOSH(1)] entry: expected 'Amatic S C' but got 'Amatic SC'

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1120]
## Expected behaviour

FB output:
PASS    [FONT_FAMILY_NAME(1):MACINTOSH(1)] entry: got 'Amatic SC'

## Observed behaviour

FB output:
ERROR    [FONT_FAMILY_NAME(1):MACINTOSH(1)] entry: expected 'Amatic S C' but got 'Amatic SC'

## How to replicate

I ran fontbakery-check-ttf.py on fonts/ofl/amaticsc on my [custom](https://github.com/m4rc1e/fonts/tree/amaticsc) branch

**Amatic SC** is the correct family name. I'm guessing this is a regex issue. Sorry I can't look into this. I will have more availability in a week or two.

@vmesel Thank you for this rather swish md template. I like it a lot!

**Comment by graphicore** [comment]
related: https://github.com/googlefonts/fontbakery/issues/1075

**Comment by felipesanches** [comment]
I would deal with it by adding exceptions for "Amatic SC" and "Press Start 2P" just like we did for "VT323".

**Comment by felipesanches** [comment]
No. This was not a good fix, sorry.

**Comment by felipesanches** [comment]
alright! :)
