### ISSUE TITLE
Simple Web App UI

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1121]
## Expected behaviour

Many font designers feel uncomfortable using a command line, and expect a drag and drop web app, similar to https://github.com/graphicore/nametableswapper

## Observed behaviour

Font Bakery has a command line interface. 

## How to replicate

Using nametableswapper as a model, make an appengine web app UI for fontbakery, such that:

1. a user visits the page and drops the files to check
2. user hits the 'go' button
3. fonts are uploaded to the server, and fb is run on them
4. the output is shown to the user

The first 3 items seem very close to what Lasse has done already; for 4, to start, just printing the MarkDown output as HTML will be sufficient.

**Comment by davelab6** [comment]
Felipe wrote me, 

> Initially I have put aside for a while the in-memory handling of TTFs
> and tried to hookup fontbakery to the webapp via bad temp files to get
> an initial working prototype. But then I figured that filesystem
> operations are not only discouraged (as I had already hinted at) but
> actually forbidden on Google App Engine for security (and maybe also
> performance) reasons.
>
> So I did all the tweaks necessary to optionally pass
> TTFont(BytesIO(stream)) objects to the check_ttf function.

Great!
 
> Then I found a few other restrictions imposed by GAppEngine. For
> instance, subprocess.Popen can't be used, so this makes all auxiliary
> tools unavailable on the webapp such as ttfautohint, ftxvalidator and
> other tools that we typically invoke as a subprocess. For now I simply
> skip these when I detect we're running in webapp mode,

Sounds good

> but I really wish there's some workaround to this restriction.

That's fine, I think: lets plan to set up a container based version of the web app with everything (except ftxval which is os x only)

> Another issue with the GAppEngine environment is that it does not
> support ctypes so I also had to disable the check that relies on the
> libmagic module (which depends on ctypes).

Cool - that's not a very important check :)

**Comment by graphicore** [comment]
What's with the "App Engine Flexible Environment" https://cloud.google.com/appengine/docs/flexible/ It seems to me it can do all those thing, as they say you can somehow supply your own docker image.
