### ISSUE TITLE
Numbers in font name

### ISSUE THREAD

**Issue by alexeiva** [googlefonts/fontbakery#1122]
Original issue on project git: https://github.com/codeman38/PressStart2P/issues/2

I know numbers are not good in font names, but Press Start 2P is an active GF font, and it validates fine in font book.

I think font-bakery has some bug in reading the name. Compare this output to the name table:

fontbakery-check-ttf.py error output:

```
ERROR    [FONT_FAMILY_NAME(1):MACINTOSH(1)] entry: expected 'Press Start2 P' but got 'Press Start 2P'  
ERROR    [FULL_FONT_NAME(4):MACINTOSH(1)] entry: expected 'Press Start2 P Regular' but got 'Press Start 2P Regular'  
ERROR    [FONT_FAMILY_NAME(1):WINDOWS(3)] entry: expected 'Press Start2 P' but got 'Press Start 2P'  
ERROR    [FULL_FONT_NAME(4):WINDOWS(3)] entry: expected 'Press Start2 P Regular' but got 'Press Start 2P Regular' 
```

name table:

```
<namerecord nameID="1" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Press Start 2P
    </namerecord>
    <namerecord nameID="2" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Regular
    </namerecord>
    <namerecord nameID="3" platformID="1" platEncID="0" langID="0x0" unicode="True">
      3.000;CYRE;PressStart2P-Regular
    </namerecord>
    <namerecord nameID="4" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Press Start 2P Regular
    </namerecord>
    <namerecord nameID="6" platformID="1" platEncID="0" langID="0x0" unicode="True">
      PressStart2P-Regular
    </namerecord>
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Press Start 2P
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Regular
    </namerecord>
    <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
      3.000;CYRE;PressStart2P-Regular
    </namerecord>
    <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
      Press Start 2P Regular
    </namerecord>
    <namerecord nameID="6" platformID="3" platEncID="1" langID="0x409">
      PressStart2P-Regular
    </namerecord>

```

**Comment by alexeiva** [comment]
or is  `PressStart2P-Regular`  > `Press Start2 P` perfectly logical?

How should I proceed with the original font naming?

**Comment by m4rc1e** [comment]
Hey Alexei,

I reported this the other day #1120. Same Issue.

**Comment by graphicore** [comment]
also related: #1075

**Comment by vmesel** [comment]
@m4rc1e and @graphicore is this a duplicated issue?

**Comment by graphicore** [comment]
@vmesel as long the policy is to add exceptions into fontbakery, I would argue that this is not a duplicate. The solution is probably to add an exception for `Press Start 2P`as well. See #1075 and the PR #1084

For the record, I'm not too happy with the exception thing, but it seems to be hard to define a universal scheme for allowed names.

**Comment by felipesanches** [comment]
I'm not too happy about it as well. As a programmer I'd expect a clear-cut algorithmic definition of what's allowed and what's unacceptable. But this universal rule seems a bit hard to come up with, as @graphicore pointed out, so that's how we're working at the moment, adding exceptions. Maybe after we gather a slightly larger set of exceptions we'll gradually grasp a reasonable algorithmic expression of our criteria and then get rid of the exceptions. Maybe not. :-P

**Comment by felipesanches** [comment]
No. This was not a good fix, sorry.

**Comment by felipesanches** [comment]
alright :-)
