### ISSUE TITLE
Dashboard: Integrate Marc Foley's gfregression app into a new dashboard page

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1123]
Hey Felipe and Dave,

I think we should merge my [gfregression](https://github.com/m4rc1e/gfregression) app into Font Bakery. Instead of having lots of seperate repos/apps/libraries, we should focus on consolidating them.

It also fits FB's brief nicely 

> Tools to prepare font families for inclusion in github.com/google/fonts

I use it for cross platform testing a collection of fonts vertical metrics, against the same fonts which are hosted on fonts.google.com. 

![screen shot 2016-10-19 at 13 53 14](https://cloud.githubusercontent.com/assets/7525512/19517845/f4a5db6c-9603-11e6-9be7-38c850c7a2b1.png)
Left: local fonts  |  Right: fonts.google.com

I also see we are pushing for a UI for FB. I've built this app with Flask and Jinja2, keeping everything as simple as possible. I would opt for AWS or Digiocean over App Engine, due to our dependencies.

Cheers,
Marc

**Comment by davelab6** [comment]
Agree, but I would like Felipe to focus on getting the checker working
first and then build this comparison feature in

**Comment by davelab6** [comment]
> I would like Felipe to focus on getting the checker working first and then build this comparison feature in

Thus moving this to 0.4.0

**Comment by felipesanches** [comment]
Migrating to fontbakery-dashboard issue tracker per #1383
