### ISSUE TITLE
Cross-family checks show up under "None" section in markdown reports

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1141]
## Expected behaviour

Should show up under a section called something like:
- "Cross-family checks..."
- or "Checking coherence among same-family font files"
- or simply "<FamilyName>"
## Observed behaviour

Section title is "None" :-P

**Comment by felipesanches** [comment]
This one may be similar or even perhaps an actual duplicate of #1116

**Comment by davelab6** [comment]
Merging into #971
