### ISSUE TITLE
Test for kerning on non-ligated sequences

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1145]
## Expected behaviour

Fonts with ligatures should have kerning on the corresponding non-ligated sequences for text where ligatures aren't used (eg https://github.com/impallari/Raleway/issues/14)

We should test for that

## Observed behaviour

We don't currently test for that

## How to replicate

See https://github.com/impallari/Raleway/issues/14

**Comment by juandelperal** [comment]
Hi! I know this is a closed issue, but I don't think this rule applies for all cases.
Maybe the result of this test should be a WARN, not a FAIL?

**Comment by juandelperal** [comment]
For example
<img width="256" alt="Screen Shot 2020-04-08 at 16 49 55" src="https://user-images.githubusercontent.com/2414972/78798265-12d3c300-79b9-11ea-9169-4f5ecb2a2ecf.png">

**Comment by felipesanches** [comment]
@juandelperal, can you tell us more about your opinion on the expected behaviour and why?

**Comment by juandelperal** [comment]
@felipesanches I think the test is useful and it's ok as it is now, but if the fon't doesn't pass it should raise a `WARN` instead of a `FAIL`

**Comment by felipesanches** [comment]
I wish I could hear from you in more detail why do you think so. For instance, what do you mean by the example image you posted? Can you describe it in more detail?

**Comment by kontur** [comment]
Note that this current _does_ emit a `WARN` and not a `FAIL` in version 0.7.22

```
   >> com.google.fonts/check/kerning_for_non_ligated_sequences
    Is there kerning info for non-ligated sequences?
    with instance_ttf/Signika-Regular.ttf

      Rationale:
      Fonts with ligatures should have kerning on the corresponding non-ligated
      sequences for text where ligatures aren't used (eg
      https://github.com/impallari/Raleway/issues/14).

    * WARN: GPOS table lacks kerning info for the following non-ligated sequences:
	- f + f
	- f + i
	- i + f
	- f + l
	- l + f
	- i + l

   [code: lacks-kern-info]

    Result: WARN
```

**Comment by felipesanches** [comment]
thanks, @kontur 

Please try upgrading your fontbakery instalation to the latest released version, @juandelperal

**Comment by rimas-kudelis** [comment]
Hi! Could anyone rationalize why this check even exists? The `liga` feature is supposed to be on by default per OpenType spec. Why should a font designer have to bother about ligating glyph pairs which will almost always be replaced by a ligature glyph anyway?
