### ISSUE TITLE
fontbakery-fix-fsselection.py --autofix not working

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1149]
It seems many fonts have incorrectly set fsSelection bitmasks and this effects their rendering on Android. I want to

- [x] have a tool to hotfix this, and 

- [ ] ensure the fontbakery check script catches this 

For example, to reproduce: 

    cd ~/fonts/tools;
    python sanity_check.py ../ofl/abhayalibre/;
    FAIL: Abhaya Libre METADATA normal/400 fullName expected Abhaya Libre, got Abhaya Libre Regular (../ofl/abhayalibre)
    FAIL: AbhayaLibre-Regular.ttf normal/400 fsSelection marked_italic 1 (../ofl/abhayalibre)

However, when I run

    fontbakery-fix-fsselection.py --autofix ../ofl/abhayalibre/AbhayaLibre-Regular.ttf ;

I get,

| filename                    | fsSelection       |
|:----------------------------|:------------------|
| AbhayaLibre-Regular.ttf.fix | 00000000 01000001 |

Then if I move that fix'd file in place, and recheck, I see the same issue reported:

    mv ../ofl/abhayalibre/AbhayaLibre-Regular.ttf.fix ../ofl/abhayalibre/AbhayaLibre-Regular.ttf
    python sanity_check.py ../ofl/abhayalibre/
    FAIL: Abhaya Libre METADATA normal/400 fullName expected Abhaya Libre, got Abhaya Libre Regular (../ofl/abhayalibre)
    FAIL: AbhayaLibre-Regular.ttf normal/400 fsSelection marked_italic 1 (../ofl/abhayalibre)
    FAIL: Abhaya Libre normal/400 'name' fullName[0] expected Abhaya Libre, got Abhaya Libre Regular (../ofl/abhayalibre)
    FAIL: Abhaya Libre normal/500 'name' family[1] expected Abhaya Libre, got Abhaya Libre Medium (../ofl/abhayalibre)
    FAIL: Abhaya Libre normal/600 'name' family[1] expected Abhaya Libre, got Abhaya Libre SemiBold (../ofl/abhayalibre)
    FAIL: Abhaya Libre normal/800 'name' family[1] expected Abhaya Libre, got Abhaya Libre ExtraBold (../ofl/abhayalibre)

So, the fixer is not working.

**Comment by felipesanches** [comment]
Thanks for reporting this! I'll take care of it now.

**Comment by felipesanches** [comment]
This looks like evidence of the problem being on the sanity-check.py script instead:

felipe@guarana:~/devel/github_google/fonts (master)*$ ~/fb-dev/fontbakery-fix-fsselection.py ofl/abhayalibre/AbhayaLibre-Regular.ttf 

| filename                | fsSelection       |
|:------------------------|:------------------|
| AbhayaLibre-Regular.ttf | 00000000 00000001 |
felipe@guarana:~/devel/github_google/fonts (master)*$ ~/fb-dev/fontbakery-fix-fsselection.py --autofix ofl/abhayalibre/AbhayaLibre-Regular.ttf 

| filename                    | fsSelection       |
|:----------------------------|:------------------|
| AbhayaLibre-Regular.ttf.fix | 00000000 01000001 |
felipe@guarana:~/devel/github_google/fonts (master)*$ ~/fb-dev/fontbakery-fix-fsselection.py ofl/abhayalibre/AbhayaLibre-Regular.ttf.fix 

| filename                    | fsSelection       |
|:----------------------------|:------------------|
| AbhayaLibre-Regular.ttf.fix | 00000000 01000001 |

**Comment by felipesanches** [comment]
hmmm... ok. Now I see the issue you pointed out is with the italic bit that is set but shouldn't on a Regular.

**Comment by felipesanches** [comment]
ok, I got it! The fixer was indeed wrong.
I'll commit the fix for it now.

**Comment by davelab6** [comment]
The sanity-check.py script code is on github.com/google/fonts so please
review it

**Comment by felipesanches** [comment]
I did a while ago :-)

**Comment by davelab6** [comment]
OK! Then, please run the santity checker over the entire /google/fonts repo (ie, globally) and grep for fsSelection issues, move all .fix files in place globally, rerun the santity checker globally, and confirm everything is fixed.

**Comment by felipesanches** [comment]
OK. I have run the fsselection fixer on the entire google/fonts repo and noticed that it indeed fixes a few font files. Then I have re-run it over the entire set of .ttf.fix files and got no error detected, which means that the autofixer is doing a good job.

In order to do so, I had to fix a bug in the fixer, so it means it was actually broken. The issue was that it was getting confused when dealing with double filename-extensions such as .ttf.fix But now (after commit 8bbe2fa as seen above) it can handle that properly as well.

All of the above ignores non-canonical filenames because filenames are the source of truth for the fs-selection fixer. The criteria for canonical names is that it must contain a single dash separating familyname from stylename such as in **HindMysuru-SemiBold.ttf** (which is a good, canonical name), while **fonts/ofl/zeyada/Zeyada.ttf** is considered a bad-name.

**Comment by felipesanches** [comment]
On the other hand, **jsMath-cmbx10.ttf** is detected as a good name, while I think it shouldn't. Maybe I should also test whether the second term in the name (after the dash) is a valid stylename. I'll work on this next.

**Comment by felipesanches** [comment]
Canonical font filename validation was improved on commit 6ce7b7c
