### ISSUE TITLE
weird crash caused by renaming a variable

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1159]
I'm facing a rather misterious crash scenario involving what seems to be an unintentional relationship between the following couple checks:

* "METADATA.pb: Fontfamily is listed in Google Font Directory ?"
* "METADATA.pb: Designer exists in GWF profiles.csv ?"

Both checks use a variable called 'fp' in their respective implementations. This is not a good var name so I changed it to a different name in the first check. (I renamed it to 'r' which is what is used in snippets of code in the requests module website). After such "harmless" edit, I started to get a crash when running fontbakery against the Merriweather family that we have in our **data/test/** folder.

I noticed that the crash only happens when the checks use different var names. So it seems that when usin the same var name, the second use of the variable name triggers garbage collection on the previous object and the lack of such object deletion introduces the crash.

Based on that rationale I did add an explicit deletion statement to the first check, but that did not help. I still get a crash.

The 'fp' variables are used liberally in these couple checks (and nowhere else in the codebase) as temporary objects. In the first check it is used to save the return value of requests.get(url) while in the second check urllib.urlopen(PROFILES_RAW_URL) is assigned to it.

I'm a bit puzzled by this issue. I'd appreciate if anyone has got any clue on what else might be happening here.

**Comment by felipesanches** [comment]
This is making me mad. I'm using different var names and properly deleting the temp objects and I still get the crash. The crash only goes away when I use the same var name for both checks. But there should NOT be any inter-dependence between these two checks. This is nasty! I can't leave it this way because it smells. I want to understand what's going on.

**Comment by felipesanches** [comment]
One more detail about this. It does not seem to throw an exception (or at least it does not output a stack-trace) It simply gets back to the terminal prompt silently without finishing the work (leaving an incomplete progressbar with no final linebreak on the screen).

**Comment by davelab6** [comment]
Is this caused by the refactoring to methods?:P

**Comment by felipesanches** [comment]
No. It is an issue that was already present in the codebase but was unnoticed until I looked at it again while refactoring. This was a hidden beast that refactoring helped uncover :-D

**Comment by felipesanches** [comment]
Refactoring is a healthy habit, dave ;-)

**Comment by davelab6** [comment]
https://youtu.be/3JcmQONgXJM

**Comment by davelab6** [comment]
@felipesanches please check if this still occurs

**Comment by felipesanches** [comment]
BOOM!
We're clear! :-)
https://www.youtube.com/watch?v=4AVWZwZq_QU
