### ISSUE TITLE
First font file runs a larger number of checks

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1160]
When running check-ttf.py on a set of font-files, the first one runs 191 checks while all the rest run only 120 checks each.

I'd expect all TTF files to run the same set of checks.
This is a critical bug.

**Comment by davelab6** [comment]
I agree

**Comment by davelab6** [comment]
@felipesanches what is the current status of this? 

Seems this should be a 'before doing anything else' sort of task? :)

**Comment by felipesanches** [comment]
Exactly! That's what I'm working at right now.
