### ISSUE TITLE
Vertical Metrics change

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1162]
In https://groups.google.com/forum/#!topic/googlefonts-discuss/H5F6NUzaWFk%5B101-125%5D @m4rc1e writes,

> I found Alexei's fonts had a few errors with the vertical metrics. This is not his fault because we didn't have a proper policy in place, until we started checking these on the last day of the summit. I've submitted these as issues in the corresponding repos. https://github.com/cyrealtype/Lora-Cyrillic/issues/9 https://github.com/alexeiva/yanone-kaffeesatz/issues/3 https://github.com/cyrealtype/Prata/issues/4.
> 
> Since this issue may pop up more in the future, I've decided to write a script to fix this in Glyphsapp. The script works as follows:
> 
> 1. Take the font family name and download the zip file of the family from fonts.google.com (stored in memory)
> 2. Check each ttf has the same vertical metrics values.
> 3. Check the masters match the values from step 2. However, Change the Win asc and Win desc to the tallest/deepest glyphs.
> 
> I think this approach will be a huge benefit in the future. This check should also be in Font Bakery.

Indeed it should! This issue tracks this. 

See the link at top for more details in the emails to the list following the one quoted above

**Comment by m4rc1e** [comment]
@felipesanches hello,

Here's my [implementation](https://github.com/m4rc1e/mf-glyphs-scripts/blob/master/Google%20Fonts/inherit_legacy_metrics.py) for how I've done it in Glyphsapp. I've kept it loosely coupled so you can do some recycling  :-)

I am more than happy to port this, if I find the time. It shouldn't take too long.

**Comment by alexeiva** [comment]
Just fixed issue in https://github.com/cyrealtype/Lora-Cyrillic/issues/9 using this srcript. Works great.

**Comment by davelab6** [comment]
This more about the 'collection flow' so I moved to to 0.4.0 release

**Comment by davelab6** [comment]
@m4rc1e could you explain what you think fontbakery should do here? I understand your email above describes taking action on the upstream source `.glyphs` file... is the action for FB to run the check on the binaries and, if they need fixing, log an error, with a suggestion to use your script?

**Comment by m4rc1e** [comment]
@davelab6 If the family has already been released on GF, the visual appearance of the vertical metrics should be the same, unless they are seriously screwed. This will stop document reflow. I have this implemented as a fix in gf-glyphs-scripts, https://github.com/googlefonts/gf-glyphs-scripts/blob/master/Google%20Fonts/fixfonts.py#L67-L108

**Comment by davelab6** [comment]
> In FB, it would also be nice to have this regression test.

@felipesanches is it clear to you how to implement this?

**Comment by felipesanches** [comment]
I'll have to look at it again later.

**Comment by m4rc1e** [comment]
@felipesanches @davelab6 

After reading the whole discussion in #2164 again. I've come up with the following schema: 

---

**For each font in a family:**
- Must have same vertical metric values
- OS/2 fsSelection bit 7 must be enabled
- WinAscent, WinDescent must be >= greatest family yMax, yMin values
- Hhea and Typo lineGaps must be set to 0
- Metrics should fall into a Goldielocks zone which is ~120%–140% of upm

    **If family already exists on google fonts:**
    **For each font in a family:**
        - Must have same vertical metrics values as Regular style on GF (some  families on GF do not have family wide consistent metrics. We’ll use Regular since it’s the most frequently used)
        **If family on GF doesn’t have OS/2  bit 7 enabled:**
            - Typo metrics should be set to GF family’s win metrics
        **else**
        - Typo metrics should be set to GF family’s typo metrics

- hhea metrics must match the typo metrics. (We match hhea to typo since there are more Win users)


I recommended this approach to @mjlagattuta in https://github.com/google/fonts/pull/1794#issuecomment-448334602.

I would like to refactor our vertical metrics tests to reflect this proposal this week.

Totally open for any suggestions.

**Comment by davelab6** [comment]
I'm not convinced, because I want correct fonts, so I think we should have all fonts following the "For each font in a family" section without regard to if they already exist on Google Fonts.

**Comment by davelab6** [comment]
Yes this will cause reflow in some apps, and yes this will be annoying for existing users, but there are more users in the future than the past, and the reflow is only happening to bring the metrics into consistency within the family and across apps.

**Comment by m4rc1e** [comment]
My proposal will give you correct fonts. If the fonts exist on GF and the hhea and typo differ, this new proposal will make both metrics sets conform to the typo/win vals depending on whether fsSelection bit 7 is enabled.

**Comment by simoncozens** [comment]
We now have a check for vertical metrics regressions; I don't believe there is any more work to do here, but let's reopen if I've misunderstood.
