### ISSUE TITLE
ERROR: METADATA.pb: copyright field contains 'Reserved Font Name'

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1163]
@davelab6 I thought we decided to include the RFN in everything now?

If we did, we should delete this test.

Cheers,
Marc

**Comment by davelab6** [comment]
No! We must retain RFN in specific situations but the majority of families should not have it. This test should not be deleted, but the returned string may be updated with more clarity

**Comment by m4rc1e** [comment]
ok, awesome.

**Comment by felipesanches** [comment]
@davelab6 Should it remain as an error but mentioning that there may be exceptions to the rule in a few specific cases?
Or should it be changed into a warning (with the added wording as well)?

**Comment by davelab6** [comment]
Sounds good
