### ISSUE TITLE
FontForge checks crashing FontBakery (sometimes)

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1166]
Fontforge checks were temporarily disabled on https://github.com/googlefonts/fontbakery/commit/1e962f10f5f91f1ccca1699d5f4b11f35dde8371 because they were crashing fontbakery in some situations. The real reason is still unknown. It still needs to be diagnosed, fixed and have the fontforge checks re-enabled.

- [ ] figure out what's the real issue causing the crashes
- [ ] fix it!
- [x] re-enable the fontforge checks

**Comment by davelab6** [comment]
Fixing ff is a black hole on the way to Mars and we don't have Elon musk on
staff

I suggest to write a stronger try/except system to isolate and contain the
xenomorphic threat until we can nuke it from orbit

**Comment by felipesanches** [comment]
LOL! Awesome message! Alright!

**Comment by felipesanches** [comment]
@davelab6 Do you believe Mars is our only lasting hope?

**Comment by felipesanches** [comment]
I re-enabled it with a try-catch that spits an error message in the check-results log. If this error message start showing up we can further investigate the issue.

I'll keep the issue open so that I can look at it again later. (because "If you haven't fixed it yet, then it's still broken!")

**Comment by davelab6** [comment]
Cool. Repriotized

**Comment by felipesanches** [comment]
yup! It seems it started showing up again :-P

https://github.com/googlefonts/fontbakery/issues/1270

**Comment by davelab6** [comment]
@graphicore does the new version prevent this from happening, do you think? :)

**Comment by felipesanches** [comment]
The new architecture does not allow a test crash to bring the whole system down. They may still happen, but they're now all isolated and won't prevent the execution of the rest of the testsuite.

**Comment by davelab6** [comment]
Winner

**Comment by graphicore** [comment]
Also, if something crashes a test run, it's a bug and we fix it. In the end these cases should all have an `ERROR` status, which means something needs to be fixed in the test implementation.
