### ISSUE TITLE
Replace hypens to underscores in script filenames

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1172]
Hey folks,

By using hypens, we cannot correctly import objects from scripts into other scripts. This makes writing tests and recycling stuff much hackier.

`from fontbakery-check-ttf import blah`
This won't work. The closest we can get is using `execfile()`

I understand this may break folks shell scripts.

**Comment by felipesanches** [comment]
I've dealt with this kind of issue a while ago. Please take a look at the `__import__` usage at test_args.py:

```python
for module_name in target_modules:
  target = __import__(module_name)
  help_text[module_name] = target.parser.format_help()
```

**Comment by m4rc1e** [comment]
This worked, thank you. It still feels a little hacky though.

**Comment by felipesanches** [comment]
yes, indeed. Perhaps this may change with issue #835
