### ISSUE TITLE
Render check results in an html table instead of list-items

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1180]
Webapp is currently rendering check results as html list items (using the ul and li tags).

Dave suggested we use an html table so that we can make it sortable.

**Comment by felipesanches** [comment]
DONE!

**Comment by davelab6** [comment]
Thanks @felipesanches - please push the latest to http://fontbakery.appspot.com :)

**Comment by felipesanches** [comment]
yep, I'll do it. But it'll be the last thing later tonight.

**Comment by davelab6** [comment]
Perfect, thank you!
