### ISSUE TITLE
in-memory code needs urgent rework

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1181]
I started working on switching the fontbakery webapp check results from getting markdown-generated html unsorted lists to receiving html tabular data instead. (issue #1180) This **should** be quick, no more than 1 hour to put it together, but I stumbled on some "code debt".

There are some poor design decisions in the way things are done right now. Especially the quick hack for in-memory font data handling need some rework because it is too hacky to be safe to move on without cleaning it up.

There's a work-in-progress commit at https://github.com/felipesanches/fontbakery/commit/b705f13f2a4266cd4956b1d034fa13e6de423022 that addresses some of it. I expect to work aproximately 2 or 3 more hours rethinking and fixing this mess. So that I can then move on to other tasks.

**Comment by felipesanches** [comment]
The first bad design decision is the way we detect whether or not the program is run as server-side backend for the webapp:

```
webapp = (__name__ != "__main__")
```

Basically I'm using a very poor euristics here that whenever the program is not run as a standalone script, then it means we're running it as part of the webapp backend. This is bad because there can be other usage scenarios where the script is not run as a standalone, such as when it is imported by some other script. This may be an ok solution now, but it may leas to problems in the future.

Also, the reason why we need to detect whether or not we're running it in webapp-backend mode is because there are a few features that are disabled on GoogleAppEngine:

```
if not webapp:
  # avoid importing magic on the webapp dues to
  # usage of ctypes which is incompatible with Google App Engine
  import magic
  import subprocess
  from fonts_public_pb2 import FamilyProto

  try:
    from google.protobuf import text_format
  except:
    sys.exit("Needs protobuf.\n\nsudo pip install protobuf")
```

(protobuf is not a dependency for the webapp because we currently do not check METADATA.pb files on the webapp.

**Comment by felipesanches** [comment]
Second issue: `config['inmem']` seems redundant with the `webapp` boolean. Since `inmem` is passed explicitely by the webapp as a parameter to the `fontbakery_check_ttf` function, this should perhaps be the signaling mechanism we're looking for (instead of the problematic `webapp = (__name__ != "__main__")` as discussed above).

**Comment by felipesanches** [comment]
On the other hand... I think it may be useful to still keep these two cases separate:
**(1)** a flag for indicating whether things are handled in-memory (as oposed to as filesystem i/o)
And **(2)** a flag indicating we need to disable certain things we do not support yet in the webapp environment.

So I'll make sure the `webapp` boolean is passed explicitely as a `fontbakery_check_ttf` function parameter instead of (poorly) auto-detecting it.

**Comment by felipesanches** [comment]
Sorry that I've been absent for a while. This week turned out to be extremely busy for me. But I'll resume work on this probably tonight or on Friday morning.

**Comment by felipesanches** [comment]
This piece of code is currently pending a rework on the check target tracking mechanism (which was initially meant to be something quite simple, but ended up growing into a convoluted set of routines).

The purpose of the check target mechanism is to track which file is being tested in each check. Stating it like that makes it clear that the implementation should be absolutely trivial. But it ended up becoming quite complicated (and probably broken) when I drafted in-memory handling of file-like objects.

**Comment by davelab6** [comment]
Maybe we should abandon appengine and move to docker

AE was meant to be fast and simple! :)

**Comment by felipesanches** [comment]
Cleaning up the mess described above is needed regardless of hosting it on GAE or anywhere else.

This is not done yet not because it is hard (it is not really), but because I was unable to dedicate more time to fontbakery lately.

**Comment by felipesanches** [comment]
DONE!

**Comment by davelab6** [comment]
Glad to see this sorted :)

**Comment by felipesanches** [comment]
Me too!
