### ISSUE TITLE
Check GSUB/GPOS tables for required features

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1188]
As our language support improves, some languages require some OpenType features to be fully supported. 

We should therefore check that these features are included in all fonts.

**Comment by felipesanches** [comment]
@davelab6 Do we have a list of the specific required features we should be checking against?

**Comment by davelab6** [comment]
@alexeiva and @m4rc1e can better advise, but if you search the gf collection for gsub tables and count commonalities, that could develop a list.

Latin: Turkish (around dotless "i", iirc), Dutch (ij?) 

Cyrillic: Romanian, Serbian, etc

The glyphsapp tutorials also has some documentation on common OpenType features for language support, please review that

**Comment by felipesanches** [comment]
cool! Thanks

**Comment by alexeiva** [comment]
I will provide some standart practise samples for Cyrillic

**Comment by alexeiva** [comment]
1. 
if font includes glyph `germandbls.calt`

`calt` feature should include
```
sub @Uppercase germandbls' @Uppercase by germandbls.calt;
sub @Uppercase @Uppercase germandbls' by germandbls.calt;
```

Source: https://glyphsapp.com/tutorials/localize-your-font-german-capital-sharp-s

**Comment by khaledhosny** [comment]
That `calt` feature above is really a bad idea. There is an atomic encoded character of it in Unicode, and upper casing is a textual process that depend on orthographic rules, not a glyph display one and fonts have no business messing with text case.

**Comment by davelab6** [comment]
Thanks Khaled!

Felipe, you'll need to do a collection wide analysis.

**Comment by simoncozens** [comment]
The way to do this is through the shaperglot checks.
