### ISSUE TITLE
check-ttf.py: fullname name length

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1190]
Hello @felipesanches and @davelab6,

I see we're checking if the fullname is under [64 characters](https://github.com/googlefonts/fontbakery/blob/master/fontbakery-check-ttf.py#L2834-L2837). I thought the limit was 32, regardless of field type?

Also, hope you had a cracking xmas and NYE

**Comment by felipesanches** [comment]
As an atheist I do not celebrate christmas. But I do drink the wine and eat the good food! It is also a great opportunity to meet all of the family :-)

Regarding the max allowed length for fullname, I'm not sure right now. I'll take a look at this again once I get back to work next Monday Jan 9th.

cheers!

**Comment by davelab6** [comment]
Felipe, what about https://stallman.org/grav-mass.html ? :)  32 sounds more
likely, but would be good to check the MSFT OpenType specification on
this... I took a quick look at
https://www.microsoft.com/typography/otspec/name.htm but couldn't quickly
find an answer to this.

**Comment by m4rc1e** [comment]
I was not able to find a definitive answer in the spec either.

I remember this being an issue in the past and I'm also guessing 32 is the max.

**Comment by davelab6** [comment]
Seems easy to empirically verify

**Comment by m4rc1e** [comment]
Alright, @anthrotype pointed me towards the AFDKO, MakeOTFUserGuide.pdf documentation. You have to download the afdko to get it. It states, pg 9:

> Note on length restrictions
Because of limitations in operating systems and common applications, it is recommended that none of these keys contain names longer than 31 characters.  Thiis results in menu names for legacy environments being 31 characters or less. The OpenType menu name (used in Adobe InDesign® and future Adobe applications) may be thought of as the combination of the f= and s= keys. Since each of these can be up to 31 characters, the OpenType menu name can be up to 62 characters.

This all sounds rather legacy to me. I'll do some testing in win7 Notepad with fontnames over 31 and 62 chars long. This should end the rumours.

**Comment by m4rc1e** [comment]
# Fullname: 31+ chars & font name < 32 chars:
I tested **[EncodeSansSemiCondensed-ExtraBold.ttf](https://github.com/m4rc1e/Encode-Sans/tree/master/fonts)**.

Font Name: 11 characters
Full name: 35 characters

![screen shot 2017-01-04 at 11 31 58](https://cloud.githubusercontent.com/assets/7525512/21641093/8b572c7e-d271-11e6-94fe-1c54b56dc987.png)

The font menu names are behaving as they should.

# Fullname: 62+ chars & font name > 31 chars:
Had to make a custom font. Font name 'The Quick Brown Fox Jumps Over The Lazy Dog'.

Font Name: 43 characters
Fullname: 67 characters

![screen shot 2017-01-04 at 12 09 39](https://cloud.githubusercontent.com/assets/7525512/21641900/b8ea48c4-d276-11e6-89bc-060296ea5bac.png)

Oh dear, The name gets cut off at 31 characters long, **'The Quick Brown Dox Jumps Over '**. 


# What about OS X?
![screen shot 2017-01-04 at 12 19 18](https://cloud.githubusercontent.com/assets/7525512/21642099/0e34fa30-d278-11e6-8fd0-8a58401b451d.png)
No issues.

# Ok, does the NAME table not accept certain fields over 31 characters?
Generating the fonts doesn't chop any fields down to 31 chars. This is an MS specific issue.
![screen shot 2017-01-04 at 11 36 25](https://cloud.githubusercontent.com/assets/7525512/21641175/1011fea8-d272-11e6-8126-5c769a1a8113.png)
![screen shot 2017-01-04 at 12 14 42](https://cloud.githubusercontent.com/assets/7525512/21642010/6aea6856-d277-11e6-874e-ff0f83169cce.png)
*screenshots from OT Master*

It looks like Fontbakery is correct. Postscript name and Fullname can be over 31 characters. Font name and style fields should be under 31.

Hope this all makes things clearer.

**Comment by m4rc1e** [comment]
Closing this since our implementation is good.
