### ISSUE TITLE
Indentation: change to 4 spaces

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1192]
I'm guessing this is linked to #1161.

I would love to use 4 spaces, instead of 2 in .py files. Imo, it has significant advantages for readability and debugging.

**Comment by davelab6** [comment]
@felipesanches thoughts?

**Comment by felipesanches** [comment]
I'd rather stick to using 2 spaces. It gets tight to make code fit into 80 chars with 4-chars indentation.

I'm not religious about it. But I'm typically the one doing the largest amount of daily editing and maintenance to the codebase so I'd rather keep it at 2-chars :-)

But you're right that #1161 is important. I should spend some time cleaning up that mixed indentation style sooner than later.
