### ISSUE TITLE
Improve HTML table styling for the webapp check-results

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1195]
Check-results content is correct but:

- [x] overflows tab-widget width (we could make the widget wider perhaps)
- [x] Text is a bit too large and unnecessarily bold, I think.
- [x] lacks color-coding for each type of result (i.e. ERROR=red, WARNING=blue, INFO=grey, etc)
- [x] "CrossFamilyChecks" tab should be hidden if there are zero log messages (i.e. if user submitts a single TTF file)
- [x] Tables embedded in log messages using Markdown syntax do not render properly
- [x] Checks with too many log messages should have status and description aligned to the top of the table cell instead of vertically centered.
- [x] does not yet allow table sorting

**Comment by felipesanches** [comment]
@davelab6 what do you think ?

**Comment by davelab6** [comment]
@felipesanches those last 2 tasks seem very quick to do, please do them and close this asap

**Comment by felipesanches** [comment]
I'll work on these after merging the fontbakery dashboard (pull request #1209)
