### ISSUE TITLE
Regression Tests

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1207]
A common problem we are now facing are regression errors. If the font already exists on fonts.google.com, we need to test the following:

1. Has the visual appearance of vertical metrics changed?
2. Has the version number increased?
3. Do the new fonts contain the old styles?
4. Do glyphs contain the same amount of points?

Montserrat had this nasty [error](https://github.com/JulietaUla/Montserrat/issues/35)

I already have tests 1–3 implemented in my GF [tests](https://github.com/m4rc1e/mf-glyphs-scripts/blob/v2/Google%20Fonts/qa.py#L187-L250). Warning, this is still very rough.
 
I will draft these today in FB

cc @davelab6

**Comment by m4rc1e** [comment]
I've spent my day on these tests. I'm pretty happy with the initial results:

![screen shot 2017-01-27 at 17 27 15](https://cloud.githubusercontent.com/assets/7525512/22380641/09839046-e4b6-11e6-9473-822dde796a5a.png)

I've settled for flagging a glyph is the difference between the point count is 10 or more. It will also see if glyphs which should be composites have been decomposed. 

You can then pump the string into [gfregression](https://github.com/m4rc1e/gfregression) and see what has changed very quickly.

I'll keep you all posted

**Comment by felipesanches** [comment]
@m4rc1e  Cool! Let me know when you feel like opening a pull request so that I can review it and merge.
