### ISSUE TITLE
Add script for release making/checking

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1208]
## Expected behaviour

Font Bakery should have a script that can confirm when a 'release' is ready to tag and push and upload a special zip... in fact it could even generate that special release zip :) 

## Observed behaviour

Per https://github.com/google/fonts/issues/611 a user complained about a new release of Inconsolata lacking adequate release documentation.

**Comment by felipesanches** [comment]
This is a duplicate of https://github.com/googlefonts/tools/issues/12
