### ISSUE TITLE
Naming families containing the prefixes "Extra", "Semi"

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1211]
Hey folks,

We've recently started dealing with super families and the GF api cannot handle widths. Widths need to be separated into their own individual families, so Roboto Condensed is a different family to Roboto.

![screen shot 2017-01-31 at 14 54 07](https://cloud.githubusercontent.com/assets/7525512/22469825/2d4161e0-e7c5-11e6-8f9c-456167832315.png)
*Menu screenshot of Roboto and Roboto Condensed*

I'm wondering how we should treat variations of Condensed and Expanded families. Should it be 
**Extra Condensed** or **ExtraCondensed**? These edge cases have not been specified in our [naming doc](https://docs.google.com/spreadsheets/d/1ckHigO7kRxbm9ZGVQwJ6QJG_HjV_l_IRWJ_xeWnTSBg/edit#gid=0). If we choose the CamelCase version, it will match out treatment of font styles, e.g: SemiBold, ExtraLight. If we choose the non CamelCase version, it will match similar family names from other foundries.

![screen shot 2017-01-31 at 10 55 02](https://cloud.githubusercontent.com/assets/7525512/22470186/5dc32136-e7c6-11e6-8b0f-f890633fe5d4.png)
![screen shot 2017-01-31 at 10 53 33](https://cloud.githubusercontent.com/assets/7525512/22470187/5dd95ece-e7c6-11e6-975a-b597ea04dd5e.png)

In Font Bakery, it likes the non CamelCase version. We have also let through [Fira Sans Extra Condensed](https://fonts.google.com/specimen/Fira+Sans+Extra+Condensed) which is non CamelCase. We haven't had any complaints yet.

I'm uncertain whether either approach will lead to any complications? I'm assuming this is more a matter of styling.

**Comment by davelab6** [comment]
Pablo had a nice idea to name widths in a way that sorts alphabetically....

Compact (Pablo used compressed but that's confusing with woff etc)
Condensed
Default [or nothing but that sorts to the top]
Expanded
Wide

The use of Semi and Extra makes a poor sort order.

Fb should also check width metadata is correct for such families btw

**Comment by davelab6** [comment]
To answer the question, I think spaced rather than camel case is best for
family names, and a single camel case word best for style names

**Comment by m4rc1e** [comment]
If we all agree to this, there are no changes needed. Any objections?

**Comment by felipesanches** [comment]
If no changes are needed, I suggest we close this. Reopen, please, if there's still any objection.
