### ISSUE TITLE
F841 local variable 'IOError' is assigned to but never used

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1218]
Travis have been failing for a while on this:

 fontbakery-check-ttf.py:1835:21: F841 local variable 'IOError' is assigned to but never used
 1     F841 local variable 'IOError' is assigned to but never used

This tracks back to https://github.com/googlefonts/fontbakery/pull/1205

Seems to be simple to fix. I'll take a closer look in a while.

**Comment by davelab6** [comment]
Thanks!

**Comment by felipesanches** [comment]
;-)

**Comment by davelab6** [comment]
Thank you Felipe
