### ISSUE TITLE
Add numerical identifiers for each check

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1219]
I've been thinking that if we had idnetifiers for each check, it could serve a good purpose in communicating both among ourselves during development (i.e.: there's an issue with check number 37) as well as when talking to type designers (i.e.: I'm getting some error messages related to check 15, can you provide me some guidance on how to fix the issue, please?)

I know it is not strictly necessary, but I think it could be worthwhile. Also, there's the precedent that some other lint tools do just that as well. So we're not reinventing the wheel here.

@davelab6 and @m4rc1e What do you think?

**Comment by felipesanches** [comment]
oh! And it could also aid in readability on the text terminal output. I have had this idea for a long time, but I have just expressed it here now because I just felt again the need for it while scrolling a few pages of verbose log. If there were check numbers it would be easier to fing the specific check I'm interested in debugging.

**Comment by davelab6** [comment]
I agree this would be nice someday

**Comment by felipesanches** [comment]
done

**Comment by felipesanches** [comment]
The check id numbers are saved on the check-results log and will be available on the database. We can later use that new database field for displaying the check id numbers to the users on the webapp.

The numbers are already visible on the command line if you use the -vv flag (VERBOSE level = 2)
