### ISSUE TITLE
Dockerize FontBakery dashboard infrastructure

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1223]
We should have:
* a worker container that fetches a font project git repo and runs fontbakery-check-ttf.py on it.
* a database container running redis. The check-results from the workers are stored here.
* a stats-update worker which is responsible for computing the aggregate project statistics for all font projects based on the raw check-results from the database. The results of this worker job should be cached on redis as well
* a dashboard webapp container. The app will be a simple angular project with data fed from the redis database.

I'll probably setup a file with Docker-Compose rules to glue these containers together, but I'm also considering the possibility of using some job-scheduler like Iron.io for dispatching the worker containers on a regular basis. Alternatively, I should also investigate whether worker containers could be dispatched on-demand by monitoring commit hooks on the font project git repositores.

@davelab6 and @m4rc1e : I need you to take a look at this description. I've just started learning about Docker a couple days ago, so I'd like to get feedback on this to be sure I'm on the right track.

**Comment by felipesanches** [comment]
The status on this is that I already got fontbakery-check-ttf running on a docker container. Now I'm tweaking that container to add otsanitize and some other auxilary tools. Then, later I will:

* setup this to save the check-results data to a redis container.
* write a helper script for fetching the TTF files from git based on a FONTFAMILY_FILES environment variable, before invoking check-ttf
* improve the script to also be able to fetch Google Fonts production font-files and identify them properly on the redis database.
* etc...

**Comment by m4rc1e** [comment]
Why Redis?

**Comment by felipesanches** [comment]
Because it seems to be a simple and efficient solution for storing and caching the data instead of the "JSON stubs everywhere" aproach :-)

**Comment by m4rc1e** [comment]
I agree with the json stubs part.

I would personally prefer the results to be stored in a db which is not an IMDB. If we're plotting charts etc, this historical data will need to be much more persistent. Also, since we'll keep adding tests, this may rule out a relational db or we'll keep needing to do db migrations. 

I'd also love to have an api to browse historical data with nice endpoints such as:
http://api.fontbakery/v1/fonts/montserrat/historical/2011-10-1/2015-10-1/

I'm not sure how well Redis will cope with this. I've briefly used it so my understanding is rather limited.

I'd really focus on nailing this before you venture off into the frontend as well.

My advice is to talk to a team at Google who really understand these problems. We're merely speculating at the moment.

**Comment by felipesanches** [comment]
well.. if there are database experts at Google who could provide some input here at this issue, it would be awesome! :-D

**Comment by felipesanches** [comment]
Regarding historical data, if we bugfix certain FB checks (or if we add/remove checks in a new FB version) we may want to rerun the test suite on old font project commits. The good thing is that all of the upstream font files are (supposed to be) versioned on git, so (even though I'm unsure this would be worth the effort) we could checkout an old commit again and rerun check-ttf on it. For this purpose, it would be good to keep a fontbakery-version-id field in the database structure.

**Comment by davelab6** [comment]
Firebase?

**Comment by felipesanches** [comment]
I'm not sure yet.

**Comment by davelab6** [comment]
@felipesanches can this be closed?

**Comment by felipesanches** [comment]
In theory this issue refers to the pending work at pull request #1209 
But as most of the discussion is going on at the pull request itself, it seems safe to close the issue.
