### ISSUE TITLE
Dashboard: Improvements to the handling of upstream git repos at the worker container

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1228]
"gather from git" runs on the cmd-line specified TTF files once per commit.

Current shortcomings:

- [ ] A) It does not cover more than one family stored in a single repo.

- [ ] B) It does not follow git renames (I considered implementing that. It would be neat. But I did not think it was the most important thing to do in terms of priorities)

**Comment by davelab6** [comment]
Given a git repo URL, git commit hash id, a fontbakery version are recorded in a central database of burndown results, it seems that we can have the gather tool cache it's findings and return early if it finds an existing result for the given repo hash with a version more up to date or equal to current version

**Comment by felipesanches** [comment]
Sounds great!

**Comment by felipesanches** [comment]
Migrating to fontbakery-dashboard issue tracker per #1383
