### ISSUE TITLE
Dashboard: Conform to Material Design

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1231]
Hey @felipesanches ,

I think it's wise we stick to using [Material Design](https://material.io/guidelines/) for the UI.

**Comment by felipesanches** [comment]
Yup! I think it's great.

**Comment by davelab6** [comment]
Material Design Components?

**Comment by davelab6** [comment]
This is low Priority to me

**Comment by felipesanches** [comment]
Migrating to fontbakery-dashboard issue tracker per #1383
