### ISSUE TITLE
Implement 'missing codepoints' check

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1232]
Nyshadh has written a 'missing codepoints' check that FB should implement

**Comment by felipesanches** [comment]
I contacted Nyshadh and he said he did not yet publish his script on google/fonts but that he'll let me know when he does that, so that I can port it / integrate it into fontbakery.

**Comment by davelab6** [comment]
Thank you nyshadh!

**Comment by felipesanches** [comment]
Sure! As soon as Nyshadh publishes his scripts, I'll port them into FB.

**Comment by felipesanches** [comment]
@davelab6 can you ask Nyshadh for this script again soon, please?

**Comment by davelab6** [comment]
Nyshadh is out of the office for a few weeks

**Comment by davelab6** [comment]
Nyshadh may be able to share this end of this week / early next week

**Comment by felipesanches** [comment]
Great, thanks!

**Comment by felipesanches** [comment]
@davelab6 Any further info on this?

Maybe a description of what needs to be done? Or a reference implementation. Otherwise, I'll re-categorize this a "MISC"/"maybe-someday" and revisit someday in the future.

Presumably there is an implementation by Nyshadh somewhere, so I should not spend time on this issue right now.

**Comment by davelab6** [comment]
@felipesanches yep - I agree, I moved it to 0.5.0 :)

**Comment by felipesanches** [comment]
thanks!

**Comment by davelab6** [comment]
I pinged Nyshadh about this again; hopefully will be possible soon :)

**Comment by felipesanches** [comment]
thanks

**Comment by davelab6** [comment]
https://github.com/google/fonts/pull/1108

**Comment by HinTak** [comment]
Does the OS/2 codepoint coverage part of FontVal does what you want for this? That's all in C# in https://github.com/HinTak/Font-Validator/blob/master/OTFontFileVal/val_OS2.cs line 1160 onwards or thereabouts.

**Comment by felipesanches** [comment]
Thanks! I'll take a look at that later.

**Comment by davelab6** [comment]
No the OS/2 codepages aren't relevant, but having that set of char checks
in pyfontaine would be nice. Please don't close this until that's resolved
or there is an upstream issue for it

**Comment by felipesanches** [comment]
we don't have pyfontaine as a dependency anymore, so I moved this issue to the pyfontaine repo and will close this one.

**Comment by davelab6** [comment]
Thanks!
