### ISSUE TITLE
Dashboard: Better choice of colors for the pie-chart in the family details page

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1235]
Red is typically associated with "problem". It would be good to change the color-scheme of the generated pie-chart so that the "OK" check-results are represented by a portion of the pie coloured in green. While "ERROR" results should use the red color, and maybe blue for "INFO" and yellow for "Warning" and soft-blue for "SKIP".

**Comment by davelab6** [comment]
Agreed

**Comment by felipesanches** [comment]
Migrating to fontbakery-dashboard issue tracker per #1383
