### ISSUE TITLE
Dashboard: Allow hidding "OK" results in the family details page

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1236]
While we display all check-results (for the sake of completeness), it is likely that the users may be much more interested in looking at what went wrong. So a button (or checkbox) for toggling the visibility of "OK" check results could be very useful in the dashboard UI.

**Comment by davelab6** [comment]
Agreed

**Comment by felipesanches** [comment]
Migrating to fontbakery-dashboard issue tracker per #1383
