### ISSUE TITLE
Dashboard: Display a burndown chart of check-results scores per family (on the family details page)

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1237]
We do collect all the data needed to build a burndown chart (and there's been some prototypes of that in the past) but right now all we show in the dashboard UI is info tagged with "HEAD": true in the database, meaning that we're just displaying the check results for the latest commit in the git repos.

Since we have the data, I think it would be wise to query that and render the chart. The best place to showcase the graph, in my oppinion, would be at the top of the family details page, where nowadays we only render the check-results summary pie-chart as seen in the screenshot below:

![selecao_746](https://cloud.githubusercontent.com/assets/213676/23764390/22b99290-04dc-11e7-9f0a-024c0415a1b8.png)

**Comment by davelab6** [comment]
Agreed

**Comment by felipesanches** [comment]
It costs too much to run FB on the full commit history of projects, so nowadays we are only checking against the repo HEAD commit.

In order to make it acceptable to keep the full history, we would need to detect whether re-running the checks on a specific commit is really necessary. The criteria for deciding that would be: (a) the specific commit was never checked previously or (b) it was checked with an older version of fontbakery so it would be needed to re-run the checks and update the database entries.

**Comment by felipesanches** [comment]
Migrating to fontbakery-dashboard issue tracker per #1383
