### ISSUE TITLE
[dashboard] Fetch font files from production and run fontbakery on them as well

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1238]
We need to run fontbakery on the production files for all families on the Google Fonts project.

I'm still not sure if that should be a task for our current "worker" container, or if we should have yet another container specifically crafter for that task. But surely there must be cross-referencing between those two sets of fontfiles in the database entries.

I'll limit the scope of this issue to the server-side portion of the task. How to display the results on the dashboard UI is reserved for #1239

**Comment by davelab6** [comment]
There should be 1,000s of workers.

**Comment by felipesanches** [comment]
Yes, thousands of worker container instances, but all of them of the same kind. Or perhaps a handful of kinds of containers for each specific task.

**Comment by davelab6** [comment]
Keep it very simple
