### ISSUE TITLE
Display results for production font files on the dashboard

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1239]
Wee need to decide how the check results for the production font files will be displayed on the dashboard. And then I need to implement whatever we decide.

I understand that we'll probably want to have the same level of detail for production files as we have with upstream git-repo files. So Ideally we would simply populate the same page template we already have. On the other hand, we'll probably want to compare side-by-side production against upstream.

@davelab6 do we need to compare in the single-font-file/individual-checks level ?
I can see the value of being able to observe in a glance that a certain check fails on upstream while passing on production (or vice versa).

We may also want to see a comparison in the global level like displaying the progress bars for the check-results summary of prod and upstream side-by-side somewhere in the UI.

This issue is focused on brainstorming this and later implementing it. For tracking the task of implementing the actual server-side fontbakery run on prod files we already have #1238

**Comment by davelab6** [comment]
>  do we need to compare in the single-font-file/individual-checks level ?

Yes, I think so 

> We may also want to see a comparison in the global level 

Also yes

**Comment by felipesanches** [comment]
The idea at the moment is that for each check that diverges between prod and upstream I'll place an icon (in an additional column of the check results table) meaning either "fixed upstream" or "broken upstream / regression"

Then, globally, I'll add to the page header a up/down arrows with the percentages of upstream fixes and of upstream regressions.

**Comment by felipesanches** [comment]
well... simple strings "broken/regression" per check result would be enough actually. And maybe even more efficient at communicating their meaning, perhaps. I think I'll only use icons for the up/down percentage arrows.

**Comment by davelab6** [comment]
That's fine - these kinds of "UX" decisions don't matter at the moment, just anything that 'works' is fine for me at this time :)

**Comment by davelab6** [comment]
I'm re-opening this for @graphite to consider the UI aspects later :)

**Comment by felipesanches** [comment]
OK, cool. But did you mean @graphicore ?

**Comment by graphicore** [comment]
I felt addressed :-)

**Comment by felipesanches** [comment]
Migrating to fontbakery-dashboard issue tracker per #1383
