### ISSUE TITLE
Investigate why some git_repos fail to run fbakery on container-engine

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1240]
I've setup the dispatcher to queue 34 git repos for processing by the worker container.

When the workers run, some of these font projects fail to be properly checked by fontbakery. From 34 projects, only 21 show up in the dashboard UI.

- [x] list which are the specific families for which this happens
- [x] inspect the worker container logs to try to identify the root cause
- [x] fix it :-)

**Comment by felipesanches** [comment]
These are the families (from our initial selection of 34 font repos) that are failing to run fontbakery on the worker container:

* https://github.com/10four/Bhavuka.git
* https://github.com/anexasajoop/cambay.git
* https://github.com/cyrealtype/Adamina.git
* https://github.com/cyrealtype/Alike.git
* https://github.com/cyrealtype/Federant.git
* https://github.com/cyrealtype/Sumana.git
* https://github.com/DunwichType/RhodiumLibre.git
* https://github.com/EbenSorkin/Asar.git
* https://github.com/EbenSorkin/Basic.git
* https://github.com/EbenSorkin/Dekko.git
* https://github.com/EbenSorkin/Kavoon.git
* https://github.com/EbenSorkin/Varta.git
* https://github.com/etunni/glegoo.git

**Comment by felipesanches** [comment]
OK. I just noticed a pattern! These are the families that place the font files right in the root dir. The issue must be related to the way I extract the font-files directory path. I'll surely find a bug in there and fix it :-)

**Comment by felipesanches** [comment]
yes, indeed!

**Comment by davelab6** [comment]
:D
