### ISSUE TITLE
Dashboard: Document the list of all font project git repos that need to be automatically checked.

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1241]
After fixing #1240, I'd like to increase the list of font projects git repos being checked by the dashboard's worker container.

It seems to me that the canonical list of font projects to check against should be whatever we currently have at prod. I know it is 800-something families, but I don't know where to find an official list of them all other than automatically querying Google Fonts itself.

Is there a similar list for the git repos for each of those? I was able to compile a list of a bit more than 104 repos by scraping the google/fonts repo for URLs referencing other repos. (the list is here: https://github.com/googlefonts/fontbakery/issues/1158#issuecomment-273958297) This would be roughtly only 13% of all projects. Does it mean 87% of the projects simply lack a git repo? Or the repos are there and I simply don't know exactly where?

**Comment by davelab6** [comment]
They are scattered around github. Many don't have upstream repos set up yet
but I have SRC data in the old hg repo or my emails archive lol

A CSV or json or .py or whatever list of them needs to be maintained

**Comment by felipesanches** [comment]
Sure! This kind of info is crucialy important. We definitely need to compile this list somewhere.

**Comment by davelab6** [comment]
CSV should be fine

**Comment by felipesanches** [comment]
if by HG you mean Mercurial on Google Code, that's not readable anymore: https://code.google.com/archive/p/googlefontdirectory/source/default/source (I get a 404, actually!)

I also looked up this: https://github.com/blipvert/googlefontdirectory-hg
But I could not find the info in there as well.

@davelab6 Can you clarify where this kind of info could be found online? Or maybe it is only available in your personal data archives?

**Comment by davelab6** [comment]
@m4rc1e has made a Google Docs spreadsheet to collaborative live-edit this data, and there is a public CSV export URL to fetch the data here:

https://docs.google.com/spreadsheets/d/1ampzD9veEdrwUMkOAJkMNkftqtv1jEygiPR0wZ6eNl8/pub?gid=0&single=true&output=csv

I suggest setting up FB to pull from that URL :)

**Comment by felipesanches** [comment]
Sure! I've been chatting with @m4rc1e aobut that earlier today and that's our plan :-)

**Comment by davelab6** [comment]
Regarding the hg repo, yes that's what I meant; lasse has a copy on his
bitbucket.org/graphicore account iirc

**Comment by graphicore** [comment]
it's here: https://bitbucket.org/lassefister/old-googlefontdirectory

**Comment by graphicore** [comment]
> @graphicore Is there any info about URLs of upstream font project repos in there ?

I don't know.

**Comment by felipesanches** [comment]
After a quick glance, I had the impression it does not have that kind of info in there. At least not consistently throughout the family folders. And it may also be outdated info, if any.

But thanks for pointing out the existence of the repo anyway! :-)

**Comment by felipesanches** [comment]
Migrating to fontbakery-dashboard issue tracker per #1383
