### ISSUE TITLE
dashboard: serve static css/js files

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1248]
Right now CSS is hardcoded into html templates because the current container setup does not serve static files.

Doing it will allow us to split out CSS. And also will be important for loading javascript libraries such as a table-sorting one as needed on #1195

**Comment by davelab6** [comment]
Why not use rawgit or whatever to load assets directly from this repo?

**Comment by felipesanches** [comment]
That could work, yeah. But using "python -m SimpleHTTPServer" seems much much better. And it is not hard.

**Comment by felipesanches** [comment]
oh well...

> The resource from “https://raw.githubusercontent.com/googlefonts/fontbakery/master/dashboard/containers/static/css/dashboard.css” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).  0.0.0.0:5000

**Comment by felipesanches** [comment]
hmm... it seems that it is much simple than I thought! I'll try something else now. Let's see...

**Comment by felipesanches** [comment]
OK, it works indeed. I'll simply serve the files from flask itself using the send_from_directory method!

It is cleaner and nicer. Surely won't scale well, but we're not currently dealing with a giant userbase (:-D), so scaling up is not really important right now.

**Comment by felipesanches** [comment]
Alright !!
