### ISSUE TITLE
Not all families are displayed on the dashboard front-page

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1268]
I noticed today that even though we're running fontbakery on a set of 158 families, only 120 of them show up on the front page of the dashboard.

We should:
- [ ] list here which are the ones that are not showing up.
- [ ] inspect their container logs to see if fontbakery failed to run on them serverside.
- [ ] figure out what's causing the problem
- [ ] and fix it.

**Comment by davelab6** [comment]
Shouldn't this be accessible from the dashboard?

I'd like to develop the system to make it more self service

**Comment by felipesanches** [comment]
families are showing up nicely on the front page now and this issue (especialy @davelab6 last comment) made me implement storage of container logs on the database. These logs are now accessible on the family details page.
