### ISSUE TITLE
Dashboard URLs should be more resilient

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1269]
> On 6 April 2017 at 01:02, Felipe Sanches <juca@members.fsf.org> wrote:
> >
> > There's also a hidden "test suite overview" page at http://35.184.229.186/testsuite/ 
>
> Its actually http://35.184.229.186/testsuite

This should work with a slash :) A minor thing

**Comment by felipesanches** [comment]
thanks, Dave!
