### ISSUE TITLE
Review a few name table check results

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1271]
Are these check-results correct, @davelab6? Or are these false-errors ?

If these are bad results, I can add the expected  correct values to our whitelist.

* ERROR: [FONT_FAMILY_NAME(1):MACINTOSH(1)] entry: expected 'Encode Sans Semi Expanded' but got 'Encode Sans SemiExpanded'
* ERROR: [FULL_FONT_NAME(4):MACINTOSH(1)] entry: expected 'Encode Sans Semi Expanded Bold' but got 'Encode Sans SemiExpanded Bold'

**Comment by felipesanches** [comment]
Same question here:

```
ERROR: [FONT_FAMILY_NAME(1):MACINTOSH(1)] entry: expected 'Encode Sans Semi Condensed' but got 'Encode Sans SemiCondensed'
ERROR: [FULL_FONT_NAME(4):MACINTOSH(1)] entry: expected 'Encode Sans Semi Condensed Thin' but got 'Encode Sans SemiCondensed Thin'
ERROR: [FONT_FAMILY_NAME(1):WINDOWS(3)] entry: expected 'Encode Sans Semi Condensed Thin' but got 'Encode Sans SemiCondensed Thin'
ERROR: [FULL_FONT_NAME(4):WINDOWS(3)] entry: expected 'Encode Sans Semi Condensed Thin' but got 'Encode Sans SemiCondensed Thin'
ERROR: [TYPOGRAPHIC_FAMILY_NAME(16):WINDOWS(3)] entry: expected 'Encode Sans Semi Condensed' but got 'Encode Sans SemiCondensed' 
```

**Comment by felipesanches** [comment]
Also this one:

```
ERROR: [FULL_FONT_NAME(4):WINDOWS(3)] entry: expected 'Work Sans Thin' but got 'WorkSans-Thin' 
```

**Comment by m4rc1e** [comment]
@felipe, I'll review this.

**Comment by davelab6** [comment]
Thanks marc!!

**Comment by m4rc1e** [comment]
I remember I wrote about this a while back, #1211. 

Family names should not be camelCase.

>To answer the question, I think spaced rather than camel case is best for
family names, and a single camel case word best for style names

@felipesanches no changes are needed. The upstream repo needs to be updated, I've already done this. The version pushed to GF is ahead and has the names fixed.

**Comment by felipesanches** [comment]
cool, thanks!
