### ISSUE TITLE
Dashboard: Checks 001 through 015 do not show up

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1273]
## Expected behaviour

These checks from 001 until 015 are "cross family" ones. For that reason, they are not stored on the individual font file report json outputs. Instead, they're saved in a file called CrossFamilyChecks.json

## Observed behaviour

There should be a tab for those cross family checks. But it doesn't show up on the dashboard family details page.

**Comment by davelab6** [comment]
Agree

**Comment by felipesanches** [comment]
Migrating to fontbakery-dashboard issue tracker per #1383
