### ISSUE TITLE
Dashboard: Add pagination to the family list on the frontpage

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1282]
We're now dealing with almost a thousand font families. This is too much to show at once at the dashboard front page, so it would be good to add a pagination system to show just a few families per page. Maybe 50 or so...

**Comment by davelab6** [comment]
The webapp still available from http://fontbakery.com dealt with this already, with some nice lazy-loading code. I hope you can use it :)

**Comment by felipesanches** [comment]
Migrating to fontbakery-dashboard issue tracker per #1383
