### ISSUE TITLE
FB module namespaces

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1288]
This is an interesting one.

When you install FB with `python setup.py install`, the modules are going lead to bad namespace pollution.

for instance, to currently import checks.py, you only need the following:

`import checks`

Ideally, everything should be moduled under **fontbakery** so:

`from fontbakery import checks`

**Comment by davelab6** [comment]
Agreed. Also I suspect the Google python fire library can be used to cut
out a lot of arg parse boilerplate and there seems plenty of duplicate code
in the view/fix scripts that set up stuff. As the code became more complex,
more boilerplate has become necessary. And many of those standalone script
files have duplicate code with what is now some check method.

So not only does​ the code base namespace need a clean up, the entire
filetree layout does too, and the peripheral scripts need updating to the
new regime of the check module.

It would be great to get that done before the next version tagged release.

**Comment by graphicore** [comment]
I could do this basically now. I was reading into fb these days. This would help me to get an even better overview.

I don't know how well google fire is for this task though. The control over the resulting CLI is still limited and we'd definitely change the interfaces a lot. Also, the interface for [boolean-arguments](https://github.com/google/python-fire/blob/master/doc/guide.md#boolean-arguments) is IMO not well and the function chaining stuff introduces a rather idiosyncratic behavior (you don't have to use it though).

But: better directory/module layout, reduction of boilerplate, I could do. I'll probably propose some more changes after that, but that needs some more time to distill (just started thinking about this). We should work on our plan for this year in parallel.

**Comment by felipesanches** [comment]
@graphicore 
Thanks, Lasse!

**Comment by m4rc1e** [comment]
> But: better directory/module layout, reduction of boilerplate, I could do. I'll probably propose some more changes after that, but that needs some more time to distill (just started thinking about this)

I've attempted to make use of some FB modules and they need refinement imo. In general, the tests work ok.

It is very difficult to overhaul the objects, whilst committing to the master branch. We should do these interface/decoupling tasks on a separate branch.

I'd like some functional tests in place to make sure we don't further break the working tests.

**Comment by felipesanches** [comment]
@graphicore Indeed, many people (myself included) have expressed interest in having tests to avoid regressions. I'll be glad to review any pull request you may send, either for adding tests or for proposing improvements to the modulatiry of the codebase.

**Comment by felipesanches** [comment]
This has all been addressed in the new fontbakery architecture (already available on master and to be released on 0.3.0)
