### ISSUE TITLE
Dashboard: Move all kubernetes/docker code into a separate git repo

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1296]
Both @m4rc1e and I have agreed that the FontBakery Dashboard deserves to be hosted in a separate code tree.

This will likely require issue #1288 to be fixed first, though.

**Comment by davelab6** [comment]
I agree with this effort but I request lasse deal with it since he will
take on ownership of the dashboard

**Comment by graphicore** [comment]
NP, it's a nice fit with #1288 anyways.
