### ISSUE TITLE
Dashboard: Enable fontforge checks

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1298]
Fontforge checks are not currently running on the worker container.

#1270

**Comment by felipesanches** [comment]
Fontforge instalation commands were added to the worker container image (via Dockerfile apt-get install statements) but the fontforge python module is not found at runtime.

**Comment by felipesanches** [comment]
Migrating to fontbakery-dashboard issue tracker per #1383

**Comment by davelab6** [comment]
How is this a dashboard ui issue?

**Comment by felipesanches** [comment]
Not UI indeed. But that's docker setup for the dashboard infrastructure, so not really FB-core. 

@graphicore are you OK with tracking these docker-related issues here?

**Comment by graphicore** [comment]
Sure, needs to be done there.
