### ISSUE TITLE
Check #003: long halt while trying to validate a DESCRIPTION file hyperlink

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1312]
Something is bad when running "Check #003: Does DESCRIPTION file contain broken links ?".
This may be a connectivity issue specifically related to my own local network. I get a very long halt (actually seems to hang indefinitely) at this point when trying to validate the "www.droidfonts.com" hyperlink:

```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): www.droidfonts.com
INFO     Starting new HTTP connection (1): www.droidfonts.com 
```

I wonder if there's a way to setup a timeout there and log that as a FB warning.

**Comment by felipesanches** [comment]
Yes, we can do it!

http://docs.python-requests.org/en/master/user/quickstart/#timeouts

**Comment by davelab6** [comment]
It loads fast for me :)

**Comment by felipesanches** [comment]
I'll setup an arbitrary 10 seconds delay with a fontbakery warning result in case it times out. This seems to be a local connectivity issue in my network, but this should definitely not block the whole thing running successfully.
