### ISSUE TITLE
unicode-org/text-rendering-tests could be useful?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1332]
Rod suggested unicode-org/text-rendering-tests (eg https://rawgit.com/unicode-org/text-rendering-tests/master/reports/fontkit.html) could be relevant to font-onboarding. Any suggestions @graphicore @m4rc1e ? :)

**Comment by felipesanches** [comment]
I found it weird that all expected/observed SVGs in that page seem to be flipped upside-down...

**Comment by felipesanches** [comment]
The link that @davelab6 posted is the generated results page. The actual testsuite project is available at https://github.com/unicode-org/text-rendering-tests

**Comment by rsheeter** [comment]
(posting some comments I made internally here too)

We have some degree of testing for things like "fsSelection is wrong" but less on the rendering front. I might imagine a set of tests made up of things to render + indication of what the expected result is / what to look out for in a broken font. Bonus points for training a model to recognize violations automatically :D

To try to spitball an actual example, they have stuff like "If your implementation is correct, each rendered glyph should show ...". We might have stuff like "If your font is correct the rendered glyph(s) should have <some characteristics>". Thinking "aloud", maybe for pairs that are usually kerned we render those pairs, a warning if there is no kerning rule, and a note about how and why the pair is typically kerned.

We might warn if things that are usually whitespace draw ink [a real problem we've seen]. We might warn if things that usually draw ink don't.

If we know what the previous version is, which we often do for Google Fonts, we might warn/highlight for manual review any glyph that changed a lot or perhaps if the rendering of any of a set of test strings has changed a lot.
