### ISSUE TITLE
Search for MS FontValidator.exe in the system path

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1336]
We have a binary of MS FontVal available at the prebuilt/fval directory in our repository (I built it from sources a while ago because I could not find any other way of installing it on my system and on the kubernetes cluster).

The code invokes it with the explicit path of the prebuilt/fval directory (thus assuming incorrectly that the code will always be running from the root of the git tree). The recent split of repos with the dashboard going to its own repo, made it clear that it is wiser to make FontBakery look for third-party tools in the system path. Anything else should be done as an installation procedure.

The goal of this issue is to make this change to the check.py code as well as to add documentation on README.md instructing the users (and @graphicore :-D) on how to setup MS FontValidator on their systems (and on the FontBakery-Dashboard kubernetes cluster).

**Comment by felipesanches** [comment]
OK. I tried to setup this on my system by adding the **prebuilt/fval** directory to the system path:
```
export PATH=$PATH:/home/felipe/devel/github_felipesanches/fontbakery/prebuilt/fval/
```

...but got this error:

```
INFO     INFO: Microsoft Font Validator returned an error code. Output follows :

Error: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
```

**Comment by felipesanches** [comment]
...but that's not a PATH issue. I must be missing some extra mono-runtime package (I reinstalled my distro last week. Great opportunity for documenting the dependencies :-D)

**Comment by felipesanches** [comment]
Probably this will do:

```
sudo apt-get install mono-complete
```

But I dislike installing everything! There must be a cleaner way of installing only what is needed in our case.

**Comment by felipesanches** [comment]
I had a hunch that maybe this would be a cleaner solution for satisfying this dependency:

```
sudo apt-get install mono-reference-assemblies-4.0
```

But it didn't. I'll resort to installing mono-complete for now. If someone has a hint of a smaller install footprint I'll be glad to update the docs.

**Comment by felipesanches** [comment]
hey! I just figured it out!

This is a good one:
```
sudo apt-get install libmono-system-windows-forms4.0-cil
```

Installed and running! Yay!

**Comment by davelab6** [comment]
Sweet :)
