### ISSUE TITLE
Do not generate reports into same folder

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1340]
It's a little annoying when you run check-ttf.py which then dumps the Ms Validator reports in your shiny google/fonts family dir.

![screen shot 2017-05-10 at 12 39 37](https://cloud.githubusercontent.com/assets/7525512/25896873/c5c7f09a-357d-11e7-909a-969f3a9deba4.png)
*before*

![screen shot 2017-05-10 at 12 41 45](https://cloud.githubusercontent.com/assets/7525512/25896965/0e9b2076-357e-11e7-9753-35cd6d6cdeba.png)
*after*

I recommend these are stored elsewhere.

**Comment by felipesanches** [comment]
ok, cool. Let's avoid that!

**Comment by m4rc1e** [comment]
Thanks man!

**Comment by davelab6** [comment]
It may also be nice to put all output in $pwd/FB/* so that we can add that
to gitignore files
