### ISSUE TITLE
check-ttf.py: Canonical font checks

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1342]
I'm confused why we have two of these in the same script.

https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/checks.py#L101-L121

https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/checks.py#L2957-L2979

The first one seems to be a condition that needs to be met in order for the test suite to run. The second is just a test.

**Comment by felipesanches** [comment]
@m4rc1e This is indeed confusing! Thanks for pointing out.

One checks the TTF filenames. The other one checks the METADATA.pb file.

I agree with you that this is not clear and that there may be problems with this. For instance, I think that the METADATA.pb check could simply verify that the name declared in its metadata fields match the available TTF files, while the actual rules for the names should be in that other initial check.

**Comment by felipesanches** [comment]
I also noticed that a single non-canonical TTF filename inhibits the execution of the rest of the checks on the whole family. Maybe a better approach would be to report the issue and drop the non-canonically named TTF files from the list of TTF files to be checked, but proceed with the other ones.
