### ISSUE TITLE
Figure out and implement optimizations for the pyfontaine checks

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1347]
@davelab6 suggested at #1345 that we could run pyfontaine subprocesses in parallel, starting them very early in the testsuite. This is not simple to achieve with the current architecture, but perhaps can be addressed by @graphicore 's proposal of a new architecture for FontBakery, described at: 
https://gist.github.com/graphicore/9456bdbdaf1276b52e56fc817a175058

**Comment by davelab6** [comment]
@graphicore can this be addressed now?

**Comment by graphicore** [comment]
This consists of two parts:

1. run in paralell.
2. find a good separation of tests for the parallel processes.

Run in parallel, here means on a multicore processor, right? In Kubernetes we'll do this a bit differently,  via worker instances.

Also, can we rethink the Pyfontaine tests? Most of them fail by default, that's bad.

And, why is it so slow? I did something like this with the specimen tools and it was not even blocking the browser UI, unless I'm missing something. I don't really trust the whole thing.

**Comment by graphicore** [comment]
Uh, yeah, so run in parallel is not so hard to do, but still some work, but I think we have a good standing for this,

**Comment by davelab6** [comment]
> This consists of two parts:
> 
> 1. run in paralell.
> 
> 2. find a good separation of tests for the parallel processes.
> 
> Run in parallel, here means on a multicore processor, right? In Kubernetes we'll do this a bit differently, via worker instances.

Well, if you run a k8s cluster locally, then I believe k8s will load-balance a pod of containers across your cores, I think. 

...

So yeah: 

>> One cpu, in Kubernetes, is equivalent to: ... 1 Hyperthread on a bare-metal Intel processor with Hyperthreading
> - https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu

and

>> For each processor core that is physically present, the operating system addresses two virtual (logical) cores and shares the workload between them when possible.
> - https://en.wikipedia.org/wiki/Hyper-threading

> Also, can we rethink the Pyfontaine tests? Most of them fail by default, that's bad.

Yeah, I was just discussing language support testing with the GF team, and currently its a mess. As you know, CLDR is the current state of the art, and this is packaged in pyfontaine, but, actually language support requires testing a font against 3 things:

1. encoded glyphs (like in CLDR)
2. OT feature codes
3. unencoded glyphs corresponding to the above

AFAIK pyfontaine can only check for 1 and 3 at the moment. 

> And, why is it so slow? I did something like this with the specimen tools and it was not even blocking the browser UI, unless I'm missing something. I don't really trust the whole thing.

Yep, I have no idea why it is slow. I'm happy to abandon it if we need to. 

> Uh, yeah, so run in parallel is not so hard to do, but still some work, still I think we have a good standing for this

Ideally I want to have a dashboard showing how the current font collection in production passes/fails every FB check, including language support checks; and how every upstream associated with each of those families passes/fails. 

This requires massive parallelism.

**Comment by felipesanches** [comment]
Pyfontaine checks were deprecated a while ago, so this issue is now invalid, so I'm closing it.
