### ISSUE TITLE
OS/2 usWeightClass vs. CSS font-weight

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#1355]
I'm checking right now Roboto Slab Thin.

Metadata.pb has `weight=100`
The font itself has `openTypeOS2WeightClass=250`

Font Bakery suggests to change the value within the font to match Metadata.pb i.e. `100`.

We usually use `250` for Thin, the CSS-weight value is however `100` in that case. I'm not sure what to do but it feels like FB is wrong and the font is OK. This is, if the Metadata.pb `weight` key refers to the CSS `font-weight`.

```
### Checking OS/2 usWeightClass matches weight specified at METADATA.pb
* ERROR: OS/2 usWeightClass matches weight specified at METADATA.pb Changes that must be applied to this font: OS/2 usWeightClass from 250 to 100
```

**Comment by m4rc1e** [comment]
@graphicore FB is wrong in this instance. The font's OS/2 weight value should be 250, whilst the METADATA.pb should be 100. Fonts need 250 because of [issues in older browsers](https://www.adobe.com/devnet/opentype/afdko/topic_font_wt_win.html)

**Comment by graphicore** [comment]
Thanks @m4rc1e for confirming.

**Comment by m4rc1e** [comment]
fyi, the METADATA.pb weight value is inferred from the [filename](https://github.com/google/fonts/blob/master/tools/util/google_fonts.py#L62-L73), not the font metadata.

**Comment by felipesanches** [comment]
Thanks, @m4rc1e and @graphicore 

I'll take a look at this and open a pull request with a fix.

**Comment by felipesanches** [comment]
FontBakery check number 020 ("Checking OS/2 usWeightClass") seems good since it takes into consideration the Windows GDI issues and makes sure the font **usWeightClass** entry on the **OS/2** table follows the rule described in its doc-string:

```
The Google Font's API which serves the fonts can only serve
  the following weights values with the  corresponding subfamily styles:

  250, Thin
  275, ExtraLight
  300, Light
  400, Regular
  500, Medium
  600, SemiBold
  700, Bold
  800, ExtraBold
  900, Black

  Thin is not set to 100 because of legacy Windows GDI issues:
  https://www.adobe.com/devnet/opentype/afdko/topic_font_wt_win.html
```

On the other hand, Fontbakery check number 112 ("Checking OS/2 usWeightClass matches weight specified at METADATA.pb") expect both **OS/2** table and **METADATA.pb** to have the exact same values. It is one of may checks that validate coherence between opentype tables and METADATA.pb entries.

This makes me wonder why METADATA.pb is meant to have diverging weight values? (Is it really?)

**Comment by felipesanches** [comment]
Also, this is a good opportunity to address this apparent inconsistency in the constants.py file:

```
# Weight name to value mapping:
WEIGHTS = {"Thin": 250,
           "ExtraLight": 275,
           "Light": 300,
           "Regular": 400,
           "Medium": 500,
           "SemiBold": 600,
           "Bold": 700,
           "ExtraBold": 800,
           "Black": 900}

WEIGHT_VALUE_TO_NAME = {
  100: 'Thin',
  200: 'ExtraLight',
  300: 'Light',
  400: '',
  500: 'Medium',
  600: 'SemiBold',
  700: 'Bold',
  800: 'ExtraBold',
  900: 'Black'
}
# FIXME: Shouldn't the two dicts above be merged into a single
#        one and have code refactored to use the single source
#        of numerical value to weight name ?
```

**Comment by graphicore** [comment]
> This makes me wonder why METADATA.pb is meant to have diverging weight values? (Is it really?)

Yes, Metadata.pb is, at least in this case, about the CSS `font-weight` which will be used by the google fonts users to select the fonts. The mapping there is:

```
  100, Thin
  200, ExtraLight
  300, Light
  400, Regular
  500, Medium
  600, SemiBold
  700, Bold
  800, ExtraBold
  900, Black
```

At least, that's my understanding of it.

**Comment by felipesanches** [comment]
If there's any good reason for us to be using diverging weight-name-to-value mapping criteria, then this should be explicit in the source code doc-strings as well as perhaps in the user error/warning messages.

@m4rc1e and/or @davelab6 : Could you please clarify if there are supposed to be, indeed, diverging criteria between METADATA.pb and OS/2 table weight entries ?

**Comment by felipesanches** [comment]
thanks, @graphicore !

So would it make sense to rename the dicts above this way?

* **WEIGHT_VALUE_TO_NAME** => **CSS_WEIGHT_VALUE_TO_NAME**
* **WEIGHTS** => **WEIGHT_CLASS_VALUE_TO_NAME** (and also invert the key-value association of this dict so that the more uniform dict naming-scheme makes sense)

**Comment by felipesanches** [comment]
And then check number 112 could be deprecated (as the values are not meant to be identical) or, even better, could be fixed to use these 2 dict for checking the coherence of the values with each of the critera.

**Comment by felipesanches** [comment]
OK. New check implementation results, for Roboto Slab, in the following message:

```
INFO     OK: OS/2 usWeightClass (250) matches CSS weight (100) specified at METADATA.pb 
```

**Comment by davelab6** [comment]
Yeah I think you fixed it. There are 2 values to the filename key, one for
os/2 and one for css, and they are the same for 300 to 900 but the first
two diverge
