### ISSUE TITLE
Add command-line switch to optionally disable the progressbar

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1357]
It is not really useful. In the move towards cleaner code, I'll simply delete it.

**Comment by davelab6** [comment]
If the goal is cleaner code,

**Comment by felipesanches** [comment]
OK. The progressbar code is not really that bad. It is not really a lot of code. Reality is that I had implemented it in the past by impulse and I thought nobody else really liked it (I didn't like it a lot myself, by the way, especially because stderr messages end up breaking the progressbars apart at some occasions, which looks ugly).

If you think it is really useful, I'm happy to bring it back. :-D

**Comment by davelab6** [comment]
I suggest turning it off by default and having a `--progress` arg :)

**Comment by felipesanches** [comment]
Then we'll be burying a useful feature and likely no one will be using it so often :-)

**Comment by felipesanches** [comment]
...but I can do it, of course !

**Comment by davelab6** [comment]
Right... So, maybe better to have it on my default and then be able to hide if the output needs to be 'clean'? :)

**Comment by felipesanches** [comment]
sure! That's much much better, I think
