### ISSUE TITLE
clean up dependencies

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#1367]
We still have "fontbakery-dashboard" dependencies in `requirements.txt` (`python-dateutil`?, `pika`, `rethinkdb`)

`fontTools` is not installed with `pip install git+https://github.com/googlefonts/fontbakery`

So, we should remove all dependencies that are dashboard only.

I'd also like to see only one place for dependencies, which is `setup.py`. `requirements.txt` can be removed. To install from the git repo for local editing `pip install -e .` should suffice and make the `pip install -r requirements.txt` command obsolete.

Alternatively, it should be possible to parse the contents of  `requirements.txt` in `setup.py` and fill `setup(install_requires=[ ... ])` with the results (I'm not sure if the syntax is the same, but it looks like). For me, it's only important to have a single point of truth.

* * * 

Edit from davelab6, Marc wrote: 

Currently, the installation process is too convoluted and prone to errors.

I can think of a few very problematic places:
- magic
- pyicu
- Headless font forge

I've spent a good two hours trying to deal with getting it to run on two users machines. I got mine to work by solving dependency errors as I went through them step by step. This isn't acceptable imo.

Installation should be create as simple as 

```
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
pip install -e . (for dev mode)
```

**Comment by felipesanches** [comment]
sounds good :-)

**Comment by anthrotype** [comment]
https://caremad.io/posts/2013/07/setup-vs-requirement/

**Comment by felipesanches** [comment]
Hey! Thanks, @anthrotype for referencing that article. It seem to be very informative. I'll read it carefully as it seems to address exactly the kind of problems we have to deal here.

Cheers!

**Comment by felipesanches** [comment]
I reviewed and cleaned up dependencies recently. And reviewed it again this week. The current setup looks reasonable to me. There's some confusion about the role of requirements (which actually lead to another mention of that same article pointed out by @anthrotype) going on at #1523 

I'll close this and if there's still any issue to be discussed regarding requirements.txt, then the best place to do so is really at that #1523 conversation.

Other than that, please reopen this issue if you actually think there are problems with the current listing of dependencies.
