### ISSUE TITLE
check-ttf.py: ERROR:root:No family found in GWF in http://fonts.googleapis.com/css?family=<family>

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1370]
This error should be a warning instead, otherwise all new fonts won't pass this test.

**Comment by davelab6** [comment]
@felipesanches this should be very quick :)

**Comment by davelab6** [comment]
@felipesanches is this done in the rewrite?

**Comment by felipesanches** [comment]
Done!
