### ISSUE TITLE
check-ttf.py: ERROR:root:METADATA.pb: '%s' is a CamelCased name. To solve this, simply use spaces instead in the font name.

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1371]
Firstly, '%s' should probably be the family name. Secondly, is this really necessary? this test will fail for families which break this rule, e.g VT323, PT Sans, Amatic SC.

**Comment by felipesanches** [comment]
OK. the %s was indeed wrong and should instead be {}. I'm fixing that now.

Regarding the supposed failures, that's not going to happen for names like VT323, PT Sans, Amatic SC because there's a plus in the regex requiring at least one lowercase letter in each word of a camelcase name:

``` python
if bool(re.match(r'([A-Z][a-z]+){2,}', font_metadata.name)):
```

**Comment by felipesanches** [comment]
There currently are no exceptions in this test implementation.

I will also write a self-test that assures us that these example good family names won't ever FAIL this test.
