### ISSUE TITLE
pip installing FB does not include all scripts

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1378]
Hey folks,

Christoph Koeberlin pointed out that pip installing FB does not include all of the scripts.

![screen shot 2017-06-06 at 10 37 24](https://cloud.githubusercontent.com/assets/7525512/26823073/2a591d32-4aa4-11e7-8170-dcd52f093c9b.png)

There's no fix-fsselection.py etc

**Comment by graphicore** [comment]
it must  be mentioned in setup.py. https://github.com/googlefonts/fontbakery/blob/master/setup.py#L66
We should probably write a function that collects all these scripts and registers them, simmilar to https://github.com/googlefonts/fontbakery/blob/master/bin/fontbakery#L9 (maybe we should reuse this, so there's no difference ever)

**Comment by davelab6** [comment]
Sounds good, @felipesanches could you take care of this?

**Comment by felipesanches** [comment]
I reviewed and fixed this earlier this week and released FontBakery v0.2.1 on pypi. See https://github.com/googlefonts/fontbakery/issues/1406#issuecomment-312751979

**Comment by davelab6** [comment]
Please automate the process so we don't regress on this
