### ISSUE TITLE
TTFs must not have RFNs unless they are on a whitelist. 

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1380]
We must have a test for `Reserved Font Name` in the name table strings, and unless its on a whitelist, we must error, not warn.

**Comment by felipesanches** [comment]
We do have an RFN test for the copyright field of METADATA.pb at com.google.fonts/test/103

```python
@register_test
@test(
    id='com.google.fonts/test/103'
  , conditions=['font_metadata']
)
def check_Copyright_notice_does_not_contain_Reserved_Name(font_metadata):
  """Copyright notice does not contain Reserved Font Name"""
  if "Reserved Font Name" in font_metadata.copyright:
    yield WARN, ("METADATA.pb: copyright field (\"{}\")"
                 " contains \"Reserved Font Name\"."
                 " This is an error except in a few specific"
                 " rare cases.").format(unidecode(font_metadata.copyright))
  else:
    yield PASS, ("METADATA.pb copyright field"
                 " does not contain \"Reserved Font Name\".")
```

But we do not have one for the name table strings. So I'll create one now!

**Comment by felipesanches** [comment]
Done!

New test:
**com.google.fonts/test/152**
'''Name table strings must not contain 'Reserved Font Name'.'''

**Comment by davelab6** [comment]
@RosaWagner requested making the allowlist a separate text file in the codebase, to make maintaining the list more easy.

**Comment by davelab6** [comment]
Moving to new issue
