### ISSUE TITLE
Small UX tweaks

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1382]
In https://groups.google.com/d/msg/googlefonts-discuss/x2oRYyP4gMQ/Ests8XivAQAJ @graphicore describes his latest progress with hooking up fontbakery in docker containers on Google Cloud Platform. Over the summer he says there will be,

> some usability work, though, we could be better off waiting for this until we got more basic stuff sorted out, like the refactoring of fontbakery (will lead to more instant feedback, i.e. we won't need a progress spinner ...)

Rather than doing nothing, and rather than doing more intense UX work, I would just a few small tweaks, while the refactoring is happening :) 

- [x] The huge divs used in http://104.197.213.179 are fun but actually simple HTML form buttons would be more clear what to click on, and subcommunicate that this is early stage work, I think :) 

- [x] The `stdout` output has ANSI color codes like `[1;33;40mErrors[0m:` which could be interpreted using https://github.com/drudru/ansi_up (so just a HTML/JS change, no fontbakery change needed)

- [x] A progress spinner is needed, but at the top of the demo page there is,

> isFinished  true 

And the progress indicator could just be a simple `🕒` character with a large `font-size` when isFinished  is false :)

Looking at the overall page, there is much to do! :) 

![screen shot 2017-06-13 at 14 16 11](https://user-images.githubusercontent.com/261579/27097810-7c424d72-5043-11e7-93cc-ac10fb0d305d.png)

**Comment by graphicore** [comment]
> using https://github.com/drudru/ansi_up 

Thanks, I googled for something like this without luck :-)

> Looking at the overall page, there is much to do! :)

Yeah, I was caring to get all the info we produce into a usable form, not to make it look nice :-)

**Comment by davelab6** [comment]
> Yeah, I was caring to get all the info we produce into a usable form, not to make it look nice :-)

All good! This is already good and I know you can make it awesome! :D

**Comment by graphicore** [comment]
@davelab6 we should use https://github.com/googlefonts/fontbakery-dashboard for issues.

**Comment by graphicore** [comment]
Buttons:

![selection_144](https://user-images.githubusercontent.com/393132/27125351-4e595304-50f4-11e7-9447-e12e53f2ce98.png)

ansi_up:

![selection_145](https://user-images.githubusercontent.com/393132/27125416-754ea360-50f4-11e7-9d78-c5121c71d8b7.png)

**Comment by davelab6** [comment]
Thanks! I mean the buttons on the first page (where you drop the fonts)

**Comment by graphicore** [comment]
> Thanks! I mean the buttons on the first page (where you drop the fonts)

:joy: Here you go:

![selection_146](https://user-images.githubusercontent.com/393132/27225452-7bf43282-529a-11e7-97bb-60a29ddbe8a0.png)

It's not at a big size, but it is spinning:

![selection_147](https://user-images.githubusercontent.com/393132/27225489-bca69acc-529a-11e7-9065-edacc333af67.png)


And then it's DONE!:

![selection_148](https://user-images.githubusercontent.com/393132/27225544-0d72a04a-529b-11e7-8b50-0929cf724a56.png)

**Comment by davelab6** [comment]
Love it
