### ISSUE TITLE
Check for OpenType Features that help languages work 

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1384]
## Observed behavior

OpenType features we should always have, if a script is supported, are not checked for. 

## Expected behavior

The features listed in https://github.com/google/fonts/issues/1038#issuecomment-308521425 (and others) should be checked for :)

## Resources and exact process needed to replicate

GSUB/GPOS parsing required; I guess we need positive examples of fonts with the features to model with. @alexeiva any suggestions?

**Comment by felipesanches** [comment]
@alexeiva any suggestions ?

**Comment by alexeiva** [comment]
A sample of `locl` can be tested on [Yanone Kaffesatz](https://github.com/alexeiva/yanone-kaffeesatz), [Vollkorn](https://github.com/FAlthausen/Vollkorn-Typeface) 

Try switching the locale between Russian, Bulgarian, and Serbian using `бульдог` as a test string.

The `locl` feature works in Chrome(left) but not in Safari(right) as tested on http://www.cyreal.org/Font-Testing-Page/index-cyrillic.php, OS 10.11.

![screen shot 2017-07-14 at 3 08 59 pm](https://user-images.githubusercontent.com/16634089/28215158-a44a7e86-68b5-11e7-857d-be03a91c9b05.png)

**Comment by davelab6** [comment]
@felipesanches this will become important in Q1 :)

**Comment by simoncozens** [comment]
This is the same as #1188, and both will be fixed by shaperglot.

**Comment by kenmcd** [comment]
> both will be fixed by shaperglot

What is shaperglot? Can we see it anywhere?

**Comment by simoncozens** [comment]
"will" is future tense. :-) But you can see where it "will" be at https://github.com/simoncozens/shaperglot

**Comment by kenmcd** [comment]
> "will" is future tense. :-) But you can see where it "will" be at https://github.com/simoncozens/shaperglot

Thanks!
