### ISSUE TITLE
[new-arch] Port FB checks to Lasse's new proposed architecture

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1388]
Me and @graphicore  have just had an awesome 2-hour technical videochat session in which he showcased the new FontBakery infrastructure he designed and implemented. It's pretty great! :-D

Lasse pushed his code into this git branch:
https://github.com/googlefonts/fontbakery/tree/refactor-architecture

And he gave me all the initial guidance on how to port our test-suite into that new framework. I'll be porting all checks and giving feedback to Lasse on any shortcomings of the new engine that I may stumble upon during the process. I guess this may take a week or too to achieve, but I'll update/refine this estimate after the end of next week.

Thanks a lot, Lasse for the work you've done!

This issue is meant for tracking the check porting work.

**Comment by davelab6** [comment]
Amazing to see all the commits that went into this :D
