### ISSUE TITLE
Can we already specify a single check-id to be performed ?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1392]
On the new architecture designed & implemented by @graphicore, can we specify a single check (from a given specification) to be performed? This would be pretty useful for debugging during development.

I would love to be able to do something like:

```
fontbakery --checkid com.google.fonts/test/031 ~/gfonts/ofl/merriweathersans/*.ttf
```

And run only the check number 031 from the google fonts specification ("Description strings in the name table must not contain copyright info.") on a given family.

If I recall correctly that was one of the benefits of the new architecture.

**Comment by felipesanches** [comment]
The syntax I suggested above could be something else, of course. (I seems we would need at least a subcommand name in there, for instance)

**Comment by graphicore** [comment]
I'll add this.

**Comment by felipesanches** [comment]
cool, thanks!

**Comment by graphicore** [comment]
Until then, temporarily for now, I suggest you change the spec definition directly to something like this:

```py
specificiation = Spec(
    conditions=conditions
  , testsections=[Section('Default', [check_description_strings_must_not_contain_copyright_info])]
  , iterargs={'font': 'fonts'}
  , derived_iterables={'ttFonts': ('ttFont', True)}
)

```

**Comment by felipesanches** [comment]
ok, thanks
