### ISSUE TITLE
Github API script for tracking issue progress

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1397]
I need a standalone script that can tell me, for a given time range, how many github issues were opened and closed, and of those closed, how many by pull requests. 

This could be simple command line python (or even bash) script to start, although I expect in long future it will be JS to graph results on a webpage direct from the Github API. For now I just need the numbers for management, eg

> On $month 1st, $A issues existed. By $month+3 1st, we merged $B PRs ($BP %), had $C open pull requests ($CP %), and $D new issues were added, thus $C issues have fixes pending and $E are yet to be fixed.

This may already exist elsewhere on the web...

* https://coderwall.com/p/hot7ga/list-add-edits-github-issues-from-shell-scripts
* https://github.com/kosamari/github-api-scripts/blob/master/repo-contributors/contributing_users.py     
* https://github.com/github-tools/github

This seems to have all the needed source data:

    curl https://api.github.com/repos/google/fonts/issues | more

**Comment by m4rc1e** [comment]
>This seems to have all the needed source data:
`curl https://api.github.com/repos/google/fonts/issues | more`

Github's api uses [pagination](https://developer.github.com/v3/#pagination). Your approach will only return the last 30 entries. I'm writing it so the script will traverse all the pages it needs.
