### ISSUE TITLE
[new-arch] com.google.fonts/test/003: Should we accept "mailto:" URLs on Description files ?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1404]
![screenshot at 2017-06-27 20 07 44](https://user-images.githubusercontent.com/213676/27613875-6c20ad30-5b74-11e7-947e-956b317a93ce.png)

**Comment by felipesanches** [comment]
I think it is likely OK to accept mailto entries. But I'd like to hear your opinion @davelab6

**Comment by davelab6** [comment]
Yes but we need a collection wide level check to list them out, to confirm
they are valid
