### ISSUE TITLE
Deprecate fontbakery.appspot.com with redirect

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/fontbakery#1406]
## Observed behaviour

I tested the four v.2.020 Hack ttf typeface sets (regular, italic, bold, bold italic) on the Appspot application in Chrome 59.0.3071.115 and Firefox 55.0b2 (64-bit) on OS X 10.12.5 and receive test results for all of the sets except the italic set. 

The problematic font file is properly detected when DnD on to the browser:

![font_select](https://user-images.githubusercontent.com/4249591/27645431-0b7b9582-5bf4-11e7-9a38-9411af17afee.png)

When section 3 is clicked, the initial popup that indicates that the analysis is taking place is displayed briefly and then it closes without results displayed in both browsers for the italic set.  The application appears back at its default state like this:

![default_app](https://user-images.githubusercontent.com/4249591/27645734-d8034280-5bf4-11e7-9734-3964f77f9509.png)

Please let me know if I can provide additional information.  Thanks!

## Resources and exact process needed to replicate

https://github.com/chrissimpkins/Hack/releases/download/v2.020/Hack-v2_020-ttf.zip

**Comment by davelab6** [comment]
@chrissimpkins the appspot page is stale. @felipesanches can you put up a redirect on that URL to the new one

**Comment by chrissimpkins** [comment]
thanks! will wait for latest release and give it another try

**Comment by davelab6** [comment]
Oh, actually https://github.com/googlefonts/fontbakery/commits/master should be good fo ryou

**Comment by graphicore** [comment]
current,  but not very mature: http://104.197.213.179/

Feel free to test and report issues here: https://github.com/googlefonts/fontbakery-dashboard/issues

**Comment by chrissimpkins** [comment]
> Oh, actually https://github.com/googlefonts/fontbakery/commits/master should be good fo ryou

Ok, thanks Dave.

> current, but not very mature: http://104.197.213.179/

👍  thank you!

**Comment by chrissimpkins** [comment]
@graphicore the application release in the URL that you linked fixed the issue with our italic build.  The application works great.  I like the stdout and stderr displays on the new page.

![fontbakery](https://user-images.githubusercontent.com/4249591/27666845-a3a10978-5c44-11e7-8481-b7dbc848dc26.png)

Will leave this open for Dave's request to include a URL redirect in https://github.com/googlefonts/fontbakery/issues/1406#issuecomment-311821672 

Thanks guys!

**Comment by chrissimpkins** [comment]
@davelab6 Is the `master` version of v0.2.0 current with reported documentation on README?  (Re-)Installed with pip from FontBakery Github repo (Ubuntu Linux 16.04.2) after identifying the following problem with:

`pip install --upgrade git+https://github.com/googlefonts/fontbakery.git`

Here is what I am seeing:

![fontbakery_error](https://user-images.githubusercontent.com/4249591/27763971-655a081c-5e5c-11e7-815e-d774078390b3.png)

Help text differs from that on the README (doesn't include the fix-dsig subcommand and others) and I can't find an approach with the `--autofix` flag that allows for this command to execute properly.  Let me know if you would like this as a formal issue report.  I may have missed something on my end with the install...

**Comment by davelab6** [comment]
Felipe, could you check on this? I thought you and Lasse we're working on a
branch and master would remain usable/stable , close to the 0.2.0 release...

**Comment by felipesanches** [comment]
@chrissimpkins I have just released fontbakery v0.2.1 with a fixed setup.py script including the script that was missing in the previous release. Can you try installing again and tell me if that works for you?

https://pypi.python.org/pypi/fontbakery/0.2.1

**Comment by chrissimpkins** [comment]
Can confirm that I installed v0.2.1 from PyPI with `pip install --upgrade fonttools`, that the help menu is expanded with the subcommands that are included on the README file, and that fix-dsig, fix-nonhinting (only autofixes that I have tried so far...) both appear to execute without any issues.  Thanks Felipe!!

**Comment by davelab6** [comment]
Thanks Felipe!!

**Comment by felipesanches** [comment]
We don't advertise the old webapp on README anymore. And the old app code has migrated into https://github.com/googlefonts/fontbakery-dashboard/ 

This issue does not belong here anymore.

**Comment by davelab6** [comment]
Ok, but please file another one so this doesn't get forgotten :)
