### ISSUE TITLE
Add check-font-version.py usage to README.md

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1416]
One thing I forgot to mention while reviewing https://github.com/googlefonts/fontbakery/pull/1415 was that we should always update README.md with usage instructions whenever we add new scripts (or when we add/remove/modify the arguments list)

Can you do that for  check-font-version.py , @m4rc1e  ?

**Comment by m4rc1e** [comment]
Good incentive. I will add them from now on.

Apologies for forgetting this in past prs.

**Comment by felipesanches** [comment]
:-)

**Comment by davelab6** [comment]
Felipe, could you add a simple unit test to grep readme for each script's
filename, such that we always get a simple reminder about this on each pr
that adds a new script? :)
