### ISSUE TITLE
[new-arch] avoid try/catch on ttfautohint_stats condition implementation

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1421]
@graphicore suggested at https://github.com/googlefonts/fontbakery/pull/1419/files/f706952d2c7c5cd74d5d2249e17757927a5dc3e7#r125860799 that it can be better (more informative) to let a condition crash instead of using a too broad try/catch block around it.

He was refering to the ttfautohint_stats condition, but we may have this as a general rule for all conditions (not to use too broad try/catch blocks anymore)

**Comment by graphicore** [comment]
I'll actually try this and see how the runner behaves if we let exceptions in conditions pass, but I'm pretty sure I thought about this already.

**Comment by felipesanches** [comment]
We still use try/catch blocks in the code where I consider it to be useful and generally safe. This is, of course, a subjective matter. I currently think we're good with the current state of the code in that regard.
