### ISSUE TITLE
xAvgCharWidth: different calculation in common tools. Revisiting rounding issues.

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#1428]
## Observed behaviour

Fontbakery *occasionally* expects a different value than ufo2ft (used by fontmake) produces.

## Expected behaviour

Both implementations should use the same method and produce the same values for `xAvgCharWidth`, as this is our common tool chain;

## Resources and exact process needed to replicate

`xAvgCharWidth` is found in many closed issues [by searc](https://github.com/googlefonts/fontbakery/issues?utf8=%E2%9C%93&q=is%3Aissue%20xAvgCharWidth%20) so this is a real classic :joy:

I was only looking at the version 3 implementation BTW, which was merged here: #636

I believe the most interesting issue, that led to our current state is #855 with mentioning https://gist.github.com/jtanx/7715851 (emphasis mine):

> Do **integer division** of this sum by the number of glyphs that had an advancement width > 0.

However, checking the [OT spec](https://www.microsoft.com/typography/otspec/os2ver3.htm#acw) we get:

> The value for xAvgCharWidth is calculated by obtaining the arithmetic average of the width of all non-zero width glyphs in the font.

So, **no mention** of an **integer division**, but of course at some point our value **must** become an `int`.

Our code now:

```py
 expected_value = int(round(width_sum) / count)
```

We use python 2 and we don't import the `__future__.division` module (which I strongly recommend for the new stuff we're doing, makes it easier to go to python3). It's not that important, since `round` produces a `float` in any case, though, it's just VERY implicit without that division module.

I also doubt that using round at this point is correct, I'd rather do (just to make sure we have an integer division but without affecting the result prior rounding (even better would be to import the new division operators):

```py
 expected_value = int(float(width_sum) / count)
```

Much more important is, that `int` produces an integer with the floating points values just removed, like a `ceil`, or like the suggested  **integer division** would have done.

Our supplier [ufo2ft (fontmake)](https://github.com/googlei18n/ufo2ft/blob/1f2e0c721fd4c33ed61fc650b5ac23121d107891/Lib/ufo2ft/outlineCompiler.py#L429) uses *floating point division* (they do `from__future__ import division`) and then they round:

```py
# average glyph width
widths = [glyph.width for glyph in self.allGlyphs.values() if glyph.width > 0]
os2.xAvgCharWidth = round(sum(widths) / len(widths))
```
(Here's no explicit conversion to the `int` type, though, `fontTools` will do it, the value is unambiguous at this point anyways.)

The question here is, who is right: **integer division**  or **floating point division** then `round` then `int` conversion?

**Comment by felipesanches** [comment]
Thanks, @graphicore ! That's insightful. But how would we decide which should be correct? Unless we have stronger evidence for a normative definition of the correct calculation, I think we may have to resort to arbitrarily choosing one. And in that case I'd choose the most commonly seen "in the wild". Which seems to be the fontmake way.

**Comment by graphicore** [comment]
Thanks Felipe, I also just ran a test and can confirm that the positioning of our `round` in 

```py
 int(round(width_sum) / count)
```

produces different results to 

```py
 int(float(width_sum) / count)
```

which is why we have to change anything anyways.

**Comment by graphicore** [comment]
>  I think we may have to resort to arbitrarily choosing one. And in that case I'd choose the most commonly seen "in the wild". Which seems to be the fontmake way.

I agree. Though, we can't observe the closed source code, like GlyphsApp, just its behavior.

I think that, without the `division` module, this would be my choice:

```py
 int(round( float(width_sum) / count ))
```

**Comment by davelab6** [comment]
Do you both agree the ot spec is ambiguous on how to implement this aspect
of it?

**Comment by davelab6** [comment]
Do you both agree the ot spec is ambiguous on how to implement this aspect
of it?

On Jul 11, 2017 8:29 PM, "Lasse Fister" <notifications@github.com> wrote:

Thanks Felipe, I also just ran a test and can confirm that the positioning
of our round in

 int(round(width_sum) / count)

produces different results to

 int(float(width_sum) / count)

which is why we have to change anything anyways.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlefonts/fontbakery/issues/1428#issuecomment-314609678>,
or mute the thread

**Comment by felipesanches** [comment]
Yes, I agree that the spec is not fully clear on the correct method for computing it.

**Comment by graphicore** [comment]
Hmm, well it could be more specific on how to produce the int from the division, but I'd expect a floating point divison from the term **arithmetic average**. I'd also expect rounding to get to the integer value, but it could also be the other thing, so yes that's ambiguous and that gist that mentions integer divison doesn't make it better.

**Comment by kenlunde** [comment]
[Apple](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6OS2.html): _average weighted advance width of lower case letters and space_.

Another question that has not yet been asked is about the practical usefulness of this particular value.

**Comment by schriftgestalt** [comment]
Glyphs does not compute the value itself but uses makeOTF this:
```
long width_sum, count;
AvgWidth = (short)(width_sum / count);
```
I extracted the relevant bits, the full code is at `FDK/Tools/Programs/makeotf/makeotf_lib/source/hotconv/hot.c:867`

**Comment by graphicore** [comment]
> Another question that has not yet been asked is about the practical usefulness of this particular value.

Right, though that quote is from [version 2](https://www.microsoft.com/typography/otspec/os2ver2.htm#acw) of OS/2  [version 3](https://www.microsoft.com/typography/otspec/os2ver3.htm#acw) says:

> the arithmetic average of the escapement (width) of all non-zero width glyphs in the font.

Which is *much* more useful :rofl:

**Comment by graphicore** [comment]
Thanks @schriftgestalt!

So makeOTF is in the integer division camp (unless I get this wrong).

A use of this value could be to detect (sometimes) if makeOTF or fontmake was used to compile the font :wink:

**Comment by HinTak** [comment]
How Microsoft calculates it is somewhere in the file `OTFontFileVal/val_OS2.cs` of Font Validator.

Note I am just the messager - I'd prefer not to engage in this discussion.

**Comment by graphicore** [comment]
> How Microsoft calculates it is somewhere in the file OTFontFileVal/val_OS2.cs of Font Validator.

[got it](https://github.com/Microsoft/Font-Validator/blob/cd1ee1a575c256a1b9497e5e84848650c6e4226f/OTFontFileVal/val_OS2.cs#L124)

relevant bits:

```c

int nTotalWidth = 0;
int nTotalGlyphs = 0;

...

short CalcAvgWidth = 0;
if (nTotalGlyphs > 0)
    CalcAvgWidth = (short)(nTotalWidth / nTotalGlyphs);
```
Same as makeOTF.


Maybe, for our purpose, we could create multiple values for the known implementations and just check if we find one of these in the font.
And the day which one is the "correct" way, we warn or info instead of fail for known but deprecated implementations.

**Comment by davelab6** [comment]
Perfect

**Comment by davelab6** [comment]
I think the next action on this is for @felipesanches  to port https://github.com/googlefonts/fontbakery/pull/1429 to the new architecture

**Comment by felipesanches** [comment]
I am going to cut a 0.3.0 release right now. Changing the behaviour of this test right before a release is not wise. I'll do it on 0.3.1 (that means I'll include it in my TO-DO list for tomorrow).
