### ISSUE TITLE
FULL_FONT_NAME false positive when style map style name is "regular"

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#1436]
## Observed behaviour

I got this error, please ignore the space issue between  `Barcode` and `39` this is about the expected **`Regular`** word.

* ERROR: [FULL_FONT_NAME(4):WINDOWS(3)] entry: expected 'Libre Barcode39 Regular' but got 'Libre Barcode 39'

## Expected behaviour

> expected 'Libre Barcode39'  but got 'Libre Barcode 39'

## Resources and exact process needed to replicate

ufo2ft is responsible for this, so I looked into the source code over there and found [the following](https://github.com/googlei18n/ufo2ft/blob/1f2e0c721fd4c33ed61fc650b5ac23121d107891/Lib/ufo2ft/outlineCompiler.py#L306):

> ```py
>        # If name ID 2 is "Regular", it can be omitted from name ID 4
>        fullName = familyName
>        if styleName != "Regular":
>            fullName += " %s" % styleName
> ```

Maybe we should take this into consideration as well.

As always with these issues, it could also be that we don't agree with the `ufo2ft` implementation...

**Comment by davelab6** [comment]
Maybe we should only warn in this case. Marc?

**Comment by felipesanches** [comment]
We did not reach consensus here. So I'll downgrade this to a Warning message and postpone a definitive decision to 0.3.1 or later.
