### ISSUE TITLE
[fontbakery fix-dsig] fake dsig table is broken.

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#1437]
## Observed behaviour

Microsoft FontValidator:

> `<Report ErrorType="E" ErrorCode="E0502" Message="The digital signature of the file did not verify" Details="Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection." TestName="DSIG_VerifySignature" />`

first reported in https://github.com/googlefonts/fontbakery/issues/1430#issuecomment-315734410

With a response of @HinTak:

> Well, that's what it says, I'd say your fake dsig table is broken... there should also be a command-line tool called DSIGInfo, which takes one or more "-v" 's and may give you more info. Anyway, the bulk of the DSIG related code is in https://github.com/HinTak/Font-Validator/blob/master/DSIGInfo/DSIGInfo.cs , and please free to play with it and see which part of your dsig table it does not like :).

## Expected behaviour

A none broken fake DSIG table created by `fontbakery fix-dsig`

**Comment by graphicore** [comment]
https://github.com/googlefonts/fontbakery/issues/1430#issuecomment-315767549:

> The rest of the dsig code is in:
https://github.com/HinTak/Font-Validator/blob/master/OTFontFileVal/val_DSIG.cs
which wraps around the other file. Your file seems to have fallen into the block around line 119 to 123, which is the catch-all "shit happens" clause that your dsig table is doing something entirely unexpected...

**Comment by graphicore** [comment]
Looks like our implementation goes back to this typedrawers post by Ben Kiel http://typedrawers.com/discussion/comment/9651/#Comment_9651

getting this ttx dump:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ttFont ttLibVersion="3.6">

  <DSIG>
    <!-- note that the Digital Signature will be invalid after recompilation! -->
    <tableHeader flag="0x1" numSigs="1" version="1"/>
    <SignatureRecord format="1">
-----BEGIN PKCS7-----
0000000100000000
-----END PKCS7-----
    </SignatureRecord>
  </DSIG>

</ttFont>

```

**Comment by HinTak** [comment]
I think for an dummy dsig table, you want numSigs=0, not 1, at least!

**Comment by HinTak** [comment]
If you want a dummy but valid NumSigs = 0 example, the amiri-*.ttf from http://www.amirifont.org (I am just looking at the Fedora shipped version of those fonts and where they are from according to the rpm database) do it correctly. They are not the only one - I am just looking at all the fonts with a DSIG table on fedora, as I did test the code with all such in fedora 24(?) over a year ago, and remember seeing that. And this one starts with a "a" . This is what it dumps - note NumSigs = 0:

```
  <DSIG>
    <!-- note that the Digital Signature will be invalid after recompilation! -->
    <tableHeader flag="0x0" numSigs="0" version="1"/>
  </DSIG>

```

**Comment by graphicore** [comment]
To create this `DSIG` table the fontTools code looks like this:

```py
          font = ttLib.TTFont(path)
          newDSIG = ttLib.newTable("DSIG")
          newDSIG.ulVersion = 1
          newDSIG.usFlag = 0
          newDSIG.usNumSigs = 0
          newDSIG.signatureRecords = []
          font.tables["DSIG"] = newDSIG
          font.save(path)

```

And I can confirm that it passes `FontValidator.exe`. Though, I don't know about compatibility with i.e. directwrite or what else is looking at `DSIG`. I remember though that @carrois mentioned at TypoLabs 2017 that his DSIGs are just empty. Checking [FiraSans-Regular.ttf](https://github.com/carrois/Fira/blob/master/Fira_Sans_4_2/Fonts/FiraSans_WEB_4203/Normal/Roman/FiraSans-Regular.ttf)

I indeed get:

```xml
  <DSIG>
    <!-- note that the Digital Signature will be invalid after recompilation! -->
    <tableHeader flag="0x0" numSigs="0" version="1"/>
  </DSIG>
```

**Comment by graphicore** [comment]
Has anyone strong feelings about this or can I prepare an updated `fontbakery-fix-dsig.py`? 

CC: @davelab6 @m4rc1e @felipesanches

**Comment by graphicore** [comment]
I was just cleaning up my `git stash` and found this lying around. Before we merge, in the issue @HinTak writes:

> However, you probably want to check that this works for the undocumented use of it in directwrite ...

So, what are these applications that need a (dummy) DSIG to be present and who can test this?
