### ISSUE TITLE
pifont.py: keep it or lose it?

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1440]
I'm converting #1387 so it will be usable on the new architecture but I face a conundrum. 

We have a module called [pifont.py](https://github.com/googlefonts/fontbakery/blob/refactor-architecture/Lib/fontbakery/pifont.py), this seems to be an adapter that will unify all the different font interfaces ttFont, sfd, ufo etc. On paper this sounds like a noble mission. However, in order to make this work across the board, it is a hell of a lot of work! I understand this is probably some legacy code written circa 2016.

Currently, we only have [a few](https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/pifont.py#L48-L81) methods available in pifont. To make this useful, we'll need well over a hundred methods/attribs. It would be an ongoing process and we'd need to add these as we went along.

In the new [specification/googlefonts](https://github.com/googlefonts/fontbakery/blob/refactor-architecture/Lib/fontbakery/specifications/googlefonts.py) module, we're not using any pifont objects. The pifont objects are only used in upstream checks in the old [checks.py](https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/checks.py#L3323-L3388) module.

I faced a similar issue when writing the unit tests for our upstream [Glyphs QA script](https://github.com/googlefonts/gf-glyphs-scripts/blob/master/Google%20Fonts/qa.py). My solution was not to write an adapter to compare a set of downloaded ttfs against a .glyphs file. It was to simply [generate ttfs from the .glyphs file](https://github.com/googlefonts/gf-glyphs-scripts/blob/master/Google%20Fonts/qa.py#L158-L167), then compare the generated ttfs against the ttfs from fonts.google.com.

**Comment by graphicore** [comment]
I'm in favor of losing it, as you say it's a **lot** of work to make this really useful. It's more like a project of it's own, similar to robofab.

**Comment by felipesanches** [comment]
I agree. Ditch it.

I'd prefer to have single-use short routines kept inline in the checks themselves, while using fb.utils for routines shared throughout multiple checks. The rationale here is that making single-use code explicit helps to better convey the semantics of the check to the code-readers.

If it becomes too cumbersome to keep larger single-use routines inline, then move them to fb.utils as well.

**Comment by m4rc1e** [comment]
Awesome, I'll get to it

**Comment by m4rc1e** [comment]
Okay, so the only place where pifont is still used in the refactor branch is for these [two functions](https://github.com/googlefonts/fontbakery/blob/refactor-architecture/Lib/fontbakery/checks.py#L49-L87) in checks.py. I'm also guessing they are going to be ported soon?

```
def check_glyphs_have_same_num_of_contours(fb, folder, directory):
    ...

def check_glyphs_have_same_num_of_points(fb, folder, directory):
    ...
```

I see the checks.py module is getting smaller so I'm guessing it will soon be defunct since the functionality is being ported to specifications/googlefonts.py.


Were these checks were written to confirm if a font is MM friendly?

@felipesanches

**Comment by felipesanches** [comment]
yes, I'll port these very soon (probably today) and checks.py will be gone.

I don't remember exactly when these checks were originally implemented, sorry.

**Comment by m4rc1e** [comment]
@felipesanches thanks! I'll wait for you to get this done before I take the hammer to this.

**Comment by davelab6** [comment]
Nice work

**Comment by felipesanches** [comment]
I ended up keeping PiFont there when I ported the few checks that use it. We may still get rid of it, of course. Or we can simply avoid working on it unnecessarily. I kind of get the usefulness of it as a façade to different font project formats. We could at least rename the class to FontProject or something...

**Comment by felipesanches** [comment]
After our video-call this morning we have decided that these upstream checks are not much useful and that we will deprecate them which, as a result, solves the PiFont conundrum as well.

**Comment by davelab6** [comment]
Good call
