### ISSUE TITLE
Urgent: name and cmap table tools to remove mac platform data

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1443]
- [ ] https://github.com/googlefonts/fontbakery/blob/master/bin/fontbakery-update-nameids.py is cool but we've lost some functionality in the last ~12 months that I now need back again :) 

From time to time, I need to remove from name tables all the nameIDs with "platformID=0 platEncID=3" - which can be removed in certain cases, but I want to have in the general case, because they are needed for some OS X "carbon" apps (eg Mac Word 2011)

@m4rc1e please can you update fontbakery-update-nameids.py to do this, asap. 

- [ ] I also want to be able to remove extra cmap table data that also comes with platformID=0 platEncID=3, which is duplicate when a cmap table has platformID=3 platEncID=1 data too. 

https://github.com/fonttools/fonttools/blob/master/Snippets/cmap-format.py may be helpful for that. 

@m4rc1e please can you create a fontbakery-update-cmap.py to do this, also asap :)

**Comment by m4rc1e** [comment]
I'll get to it, I'll put my other stuff on hold.

**Comment by davelab6** [comment]
@m4rc1e thanks again for this and thanks to @felipesanches for reviewing :)
