### ISSUE TITLE
bin/fontbakery-family-html-snippet.py Improvements

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1447]
bin/fontbakery-family-html-snippet.py can be improved in a few ways. 

Script:

- [ ] Add an arg to post to jsbin using https://jsbin.com/help/api

HTML:

- [ ] Add an input for testing with various subsets; allow free text entry since there are undocumented subsets that shouldn't be exposed in the code but can be entered
- [ ] Add a toggle for staging servers

I took a quick pass at this this morning but gave up as I need to move on to other stuff :( 

https://jsbin.com/fonuwik/edit?html,js,output

**Comment by m4rc1e** [comment]
>  Add an arg to post to jsbin using https://jsbin.com/help/api

This would be great but this only works for paid accounts, "Post data for pro user accounts (to be detailed)" 

I'll have Niall look at the html features you've requested today.

**Comment by felipesanches** [comment]
I saw a tinyurl in the script and I dislike that. Additionally, when I decoded that into the actual google api url (which is what we should have explicitely in the script) I noticed it carries a hardcoded Google API key. This can lead to abuse of your API key.

So I'd like to request 2 changes here:
* replace the tinyurl by the actual plain URL
* get the user Google API key as a command-line attribute (just like **fontbakery-metadata-vs-api.py** does)

**Comment by felipesanches** [comment]
If multiple fontbakery scripts require an API key we might in the future think of ways of helping the user, but hardcoding keys is not an option (in my opinion).

**Comment by felipesanches** [comment]
hey! I'll take care of this tinyurl fix!

**Comment by davelab6** [comment]
All sounds good to me

**Comment by felipesanches** [comment]
yeah! That's one of my very net issues to deal with. I'll try to fix this one still today.

**Comment by davelab6** [comment]
> this only works for paid accounts

That's fine, jsbin is a great paid libre software project, so we can self-host our own in our GCP farm

https://github.com/jsbin/jsbin/blob/master/docs/running-your-own-jsbin.md

**Comment by davelab6** [comment]
...or we can just all use paid accounts; I have one :)

**Comment by felipesanches** [comment]
@m4rc1e Let us know if you:

* will address this this week prior to the upcoming fontbakery v0.3.3 release
* will be interested in addressing this for a future release (such as reallocating it to the 0.3.4 milestone)
* would want me to work on it instead
* or perhaps does not feel like we need to implement this at all.

**Comment by felipesanches** [comment]
migrated to https://github.com/googlefonts/tools/issues/36
