### ISSUE TITLE
UIs for fix/check scripts

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1454]
Thought of this yesterday whilst helping a 3rd party use our tools.

Since we've already started modularising the different scripts, we should have them web based imo. 

Aim should be to drag n drop a collection of fonts, run any sequence of scripts, then download the modified fonts. A log file should be included so the steps are repeatable.

**Comment by graphicore** [comment]
Since it's web based, is this rather a feature request for https://github.com/googlefonts/fontbakery-dashboard?

**Comment by felipesanches** [comment]
I agree with @graphicore that this would be a good fit for the Fontbakery-Dashboard repo.

**Comment by m4rc1e** [comment]
Good points folks, I'll port this issue over
