### ISSUE TITLE
[checkrunner] Add user input value validation to specifications.

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#1457]
I found these TODOs in my Code somewhere. It's not incredible important but it may be nice to have.

The idea is that via the `values` argument of `CheckRunner` the external arguments (like paths to fontfiles) to run the checks are brought into the environment.

Since the spec uses these values and thus *implicitly* knows what they should be, it would be the right place to define validation/sanity checks for these values i.e. the spec describes how it's expecting input to be.
This could provide helpful information for fontbakery users.

Until then, we'll probably see just regular exceptions or `ERROR` states when wrong args are provided, earlier or later in the run. For the developers, a switch to skip validation could be provided as well, may be handy.

* Add a way to check for missing arguments or wrong types in the checkrunner `values` property (via spec).
* Add custom user input validation to the spec, to check values brought in via checkrunners `values`.

**Comment by graphicore** [comment]
This is done now via 194c594 `FontBakeryExpectedValue` which optionally has validate and https://github.com/googlefonts/fontbakery/commit/3097cae5b8b4fa81202296fff69942d2b4e93c9f#diff-ffd6fa65a868981f63dc40761199c639L245 and https://github.com/googlefonts/fontbakery/commit/3097cae5b8b4fa81202296fff69942d2b4e93c9f#diff-ffd6fa65a868981f63dc40761199c639R974 where it is called.

**Comment by davelab6** [comment]
Great!
