### ISSUE TITLE
Full name check is reliable?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1467]
@m4rc1e Given that https://github.com/mozilla/zilla-slab/issues/15 happened I guess that the FB name table 'full name' check may not be reliable... Please investigate :)

**Comment by felipesanches** [comment]
@davelab6 you are probably talking about:

**com.google.fonts/test/068:**
"Does full font name begin with the font family name?"

Which validates the value of NAMEID_FULL_FONT_NAME entries.

**Comment by felipesanches** [comment]
I see that the bad value on zilla-slab was: "Zilla Slab Highlight Bold Bold".

That extra " Bold" in the end of the name would not be caught by the "begins with family name" check, indeed.

**Comment by felipesanches** [comment]
Other FULL_FONT_NAME related tests are:

* **com.google.fonts/test/071:** Among other things, it verifies whether the entry exceeds max length of 64 chars.
* **com.google.fonts/test/094:** METADATA.pb "fullname" value matches internal "fullname" ?
* **com.google.fonts/test/106**, **com.google.fonts/test/107** and **com.google.fonts/test/108**: Among other things, these infer expected METADATA.pb values based on FULL_FONT_NAME value.

None of the above would trigger the issue.

**Comment by felipesanches** [comment]
Finally, there's this rule that enforces the expected format on **com.google.fonts/test/017** - "Assure valid format for the main entries in the name table.":

```python
    [...]
    elif name.nameID == NAMEID_FULL_FONT_NAME:
      expected_value = "{} {}".format(fname_with_spaces,
                                      style_with_spaces)
```

**Comment by felipesanches** [comment]
I'll attempt writing a pytest for this one now to ensure it fails for "Zilla Slab Highlight Bold Bold" :-)

**Comment by felipesanches** [comment]
well... even before writing the test using pytest, I downloaded the Zilla-Slab TTF and I can confirm that the current implementation of test/017 properly emits a FAIL message indicating the bad entry: "Zilla Slab Highlight Bold Bold". So that answers the question: yes, it is reliable!

![screenshot at 2017-07-26 20 53 22](https://user-images.githubusercontent.com/213676/28648522-bd66bc52-7244-11e7-8510-28b72fab8da8.png)

**Comment by m4rc1e** [comment]
@felipesanches thanks for checking this.

**Comment by felipesanches** [comment]
Cool! I'm glad the issue was sorted out :-)
