### ISSUE TITLE
Don't ask me to add things to PATH, tell me how to run subcommands directly

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontbakery#1478]
## Observed behaviour

Instructions to use utilities are overly invasive: Fontbakery installs its own command fontbakery in your $PATH. The fontbakery command makes other subcommands accessible.

## Expected behaviour

I want to directly run a utility, e.g. fontbakery-metadata-vs-api.py

## Resources and exact process needed to replicate

Note that this can be bypassed by running python thefile.py, e.g. `PYTHONPATH=Lib python bin/fontbakery-metadata-vs-api.py <args>`

**Comment by graphicore** [comment]
I suggest to use a python virtual environment and install fontbakery within: https://virtualenv.pypa.io/en/stable/ at least that's what I do.

I don't install things like fonttools or fontmake globally as well (ever). What's your stance on these? Both add things to PATH.

**Comment by felipesanches** [comment]
The updated README provides instructions on how to run the scripts directly. The **fontbakery** script that calls subcommands is handy to have (for the people who like it), so we'll keep it. And there's also the virtualenv solution described by Lasse.

@rsheeter would you be ok with this issue being closed?

**Comment by felipesanches** [comment]
@rsheeter please reopen if needed.
