### ISSUE TITLE
Avoid sys.exit(1); provide a message instead

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontbakery#1479]
## Observed behaviour

When a utility like `fontbakery-metadata-vs-api.py` fails it may do so with no informative message because it terminates with sys.exit(1)

## Expected behaviour

For an error exit print something helpful. E.g. instead of sys.exit(1) sys.exit('my helpful message')

## Resources and exact process needed to replicate

Run `fontbakery-metadata-vs-api.py` with a bad API key. Silent exit. Preferred result would be at the very least to say failed to download json, and preferably include the url atttempted.

**Comment by davelab6** [comment]
@felipesanches would be good to remove all instances of `sys.exit(1)` before closing this; https://github.com/googlefonts/fontbakery/search?utf8=%E2%9C%93&q=sys.exit%281%29&type= currently reports 14 instances

**Comment by felipesanches** [comment]
Dave, those 14 search results are misleading because they include sys.exit(0) which is OK.

There were only 2 instances of sys.exit(non-zero) on failure scenarios. I replaced one of them by sys.exit(error_message_string) in metadava-vs-api. And I'll do the same for the other one now.

**Comment by davelab6** [comment]
Okay cool :) Sounds good!
