### ISSUE TITLE
fontbakery-metadata-vs-api.py fails with ValueError: u'200' is not in list

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontbakery#1480]
## Observed behaviour

fontbakery-metadata-vs-api.py fails to complete

## Expected behaviour

fontbakery-metadata-vs-api.py runs to completion

## Resources and exact process needed to replicate

Run `fontbakery-metadata-vs-api.py`. Prints a bunch of messages then terminates with error:

```
Traceback (most recent call last):
  File "bin/fontbakery-metadata-vs-api.py", line 164, in <module>
    main()
  File "bin/fontbakery-metadata-vs-api.py", line 89, in main
    filenameWeightStyleIndex = [getVariantName(item) for item in metadata.fonts].index(variant)
ValueError: u'200' is not in list
```

**Comment by davelab6** [comment]
I believe @felipesanches wrote this, so assigning to him to fix as P0 :)

**Comment by felipesanches** [comment]
Fixed.

I also took the opportunity to improve the code style of the script as a whole. And I also added script description metadata to the ArgumentParser and to the README.md.
