### ISSUE TITLE
Review usage of INFO and WARN results

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1485]
I was talking to @graphicore about the log levels we have and we agreed on the semantics of INFO and WARN:

* **WARN** is informative stuff that requires user attention
* **INFO** would be harmless to hide if user is not looking for verbose output

Now we need to review the usage of those in the tests so that they follow the above description.

This affects what shows up in the default verbosity-level.

**Comment by davelab6** [comment]
Agreed

**Comment by felipesanches** [comment]
We also decided that:
* the default verbosity level will only display FAIL, WARN and ERROR.
* ERROR always shows up because it means critically bad stuff going on.
* -l flag provides the maximum flexibility allowing the user to choose exactly what verbosity level is desired (-l DEBUG is the only way to see DEBUG messages)
* --verbose is redundant (because it is the same as -l PASS) but we'll have it because it is more intuitive to the users since it is similar to other programs.

**Comment by davelab6** [comment]
I believe this can be closed as @m4rc1e has done a review of the levels in his recent work

**Comment by felipesanches** [comment]
thanks!
