### ISSUE TITLE
Review all settings of the googlefonts org on github.

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1495]
@davelab6 Can you please remove the URL "http://fontbakery.appspot.com" from the project description? I think you are the only one with administrative rights to edit the project description.

If possible, please also considering giving me admin rights to do so.

**Comment by davelab6** [comment]
Removed the URL; I'll leave this open as I need to review all the settings of the org

**Comment by felipesanches** [comment]
Cool, Thanks!
