### ISSUE TITLE
Can we better organize the fixer scripts ?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1496]
Font Bakery 0.3.0 has jsut been released with a modular re-design. The tests all have UUIDs and are neatly organized. And we have a growing set of self-tests as well.

In comparison, the fixer scripts and other auxiliary stand-alone scripts provided by Font Bakery still look pretty much a mess in the project root-dir. Maybe something similar could be acchieved with the helper scripts as well.

This is very very low priority. It is just a thought for the future. Definitely a maybe-someday issue.

**Comment by davelab6** [comment]
Closing to fold into https://github.com/googlefonts/fontbakery/issues/1501
