### ISSUE TITLE
keep a CHANGELOG file or summary of changes in release page?

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/fontbakery#1497]
I noticed that [v0.3.0](https://github.com/googlefonts/fontbakery/releases/tag/v0.3.0) was published and was curious to see what the changes were.
It would be nice if you maintained a `CHANGELOG.md` file, or if you prefer write a brief summary of changes since the previous version in the message body of a release tag.

I don't want to add extra work on you guys, take it as a low-priority would-be-nice-to-have ;)

Also see http://keepachangelog.com

**Comment by felipesanches** [comment]
Thanks, Cosimo. I'll make an effort towards that :-)
