### ISSUE TITLE
Some fix scripts are broken

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1499]
When we moved over to the new architecture, we broke some fix scripts. 

This was because we changed the names of some functions. I'd like @eniallator to track these down, fix them and also write a shell script which can be added to Travis to make sure they never break again.

**Comment by felipesanches** [comment]
Oh! That sounds pretty bad! Sorry about that. I'll add this to the 0.3.1 milestone since we'd want to cut another release once this (and any other issues brought by 0.3.0) are fixed.

**Comment by felipesanches** [comment]
Note: I only assigned this to @m4rc1e because I was unable to assign it to Niall.

**Comment by felipesanches** [comment]
Can you provide further detail on this issue?

I noticed today that the 0.3.0 is borked due to a silly setup.py misconfiguration. I'll very soon have to package a new release. If we could clarify what was the problem here we could add it to this rushed out 0.3.1 version.

**Comment by felipesanches** [comment]
@eniallator could you tell me more about these issues? I'd like to work on fixes for these in today/tomorrow, but I need more detailed info.

**Comment by eniallator** [comment]
I'm also a bit vague on these issues as well but when @m4rc1e  is online tomorrow he could explain what the issues are.

**Comment by felipesanches** [comment]
ok, cool!

**Comment by felipesanches** [comment]
I haven't got any feedback here yet. I'm worried I may have to leave it as is on 0.3.1

@m4rc1e Please clarify this as soon as you have some time to look it up.

**Comment by m4rc1e** [comment]
@eniallator is working on the fix scripts this week, they desperately need a fresh pair of eyes. Yes, leave this issue out for 0.3.1,

**Comment by davelab6** [comment]
@eniallator hows it going?

**Comment by felipesanches** [comment]
I have already addressed these and they are all working and covered by automated tests.
