### ISSUE TITLE
cleanup dependencies and make installation simpler

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1500]
Currently, the installation process is too convoluted and prone to errors.

I can think of a few very problematic places:
- magic
- pyicu
- Headless font forge

I've spent a good two hours trying to deal with getting it to run on two users machines. I got mine to work by solving dependency errors as I went through them step by step. This isn't acceptable imo.

Installation should be create as simple as 

```
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
pip install -e . (for dev mode)
```

**Comment by m4rc1e** [comment]
Closing this. I already mentioned this in #1367

**Comment by davelab6** [comment]
The way that I solved this is to not have the deps as hard requirements but to FAIL tests that depend on those upstream packages being available with instructions about how to install them.

**Comment by felipesanches** [comment]
We're still very much following those principles. If we find places where things are imported globally I think we should have an explicit rule to embed the import statements into the individual tests to make sure we achieve that same end-result as what @davelab6 mentioned above.
