### ISSUE TITLE
Subcommands?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1501]
Felipe wrote:

> Font Bakery 0.3.0 has jsut been released with a modular re-design. The tests all have UUIDs and are neatly organized. And we have a growing set of self-tests as well.
>
> In comparison, the fixer scripts and other auxiliary stand-alone scripts provided by Font Bakery still look pretty much a mess in the project root-dir. Maybe something similar could be achieved with the helper scripts as well.

I wrote: 

## Observed behavior

I see

```
$ fontbakery -h
...
Run fontbakery subcomands:
    build-font2ttf
    build-fontmetadata
    check-description
    check-ttf
    check-upstream
    fix-ascii-fontmetadata
    fix-familymetadata
    fix-gasp
    fix-glyph-private-encoding
    fix-nameids
    fix-nonhinting
    fix-ttfautohint
    list-panose
    list-weightclass
    list-widthclass
    metadata-vs-api
    update-families
...
```

## Expected behaviour

What I expect is that the commands' shared stems are actually subcommands... like this

```
$ fontbakery -h
...
Run fontbakery subcomands:
    build font2ttf
    build fontmetadata
    check description
    check ttf
    check upstream
    fix ascii-fontmetadata
    fix familymetadata
    fix gasp
    fix glyph-private-encoding
    fix nameids
    fix nonhinting
    fix ttfautohint
    list panose
    list weightclass
    list widthclass
    metadata-vs-api
    update families
...
```

**Comment by felipesanches** [comment]
That looks like just a bit of syntactic sugar. Would make a lot of sense, though, if we gathered the scripts by categories. Does these categories make sense or should we regroup them?

* fix
* list
* update
* check
* build

see #1496

**Comment by felipesanches** [comment]
migrated to https://github.com/googlefonts/tools/issues/15
