### ISSUE TITLE
setup.py paths made for unix but gives an error for windows

### ISSUE THREAD

**Issue by eniallator** [googlefonts/fontbakery#1505]
[setup.py](https://github.com/googlefonts/fontbakery/blob/master/setup.py#L69-L86) has paths joined with `/` . This doesn't work on windows since windows uses `\`.

I can try fixing this today since it's just a matter of using `os.path`.

**Comment by felipesanches** [comment]
Great! Thanks; Since this is a packaging issue, I'd like to include a fix for it on the Emergency 0.3.1 release this week.

**Comment by felipesanches** [comment]
Thanks, @eniallator
