### ISSUE TITLE
bin/fontbakery-update-families.py refactor

### ISSUE THREAD

**Issue by eniallator** [googlefonts/fontbakery#1514]
I want to change [fontbakery-update-families](https://github.com/googlefonts/fontbakery/blob/master/bin/fontbakery-update-families.py) so we can remove lib magic and also making the interface nicer. What I'm thinking of doing is using a before and after list of file names and comparing instead of assuming there's another file within the directory named the same but with "-old" at the end. Also just checking if me changing the interface will impact any scripts setup or not @felipesanches

**Comment by felipesanches** [comment]
I think that's a perfect plan, @eniallator !
I noticed that the "-old" file is one of the reasons for the Travil build-failure on #1513 Pull Request.

Also, removing the libmagic dependency will be great.

**Comment by davelab6** [comment]
When you do, please file an issue with the removed code so that I can propose a new way to achieve the same ends

**Comment by felipesanches** [comment]
migrating to https://github.com/googlefonts/tools/issues/13
