### ISSUE TITLE
Review DESIGN_CONSIDERATIONS.md

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1522]
@felipesanches last year you wrote https://github.com/googlefonts/fontbakery/blob/00d4eb625db99941ec7c5d84a5efc30f2d1169da/DESIGN_CONSIDERATIONS.md and I guess this now needs major revision after 0.3.1

**Comment by felipesanches** [comment]
That's an approach that is now completely obsolete.

**Comment by davelab6** [comment]
The document probably needs to be completely rewritten, but the idea that people would run Font Bakery on travis for the individual projects is still totally valid :)

**Comment by simoncozens** [comment]
I think this is closable, given that people are getting a CI run of fontbakery by default in the GF font repo template.
