### ISSUE TITLE
Update bin/fontbakery-list-variable-source.py

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1529]
This script was used to quickly determine which .glyphs files on my local machine could be turned into variable fonts.

We can either remove this script or make it more general purpose. Ideally, it should look at [upstream repositories document](https://docs.google.com/spreadsheets/d/1ampzD9veEdrwUMkOAJkMNkftqtv1jEygiPR0wZ6eNl8/edit?usp=sharing) instead

**Comment by felipesanches** [comment]
migrating to https://github.com/googlefonts/tools/issues/9
