### ISSUE TITLE
Whitelist barcode fonts

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1534]
Per https://github.com/graphicore/librebarcode/issues/3

**Comment by felipesanches** [comment]
I'm starting to wonder whether we should maintain hardcoded whitelists within Fontbakery itself. It is starting to feel like a big hack. Perhaps the good way would be having whitelists on some sort of user config.

Then we can, off course maintain sample configs with the our own whitelists.

**Comment by felipesanches** [comment]
There's a bit of risk of over-engineering here, though. But I think it can get messy (and gradually messier) to keep adding hardcoded exceptions.

**Comment by davelab6** [comment]
We need the barcode exceptions fixed immediately. 

We can clean it up later.

**Comment by felipesanches** [comment]
I can also quickly resolve this by fulfilling this Barcode whitelist request now and leaving this issue open for thinking of cleaner solutions later, off course :-)

**Comment by davelab6** [comment]
I filed a separate issue :)

**Comment by felipesanches** [comment]
thanks

**Comment by graphicore** [comment]
@felipesanches not sure if my CCing you in that comment was sent to you, because it was made in an update to that post: https://github.com/googlefonts/fontbakery/issues/1540#issuecomment-324060835
