### ISSUE TITLE
Only run pyfontaine codepage check if the font has glyphs in the unicode range

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1538]
In the current implementation, every pyfontaine check will be run, regardless of whether the font contains a single glyph in the codepage's unicode range.

https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/specifications/googlefonts.py#L4099-L4267

This is causing a lot of bloat and is related to #1537

**Comment by davelab6** [comment]
Per https://github.com/googlefonts/fontbakery/issues/1537#issuecomment-324040991 we should not run pyfontaine, so I'm closing this
