### ISSUE TITLE
com.google.fonts/test/109: Check if fontname is not camel cased. What is the point of this test?

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1539]
I don't know why this test exists.

```
>> com.google.fonts/test/109 with ((u'font[2]', '/Users/marc/Documents/googlefonts/fonts/ofl/someonesans/SomeOneSans-Regular.ttf'),)
   Check if fontname is not camel cased.
 * FAIL: METADATA.pb: 'SomeOne Sans' is a CamelCased name. To solve this, simply use spaces instead in the font name.
```

I don't really care if a family name is CamelCased. Many technologies, companies and some of our existing families use this pattern.

I understand that several of our tools will derive the font name from a filename by using a camelCase splitting function, but I still feel this should not be an error.

Am I missing something here?

**Comment by davelab6** [comment]
I want to avoid this in the future.

**Comment by felipesanches** [comment]
@davelab6 "I want to avoid this in the future" means that you want to avoid camel cased names and that's the point of this test, right? If so, then there's nothing to do here.

Or would you prefer to make this FAIL a WARN ?

**Comment by davelab6** [comment]
Fail with whitelist :)

**Comment by felipesanches** [comment]
@m4rc1e (or @davelab6) are there specific Families that you'd like to add in a whitelist for this test ?

What's the actionable task right now on this issue?

**Comment by davelab6** [comment]
The specific families that fail the test today should be whitelisted.

**Comment by felipesanches** [comment]
Perfect!

**Comment by felipesanches** [comment]
So, new camel-cased families will FAIL. Old ones will be accepted as legacy (via a whitelist). I'll build that list now.

**Comment by felipesanches** [comment]
This is our short (but complete) list of legacy CamelCased family names:
* BenchNine
* FakeFont
* McLaren
* MedievalSharp
* UnifrakturCook
* UnifrakturMaguntia
