### ISSUE TITLE
Design special case handling (allowlists/blocklists)

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1540]
Per https://github.com/googlefonts/fontbakery/issues/1534#issuecomment-324054699 we should not maintain hardcoded allowlists/blocklists within Fontbakery itself. 

Special casing should be done with some sort of user configuration file.

**Comment by graphicore** [comment]
There's a good start for it already, we can inject the whitelist into the `TestRunner` via the `values` dictionary.

in https://github.com/googlefonts/fontbakery/blob/master/bin/fontbakery-check-googlefonts.py#L131

```py
  values = dict(
    fonts=get_fonts(args.arg_filepaths)
  , FAMILYNAMES_WITH_SPACES_EXCEPTIONS={
         'VT323': 'VT323',
         'PressStart2P': 'Press Start 2P',
         'ABeeZee': 'ABeeZee'
    }
  )
 runner = TestRunner(specification, values
```

Then a test can just have that new value as a dependency:

```py
@register_test
@test(
    id='com.google.fonts/test/017'
)
def check_main_entries_in_the_name_table(ttFont, style, FAMILYNAMES_WITH_SPACES_EXCEPTIONS):
  # use FAMILYNAMES_WITH_SPACES_EXCEPTIONS here
  ...

cc @felipesanches
```

**Comment by davelab6** [comment]
@graphicore I'm curious what the status of this is; any action since Aug 22? No worries if not

**Comment by graphicore** [comment]
I just got reminded: in https://github.com/googlefonts/fontbakery/blame/master/Lib/fontbakery/commands/check_googlefonts.py#L16 we have now:

```py
# in comands/check_googlefonts.py
GOOGLEFONTS_SPECIFICS = {}
```

Which is intended to define values in the runner namespace, i.e. accessible via dependency injection in the check and condition functions. Thus, my previous example looks like this:

```py
# in comands/check_googlefonts.py

GOOGLEFONTS_SPECIFICS = {
# we could load this via some sort of configuration as well, but I think this
# should be the central place for custom google fonts config.
# the dashboard also uses this config
  'FAMILYNAMES_WITH_SPACES_EXCEPTIONS': {
         'VT323': 'VT323',
         'PressStart2P': 'Press Start 2P',
         'ABeeZee': 'ABeeZee'
  }
}
```

> any action since Aug 22? No worries if not

This was done in a commit from Aug 25 a6ce1ea3c9 :confused:, guess I just forgot to mention.

**Comment by simoncozens** [comment]
Users can now add a configuration file which allows or skips certain checks. We also have the ability to send values from the configuration file into the checks, where necessary.
