### ISSUE TITLE
Undefined names

### ISSUE THREAD

**Issue by cclauss** [googlefonts/fontbakery#1547]
flake8 testing of https://github.com/googlefonts/fontbakery on Python 2.7.13

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./Lib/fontbakery/callable.py:60:31: F821 undefined name 'defaults'
    args = argspec.args[:-len(defaults)] \
                              ^

./Lib/fontbakery/callable.py:71:36: F821 undefined name 'defaults'
    return tuple(argspec.args[-len(defaults):] \
                                   ^

./Lib/fontbakery/testrunner.py:235:50: F821 undefined name 'k'
                      'namespace as a {}'.format(k, spec.get_type(name)))
                                                 ^

./Lib/fontbakery/testrunner.py:343:13: F821 undefined name 'CircularDependencyError'
      raise CircularDependencyError('Condition "{0}" is a circular dependency in {1}'\
            ^

./Lib/fontbakery/testrunner.py:344:43: F821 undefined name 'condition'
                                  .format(condition, ' -> '.join(path)))
                                          ^

./Lib/fontbakery/testrunner.py:1038:14: F821 undefined name 'partial'
      return partial(self._add_test, section)
             ^

./Lib/fontbakery/testrunner.py:1063:14: F821 undefined name 'partial'
      return partial(self._add_condition, *args, **kwds)
             ^

./bin/fontbakery-build-fontmetadata.py:496:19: F821 undefined name 'errno'
    raise OSError(errno.ENOTDIR, 'No such directory', fontdir)
                  ^

./bin/fontbakery-build-fontmetadata.py:500:19: F821 undefined name 'errno'
    raise OSError(errno.ENOENT, 'no font files found')
                  ^

./bin/fontbakery-fix-gasp.py:56:51: F821 undefined name 'path'
            print('ER: {}: no index 65535'.format(path))
                                                  ^

./bin/fontbakery-update-families.py:65:102: F821 undefined name 'filename'
        logging.warning("Skipping '{}' as mime was '{}', should be 'application/x-font-ttf')".format(filename, mimetype))
                                                                                                     ^
```

**Comment by graphicore** [comment]
Ok, thanks! I can take care of the issues in testrunner.py later today. It's a good reason to review these rarely executed parts.

**Comment by felipesanches** [comment]
we didn't catch these before for 2 reasons:

* we don't use flake8 anymore. Nowadays we run pylint on every Travis build.
* we only test **Lib/fontbakery/specifications/*.py**

**Comment by felipesanches** [comment]
We also have a long list of ignored checks which anyone can disable one-by-one and cleaning up, off course. Not a huge, priority, but a good task for random external contributors to pick up, clean and contribute.

Checks that don't make much sense (or that we consider irrelevant) are gradually listed on .travis.yml's WONT_FIX env-var.

**Comment by cclauss** [comment]
Thanks for the explanations.  It is a cool project!

I have found pylint to be good for finding the style stuff but overlooks some key errors.  Here I am using flake8 in a focused way that ignores _all_ of the "style violations" and only concentrates on five issues (--select=E901,E999,F821,F822,F823) that can halt your program in front of your user.  

In the first example above, if `defaults` is not defined then an exception is thrown which if not caught and properly dealt with, stops all execution.  Fixing one of those issues has more value than fixing dozens of style violations.  I hope that helps.  Please keep up the great work.

**Comment by felipesanches** [comment]
@graphicore we merged that PR, but I had the impression that you'll still make another PR for this issue, right? Feel free to close this issue once you addressed all points brought up by @cclauss (thanks!)
