### ISSUE TITLE
mem alloc error on progressbar code

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1550]
When tyring to get a list of all font files that FAIL test 049 (space glyph has ink) (see issue #1549), by running this command:

```
fontbakery check-googlefonts -c com.google.fonts/test/049 ~/gfonts/*/*/*.ttf
```

I got a memory allocation problem with the progress bar code:

![screenshot at 2017-08-25 10 30 32](https://user-images.githubusercontent.com/213676/29716158-a90d9872-8980-11e7-963b-8997abfe9e89.png)

I was able to re-run the command flawlessly by disabling the progressbar:

```
fontbakery check-googlefonts -c com.google.fonts/test/049 ~/gfonts/*/*/*.ttf --no-progress
```

![screenshot at 2017-08-25 10 38 01](https://user-images.githubusercontent.com/213676/29716369-8372d7d4-8981-11e7-9c51-b2161e902914.png)

**Comment by graphicore** [comment]
> I got a memory allocation problem with the progress bar code:

Crazy! Is it always at the same position in the code and test progress? Maybe we need a smaller, kind of summarizing, progressbar. Though, at the moment I like that the progress bar items relate directly to checks. In a summarizing progress bar, one item would stand for multiple tests, and probably always display the worst status. We'd save a lot of screen space.

I wonder if that would help anything or if that call to calculate the tty size is generally a problem.

I guess this will be hard to reproduce for me :-/

> I was able to re-run the command flawlessly by disabling the progressbar:

That's what I would suggest for the test scenario anyways.

**Comment by felipesanches** [comment]
I like the way it currently works. I think we should aim at preserving its current behaviour while tackling the heavy memory allocation that seems to be happening I don't get yet exactly why.

**Comment by felipesanches** [comment]
This is a duplicate of issue #1610
