### ISSUE TITLE
com.google.fonts/test/065: Is there kerning info for non-ligated sequences, drop test

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1555]
Imo, there shouldn't be any kerning for ligated sequences.

Ligated sequences should use kern classes instead e.g:

f_i: 
left_class=f
right_class=i:

![screen shot 2017-08-30 at 11 15 19](https://user-images.githubusercontent.com/7525512/29867808-a737abf8-8d74-11e7-9adb-a384e7d099ed.png)

This test fails on many of the Raisins. Screenshot and sample from [Alice](https://github.com/cyrealtype/Alice)

I wouldn't mind this test to be refactored to check if the ligatures are using kern classes instead.

**Comment by m4rc1e** [comment]
Some fail messages for this test are pretty lengthy. Here's one for just one weight of [Alegreya](https://github.com/huertatipografica/Alegreya)

```
 FAIL: GPOS table lacks kerning info for the following non-ligated sequences: [u'less_asciicircum', u'less_hyphen', u'less_equal', u'hyphen_asciicircum', u'hyphen_greater', u'l_periodcentered', u'asciitilde_E', u'asciitilde_G', u'asciitilde_I', u'asciitilde_U', u'asciitilde_Y', u'asciitilde_e', u'asciitilde_g', u'asciitilde_i', u'asciitilde_u', u'asciitilde_y', u'asciitilde_e.sc', u'asciitilde_g.sc', u'asciitilde_i.sc', u'asciitilde_u.sc', u'asciitilde_y.sc', u'tilde_E', u'tilde_G', u'tilde_I', u'tilde_U', u'tilde_Y', u'tilde_e', u'tilde_g', u'tilde_i', u'tilde_u', u'tilde_y', u'tilde_e.sc', u'tilde_g.sc', u'tilde_i.sc', u'tilde_u.sc', u'tilde_y.sc', u'uni0308.case_acutecomb.case', u'uni0308.case_uni0304.case', u'greater_asciicircum', u'Iacute_J', u'uni0304.case_gravecomb.case', u'uni0304.case_acutecomb.case', u'uni0307.case_uni0304.case', u'iacute_j', u'tildecomb.case_uni0308.case', u'tildecomb.case_acutecomb.case', u'tildecomb.case_uni0304.case', u'L_periodcentered', u'N_o', u'dieresis_I', u'dieresis_O', u'dieresis_i', u'dieresis_o', u'dieresis_i.sc', u'dieresis_o.sc', u'uni0307_uni0304', u'uni0304_gravecomb', u'uni0304_acutecomb', u'uni0302_gravecomb', u'uni0302_acutecomb', u'uni0302_tildecomb', u'uni0302_hookabovecomb', u'T_h', u'asciicircum_hyphen', u'asciicircum_equal', u'uni0308_gravecomb', u'uni0308_acutecomb', u'uni0308_uni030C', u'uni0308_uni0304', u'acute_Y', u'acute_y', u'acute_y.sc', u'c_h', u'c_t', u'f_i', u'f_j', u'f_l', u'h_t', u'equal_greater', u'equal_asciicircum', u's_t', u'uni0306_gravecomb', u'uni0306_acutecomb', u'uni0306_tildecomb', u'uni0306_hookabovecomb', u'tildecomb_E', u'tildecomb_G', u'tildecomb_I', u'tildecomb_U', u'tildecomb_Y', u'tildecomb_e', u'tildecomb_g', u'tildecomb_i', u'tildecomb_u', u'tildecomb_y', u'tildecomb_e.sc', u'tildecomb_g.sc', u'tildecomb_i.sc', u'tildecomb_u.sc', u'tildecomb_y.sc', u'gamma_gamma', u'lambda_lambda']

```

**Comment by felipesanches** [comment]
Lengthy but precise :-)

**Comment by felipesanches** [comment]
Would it make sense to change that to a less verbose message such as:

```
FAIL: GPOS table lacks kerning info for non-ligated sequences such as 'less_asciicircum', 'less_hyphen', 'less_equal', and 97 other ones.
```

?

**Comment by m4rc1e** [comment]
I'm more keen for us to drop it.

In 99% of cases, you should not be kerning ligatures since a ligature's shape is usually derived from the base glyphs it represents. Ligatures should be added to classes instead. e.g

for ligature ffi: left class = f, right class = i

**Comment by felipesanches** [comment]
OK. This is yet another case of a test for which we lack a proper history of when/why it was initially created. I'm sure there was a reason and a demand for it at some point. Maybe @davelab6 remembers the rationale behind it?

**Comment by felipesanches** [comment]
I did some digging, git grepping, git blaming, and finaly found the reference to the actual original request from @davelab6 

This is it:
https://github.com/googlefonts/fontbakery/issues/1145

**Comment by felipesanches** [comment]
I'm glad I always keep references to github issues on my git log messages :-D

**Comment by m4rc1e** [comment]
Ahhh God, I finally see the purpose of this test.

Keep this open for the time being. I will reword this issue.

**Comment by felipesanches** [comment]
@m4rc1e please reword the issue or close it.

**Comment by felipesanches** [comment]
thanks :-)
