### ISSUE TITLE
Update top level readme on Font Validator

### ISSUE THREAD

**Issue by HinTak** [googlefonts/fontbakery#1564]
I think we can agree that nothing is happening upstream. As of 2.1.1, you don't need mono on your system either, with mac os x and linux.

**Comment by felipesanches** [comment]
thanks. I'll review that.

**Comment by felipesanches** [comment]
done.

**Comment by HinTak** [comment]
Vanilla freetype is not sufficient for the rest. It depends. See the "ComputeMetrics patch" reference which was integrated into FreeType 2.6.1.

**Comment by felipesanches** [comment]
It is good enough for our purposes right now. Feel free to open a new issue pinpointing a specific test that the current approaches does not support and which are the benefits of it. Based on that we can decide on how to prioritize work on this.
