### ISSUE TITLE
New check: Does METADATA category match what is in production?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1582]
To close out https://github.com/google/fonts/issues/720 I need a script/check that tells me, for each family that exists in both github and production, if the categories don't match.

**Comment by davelab6** [comment]
Reassigning this to @felipesanches - its simply grabbing the developer api json -
 https://developers.google.com/fonts/docs/developer_api - and then, if the family exists in that json, take it's category key's value, normalizing it against the possible values of METADATA.pb category keys, and then do a simple comparision :)

**Comment by felipesanches** [comment]
This could be a check, but it needs a api key. We could conceivably add an api key to the testrunner command line and make it a condition for the checks that need it.

Also, implementing this as a test in the googlefonts testsuite would not be much useful while the proper handling of families described in #1609 is sorted out.

So, this issue will be focused on implementing a standalone script.

**Comment by felipesanches** [comment]
This should be enough for that kind of task:

```
fontbakery metadata-vs-api YOUR_API_KEY_HERE ~/gfonts/ofl/ 2>&1|grep category
```

One problem though is that doing it involves downloading TTF remote files which slows down the task and you don't really need that in this case.

So, I forked that metadata-vs-api and deleted all code that's not related to the category metadata. With this I got a single bad font reported:

![screenshot at 2017-10-17 20 18 56](https://user-images.githubusercontent.com/213676/31692486-b4d33852-b378-11e7-94dc-aae79cc41f99.png)

I'll review my code to make sure this is indeed correct before committing this new script.

**Comment by felipesanches** [comment]
Maybe both tasks could be accomodated in a single metadata-vs-api script. But then the code would need to be refactored because the current implementation is a bit too much complicated / hard to read right now. I think it definitely deserves a better/cleaner approach.

**Comment by felipesanches** [comment]
@davelab6  Please test using the script and reopen the issue if improvements are needed.
