### ISSUE TITLE
Add a --list-tests command line argument to describe the tests of a given specification

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1586]
For instance, if one wants to know which are the titles, descriptions and IDs of all tests available in the Google Fonts specification, then it would possible to list that info with the following command:

```
fontbakery check-googlefonts --list-tests
```

**Comment by felipesanches** [comment]
Without this, one has to look at the FontBakery source code in order to figure out which are the available test IDs (or, alternatively, the IDs can be seen in the terminal output after running the full spec once).

Providing a --list-tests sounds reasonable. We may even think of a --list-specs as well in the future.

**Comment by davelab6** [comment]
Did someone request this? If so I suggest a sooner milestone

**Comment by felipesanches** [comment]
Me and Lasse came up with this as an insight while talking to Marek at ATypI last week.
