### ISSUE TITLE
API vs Repo for Early Access

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1592]
- [ ] The github.com/google/fonts repo doesn't include all the fonts available in fonts.google.com/earlyaccess but it should. Please provide a script which provides details about which versions are available in each place. 

- [ ] Additionally, for Noto fonts, check the upstream version too, to accelerate our ability to keep them up to date.

**Comment by felipesanches** [comment]
Migrating to https://github.com/googlefonts/tools/issues/8
