### ISSUE TITLE
Package fonts for distros

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1598]
It would be nice to support the distro packaging formats.

* Debian
* Fedora
* Arch
* CTAN

- [ ] check a repo has a metadata XML file as specified in http://blog.tenstral.net/2017/09/adding-fonts-to-software-centers.html
- [ ] generate those files

This is related to our own METADATA.pb stuff...

**Comment by sladen** [comment]
What's the plan here;  actively provide a minimum `.deb`/`.rpm` as a download format?

Note to self... versioning.

**Comment by felipesanches** [comment]
migrating to https://github.com/googlefonts/tools/issues/12
