### ISSUE TITLE
ERROR on com.google.fonts/test/153 with DroidSansJapanese.ttf

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1599]
![screenshot at 2017-10-03 16 34 29](https://user-images.githubusercontent.com/213676/31145144-4ba8f08a-a859-11e7-8c9a-cc5e999e88b0.png)

**Comment by davelab6** [comment]
That font is deprecated so blacklist it

**Comment by davelab6** [comment]
Actually, I think something bad is happening here; while I don't care too much about that font, it does have a cmap, so something is broken. 

```
$ ttx -t cmap fonts/apache/droidsansjapanese/DroidSansJapanese.ttf 
$ head fonts/apache/droidsansjapanese/DroidSansJapanese.ttx
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="3.13">

  <cmap>
    <tableVersion version="0"/>
    <cmap_format_12 platformID="3" platEncID="10" format="12" reserved="0" length="48496" language="0" nGroups="4040">
      <map code="0x203e" name="uni203E"/><!-- OVERLINE -->
      <map code="0x3000" name="uni3000"/><!-- IDEOGRAPHIC SPACE -->
      <map code="0x3001" name="uni3001"/><!-- IDEOGRAPHIC COMMA -->
      <map code="0x3002" name="uni3002"/><!-- IDEOGRAPHIC FULL STOP -->

...

```

**Comment by felipesanches** [comment]
yeah. I was investigating that one right now and I'm still a bit puzzled. I'll continue looking at it and see what I can find.

**Comment by felipesanches** [comment]
the issue here is that the code is looking for plat=3, enc=1, while this one has plat=3 enc=10

**Comment by felipesanches** [comment]
PLATFORM_ID__WINDOWS = 3

PLAT_ENC_ID__UCS2 = 1
PLAT_ENC_ID__UCS4 = 10

**Comment by HinTak** [comment]
My impression is that it is actually quite common for CJK fonts to have both (3,1) and (3,10) cmaps, and I think I have seen cases where **only** a (3,10) cmap is present - and it makes sense for fonts with glyphs outside the basic multi-lingual planes, which are not representable in (3,1) cmap.

We are not talking about **only** CJK fonts. Emojis are outside the BMP too.

**Comment by davelab6** [comment]
The code is should prefer a plat=3 enc=1 cmap, but if not found, it should use the next one available.

**Comment by HinTak** [comment]
Actually, a pure Emoji font has no glyphs inside the BMP. So a (3,1) cmap would be empty, and therefore not useful and perhaps should not be present at all.
