### ISSUE TITLE
Map all FontBakery dependencies and try to minimize the dependency tree

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1602]
FontBakery depends on a whole bunch of third-party python modules and other external programs.

The goal here is to map them all listing which tests or fixer scripts rely on each.

**Comment by felipesanches** [comment]
I'll keep updating this comment with the full list.

## External programs
* ttfautohint: **com.google.fonts/test/054**, **com.google.fonts/test/056**
* ots-sanitize: **com.google.fonts/test/036**
* Microsoft Font Validator: **com.google.fonts/test/037**
* python-fontforge: **com.google.fonts/test/038**, **com.google.fonts/test/039**
* ftxvalidator: **com.google.fonts/test/035**

## python modules
* TODO: list modules here

**Comment by graphicore** [comment]
Awesome, this will also be helpful to remove dependencies that we don't use anymore. AFAIK requirements.txt/setup.py has such.

**Comment by davelab6** [comment]
https://github.com/googlefonts/fontbakery/issues/1523 seems related

**Comment by felipesanches** [comment]
This is done! The dependencies were systematically mapped above and with that we removed any left-over dependencies (that were used in the past, but removed later but mistakenly remained in setup.py or requirements.txt).
