### ISSUE TITLE
Report an error if copyright (name id 0) exceeds 500 characters

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontbakery#1603]
If a font has a 'name' with copyright whose length exceeds 500 characters report an error.

'name' ID 0, see https://www.microsoft.com/typography/otspec/name.htm#nameIDs.

**Comment by felipesanches** [comment]
What's the rationale for this specific length limit of 500 chars ? Is it arbitrary or are there known user agents that fail to deal with specifically 501 chars or more ?

**Comment by davelab6** [comment]
Its arbitrary, we just don't want very long ones. I made a script to show us the notices and lengths, 

Eg

    bin/fontbakery-check-copyright-notices.py ~/fonts/ufl/*/*ttf;

Outputs

|                             |                                                                           |   filename | copyright notice                                                          |   char length |
|:----------------------------|:--------------------------------------------------------------------------|-----------:|:--------------------------------------------------------------------------|--------------:|
| Ubuntu-Bold.ttf             | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |         73 | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |            73 |
| Ubuntu-BoldItalic.ttf       | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |         73 | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |            73 |
| Ubuntu-Italic.ttf           | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |         73 | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |            73 |
| Ubuntu-Light.ttf            | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |         73 | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |            73 |
| Ubuntu-LightItalic.ttf      | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |         73 | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |            73 |
| Ubuntu-Medium.ttf           | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |         73 | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |            73 |
| Ubuntu-MediumItalic.ttf     | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |         73 | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |            73 |
| Ubuntu-Regular.ttf          | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |         73 | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |            73 |
| UbuntuCondensed-Regular.ttf | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |         73 | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |            73 |
| UbuntuMono-Bold.ttf         | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |         73 | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |            73 |
| UbuntuMono-BoldItalic.ttf   | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |         73 | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |            73 |
| UbuntuMono-Italic.ttf       | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |         73 | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |            73 |
| UbuntuMono-Regular.ttf      | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |         73 | Copyright 2011 Canonical Ltd.  Licensed under the Ubuntu Font Licence 1.0 |            73 |

**Comment by davelab6** [comment]
Here's the top 5 lenghts across the collection

| copyright notice char length | count |
|----------------------------:|:-------:|
| 394 | 2 |
| 299 | 1 |
| 276 | 1 |
| 275 | 1 |
| 270 | 3 |

**Comment by felipesanches** [comment]
I've just implemented the new test and running it on the full collection of 2400 font files I noticed that absolutely all fonts pass the test!

**Comment by felipesanches** [comment]
Are these top 5 lengths reasonable? Or would you like to flag them as too long? If so, would you like to have a smaller max-length criteria then? Maybe max-length = 100, or 200 perhaps...?

**Comment by felipesanches** [comment]
Well... the new check (and a code test for it) have been merged. Reopen the issue if you'd like to use smaller max-length criteria.

**Comment by davelab6** [comment]
This is just a safety check :)
