### ISSUE TITLE
ERROR at google test/020 KeyError: u'Heavy'

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1607]
![screenshot at 2017-10-10 00 09 47](https://user-images.githubusercontent.com/213676/31367701-74c1be16-ad4f-11e7-904e-263fd39e1e26.png)

**Comment by m4rc1e** [comment]
GF api only allows Thin-Black. You could do something like this so it just fails.

```
if key not in GF_API_WEIGHTS:
    FAIL (...)
```

**Comment by felipesanches** [comment]
yeah that's right

**Comment by davelab6** [comment]
It should have failed much earlier; the 'one file' checker that Felipe and
I first worked on had an if statement like that.

In general the code structure should have some 'prechecks' that check its
assumptions and allow it to bail out as early as possible.

**Comment by felipesanches** [comment]
The current code structure decoupled the tests. They all run independent of each other unless we explicitely declare a precondition. We can add styles as a condition here and it will skip running this test for any font that does not have a good stylename.

**Comment by felipesanches** [comment]
Hmmm... actually we already had "style" as a condition here. But the condition itself was accepting non-canonical style names as valid. I changed it now so that the style precondition only returns valid/canonical style names or None otherwise.

**Comment by felipesanches** [comment]
Before:

![screenshot at 2017-10-10 16 16 18](https://user-images.githubusercontent.com/213676/31406908-6bcd7c84-add9-11e7-9a15-fa29ea02fa32.png)

After:

![screenshot at 2017-10-10 16 25 10](https://user-images.githubusercontent.com/213676/31406917-7746ca7a-add9-11e7-8040-4d8245c16807.png)

**Comment by davelab6** [comment]
Reopening as your before/after troubles me :) 

> The current code structure decoupled the tests. They all run independent of each other unless we explicitely declare a precondition. 

Okay, that sounds good - so what i called 'pre-checks' can be what you call 'pre-conditions'?

> We can add styles as a condition here and it will skip running this test for any font that does not have a good stylename.

Right - but there should be a pre-check that all of the styles are good / none of the styles are bad. 

> Hmmm... actually we already had "style" as a condition here. But the condition itself was accepting non-canonical style names as valid. I changed it now so that the style precondition only returns valid/canonical style names or None otherwise.

So, in your 'before' screenshot there are 45 errored checks, which I guess are 45 checks that failed due to the style name 'Heavy' being bad

And, in your 'after' screenshot, there are now no errors - which is good - but there are an additional 45 skipped checks, and no additional fails. 

There should be 1 additional fail.

**Comment by felipesanches** [comment]
I disagree, Dave.

Your expectation for FAILs indicating non-canonical names is fulfilled by the dedicated **com.google.fonts/test/001: "Checking file is named canonically"**.

The purpose of **test/020** is not validating canonical names, but instead **"Checking OS/2 usWeightClass"**. Having a canonical name is only a condition that needs to be fulfilled in order to run **test/020**, but not the kind of problem that it is concerned with reporting, as this is the job of **test/001**.

**Comment by felipesanches** [comment]
In other words: you'll get the 45 FAILs due to non-canonical names (not only "Heavy", but anything that's non-canonical) on **test/001**.

**Comment by davelab6** [comment]
Do you mean FAILs or ERRORs?

There are 42 FAILs in both before and after images. 

There are 45 ERRORs in before and 0 in after. 

However, I think the SKIPing is what I wanted :)

**Comment by felipesanches** [comment]
* ERROR means code bug.
* FAIL means "font problem detected"

So, I meant you should see FAILs regarding non-canonical names on test/001 output. You should **never* see ERRORs because we're supposed to fix all fontbakery bugs :-)

**Comment by felipesanches** [comment]
@davelab6 I think this issue should be closed. Please do so, unless there's something else you think is still wrong here.

**Comment by davelab6** [comment]
How can there be 45 fails if a single font is non-canonical? Surely that will be 1 fail?

**Comment by davelab6** [comment]
(Indeed, I am going to close this - I suppose that the 42 FAILs already includes the single FAIL result from check 001, and always did, and so there's no reason for it to become 43 :)

**Comment by felipesanches** [comment]
I meant that 45 font files with non-canonical names would lead to 45 FAILs.

**Comment by felipesanches** [comment]
Those FAILs on test/020 are for other reasons (bad weightclass). Non-canonical names here would merely result in SKIPs intead.

**Comment by felipesanches** [comment]
This conversation may sound confusing because we're discussing 2 different tests with different purposes at once.
