### ISSUE TITLE
Make it convenient and fast to run FB over families on a large collection such as github.com/google/fonts

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1609]
When running fontbakery with `~/gfonts/*/*/*.ttf` I get good results if the tests deal with single ttFont objects (testing aspects of a single font file), so for the Google Fonts collection that means I get roughtly 2400 testruns.

But if the test deals with multiple ttFont objects (tests that validate things across a given family), then this command line invokation will treat all 2400 font files as if they were all members of a single family, which is clearly bad.

I'd like to have a different behaviour here. I'd wish to get the set of font files split in groups of fontfiles defined by their directory paths. Here we have an implicit rule that all files of a given family are placed in a single directory and that if files are in different directories, then it means they belong to different families.

I think @graphicore may be interested in discussing this one.

**Comment by felipesanches** [comment]
For instance, on #1607 I was not able to easily run **test/001** on the whole collection to showcase to @davelab6 the expected FAILs due to non-canonical names.

We have a helper shell script for running fontbakery on the full collection, but that runs all tests, instead of a single one.

**Comment by davelab6** [comment]
SGTM! I'm moving this up to the next point release after the one due this week :)

**Comment by felipesanches** [comment]
great!

This would also mean that we would deprecate **com.google.fonts/test/002**:
```
  """Checking all files are in the same directory

     If the set of font files passed in the command line
     is not all in the same directory, then we warn the user
     since the tool will interpret the set of files
     as belonging to a single family (and it is unlikely
     that the user would store the files from a single family
     spreaded in several separate directories).
  """
```

**Comment by felipesanches** [comment]
I'd love to hear from @graphicore here as well, though. What do you think, Lasse ?

**Comment by graphicore** [comment]
I think we have different purposes here and should be careful what we wish for. The original idea is to test by families, and as such **com.google.fonts/test/002** is very good. However, The fontbakery runner itself has no idea about a `family`  at all, it doesn't even know what a font is, all that is handled via `@condition`s and iterargs and the tests of course.
I think we can maybe do something that comes close to your request, but I wouldn't like to complicate the runner much by adding another level to consider. Maybe, we'll have different specs for running a collection wide test and for running a family test, but I'd very much prefer to see this handled on the spec side.

**Comment by felipesanches** [comment]
And it would also mean deprecating the hacky check-collection shell script, as simpy doing this would be enough:

```
fontbakery check-googlefonts ~/gfonts/*/*/*.ttf
```

**Comment by davelab6** [comment]
Test 002 needs modification, not deprecation; all the files should still be checked to be within the same directory - however, I am surprised when reading https://github.com/googlefonts/fontbakery/blob/3c7eb1eacbdc31a379de81182870d741825c2dc5/Lib/fontbakery/specifications/googlefonts.py#L82-L107 that only font files (TTFs) are checked - what about the METADATA and DESC files?

**Comment by felipesanches** [comment]
Families are such an important concept for font-testing that I think the fontbakery test runner should be natively able to grasp that and offer helpers to deal with them.

**Comment by graphicore** [comment]
* How do you think the output would be?
* What is the problem with `test/001` and the current situation?

**Comment by felipesanches** [comment]
METADATA and DESC files are tested as well. But they are inferred from the path of the corresponding TTFs. You never pass a METADATA file to fontbakery on the command line.

**Comment by graphicore** [comment]
The testrunner has no idea about semantics. These are supposed to be in the spec. No matter how importnat the semantics are ;-)

**Comment by graphicore** [comment]
I would love to pass METADATA.pb etc directly, this is just historical. I would also love to be independent from a filesystem, just have all in memory, for that matter.

**Comment by felipesanches** [comment]
I think the current behaviour is clumsy for family-wide tests. I've already described the details of the problem at hand on the first post of this issue. Maybe @davelab6 can elaborate on what behaviour is best for him and the team.

**Comment by graphicore** [comment]
Also, if we can solve it within the spec, what's the deal, solved is solved, right?

**Comment by felipesanches** [comment]
The filesystem versus in-memory object discussion would be better in a separate issue, though.

**Comment by felipesanches** [comment]
"solved is solved" ? Well... yes... But "well designed is solved" would be better :-)

So let's try to come up with proposals here for a good solution either via (a) test-runner changes or via (b) changes to the spec file.

**Comment by felipesanches** [comment]
As a user of my own program I constantly stumble on this limitation of the command line invokation treating the whole set of TTFs as a single huge family with 2400 font files :-P

I'd like to somehow get rid of that bad behaviour of the tool and I am unsure how to deal with it in a sane way.

**Comment by graphicore** [comment]
I have to think about this anyways, but at the moment I think the proposed solution is a bit impulsive and a huge change of the initial concept -- which clearly is testin a family at a time. We also plan do it like this in the dashboard. I'm happy with proposals, I'm just saying there may be a way to do it differently.

Thus, now I'd rather like to hear about the specific outcome that is requested than where to do it.

**Comment by felipesanches** [comment]
This is not a big issue for the dashboard because I suppose each container will be invoking fontbakery with the set of TTFs of a single family. But as a command line tool, there should be a good usage scenario for testing a big collection without mixing the TTFs of them all.

**Comment by graphicore** [comment]
We can do it with a collection-runner script, that internally runs many family-wide fontbakery checks and collects the result. Not a single change would be needed for the runner or the spec. Maybe a reporter would need to be modified.

**Comment by felipesanches** [comment]
It may sound impulsive because it is something that has ben bugging me for a long time, so in my head this is a big-old problem, but it is the first time I try to describe it here. And the potential solutions ended up mixed with the problem description above. :-)

**Comment by graphicore** [comment]
talking about a new, not hacky `fontbakery check-collection`

**Comment by davelab6** [comment]
Yeah my intuition is that we want to upgrade the bash script to a python script, that calls the FB classes directly instead of via their command line.

**Comment by graphicore** [comment]
>  my intuition is that we want to upgrade the bash script to a python script, that calls the FB classes directly instead of via their command line.

Probably the most straight forward thing to do. I think, as long as we don't need access to all files of the collection from one single test, this should be fine. A modified reporter and we see no real difference, we can unify all runs into one united report.

If we introduce this on a lower level, we'll have  to modify some tests, to mark them to run once per `family`(would be an argument) which is now implicit if they do not require  `font` or `ttFont` (then they run once per font). Maybe the iterargs mechanism needs some tweaks. It's more interesting to build this stuff for me, but the other option seems faster.

I would consider both before writing anything.

**Comment by davelab6** [comment]
No, I don't think we have yet needed to access to all files of the collection from one single test; in such a case, then what @felipesanches already does (run a single test across all the fams) is sufficient. 

However, we definitely should already have some 'family-wide' checks that run once per family, and making them explicitly so seems like A Good Thing, especially because we have a couple of open issues to make 'super-family-wide' checks, and perhaps the same explicit approach that works for "x" family checks can work for "x + y + x" super-family checks...

* https://github.com/googlefonts/fontbakery/issues/1568
* https://github.com/googlefonts/fontbakery/issues/1487

**Comment by felipesanches** [comment]
One side issue here is that some single-font tests fail to run for the full set of TTFs because at some point we reach a memory allocation crash. Even if it does not crash, I can notice that the tests run slower and slower as fontbakery progresses in the batch of 2400 TTF files. It seems to me that we should be freeing up memory as we go.

**Comment by graphicore** [comment]
>  It seems to me that we should be freeing up memory as we go.

Yeah, that's clearly due to the caching of the `@condition`s I guess we'll have to be smart here, because not caching the ttx-objects will free ram but cause more i/o and fonttools parsing.

pytest has `@fixture` which is very much in concept as our `@condition`, they can specify a `scope` in which a fixture is kept alive.

But maybe something simpler will do, like a general `dont-cache` flag on the CLI. This should be another issue.

> ... I can notice that the tests run slower and slower

Is it because of swapping?

**Comment by graphicore** [comment]
The memory thing would be much better handled by the improved `fontbakery check-collection` script.

The other thing, I see that we need it or something like it for super-families and such. 

I this about right (as a starting point):

`Collection > Super Family > Family > Font`

I think this will be a new type or extension of iterarg.

**Comment by felipesanches** [comment]
yes, that hierarchy makes a lot of sense. Thanks for reminding us of the super-family need as well.

**Comment by davelab6** [comment]
Also sounds about right to me, in that we want be able to run or define checks for each of those levels.

**Comment by HinTak** [comment]
Since the fonts are stored and sorted in a directory hierarchy, should it not be quite simple to compare, say, successive font location to see if they are in the same directory, or same grand-parent directory, and decache if not?

**Comment by felipesanches** [comment]
This is a duplicate of #2431
