### ISSUE TITLE
Make com.google.fonts/test/163 a WARN

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1621]
When running the check-googlefonts on [Barlow](https://github.com/jpt/barlow), we get the following

```
>> com.google.fonts/test/163 with ((u'font[14]', '/Users/marc/Documents/googlefonts/manual_font_cleaning/barlow/fonts/ttf/Barlow-SemiBold.ttf'),)
   Combined length of family and style must not exceed 20 characters.
 * FAIL: The combined length of family and style exceeds 20 chars in the following 'WINDOWS' entries: FONT_FAMILY_NAME = 'Barlow SemiBold' / SUBFAMILY_NAME = 'Regular'

```

For the test rational we have
>    According to a Glyphs tutorial (available at
      https://glyphsapp.com/tutorials/multiple-masters-part-3-setting-up-instances),
      in order to make sure all versions of Windows recognize it as a valid
      font file, we must make sure that the concatenated length of the
      familyname (NAMEID_FONT_FAMILY_NAME) and style (NAMEID_FON

When I look at the glyphs [url](https://glyphsapp.com/tutorials/multiple-masters-part-3-setting-up-instances), we get
> One good piece of advice: Keep your style name short to avoid problems in Windows. How short? Well, you are on the safe side if the combined length of family and style name does not exceed 20 characters. If the name is too long, Windows may think the font is invalid.

Again, this value feels arbitrary. The screenshot looks like its from Win XP and the tutorial was written in 2013 when this OS was obviously more in use. 

20 characters for both combinations seems unbelievably short. This test will fail on most of the families in our collection. Not once has a user ever reported it.

**Comment by felipesanches** [comment]
We can make it a WARN. Or we can completely deprecate it. I'd prefer to keep it as a WARN as it seems that it affected some version of Windows.

@davelab6 You requested it at https://github.com/googlefonts/fontbakery/issues/1488 What do you think?

**Comment by davelab6** [comment]
Moving this check to a WARN seems good to do. 

(The fact that we have no user reports is not a good signal that there is no problem; GlyphsApp has won a huge market share across all Latin foundries and their paying customers demand detailed support whereas with us a lot of people say "you get what you pay for" and their time to report things is money they won't spend.

However XP is now something can should consider deprecated, but not quite obsolete.)
