### ISSUE TITLE
com.google.fonts/test/034: xAvgCharWidth bakery vs glyphs vs font val 

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1622]
When running check-google fonts on [Barlow](https://github.com/jpt/barlow) we get:

```
>> com.google.fonts/test/034 with ((u'font[16]', '/Users/marc/Documents/googlefonts/manual_font_cleaning/barlow/fonts/ttf/Barlow-Thin.ttf'),)
   Check if OS/2 xAvgCharWidth is correct.
 * FAIL: OS/2 xAvgCharWidth is 500 but should be 501 which corresponds to the average of all glyph widths in the font
```

Recently this test has been off by just a unit on the most recent versions of glyphs.

In Ms Val, it is a completely different story:
![screen shot 2017-10-25 at 15 27 26](https://user-images.githubusercontent.com/7525512/32004181-126a016e-b999-11e7-9316-666734dd7bd5.png)

So we have:

Glyphs: 500
FB: 501
Ms Font Val: 420

In the MS Spec:
> The value for xAvgCharWidth is calculated by obtaining the arithmetic average of the width of all non-zero width glyphs in the font. Furthermore, it is strongly recommended that implementers do not rely on this value for computing layout for lines of text, especially for cases where complex scripts are used. 

https://www.microsoft.com/typography/otspec/os2.htm#acw

**Against MS**
When I look at the FB [implementation](https://github.com/googlefonts/fontbakery/blob/6de3a1b1ed3fee1620311b6c34e99d470efa06e3/Lib/fontbakery/specifications/googlefonts.py#L1033-L1036), I can't see anything that would lead to such a drastic difference. 

**Against Glyphs**
Perhaps they do floor rounding for this calculation?. We use `round` which will round higher any float >.5 e.g 4.5 is 5

cc @schriftgestalt

**Comment by anthrotype** [comment]
I wouldn't care too much about xAvgCharWidth. See @behdad's https://github.com/fonttools/fonttools/pull/1079#issuecomment-338724298

> We discussed having an MVAR entry for that item but everyone agreed that value is useless...

**Comment by davelab6** [comment]
Maybe our check can accept values that off by 1-2-5 units?

**Comment by m4rc1e** [comment]
Could this also be set to a WARN?

**Comment by davelab6** [comment]
I would prefer the value to be somewhat sensical, since things like getflourish.github.io/anatomy-of-typefaces use it

**Comment by anthrotype** [comment]
yeah, WARN sounds good, and allow a tolerance of +/- 1 unit

**Comment by felipesanches** [comment]
OK. I think I have enough input to come up with a sensible solution to this.

I'm working on this one now.

**Comment by HinTak** [comment]
See https://github.com/HinTak/Font-Validator/issues/33
