### ISSUE TITLE
com.google.fonts/test/065: Is there kerning info for non-ligated sequences? change to WARN

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1623]
According to the test rationale:
>Fonts with ligatures should have kerning on the corresponding
      non-ligated sequences for text where ligatures aren't used
      (eg https://github.com/impallari/Raleway/issues/14).

This shouldn't be a FAIL, it should be WARN imo. In many instances, non ligated sequences don't need kerning, in some cases they do (The Raleway example is definitely one where it is needed).

This test is similar to the recommended contour count and out of bounds coordinates. Both are just WARN.

**Comment by davelab6** [comment]
Agreed
