### ISSUE TITLE
Restore fontbakery-fix-italicangle.py

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1630]
## Observed behaviour

In the past there was a italic angle report & hotfix script, that worked like this to ensure italic angles are all equal:

```
$ fontbakery-fix-italicangle.py ~/fonts/ofl/merriweather/Merriweather-*ttf
| filename                     |   italicAngle |
|:-----------------------------|--------------:|
| Merriweather-Black.ttf       |           0   |
| Merriweather-BlackItalic.ttf |          -8   |
| Merriweather-Bold.ttf        |           0   |
| Merriweather-BoldItalic.ttf  |          -8   |
| Merriweather-Italic.ttf      |          -8   |
| Merriweather-Light.ttf       |           0   |
| Merriweather-LightItalic.ttf |          -7.8 |
| Merriweather-Regular.ttf     |           0   |
$
```

(From https://github.com/EbenSorkin/Merriweather/issues/32

## Expected behaviour

This tool is no longer available. I thought we already fixed the problem that some tools went missing, but this seems to have slipped through the net :) 

Please bring it back :)

**Comment by felipesanches** [comment]
ok, but I'll rename it to list-italicangle as it does not fix anything. It only lists.
