### ISSUE TITLE
Script to detect characters not in subsets

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1631]
To solve https://github.com/google/fonts/issues/1285 I need a small script that will compare all the characters in all the fonts in the GF repo against the bunch of GF subsets, and against the bunch of glyph sets, and tell us what characters and not in each bunch :)

**Comment by felipesanches** [comment]
What's the difference between this request and #1466 ? Can this be closed as a duplicate and the description of this issue be posted there as an additional comment ?

**Comment by davelab6** [comment]
Yep, its a duplicate!
