### ISSUE TITLE
Splitting out helper scripts as a separate project

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1639]
I would like to consider and discuss here the idea of eventually splitting fontbakery into 2 separate python packages:

* (a) FontBakery itself as a tool exclusively focused on quality assurance of font families. A.k.a. the "ultimate typography testsuite".
* (b) A second package to host helper scripts such as the plethora of scripts we currently have in our `bin/` directory. A whole bunch of tiny tools for inspecting and hotfixing font files.

The rationale to that proposal relates to a common complain about the difficulty to install fontbakery on a system due to its large number of dependencies. The testsuite portion of the code still requires a lot of dependencies, but there are things that are really only needed on the scripts.

It seems to me that a fontbakery-scripts package could pretty easily list fontbakery as a dependency in its setup.py so that it would be doable to install everything by simply performing a pip install fontbakery-scripts, but users who only need to run the testsuite can skip installing the scripts and their extra dependencies.

A second reason is simply the fact that right now the project tries to accomplish 2 fairly separate purposes: (a) QA automated reports and (b) code snippets for font inspection & hotfixing.

**Comment by graphicore** [comment]
I like this. We should do it so that #1515 is satisfied as well. @chrissimpkins suggested using [PEP 420 - Implicit Namespace Packages](https://www.python.org/dev/peps/pep-0420/) which is already a python built in.

**Comment by davelab6** [comment]
We should probably move (b) into https://github.com/googlefonts/tools :)

**Comment by graphicore** [comment]
Uh, seems like PEP 420 support for python 2.7 is sub-optimal https://github.com/pypa/setuptools/issues/406#issuecomment-311234430

**Comment by chrissimpkins** [comment]
:+1:

**Comment by anthrotype** [comment]
pkgutil-style namespace packages work well in both python 2 and 3
https://packaging.python.org/guides/packaging-namespace-packages/

**Comment by chrissimpkins** [comment]
You decide to transition all QA tools to the tools repo?

**Comment by felipesanches** [comment]
yes. It is all there and it is also already available as a pip package since this weekend when I made a first release of gftools. Install it with:

```
pip install gftool
```

and use it just like you used fontbakery (with the subcommands and so on...)

**Comment by felipesanches** [comment]
http://pypi.python.org/gftools

**Comment by chrissimpkins** [comment]
Thanks for the link Felipe!

**Comment by felipesanches** [comment]
you're welcome!

I'll also add that info to the README and to the CHANGELOG !

**Comment by felipesanches** [comment]
done!

**Comment by davelab6** [comment]
Congrats! 

This is a pretty big change so I suggest to tag and release 0.3.3 soon (like this week)

I moved stuff from 0.3.3 to 0.3.4 - does https://github.com/googlefonts/fontbakery/milestone/61 look doable this week?
