### ISSUE TITLE
When updating a family, check version numbers increase

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1640]
## Observed behaviour

https://github.com/google/fonts/pull/1304 didn't check and fail that the version number didn't increase; I guess this is because it was checking what is on production, but since https://github.com/google/fonts/pull/1301 hadn't made it all the way to production, the check passed, incorrectly. 

## Expected behaviour

- [ ] If family exists in production, check that version numbers increase, both in prod, and in github; perhaps via Github PR checks (travis style)

**Comment by davelab6** [comment]
Updated issue text

**Comment by felipesanches** [comment]
I cannot replicate this issue. The test passes nicely when running **test/005** on ofl/pacifico from google/fonts repo (master branch, after https://github.com/google/fonts/pull/1304 was merged) with the current fontbakery code from master branch.

And the DESCRIPTION file there is still 398 bytes long and the test is working.

It puzzles me that it actually failed at some point. Are you sure about that @davelab6 / @m4rc1e ?

**Comment by felipesanches** [comment]
![screenshot at 2017-11-06 19 52 54](https://user-images.githubusercontent.com/213676/32465854-1ab4e05e-c32c-11e7-9527-2c4344dea009.png)
