### ISSUE TITLE
Review description length check

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1641]
## Observed behaviour

https://github.com/google/fonts/pull/1301 failed a check that the description must be longer than 200 bytes but the description is 398 bytes.

## Expected behaviour

- [ ] The description check should work reliably

**Comment by felipesanches** [comment]
OK, I'll look into it

This should be a trivial test. I'm shocked that it apparently misbehaves.

**Comment by felipesanches** [comment]
I cannot replicate this issue. The test passes nicely when running **test/005** on ofl/pacifico from google/fonts repo (master branch, after https://github.com/google/fonts/pull/1304 was merged) with the current fontbakery code from master branch.

And the DESCRIPTION file there is still 398 bytes long and the test is working.

It puzzles me that it actually failed at some point. Are you sure about that @davelab6 / @m4rc1e ?

**Comment by felipesanches** [comment]
![screenshot at 2017-11-06 19 52 54](https://user-images.githubusercontent.com/213676/32469544-606c35d0-c33a-11e7-8c94-1f03979311af.png)

**Comment by felipesanches** [comment]
Please reopen providing further evidence of the issue and how to replicate it.

**Comment by davelab6** [comment]
https://github.com/google/fonts/pull/1301

<img width="958" alt="screen shot 2017-11-06 at 19 48 39" src="https://user-images.githubusercontent.com/261579/32471484-83639a88-c32b-11e7-8f74-19695c9238b1.png">

@m4rc1e please explain how this came to fail :)

**Comment by felipesanches** [comment]
Latest Fontbakery testsuite has got **125** tests. This screenshot reports only **120**. This looks like an old release of Fontbakery. Please try to test using the latest code from `master` branch.

**Comment by felipesanches** [comment]
@m4rc1e can you verify this, please?

**Comment by felipesanches** [comment]
I suspect this was an old version of fontbakery. @m4rc1e Please reopen the issue if you can replicate the problem with the latest code from fontbakery's git master.

**Comment by felipesanches** [comment]
I closed it because it works for me.

**Comment by davelab6** [comment]
Sounds good, thanks! :)
