### ISSUE TITLE
'kern' version should not be 1

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontbakery#1644]
https://www.microsoft.com/typography/otspec/kern.htm doesn't specify v1. IIUC (from @anthrotype's comments) 1.0 is only use for Apple AAT.

Report existence of a 1.0 `kern` table as a problem. Can be detected in Python using something like `'kern' in f and f['kern'].version == 1`

In my local [possibly outdated] clone of our google/fonts `ofl/coda/Coda-Regular.ttf` has this problem.

**Comment by m4rc1e** [comment]
I thought we didn't want kern tables?

https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/specifications/googlefonts.py#L2437-L2449

**Comment by felipesanches** [comment]
![screenshot at 2017-11-08 14 11 36](https://user-images.githubusercontent.com/213676/32559625-c11c56d0-c48e-11e7-90e7-9c0d03a72b8c.png)

**Comment by felipesanches** [comment]
But that caught our attention to another issue. I see that this test checks for 'KERN'. According to the spec, it seems we should be looking for 'kern' instead.

**Comment by felipesanches** [comment]
@rsheeter are you OK with closing this issue as test/066 will report any kern table found in a font as a problem?

**Comment by felipesanches** [comment]
I assume the issue has been addressed. Re-open in case you disagree.
