### ISSUE TITLE
Integrate Android Platform Frameworks Font Chain Linter Checks

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1652]
## Observed behaviour

We don't run the checks that Android Platform Frameworks team runs

## Expected behaviour

We run those checks

## Resources and exact process needed to replicate

https://android.googlesource.com/platform/frameworks/base/+/master/tools/fonts/fontchain_linter.py

**Comment by m4rc1e** [comment]
Nice.

I suspect this linter is being used to check just one family? The check_vertical_metrics function is checking against cached values.  This test also uses a negative integer for the winDescent. I've always known this value to be positive (I'll see if I can get a citation for this)

In order for us to use it, we'll have to change a few bits such as removing the sys.exit() functions

**Comment by graphicore** [comment]
If you need a hack, you can catch `SystemExit`

``
try:
    sys.exit(1)
except SystemExit:
     print('But it is not this day!')
```

**Comment by felipesanches** [comment]
The reliance of that code on a `_fallback_chain` global list of fonts to be tested that is fed from parsing an XML file makes it unsuitable for direct use in FontBakery.

We could, though, port those checks into our codebase if they're deemed useful.

**Comment by felipesanches** [comment]
The check called `check_cjk_punctuation` only tests font files that do not support scripts `Hans`, `Hant`, `Jpan` or `Kore`. And then it makes sure that none of the codepoints between 0x3000 and 0x301F are implemented in the font.

* **Hans**: Simplified Han, also called Simplified Chinese, is the official script of the People's Republic of China (PRC) and Singapore.
* **Hant**: The Traditional Han script, also known as Traditional Chinese.
* **Jpan**: Japanese (alias for Han + Hiragana + Katakana)
* **Kore**: Korean (alias for Hangul + Han)

Even though the check fails for non-cjk fonts with chars in the codepoint range 0x3000 - 0x301F, I have the impression that perhaps the full "CJK Symbols and Punctuation" range from 0x3000 to **0x303F** should be tested against instead: http://www.unicodemap.org/range/61/CJK_Symbols_and_Punctuation/

**Comment by felipesanches** [comment]
I wonder how frequently this goes bad, though...

**Comment by felipesanches** [comment]
If we consider this useful I can port it into FontBakery and then I would describe this as "Check that CJK Symbols and Punctiuation characters are not supported by non-CJK fonts"

What would be the rationale for that? Would it be meant to avoid bloating the font file size with unnecessary CJK glyphs ? Or is there some other reason?

**Comment by felipesanches** [comment]
As @m4rc1e mentioned above, there are some hardcoded magic numbers on `check_vertical_metrics`. I would not port that unless there's a clarification on the intention behind that checking routine.

**Comment by felipesanches** [comment]
Also, the third check is about testing coverage on emoji fonts. I think this is most likely out of scope for the fonts in the Google Fonts collection, right? Or do we have fonts in the collection shipping emoticons? Even if we do, I think such glyphs are not required on any of the GF glyph-sets.

**Comment by davelab6** [comment]
Yes, no emoji.

VM magic is likely to keep the metrics from regressing, and can be ignored.

**Comment by felipesanches** [comment]
thanks!

**Comment by simoncozens** [comment]
So in summary:

* We don't want the fonts_xml check
* We don't want the compact_only_fallback check
* We don't want the vertical metrics check
* We're not sure about the CJK punctuation check
* We already have canonical name checks
* We don't want the emoji check

So I think there is nothing to be done here.
