### ISSUE TITLE
usWinAscent & usWinDescent greater than bbox?

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1655]
In some fonts, the usWinAscent, usWinDescent are greater than the yMax, yMin. Personally, I can't see this causing any problems. Could we change check *com_google_fonts_test_040* to pass these cases? it should still fail if the values are less than yMax, yMin because clipping will occur on some Win apps.

**Comment by davelab6** [comment]
Yeah afaik this will not cause a problem, just additional white space,
which is required for short family members to have consistent line heights

**Comment by m4rc1e** [comment]
@davelab6 agreed. However, If a family has already been released with win metrics which are greater than the bbox, I think we should keep them as they are.

**Comment by khaledhosny** [comment]
It is often required that win ascent/descent be greater than font bbox to account for combining marks. The check should test that the ascent/descent values are not **smaller** thank bbox, larger values can be a warning or just silently accepted.

**Comment by felipesanches** [comment]
thanks, @m4rc1e and @khaledhosny !
