### ISSUE TITLE
Add TTF checks as outlined in OFF/X

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#167]
Place holder for me to turn http://lists.w3.org/Archives/Public/public-webfonts-wg/2013Jun/0023.html into a set of downstream checks

**Comment by felipesanches** [comment]
@twardoch, would you like to take a look at this one nowadays?

**Comment by simoncozens** [comment]
Original requestor does not seem desperate to have this check, and most of the recommendations are either out of date or covered by other checks...
