### ISSUE TITLE
variable fonts: require STAT table on Mac

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1671]
@davelab6 said:

Erik van Blokland said in https://twitter.com/letterror/status/911910519459729409 that WebKit in 10.12 requires a STAT table.

We should have a check for that.

**Comment by felipesanches** [comment]
![screenshot at 2017-12-12 18 09 39](https://user-images.githubusercontent.com/213676/33906011-b87f0d3a-df67-11e7-9895-a86c91b721d3.png)

![screenshot at 2017-12-12 18 10 10](https://user-images.githubusercontent.com/213676/33906025-c0b1bcb4-df67-11e7-96d2-001b09403480.png)

**Comment by felipesanches** [comment]
I'll add "stat" to the list of required tables on **check/052**, but the twitter conversation backed-up above does not make it clear exactly why it is **(and if it is)** strictly required.

**Comment by moyogo** [comment]
WebKit only requires the STAT table for variable fonts; non-variable fonts are fine without it.
The specs are pretty clear about this.

**Comment by sladen** [comment]
Think the conversation above is only about variable fonts:
> "Anyone installed #variablefonts in macOS … @youknowcj discovered Webkit requires a stat table."

don't think `STAT` or not, should have have any impact on older, or non-variable fonts.

The Webkit/MacOSX question can probably be solved by taking a working variable font, and stripping just the `STAT` table, and seeing what happens.

**Comment by felipesanches** [comment]
I'd appreciate if anyone could perform this experiment. I do not own a Mac.

**Comment by felipesanches** [comment]
Perhaps I should add a condition:

```python
@condition
def is_variable_font(ttFont):
  return "fvar" in ttFont.keys()
```

...and then only require a STAT table when the condition is True.

**Comment by moyogo** [comment]
On High Sierra 10.13.3, the STAT table is required by Webkit for OT variable fonts to work properly. Without the STAT table, the variation tables are not read properly but read as GX tables and interpolation behaves incorrectly. With the STAT table, the variation tables are read properly and interpolation behaves as expected.

Having or not the STAT table, doesn’t affect non-variable fonts.

A TTF with an fvar table but no STAT table is most likely a GX font. The only way to know if a font with a fvar table is an OT variable font is if it also has a STAT table.
So your test would not accept GX fonts, which may be what you want.

**Comment by davelab6** [comment]
I think we don't want GX fonts

**Comment by felipesanches** [comment]
yeah, I think that detecting variable fonts as those that have fvar and then ERRORing if they lack STAT is good enough for Google Fonts purposes.
