### ISSUE TITLE
Kerning checks are buggy

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1675]
See https://github.com/daltonmaag/ubuntu/issues/36#issuecomment-352291811

**Comment by davelab6** [comment]
@felipesanches please fix this ASAP :)

**Comment by felipesanches** [comment]
So, this means completely deprecating **check/066**, right?

https://github.com/googlefonts/fontbakery/blob/4f74de600f32a788ce59c039b7ee1b75536a42ec/Lib/fontbakery/specifications/googlefonts.py#L2521-L2533

**Comment by davelab6** [comment]
No. Fonts SHOULD have kerning in BOTH 'kern' table and 'GPOS' tables.

**Comment by felipesanches** [comment]
So it means that the kern table is indeed mandatory, instead of optional. I think **check/052** ("Font contains all required tables?") should be updated accordingly so that a missing kern table is reported as an error.

https://github.com/googlefonts/fontbakery/blob/49a5ab5b55a078115925092a86d00f247808aaef/Lib/fontbakery/specifications/googlefonts.py#L1934-L1948

**Comment by moyogo** [comment]
> No. Fonts SHOULD have kerning in BOTH 'kern' table and 'GPOS' tables.

CAN instead of SHOULD would be better.

**Comment by felipesanches** [comment]
@davelab6 said:

"Google Fonts ingests fonts made for download and use as desktops, and does all web font optimizations in the serving pipeline (using libre libraries that anyone can replicate.)"

And also:

"TTFs intended for desktop users (and thus the ones intended for GF) should have both KERN and GPOS tables."

**Comment by felipesanches** [comment]
I hope this is good now. Crossing fingers that the Travis checks pass. I'll have to leave now. I'll be away from the computer throughout the day, but I can look at it again tonight.

Cheers!

**Comment by madig** [comment]
Is the following FontForge output (test 038) seen as an error?
```
[...]
This font contains both a 'kern' table and a 'GPOS' table.
  The 'kern' table will only be read if there is no 'kern' feature in 'GPOS'.
[...]
```

**Comment by sladen** [comment]
That FontForge warning might want toning down a little.

**Comment by madig** [comment]
Or you need to differentiate between warnings and errors in that output...

**Comment by khaledhosny** [comment]
The FontForge warning above is about FontForge’s own behavior when reading fonts. Layout engines might ignore `kern` table completely if there is a `GPOS` table whether it has a `kern` feature or not (HarfBuzz does that, at least).

**Comment by madig** [comment]
Does it make sense to include a kern table in variable fonts?
