### ISSUE TITLE
com.google.fonts/check/052 fails to see tables that exist

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1681]
## Observed behaviour
```
>> com.google.fonts/check/052 with ((u'font[0]', 'font2/Ubuntu-R.ttf'),)
   Font contains all required tables?
 * FAIL: This font is missing the following required tables: [head, name, OS/2, maxp, STAT, hmtx, cmap, post, hhea]

   Result: FAIL
```

## Expected behaviour

Test should complain only about STAT (in a non-variable font?). TTX lists:
```
Listing table info for "font2/Ubuntu-R.ttf":
    tag     checksum   length   offset
    ----  ----------  -------  -------
    GPOS  0xD10650EA   147128   251176
    GSUB  0xE0E2EEE8     3892   398304
    LTSH  0x506B5618     1268     5608
    OS/2  0x892FF9AC       96      456
    VDMX  0xEFD8F7C5     5846     6876
    cmap  0x71973EF1      984    48236
    cvt   0x2D242406      532    51544
    fpgm  0x75BD4574     1571    49220
    gasp  0x00190009       16   251160
    glyf  0x0194DC54   150348    57136
    hdmx  0x8BC53662    35512    12724
    head  0x18F0D67B       54      332
    hhea  0x10B41148       36      388
    hmtx  0xA7ACC161     5056      552
    kern  0x8BC8A6E5    31602   207484
    loca  0x0644951B     5060    52076
    maxp  0x0A9708D1       32      424
    name  0x3C956283      674   239088
    post  0xE70AB679    11393   239764
    prep  0xC39F413C      752    50792
```

## Resources and exact process needed to replicate

1. Download and extract [test.tar.gz](https://github.com/googlei18n/ufo2ft/files/1587871/test.tar.gz)
2. `fontmake --keep-overlaps --no-production-names --keep-direction -o ttf -u Ubuntu-R.ufo`
3. `fontbakery check-googlefonts master_ttf/Ubuntu-Regular.ttf`

**Comment by felipesanches** [comment]
Oh! That seems pretty bad! We gotta fix this one asap!

**Comment by felipesanches** [comment]
OK! I built Ubuntu-Regular using fontmake now and then running fontbakery with the commit above (ebf9e8f) complains only about STAT (as you suggested should happen):

![screenshot at 2018-01-15 13 29 00](https://user-images.githubusercontent.com/213676/34949758-30271d82-f9f8-11e7-9c7c-35f23f5c2fe6.png)

**Comment by sladen** [comment]
Think this might be backwards slightly:
* https://www.microsoft.com/typography/otspec/otff.htm
  "STAT 	Style attributes (required for variable fonts, optional for non-variable fonts)"

It only matters when we are processing a variable font (when `STAT` must be present).  In all cases it doesn't matter either way.

**Comment by felipesanches** [comment]
According to https://github.com/googlefonts/fontbakery/issues/1671 STAT table is required on WebKit on MacOS 10.12

**Comment by felipesanches** [comment]
let's continue this conversation at #1671, please.

**Comment by sladen** [comment]
(#1671 is about validating variable fonts.  The example TTF here, is _not_ variable.)

**Comment by felipesanches** [comment]
This should be working properly now.
