### ISSUE TITLE
com.google.fonts/check/030 fails to see license fields

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1682]
## Observed behaviour

```
>> com.google.fonts/check/030 with ((u'font[0]', 'font2/Ubuntu-R.ttf'),)
   "License URL matches License text on name table?
 * FAIL: A License URL must be provided in the NameID 14 (LICENSE INFO URL) entry.

   Result: FAIL
```

## Expected behaviour

The check should not complain about missing URL. TTX sees:
```
  <name>
    <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
      Copyright 2011 Canonical Ltd.
    </namerecord>
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Ubuntu
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Regular
    </namerecord>
    <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
      Ubuntu Regular Version 0.83
    </namerecord>
    <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
      Ubuntu Regular
    </namerecord>
    <namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
      Version 0.83
    </namerecord>
    <namerecord nameID="6" platformID="3" platEncID="1" langID="0x409">
      Ubuntu-Regular
    </namerecord>
    <namerecord nameID="7" platformID="3" platEncID="1" langID="0x409">
      Ubuntu and Canonical are registered trademarks of Canonical Ltd.
    </namerecord>
    <namerecord nameID="8" platformID="3" platEncID="1" langID="0x409">
      Dalton Maag Limited
    </namerecord>
    <namerecord nameID="9" platformID="3" platEncID="1" langID="0x409">
      Dalton Maag Limited
    </namerecord>
    <namerecord nameID="11" platformID="3" platEncID="1" langID="0x409">
      http://www.daltonmaag.com/
    </namerecord>
    <namerecord nameID="12" platformID="3" platEncID="1" langID="0x409">
      http://www.daltonmaag.com/
    </namerecord>
    <namerecord nameID="13" platformID="3" platEncID="1" langID="0x409">
      Licensed under the Ubuntu Font Licence 1.0.
    </namerecord>
    <namerecord nameID="14" platformID="3" platEncID="1" langID="0x409">
      https://www.ubuntu.com/legal/terms-and-policies/font-licence
    </namerecord>
  </name>
```
## Resources and exact process needed to replicate

1. Download and extract [test.tar.gz](https://github.com/googlei18n/ufo2ft/files/1587871/test.tar.gz)
2. `fontmake --keep-overlaps --no-production-names --keep-direction -o ttf -u Ubuntu-R.ufo`
3. `fontbakery check-googlefonts master_ttf/Ubuntu-Regular.ttf`

**Comment by felipesanches** [comment]
Currently the check expects eigther Apache or OFL. That's why it did not recognize the Ubuntu Font License as an acceptable one. Perhaps we should add Ubuntu Font License to the list of expected licenses. But for that we'll have to hear from @davelab6 because I am not sure what's the licensing policy for Google Fonts. I thought it was restricted to OFL and Apache only, but Dave may help us clarify this.

Having said that, indeed the error message is a bit confusing because it makes the user think that a license url was not detected at all, while what actually happened was that fontbakery was able to detect it, but rejected it as not being one of the licenses it currently considers acceptable.

**Comment by davelab6** [comment]
We can only accept the ufl for the existing ufl fonts, so the check will be
to special case that. Other changes sound good

**Comment by madig** [comment]
```
>> com.google.fonts/check/030 with ((u'font[6]', 'build/Ubuntu-Medium.ttf'),)
   "License URL matches License text on name table?
 * FAIL: A known license URL must be provided in the NameID 14 (LICENSE INFO URL) entry. Currently accepted licenses are Apache or Open Font License. For a small set of legacy families the Ubuntu Font License may be acceptable as well.

   Result: FAIL
```
Shouldn't this be a WARN at most? Or a PASS/INFO? It is not technically an error, but a legacy exception.

**Comment by felipesanches** [comment]
Could you please send me a copy of your Ubuntu-Medium.ttf file to juca@members.fsf.org ? I'd like to test fontbakery with it to make sure the current implementation is working well.

**Comment by madig** [comment]
D'oh, nevermind, I was in the wrong branch, test passes! Sorry for the noise... The exact working of the license fields may change though, the PR is not yet merged.

**Comment by felipesanches** [comment]
ok, cool.
Make sure to send me files if you ever feel like it would be useful for me to replicate issues locally for debugging fontbakery. It sounds like we have no issue at this time, though, right?

cheers!

**Comment by madig** [comment]
Sent :)

I think you can test a lot of tests with the current GF release of Ubuntu ;)
