### ISSUE TITLE
Add parameter to exclude tests when running checks

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1683]
## Observed behaviour

FontVal floods me with errors on one particular font family that I don't want to see yet, quickly reaching the terminal's line limit.

## Expected behaviour

The presence of an inverted `-c` parameter that lets me exclude the test until I have dealt with the other errors.

## Resources and exact process needed to replicate

1. Build https://github.com/daltonmaag/ubuntu
2. `fontbakery check-googlefonts build/Ubuntu-R.ttf`

**Comment by felipesanches** [comment]
That's an insightful proposal. Thanks!

**Comment by felipesanches** [comment]
implemented in PR #1884
