### ISSUE TITLE
com.google.fonts/check/012 should list differing glyph names

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1684]
## Observed behaviour
```
>> com.google.fonts/check/012
   Fonts have equal glyph names?
 * FAIL: Fonts have different glyph names.

   Result: FAIL
```
Which ones?

## Expected behaviour

The test should tell me what exactly differs (glyphs in one but not the other fonts, names being different for the same Unicode codepoint, ...).

## Resources and exact process needed to replicate

1. Build https://github.com/daltonmaag/ubuntu
2. `fontbakery check-googlefonts -c "com.google.fonts/check/012" build/Ubuntu-*.ttf`

**Comment by felipesanches** [comment]
Thanks for reporting that, @madig

**Comment by madig** [comment]
Similarly, `com.google.fonts/check/011` should tell me which glyphs are missing, etc.

**Comment by felipesanches** [comment]
please open a separate issue for that.

**Comment by felipesanches** [comment]
![screenshot at 2018-01-18 19 24 47](https://user-images.githubusercontent.com/213676/35122256-457c0c26-fc85-11e7-8602-372a06b21a8a.png)
