### ISSUE TITLE
com.google.fonts/check/011 should list the glyphs that differ

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1685]
Analogous to https://github.com/googlefonts/fontbakery/issues/1684, com.google.fonts/check/011 should list everything that differs.

**Comment by felipesanches** [comment]
![screenshot at 2018-01-18 23 56 03](https://user-images.githubusercontent.com/213676/35131219-ec587932-fcab-11e7-9ca2-a1b1a9e22ef8.png)
