### ISSUE TITLE
Test for ink percentage to catch cases of missing hinting

### ISSUE THREAD

**Issue by sladen** [googlefonts/fontbakery#1691]
Ideally Fontbakery can detect and flag up extreme cases where the font behaves mechanically correctly, but the user sees nothing rendered.  Ideally this could be implemented as:

1. Render standard test sheet to a large raster.
2. Sum all ink (grayscale pixel values) on the raster.
3. Divide by the number of pixels (width * height), giving a percentage of ink covering.
4. _Fail_ if ink coverage is less than 1% ink coverage
5. Compare to the previously recorded value for ink coverage and _Warn_ if there is a variance of more than +/- 0.1% between the new and previous versions.

A third follow-on would compute the theoretical coverage computed from the vector outlines (mathematically integrate the area of ink coverage) with the measured ink from rasterisation with and without hinting enabled.  The amounts of variance without hinting should be very low, and the amount of variance with hinting should be relatively low.  …Running this test with multiple renderers and options will also test the rendering pipelines.

*(Background situation; a font was compiled and uploaded without its VTT hinting information, thus seemingly passing existing tests, but the output was all-empty white space with hinting enabled).*

**Comment by davelab6** [comment]
I believe this is done by https://github.com/m4rc1e/gfregression/ already

**Comment by m4rc1e** [comment]
Hey @sladen. We have something very similar as Dave mentioned. GFRegression can be used to generate before and after screenshots using https://github.com/m4rc1e/diffbrowsers to control it from the command line. It uses [BrowserStack](https://www.browserstack.com) to gen the screenshots on diff browsers

We use it for every pr we make to google/fonts. It also returns the amount of different pixel values. 

My aim is to get this hooked into Travis/CI system later this year. Whenever someone makes a pr it will include before and after images automatically.

Here are some recent examples:
https://github.com/google/fonts/pull/1385
https://github.com/google/fonts/pull/1374
https://github.com/google/fonts/pull/1355

**Comment by felipesanches** [comment]
Unless there's a desire of integrating these tools into fontbakery, I think we're good to close this issue now.
My understanding is that this may at some point get integrated into FontBakery-Dashboard, but I don't think it is necessary to deal with it on the FB-core and command-line.

**Comment by sladen** [comment]
Sounds like the `GFRegression` side might have the raster generation side sorted.  Indeed, when the logic for the testing is better handed these can be added later.  Another obvious test that might be possible (easy to do monospaces) is confirming that higher weights have higher ink percentages.
