### ISSUE TITLE
com.google.fonts/check/055 question

### ISSUE THREAD

**Issue by pathumego** [googlefonts/fontbakery#1700]
I am running the `check-googlefonts` on a font and `check/055` fails with this message.

```
 * FAIL: The NAMEID_VERSION_STRING (nameID=5) value must follow the pattern Version X.Y between 1.000 and 9.999. Current value: 2.920 [code: bad-version-strings]
```
Checked everything and looks good. Am I missing something here?

**Comment by felipesanches** [comment]
It seems that your nameid 5 (version string) lacks the "Version" prefix. The content of the version string in your font seems to be simply the version number (just a `2.920` string instead of `Version 2.920`).

**Comment by pathumego** [comment]
ha ha yes, thanks! maybe put `Version X.Y` in quotes? Could be just me :)

**Comment by felipesanches** [comment]
I agree! I also thought about the need for quotes. I'll do it.

**Comment by felipesanches** [comment]
Please, let me know if this now looks good for you

**Comment by pathumego** [comment]
Awesome! Thanks @felipesanches !
