### ISSUE TITLE
com_google_fonts_check_037:  Running FontValidator.exe on mac

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1704]
In #1336 there's a discussion on how to get FontValidator.exe to run. Unfortunately, It only focuses on Linux. 

As a mac user, I haven't found a way to run FontValidator.exe without calling `mono` in the shell. For our subprocess command we have:
```
    fval_cmd = ["FontValidator.exe",
                "-file", font,
                "-all-tables",
                "-report-in-font-dir",
                "+raster-tests"]
```

I see Linux users can use Binfmt to run .exes without calling `mono`. @felipesanches have you used this approach? if so, we'll need to update out subprocess command so it is cross platform compatible. 

I may be totally wrong with my assumptions here. Please correct me if I am.

**Comment by graphicore** [comment]
Here's what I came up with for the docker environment in Fontbakery-Dashboard, because the calling without mono did not work for me either: https://github.com/googlefonts/fontbakery-dashboard/blob/master/containers/base/python/Dockerfile#L55

```
# in Dockerfile
RUN ...
    echo "#! /bin/bash"  > /bin/FontValidator.exe; \
    echo "mono /var/fontbakery/prebuilt/fval/FontValidator.exe \$@" >> /bin/FontValidator.exe; \
    chmod +x /bin/FontValidator.exe; \
    echo 'export LD_PRELOAD=/var/fontbakery/prebuilt/custom_freetype/lib/libfreetype.so' >> ~/.bashrc;
```

maybe it helps.

**Comment by m4rc1e** [comment]
@graphicore thanks!

I think I'll find a cross platform solution for this and pr.

cc @felipesanches

**Comment by HinTak** [comment]
Or just use the provided all-in-one mac and Linux binaries.
https://github.com/HinTak/Font-Validator/releases/tag/FontVal-2.1.1-py

FWIW, as long as a hostile fork exists, the source code of the backend will not be posted. So using a hostile fork is one way of making sure that you will not see the code.

**Comment by anthrotype** [comment]
"hostile" what?!

**Comment by HinTak** [comment]
A fork that (1) does not contribute to upstream, (2) intentionally incompatible, is called a hostile fork. You are aware that your fork intentionally breaks the freetype-py client also?

**Comment by HinTak** [comment]
If you are going to use LD_PRELOAD, you might as well use these.

https://github.com/HinTak/Font-Validator/tree/master/bin/ubuntu-14.04-x64
https://github.com/HinTak/Font-Validator/tree/master/bin/ubuntu-16.04-x64
https://github.com/HinTak/Font-Validator/tree/master/bin/Darwin

Note you may need to check out the slightly older version of the backends. The communication between the backend and front end has changed slightly lately - migrating towards thread-safeness, etc.

**Comment by anthrotype** [comment]
huh. whose fork of what?

**Comment by m4rc1e** [comment]
Thank you all for reminding me I need to haul ass on this one.

**Comment by HinTak** [comment]
If you just use the provided mac binary (and the Linux binary also), you don't need to worry about mono, and you do not need to fiddle with LD_PRELOAD with your own hostile fork. It is just a single binary. Nothing else.

The 5 binary freetype backends (for 7 architectures - win32/win64, intel mac 32-bit/64-bit, ppc mac 32-bit, unbuntu 14.04.x64 and 16.04.x64 - the mac is a biarch/triarch) are posted mostly just to remind myself, what exactly did I include in the all-in-one binaries. For as long as the hostile fork exists, you will not see its source.

**Comment by davelab6** [comment]
If Felipe deletes all traces of his fork, you will publish compete corresponding sources?

**Comment by HinTak** [comment]
Felipe started a bad trend and will only be the first of many people who tries to disrupt and destroy the work, unfortunately. There will be more such people to come.
 
I'd say for as long as it is mostly my work, I do not need to show the code. In the spirit of co-operation, I would say the person(s) who can see the backend code patch , which currently has a size of 100k and line count of about 3000 , is somebody who has contributed an equivalent amount of work to the rest of FontVal. There are plenty to do - the last time I counted there are about 50 open issues. And it should be quite easy if adding checks for the newer tables is considered.

People who had contributed nothing positive so far? I don't need to hear what they want. It is irrelevant.

**Comment by davelab6** [comment]
Felipe wants to contribute. I want to direct people to contribute. But if no one can see the complete current codebase, how can they contribute to the open issues? They can't, and they won't. No one is going to contribute to an open source project where source code isn't available. Simple as that.

**Comment by HinTak** [comment]
Felipe has not contributed anything positive so far. Still waiting. If you are not contributing positively, what you want to do is irrelevant.

**Comment by anthrotype** [comment]
I wasn't aware Felipe maintained a fork of fontval. But the tone of your previous remarks ("hostile", "bad", "disrupt and destroy", "nothing positive", "irrelevant", etc.) doesn't seem quite welcoming for new contributions.

**Comment by HinTak** [comment]
My response is exactly what is expected towards people trying destroy a few years of work. I call the hostile action what it is, it is hostile.

As for the earlier argument - I did not see the complete original Fontval code either. Microsoft did not release their backend code . You can tell me not to work on Fontval 3 years ago with exact same argument. Dave, you probably should have. If you apply the same argument 3 years ago, it would save us all a lot of pain.

**Comment by HinTak** [comment]
I shall update the FAQ https://github.com/HinTak/Font-Validator/wiki/FAQ , regarding "hostile fork", and quoting Dave's coment above and my response. In particular, here are 3 reasons at least that the backend code will not be released:

- the backend code will not be released as long as any hostile fork exists.

- the backend code will not be released until it is tested safe to function patching against Linux's system-wide FreeType. (currently scheduled for 2019 spring/summer in the Fedora 29 time frame). It will be a private testing only, and you'll need to first convince me to risk and sacrify my own box's stability.

- the backend code will not be released until FontVal is not my personal project. That, specifically means, that the sum total of community code contribution to the C# part exceeds my own. The backend code is currently just over 100k with a line count of about 3000 . So try contributing 3000 lines of C# code, before that trying to argue on that.

These are the 3 reasons at least. If I think of a 4th, etc, I'll add to the list. These conditions will not be removed.

Please also read the "negative contribution" entry in the FAQ. It was written specifically as a consequence of Felipe's behavior last summer.

**Comment by m4rc1e** [comment]
closing as we've solved this.
