### ISSUE TITLE
Which fonts family does Google Home App uses (Each and every font family)

### ISSUE THREAD

**Issue by ayan-das1234** [googlefonts/fontbakery#1706]
Which fonts family does Google Home App uses (Each and every font family)

**Comment by felipesanches** [comment]
I think that perhaps @davelab6 could help to answer your question. But this does not seem to be related to FontBakery at all, so I'll close this issue.

**Comment by ayan-das1234** [comment]
@davelab6 Which fonts family does Google Home App uses (Each and every font family)
