### ISSUE TITLE
check-googlefonts fails to output json file

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1709]
If you use fontbakery from the cli with the optional json param

```
fontbakery check-googlefonts Font-Regular.ttf --json foo.json
```

FB produces the following traceback.

```
Traceback (most recent call last):
  File "/Users/marc/Documents/googlefonts/fontbakery/bin/fontbakery-check-googlefonts.py", line 7, in <module>
    main()
  File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/commands/check_spec.py", line 210, in main
    json.dump(sr.getdoc(), args.json, sort_keys=True, indent=4)
  File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/reporters/serialize.py", line 147, in getdoc
    sectionDoc['checks'].append(check)
KeyError: u'checks'
```

pretty sure the key is mean't to be 'check' and not 'checks'. Will file a pr.

**Comment by felipesanches** [comment]
the other way around. It seems much more reasonable to keep it called "checks" because the following makes a lot of sense:

```
sectionDoc['checks'].append(check)
```

... meaning "append yet another check to the current list of checks of this sectionDoc"

**Comment by graphicore** [comment]
I was just saying the same thing. It seems like line 80 should be changed:

https://github.com/googlefonts/fontbakery/blob/c49313564d005c38f5497d9fd63262a9784303b9/Lib/fontbakery/reporters/serialize.py#L79-L80

From:

```py
      if status in (STARTSECTION, ENDSECTION):
        item.update(dict(key=key, result=None, check=[]))
```

To:

```py
      if status in (STARTSECTION, ENDSECTION):
        item.update(dict(key=key, result=None, checks=[]))
```

**Comment by m4rc1e** [comment]
Done
