### ISSUE TITLE
Fix test_check_154 and re-enable it.

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1712]
https://travis-ci.org/googlefonts/fontbakery/builds/341518696

**Comment by m4rc1e** [comment]
Strangely, it passes for me.

When I run pytest for this particular test, I get the following.

```
pytest Lib/fontbakery/specifications/googlefonts_test.py::test_check_154
============================= test session starts ==============================
platform darwin -- Python 2.7.10, pytest-3.1.3, py-1.4.34, pluggy-0.4.0
rootdir: /Users/marc/Documents/googlefonts/fontbakery, inifile:
collected 1 item

Lib/fontbakery/specifications/googlefonts_test.py .

=========================== 1 passed in 1.13 seconds ===========================
(env)Marc:fontbakery marc$
```

**Comment by felipesanches** [comment]
there's something going bad when running on Travis though...

**Comment by felipesanches** [comment]
```
Lib/fontbakery/specifications/googlefonts_test.py:2057: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ttFont = <fontTools.ttLib.ttFont.TTFont object at 0x7f0c4930e510>
api_gfonts_ttFont = None
    @register_check
    @check(
        id = 'com.google.fonts/check/154'
      , conditions=['api_gfonts_ttFont']
    )
    def com_google_fonts_check_154(ttFont, api_gfonts_ttFont):
      """Check font has same encoded glyphs as version hosted on
      fonts.google.com"""
      cmap = ttFont['cmap'].getcmap(3, 1).cmap
>     gf_cmap = api_gfonts_ttFont['cmap'].getcmap(3, 1).cmap
E     TypeError: 'NoneType' object has no attribute '__getitem__'
Lib/fontbakery/specifications/googlefonts.py:4656: TypeError
```

**Comment by m4rc1e** [comment]
Is that output from your machine or Travis?

I have a hunch it may have failed because the request to dl the fonts failed.

**Comment by felipesanches** [comment]
That's output form Travis as can be seen at https://travis-ci.org/googlefonts/fontbakery/builds/341518696

**Comment by m4rc1e** [comment]
Now passes Travis https://travis-ci.org/googlefonts/fontbakery

I'm 90% sure its the network request in the unit test which is causing this. We should find a way to mock it

**Comment by felipesanches** [comment]
it now passes because I commented it out in order to focus on other issues:

https://github.com/googlefonts/fontbakery/commit/1e198ef2ddd46a788c09b7651e9674eafc9cb747

**Comment by felipesanches** [comment]
This still needs to be fixed, though.

Also, I do no think this is related to connectivity issues. Because it crashes at:

```
 gf_cmap = api_gfonts_ttFont['cmap'].getcmap(3, 1).cmap
```

which is in the body of the check codeblock. This means the `api_gfonts_ttFont` condition should be `"True-ish"`, making me believe that it was able to properly load the remote font file. It may be crashing for some other reason...

**Comment by m4rc1e** [comment]
> Also, I do no think this is related to connectivity issues. Because it crashes at:
> gf_cmap = api_gfonts_ttFont['cmap'].getcmap(3, 1).cmap

That's because it has returned a Nonetype. It completely failed to download the fonts.

**Comment by m4rc1e** [comment]
I'll keep looking into this

**Comment by felipesanches** [comment]
This in not breaking travis anymore.

**Comment by felipesanches** [comment]
Travis does not fail simply because the test is disabled. But we need to fix the test and reenable it.
