### ISSUE TITLE
check 'wght' axis values match every TTF instance's OS/2 usWeightClass value

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1716]
@m4rc1e said at #1713:

We need a further test to determine whether axis values are mapped correctly. How about we check the wght axis vals match every ttf instance's OS/2 usWeightClass value?

I recently PR'd [Marakazi Text](https://github.com/google/fonts/pull/1448). It has four ttfs. For the variable font,  its fvar table aligns with the ttf instances.

```
  <fvar>

    <!-- Weight -->
    <Axis>
      <AxisTag>wght</AxisTag>
      <Flags>0x0</Flags>
      <MinValue>400.0</MinValue>
      <DefaultValue>400.0</DefaultValue>
      <MaxValue>700.0</MaxValue>
      <AxisNameID>256</AxisNameID>
    </Axis>

    <!-- Regular -->
    <NamedInstance flags="0x0" subfamilyNameID="257">
      <coord axis="wght" value="400.0"/>
    </NamedInstance>

    <!-- Medium -->
    <NamedInstance flags="0x0" subfamilyNameID="258">
      <coord axis="wght" value="491.66666"/>
    </NamedInstance>

    <!-- SemiBold -->
    <NamedInstance flags="0x0" subfamilyNameID="259">
      <coord axis="wght" value="608.33333"/>
    </NamedInstance>

    <!-- Bold -->
    <NamedInstance flags="0x0" subfamilyNameID="260">
      <coord axis="wght" value="700.0"/>
    </NamedInstance>
  </fvar>
```

By making sure the [fvar](https://docs.microsoft.com/en-gb/typography/opentype/spec/fvar) axises match the individual ttfs usWeightClass, we could in theory drop the individual ttfs, once browser support for variable fonts is better. 

I really think we should spend more time on making meaningful tests for VF fonts. I understand you have other priorities at the moment but we should get this right the first time.

**Comment by m4rc1e** [comment]
@felipesanches Thank you for adding this!

I've done some more reading. Can I edit your comment?

**Comment by felipesanches** [comment]
> Can I edit the title and post?

Sure!

**Comment by m4rc1e** [comment]
@davelab6 you're right and its why I want to update the post.

@felipesanches thanks!

**Comment by felipesanches** [comment]
closing this, as the conversation migrated to #1920
