### ISSUE TITLE
com.google.fonts/check/018: Why does VendorID need to match name ID 8 (Manufacturer)

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1717]
According to the Ms spec:

> This is not the royalty owner of the original artwork. This is the company responsible for the marketing and distribution of the typeface that is being classified. 

https://docs.microsoft.com/en-gb/typography/opentype/spec/os2#achvendid

In a lot of cases, the vendor and manufacturer are not the same e.g for IBM Plex the manufacturer is Bold Monday and the Vendor is IBM.

Imo, I think we can drop this test. It is testing an assumption which may not always be true.

**Comment by davelab6** [comment]
Agree, they don't need to match

**Comment by davelab6** [comment]
The vendor and manufacturer don't need to be the same, so it can be dropped
