### ISSUE TITLE
FB errors on recent PR

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1722]
## Observed behaviour

https://github.com/googlefonts/francoisoneFont/pull/1 reports 1 FAIL and 4 errors. 

## Expected behaviour

That should be a clean run. 

## Resources and exact process needed to replicate

@m4rc1e please advise on how you would like FB to be improved to not error like that

**Comment by m4rc1e** [comment]
Here's a summary of the errors:

```
com.google.fonts/check/037 with ((u'font[0]', '/Users/marc/Documents/googlefonts/manual_font_cleaning/francoisone/fonts/FrancoisOne-Regular.ttf'),)
   Checking with Microsoft Font Validator.
```

Related to #1704, I will fix this today.

```

>> com.google.fonts/check/065 with ((u'font[0]', '/Users/marc/Documents/googlefonts/manual_font_cleaning/francoisone/fonts/FrancoisOne-Regular.ttf'),)
   Is there kerning info for non-ligated sequences?
 * ERROR: Failed with KeyError: 'f'
```

Genuine error. @felipesanches could you try and tackle this? 

repo for fonts is https://github.com/googlefonts/francoisoneFont

```
>> com.google.fonts/check/117 with ((u'font[0]', '/Users/marc/Documents/googlefonts/manual_font_cleaning/francoisone/fonts/FrancoisOne-Regular.ttf'),)
   Version number has increased since previous release on Google Fonts?
 * ERROR: The condition <FontBakeryCondition:github_gfonts_ttFont> had an error: KeyError: None
         Traceback (most recent call last):
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/checkrunner.py", line 383, in _evaluate_condition
             return None, condition(**args)
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/callable.py", line 78, in __call__
             return self._func(*args, **kwds)
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 4260, in github_gfonts_ttFont
             "/{}/{}/{}").format(LICENSE_DIRECTORY[license],
         KeyError: None


   Result: ERROR

>> com.google.fonts/check/166 with ((u'font[0]', '/Users/marc/Documents/googlefonts/manual_font_cleaning/francoisone/fonts/FrancoisOne-Regular.ttf'),)
   Check for font-v versioning
 * ERROR: Failed with AttributeError: 'FontVersion' object has no attribute 'get_name_id5_version_string'
         Traceback (most recent call last):
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/checkrunner.py", line 307, in _exec_check_generator
             for sub_result in gen:
           File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/specifications/googlefonts.py", line 5172, in com_google_fonts_check_166
             "").format(fv.get_name_id5_version_string())
         AttributeError: 'FontVersion' object has no attribute 'get_name_id5_version_string'


   Result: ERROR
```

These two errors occur when a license file is not in the same dir as the fonts. Currently, these tests need a license file to download the fonts from GF. We should refactor this so a license file isn't needed

**Comment by felipesanches** [comment]
@m4rc1e your **check/166** output said:
'''
'FontVersion' object has no attribute 'get_name_id5_version_string'
'''

Please consider upgrading your fontv package using pip. This same check worked nicely for me here with the same FrancoisOne font repo.

**Comment by felipesanches** [comment]
OK. I fixed most of the issues. The remaining, as described above, seems to be on @m4rc1e 's plate now :-)

Let me know @m4rc1e if you need any further help from me here. :-D

**Comment by davelab6** [comment]
Can we have some nicer dependency checking so that when dependencies are
stale, we tell the user that they should upgrade.

**Comment by felipesanches** [comment]
Here's an updated fb-report using the latest fontbakery 0.4.0 and FrancoiseOne from google/fonts master:

## Fontbakery report

<details>
<summary><b>[7] FrancoisOne-Regular.ttf</b></summary>
<details>
<summary>:broken_heart: <b>ERROR:</b> Checking with ftxvalidator.</summary>

* [com.google.fonts/check/035](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/035)
* **ERROR** [:broken_heart:] ftxvalidator is not available!

</details>
<details>
<summary>:fire: <b>FAIL:</b> Copyright notice on METADATA.pb matches canonical pattern?</summary>

* [com.google.fonts/check/102](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/102)
* **FAIL** [:fire:] METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2011 The Francois One Project Authors (contact@sansoxygen.com)'

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking with Microsoft Font Validator.</summary>

* [com.google.fonts/check/037](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/037)
* **FAIL** [:fire:] MS-FonVal: The xAvgCharWidth field does not equal the calculated value DETAILS: actual = 505, calc = 418
* **FAIL** [:fire:] MS-FonVal: There are undefined bits set in fsSelection field DETAILS: Bit(s) 7
* **WARN** [:warning:] MS-FonVal: Recommended table is missing DETAILS: kern
* **WARN** [:warning:] MS-FonVal: Recommended table is missing DETAILS: hdmx
* **WARN** [:warning:] MS-FonVal: Recommended table is missing DETAILS: VDMX
* **WARN** [:warning:] MS-FonVal: Tables are not in optimal order DETAILS: table 'OS/2' precedes table 'head'
* **WARN** [:warning:] MS-FonVal: The version number is valid, but less than 5 DETAILS: 4
* **WARN** [:warning:] MS-FonVal: The value of sTypoAscender minus sTypoDescender is greater than unitsPerEm DETAILS: sTypoAscender = 1089, sTypoDescender = -329
* **WARN** [:warning:] MS-FonVal: A CodePage bit is set in ulCodePageRange, but the font is missing some of the printable characters from that codepage DETAILS: bit #29, Mac character set (missing chars: U221E U2202 U2211 U220F U03C0 U222B U2126 U221A U2206 U25CA)
* **WARN** [:warning:] MS-FonVal: Intersecting components of composite glyph DETAILS: Glyph index 297
* **WARN** [:warning:] MS-FonVal: fontRevision is not consistent with the font's version string DETAILS: revision: 2,000, version: 2.000
* **WARN** [:warning:] MS-FonVal: The unitsPerEm value is not a power of two DETAILS: 1000
* **WARN** [:warning:] MS-FonVal: Ascender is different than OS/2.usWinAscent. Different line heights on Windows and Apple DETAILS: hhea.Ascender = 1089, OS/2.usWinAscent = 1351
* **WARN** [:warning:] MS-FonVal: Descender is different than OS/2.usWinDescent. Different line heights on Windows and Apple DETAILS: hhea.Descender = -329, OS/2.usWinDescent = 332
* **WARN** [:warning:] MS-FonVal: The LineGap value is less than the recommended value DETAILS: LineGap = 0, recommended = 265
* **WARN** [:warning:] MS-FonVal: Loca references a glyf entry which length is not a multiple of 4 DETAILS: Number of glyphs with the warning = 1
* **WARN** [:warning:] MS-FonVal: maxSizeOfInstructions computation not via either approved method DETAILS: glyf maxSizeOfInstructions=312, prep size=152, fpgm size=3350, whereas maxp maxSizeOfInstruction is 3350

</details>
<details>
<summary>:warning: <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/018](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/018)
* **WARN** [:warning:] OS/2 VendorID value 'newt' is not a known registered id. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: unknown]

</details>
<details>
<summary>:warning: <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/153](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/153)
* **WARN** [:warning:] This check inspects the glyph outlines and detects the total number of counters in each of them. The expected values are infered from the typical ammounts of counters observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: aring	Counters detected: 3	Expected: 4
Glyph name: ldot	Counters detected: 1	Expected: 2
Glyph name: notequal	Counters detected: 2	Expected: 1
Glyph name: uni1EB7	Counters detected: 3	Expected: 4

</details>
<details>
<summary>:warning: <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/065](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/065)
* **WARN** [:warning:] GPOS table lacks kerning info for the following non-ligated sequences: [u'N_o', u'three_slash', u'f_f', u'f_i', u'f_l', u'one_slash'] [code: lacks-kern-info]

</details>
<details>
<summary>:warning: <b>WARN:</b> Is there a caret position declared for every ligature?</summary>

* [com.google.fonts/check/064](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/064)
* **WARN** [:warning:] It seems that this font lacks caret positioning values for some of its ligature glyphs on the GDEF table. There's a total of 4 ligatures, but only 2 sets of caret positioning values. [code: incomplete-caret-pos-data]

</details>
<br>
</details>

### Summary

| :broken_heart: ERROR | :fire: FAIL | :warning: WARN | :zzz: SKIP | :information_source: INFO | :croissant: PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 1 | 2 | 4 | 15 | 5 | 105 |
| 1% | 2% | 3% | 11% | 4% | 80% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**

**Comment by felipesanches** [comment]
I think only this one is a font problem that still remains and was reported when this issue was opened:

![screenshot at 2018-05-17 02 45 53](https://user-images.githubusercontent.com/213676/40158754-b519cdf8-5995-11e8-8c77-305b45e34636.png)

All the actual fontbakery bugs discussed here were already fixed. So I'm closing this.
