### ISSUE TITLE
[Variable Fonts] Check fonttools.varLib.mutator can generate a static instance from a variable font

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1727]
This test is needed because the GF Team want to generate font instances from variable fonts.

One of our variable test fonts, MarkaziText-VF.ttf (will email it to you @felipesanches ), failed in mutator with the following cli input

```
$./fonttools varLib.mutator MarkaziText-VF.ttf wght=500
```

Which produced the following traceback
```
Location: {'wght': 500.0}
Loading variable font
Normalized location: {'wght': 0.33331298828125}
Mutating glyf/gvar tables
Mutating GDEF/GPOS/GSUB tables
Building interpolated tables
Removing variable tables
Saving instance font MarkaziText-VF-instance.ttf
ERROR: Glyph 'uni0615' has negative advance width
ERROR: Glyph 'uniFBB4' has negative advance width
ERROR: Glyph 'uni0655' has negative advance width
Traceback (most recent call last):
  File "./fonttools", line 12, in <module>
    sys.exit(main())
  File "/usr/local/google/home/nyshadhr/src/fonttools/Lib/fontTools/__main__.py", line 29, in main
    runpy.run_module(mod, run_name='__main__')
  File "/usr/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/google/home/nyshadhr/src/fonttools/Lib/fontTools/varLib/mutator.py", line 156, in <module>
    sys.exit(main())
  File "/usr/local/google/home/nyshadhr/src/fonttools/Lib/fontTools/varLib/mutator.py", line 150, in main
    varfont.save(outfile)
  File "/usr/local/google/home/nyshadhr/src/fonttools/Lib/fontTools/ttLib/ttFont.py", line 166, in save
    writer_reordersTables = self._save(tmp)
  File "/usr/local/google/home/nyshadhr/src/fonttools/Lib/fontTools/ttLib/ttFont.py", line 205, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/usr/local/google/home/nyshadhr/src/fonttools/Lib/fontTools/ttLib/ttFont.py", line 615, in _writeTable
    self._writeTable(masterTable, writer, done, tableCache)
  File "/usr/local/google/home/nyshadhr/src/fonttools/Lib/fontTools/ttLib/ttFont.py", line 619, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/google/home/nyshadhr/src/fonttools/Lib/fontTools/ttLib/ttFont.py", line 637, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/google/home/nyshadhr/src/fonttools/Lib/fontTools/ttLib/tables/_h_m_t_x.py", line 96, in compile
    % (self.tableTag, self.advanceName))
fontTools.ttLib.TTLibError: 'hmtx' table can't contain negative advance widths
```
More info in the following fonttools pr https://github.com/fonttools/fonttools/pull/1198

cc @nyshadhr9

**Comment by felipesanches** [comment]
```
ERROR: Glyph 'uni0615' has negative advance width
ERROR: Glyph 'uniFBB4' has negative advance width
ERROR: Glyph 'uni0655' has negative advance width
```

We do have a check for that. It was added last week:
https://github.com/googlefonts/fontbakery/blob/97de5a3802789a98ed4b5ceb9c2c26e646ddc84f/Lib/fontbakery/specifications/googlefonts.py#L5401-L5421

**Comment by m4rc1e** [comment]
@felipesanches The font does have positive hmtx values. This issue relates to the deltas in the gvar table.

**Comment by anthrotype** [comment]
that check is spurious.. If you're reading a TTFont from a file, it can't _never_ have negative advances in hmtx, because the field will always be decompiled as an `uint16` (*unsigned* short integer), even if it's huge e.g. 0xFFFF.

The error Marc is getting is while attempting to instantiate a variable font that was originally produced with Glyphs.app, in which some glyphs that are supposed to have 0 advance width (being classified as non-spacing combining marks) end up with `gvar` "phantom" points (for the left, right, top, bottom side bearning) that are messed up (e.g. the right one has a smaller x coordinate than the left). That's because in the source file those glyphs have some non-zero advance widths (it's a common trick designers use to be able to preview those glyphs in the editor), however Glyphs.app was not automatically setting them to 0 upon exporting a variable font, in the same way it does when exporting a non-variable instance font.
Georg said he's fixed the bug.

**Comment by anthrotype** [comment]
> while attempting to instantiate a variable font

I mean, using `fonttools varLib.mutator MyFont-VF.ttf wght=700 wdth=85`

**Comment by davelab6** [comment]
@m4rc1e do you want to take care of this?

**Comment by m4rc1e** [comment]
Sure!

**Comment by anthrotype** [comment]
note that this has already been fixed in fonttools (since 3.24.0)
https://github.com/fonttools/fonttools/pull/1198
https://github.com/fonttools/fonttools/commit/ad7b97a7b295b8ab6df1937d73167ff535155248

**Comment by m4rc1e** [comment]
@anthrotype Thanks! I remember this pr :-).

I'd still like to determine whether this test is actually useful. There may be other issues which stop an instance being genned from mutator that I don't know about.

**Comment by anthrotype** [comment]
could you send me again the font that was failing (i.e. before Georg and the two of us fixed it respectively in Glyphs.app and fonttools)? I'd like to take another look as well, thanks.

**Comment by m4rc1e** [comment]
Here you go [MarkaziVFs.zip](https://github.com/googlefonts/fontbakery/files/1830757/MarkaziVFs.zip)

Since GF may use mutator in the future to gen instances, I'd like to dump a load of VF's through the new fonttools and see any other unforeseen issues come up. We're a bit too light on tests for VFs atm.

**Comment by anthrotype** [comment]
Thanks Marc. One is never too heavy on tests ;)

**Comment by anthrotype** [comment]
Comparing the "broken" and the "fixed" fonts that you sent me, I see that in the broken one there are some glyphs in the gvar, for which the last four tuples -- which identify the left, right, top and bottom "phantom points" -- have a problem: the right's x coordinate is smaller than the left's x coodinate, hence the negative horizontal advance width computed by mutator (and the subsequent failure when compiling the hmtx).

```diff
--- /home/clupo/Downloads/MarkaziText-VF-broken.ttx
+++ /home/clupo/Downloads/MarkaziText-VF-fixed.ttx
@@ -1248,12 +1248,12 @@
     <!-- Most of this table will be recalculated by the compiler -->
     <tableVersion value="1.0"/>
     <fontRevision value="1.0"/>
-    <checkSumAdjustment value="0x767e98da"/>
+    <checkSumAdjustment value="0x5bf1d08c"/>
     <magicNumber value="0x5f0f3cf5"/>
     <flags value="00000000 00000011"/>
     <unitsPerEm value="2048"/>
     <created value="Thu Mar  9 22:12:49 2017"/>
-    <modified value="Tue Feb 13 09:01:00 2018"/>
+    <modified value="Mon Feb 26 11:39:27 2018"/>
     <xMin value="-341"/>
     <yMin value="-893"/>
     <xMax value="2485"/>
@@ -112145,7 +112145,7 @@
         <delta pt="38" x="-5" y="1"/>
         <delta pt="39" x="-5" y="1"/>
         <delta pt="40" x="0" y="0"/>
-        <delta pt="41" x="-6" y="0"/>
+        <delta pt="41" x="0" y="0"/>
         <delta pt="42" x="0" y="0"/>
         <delta pt="43" x="0" y="0"/>
       </tuple>
@@ -112189,7 +112189,7 @@
         <delta pt="0" x="19" y="-36"/>
         <delta pt="1" x="-32" y="-36"/>
         <delta pt="2" x="0" y="0"/>
-        <delta pt="3" x="-24" y="0"/>
+        <delta pt="3" x="0" y="0"/>
         <delta pt="4" x="0" y="0"/>
         <delta pt="5" x="0" y="0"/>
       </tuple>
@@ -112368,7 +112368,7 @@
         <coord axis="wght" value="1.0"/>
         <delta pt="0" x="11" y="-25"/>
         <delta pt="1" x="0" y="0"/>
-        <delta pt="2" x="-39" y="0"/>
+        <delta pt="2" x="0" y="0"/>
         <delta pt="3" x="0" y="0"/>
         <delta pt="4" x="0" y="0"/>
       </tuple>
```

You could to check that in each gvar tuple the last four deltas for the phantom points are such that you don't get rightSideX < leftSideX

**Comment by anthrotype** [comment]
Basically this means you’d do the same computation that mutator does to compute a glyph’s coordinates (including the last four phantom points) at a specific location.. for a transient bug that has been fixed in Glyphs.app by now.

**Comment by felipesanches** [comment]
That's what people call regression testing. To make sure it never creeps up back again unnoticed ;-)

**Comment by m4rc1e** [comment]
Closing test added in #1755

**Comment by simoncozens** [comment]
I'm wondering how useful this check is in 2025. For one thing, it tests whether or not `fonttools varLib.mutator` works, not whether or not a font works. For another, we don't even *use* `fonttools varLib.mutator` to serve statics any more. I'm inclined not to carry it over to fontspector unless someone can come up with a good reason.
