### ISSUE TITLE
Deprecate check/082: "Designer exists in Google Fonts profiles.csv?"

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1728]
According to https://github.com/google/fonts/pull/1465 (merged today), profiles.csv is not used anymore by the Google Fonts project. So this means that FB **check/082** should probably be deprecated:

https://github.com/googlefonts/fontbakery/blob/3e8988c421f782b8a6c982358f2104a24fba17fb/Lib/fontbakery/specifications/googlefonts.py#L3178-L3213

**Comment by davelab6** [comment]
Yes; you could comment it out though as there's a new designer profiles/bio
section coming soon :)
