### ISSUE TITLE
Code style does not conform to Google Python style

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1734]
## Observed behaviour

Using yapf to automatically format source code with `--style '{based_on_style: google}'` results in massive changes across all Python files in the project.

## Expected behaviour

BRIEF.md states that "For Python code style, we conform to Google Python Style Guide".

## Resources and exact process needed to replicate

`yapf -i --style '{based_on_style: google}' **/*.py`
`docformatter -i **/*.py`

Do you accept massive PRs with style changes? ;)

**Comment by felipesanches** [comment]
> Do you accept massive PRs with style changes? ;)

No ;-)

See also:  #838

**Comment by felipesanches** [comment]
But I would naturally accept removing the "Google Python Style Guide" sentence from that markdown file
