### ISSUE TITLE
Depend on ttfautohint-py instead of actual ttfautohint

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1737]
## Observed behaviour

ttfautohint needs to be installed externally. Groan.

## Expected behaviour

Use ttfautohint-py instead to let pip handle it. Less hassle.

## Resources and exact process needed to replicate

https://github.com/fonttools/ttfautohint-py
`pip install ttfautohint-py`

**Comment by felipesanches** [comment]
this will be done at #1972
