### ISSUE TITLE
Extending checks for all/more OpenType fields?

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1742]
We test font files for conformance to defined OpenType fields, e.g. the preferred family name of something.ttf should be "Something Something". Ideally, this can access tables like the `cvt ` so we can enforce certain values across the family. Would that be something within the scope of the project?

(I saw that @m4rc1e has something in that direction: https://github.com/m4rc1e/mf-glyphs-scripts/tree/master/QA)

**Comment by davelab6** [comment]
METADATA files are just a cache of TTF values, so checks like that are
welcome but the source of truth is the check code itself, not the METADATA
file.

**Comment by davelab6** [comment]
>  We test font files for conformance to defined OpenType fields, e.g. the preferred family name of something.ttf should be "Something Something". Ideally, this can access tables like the `cvt ` so we can enforce certain values across the family. Would that be something within the scope of the project?

Yes, checks  for things like  `cvt `  tables or  other tables that should  have consistent values  across files in a family are firmly  within scope. 

I'm assigning to you so that you can tell us what values you think should  be uniform.

**Comment by felipesanches** [comment]
I'll remove the reference to METADATA.pb from the title of the issue, as it is confusing/unrelated.

**Comment by felipesanches** [comment]
@madig, could you tell us a bit more about your proposed new checks?

**Comment by madig** [comment]
There are no proposed checks yet. The values I referred to are saved in a company database and would be downloaded and cross checked by a custom check. I haven't gotten around to implementing any of this yet...

**Comment by felipesanches** [comment]
ok, cool.
It seems there's nothing else to do in this issue.
Feel free to reopen it (or create a new one) when you have suggestions for new checks.
