### ISSUE TITLE
FontValidator test: HTML report apparently doesn't exist 

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1747]
## Observed behaviour

Running `pytest Lib` with an Hin-Tak's latest upstream FontVal in the path fails with
```
      os.remove("{}.report.xml".format(font))
>     os.remove("{}.report.html".format(font))
E     WindowsError: [Error 2] The system cannot find the file specified: u'data/test/mada/Mada-Regular.ttf.report.html'

Lib\fontbakery\specifications\googlefonts.py:1274: WindowsError
```

Can't test with the packaged FontVal because it crashes somewhere... but the test funnily enough fails in the same spot.

## Expected behaviour

Test should pass.

Change test to check for existence of file first?

**Comment by madig** [comment]
Fixed in https://github.com/googlefonts/fontbakery/pull/1748

**Comment by HinTak** [comment]
There are two possibilities. The generation of html is actually a workaround as non-MS browser does not allow rendering xml with associated xsl directly. AFAIK only MS IE does - firefox and webkit directives (i.e. Safari) won't. So on non-windows platforms, FontVal internally merges the two and generates an html. It looks like you are running on windows.

The other possibilities is that the html generation (on non-windows platforms) has gone wrong. This is also possible if some of the fields such as font name or copyright notices have strange non-ascii characters.

If it is the latter case, please send me the test font file.

**Comment by madig** [comment]
I am running on Windows -- so my check in #1748 is correct? (see if file exists and if so, remove it)

The test font is fontbakery's `data/test/mada/Mada-Regular.ttf`.

**Comment by HinTak** [comment]
Your change would do. Although, as I said above, there are really two possibilities if *.html does not exist. The first possibility is working as desired and not an error, while the 2nd one is something to worry about, so I'd suggest you do something like this to properly tell the two possibilities apart:

```
if os != windows :
    os.remove("{}.report.html".format(font)) 
```

**Comment by madig** [comment]
Hm. A HTML report does not seem to be generated at all:
```
      if sys.platform != "win32":  # A HTML report is produced only on non-Windows
>       os.remove("{}.report.html".format(font))
E       OSError: [Errno 2] No such file or directory: 'data/test/mada/Mada-Regular.ttf.report.html'
```
This passes on Windows but fails on Linux. I'm using `Windows.FontVal-2.1.0-py-bin-net4-x86.zip`.

**Comment by felipesanches** [comment]
@madig are you still having any trouble with this? If so, then reopen the issue, please.
