### ISSUE TITLE
Create a tag-test-deploy workflow for releases

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1751]
## Observed behaviour

Releases have to be done by hand. Eww, hands.

## Expected behaviour

The release manager tags a commit he wants to release and the CI/CD service (Travis) tests the code and deploys a source ball to PyPI.

To make things easier, the [setuptools_scm](https://github.com/pypa/setuptools_scm#setuppy-usage) package is used to determine the version from a Git tag automatically, so you don't have to change any number anywhere else (so much easier!).

## Resources and exact process needed to replicate

I'd point to https://github.com/fonttools/ttfautohint-py/blob/master/.travis.yml for an example, but that one is a bit complicated due to building a special binary wheel. I think you get the idea from the last `deploy:` thing though.

**Comment by anthrotype** [comment]
that's a great idea! 👍 

I once tried to add it to fonttools, but there was some resistance from other maintainers who wanted to ["keep it simple"](https://github.com/fonttools/fonttools/pull/648#issuecomment-239884715). I somehow failed to convince them the release task would actually become simpler and I could do a release from my phone while waiting for the bus. We ended up using the [bump2version](https://github.com/c4urself/bump2version) script, called with a custom-made `setup.py release` command, which I then copy-pasted to the other the font-related projects of ours.

I still like to use setuptools_scm whenever I can (e.g. when I start a new project).
Here's another example:
https://github.com/typemytype/booleanOperations/blob/6cda8215bcb549ae1e73a14ca068f89560d29452/setup.py#L14

**Comment by anthrotype** [comment]
yes, it works but only as long as the package has been properly installed alongside its metadata files (which is where the version string is actually stored upon installation), and by properly I mean with a compliant installer like pip or setuptools.
Retrieving `my_package.__version__` requires one has `pkg_resources` installed, which is part of setuptools, which in turn is almost always present in all modern python distributions (being itself a requirement for pip).

The "degenerate" case is when a developer expects that a python package just works by cloning a repo, symlinking a script or exporting a PYTHONPATH, without even bothering to do a minimal `python setup.py egg_info` that generates the required metadata files. Or when one copies the content of a git repository to the resource folder of one's standalone native app, without also copying the metadata files that accompany the packages, making it impossible to retrieve the version string.

**Comment by madig** [comment]
Good to know. Let's not care about that case until someone complains about it :)

**Comment by anthrotype** [comment]
see e.g. https://github.com/fonttools/ttfautohint-py/blob/master/src/python/ttfautohint/_version.py

where i basically simply report a deliberately incorrect version string "0.0.0" when the package was not correctly installed

**Comment by madig** [comment]
Closed with #1753.

Cosimo's version hack can be considered when the problem crops up :)

**Comment by madig** [comment]
Wargh. I forgot the automatic deploy step.
