### ISSUE TITLE
Use os.path.join instead of strs with '/'

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1756]
In the tests, I noticed with don't use `os.path.join`, https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/specifications/googlefonts_test.py#L22-L28

We currently use strings with forward slashes. This is fine for Linux and OS X but not Windows.

**Comment by m4rc1e** [comment]
@madig are you Win based? and is the above statement still true?

**Comment by madig** [comment]
I suggest we use [pathlib ](https://pypi.python.org/pypi/pathlib2/) instead :) A nicer path API and with broader support in base libraries in Python 3.6+. That would of course require re-writing the code that is supposed to use os.path.join.

I regularly use Windows, Linux and macOS, forward slashes surprisingly work fine most of the time on Windows.

**Comment by felipesanches** [comment]
we already do that ;-)
