### ISSUE TITLE
Check fonts roundtrip through ttx without any errors/warnings

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1763]
@evanadams kindly downloaded the github.com/google/fonts repo and run `ttx` on all the ttf files, 2545 in all, and shared the following info. 

Given fonttools is used by the GF API, for me anything that doesn't roundtrip through ttx is a major concern, and so in Q2 we should perhaps pause the onboarding of new fonts and sort out the files that are there - as a few of them have problems:

* 36 errors in 26 files
* 2285 warnings in 115 files
* 11 files with both errors and warnings

Here's a summary of the errors and the files they occurred in:

```
ERROR: An exception occurred during the decompilation of the 'morx' table
    apache/nokora/Nokora-Bold.ttf
    apache/nokora/Nokora-Regular.ttf
    ofl/battambang/Battambang-Bold.ttf
    ofl/battambang/Battambang-Regular.ttf
    ofl/fasthand/Fasthand-Regular.ttf
    ofl/hanuman/Hanuman-Bold.ttf
    ofl/hanuman/Hanuman-Regular.ttf
    ofl/kantumruy/Kantumruy-Bold.ttf
    ofl/kantumruy/Kantumruy-Light.ttf
    ofl/kantumruy/Kantumruy-Regular.ttf
    ofl/kdamthmor/KdamThmor-Regular.ttf
    ofl/khmer/Khmer.ttf
    ofl/phetsarath/Phetsarath-Bold.ttf
    ofl/phetsarath/Phetsarath-Regular.ttf
    ofl/suwannaphum/Suwannaphum-Regular.ttf

ERROR: An exception occurred during the decompilation of the 'Silf' table
    ofl/harmattan/Harmattan-Regular.ttf
    ofl/scheherazade/Scheherazade-Bold.ttf
    ofl/scheherazade/Scheherazade-Regular.ttf
```

Those are 2 non-opentype tables (from AAT and Graphite I believe) so can be ignored, although I'm curious if FontTools could handle them better as they are rather common. 

```
ERROR: An exception occurred during the decompilation of the 'GSUB' table
error: unpack requires a string argument of length 4
ERROR: An exception occurred during the decompilation of the 'vmtx' table
    ofl/seoulhangang/SeoulHangang-Light.ttf
    ofl/seoulhangang/SeoulHangang-Medium.ttf
    ofl/seoulnamsan/SeoulNamsan-Bold.ttf
    ofl/seoulnamsan/SeoulNamsan-Light.ttf
    ofl/seoulnamsan/SeoulNamsan-Medium.ttf
```

This is a surprise as this was only added recently, and is something fontbakery should have prevented getting to the github repo, so I filed  https://github.com/google/fonts/issues/1513 to get it fixed in the fonts asap.

```
ERROR: Unhandled exception has occurred
    ofl/gudea/Gudea-Bold.ttf
    ofl/gudea/Gudea-Italic.ttf
    ofl/gudea/Gudea-Regular.ttf
```

This seems like a bug in fontTools, so I filed https://github.com/fonttools/fonttools/issues/1229

The warnings (2285) fell into three categories:

* 2272: name id NNN missing from name table
* 12: Glyph <name> has a huge advance width (NNNNN); is it intentional or an (invalid) negative value?
* 1: 'created' timestamp seems very low; regarding as unix timestamp

The advance width and timestamp issues also seem like very helpful checks that fontbakery should be capturing and reporting as fails (and we should be prioritizing them higher than just a warning.) The name id missing concerns should also not be happening, but requires further inspection. These can be split out into separate fontbakery issues. 

The point is that FB should check fonts roundtrip through ttx without any errors/warnings :)

**Comment by evanadams** [comment]
There were 12 warnings saying:

    Glyph <name> has a huge advance width (NNNNN); is it intentional or an (invalid) negative value?

Six of them are for the glyph 'space', which seems very suspicious.  They are all from the same family:

    apache/jsmathcmbx10/jsMath-cmbx10.ttf
    apache/jsmathcmbx10/jsMath-cmex10.ttf
    apache/jsmathcmbx10/jsMath-cmmi10.ttf
    apache/jsmathcmbx10/jsMath-cmr10.ttf
    apache/jsmathcmbx10/jsMath-cmsy10.ttf
    apache/jsmathcmbx10/jsMath-cmti10.ttf

One for glyph 'rs' from:

    ofl/vibur/Vibur-Regular.ttf
 
Some *.te ones,  'matraAi.te', 'matraAiLengthmark.te', 'Lengthmark.te', 'Halant.te', from:

    ofl/balootammudu/BalooTammudu-Regular

One for glyph '_336' from:

    ofl/dekko/Dekko-Regular.ttf

**Comment by davelab6** [comment]
Ignore the jsmathcmbx10 stuff, it was special stuff for https://en.wikipedia.org/wiki/JsMath

`.te` is Telugu; sounds like a compiler bug and worth reporting upstream. I guess -1 became a max value it something silly. 

The others are also worth reporting upstream :)

**Comment by m4rc1e** [comment]
The [Name table Ms spec](https://docs.microsoft.com/en-us/typography/opentype/spec/name) states 
> Name IDs 26 to 255, inclusive, are reserved for future standard names. **Name IDs 256 to 32767, inclusive, are reserved for font-specific names such as those referenced by a font's layout features.**

I've just had a quick look at Source Sans Pro. Our version on GF is out of date, the latest version does have these IDs. They seem to be linked to the Stylistic Set features. Tbh, I'm not sure how applications use these name IDs. 

![screen shot 2018-04-03 at 09 41 55](https://user-images.githubusercontent.com/7525512/38238961-6710a346-3723-11e8-9d29-d9074d44cbb4.png)

**Comment by thlinard** [comment]
Hi @m4rc1e,

Alegreya and Alegreya Sans use both nameID for ss0x. You can check [the Glyphs source](https://github.com/huertatipografica) (btw, [issue14](https://github.com/huertatipografica/Alegreya/issues/14), thank to you!).

InDesign and Illustrator use these names. https://glyphsapp.com/tutorials/stylistic-sets

**Comment by davelab6** [comment]
@felipesanches this seems like it should be very fast to implement.

**Comment by felipesanches** [comment]
![screenshot at 2018-07-20 01 55 20](https://user-images.githubusercontent.com/213676/42983943-31bcf432-8bd9-11e8-9c09-d994314d3c48.png)

**Comment by felipesanches** [comment]
I have further improvements to the implementation of this check. See also: https://github.com/google/fonts/issues/1622

**Comment by felipesanches** [comment]
I close issues tagged with a specific milestone before cutting a release. I have opened an auxiliary isseu for your review task, @davelab6
