### ISSUE TITLE
Warn when copyright string is not "X project authors"

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1769]
## Observed behaviour

https://github.com/google/fonts/pull/1510 has FB output where the copyright notice is not "project authors" 

## Expected behaviour

I expect a warning about this

**Comment by davelab6** [comment]
The copyright does not match between OFL and font files and METADATA.pb. I am surprised that that wasn't checked and reported as a FAIL.

**Comment by felipesanches** [comment]
Nowadays **com.google.fonts/check/102** properly detects this problem:

<img width="1280" alt="captura de tela 2019-01-23 as 17 10 25" src="https://user-images.githubusercontent.com/213676/51630656-dfcb1e00-1f31-11e9-99f7-97f7334bcda4.png">

This was fixed last November, 2018, on FontBakery 0.6.3

<img width="766" alt="captura de tela 2019-01-23 as 17 13 49" src="https://user-images.githubusercontent.com/213676/51630874-5c5dfc80-1f32-11e9-903f-0ddc119fafe0.png">

(issue #2210)
