### ISSUE TITLE
TTFAutohint 'name' table details

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1773]
It is critically important that all TTFs in the API have their TTFAutohint args in the 'name' table, so that an automated solution can be made to replicate the hinting on subsets, etc. 

FB must therefore have a FAILing check for this (likely coded similar to the copyright notice check) and this is a high priority thing for the @graphicore dashboard to track across the publication flow for all families.

**Comment by felipesanches** [comment]
Sure! I'll do it :-D

(I agree this is **very important** stuff)

**Comment by graphicore** [comment]
Is that a feature request, to highlight/track specific check results?

**Comment by felipesanches** [comment]
I think it is just a feature request for a new check. But it might be a feature request for highlighting specific resuts if you decide to fill an issue at https://github.com/googlefonts/fontbakery-dashboard ;-)

By the way, we do have a sketch of a metadata schema for check "priorities". But we never really tagged a significant amount of checks with these specific metadata fields.

**Comment by graphicore** [comment]
> By the way, we do have a sketch of a metadata schema for check "priorities". But we never really tagged a significant amount of checks with these specific metadata fields.

Yeah, and we don't use it all. If we decide to use it e.g. for this kind of thing, we may end up putting priorities on general checks that who are ours, but not those of other users ...

In this case, the check is of course google fonts specific and the clash of priority preferences is far away of becoming real.

**Comment by felipesanches** [comment]
I do not wish to over-complicate things here, but I acknowledge that priority-sorting seems like a user-specific setting rather than an absolute truth that is valid for everyone...

**Comment by felipesanches** [comment]
Our current implementation of **check/056** does already detect when ttfautohint versioning is lacking on the name table entries. But it emits an INFO:

![screenshot at 2018-04-12 17 53 14](https://user-images.githubusercontent.com/213676/38703722-672e090a-3e7a-11e8-94b7-e15ad07c825b.png)

We can make it a **FAIL**.

**Comment by felipesanches** [comment]
And explicitly state why in the FAIL message.

**Comment by felipesanches** [comment]
The current check only tries to parse ttfautohint version info, but not the args:

```
installed_ttfa = re.search(r'ttfautohint ([^-\n]*)(-.*)?\n',
                             ttfa_output).group(1)
```

We probably would want to parse the args as well.

**Comment by felipesanches** [comment]
That's the current state of the collection, regarding availability of the ttfautohint params on version strings of the name table:

![screenshot at 2018-08-22 23 51 25](https://user-images.githubusercontent.com/213676/44502128-8c515d00-a67f-11e8-900c-5414f76a0f76.png)
