### ISSUE TITLE
We need an example file for com.google.fonts/check/all_glyphs_have_codepoints

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1793]
## Observed behaviour

Test 076 passes on the this TTF dump: [test.txt](https://github.com/googlefonts/fontbakery/files/1916395/test.txt)
Note the following cmap table that I hand-corrupted:
```
  <cmap>
    <tableVersion version="0"/>
    <cmap_format_4 platformID="0" platEncID="3" language="0">
      <map code="0x42" name="uni0041"/><!-- LATIN CAPITAL LETTER A -->
      <map code="0x42" name="uni0042"/><!-- LATIN CAPITAL LETTER B -->
      <map code="0x43" name="uni0043"/><!-- LATIN CAPITAL LETTER C -->
    </cmap_format_4>
    <cmap_format_4 platformID="3" platEncID="1" language="0">
      <map code="0x42" name="uni0041"/><!-- LATIN CAPITAL LETTER A -->
      <map code="0x42" name="uni0042"/><!-- LATIN CAPITAL LETTER B -->
      <map code="0x43" name="uni0043"/><!-- LATIN CAPITAL LETTER C -->
    </cmap_format_4>
  </cmap>
```

## Expected behaviour

Test should fail.

## Resources and exact process needed to replicate

fontTools silently discards glyphs that have a duplicate Unicode value:
```
import fontTools.ttLib
t = fontTools.ttLib.TTFont()
t.importXML("test.txt")
t["cmap"].tables[0].cmap
t["cmap"].tables[1].cmap
```
Yields:
```
{66: 'uni0042', 67: 'uni0043'}
{66: 'uni0042', 67: 'uni0043'}
```
Written to disk (`t.save("test.ttf")`):
```
[...]
  <cmap>
    <tableVersion version="0"/>
    <cmap_format_4 platformID="0" platEncID="3" language="0">
      <map code="0x42" name="uni0042"/><!-- LATIN CAPITAL LETTER B -->
      <map code="0x43" name="uni0043"/><!-- LATIN CAPITAL LETTER C -->
    </cmap_format_4>
    <cmap_format_4 platformID="3" platEncID="1" language="0">
      <map code="0x42" name="uni0042"/><!-- LATIN CAPITAL LETTER B -->
      <map code="0x43" name="uni0043"/><!-- LATIN CAPITAL LETTER C -->
    </cmap_format_4>
  </cmap>
[...]
```
Is there actually a real-world test that works (= fails) here? Maybe _this_ is something for a source check instead ;)

**Comment by madig** [comment]
It looks like fontTools will always do some sanitisation, so this check is useless in its current form. We'd need to read the raw data structure.

**Comment by felipesanches** [comment]
**note:** Test 076 was deprecated on FB 0.6.10 (2019-Feb-11)

**Comment by bobh0303** [comment]
For sfnt-based fonts, this test (as written) cannot fail.  Remember that within sfnt-based fonts -- unlike within TTFont python structures representing such fonts -- glyphs do not _themselves_ contain any information about Unicode.

This test iterates over a Unicode cmap which, by definition, maps an _integer_ (interpreted as the Unicode scalar value or USV) to a glyph, and then tests the resulting _integer_ (USV) to see if it is `None`.  Thinking of the sfnt cmap conceptually as a dictionary (with USVs as the keys), the binary structure inside an sfnt implementation constrains the keys of that dictionary to be integer values -- `None` cannot possibly be stored as a key in the cmap.

It is possible that the sfnt cmap structure is bad, mapping a USV to a number that isn't a valid glyph ID, but fontTools would already have caught that and declared the appropriate errors (see class [cmap_format_4() in _c_m_a_p.py](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/_c_m_a_p.py#L681)). (And I'm sure ots would have picked up such a problem.)

It is also possible that fonttools has a bug that, when reading a Unicode cmap, creates a dictionary that has `None` as a key, but fontbakery is not the place to be writing tests for fonttools.
