### ISSUE TITLE
Document how to set up FB & UFO Normalizer as a Git hook

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1794]
I guess that its possible that users would like to get stuff checked on each commit, so we should document how to set it up as a Git hook, which only runs when TTFs are changed (for example.) 

Also, since it is a source (UFO/.Glyphs) checker, we should document how to set up UFO Normalizer and the source checkers as Git hooks, so that stuff is normalized and then checked on each commit. 

Perhaps Font Bakery is likely best run via container pods on PRs, but it is quite a lot of effort to set that up, and the GF cloud may not be a public service - ie, only for families accepted into GF.

**Comment by anthrotype** [comment]
I once experimented doing this with the ufoNormalizer and https://github.com/pre-commit/pre-commit
I had to patch the ufonormalizer script to allow normalizing individual sub-files in the UFO directory (git works on files, not folders), and also to return non-zero exit code whenever a file was normalized, or zero (success) when a file was already normalized.
I haven't pushed it though, it must be somewhere in my old laptop, i'll have to search.. Maybe @moyogo has something similar.

**Comment by davelab6** [comment]
@anthrotype perfecto

**Comment by simoncozens** [comment]
This suggestion was in the pre-GitHub-Actions, pre-googfonts-project-template days, and we can now FontBakery check fonts on build via CI, so I'm calling this done.
