### ISSUE TITLE
com.google.fonts/check/glyphnames_max_length - Only name length of glyphs with cmap entry relevant?

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1795]
Right now, the check ignores glyphs that do not show up in the cmap table, e.g. substitution glyphs accessible via OpenType features. Do those have a length restriction, too? And what's the rationale for the length?

**Comment by madig** [comment]
And does it only matter for the cmap table or should the PostScript name also be below the threshold?

**Comment by madig** [comment]
Ah yes, that's what I meant actually. Maybe the test should move to post.py.

**Comment by davelab6** [comment]
move sounds good

**Comment by davelab6** [comment]
While we are waiting for input, you can still add a note to the check that this check is ported from Mekkablue Preflight Checks

**Comment by madig** [comment]
The 109 limit is shorted out by test 058 that mandates a 31 character limit.

**Comment by felipesanches** [comment]
I would prefer to disable it (with the @disable decorator and adding a DISABLED_ prefix to the corresponding code-test). We may still hear from @mekkablue regarding a rationale for this checj and maybe the other check's 31-char limit might be invalid while the 109 may still hold. So let's not trash it so fast.

**Comment by simoncozens** [comment]
This check is disabled, and considers the maximum valid length of a glyph to be 109 bytes. However, the [post specification](https://docs.microsoft.com/en-us/typography/opentype/spec/post) states that "Names must be no longer than 63 characters". The check should be re-enabled and the limit reduced to 63.

**Comment by felipesanches** [comment]
@miguelsousa deleted this check on his personal repo: https://github.com/miguelsousa/openbakery/commit/4f6f4c30c42a634d9409b8772ef7d43415bd55fd

> The check should be re-enabled and the limit reduced to 63.

What do you think of @simoncozens's suggestion, Miguel?

**Comment by felipesanches** [comment]
As I've been making a strong effort to keep FontBakery in sync with Miguel's repo, I will delete the check in FontBakery as well. And if we ever decide to reintroduce this check, its code is available in the removal commit mentioned above.

**Comment by miguelsousa** [comment]
For what is worth, my rationale for deleting the code was:
- The check has been disabled since #1816
- The disabled code is more than 5 years old, so it's very stale
- If the code is ever needed it can be found in the commit history
- [`com.google.fonts/check/valid_glyphnames`](https://github.com/googlefonts/fontbakery/blob/0b2e10dd117c657794c246c6f450ff82bf7e0cf7/Lib/fontbakery/profiles/universal.py#L817) already validates the length of glyph names

**Comment by felipesanches** [comment]
Fair enough :-)
