### ISSUE TITLE
deprecate 060

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1808]
060 does not contain any hint as to what is "incorrect".

**Comment by madig** [comment]
Ah. It checks for glyph name duplicates, fonttools renames glyphs internally with `"#<n>"` like `[..., "space", "space#1", ...]`.

**Comment by felipesanches** [comment]
alright! I think 060 can be dropped then, as 058 already fulfills that need for checking validity of glyph names and 059 does the same as 060 but stating clearly its purpose.

**Comment by madig** [comment]
What about https://github.com/googlefonts/fontbakery/issues/1795?

**Comment by felipesanches** [comment]
check/060 was deprecated on FontBakery 0.4.0 (2018-May-16)
