### ISSUE TITLE
Add checks for ISO 15008:2017

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1832]
ISO 15008 has a bunch of requirements for typefaces used in automobile dashboards. Given the Libre Planet presentation that @felipesanches and I attended, I thought that we could add checks for this, as it will be a fun thing to highlight in the dashboard. 

https://www.iso.org/standard/62784.html

**Comment by felipesanches** [comment]
oh wow! That sounds interesting! ;-)

**Comment by felipesanches** [comment]
@davelab6 please describe the specific checks you think would be useful based on the ISO standard

**Comment by felipesanches** [comment]
I am not sure, but maybe this was the talk. I would only be able to confirm by actually watching the entire video to try to find where's the reference to the ISO spec: https://media.libreplanet.org/u/libreplanet/m/freedom-embedded-vehicles/

There doesn't seem to be any other talk in the LibrePlanet 2018 program where this ISO spec could have been likely mentioned. So I think this is indeed the talk Dave and I attended.

**Comment by felipesanches** [comment]
@davelab6 mentioned at #3249 that this is needed "basically immediately for a customer."

Dave also requested:
* "Check if each named style meets ISO 15008 legibility standards."

**Comment by davelab6** [comment]
Thanks Simon for jumping on this. 

I miss the dashboard
