### ISSUE TITLE
Setup a Gitter chatroom. (We were planning to use IRC freenode.net but now we'll give Gitter a try...)

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1833]
To allow for realtime chat between fontbakery contributors. Naturally, it should not replace the issue tracker! Relevant issues should still be filed in here.

```
#fontbakery
irc.freenode.net
```

**Comment by felipesanches** [comment]
I haven't setup the channel yet. I'll close the issue once I do these things:
- [ ] set up the channel
- [ ] register an admin (initially myself)
- [ ] update info on README.md
- [ ] start showing up myself in there regularly

**Comment by madig** [comment]
Alternative: Use Gitter and see if that fits the bill.

**Comment by davelab6** [comment]
Isn't Gitter proprietary?

**Comment by davelab6** [comment]
Awesome! Then this seems fine :)

**Comment by felipesanches** [comment]
We will start experimenting Gitter, then.

I will be the boring person who will ask from time to time for things mentioned in that chat channel to be persisted into properly detailed issues on the tracker :-)

**Comment by cjchapman** [comment]
So... how's it going with setting up Gitter? 😄

**Comment by davelab6** [comment]
www.gitter.im/fontbakery

Please add to readme to close this out
