### ISSUE TITLE
Set fontbakery.appspot.com to redirect to fontbakery.com

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1835]
## Observed behaviour

https://fontbakery.appspot.com is still up, with a very old and partial version

## Expected behaviour

https://fontbakery.appspot.com should redirect to fontbakery.com

## Resources and exact process needed to replicate

Easiest thing will be to push a index.html similar to https://github.com/googlefonts/fontbakery/blob/gh-pages/index.html

**Comment by felipesanches** [comment]
Done!
