### ISSUE TITLE
[specifications/dsig] Which applications require a dsig table?

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1845]
It's 2018 and I'm wondering which MS apps depend on this table?

There's no rationale in the test, just a very loose comment.

https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/specifications/dsig.py

I'd love for someone to confirm that MS Office 2013 depends on this table etc and then we can add this to the test rationale.

btw, Fontmake doesn't create a dsig table.

cc @khaledhosny

**Comment by jenskutilek** [comment]
I can confirm that Word 2016 does **not** require a DSIG table in TTFs for the OT layout features to be recognized.

**Comment by anthrotype** [comment]
:champagne:

**Comment by chrissimpkins** [comment]
Is it possible to revisit this FAIL?  We are still failing default fontmake builds which means that a project must implement a post-compile workaround to pass fontbakery tests when fonts are compiled with fontmake.

I suggest that we either provide explicit rationale for this failure so that users can understand whether to exclude it themselves or (ideally) downgrade to a WARN in the universal profile. 

Associated: https://github.com/googlefonts/fontmake/issues/431

**Comment by bobh0303** [comment]
I can confirm that, with Windows 10, Word 2013 _does_ require DSIG in some contexts. For example, Stylistic Sets won't work in latin script fonts without DSIG. 

(As mentioned above, this is no longer true for Word 2016)

**Comment by chrissimpkins** [comment]
Thanks @bobh0303!  That is helpful.

**Comment by chrissimpkins** [comment]
[Office 2013 Extended Support](https://support.microsoft.com/en-us/lifecycle/search/?p1=16674) end date is 4/1/2023:

<img width="503" alt="gb1uc-image" src="https://user-images.githubusercontent.com/4249591/70635741-6ea46000-1c02-11ea-95a0-da08fd254cb0.png">

[Microsoft Fixed Life Cycle Policy](https://support.microsoft.com/en-us/help/14085/fixed-lifecycle-policy)

**Comment by felipesanches** [comment]
yea, we'll have to keep the check as-is. We should consider sending a PR to fontmake to ensure it generates fonts with dummy signatures.

**Comment by chrissimpkins** [comment]
Marc raised the issue in https://github.com/googlefonts/fontmake/issues/431 but there was not support for it.

**Comment by chrissimpkins** [comment]
I added all of this information to the rationale for the check in https://github.com/googlefonts/fontbakery/pull/2716

**Comment by chrissimpkins** [comment]
The MS team confirmed the findings by Jens and Bob here through the developer who changed the behavior in MS Word back in 2014. The absence of a DSIG table has not blocked the enumeration of OpenType features in MS Word since.
