### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1854]
I'd appreciate a 0.3.6 release that would also advertise Python 3 compatibility.

**Comment by davelab6** [comment]
Seems like a 0.4.0 to me :D 

@felipesanches is keen to to a monthly release cadence, and I agree, its been a while since the last release :)

**Comment by davelab6** [comment]
@felipesanches what's the ETA on this?

**Comment by felipesanches** [comment]
likely this week.I want to sort out the markdown reporter before releasing.

**Comment by felipesanches** [comment]
#1754

**Comment by felipesanches** [comment]
I have just published the Font Bakery 0.4.0 packages (compatible with both python 2 and python 3) to pypi.

https://pypi.org/project/fontbakery/

I installed it on MacOS using pip and got it working nicely. Cheers!
