### ISSUE TITLE
Improve 'gasp' table checks

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1858]
## Observed behaviour

#1857 improves the 'gasp' table checks in small ways. 

However, it would be ideal to have a table showing what the gasp table values are, with a col for if the value is reasonable; and to have several reasonable check results. 

## Expected behaviour

https://docs.microsoft.com/en-us/typography/opentype/spec/gasp provides such an example table at the end. 

## Resources and exact process needed to replicate

@m4rc1e do you feel qualified to weigh in on what a reasonable set of gasp table results are?

**Comment by felipesanches** [comment]
@m4rc1e do you feel qualified to weigh in on what a reasonable set of gasp table results are?

**Comment by m4rc1e** [comment]
Unfortunately, there is no *one size fits all* for setting a gasp table. At Dama, we set them individually for each family.

To start with, we could do the following:

• If the font uses ttfautohint, make sure the gasp is set to the following:
![screen shot 2018-07-31 at 15 21 40](https://user-images.githubusercontent.com/7525512/43465778-f71eb774-94d5-11e8-8694-3c2190aa439d.png)


• If the font is manually hinted, warn if there's only a single range. Message could state that adding ranges with grid fitting may improve quality etc
