### ISSUE TITLE
Add checks for upstream repos

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1868]
[Here](https://github.com/EbenSorkin/Aplous), at it's current commit, is a great example of a repo that doesn't meet expectations. Looking at the repo, one can come up with lots of checks for things that are missing it should be moved...

**Comment by felipesanches** [comment]
By "at it's current commit" @davelab6 meant this:
https://github.com/EbenSorkin/Aplous/tree/46e559c70941f31efe5e9097f261020a21c14a97

(for keeping this issue future-proof :-D)

**Comment by davelab6** [comment]
Closing as duplicate of https://github.com/googlefonts/fontbakery/issues/1772
