### ISSUE TITLE
[crash] reporters/serializer on python 3 when using check clustering

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1873]
While inspecting and bugfixing issue #1870 I noticed that @m4rc1e 's command-line would trigger a crash on **python 3** (Marc seems to be using python 2 at the moment though, so I think he had not noticed this one yet):

![screenshot at 2018-05-17 10 50 59](https://user-images.githubusercontent.com/213676/40181739-5a6f14b4-59d9-11e8-829c-d5d7b1660428.png)

**Comment by m4rc1e** [comment]
Yeah I'm still py2.7 for font stuff atm.

**Comment by madig** [comment]
I remember this I think. The `max()` function works on None in Py2 because `1 > None` works, but Py3 has stricter requirements.
