### ISSUE TITLE
OS/2 usWeightClass should only warn when ExtraLight is 250

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1876]
In https://github.com/Omnibus-Type/Grenze/issues/1 `com.google.fonts/check/020` says

> 🔥**FAIL** OS/2 usWeightClass expected value for 'ExtraLight' is 275 but this font has 250.

250 is acceptable for TTFs (not OTFs), because it won't auto-bold (and blur) in Windows GDI apps. However, since OTFs will, and because we'd like to have OTFs and TTFs be as consistent as possible, we'd prefer ExtraLight to be 275 in both cases. 

So, the above should be a WARN not a FAIL, but the check logic should reflect this nuance - not just s/FAIL/WARN :)

Related older discussion in https://github.com/googlefonts/fontbakery/issues/1355

**Comment by felipesanches** [comment]
@m4rc1e I have checked out https://github.com/Omnibus-Type/Grenze.git and when running fontbakery I do not get that "this font has 250" FAIL. The message for ExtraLight is "but this font has 200" instead.

Have you run fontbakery on a different set of TTFs to generate that report (https://github.com/Omnibus-Type/Grenze/issues/1#issue-324383064) then?

**Comment by m4rc1e** [comment]
Nope,

Well I now get
```
>> com.google.fonts/check/020 with ((u'font[0]', '/Users/marc/Documents/googlefonts/manual_font_cleaning/Grenze/fonts/ttf/Grenze-ExtraLight.ttf'),)
   Checking OS/2 usWeightClass.
 * WARN: A value of 250 for OS/2 usWeightClass is acceptable for TTFs (but not for OTFs), because it won't auto-bold (and blur) in Windows GDI apps. However, since OTFs will, and because we'd like to have OTFs and TTFs be as consistent as possible, we'd prefer ExtraLight to be 275 in both cases.

   Result: WARN
```

Which works just fine for me :-).

Thanks

**Comment by felipesanches** [comment]
yes. I have just implemented that a few days ago, hahaha
