### ISSUE TITLE
Fix GFonts-specific checks that crept into the opentype-spec checks

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1881]
### Test 40 and 42: WARN instead of FAIL?

We use a specific way of calculating vertical metrics and on some fonts, one or the other test fails when the metrics are really deliberate. So... for GF, a fail certainly make sense, but for us, they're more of a warning. Foundries can chose whatever metrics calculation suits the project at hand, so would it make sense to make this a warning? I don't think we currently can make it fail for the googlefonts specification but warn otherwise?

**Comment by davelab6** [comment]
I agree that [Lib/fontbakery/specifications/os2.py#L199](https://github.com/googlefonts/fontbakery/blob/e300c34fa44f500bcdccb648e732f6463ddfc64f/Lib/fontbakery/specifications/os2.py#L199) looks like a "GF distributor level" check, and so should be in `Lib/fontbakery/specifications/googlefonts.py`, and the check in `os2.py` should be checking stuff is valid only in terms of the OpenType spec (eg values are within the expected positive or negative range; some values often flip to positive when they should be negative and vice versa, or are crazy big/small)

**Comment by felipesanches** [comment]
In the past we've identified and discussed that it could be desirable to have a way to customize the check-results (such as FAIL versus WARN) based on user preferences. But it is unclear at this moment how could that feature be implemented.

We currently have ways to craft custom specifications by cherry-picking checks and adding custom checks, but we still have no "check-inheritance" techniques in place to allow customizing an existing check without duplicating code.

I am not even sure that would be good to have. But it is an issue that has already surfaced a few times.

**Comment by madig** [comment]
This seems neither quick nor up for 0.4.1.

**Comment by felipesanches** [comment]
@davelab6's suggestion seems rather quick(-ish) while completely avoiding the "fails for gfonts but warns for every one else" proposal. My previous comment, on the other hand, reflects something that would certainly take more time to figure out, but we can leave that to a separate "maybe-someday" issue, if we ever decide to tackle the challenge.

So please take https://github.com/googlefonts/fontbakery/issues/1881#issuecomment-392149538 as just a mildly related thought rather than the actual task at hand in here.

**Comment by davelab6** [comment]
> In the past we've identified and discussed that it could be desirable to have a way to customize the check-results

This is a separate issue. If there isn't an issue for that, please file one. But this issue is scoped to fixing the GF-specific checks that crept into the OT-spec checks.
