### ISSUE TITLE
Add check for mkmk feature

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1883]
We need a check that fails on the issue described in https://github.com/googlei18n/ufo2ft/pull/189

**Comment by anthrotype** [comment]
Can you elaborate what the issue exactly is and how to reproduce? Otherwise, I cannot fix it, nor fontbakery can do any checks?

**Comment by davelab6** [comment]
> what the issue exactly is

https://github.com/googlei18n/ufo2ft/pull/189#issue-157273446 says a widespread OpenType layout library (InDesign vCS6) doesn't correctly process `mkmk` with more than one lookup. How is this not clear :)

> nor fontbakery can do any checks

I propose a binary check would fail is the `mkmk` feature has more than one lookup; and if there is more than one subtable per anchor; and if there is no subtle for an anchor; and a source check would fail if there is more than one lookup for `mkmk`.

**Comment by anthrotype** [comment]
before you put any checks or spread rumors about this, we need to first reproduce this.

**Comment by felipesanches** [comment]
I had the impression that some people experienced the issue and reported it. Are you saying you think they may be mistaken and that there's need for a second person to replicate the issue before moving on?

**Comment by felipesanches** [comment]
if you have a reasonable suspicion that the reported issue is bogus then I would agree that we'd need further confirmation of the problem.

**Comment by anthrotype** [comment]
see @belluzj reply https://github.com/googlei18n/ufo2ft/pull/189#issuecomment-392094187

**Comment by simoncozens** [comment]
Seems like this was not reproducible and Jany wasn't sure if it was an issue or not. And frankly if there is an issue here, it's that Adobe should fix their software...
