### ISSUE TITLE
Release 0.4.1?

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1891]
I think we need one to get https://github.com/googlefonts/fontbakery/pull/1880 and https://github.com/googlefonts/fontbakery/pull/1889 out. Since the spec_imports kwarg PR is merged, this might actually be more like a 0.5.0...

**Comment by graphicore** [comment]
I'll quickly do a  PR for this https://github.com/googlefonts/fontbakery/pull/1888#issuecomment-392574472 `set_check_skip_filter`. So we can include that into the version bump. I have no idea of how big a version increase step size should be, but the `spec_imports` doesn't seem to be a backwards compatibility issue, while changing `set_check_filter` to e.g. `@property check_skip_filter` would break the old API, so, with that I guess a bigger version increase is rather justified(?).

**Comment by felipesanches** [comment]
don't you think more than 1 release per month is a bit too much?

**Comment by graphicore** [comment]
> don't you think more than 1 release per month is a bit too much?
 
I don't have a strong opinion about this.

**Comment by madig** [comment]
I'd say release as often as necessary? I think #1880 and #1889 need to get out there.

As for version increases: https://semver.org/.

**Comment by graphicore** [comment]
> As for version increases: https://semver.org/.

OK, but since we're still in MAJOR 0:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

we're basically free to do whatever we want.

**Comment by felipesanches** [comment]
I think there's no desperate need to rush things. We've just released 0.4.0 barely 13 days ago, after 5 months of development. My goal was then to intensify the release schedule by starting cutting roughly one release per month. More than that sounds like an unnecessary burden.

**Comment by felipesanches** [comment]
@madig Is there anything affecting/complicating Dalton Maag's usage of the tool if we keep the plan of releasing 0.4.1 by mid-June?

**Comment by madig** [comment]
Yes, https://github.com/googlefonts/fontbakery/pull/1880 makes a standard test relevant for every OpenType font not be broken.

> one release per month

You can do that, but patch releases can and should be faster. All you need to do is tag it.

**Comment by davelab6** [comment]
I agree with Nikolas, no need to gate releases to a Max cadence, I see it
more as one release per month minimum.

0.4.1 seems right to me

**Comment by felipesanches** [comment]
alright. Let's do it then!

**Comment by felipesanches** [comment]
https://pypi.org/project/fontbakery/0.4.1/
