### ISSUE TITLE
Ways to customize check results to address user's diverging checking criteria

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1893]
In the past we've identified and discussed that it could be desirable to have a way to customize the check-results (such as FAIL versus WARN) based on user preferences. But it is unclear at this moment how could that feature be implemented.

We currently have ways to craft custom specifications by cherry-picking checks and adding custom checks, but we still have no "check-inheritance" techniques in place to allow customizing an existing check without duplicating code.

I am not even sure that would be good to have. But it is an issue that has already surfaced a few times.

Note: This was originally mentioned at issue #1881

**Comment by graphicore** [comment]
There are already ways to implement such a thing, but without a good description I wouldn't bother to give a complete example. In short, e.g. a dictionary or just the plain  status value could be put into the DI-namespace and required by the checks. The DI namespace can be overridden by a spec, we do this overriding already e.g. in

https://github.com/googlefonts/fontbakery/blob/21b51ae72653b57b61dd6402ded30c0e48289e82/Lib/fontbakery/specifications/googlefonts.py#L197-L198

note the `force=True`

Other ways (not implemented )could be to add some transformation function directly to the spec, checkrunner or reporters …

Changing specs is not always cool, so we should be careful. I.e. the opentype spec should not not override any other spec it included. The googlefonts spec could however be considered like a end-point spec, so overriding there is OK, we do it to set our defaults. Also, an end user can do so, when it's obviously not influencing other users of the same spec. (This is a typical side-effects issue.)

**Comment by felipesanches** [comment]
what does `DI` stand for?

**Comment by graphicore** [comment]
dependency injection

**Comment by simoncozens** [comment]
I think the configuration files (particularly the `override` key), together with custom profiles, allow this kind of behaviour.
