### ISSUE TITLE
What to do about FAIL -fontforge-check: Glyphs do not have points at extremas!

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/fontbakery#1895]
## Observed behaviour

I have run the "add extremas" in Glyphs and this altered 10-15 glyphs but I still get this error. 

## Expected behaviour

Should I now ignore it this error or is there an efficient method for finding/fixing the problem shapes?

## Resources and exact process needed to replicate

[Aplos-Regular.ttf.zip](https://github.com/googlefonts/fontbakery/files/2050913/Aplos-Regular.ttf.zip)

**Comment by EbenSorkin** [comment]
I spent some time looking into what could be done with my font using existing tools to check. I tried red arrow and it helped me find some non flat curve points that resolve from PS bezier into in a TTF quadratic shape that does lack an extrema. Thanks to Kostas for noticing it in the TTF output! I also found non flat and no straight lines that I could fix and fixed them. And I merged some shapes to see if issues showed up post-merge. They do. So I fixed those. But I still get the extrema error in FL. It think now that the most useful thing would be to have the error report which glyph/s has/have the issue by name and or by glyph number. I am also of two minds about if this should be a "Warning" or a "Fail". The argument for fail is that if you really don't have an extrema at the top of let's say O this could cause catastrophic rendering errors - BUT- you could also have a design that deliberately works to get a shape that can't be made unless you violate a rule. (Mathew Carter has given examples of this ) then the fail is arguably too strong. My feeling is that especially if there is reporting about where the errors are found we could more reasonably assume that designers or others will be able to take steps to remedy the problem.

**Comment by EbenSorkin** [comment]
BTW - with the red arrow issues fixed I was able to use the Glyphs add extrema tool to somehow fix something the red arrow script did not see and now I don't get the extrema error.

**Comment by felipesanches** [comment]
we don't have fontforge checks anymore
