### ISSUE TITLE
.null or NULL Question

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/fontbakery#1896]
## Observed behaviour

I get this Warning - com.google.fonts/check/046 Font contains the first few mandatory glyphs (.null or NULL, CR and space)?

## Expected behaviour

I expected Glyphs to encode NULL or .null ( I think it likes .null better) but it doesn't. Should we eliminate this or encorage people to enter the data manually? That is assuming it stays! LOL.

**Comment by davelab6** [comment]
I think this check may be obsolete. If glyphsapp no longer compiles these,
we can forget it...

**Comment by EbenSorkin** [comment]
OK great. Should we probably have a standard name for this? Again based on Glyph's behavior it looks like it likes ".null"

-e.

**Comment by madig** [comment]
I'd like a better rationale than "Glyphs doesn't do it". I found this: http://www.homer.com.au/webdoc/graphics/ttf/recom.htm -> "First Four Glyphs in Fonts". Doesn't seem to be present in v1.8.2 of the OpenType spec: https://docs.microsoft.com/en-us/typography/opentype/spec/recom. Instead, the .notdef glyph is described as must-be-first-glyph.

**Comment by moyogo** [comment]
The first four glyphs were discussed on the OpenType mailing list a couple of years ago, there were no valid reasons for the recommendation and it was removed from the spec. See https://docs.microsoft.com/en-us/typography/opentype/spec/changes under Version 1.8.

**Comment by moyogo** [comment]
The only thing that was kept is of course that the first glyph must be .notdef.

**Comment by EbenSorkin** [comment]
OK so then being arbitrary and choosing .null or NULL as standard in a
system makes no difference.

We could be OK with either I suppose e.g. permit both but... I think it
will make less noise over time if a choice is made with regard to Bakery
and the Google standard glyph lists.

-e.

**Comment by davelab6** [comment]
Thanks Denis! I guess we should have a few checks, so that the end state is
that all GF fonts end up without the unneeded glyphs and a glyph named
.notdef as the first glyphID
