### ISSUE TITLE
"fonts" injected parameter: pass TTFont objects instead?

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1898]
## Observed behaviour

Check `com.google.fonts/check/002` features the magic `fonts` parameter, which is a list of str-paths.

## Expected behaviour

I'd like to get a list of TTFont/defcon.Font objects (optionally or instead) to save me the trouble of opening the fonts myself.

Maybe the parameter can be split into

- font: a TTFont/defcon.Font object, determined by the specification object. Would replace the ttFont parameter.
- fonts: a list of above, i.e. all fonts to check.
- font_paths: a list of os.PathLike objects, i.e. the file paths of the fonts.

**Comment by graphicore** [comment]
with `FontsSpec` use `ttFonts`, it's already there, as a "derived iterable" you can define your own derrived iterables in `UfoSpec`. Just like in:

https://github.com/googlefonts/fontbakery/blob/a6c76dd9ae5526019dec5d75bd610906a0afd19a/Lib/fontbakery/fonts_spec.py#L61-L67

**Comment by madig** [comment]
I'd need to run benchmarks, but fontTools loads binaries lazily.

**Comment by madig** [comment]
Ugh, that's hardcore. Okay, found the docs on https://github.com/googlefonts/fontbakery/blob/master/docs/writing-specifications.md...

**Comment by madig** [comment]
I'd have to dig into the `loca` test -- I remember that I had to poke the font object in a certain sequence or fontTools would silently fix the corrupt table entries.

**Comment by graphicore** [comment]
> fontTools would silently fix

Yep, that's bad! Maybe we can ask if fontTools could have a kind of inspection mode that doesn't do these things.

**Comment by madig** [comment]
Or maybe it was related to saving and loading the object for the test...? Hm... I can't prove it right now, so maybe it's not relevant here, may come back when I find something.

**Comment by davelab6** [comment]
I think we should simply have a FAIL level check that round trips the TTF through fonttools and md5s the input and output and fails if they aren't the same. I think there was a timestamp neutral mode added to allow this.

**Comment by anthrotype** [comment]
Upon loading, fonttools should not "silently fix" anything, it should just read the incoming data. If you can show me that it is modifying things when reading, than it's a bug and we need to fix it.

I'm a bit skeptical about the latter suggestion of checking that roundtripping through fonttools doesn't change the output, binary-wise.
FontTools can only guarantee that it will roundtrip a file that was in turn generated by the same version of FontTools. It this is not the case, then there could be some hidden bugs that prevent it from generating a deterministic output. However, things may and do change (for the better, I hope) across versions.
