### ISSUE TITLE
So... ijacute etc?

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/fontbakery#1902]
I just noticed that the ijacute and IJacute are not part of the Google glyph lists. 

The link below may go some way to explaining why. e.g. Perhaps there isn't really an existing agreed orthodoxy to follow? 
http://typedrawers.com/discussion/1294/how-do-you-implement-ijacute-and-ijacute

Or maybe you are happy with this 
https://glyphsapp.com/tutorials/localize-your-font-accented-dutch-ij
And this is an omission? 

What's the current attitude?

-e.

**Comment by felipesanches** [comment]
#2263

**Comment by felipesanches** [comment]
do you have an update on this, @EbenSorkin?

**Comment by EbenSorkin** [comment]
RE: IJ and IJacute -  I think it would make sense to add them to the standard lists particularly as it is fairly easy to make them and auto-gen code for them now. But I am not managing the lists. I am also not sure who is. 

There may be other tweaks to glyph names that are worth making too so that they are made contemporary/orthodox with Glyphs app "nice names". I think that probably an official nice name may have shifted over time and/or that an imperfect mapping of older expected names to nice names may have been done. Unfortunately I don't have a complete list of examples of these to hand. But I am interested in helping to get it sorted this year.
