### ISSUE TITLE
Properly setup Travis CI on this repo

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#1906]
@anthrotype, @madig myself and @davelab6 got into a conversation about setting up Travis CI properly for this repo, but we discussed this in the middle of a pull request thread here:
https://github.com/googlefonts/fontbakery/pull/1900#issuecomment-393600755

Since that PR was merged and closed, I just opened now this issue to keep track on the progress of this task. It seems by @davelab6's https://github.com/googlefonts/fontbakery/pull/1900#issuecomment-395511467 that Dave may have just fixed the problem.

@madig / @anthrotype please let us know here when you feel the system is working well so that we can close the issue. Otherwise, please describe what else might still be missing in the setup.

Cheers!

**Comment by madig** [comment]
Works now: https://github.com/googlefonts/fontbakery/pull/1908

**Comment by felipesanches** [comment]
thanks!
