### ISSUE TITLE
Status class refactor

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1909]
It feels very clumsy to yield a `tuple(global instance of a Status class, string)` and sometimes `tuple(global instance of a Status class, instance of a Message class)` from a check. I'm also not fond of how the Status class is used for bookkeeping (`START`, etc.), but that may be a different issue.

Here's a first pass at rewriting the class using the `attrs` library:
```Python
import attr


@attr.s(frozen=True)  # Make instances "immutable".
class Status:
    weight = attr.ib(cmp=True, type=int)  # Used for comparison.
    message = attr.ib(cmp=False, type=str)
    code = attr.ib(cmp=False, type=str)

    @classmethod
    def Debug(cls, message, code=None):
        return cls(weight=0, message=message, code=code)

    @classmethod
    def Pass(cls, message, code=None):
        return cls(weight=1, message=message, code=code)

    @classmethod
    def Info(cls, message, code=None):
        return cls(weight=2, message=message, code=code)

    @classmethod
    def Skip(cls, message, code=None):
        return cls(weight=3, message=message, code=code)

    @classmethod
    def Warn(cls, message, code=None):
        return cls(weight=4, message=message, code=code)

    @classmethod
    def Fail(cls, message, code=None):
        return cls(weight=5, message=message, code=code)

    @classmethod
    def Error(cls, message, code=None):
        return cls(weight=6, message=message, code=code)
```
Instances can be compared:
```Python
def test_comparison():
    a = Status.Pass("...")
    b = Status.Error("...")
    assert a < b
```
A test would yield like this:
```Python
def check_something():
    # ...
    yield Status.Pass("Looks good.")
    # ...
    yield Status.Fail("Nope.", code="mismatched-something")
```
This would also make the `Message` class obsolete. I left out the name field because I don't know how useful custom statuses are.

What do you think?

**Comment by davelab6** [comment]
The ability to compare check results like that seems desirable to me;
especially if weight can become a float, such that we can add meta checks
that have a very high weight for their class when things are inconsistent.
Eg for GF, if all fonts have a fsType of zero except one, then something is
more messed up than if they all have non zero fsTypes...

**Comment by madig** [comment]
You can already compare Status objects.

Not sure how useful how a more complex weight handling would be, are you thinking of pylint's code grades?

**Comment by madig** [comment]
I improves things insofar that you don't have global singleton instances of the Status object, the code is significantly easier to work with and you can toss that Message object that for some reason is disjointed from `Status` and has to be imported separately. This is about ease of maintenance, something fontbakery definitely needs more of.

**Comment by madig** [comment]
Hm. Need to think about how a test of a check would test for statuses.

**Comment by graphicore** [comment]
> you don't have global singleton instances of the Status object,

How's that a problem and fundamentally different from your suggestion?
 
> the code is significantly easier to work with

I disagree. I see no real difference. 

> and you can toss that Message object that for some reason is disjointed from Status and has to be imported and handled separately.

The Message class was retrofitted for unit testing of specific check statuses. It's an example of the customizability I was talking about.

> This is about ease of maintenance, something fontbakery definitely needs more of.

I can't follow, sorry. It still looks to me like a style/taste thing and a rather big effort.

**Comment by davelab6** [comment]
>>> Instances can be compared
> 
> You can already compare Status objects
> ...
> This is about ease of maintenance, something fontbakery definitely needs more of

If there's no functional benefit, please could you explain in more detail what is made easier?

**Comment by madig** [comment]
> How's that a problem and fundamentally different from your suggestion?

"If you create a custom Status symbol, please keep in mind that all statuses are registered globally and that can cause name collisions". Nothing global in my approach, except for the class itself.

> The Message class was retrofitted for unit testing of specific check statuses. It's an example of the customizability I was talking about.

Ah okay, I thought it was meant to provide a short-hand for a specific condition in a test.

**Comment by davelab6** [comment]
> Nothing global in my approach, except for the class itself

What is the benefit of have no globals?

**Comment by graphicore** [comment]
> can cause name collisions

Maybe we should remove the comment if it's disturbing. Or formulate it in a more positive way, the upside of possible name collisions is that you are encouraged to check that your new status is not already in use but with other semantics.

**Comment by madig** [comment]
> What is the benefit of have no globals?

It removes a class of bugs where a global variable is changed while your code assumes something else. Or you try to test/modify something and have to faff around with a global variable that may break something else.

> the upside of possible name collisions is that you are encouraged to check that your new status is not already in use but with other semantics.

IMHO, this is only useful if you get a proper error message upon colliding. Otherwise, stuff may just break in weird ways and you have to debug it.

**Comment by graphicore** [comment]
> IMHO, this is only useful if you get a proper error message upon colliding.

That's straight forward to add.
