### ISSUE TITLE
Why is it important to specify the order of check runs?

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1918]
I found this in the README but have no idea what it's trying to tell me:
```
      -o ORDER, --order ORDER
                            Comma separated list of order arguments.
                            The execution order is determined by the order of the check
                            definitions and by the order of the iterable arguments.
                            A section defines its own order. `--order` can be used to
                            override the order of *all* sections.
                            Despite the ITERATED_ARGS there are two special
                            values available:
                            "*iterargs" -- all remainig ITERATED_ARGS
                            "*check"     -- order by check
                            ITERATED_ARGS: font
                            A sections default is equivalent to: "*iterargs, *check".
                            A common use case is `-o "*check"` when checking the whole
                            collection against a selection of checks picked with `--checkid`.
```

**Comment by graphicore** [comment]
The algorithm that determines the order of the check execution has to make decisions that influence the order it produces. This option can change the default decisions.

**Comment by madig** [comment]
Can you give a concrete example where this is used and why? I don't understand the last sentence of the help text quoted above.

**Comment by graphicore** [comment]
You pick two checks. `check01(font)` and `check02(font)` You run them with three `fonts =  ["fontA", "fontB", "fontC"]`.

The default execution order will be:

```
check01("fontA")
check02("fontA")
check03("fontA")
check01("fontB")
check02("fontB")
check03("fontB")
check01("fontC")
check02("fontC")
check03("fontC")
```

with `-o "*check"`

```
check01("fontA")
check01("fontB")
check01("fontC")
check02("fontA")
check02("fontB")
check02("fontC")
check03("fontA")
check03("fontB")
check03("fontC")
```

In the second example you have all executions of a check in direct succession. It could be easier to read/interpret your result's, depending on your use case. 

I just had to make a small fix (PR in a minute) to make this argument work again.

Here's a command I just used to test:

```
$ fontbakery check-googlefonts  -v -o "*check" -c com.google.fonts/check/001 -c com.google.fonts/check/156 ../testfonts/RobotoSlab-*

[...]

Start ... running 8 individual check executions.
>> com.google.fonts/check/001 with ((u'font[0]', '../testfonts/RobotoSlab-Bold.ttf'),)
   Checking file is named canonically.
 * PASS: ../testfonts/RobotoSlab-Bold.ttf is named canonically.

   Result: PASS

>> com.google.fonts/check/001 with ((u'font[1]', '../testfonts/RobotoSlab-Light.ttf'),)
   Checking file is named canonically.
 * PASS: ../testfonts/RobotoSlab-Light.ttf is named canonically.

   Result: PASS

>> com.google.fonts/check/001 with ((u'font[2]', '../testfonts/RobotoSlab-Regular.ttf'),)
   Checking file is named canonically.
 * PASS: ../testfonts/RobotoSlab-Regular.ttf is named canonically.

   Result: PASS

>> com.google.fonts/check/001 with ((u'font[3]', '../testfonts/RobotoSlab-Thin.ttf'),)
   Checking file is named canonically.
 * PASS: ../testfonts/RobotoSlab-Thin.ttf is named canonically.

   Result: PASS

>> com.google.fonts/check/156 with ((u'font[0]', '../testfonts/RobotoSlab-Bold.ttf'),)
   Font has all mandatory 'name' table entries ?
 * PASS: Font contains values for all mandatory name table entries.

   Result: PASS

>> com.google.fonts/check/156 with ((u'font[1]', '../testfonts/RobotoSlab-Light.ttf'),)
   Font has all mandatory 'name' table entries ?
 * PASS: Font contains values for all mandatory name table entries.

   Result: PASS

>> com.google.fonts/check/156 with ((u'font[2]', '../testfonts/RobotoSlab-Regular.ttf'),)
   Font has all mandatory 'name' table entries ?
 * PASS: Font contains values for all mandatory name table entries.

   Result: PASS

>> com.google.fonts/check/156 with ((u'font[3]', '../testfonts/RobotoSlab-Thin.ttf'),)
   Font has all mandatory 'name' table entries ?
 * PASS: Font contains values for all mandatory name table entries.

   Result: PASS

[...]
```

**Comment by madig** [comment]
Ok, that I understand. This needs to be in the docs :) Is there any particular reason the argument reads "*checks", etc.? I'd find something like `--order [each_check_all_fonts|each_font_all_checks]` easier to understand.

**Comment by graphicore** [comment]
> There are only two hard things in Computer Science: cache invalidation and naming things.

;-)

`*iterargs` and `*check` are special cases, I added the asterisk so that they are never confused with the names of any of `ITERATED_ARGS` (e.g. "font") which must be compatible with python parameter names  as we use them as parameters in the check/condition functions.

help says:

```
Despite the ITERATED_ARGS there are two special
values available:
"*iterargs" -- all remainig ITERATED_ARGS
"*check"     -- order by check
ITERATED_ARGS: font
A sections default is equivalent to: "*iterargs, *check".
```

When defining the `order` parameter, the first argument in the list is the one with the greatest effect on ordering, it's a bit boring if `ITERATED_ARGS` has only one item (usually `font`), but it is possible to define more than one iterated argument in a specification. Also, font doesn't have to be in a spec at all, it just happens that we use it a lot.

You can pick all items of `ITERATED_ARGS` and `*check` and `*iterargs` to set up the order argument, so, if `ITERATED_ARGS : font, template`(maybe we have a list of templates that we want to use with the fonts, just a silly example, we could write the order like this:

```
-o "template, *check"
```

this is equivalent (and automatically expanded) to:

```
-o "template, *check, *iterargs"
```

and `*iterargs` is resolved to `ITERATED_ARGS - ALREADY_USED_ITERATED_ARGS`, thus it is equivalent to:

```
-o "template, *check, font"
```

A similar example:


```
-o "template"
```

this is equivalent (and automatically expanded adding` *iterargs` and `*check`) to:

```
-o "template, *iterargs, *check"
```

and this is equivalent to (`*iterargs` here still contains `['font']`):

```
-o "template, font, *check"
```

One downside is, that we can't set an ordering that leaves the section boundaries, i.e. we should probably make a `*section` special argument work, so when applied to the end of the order list, the section would have no effect. But that's unfortunately some work to do when taking care of not breaking things.

**Comment by graphicore** [comment]
Not exactly, it needs to know how many items are in `fonts` not the value of the items. It looks at the parameters used by the checks as well. So, if a check uses two parameters that are iterargs, a check is executed: `len(iterargsA) * len(iterargsB)` times. The question is whether to iterate over `iterargsB` first and then over `iterargsA` or the other way around.

```
for ia in range(0, len(iterargsA)):
  for ib in range(0, len(iterargsB)):
    check(iterargsA[ia], iterargsB[ib])

# check(iterargsA[0], iterargsB[0])
# check(iterargsA[0], iterargsB[1])
# check(iterargsA[0], iterargsB[2])
# check(iterargsA[1], iterargsB[0])
# check(iterargsA[1], iterargsB[1])
# check(iterargsA[1], iterargsB[2])

# OR 

for ib in range(0, len(iterargsB)):
  for ia in range(0, len(iterargsA)):
    check(iterargsA[ia], iterargsB[ib])


# check(iterargsA[0], iterargsB[0])
# check(iterargsA[1], iterargsB[0])
# check(iterargsA[0], iterargsB[1])
# check(iterargsA[1], iterargsB[1])
# check(iterargsA[0], iterargsB[2])
# check(iterargsA[1], iterargsB[2])

```

Maybe you want to follw the `checkrunner.order` getter and ask more detailed questions about the implementation when you get stuck?

**Comment by anthrotype** [comment]
haven't followed the discussion, just wanted to say there's https://docs.python.org/3/library/itertools.html#itertools.product to do nested for-loops like that
(sorry for the interruption)

**Comment by graphicore** [comment]
> (sorry for the interruption)

NP. That was to illustrate how the algorithm works, it is not the implementation.

**Comment by anthrotype** [comment]
Sure sure! I like to play the python police when I'm bored :)
:snake: :policeman:
