### ISSUE TITLE
Revise 'wght' axis values checks

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1920]
I raised issue #1716 when I didn't fully understand how variable font axises work.  For the weight axis, I believed that the axis values should match OS/2 usWeightClass values...this often isn't possible for interpolated instances. Here's a quick scenario, we'll use a family with 2 masters and 3 instances:

Masters:
Light = 300 (same as OS/2 val)
Bold = 700 (same as OS/2 val)

Instances:
Light = 300 (same as master)
Reg = 500 (halfway between light and bold)
Bold = 700 (same as master)

If the designer was to set the Regular instance's value to the same as the OS/2's Reg value, 400, it may be visually too light for them.

We should actually be testing whether font-weight css values on variable fonts return the same visual appearance as an instance from the static family. Getting this to work involves using an [avar](https://docs.microsoft.com/en-us/typography/opentype/spec/avar) table.

I'm currently testing this visually using https://github.com/googlefonts/tools/blob/master/bin/gftools-check-vf-avar.py. It will produce an overlay of a variable font vs a static family.

![vollkorn](https://user-images.githubusercontent.com/7525512/41535484-6563722c-72fa-11e8-8a58-7cde69dc705e.png)

**Comment by felipesanches** [comment]
I've spent some time this week on this and inspected a few fonts using ttx. I think I partially understood the problem but I'd appreciate if you could describe in more detail how the avar table would be setup to address the problem, @m4rc1e.

**Comment by felipesanches** [comment]
ping, @m4rc1e

**Comment by m4rc1e** [comment]
In my opening post, I wrote:

> For the weight axis, I believed that the axis values should match OS/2 usWeightClass values

My original assumption is actually correct. We **do want** fvar wght axis values to match the OS/2 usWeightClass. An avar table can be used in order to achieve this, https://docs.microsoft.com/en-us/typography/opentype/spec/avar.

I guess my main concern was ensuring that the VF instances have the same visual weight appearance as their static counterparts. Imo this is more of a regression problem. I currently check this using font diffenator and diff browsers.

Since we already have a VF instance coordinate [check](https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/profiles/googlefonts.py#L3695), I'm closing this issue.

**Comment by felipesanches** [comment]
thanks, @m4rc1e !

**Comment by m4rc1e** [comment]
An interesting check would be to ensure that the avar is correct. I guess we could compare the gvar coordinates against the desired fvar results. I need to dig a bit deeper on this.

**Comment by felipesanches** [comment]
Please consider opening an issue about that when you have the time.
