### ISSUE TITLE
Filter MS Font Val result status

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1924]
## Observed behaviour

Marc posted https://github.com/googlefonts/OswaldFont/pull/11 today and the results are a bit misleading, because the "FAILS" were really just "WARN" level things.

I propose that we "filter" the MSFontVal results to change the check level status, where we rate it differently to what is provided. 

## Expected behaviour

Two checks are for sure WARNs not FAILs. 

First example:

> The xAvgCharWidth field does not equal the calculated value DETAILS: actual = 436, calc = 338

Second example:

> There are undefined bits set in fsSelection field DETAILS: Bit(s) 7

**Comment by felipesanches** [comment]
yeah... I can build the code infrastructure for that, but then we'll need to gradually feed it with rules for re-evaluating statuses based on our own taste :-)

**Comment by HinTak** [comment]
The first example was already fixed some months ago, but post 2.1 so you need to build from git head to get the fix.

**Comment by felipesanches** [comment]
We already have the filtering code. We can continue adding more special cases whenever needed.
