### ISSUE TITLE
please add instructions for getting ftxvalidator to the Mac installation instructions 

### ISSUE THREAD

**Issue by cjchapman** [googlefonts/fontbakery#1927]
Please add instructions for getting `ftxvalidator` to the Mac OS X installation instructions in the README.md file, in the "Additional dependencies" section.

e.g. a link to:
https://developer.apple.com/fonts/
and a note to click on "Download the Apple Font Tool Suite"

Thanks!

**Comment by felipesanches** [comment]
hi, @cjchapman, I'll look into this. Thanks for reporting.

**Comment by davelab6** [comment]
Felipe, I put instructions in the ProjectChecklist file that you can copy
from

**Comment by felipesanches** [comment]
I have used the instructions suggested by Dave. If you think it can be improved, let us know because we may want to update it both in the README.md file of this repo as well as at https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md#apple-os-x-font-tools

@cjchapman Feel free to re-open the issue if further rewording is eventually needed.

**Comment by cjchapman** [comment]
@felipesanches Those instructions seem more complicated and less beginner friendly than what I did. Starting at the download part of the instructions, I think I just:
* downloaded `Font_Tools_for_Xcode_9.dmg`
* double-clicked on `Font_Tools_for_Xcode_9.dmg`
* double-clicked on `macOS Font Tools.pkg`
* followed the GUI's instructions to install the tools (e.g. click "continue", "agree", "install", etc.)

When it was done, `ftxvalidator` was in my path at `/usr/bin/ftxvalidator` and Font Bakery seems to be able to find and use it.

I don't know if it's worth re-opening the issue for this, so I'll leave it to you to decide.

**Comment by davelab6** [comment]
Thanks @cjchapman - I agree that the details I collected were not beginner friendly :) I've updated with your notes - thank you!!
