### ISSUE TITLE
please add instructions for using Microsoft Font Validator with Font Bakery on the Mac

### ISSUE THREAD

**Issue by cjchapman** [googlefonts/fontbakery#1928]
Please add instructions in the Mac OS X section of the readme for using Microsoft Font Validator with Font Bakery on the Mac.

I've downloaded Hin-Tak's Mac command-line version of Microsoft Font Validator, and put it in my path, but Font Bakery doesn't seem to detect it.

Thanks!

**Comment by felipesanches** [comment]
hi, @cjchapman, I'll look into this. Thanks for reporting.

**Comment by laerm0** [comment]
@davelab6 assigned this one to me, @felipesanches, so I am on it.

**Comment by felipesanches** [comment]
Great! Thanks!

**Comment by laerm0** [comment]
Hi @cjchapman, a question for you: downloading the binary [here](https://sourceforge.net/projects/hp-pxl-jetready/files/Microsoft%20Font%20Validator/FontVal-2.1.1-osx-10.7-x64.tgz/download) works fine for me. It's the non-GUI version and it runs fine on OS X without any additional dependencies. Can you check and see if it works for you? Thanks.

**Comment by eliheuer** [comment]
I copied `FontValidator` from the above link to `/usr/local/bin/` but still get an error from `fontbakery`:

```
>> com.google.fonts/check/037 with (('font[0]', 'variable_ttf/Dosis-VF.ttf'),)
   Checking with Microsoft Font Validator.
 * ERROR: Failed with FileNotFoundError: [Errno 2] No such file or directory: 'variable_ttf/Dosis-VF.ttf.report.xml'
           File "/Users/Air/Type/Tools/Source/fontbakery/Lib/fontbakery/checkrunner.py", line 347, in _exec_check_generator
             for sub_result in gen:

   Result: ERROR
``` 

Looks like it should make a XML report but isn't?

**Comment by graphicore** [comment]
> Looks like it should make a XML report but isn't?

It can't find the xml file that it is expecting, looking at `variable_ttf/Dosis-VF.ttf.report.xml`.

**Comment by cjchapman** [comment]
@laerm0 Hi Micah, sorry, I somehow missed your question until now. I'm able to download & run Microsoft Font Validator on my Mac just fine when I run it directly, but Font Bakery doesn't seem to detect it.

**Comment by cjchapman** [comment]
@laerm0 OK, so I downloaded the specific version you linked, added `~/FontVal-2.1.1-osx-10.7-x64/FontVal-2.1.1-osx-10.7-x64/` to my path, and tried Font Bakery again. The message I get from Font Bakery is:
```
cchapman-macOS:temp cchapman$ FontBakery check-opentype NotoSansDevanagari-Regular.ttf
Start ... running 55 individual check executions.
>> com.google.fonts/check/037 with ((u'font[0]', 'NotoSansDevanagari-Regular.ttf'),)
   Checking with Microsoft Font Validator.
 * ERROR: Mono runtime and/or Microsoft Font Validator are not available!
 * ERROR: Failed with OSError: [Errno 2] No such file or directory
           File "/usr/local/lib/python2.7/site-packages/fontbakery/checkrunner.py", line 347, in _exec_check_generator
             for sub_result in gen:
         

   Result: ERROR
```
If I try running Font Validator from the command line without a path I get:
```
cchapman-macOS:temp cchapman$ FontValidator
Usage is: mono [options] program [program-options]

Development:
    --aot[=<options>]      Compiles the assembly to native code
    --debug[=<options>]    Enable debugging support, use --help-debug for details
    --debugger-agent=options Enable the debugger agent
    --profile[=profiler]   Runs in profiling mode with the specified profiler module
    --trace[=EXPR]         Enable tracing, use --help-trace for details
    --jitmap               Output a jit method map to /tmp/perf-PID.map
    --help-devel           Shows more options available to developers

Runtime:
    --config FILE          Loads FILE as the Mono config
    --verbose, -v          Increases the verbosity level
    --help, -h             Show usage information
    --version, -V          Show version information
    --runtime=VERSION      Use the VERSION runtime, instead of autodetecting
    --optimize=OPT         Turns on or off a specific optimization
                           Use --list-opt to get a list of optimizations
    --security[=mode]      Turns on the unsupported security manager (off by default)
                           mode is one of cas, core-clr, verifiable or validil
    --attach=OPTIONS       Pass OPTIONS to the attach agent in the runtime.
                           Currently the only supported option is 'disable'.
    --llvm, --nollvm       Controls whenever the runtime uses LLVM to compile code.
    --gc=[sgen,boehm]      Select SGen or Boehm GC (runs mono or mono-sgen)
    --arch=[32,64]         Select architecture (runs mono32 or mono64)
cchapman-macOS:temp cchapman$ 
```
If I try running it with an explicit path, I get:
```
cchapman-macOS:temp cchapman$ ~/FontVal-2.1.1-osx-10.7-x64/FontVal-2.1.1-osx-10.7-x64/FontValidator 
Usage: FontValidator [options]

Usage: FontValidator script.py args1 args2 ...
    ( Python mode when first arg ends with ".py" )

Version: 2.1.1

Options:
-file          <fontfile>      (multiple allowed)
+table         <table-include> (multible allowed)
-table         <table-skip>    (multiple allowed)
-all-tables    ("+all-tables" is an alias)
-only-tables
-quiet
-test-parms    <test-parms>.py
+raster-tests
-report-dir    <reportDir>
-report-stdout                 (="-stdout", implies -quiet)
-temporary-reports
-report-in-font-dir
-version

Valid table names (note the space after "CFF " and "cvt "):
BASE,CBDT,CBLC,CFF ,cmap,COLR,CPAL,cvt ,DSIG,EBDT,EBLC,EBSC,fpgm,gasp,GDEF,glyf,GPOS,GSUB,hdmx,head,hhea,hmtx,JSTF,kern,loca,LTSH,MATH,maxp,name,OS/2,PCLT,post,prep,SVG ,VDMX,vhea,vmtx,VORG

Example:
  FontValidator -file arial.ttf -file times.ttf -table 'OS/2' -table DSIG -report-dir ~/Desktop
  FontValidator ttx-l-example.py arial.ttf
cchapman-macOS:temp cchapman$ 
```
Help? Thanks!

**Comment by HinTak** [comment]
If I try running Font Validator from the command line without a path I get:




You have something else in your $PATH named "FontValidator". Can you show the result of `echo $PATH` , `which FontValidator`  , and `type FontValidator` please?
```
cchapman-macOS:temp cchapman$ FontValidator
Usage is: mono [options] program [program-options]
```

**Comment by cjchapman** [comment]
@HinTak:
```
cchapman-macOS:temp cchapman$ echo $PATH
~/FontVal-2.1.1-osx-10.7-x64/FontVal-2.1.1-osx-10.7-x64/:/usr/local/bin:/Users/cchapman/.cargo/bin:/usr/local/opt/python@2/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/cchapman/bin:/Users/cchapman/.gem/ruby/2.3.0/bin:/Users/cchapman/Library/Developer/Xcode/DerivedData/cts-shape-fczaxhsbzemgmzfiawwnflglituh/Build/Products/Debug:/usr/local/opt/icu4c/bin/
cchapman-macOS:temp cchapman$ which FontValidator
cchapman-macOS:temp cchapman$ type FontValidator
FontValidator is hashed (/Users/cchapman/FontVal-2.1.1-osx-10.7-x64/FontVal-2.1.1-osx-10.7-x64/FontValidator)
cchapman-macOS:temp cchapman$ 
```

**Comment by HinTak** [comment]
That's interesting - you have a literal `~/` in your $PATH. Normally it should be replaced by the value

**Comment by cjchapman** [comment]
@HinTak
Also, if I rename the FontValidator file in that folder, and then try to use  on the command line, I get:
```
cchapman-macOS:temp cchapman$ FontValidator
-bash: /Users/cchapman/FontVal-2.1.1-osx-10.7-x64/FontVal-2.1.1-osx-10.7-x64/FontValidator: No such file or directory
```
So it does seem to be looking in the same folder I am. I don't think there's anything else in my $PATH with that name.

**Comment by cjchapman** [comment]
@HinTak I set the path wrong, I had quotes around it in my `.bash_profile`. However, I still get `mono` after fixing it, i.e.:
```
cchapman-macOS:~ cchapman$ echo $PATH
/Users/cchapman/FontVal-2.1.1-osx-10.7-x64/FontVal-2.1.1-osx-10.7-x64/:/usr/local/bin:/Users/cchapman/.cargo/bin:/usr/local/opt/python@2/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/cchapman/bin:/Users/cchapman/.gem/ruby/2.3.0/bin:/Users/cchapman/Library/Developer/Xcode/DerivedData/cts-shape-fczaxhsbzemgmzfiawwnflglituh/Build/Products/Debug:/usr/local/opt/icu4c/bin/
cchapman-macOS:~ cchapman$ FontValidator
Usage is: mono [options] program [program-options]
...
cchapman-macOS:~ cchapman$ which FontValidator
/Users/cchapman/FontVal-2.1.1-osx-10.7-x64/FontVal-2.1.1-osx-10.7-x64//FontValidator
cchapman-macOS:~ cchapman$ type FontValidator
FontValidator is hashed (/Users/cchapman/FontVal-2.1.1-osx-10.7-x64/FontVal-2.1.1-osx-10.7-x64/FontValidator)
cchapman-macOS:~ cchapman$ 
```

**Comment by HinTak** [comment]
This is wierd. Wonder where the reference to mono comes from.

**Comment by cjchapman** [comment]
```
cchapman-macOS:FontVal-2.1.1-osx-10.7-x64 cchapman$ cp FontValidator ThisIsAnExperimentForHinTak
cchapman-macOS:FontVal-2.1.1-osx-10.7-x64 cchapman$ cd ~/temp
cchapman-macOS:temp cchapman$ ~/FontVal-2.1.1-osx-10.7-x64/FontVal-2.1.1-osx-10.7-x64/ThisIsAnExperimentForHinTak
Usage: FontValidator [options]
...
cchapman-macOS:temp cchapman$ ThisIsAnExperimentForHinTak
Usage is: mono [options] program [program-options]
...
```

**Comment by cjchapman** [comment]
```
cchapman-macOS:temp cchapman$ echo $PATH
/Users/cchapman/FontVal-2.1.1-osx-10.7-x64/FontVal-2.1.1-osx-10.7-x64
cchapman-macOS:temp cchapman$ ThisIsAnExperimentForHinTak | /usr/bin/head -1
Usage is: mono [options] program [program-options]
cchapman-macOS:temp cchapman$ /Users/cchapman/FontVal-2.1.1-osx-10.7-x64/FontVal-2.1.1-osx-10.7-x64/ThisIsAnExperimentForHinTak | /usr/bin/head -1
Usage: FontValidator [options]
cchapman-macOS:temp cchapman$ 
```

**Comment by eliheuer** [comment]
@davelab6 @cjchapman testing

**Comment by cjchapman** [comment]
Correction, I'm getting other notifications from this project, but not from this particular issue. I've just tried unsubscribing from the issue and then resubscribing to it in case it helps.

**Comment by HinTak** [comment]
That, running the same binary with or without explicit path gives different results, is a bit screwy. I'll have a look around mono places for some answers.

**Comment by kontur** [comment]
Just writing to confirm I get the same behavior, thus equally stuck on running that test:

```
$ which FontValidator
/usr/local/bin/FontValidator
$ FontValidator
Usage is: mono [options] program [program-options]
...
```

**Comment by m4rc1e** [comment]
Can't we just get the user to install MS Font Validator and add it to their path as `FontValidator`? 

We could write a shell script to do this:
- Determine what OS the user has
- Download the OS specific version of Font Validator.
- Include it in the user's path as `FontValidator`.


We could then replace the `Fontvalidator.exe` subprocess command with `FontValidator`. We'd now have an implementation which is platform agnostic.

@felipesanches Are we still using your 'danger fork' of Font Validator?.

@laerm0 I'd be happy to take this task over.

In the future, I'm in favour of deprecating this dependency. I only seem to use the glyf checks anyway.

**Comment by davelab6** [comment]
Felipe is now on vacation until ATypI but this is super important imho

**Comment by anthrotype** [comment]
wow I just tried this and it's super weird.. It's true, when run with the explicit filename it works, whereas when run like a normal executable in the $PATH as "FontValidator" it shows the usage of mono itself.

@HinTak I'm curious, how did you create the self-contained mac FontValidator executable?

**Comment by anthrotype** [comment]
this maybe? https://www.mono-project.com/docs/tools+libraries/tools/mkbundle/

**Comment by m4rc1e** [comment]
I see.

I've always used the FontValidator which is bundled with this repo, https://github.com/googlefonts/fontbakery/blob/master/prebuilt/fval/FontValidator.exe.

I then patch the check which calls it... it's a terrible solution ;-)

@felipesanches can we make time to discuss a good solution for this at AtypI?

**Comment by anthrotype** [comment]
Disclaimer: I know nothing about C# or mono.
I just tried to compile a hello_world.cs with mono (installed via homebrew on macOS 10.12), and used mkbundle to create a self-contained executable, `mkbundle -o hello --simple hello.exe`.
It seems to be working both if I run it as in `./hello` (with the filename) or if I add its folder to my $PATH, change directory to somewhere else just in case, and run it as unqualified `hello`.
So this might just be a packaging problem with the version Hin-Tak uploaded.

**Comment by HinTak** [comment]
The actual command which I used is (running inside the post-build "bin" directory):

```
MONO_PATH=. mkbundle -v --i18n all --cross mono-4.8.0-osx-10.7-x64.zip -o FontVal-2.1.1-py-osx-10.7-x64/FontValidator       FontValidator.exe  IronPython.Modules.dll --library Darwin/libfreetype.6.dylib                           --library libfreetype6.dylib,Darwin/libfreetype.6.dylib
```

Note that mono 5.x is buggy - issue filed as https://bugzilla.xamarin.com/show_bug.cgi?id=59076 .

**Comment by HinTak** [comment]
```
> In the future, I'm in favour of deprecating this dependency. I only seem to use the glyf checks anyway.
```

The bulk of FontVal's C# code *is* the glyf test. The main module which implements the glyf test, `Glyph` and `GMath` (which are only used by the the glyf test), is 17% of FontVal's codebase, so saying FontVal is about one-third glyf test is about correct.

(excluding the large language look-up tables in Compat. Those are auto-generated.).

```
$ find Compat/cp* Compat/dbcs* -type f -name '*.cs' -exec cat {} \; | wc -l
143516
[Hin-Tak@localhost Font-Validator-up]$ find . -type f -name '*.cs' -exec cat {} \; | wc -l
226492
$ find GMath/ Glyph/ -type f -exec cat {} \; | wc -l
14349
$ python
...
>>> 226492 - 143516
82976
>>> 14349.0 / 82976
0.17292952178943308
>>> 
```

As I said, a font is mainly glyphs.

**Comment by HinTak** [comment]
Note also that mkbundle was substantially rewritten in mono 4.8.x. This was mentioned briefly in the release note of FontVal 2.1. Thus, mono 5.x is buggy (and another bug affecting ironpython), and mono below 4.8 does not have the required change in mkbundle, the only version of mono you should use for FontVal development is exactly mono 4.8.x, and no other versions.

This does not affect end-users. Just in case you want to contribute to FontVal development - still hoping my breath on it happening at all :-).

**Comment by HinTak** [comment]
Issue filed upstream and with suggested code location to fix - 
https://github.com/mono/mono/issues/10470#issuecomment-418540482 . Have a go at fixing it if any of you feel so inclined.

Meanwhile, basically mkbundled executable needs to know its own location in `argv[0]`. This means any of these works:

- full path (i.e. `/home/myname/someplace/...`)
- relative path (i.e. `./someplace/...` )
- current directory

but it doesn't know where itself is, if it is called via putting it someplace in $PATH then calling its basename.

The pre-4.8.0 way of mkbundle did work with basename calling via $PATH, but had some other problems... (well, you can read the commit referenced above for why/how it was changed for mono 4.8.x).

**Comment by HinTak** [comment]
The fix is in mono 5.12+ . So re-packaging with a recent mono 5.x (current 5.14) should do. However as I said there were a few important problems with early mono 5.x . So I 'd rather backported the fix - which seems obvious /isolated and straightforward to mono 4.8 and rebuild. Until I upgrade to a late 5.x for development myself, the best thing to do is perhaps ask the mono people to release a 4.8.2 with the fix.

**Comment by HinTak** [comment]
Tagged and packaged FontVal 2.1.2 with mono 5.14 - 
https://github.com/HinTak/Font-Validator/releases/tag/FontVal-2.1.2 - for this issue. This is basically a snapshot build with very little testing. YMMV.

Problems with running FontVal with mono 5.x should go to https://github.com/Microsoft/Font-Validator/issues/53 .

In the last day or so I have filed https://github.com/mono/mono/issues/10478 , https://github.com/mono/mono/issues/10479 , https://github.com/mono/mono/issues/10489 , https://github.com/mono/mono/issues/10490 , https://bugs.winehq.org/show_bug.cgi?id=45782 . They all have workarounds, etc but nonetheless a bit tiring, for this issue which has a number of workarounds.

I'd really like the next FontVal release to have https://github.com/HinTak/Font-Validator/issues/27 and https://github.com/Microsoft/Font-Validator/issues/49 fixed, as well as building with visual studio working (again), so I'd prefer not to do any release builds until then.

**Comment by HinTak** [comment]
@cjchapman @kontur : please get FontVal 2.1.2 .

**Comment by kontur** [comment]
Thanks, the FontValidator seem to work, eg:
```
$ FontValidator
Usage: FontValidator [options]

Usage: FontValidator script.py args1 args2 ...
    ( Python mode when first arg ends with ".py" )

Version: 2.1.2

Options:
-file          <fontfile>      (multiple allowed)
+table         <table-include> (multible allowed)
-table         <table-skip>    (multiple allowed)
-all-tables    ("+all-tables" is an alias)
-only-tables
-quiet
-test-parms    <test-parms>.py
-no-raster-tests
-report-dir    <reportDir>
-report-stdout                 (="-stdout", implies -quiet)
-temporary-reports
-report-in-font-dir
-version

Valid table names (note the space after "CFF " and "cvt "):
BASE,CBDT,CBLC,CFF ,cmap,COLR,CPAL,cvt ,DSIG,EBDT,EBLC,EBSC,fpgm,gasp,GDEF,glyf,GPOS,GSUB,hdmx,head,hhea,hmtx,JSTF,kern,loca,LTSH,MATH,maxp,name,OS/2,PCLT,post,prep,SVG ,VDMX,vhea,vmtx,VORG

Example:
  FontValidator -file arial.ttf -file times.ttf -table 'OS/2' -table DSIG -report-dir ~/Desktop
  FontValidator ttx-l-example.py arial.ttf
```

And just to confirm, the actual error running fontbakery (after updating just now) is:

```
>> com.google.fonts/check/037 with (('font[0]', 'fontymacfontface.otf'),)
   Checking with Microsoft Font Validator.
 * ERROR: Mono runtime and/or Microsoft Font Validator are not available!
 * ERROR: Failed with FileNotFoundError: [Errno 2] No such file or directory: 'FontValidator.exe': 'FontValidator.exe'
           File "/usr/local/lib/python3.6/site-packages/fontbakery/checkrunner.py", line 350, in _exec_check
             for sub_result in result:  # Might raise.
           File "/usr/local/lib/python3.6/site-packages/fontbakery/specifications/general.py", line 179, in com_google_fonts_check_037
             raise error
           File "/usr/local/lib/python3.6/site-packages/fontbakery/specifications/general.py", line 166, in com_google_fonts_check_037
             subprocess.check_output(fval_cmd, stderr=subprocess.STDOUT)
           File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
             **kwargs).stdout
           File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 403, in run
             with Popen(*popenargs, **kwargs) as process:
           File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
             restore_signals, start_new_session)
           File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
             raise child_exception_type(errno_num, err_msg, err_filename)


   Result: ERROR
```

Apparently looking for that `exe` still.

**Comment by anthrotype** [comment]
Thanks @HinTak!
@kontur I guess you could rename it to `FontValidator.exe` and then it should work.

**Comment by kontur** [comment]
@anthrotype 🤦‍♂️ yes, that works... didn't think of that

FontValidator tests running without errors, thanks for taking a look at this and providing those additional instructions and workarounds 👍

**Comment by HinTak** [comment]
Or, remove the `.exe` part in line 163 of
https://github.com/googlefonts/fontbakery/blob/302c00f18e173136c2e19af3d18172d34179797d/Lib/fontbakery/specifications/general.py

. That should do it.

Also, update the two lines, 115 and 112 to remove again the `.exe` part of the install instruction, and remove the whole paragraph about mono in:
https://github.com/googlefonts/fontbakery/blob/6212e589ceee84127c2db8185702dc91fa996851/INSTALL.md

**Comment by HinTak** [comment]
BTW, the windows command shell AFAIK can auto-append ".exe", ".bat" .  Windows users skip those parts all the time. 

So the correct cross-platform answer is simply to delete the ".exe" in the fontbakery code. NO need tablet have it. Just delete it would do.
