### ISSUE TITLE
MacOS: ots(OpenType Sanitizer), brew install and make fails

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#1934]
I'm trying to install the additional dependency `ots`.

ots builds fine for me on Ubuntu 18, but I haven't been able to install on MacOS 10.11 by following the provided instructions.

First I try installing with HomeBrew 1.6.9 + xcode-select version 2343 and GNU Make 3.81, like so...   
```
# install ots
brew tap bramstein/webfonttools;
brew update;
brew install ots --HEAD;
```
... and get the following error: 
```
Last 15 lines from /Users/eli/Library/Logs/Homebrew/ots/03.make:
      ots::OTSContext::~OTSContext() in ots_testfuzz-ots-fuzzer.o
      ...
  "___ubsan_vptr_type_cache", referenced from:
      _LLVMFuzzerTestOneInput in ots_testfuzz-ots-fuzzer.o
      ots::ExpandingMemoryStream::Seek(long long) in ots_testfuzz-ots-fuzzer.o
      ots::ExpandingMemoryStream::~ExpandingMemoryStream() in ots_testfuzz-ots-fuzzer.o
      ots::OTSContext::~OTSContext() in ots_testfuzz-ots-fuzzer.o
      _main in ots_testfuzz-ots-fuzzer.o
      std::__1::basic_ifstream<char, std::__1::char_traits<char> >::~basic_ifstream() in ots_testfuzz-ots-fuzzer.o
      ots::OTSContext::~OTSContext() in ots_testfuzz-ots-fuzzer.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [ots-testfuzz] Error 1
make: *** [all] Error 2
```
At this point, I try installing manually as is described in the ots readme [here](https://github.com/khaledhosny/ots/blob/master/INSTALL), but get the same error.

**Comment by felipesanches** [comment]
If you get the same problem while following the install instructions provided at the ots readme, then I'd say this is probably a problem to be reported upstream.

**Comment by felipesanches** [comment]
what do you think, @khaledhosny?

**Comment by eliheuer** [comment]
Ok, will do. Running `make` with `-stdlib=libstdc++` seems to have fixed it.

**Comment by felipesanches** [comment]
@eliheuer would you like to suggest better wording for our README.md then?

**Comment by eliheuer** [comment]
@felipesanches Yeah, when I have it working on MacOS I'll update the README and send a pull request.

**Comment by felipesanches** [comment]
great, thanks!

**Comment by khaledhosny** [comment]
See https://github.com/khaledhosny/ots/issues/151

**Comment by khaledhosny** [comment]
You can also try the OSX binaries I provide on GitHub releases.

**Comment by eliheuer** [comment]
@khaledhosny Thanks! I installed the binaries and that is working well so far. I'll just make a small update to the README suggesting this as an alternative method.

**Comment by felipesanches** [comment]
@eliheuer could you try https://github.com/khaledhosny/ots/issues/151#issuecomment-375872848 and perhaps also mention it on our README.md?

**Comment by eliheuer** [comment]
@felipesanches I wasn't able to get `--disable-fsanitize` to work, but will try adding it to the README if I do.

**Comment by felipesanches** [comment]
if you do, then please open a complementary pull request for that.

Thanks, @eliheuer!
