### ISSUE TITLE
Add check for named instances

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1952]
A variable font that is provided is an update to a prior set of static fonts, should have named instances for the old static styles. We should have some way to declare what the expected named instances are in a project. 

This is somewhat related to https://github.com/googlefonts/fontbakery/issues/1868, and other issues.

**Comment by felipesanches** [comment]
yes, I agree.

**Comment by davelab6** [comment]
https://github.com/kosbarts/Commissioner/issues/12 shows there are critical problems with the way this check is currently implemented.

**Comment by simoncozens** [comment]
This is done, remaining parts of the issue move to #2820.
