### ISSUE TITLE
com.google.fonts/check/032: name table descriptions length

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1956]
For Archivo, I get the following fail:

```
>> com.google.fonts/check/032 with ((u'font[0]', '/Users/marc/Documents/googlefonts/manual_font_cleaning/Archivo/Archivo/fonts/ttf/Archivo-Regular.ttf'),)
   Description strings in the name table must not exceed 100 characters.
 * FAIL: Namerecords with ID=10 (NAMEID_DESCRIPTION) are longer than 100 characters and should be removed.

```

In the MS nametable [spec](https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids), there is no mention of any limitation for this nameID.

As a side note, for nameID13 (license description) it is always over 100 characters if the font is ofl.

Can we make this nameID greater than 100 characters please?

**Comment by felipesanches** [comment]
**com.google.fonts/check/032** does not deal with nameID 13 (license description).

It does only enforce the max length of 100 chars (which I think was suggested by Dave) on nameID 10.

**Comment by m4rc1e** [comment]
@felipesanches my reference to nameID13 was just to illustrate that not all IDs are kept under 100 :-)

**Comment by felipesanches** [comment]
sure.

It is not clear to me why Dave originally suggested to keep nameid 10 not longer than 100 chars. (ifI recall correctly he did, but I may be mistaken about that)

It would be good to find out where the restriction comes from and document it as rationale metadata for this check.

This is clearly not specific to the opentype spec , so I am moving this check to the googlefonts spec.

**Comment by felipesanches** [comment]
the check was originally called `"name record 10s (descriptions) are reasonable?"` and included more requirements. It was split into smaller, simpler checks here: https://github.com/googlefonts/fontbakery/issues/975

**Comment by felipesanches** [comment]
@davelab6 introduced this max-length requirement back in July 2016:

![screenshot at 2018-07-05 11 13 47](https://user-images.githubusercontent.com/213676/42328416-b5d20f14-805d-11e8-99d7-31bf1e7ff102.png)

It seems that originally no nameID 10 was expected to be in a font file because there was a bug in FontLab that was copying complete copyright notice text into that name table entry. Maybe Dave's idea was to use the arbitrarily chosen length limit of 100 chars to distinguish such copyright notices from some legitimate use of the field. Can you confirm that, Dave?

**Comment by felipesanches** [comment]
https://github.com/googlefonts/fontbakery/commit/6d50c0179bc8c63e707f98bc49e124389d20073f

**Comment by m4rc1e** [comment]
Really appreciate you investigating this! your conclusion makes sense

**Comment by felipesanches** [comment]
@m4rc1e can you tell me which specific string is triggering this check today on Archivo?

**Comment by felipesanches** [comment]
yeah, that looks very much reasonable indeed!

**Comment by felipesanches** [comment]
I think we can do one of the following thigs:

* deprecate the check
* increase the max-length requirement
* do you have any other idea?

If we keep the check then it would be good to document the rationale and probably it would be nice to learn in more details what was the actual FontLab bug like. (i.e. what s the typical size of such copyright notices?)

**Comment by felipesanches** [comment]
Also, did we have any font in the Google Fonts collection affected by this bug at somepoint?

Even if we didn't I still find it useful to keep the check as a safety net against some future user who may be using the old bugged FontLab version.

**Comment by m4rc1e** [comment]
I can't remember any off the top of my head I'm afraid.

**Comment by davelab6** [comment]
I don't want to bloat the filesize with this string being long. But that is
maybe more warn than fail.

And it should be in a gf file not a name.py file

I absolutely want to check and strip misplaced copyright notices.

**Comment by felipesanches** [comment]
The Archivo description string has 199 chars. I think it is reasonable to update the max-length to 200 chars then. And I will also make the check emit WARNs instead of FAILs when such length is exceeded.
