### ISSUE TITLE
MacOS: FontBook specimen for variable fonts shows (null)

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#1958]
## Observed behaviour

![fontmake-vf](https://user-images.githubusercontent.com/5162664/42351755-ace7298a-8084-11e8-8da8-7bc7676f0c5d.png)

## Expected behaviour

![input-mono](https://user-images.githubusercontent.com/5162664/42351760-b1b10224-8084-11e8-8c86-d4b822778c52.png)

What is going on here? Is this something FontBakery could test for and help fix?

**Comment by davelab6** [comment]
To confirm, is that input mono a VF?

I'm not sure where Font Book gets it's strings from. I wonder if it uses
the sample text strings in the name table. I know it uses the os/2 table
code page values for the Finder preview image.

**Comment by davelab6** [comment]
Sure thing! I guess until you figure out a fix it's not possible for Felipe
to write a check

**Comment by m4rc1e** [comment]
Which version of Mac OS X? if it's < 10.13.5, try restarting fontbook.

This is how it looks for me on 10.13.5

![screen shot 2018-07-06 at 08 47 12](https://user-images.githubusercontent.com/7525512/42366469-32b1268c-80f9-11e8-8e58-3e502cd01848.png)

**Comment by m4rc1e** [comment]
![screen shot 2018-07-06 at 08 47 46](https://user-images.githubusercontent.com/7525512/42366511-453faac6-80f9-11e8-9bc2-ed3d9a06af00.png)

Nothing wrong with any VF fonts in Font Book v 8.0 (314.1)

**Comment by anthrotype** [comment]
Marc, I think you are looking at a different view, the info panel instead of the default string preview. Click the first button at the top on the left hand side.

**Comment by m4rc1e** [comment]
@anthrotype thanks. Still lgtm

![screen shot 2018-07-06 at 09 21 18](https://user-images.githubusercontent.com/7525512/42368072-fd5fc0f6-80fd-11e8-94f8-bc8bd338a3d2.png)

**Comment by eliheuer** [comment]
Thanks Mark. I'm on 10.11, I've been holding out for the year of the Linux desktop, but I guess I'll need to upgrade this weekend. :-)

Feel free to close this issue.

**Comment by eliheuer** [comment]
I updated to 10.13.6 and variable fonts are working as expected in FontBook now.

**Comment by davelab6** [comment]
Thanks Eli!
