### ISSUE TITLE
Go Python 3.6+ only

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#1961]
http://python3statement.org/

I'd say it is soon time to drop Python 2 support. That would allow some code clean-up and eases maintenance.

**Comment by davelab6** [comment]
Since FB isn't used by GF staff eng team today, it would be fine to do this
now I think.

**Comment by davelab6** [comment]
Currently, by the time the staff engineers touch the files, the files are
presumed good; FB is used by the contractors that Google works with to
prepare fonts for onboarding into the API.

**Comment by felipesanches** [comment]
I reviewed the code and it looks good (and safe) to merge.

**Comment by davelab6** [comment]
I'm happy to see this :)

**Comment by felipesanches** [comment]
yeah. Me too. The full rationale for my code review was posted at https://github.com/googlefonts/fontbakery/pull/1980#issuecomment-407043124

> OK. Initially I felt worried about touching so many files (57) at once. But now I finished reviewing the full set of changes and the bulk of it is changing the string formatting code-style. That's nice. This new syntax makes it more readable and possibly easier to write as well.
> 
> My other worry was related to introducing bugs. We have a test suite with still only 60% code coverage, so it is not guaranteed it will catch all possible new problems. But the fact that I read the full change-set above and did not notice anything too unconventional, makes me feel safe to move on now and merge this.
> 
> Thanks, @madig and @hugovk

**Comment by madig** [comment]
Keep in mind that even a 100% coverage just means that every line of code got executed at least once, it does not mean that the code has no bugs. I think one would need quantum computers to test every possible state of a program.
