### ISSUE TITLE
USAGE.md link is broken in the main README

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#1962]
## Observed behaviour

USAGE.md link now points to: [https://github.com/googlefonts/fontbakery/blob/master/USAGE.md](https://github.com/googlefonts/fontbakery/blob/master/USAGE.md)
But should point to: [https://github.com/googlefonts/fontbakery/blob/master/docs/USAGE.md](https://github.com/googlefonts/fontbakery/blob/master/docs/USAGE.md)

**Comment by felipesanches** [comment]
thanks!

fixed at https://github.com/googlefonts/fontbakery/commit/5d30578b69b1335164fa665cce28ed4f04b68e68
