### ISSUE TITLE
com.google.fonts/check/020: ERROR: Failed with TypeError

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#1964]
## Observed behaviour

On MacOS 10.13 I get an error when running `com.google.fonts/check/020` on a variable font.

I'm using fontbakery `0.4.2.dev74+ga11a11fb` installed in editable mode.

**Comment by davelab6** [comment]
@eliheuer what is the output you see?

**Comment by eliheuer** [comment]
I just tested this with a `pip2` installed `fontbakery` in a `virtualenv` and I no longer get the error. This is a Python3 support issue.
