### ISSUE TITLE
com.google.fonts/check/054: TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#1965]
## Observed behaviour

On MacOS 10.13 I get an error when running com.google.fonts/check/054 on a variable font.

```
>> com.google.fonts/check/054 with (('font[0]', 'fonts/Dosis-VF.ttf'),)
   Show hinting filesize impact.
 * ERROR: The condition <FontBakeryCondition:ttfautohint_stats> had an error: TypeError: cannot use a string pattern on a bytes-like object
           File "/Users/Air/Type/Tools/Source/fontbakery/Lib/fontbakery/checkrunner.py", line 423, in _evaluate_condition
             return None, condition(**args)

   Result: ERROR
```
## Resources and exact process needed to replicate

I'm using fontbakery 0.4.2.dev74+ga11a11fb installed in editable mode.

The font used was fontmake output from(cdd0a5e): https://github.com/eliheuer/Dosis/blob/vf-mastering/fonts/Dosis-VF.ttf

**Comment by felipesanches** [comment]
yes, I was able to replicate that on GNU/Linux with python3 (works fine with python2):
![screenshot at 2018-07-12 15 51 30](https://user-images.githubusercontent.com/213676/42653303-9ff4be42-8604-11e8-8ad6-c5a72ccfbe33.png)

**Comment by davelab6** [comment]
Since this is a VF issue, I'm putting it to the 0.4.3 milestone (so while urgent, its more urgent to get the next release out :)

**Comment by eliheuer** [comment]
Yes, I just tested this with a `pip2` installed `fontbakery` in a `virtualenv` and I no longer get the error. This is a Python3 support issue.

**Comment by davelab6** [comment]
Oh @felipesanches is fast, he already has a PR to fix it :)

**Comment by felipesanches** [comment]
done! ;-)

**Comment by felipesanches** [comment]
sometimes things are easy :-D
