### ISSUE TITLE
com.google.fonts/check/056: TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#1966]
## Observed behaviour

On MacOS 10.13 I get an error when running com.google.fonts/check/056 on a variable font.

```
>> com.google.fonts/check/056 with (('font[0]', 'fonts/Dosis-VF.ttf'),)
   Font has old ttfautohint applied?
 * ERROR: The condition <FontBakeryCondition:ttfautohint_stats> had an error: TypeError: cannot use a string pattern on a bytes-like object
           File "/Users/Air/Type/Tools/Source/fontbakery/Lib/fontbakery/checkrunner.py", line 423, in _evaluate_condition
             return None, condition(**args)
         

   Result: ERROR
```

## Resources and exact process needed to replicate

I'm using fontbakery 0.4.2.dev74+ga11a11fb installed in editable mode.

The font used was fontmake output from(cdd0a5e): https://github.com/eliheuer/Dosis/blob/vf-mastering/fonts/Dosis-VF.ttf

**Comment by davelab6** [comment]
Likely similar to #1965

**Comment by eliheuer** [comment]
I just tested this with a `pip2` installed `fontbakery` in a `virtualenv` and I no longer get the error. This is a Python3 support issue.

**Comment by felipesanches** [comment]
this is exactly the same as #1965 so it is fixed by that pull-request as well.
