### ISSUE TITLE
CHECK/056: Am I getting an unnecessary version warning for ttfautohint?

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#1969]
## Observed behaviour

I installed a new version of `ttfautohint` with homebrew on MacOS 10.13
```
brew install ttfautohint
```
I then run `ttfautohint` followed by `fontbakery`
```
ttfautohint Font-VF.ttf Font-VF-ah.ttf --verbose
fontbakery check-googlefonts Font-VF-ah.ttf 
```
And then I see the following warning.
```
>> com.google.fonts/check/056 with ((u'font[0]', 'Font-VF-ah.ttf'),)
   Font has old ttfautohint applied?
 * WARN: ttfautohint used in font = 1.8.1; installed = 1.8.1; Need to re-run with the newer version!

   Result: WARN
```
## Expected behaviour

It isn't clear to me if this is an error or what the next step is, I used the newest version from `brew` and I have that same version installed.

Looking at the freetype website, `1.8.1` seems to be the newest version: https://www.freetype.org/ttfautohint/#download

**Comment by felipesanches** [comment]
I said "may even fix #1969" and github auto-closed the issue :-P

But I still need to verify this...

**Comment by davelab6** [comment]
> WARN: ttfautohint used in font = 1.8.1; installed = 1.8.1; Need to re-run with the newer version!

Hmm, that suggests to me that the check is comparing version found in font with version installed.... but version installed may be stale. 

So there needs to be another aspect of the check, to find out if the ttfautohint available locally is the latest version, and if it isn't, tell the user to upgrade.

**Comment by eliheuer** [comment]
I pulled the update from #1971 and I'm no longer getting this warn, but it looks like we should keep this issue open until `fontbakery` can check if there is a new remote version available.
