### ISSUE TITLE
Double check NAME table checks are working correctly, using Open Sans, Roboto, Roboto Slab

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1974]
@felipesanches Per https://github.com/google/fonts/issues/1618 could you check these families, using the versions available in the API? :)

**Comment by felipesanches** [comment]
The conversation at https://github.com/google/fonts/issues/1618 in unclear at the moment.

**Comment by mjlagattuta** [comment]
I tested this with Font Bakery via the command line (using check 157) and it successfully detects the error in the name table of Roboto Slab Thin and results in a 'FAIL'

Perhaps I'm missing something, but it Font Bakery is already detecting this issue, what fix is needed?

**Comment by mjlagattuta** [comment]
The OT spec recommends (for PlatformID3, i.e. Windows) that for families with styles other than Regular, Italic, Bold, and Bold Italic, the NameID2 (Font Subfamily Name) entry should be Regular, and if this is the case, to also include NameID's 16 and 17 (Typographic Family Name, and Typographic Subfamily Name)

Perhaps this could be added to this check to make it more complete?

**Comment by felipesanches** [comment]
any further insights here?

I'll probably look closer tomorrow

**Comment by felipesanches** [comment]
This is not MFDOS specific, so I'll move on with the 0.5.1 release.

(see also: https://github.com/google/fonts/issues/1618#issuecomment-409013611 - closing this issue will require a bit more conversation to clarify the proper name entry rules)

**Comment by felipesanches** [comment]
The commits listed above address most of the issues pointed out by @mjlagattuta at https://github.com/google/fonts/issues/1618#issuecomment-425948569

There's only a couple more code-tests that we need to add to checks 161 and 162 before having full coverage of the name table checking routines.

**Comment by felipesanches** [comment]
"Checks 161 and 162 check for proper entries at nameID 16 and 17 respectively."

**Comment by felipesanches** [comment]
Now we've got code-tests for all checks that deal with name table rules.
If we ever find bad behaviors on name-table related checks we must discuss them based on the requirements codified in the code-tests. And if those requirements are incorrect then changing the code-tests to what is actually expected will guide us when fixing bugs on the actual font checks.
