### ISSUE TITLE
Check/065: can't resolve WARN for N_o having no kerning, is this a bug?

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#1977]
## Observed behaviour

Testing Dosis ( https://github.com/eliheuer/Dosis/commit/fb1e2a004fcb93e5437653dae09a7c1cc8e8dda6 ) with `fontbakery` I was able to resolve all `Check/065 WARNs` except one, `N_o`. I'm not sure why `Fontbakery` thinks `N_o` needs kerning, but just as a test I added some and still got the `WARN`. This makes me think this could be a bug of some kind. 

## Expected behaviour

No `WARN` for `N_o` not having kerning.

See: http://35.225.170.228/report/b7fce055-e572-4d11-bb46-4d0cf2516011

**Comment by davelab6** [comment]
Isn't that a character, not a ligature?

**Comment by felipesanches** [comment]
@eliheuer I am trying to load the fontbakery dragndrop you referenced by URL, but it seems to be offline (or having some sort of trouble to load the page).

In such cases it could be nice to take a screenshot and attach here. Also, this approach would make way the reported issue more future proof.

**Comment by eliheuer** [comment]
@felipesanches Noted, I'll include screenshots with issues when possible. It's offline for me
 also, here is a screenshot:

![screen shot 2018-07-18 at 12 59 22 pm](https://user-images.githubusercontent.com/5162664/42896457-f3705a92-8a8a-11e8-8193-8a2cb287eb76.png)

![screen shot 2018-07-18 at 1 01 54 pm](https://user-images.githubusercontent.com/5162664/42896475-ffe62108-8a8a-11e8-9abb-a31bf1e3adaf.png)

**Comment by eliheuer** [comment]
@davelab6 I wonder if I'm beyond the limits of my typographic knowledge here. I'm flipping through the appendix of Elements of Typographic Style but not finding anything. So I assume this is a bug?

**Comment by felipesanches** [comment]
And here's the ligature glyph in fontforge:

![screenshot at 2018-07-18 14 31 36](https://user-images.githubusercontent.com/213676/42897747-7aa78ff6-8ab0-11e8-881e-07fc9e13309b.png)

**Comment by felipesanches** [comment]
In some languages the word "number" is represented by the letter N followed by a small elevated letter o. In Portuguese, for instance, the 'o' refers to the last letter in the word "número" (meaning "number").

This is similar to how "first" is represented as 1st and in some cases the 'st' is also small and positioned higher than the baseline. In Portuguese we say "primeiro" (meaning "first") and represent it as '1o' (but also with the tiny elevated 'o').

**Comment by felipesanches** [comment]
I guess the same applies to Spanish.

**Comment by felipesanches** [comment]
One problem though is that **(I guess)** having an `N_o` ligature would cause english text like "No way!" to render like "número way!" which seems like a bug in the font.

I need to test it to see if it actually happens though.

**Comment by felipesanches** [comment]
Also, the 'o' is commonly underlined. Here are a few examples:

![screenshot at 2018-07-18 14 48 20](https://user-images.githubusercontent.com/213676/42898484-d8c87abc-8ab2-11e8-848b-b4890004e026.png)

**Comment by felipesanches** [comment]
I think the glyph for U+2116 (**'NUMERO SIGN'**) should be used as ligature for the 'N' followed by U+00BA (**'MASCULINE ORDINAL INDICATOR'**) instead of 'N' followed by 'o'.

* https://www.fileformat.info/info/unicode/char/2116/index.htm
* http://www.fileformat.info/info/unicode/char/ba/index.htm

**Comment by felipesanches** [comment]
All the above makes me believe this is not a fontbakery bug.

**Comment by eliheuer** [comment]
@felipesanches Thanks for providing all this information, I should be able to resolve this now.

**Comment by felipesanches** [comment]
Maybe you can open an issue for the Dosis font project (are you working on a git repo?) and then reference this one for background info

**Comment by davelab6** [comment]
We should remove the ligature, and update FB with a much better explanatory text about the possible ways to resolve

**Comment by felipesanches** [comment]
The way fontbakery deals with ligatures (and also caret positions) was improved at #1976 and the warning messages are much clearer now.
