### ISSUE TITLE
[specifications][googlefonts]: Only run regression checks if family is on GF

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1995]
Whilst PRing https://github.com/google/fonts/pull/1634, I noticed that the regression checks ran, even though the family is new. They should only run if the family exists on GF.

![screen shot 2018-08-03 at 11 47 16](https://user-images.githubusercontent.com/7525512/43639126-1a0b690a-9713-11e8-8f2b-6797a3344876.png)

**Comment by davelab6** [comment]
Agree
