### ISSUE TITLE
Dashboard seems to be down

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/fontbakery#2010]
## Observed behaviour

When the links to the web front end are used they time out

## Expected behaviour

I expected to be able to use the web from end for Font Bakery

## Resources and exact process needed to replicate

clicking on links here http://fontbakery.com/dashboard/

Gives the result

35.225.170.228 refused to connect.

**Comment by graphicore** [comment]
Thanks for reporting!

This is a reoccurring condition reported and tracked here: https://github.com/googlefonts/fontbakery-dashboard/issues/78

Should be working again for now.

**Comment by EbenSorkin** [comment]
Thanks!

-e.
