### ISSUE TITLE
Using test result as a condition?

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#2016]
Edit: reworded issue.

I have some tests that fill a DIN A4 page because each sub-check depends on the previous step to check out (think testing several assumptions about kerning classes one after the other where checking later stages makes no sense if something before that fails). I'd like to break these into separate checks where later checks don't execute if previous checks fail. Achievable or should I do something else?

**Comment by graphicore** [comment]
As you already suggested before the rewording, make them into conditions and have the checks just be thin layer looking at the condition values. Dependencies can be modeled using the `conditions` argument of the check decorator.

**Comment by graphicore** [comment]
About boilerplate: you may be able to meta-program it away …

**Comment by felipesanches** [comment]
yeah. I think that the strategy suggested by Lasse is good enough for our current codebase/code-style. I will close this issues as this does not seem to be an actual fontbakery bug, but feel free to continue using this space as a forum for discussing strategies related to implementing your new checks.
