### ISSUE TITLE
Sensible mixing of specification when looking at different file formats?

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#2019]
I'm writing a Dalton Maag specific front-end to Fontbakery and want to keep command-line arguments as far away from the users as possible (mainly because most of our designers are scared of the CLI as is). The idea is that people run `damacheck` in a project's root directory and it will automatically crawl `sources/` with all the UFOs and `release` with the OT binaries to be shipped; the thing is to handle different formats in one Runner, so command-line arguments count for everything and there is _one_ report at the end. Can this be sensibly done with the current architecture? Anyone have a better idea?

**Comment by davelab6** [comment]
@madig did you resolve this?

**Comment by madig** [comment]
No, but I haven't had time for it, either.

**Comment by davelab6** [comment]
I think you can make a specification/profile that calls checks conditionally. @graphicore?

**Comment by graphicore** [comment]
Not an easy answer here. Calling checks conditionally means skipping them. you could have one iterarg `"font": "fonts"` for `ttFont` and one `"ufo": "ufos", that would run checks only for ufo's/defcon-font objects. It's important then to be clear what namespace items belong to which type of check, otherwise it may  get messy.

**Comment by chrissimpkins** [comment]
There are simple (to implement + use) DnD GUI application builders for macOS like Platypus that would allow you to script all of the source parsing and fontbakery execution logic in shell scripts or Python scripts.  This would give users a GUI window where they could simply drop the entire repository directory providing you with their desired test path and empower you to author what happens from there without user involvement or the need for users to touch a terminal.  Can be easily packaged in a macOS installer that can be downloaded from Github releases for double click installs and/or distributed through Homebrew Cask.  They cannot be easily packaged for distribution in the App Store.  Outside of the source the only requirement is that you design an application icon that will be displayed in the user's Launcher.  

Not aware of simple to implement applications that build GUI apps on Linux or Win if these are platforms that you need to deal with.  

I've made several of these for a variety of purposes and have  shell scripts that demonstrate implementation of the source to interact with the GUI and scripts for packaging the installer.  Crunch repo is the best example but it is littered with other non GUI source.  If this is of any interest let me know and I can point to exact files/provide more details.

**Comment by simoncozens** [comment]
@madig I'm assuming that after five years you've found a better workflow for testing, so I'm closing it here. But if this is still an issue, I suspect the real requirement is for a nicer Python API to the checking infrastructure; which overlaps with issues like #4128, so I would prefer to track that there. (I think we acknowledge that we need a clean API, but haven't got to working on it yet. We will.)
