### ISSUE TITLE
Shortening iterargs display for reporters?

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#2020]
## Observed behaviour

```
>> com.daltonmaag/check/encoding_order with (('font[13]', 'C:\\Users\\nikolaus.waxweiler\\AppData\\Local\\Temp\\asdf\\sources\\asdf_RgIt.ufo'),)
...
```

## Expected behaviour

```
>> com.daltonmaag/check/encoding_order with 'sources\asdf_RgIt.ufo'
...
```
or similar.

One designer said that the current format is a bit verbose and confusing.

**Comment by felipesanches** [comment]
I implemented this change some time ago and forgot to reference this issue and close it ;-)
