### ISSUE TITLE
Cupcake artwork is too big, negatively impacts usability

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#2030]
## Observed behaviour

When running a single test, the cupcake artwork from commit dc29722ad0d0c1d38ddf49271541b60fe1bae29e is too big(52 chars wide) and negativly impact usablity. I'm forced to scroll up to see the results or to use a very small font size. 

## Expected behaviour

The results from a single test should try to be readable in a reasonably sized terminal.

An ASCII cupcake could be rendered at a significantly smaller size. 16x8 chars for example. 

See screenshot below, note the results are pushed off the screen:

![cupcake-issue](https://user-images.githubusercontent.com/5162664/44667297-69f57180-a9e8-11e8-9285-460cb16a1401.png)

**Comment by felipesanches** [comment]
heh, yeah... but it more closely resembles an oak nut (instead of a cupcake)...

I should mention, by the way, that the unicorn artwork we previously had here probably also took roughly the same amount of screen space.

**Comment by felipesanches** [comment]
@eliheuer would you suggest using a smaller version of the artwork on certain conditions, but still keep the large one on other occasions?

Maybe the threshold would be the total number of checks actually executed?

Or are you advocating for the large artwork to be completely removed from the codebase?

**Comment by eliheuer** [comment]
I should note, this isn't an urgent issue, it's just something that has been slightly bothering me while using the CLI.

I like having the artwork, I think it's a nice feature, but anything bigger than 80x12 chars can make using the software difficult for people. This is just an accessibility issue, but also some typographers appreciate when CLI software respects a minimum line length.

**Comment by madig** [comment]
If you happen to use fontbakery from custom Python scripts, you can do
```
import fontbakery.reporters.terminal
fontbakery.reporters.terminal.UNICORN = ""
```
as a makeshift solution.

**Comment by m4rc1e** [comment]
@madig I wish that was the default!
