### ISSUE TITLE
Suggest scraping `checks` into Markdown document

### ISSUE THREAD

**Issue by nathan-williams** [googlefonts/fontbakery#2039]
This isn't a bug report, more of a suggestion.

The flow for getting more info on check's from fontbakery output is sort of janky. You could add a python script, which scrapes all of the @check's in the project, gets their __doc__ values and other relevant information, and presents that data in an organized file at docs/checks.md. The headings can be linked directly from the fontbakery output.

**Comment by graphicore** [comment]
I'd love to see or do it and also have some ideas for some kind of a help system. I'd also like to provide something like this via the dashboard.
Maybe though, we can have it cheap and tweak Sphinxs into generating sufficient documentation for specifications/checks etc. See: https://github.com/googlefonts/fontbakery/pull/2027. That would be likely two setups, one for the actual Font Bakery implementation (checkrunner etc.) and one for specifications.

**Comment by nathan-williams** [comment]
It's quite sloppy+hacky, but this almost does the bare minimum :D

```python
import pkgutil

from fontbakery import specifications
from fontbakery.callable import FontBakeryCheck

checks = []

for importer, modname, ispkg in pkgutil.iter_modules(specifications.__path__):
	exec('from fontbakery.specifications import ' + modname)
	exec('module = ' + modname)
	for attr_name in dir(module):
		attr = getattr(module, attr_name)
		if isinstance(attr, FontBakeryCheck):
			checks.append((attr.__name__, attr.__doc__))

checks.sort()

for name, doc in checks:
	print('# ' + name)
	print()
	print(doc.strip())
	print()
```

**Comment by felipesanches** [comment]
Hey! Thanks for the code snippet!

I've tweaked it a bit and I think something this would be slightly better:
```python
import pkgutil

from fontbakery import specifications
from fontbakery.callable import FontBakeryCheck

checks = []

for importer, modname, ispkg in pkgutil.iter_modules(specifications.__path__):
  exec('from fontbakery.specifications import ' + modname)
  exec('module = ' + modname)
  for attr_name in dir(module):
    attr = getattr(module, attr_name)
    if isinstance(attr, FontBakeryCheck):
      try:
        rationale = f"\n## rationale:\n\t{attr.rationale}\n"
      except:
        rationale = ""
      checks.append((attr.id, attr.__doc__, rationale))

checks.sort()

for check_id, doc, rationale in checks:
  print(f'# {check_id}\n{doc.strip()}{rationale}\n')
```

But for that to work we also need to do:
```
self.rationale = rationale
```
on the constructor of the `FontBakeryCheck` class.

**Comment by felipesanches** [comment]
nowadays we have docs for checks on our ReadTheDocs page
