### ISSUE TITLE
Update OTS Homebrew Forumla for latest release (v7.x) and HEAD

### ISSUE THREAD

**Issue by mjlagattuta** [googlefonts/fontbakery#2041]
## Observed behaviour

When following the installation instructions for ots using brew the following error was encountered:
<img width="757" alt="screen shot 2018-09-11 at 10 17 39 am" src="https://user-images.githubusercontent.com/35570153/45366146-297f2180-b5ac-11e8-8951-67c790cf975b.png">

## Expected behaviour

Should install smoothly

## Resources and exact process needed to replicate

This issue was encountered by several people  at the AtypI fontbakery workshop on September 11th, 2018. It is possible that the problem was caused by the network blocking ssh but we are unsure.

**Comment by davelab6** [comment]
https://github.com/bramstein/homebrew-webfonttools/pull/27 fixes this,
although perhaps we should maintain our own googlefonts homebrew tap for
this situation

**Comment by HinTak** [comment]
Personally I'd stay away from homebrew; I think fontbakery should run `--version` or similar to check version. More reproducible results that way. My 2 cents.

**Comment by davelab6** [comment]
Agree, that install process is likely better

**Comment by chrissimpkins** [comment]
#2058 updates the install docs with the curl approach above if there is consensus that this is a better approach for now
