### ISSUE TITLE
unexpected error in running checks 

### ISSUE THREAD

**Issue by n7s** [googlefonts/fontbakery#2043]
## Observed behaviour

running the following checks I get these errors:
(at the FB workshop at AtypI)

>> com.google.fonts/check/050 with (('font[3]', 'test/mada/Mada-Light.ttf'),)
   Whitespace and non-breaking space have the same width?
 * ERROR: The condition <FontBakeryCondition:missing_whitespace_chars> had an error: AttributeError: 'TTFont' object has no attribute 'getBestCmap'
           File "/root/fontbakery-n7s/Lib/fontbakery/checkrunner.py", line 413, in _evaluate_condition
             return None, condition(**args)
         

   Result: ERROR

>> com.google.fonts/check/050 with (('font[4]', 'test/mada/Mada-Medium.ttf'),)
   Whitespace and non-breaking space have the same width?
 * ERROR: The condition <FontBakeryCondition:missing_whitespace_chars> had an error: AttributeError: 'TTFont' object has no attribute 'getBestCmap'
           File "/root/fontbakery-n7s/Lib/fontbakery/checkrunner.py", line 413, in _evaluate_condition
             return None, condition(**args)
         

   Result: ERROR

>> com.google.fonts/check/050 with (('font[5]', 'test/mada/Mada-Regular.ttf'),)
   Whitespace and non-breaking space have the same width?
 * ERROR: The condition <FontBakeryCondition:missing_whitespace_chars> had an error: AttributeError: 'TTFont' object has no attribute 'getBestCmap'
           File "/root/fontbakery-n7s/Lib/fontbakery/checkrunner.py", line 413, in _evaluate_condition
             return None, condition(**args)
         

   Result: ERROR

>> com.google.fonts/check/050 with (('font[6]', 'test/mada/Mada-SemiBold.ttf'),)
   Whitespace and non-breaking space have the same width?
 * ERROR: The condition <FontBakeryCondition:missing_whitespace_chars> had an error: AttributeError: 'TTFont' object has no attribute 'getBestCmap'
           File "/root/fontbakery-n7s/Lib/fontbakery/checkrunner.py", line 413, in _evaluate_condition
             return None, condition(**args)

## Resources and exact process needed to replicate

running against master on the test/mada font in the fontbakery repository. fonttools is installed but apparently there is an issue with fonttools integration. (running in a lxc test vm). 

Thanks !

**Comment by felipesanches** [comment]
fontTools CHANGELOG at https://pypi.org/project/FontTools/ states:

```
3.19.0 (released 2017-11-06)
[ttLib] Added getBestCmap() convenience method to TTFont class
 and cmap table class that returns a preferred Unicode cmap
 subtable given a list of options (#1092).
```

@n7s, maybe for some reason you are using an older version of fontTools?
Installing Font Bakery should have caused a pretty recent version of fontTools to be installed automatically as well, so that is a bit weird.

Nicolas, could you please let me know which version of fontTools you have?

**Comment by felipesanches** [comment]
well... maybe this is the problem:
https://github.com/googlefonts/fontbakery/blob/master/requirements.txt#L1

This should definitely be `>=3.19`!

**Comment by felipesanches** [comment]
ok. I have just updated the requirements.txt file to address the issue.

Please consider fetching the latest code from git master and then re-running `pip install -r requirements.txt`

**Comment by felipesanches** [comment]
OK. I have just verified this on @n7s 's laptop here during the FontBakery workshop at Atypi 2018. It is now fixed :-)
