### ISSUE TITLE
Wrap or port FontQA checks

### ISSUE THREAD

**Issue by Fonthausen** [googlefonts/fontbakery#2044]
I had a discussion with @felipesanches and @graphicore on a tool I used in the past. 

FontQA by Andreas Eigendorf (http://fontqa.com). It was using a script in FontLab and exported the results as a XML file that could be opened in a browser. It had a simple, but clear graphical output. For designers with less technical know-how, it was quite nice to work with.

I added a XML file for you to look at if you want, and a screenshot. Problem is only that Mac browsers don't work well with XML anymore.

<img width="1552" alt="schermafbeelding 2018-09-11 om 16 57 26" src="https://user-images.githubusercontent.com/20181530/45368475-f6588480-b5e3-11e8-8c1e-d769cd012cfe.png">

[XML.zip](https://github.com/googlefonts/fontbakery/files/2371480/XML.zip)

**Comment by felipesanches** [comment]
It is important to clarify here that @Fonthausen 's request originally expressed in words during a face to face conversation on the atypi workshop seemed to be about having XML output to be viewed as tables on a web browser. He was suggesting we could use some technologies to have graphical output of our test reports other than the text terminal. The workflow of outputting markdown and then previewing that on a github issue seemed to be a bit too complicated perhaps and @Fonthausen was mentioning something he considered nice in another tool (XML output from FontQA).

**Comment by davelab6** [comment]
Right; I guess we could have a HTML reporter which simply takes the output from `--ghmarkdown` and runs it through https://github.com/Python-Markdown/markdown or whatever to create the `output.html` file that you can immediately open and read.

**Comment by madig** [comment]
I played with some Markdown converters and found them painfully slow for huge reports, so I wrote a direct-to-HTML reporter.

**Comment by anthrotype** [comment]
This one’s good
https://github.com/theacodes/cmarkgfm

**Comment by madig** [comment]
Worth a try I guess, before I submit my custom one.

**Comment by anthrotype** [comment]
It’s the same used on PyPI to render the Readme written in Github Flavored Markdown, the original library is written in C (from github itself), this is the python bindings

**Comment by anthrotype** [comment]
My golden rule: never reinvent the wheel

**Comment by madig** [comment]
Unless it's fun.

**Comment by anthrotype** [comment]
That’s my platinum rule

**Comment by simoncozens** [comment]
We now have HTML output (and have had for some time)!
