### ISSUE TITLE
ttx roundtrip error

### ISSUE THREAD

**Issue by laerm0** [googlefonts/fontbakery#2048]
fontbakery 0.5.1

```>> com.google.fonts/check/ttx-roundtrip with (('font[0]', 'Roboto-VF.ttf'),)
   Checking with fontTools.ttx
 * ERROR: Failed with ExpatError: not well-formed (invalid token): line 422637, column 66
           File "/usr/local/lib/python3.6/site-packages/fontbakery/checkrunner.py", line 350, in _exec_check
             for sub_result in result:  # Might raise.
           File "/usr/local/lib/python3.6/site-packages/fontbakery/specifications/general.py", line 718, in com_google_fonts_check_ttx_roundtrip
             f.importXML(font + ".xml")
           File "/usr/local/lib/python3.6/site-packages/fontTools/ttLib/ttFont.py", line 336, in importXML
             reader.read()
           File "/usr/local/lib/python3.6/site-packages/fontTools/misc/xmlReader.py", line 49, in read
             self._parseFile(self.file)
           File "/usr/local/lib/python3.6/site-packages/fontTools/misc/xmlReader.py", line 74, in _parseFile
             parser.Parse(chunk, 0)
         

   Result: ERROR
```

**Comment by felipesanches** [comment]
send me a sample, please!

**Comment by laerm0** [comment]
[File](https://github.com/laerm0/Roboto/tree/hinting/fonts/hinting%20WIP) is located in my fork of Roboto, `hinting` branch.

**Comment by felipesanches** [comment]
also, which version of fonttools are you using?

**Comment by laerm0** [comment]
Hold on, it may be a `fonttools` issue.

**Comment by graphicore** [comment]
The dashboard has it as well: http://35.225.170.228/report/7932caa2-e1d6-45a1-96d1-56f608d1ecc6


![1_210](https://user-images.githubusercontent.com/393132/45370668-f1e29a80-b5e8-11e8-80a3-09a4f48c94a3.png)

**Comment by anthrotype** [comment]
I was able to reproduce with latest ttx and the ttf file that @laerm0 linked to above.
I'll investigate, thanks.

**Comment by anthrotype** [comment]
yeah, for some reason an inline comment in the VTT code contained in one of the TSI tables (TSI3, i think) contains an invalid control character [U+000B](http://www.fileformat.info/info/unicode/char/000B/index.htm).
This is invalid in XML, so the expat parser chokes.
There is an open issue on fonttools about dealing with invalid XML chars:
https://github.com/fonttools/fonttools/issues/71

for the time being I would recommend editing the VTT sources and deleting the offending character, which is located at line line 422637, column 66 in my ttx dump (check the expat error message).
