### ISSUE TITLE
CLI: Limit line length of check output to improve readability

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#2052]
## Observed behaviour

When using the command line interface the output message has no line length limit. Note the following example: 

```
>> com.google.fonts/check/028
   Check font has a license.
 * FAIL: No license file was found. Please add an OFL.txt or a LICENSE.txt file. If you are running fontbakery on a Google Fonts upstream repo, which
is fine, just make sure there is a temporary license file in the same folder. [code: none]

   Result: FAIL

>> com.google.fonts/check/001 with (('font[0]', 'Isotherma-Alpha.otf'),)
   Checking file is named canonically.
 * FAIL: Style name used in "Isotherma-Alpha.otf" is not canonical. You should rebuild the font using any of the following style names: "Thin", "Extra
Light", "Light", "Regular", "Medium", "SemiBold", "Bold", "ExtraBold", "Black", "Thin Italic", "ExtraLight Italic", "Light Italic", "Italic", "Medium
Italic", "SemiBold Italic", "Bold Italic", "ExtraBold Italic", "Black Italic".

   Result: FAIL

>> com.google.fonts/check/018 with (('font[0]', 'Isotherma-Alpha.otf'),)
   Checking OS/2 achVendID.
 * WARN: OS/2 VendorID value 'pyrs' is not a known registered id. You should set it to your own 4 character code, and register that code with Microsof
t at https://www.microsoft.com/typography/links/vendorlist.aspx [code: unknown]

   Result: WARN
```

## Expected behaviour

If the output was limited to a line length of 79 characters, readability might be improved. See the following reformatted example: 
```
>> com.google.fonts/check/028
   Check font has a license.
 * FAIL: No license file was found. Please add an OFL.txt or a LICENSE.txt
file. If you are running fontbakery on a Google Fonts upstream repo, which
is fine, just make sure there is a temporary license file in the same folder. 
[code: none]

   Result: FAIL

>> com.google.fonts/check/001 with (('font[0]', 'Isotherma-Alpha.otf'),)
   Checking file is named canonically.
 * FAIL: Style name used in "Isotherma-Alpha.otf" is not canonical. You should
 rebuild the font using any of the following style names: "Thin", "Extra
Light", "Light", "Regular", "Medium", "SemiBold", "Bold", "ExtraBold", "Black",
"Thin Italic", "ExtraLight Italic", "Light Italic", "Italic", "Medium
Italic", "SemiBold Italic", "Bold Italic", "ExtraBold Italic", "Black Italic".

   Result: FAIL

>> com.google.fonts/check/018 with (('font[0]', 'Isotherma-Alpha.otf'),)
   Checking OS/2 achVendID.
 * WARN: OS/2 VendorID value 'pyrs' is not a known registered id. You should
set it to your own 4 character code, and register that code with Microsof
t at https://www.microsoft.com/typography/links/vendorlist.aspx 
[code: unknown]

   Result: WARN
```

**Comment by graphicore** [comment]
This suggestion could be problematic with properly preformatted output. Also, isn't this very uncommon for CLIs?

**Comment by graphicore** [comment]
Also, my terminal emulator breaks lines automatically. So, the observed behavior described above does not apply for me.

**Comment by felipesanches** [comment]
I also think that formatting should be done on the specific reporters (https://github.com/googlefonts/fontbakery/tree/master/Lib/fontbakery/reporters) and not hardcoded in the check implementation. That way we may have more flexibility to do things like you are suggesting (if we decide to do so) but format is differently on the markdown output, if necessary.

**Comment by chrissimpkins** [comment]
My personal preference is to allow text to flow to my terminal width settings.  I frequently modify terminal widths/lengths on large screens so that they accommodate long lines of text.  This is a feature in my mind and this change would eliminate the ability to do that.  Readability is always compromised in the terminal by long blocks of output text.  Perhaps reformatting output to more concise text with use of lists for errors / action items or some other approach could be used to achieve this.

**Comment by chrissimpkins** [comment]
An alternate approach might be to host the detailed error messages outside of the application output (e.g. Github Markdown files, website, etc) and simply include a brief one-liner of the problem and URL to the description of the fix in the terminal.  An example of this approach is `shellcheck`.  The wiki files for each error/solution is here: https://github.com/koalaman/shellcheck/wiki/Checks

**Comment by felipesanches** [comment]
I disagree with moving the info into a website because that would make the tool less useful for users temporarily offline or having network issues. I suspect it could also potentially lead to unnecessary issues related to synchronization of the data with the program version. I still prefer to keep the tool self-contained.

**Comment by chrissimpkins** [comment]
Eli, is the issue that there is no wrapping when you paste into threads like this as you demonstrated in your OP (which extends beyond the text box for the issue report) or that you don't like for the text to extend to the margins of your terminal and automatically wrap at the width set in the terminal (for those of us who aren't using whatever application Lasse is :)  )?  The former is a problem as you've shown above and can be addressed with something like Markdown output that can be pasted into threads for discussion.  This would look great if you could format the report in GH flavored Markdown and paste that into a thread as the basis for discussion about an issue that arises during testing.  My comments above refer to viewing the text in a terminal / text wrapping in the terminal, not for copy/paste issues.

**Comment by felipesanches** [comment]
I've done this for the check rationales on text terminal a while ago, but not for the log messages. The necessary code for wrapping is already in place, I only need to hookup the log messages to that. Should be straightforward to do.

**Comment by felipesanches** [comment]
A friend of mine, Aurélio Heckert (@aurium) will help us here. He's got an implementation of the text wrapping for the log messages and will soon submit a pull request ;-D
