### ISSUE TITLE
Document how to install and use on Windows

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2054]
## Observed behaviour

Many font developers use macOS, but many font engineers use Windows. 

While @madig and colleagues are using FB on Windows daily, our documentation for Windows users sucks

## Expected behaviour

macOS and Windows documentation should have parity :)

@madig would you be interested to take this on?

**Comment by madig** [comment]
1. `pip install fontbakery`
2. `fontbakery check-opentype bake-me.ttf`

For the rest I'd have to do research some day, as I distribute a custom front-end for fontbakery internally and currently only really use custom UFO checks, disabling all external tools.

**Comment by davelab6** [comment]
Like a .exe installer with a pyQt UI?

**Comment by madig** [comment]
No, a command line tool that creates a HTML report (the markdown thing without the markdown dependency) and opens it ina browser tab.

**Comment by graphicore** [comment]
> 1. pip install fontbakery
> 2. …

Using `cmd.exe` (the "DOS window") or PowerShell?

**Comment by madig** [comment]
Either one works with the commands I posted.

**Comment by HinTak** [comment]
Are you using win64 python or win32 python?

I am about to upload a new win32/win64 pre-release of FontVal, mainly to fix a rather long-term bug of crash caused by harfbuzz being buggy on win64.

**Comment by HinTak** [comment]
The new windows builds is at https://github.com/HinTak/Font-Validator/releases under 2.1.2 . I would appreciate if you concentrate on the win64 build and report any crashes (the one I fixed is harfbuzz related but there might be others). This probably means win64   python.

Btw, even if you have 64-bit wine and completely wow64 capable, you would only run FontVal in 32-bit mode on wine. This was discussed on wine-devel a few years ago, and finally filed as https://github.com/madewokherd/wine-mono/issues/40 recently, as I needed to test for win64 specifically.

**Comment by felipesanches** [comment]
I've split install docs per target operating system. Users at ATypI got confused about the boundaries between each section. So I think splitting will enhance usability,

Windows-specific instructions are still incomplete. Can you help us improve that, @madig ?

**Comment by madig** [comment]
Can this be closed? Or is there more missing?

**Comment by felipesanches** [comment]
yep. Thanks, @madig!

**Comment by madig** [comment]
It just occured to me that the FontForge checks probably won't run on Windows because `python` is not guaranteed to be 2.x. I think the FF module is 2.x only 🤔 And Python would need to know where to look for the module, not sure it gets put into a standard location.

**Comment by felipesanches** [comment]
I think fontforge checks should be ported into individual native fontbakery checks written in python. At least the ones that make sense. And the rest should be ignored. Maybe we should open an issue for that task... :-)

**Comment by davelab6** [comment]
> I think fontforge checks should be ported into individual native fontbakery checks written in python. At least the ones that make sense. And the rest should be ignored. Maybe we should open an issue for that task... :-)

I've updated https://github.com/googlefonts/fontbakery/issues/1814 to be about it.
