### ISSUE TITLE
ots install

### ISSUE THREAD

**Issue by laerm0** [googlefonts/fontbakery#2057]
Hi @felipesanches –

I am reinstalling everything on a clean install of OS X High Sierra. I hit a bump with the ots install instructions in the [FB install instructions page](https://github.com/googlefonts/fontbakery/blob/master/INSTALL.md).

```
MacBook-Pro:~ stupakm$ brew tap bramstein/webfonttools;
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from d44bc8be2 to f239b7a62.
Updated 1 tap (homebrew/core).
==> Updated Formulae
azure-cli                   fn                          libcouchbase

MacBook-Pro:~ stupakm$ brew update;
Already up-to-date.
MacBook-Pro:~ stupakm$ brew install ots --HEAD;
Error: ots: /usr/local/Homebrew/Library/Taps/bramstein/homebrew-webfonttools/ots.rb:6: syntax error, unexpected <<, expecting keyword_end
<<<<<<< Updated upstream
  ^
/usr/local/Homebrew/Library/Taps/bramstein/homebrew-webfonttools/ots.rb:8: syntax error, unexpected ===, expecting keyword_end
=======
   ^
MacBook-Pro:~ stupakm$
```

As it says...

`If brew fails, try installing the binaries from https://github.com/khaledhosny/ots/releases and report an error on the Font Bakery issue tracker.`

Let me know if I can test anything else for you.

**Comment by chrissimpkins** [comment]
It looks like others have run into this issue too.  There is an open PR on Bram's repository to update the Homebrew install script:

https://github.com/bramstein/homebrew-webfonttools/pull/27

As a workaround until it is fixed, you can download the current release versions of the compiled ots binaries from Khaled's releases:

https://github.com/khaledhosny/ots/releases/download/v7.1.7/ots-7.1.7-osx.zip

and move `ots-sanitize` to the path `/usr/local/bin/ots-sanitize`.  That will work with the ots-sanitize check in Font Bakery:

https://github.com/googlefonts/fontbakery/blob/57e85503fd26e21cb200633a348f671f4001afd5/Lib/fontbakery/specifications/general.py#L117-L137

**Comment by chrissimpkins** [comment]
Updated the `ots-sanitize` installation docs for macOS in #2058
