### ISSUE TITLE
Code health: use enum package for enumeration constants

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#2071]
## Observed behaviour

`constants.py` houses various enumerations such as

```Python
# fsSelection bit definitions:
FSSEL_ITALIC         = (1 << 0)
FSSEL_UNDERSCORE     = (1 << 1)
FSSEL_NEGATIVE       = (1 << 2)
FSSEL_OUTLINED       = (1 << 3)
FSSEL_STRIKEOUT      = (1 << 4)
FSSEL_BOLD           = (1 << 5)
FSSEL_REGULAR        = (1 << 6)
FSSEL_USETYPOMETRICS = (1 << 7)
FSSEL_WWS            = (1 << 8)
FSSEL_OBLIQUE        = (1 << 9)
```

which are used like

```Python
def com_google_fonts_check_129(ttFont, style):
  """Checking OS/2 fsSelection value."""
  from fontbakery.utils import check_bit_entry
  from fontbakery.constants import (STYLE_NAMES,
                                    RIBBI_STYLE_NAMES,
                                    FSSEL_REGULAR,
                                    FSSEL_ITALIC,
                                    FSSEL_BOLD)

  # Checking fsSelection REGULAR bit:
  expected = "Regular" in style or \
             (style in STYLE_NAMES and
              style not in RIBBI_STYLE_NAMES and
              "Italic" not in style)
  yield check_bit_entry(ttFont, "OS/2", "fsSelection",
                        expected,
                        bitmask=FSSEL_REGULAR,
                        bitname="REGULAR")
[...]
```

## Expected behaviour

Using the [enum package](https://docs.python.org/3.6/library/enum.html) makes these constants a bit easier to handle:

```Python
import enum

class FSSelection(enum.IntEnum):
    ITALIC = 1 << 0
    UNDERSCORE = 1 << 1
    NEGATIVE = 1 << 2
    OUTLINED = 1 << 3
    STRIKEOUT = 1 << 4
    BOLD = 1 << 5
    REGULAR = 1 << 6
    USE_TYPO_METRICS = 1 << 7
    WWS = 1 << 8
    OBLIQUE = 1 << 9
[...]
from fontbakery.constants import (FSSelection, ...)  # instead of each constant by itself
[...]
  yield check_bit_entry(ttFont, "OS/2", "fsSelection",
                        expected,
                        bitmask=FSSelection.REGULAR,
                        bitname="REGULAR")
[...]
```

Might need a look at the entire codebase to determine all hidden enums.

Possibly also interesting in a bitflag context: https://docs.python.org/3.6/library/enum.html#flag.

**Comment by anthrotype** [comment]
Instead of enum.IntEnum you could also use enum.Flag in that particular example
https://docs.python.org/3/library/enum.html#enum.Flag

(I’m so gealous you guys are python3.6+ only)

**Comment by anthrotype** [comment]
Oh I just noticed Nikolaus had already linked to enum flags, cool cool

**Comment by anthrotype** [comment]
lmgtfy
https://stackoverflow.com/a/37601645

**Comment by madig** [comment]
checkrunner.py's `Status` object also looks like a convoluted enumeration, unless there are plans to extend it to beyond holding `weight: int`.

**Comment by felipesanches** [comment]
OK. I like it. It makes the code cleaner by allowing us to simply do:

```
from fontbakery.contants import NameID
```

instead of importing each specific NAMEID_SOMETHING to be used on each check.

And it is also aligned to my self-imposed development guidelines for fontbakery:
![captura de tela 2018-10-05 a cc 80s 09 50 23](https://user-images.githubusercontent.com/213676/46556466-43273680-c8d6-11e8-8616-d8dd56f5a2dc.png)

**Comment by madig** [comment]
This is an API change, so you might want to jump to 0.6.0 ;)

**Comment by felipesanches** [comment]
yep... makes sense. But let's continue working on more things before cutting a new release.

**Comment by felipesanches** [comment]
By the way, you will have to update your internal checks to use the new API. Would you like me to help you with that? Then this can also be a good opportunity to make them public :-)

**Comment by madig** [comment]
Making them public is not my decision. Maybe some day.
