### ISSUE TITLE
check-opentype is broken in master

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#2076]
## Observed behaviour

```
> fontbakery.exe check-opentype -c 064 -c 065 something.ttf
[...]
fontbakery.checkrunner.SetupError: Spec uses names that are not declared in its namespace: vtt_talk_sources.
```

## Resources and exact process needed to replicate

`vtt_talk_sources` seems to be general enough to be moved to shared conditions?

**Comment by felipesanches** [comment]
ouch!

I'll take a look at it and fix it asap!

**Comment by madig** [comment]
I'm on it already. Need to add a test somehow.
