### ISSUE TITLE
skip a check

### ISSUE THREAD

**Issue by laerm0** [googlefonts/fontbakery#2089]
We have a switch to do just a check; can we add a switch to _skip_ a check? Eg.
`fontbakery check-googlefonts -nc com.google.fonts/check/034 fontymcfont.ttf`
would skip check 34. This would enable the user who is tuning one particular thing to skip a check that takes a while (i.e. contours).

**Comment by felipesanches** [comment]
we do have `-x` for that!

```
  -c CHECKID, --checkid CHECKID
                        Explicit check-ids (or parts of their name) to be executed.
                        Use this option multiple times to select multiple checks.

  -x EXCLUDE_CHECKID, --exclude-checkid EXCLUDE_CHECKID
                        Exclude check-ids (or parts of their name) from execution.
                        Use this option multiple times to exclude multiple checks.
```

**Comment by laerm0** [comment]
Hi, did you know I can't read? 😂

**Comment by felipesanches** [comment]
no worries! I'm here to help :-)
