### ISSUE TITLE
Ensure latest Fontbakery is installed, otherwise emit a hysterical ERROR message with update instructions

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2093]
In https://github.com/google/fonts/pull/1720 there are 4 checks that ERROR because they have not been written correctly for the case of checking new families - when the family doesn't exist yet, the error message is inscrutable unless you know your HTTP ;)

> **ERROR** The condition <FontBakeryCondition:api_gfonts_ttFont> had an error: FailedConditionError: The condition <FontBakeryCondition:remote_styles> had an error: HTTPError: HTTP Error 404: Not Found

## Expected behaviour

These checks should pass as INFO that the family doesn't exist yet, so everything is fine. 

(Marking this as a p0 because its a false failure, that breaks the promise of reliability and trustworthiness we strongly aspire to)

**Comment by m4rc1e** [comment]
This has been fixed. Those fonts were run through an older pip version of fb.

Reason its an older FB is because updating is a pain the ass until we fix #1337.

I'll update my hacked pip FB and rerun the fonts through.

**Comment by felipesanches** [comment]
#1337 is a PR which seems unrelated. Can you please clarify which issue or pull request you originally intended to refer to in you previous comment, @m4rc1e ?

**Comment by felipesanches** [comment]
I think we should have a "meta" check that ensures the user is running the very latest release of fontbakery and otherwise result in a very loud and clear disclaimer stating that the report that follows is likely incorrect due to new fixes already present in newer fontbakery releases. And also instructing the user on how to perform the fontbakery update.

**Comment by felipesanches** [comment]
I wish we had a label **"Priority: -1 DOOMSDAY"** for issues like this one...

**Comment by graphicore** [comment]
It's not DOOMSDAY, ERROR should be visible enough. There may also be good reasons for running older releases, e.g. regressions or newly introduced bugs.

Also, with all the not idempotent checks that we have, each run, even with the same version of FB, can yield different reports. Where do you draw the line?

**Comment by m4rc1e** [comment]
I mean't #2067.

Getting MS Font Val to run on OS X requires me to patch the googlefonts.py specification manually. For OS X, I can't just exec the Ms Font Val .exe directly as we have it. https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/specifications/general.py#L159

You either have to call mono before it or use the OS X version of Font Validator, add to your path and remove the `.exe` part.

Imo, running the latest and greatest is not always the best. My current policy is to use the latest pip version.

**Comment by felipesanches** [comment]
There should be a "meta" check to ensure the latest stable pip release of fontbakery is being used. Surely for most endusers it would not necessarily need to be the latest from git. Even though, I wish that installing the latest from git at least once per week should be our goal, at least among us Google Fonts contractors. The sooner we get feedback about critical issues, the sooner we'll fix them. There's no excuse to postpone this important feedback by implementing workarounds / hand patching code to live with older versions of the tool.

**Comment by felipesanches** [comment]
There's an open pull request with improvements to the Font Validator install procedures, but it is failing Travis. Can you prioritize fixing that, @m4rc1e, so that I can merge it asap? What else do we need to get this sorted out without hacks?

**Comment by m4rc1e** [comment]
> There should be a "meta" check to ensure the latest stable pip release of fontbakery is being used. 

Those issues are in the latest [pip release](https://pypi.org/project/fontbakery/) which is 0.51.

> There's no excuse to postpone this important feedback by implementing workarounds / hand patching code to live with older versions of the tool.

Well its been the only way to get Ms Font Val to work for an eternity and I've been complaining about it for an eternity. Since there was no progress, I started #2067. I'll ask for time to get this done.

**Comment by anthrotype** [comment]
> a "meta" check to ensure the latest stable pip release of fontbakery is being used.

you could implement it by calling `pip` as subprocess (pip as a module does not have a supported public API), using the `search` command. This is what I get when I run `pip search fontbakery` from my console. You could capture the output, parse it and compare the INSTALLED vs LATEST version.
There are probably more elegant solutions but this was the easiest one that I could think of.

```
$ pip search fontbakery
fontbakery (0.5.1)  - Well designed Font QA tool, written in Python 3
  INSTALLED: 0.5.2.dev46+g24be1c1e.d20181016
  LATEST:    0.5.1
```

**Comment by felipesanches** [comment]
Quick thought: maybe we could label the checks that rely on network access and have a flag to optionally skip them.

**Comment by felipesanches** [comment]
`--offline`

**Comment by graphicore** [comment]
> to optionally skip them

Then the dashboard is incomplete. Well, the dashboard already skips `com.google.fonts/check/165`. The point is that this (both skipping or external I/O) is almost an equivalent of a DOOMSDAY as an outdated version of FB. At least for a reliably consistent quality of reports.

**Comment by felipesanches** [comment]
I  see that a check that contacts pip to get the latest available fontbakery version would be a non-idempotent check. We can live with that and we can make it emit an WARN letting the user know the online resource was not available to properly perform the check.

**Comment by felipesanches** [comment]
It seems reasonable to me that we could accept the "latest fontbakery version" check (and possibly any similar "latest dependency version" checks) as the single exception to a possible rule against network-dependent checks.

**Comment by graphicore** [comment]
> Sure! But how  …

Just some thoughts:

We would create some kind of a cache, that helps with the DOS problem. In the dashboard we'd create a centralized cache service, FB-cli could run in two modes: not using a cache and using a (local) cache and filling it if necessary, and we'd need a way to invalidate (delete) the cache.

The cache could also be called a "fixture". It could be nice to have an explicit thing that runs before fontbakery check runner, to create the fixture, if it is not there yet. I.e. a check could register an explicit method that fetches it's external resources and we can then use that to create the fixture. Probably a special `@condition` could be used for that, we mark it as `non-idempotent`, and then we can implement all kinds of things with it, i.e. all of the above.

One level deeper, we could also build and inject abstractions for network based i/o that can be used to create caches/fixtures with more detail/control, if needed. I.e. a `non-idempotent @condition` could just use a random number generator to create some kind of result, but with a special API, we could provide methods specific for each external service and can decide in the adapter how to handle each case.

Cache invalidation always is a tedious thing as well, no easy answers here.

**Comment by davelab6** [comment]
Agree about the meta check. File an issue and a PR :)

**Comment by felipesanches** [comment]
This is the issue. No need to open another one.
