### ISSUE TITLE
Broken check? com.google.fonts/check/034 (xAvgCharWidth)

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2095]
In https://github.com/google/fonts/pull/1720 the xAvgCharWidth fails, but the fonts were generated with glyphsapp or fontmake, so that suggests either our check is broken, or one of those compilers is broken. 

> 🔥 FAIL: Check if OS/2 xAvgCharWidth is correct.
> [com.google.fonts/check/034](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/034)
> 🔥 FAIL OS/2 xAvgCharWidth is 518 but it should be 533 which corresponds to the weighted average of the widths of the latin lowercase glyphs in the font

## Expected behaviour

The xAvgCharWidth check should not fail when a font is built with glyphsapp or fontmake or afdko's default build path. 

(Marking this as a p0 because its a false failure, that breaks the promise of reliability and trustworthiness we strongly aspire to)

**Comment by m4rc1e** [comment]
Glyphsapp recently changed the way it calculates xAvgChar width.

Where is xAvgChar width even used? I mean every editor/fontmake has their own way of calculating this value.

I'd prefer us to work out where it's used and if the differing values between editors cause any significant issues.

**Comment by felipesanches** [comment]
Are we extremely sure that this value is irrelevant nowadays? If so, then we should considering deprecating the check at all.

**Comment by felipesanches** [comment]
Otherwise, we should clarify which problems are caused by a bad value.

**Comment by davelab6** [comment]
Can't remember anything. Make it a warn and move on?

This should be a OT spec check, following the OT spec.

I wonder if Georg will explain why he changed his algo

**Comment by felipesanches** [comment]
@schriftgestalt any thoughts here?

**Comment by schriftgestalt** [comment]
from the OT spec:
> The value for xAvgCharWidth is calculated by obtaining the arithmetic average of the width of all non-zero width glyphs in the font.

**Comment by felipesanches** [comment]
do you have a different algo depending on the version of the OS/2 table?

```
# Since version 3, the average is computed using _all_ glyphs (with non-zero width) in a font.
# Version 2 and below only consider lowercase latin glyphs and space.
```

**Comment by felipesanches** [comment]
> This should be a OT spec check, following the OT spec.

It is! It is part of `os2.py` which is one of the table-specific python files that are included on the `opentype.py`, which is our "OpenType profile".

**Comment by davelab6** [comment]
I meant it should not be com.google.fonts/check/034 but an OpenType check id

**Comment by felipesanches** [comment]
> I meant it should not be com.google.fonts/check/034 but an OpenType check id

The reverse domain on a check id denotes who contributed the check implementation.

**Comment by felipesanches** [comment]
The only checks that do not have `com.google.fonts` in the checkid are those contributed by Dalton Maag and the ones that we'll port from Adobe's afdko. And also, hopefully, contributions from other people in the future.

**Comment by davelab6** [comment]
Maybe com.google.fonts/ot/check-name is better, then...

I think for 0.7 we should probably redo all the check IDs. We don't follow
our own guidelines for most of our checks.

I remember @graphicore had some ideas about this.
