### ISSUE TITLE
Generate documentation with Sphinx

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#2100]
@chrissimpkins said at https://github.com/googlefonts/fontbakery/pull/2027#issuecomment-430851664:

----

Coming along!  

<img width="1285" alt="x96g5-image" src="https://user-images.githubusercontent.com/4249591/47127093-b4ada000-d259-11e8-9801-eeef03b35989.png">

The existing free text docs render great:

<img width="1255" alt="1qjaz-image" src="https://user-images.githubusercontent.com/4249591/47127203-27b71680-d25a-11e8-9673-d30641843cad.png">

Will work on source file docs over the next couple of days.

**Comment by chrissimpkins** [comment]
Alright, here is where we are:

### Home

<img width="1256" alt="ieag4-image" src="https://user-images.githubusercontent.com/4249591/47162505-16a1f000-d2c2-11e8-9ef8-2da7765cd5ae.png">

### Markdown Renders

<img width="1233" alt="r5wwm-image" src="https://user-images.githubusercontent.com/4249591/47162537-23264880-d2c2-11e8-8efc-fa217f97d4d6.png">


### Autodoc parses of source files

<img width="1246" alt="bjiah-image" src="https://user-images.githubusercontent.com/4249591/47162574-32a59180-d2c2-11e8-8aa9-8e363c599829.png">

**Comment by chrissimpkins** [comment]
Everything appears to be working with the docstring parsing (on first glance) **except** the decorated specification functions under the fontbakery.specifications modules.  All autopopulated documentation files are blank across the entire set of modules under specifications:

<img width="1185" alt="yudlx-image" src="https://user-images.githubusercontent.com/4249591/47162781-a34cae00-d2c2-11e8-91bb-84415c67c234.png">

If I add a public class in one of the modules, it renders as expected so I think that we are dealing with a problem parsing functions with decorators:

<img width="1204" alt="s0c2i-image" src="https://user-images.githubusercontent.com/4249591/47162855-c9724e00-d2c2-11e8-8389-09297cdef60b.png">

[autodoc documentation](http://www.sphinx-doc.org/en/stable/usage/extensions/autodoc.html#directive-autofunction) suggests the following:

> f you document decorated functions or methods, keep in mind that autodoc retrieves its docstrings by importing the module and inspecting the __doc__ attribute of the given function or method. That means that if a decorator replaces the decorated function with another, it must copy the original __doc__ to the new function.
>
>From Python 2.5, functools.wraps() can be used to create well-behaved decorating functions.

I can verify that I can import the module and the docstring prints with a call of the `[function].__doc__` and that you are using `functools` to wrap the decorators in the callable module.  Not sure how to address this in a way that will automate the documentation with members and associated docstrings in these modules.  Thoughts?

**Comment by anthrotype** [comment]
https://docs.python.org/3/library/functools.html#functools.wraps

**Comment by anthrotype** [comment]
ah you _are_ already using `functools.wraps` sorry for the noise

**Comment by chrissimpkins** [comment]
no worries Cosimo.  have any thoughts?

**Comment by chrissimpkins** [comment]
We can add all of them in manually but it defeats the purpose of the automated parsing for an important part of this project that changes most frequently

**Comment by anthrotype** [comment]
not sure.. maybe those functions are wrapped twice? not sure if wraps is idempotent

**Comment by chrissimpkins** [comment]
Let's see if Felipe or Lasse have thoughts.  If not I will write them manually.  Thanks for having a look.

**Comment by chrissimpkins** [comment]
I should mention as well that autodoc does not raise any errors or warnings about this.  Happy to submit the PR as is if this is helpful.

**Comment by felipesanches** [comment]
Please, send the pull request and we'll try to help debugging this.

**Comment by felipesanches** [comment]
any time spent fixing the code to ensure it is fully automated is good use of time.

**Comment by graphicore** [comment]
I didn't expect that the `@check` and `@condition` decorators go down well with this. Maybe we can figure a way to plug in some custom renderer for these? Would be awesome. We can also just write something from scratch.

**Comment by chrissimpkins** [comment]
PR with the documentation changes is open #2106 if you want to have a look at the doc build.

Let me know what I can do.

**Comment by felipesanches** [comment]
> I didn't expect that the @check and @condition decorators go down well with this. Maybe we can figure a way to plug in some custom renderer for these? Would be awesome.

I think the most important part of documentation of checks is their rationale (and any other metadata they may have). This is currently not displayed to users on runtime, but it should be available and listed on the docs.

**Comment by chrissimpkins** [comment]
> I think the most important part of documentation of checks is their rationale (and any other metadata they may have). This is currently not displayed to users on runtime, but it should be available and listed on the docs

I agree.  It would be very helpful to have a reference of all of the tests that are performed and their rationale.  I won't be the best person to draft that document but I'd be happy to help merge it into the new docs if needed.

**Comment by chrissimpkins** [comment]
OK to close I think.  I pulled relevant information from this thread into new issue reports.
