### ISSUE TITLE
Automatic builds on Travis

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2101]
https://github.com/googlefonts/fontbakery/pull/2092#issuecomment-430288080

Sounds like we should have this :)

**Comment by felipesanches** [comment]
We do have this!

I think what happened there was that it took a bit longer for the build to come up. I have experienced this kind of slowdown on Travis from time to time. But in most cases the automatic builds start fast and run nicely.

**Comment by davelab6** [comment]
Sweet.
