### ISSUE TITLE
FontVal W0020: Tables are not in optimal order

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#2105]
FontVal has a check called "W0020 - Tables are not in optimal order"

This is the rationale found on FontVal sources:
```
OpenType fonts with TrueType outlines are most efficiently utilized by Windows when
the tables are ordered as follows (from first to last):
head, hhea, maxp, OS/2, hmtx, LTSH, VDMX, hdmx, cmap, fpgm, prep,
cvt, loca, glyf, kern, name, post, gasp, PCLT, DSIG

The initial loading of an OpenType font containing CFF data will be more efficient if the
following table ordering is used within the body of the font (from first to last):
head, hhea, maxp, OS/2, name, cmap, post, CFF, other tables (as convenient)

This efficiency results from the operating system being able to access commonly used
information without having to move between 'pages' of data in memory. Therefore,
the efficiency gained by Windows applies to implementations of the rasterizer on other
operating systems that use a paging architecture.
```

This does not specify which versions of Windows are affected by that. I would guess this only applies to very old operating systems running on old hardware. On moder systems, the performance hit must be negligible. So I suggest we black-list that check.

**Comment by HinTak** [comment]
The bulk of FontVal was written around 2002/2003 - with an update which was never made public in 2009. So XP/Vista for the earlier, and Windows 7 for the latter. Depending on whether you think windows 7 is old.

**Comment by davelab6** [comment]
I think fonttools ttx uses this order. If it doesn't, it should :) Cosimo,
do you know?

**Comment by anthrotype** [comment]
It sure does

**Comment by anthrotype** [comment]
But can be turned off with reorderTables=False
