### ISSUE TITLE
Turn off `MS-FonVal: The device table's DeltaFormat value is invalid` errors for variable fonts?

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#2109]
Noise from `ms-fonval` is causing my markdown output to exceed the length GitHub can display. Can we limit or turn off the `MS-FonVal: The device table's DeltaFormat value is invalid` errors for variable fonts?

## Observed behaviour

```
* :fire: **FAIL** MS-FonVal: The device table's DeltaFormat value is invalid DETAILS: LookupList, Lookup[0], SubTable[0](PairPos, fmt 1), PairSet[2], PairValueRecord[22], Value1, XAdvDeviceTable, DeltaFormat = 32768
* :fire: **FAIL** MS-FonVal: The device table's DeltaFormat value is invalid DETAILS: LookupList, Lookup[0], SubTable[0](PairPos, fmt 1), PairSet[2], PairValueRecord[23], Value1, XAdvDeviceTable, DeltaFormat = 32768
* :fire: **FAIL** MS-FonVal: The device table's DeltaFormat value is invalid DETAILS: LookupList, Lookup[0], SubTable[0](PairPos, fmt 1), PairSet[2], PairValueRecord[24], Value1, XAdvDeviceTable, DeltaFormat = 32768
* :fire: **FAIL** MS-FonVal: The device table's DeltaFormat value is invalid DETAILS: LookupList, Lookup[0], SubTable[0](PairPos, fmt 1), PairSet[3], PairValueRecord[0], Value1, XAdvDeviceTable, DeltaFormat = 32768
* :fire: **FAIL** MS-FonVal: The device table's DeltaFormat value is invalid DETAILS: LookupList, Lookup[0], SubTable[0](PairPos, fmt 1), PairSet[3], PairValueRecord[1], Value1, XAdvDeviceTable, DeltaFormat = 32768
* :fire: **FAIL** MS-FonVal: The device table's DeltaFormat value is invalid DETAILS: LookupList, Lookup[0], SubTable[0](PairPos, fmt 1), PairSet[3], PairValueRecord[2], Value1, XAdvDeviceTable, DeltaFormat = 32768
* :fire: **FAIL** MS-FonVal: The device table's DeltaFormat value is invalid DETAILS: LookupList, Lookup[0], SubTable[0](PairPos, fmt 1), PairSet[3], PairValueRecord[3], Value1, XAdvDeviceTable, DeltaFormat = 32768
* :fire: **FAIL** MS-FonVal: The device table's DeltaFormat value is invalid DETAILS: LookupList, Lookup[0], SubTable[0](PairPos, fmt 1), PairSet[3], PairValueRecord[4], Value1, XAdvDeviceTable, DeltaFormat = 32768
```

## Expected behaviour

Ok, I see this is a `*VF.ttf` file, don't worry about this.

**Comment by felipesanches** [comment]
I have just committed code yesteday that allows us to filter certain fontval checks when dealing with variable fonts. I can add this one to the black list as well.

I would like to silence checks that are too noisy. But I would also want to be sure the check is also not important. What's the meaning of this specific check?

**Comment by felipesanches** [comment]
`DeltaFormat = 32768` (same as 0x8000) means DELTA_INDEX, according to https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2

The FontVal problem description for this check only mentions the other values and possible valid ones. So apparently this means FontVal implementation is not up-to-date with more recent versions of the spec and that's why these spurious FAILs are being emitted. That's good enough reason to mute it.

**Comment by eliheuer** [comment]
My understanding of this `FAIL` is simply that `ms-fonval` doesn't fully know how to deal with variable fonts, and this `fail` is a result of that. I could be wrong and would like to understand this `fail` better.

**Comment by felipesanches** [comment]
It fails to understand a new valid value from a more recent version of the opentype spec. I have the impression that a whole lot of fval checks may have this kind of problem.

**Comment by HinTak** [comment]
If it is not up to date, file an issue at Microsoft's issue tracker.

**Comment by HinTak** [comment]
Fixed in https://github.com/HinTak/Font-Validator/commit/37b5e71ee29f6e0f38351a65e5efe36709f4a2f6

@eliheuer : please file an issue at the Microsoft issue tracker (not mine) next time. Nobody hear about these sort of issues, nobody fixes them. Thank you.

Cc: @davelab6

**Comment by eliheuer** [comment]
@HinTak Sure, will do. Is the preferred place to post issues https://github.com/Microsoft/Font-Validator/issues ?
