### ISSUE TITLE
com.google.fonts/check/has_ttfautohint_params should be done only if font is hinted using ttfautohint

### ISSUE THREAD

**Issue by santhoshtr** [googlefonts/fontbakery#2115]
If a font is not hinted(happens especially in the case of non-latin fonts), com.google.fonts/check/has_ttfautohint_params reports the check failure. 
Ref: https://github.com/smc/manjari/issues/1#issuecomment-431284512

That test should be skipped if the font is not hinted using ttfautohint

**Comment by felipesanches** [comment]
thanks, @santhoshtr !

**Comment by felipesanches** [comment]
we need to address the things described by @chrissimpkins 
 at: https://github.com/googlefonts/fontbakery/pull/2116#issuecomment-431674838
