### ISSUE TITLE
Add check for HVAR table in VFs

### ISSUE THREAD

**Issue by nyshadhr9** [googlefonts/fontbakery#2119]
## Observed behaviour

Not having a HVAR table can lead to costly text-layout operations on some platforms, which we want to avoid.

## Expected behaviour

Add a check for presence of HVAR table with valid values in all VFs. 

## Resources and exact process needed to replicate

https://docs.microsoft.com/en-us/typography/opentype/spec/otvaroverview#variation-data-tables-and-miscellaneous-requirements

**Comment by davelab6** [comment]
Thank you Nyshadh!

**Comment by felipesanches** [comment]
I assume that this is a GoogleFonts-specific check.

I will call it **com.google.fonts/check/VF/has_HVAR**. And all new variable font checks from now on will likely also have the same `/check/VF/something` naming structure. Unfortunately we are not supposed to change the name of the previous VF checks we already have.
