### ISSUE TITLE
Add a file system watcher for rapid local development

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#212]
Similar to the way Jeykll works for web development projects, many designers like to work on their projects locally.
- [ ] add a filesystem watcher, so if you run bakery locally and point it to a directory (instead of a git repo) then each time the UFOs change on disk, a bake process is run. 
- [ ] at the end of each build, as part of the `build finished` message, it would be good to show the total size of the `/builds` directory, with a tip about how to count the size of only the immediate children with `du`, so that as the builds dir grows the user knows to trim it :)

https://github.com/facebook/watchman can help with this

**Comment by felipesanches** [comment]
I consider this out of scope for FontBakery-core.
