### ISSUE TITLE
Enable Github Branch Protection?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2128]
## Observed behaviour

Google's standard [CONTRIBUTING.md#code-reviews](https://github.com/googlefonts/fontbakery/blob/master/CONTRIBUTING.md#code-reviews) says,

> All submissions, including submissions by project members, require review. We use GitHub pull requests for this purpose. 

## Expected behaviour

Today this is not enforced, but Github has a feature to help this policy stick. 

At https://github.com/googlefonts/fontbakery/settings/branch_protection_rules/new I can set some rules:

<img width="819" alt="screen shot 2018-10-25 at 10 11 21 pm" src="https://user-images.githubusercontent.com/261579/47540470-66288300-d8a3-11e8-978e-772bd525b3cb.png">

Should I enable this?

## Resources

* https://help.github.com/articles/enabling-branch-restrictions/
* https://help.github.com/articles/about-protected-branches/
* https://blog.github.com/2018-08-15-protected-branch-updates/

**Comment by felipesanches** [comment]
no, please don't do it.
There are several small and quick improvements that I make on a daily basis that do not really require such hard-requirement of code-reviews. This would make improving the code much harder.
