### ISSUE TITLE
MS-FontVal/Check-037: Needs support for GDEF Header, Version 1.3

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#2131]
## Observed behaviour
`com.google.fonts/check/037` returns the following `FAIL`: 
```
* FAIL: MS-FonVal: The version number is neither 0x00010000 nor 0x0001002 DETAILS: 0x00010003
```
Sometimes this is the only issue causing `com.google.fonts/check/037` to fail, so it would be nice to have this fixed.

## Expected behaviour
https://docs.microsoft.com/en-us/typography/opentype/spec/gdef Describes GDEF header version 1.3, which should be supported?

## Resources and exact process needed to replicate
Run fontbakery on a new variable font, example: https://github.com/eliheuer/orbitron-vf

**Comment by felipesanches** [comment]
please add a corresponding issue on the FontVal issue trackerso that upstream is informed about it.

**Comment by eliheuer** [comment]
Ok: https://github.com/Microsoft/Font-Validator/issues/66
