### ISSUE TITLE
skip com.google.fonts/check/072 if font is VTT hinted

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#2139]
At https://github.com/googlefonts/fontbakery/issues/2047#issuecomment-434849707 @laerm0 said:
----
Hey @felipesanches, I think we can skip 072 for VTT hinted fonts too. I think the best way to automatically skip this check is to turn it off is if FB finds a TSI5 table (which I've only really seen come out of VTT).

**Comment by felipesanches** [comment]
The solution here is to create a condition called is_VTT_hinted:

```python
@condition
def is_VTT_hinted(ttFont):
  # it seems that VTT is the only program that generates a TSI5 table
  return 'TSI5' in ttFont
```

And then use `not is_VTT_hinted` as a condition to check/072.

**Comment by laerm0** [comment]
Thanks!

**Comment by madig** [comment]
I just stumbled over this, as a font in preparation is flagged as needing smart dropout control, but the condition says this should not be checked for VTT-hinted fonts. It happens to be a VTT-hinted font. The condition tests for TSI5 tables, but that should not happen? TSI* tables are source formats, they are removed from release fonts, so the condition will never be honored for release fonts?!
