### ISSUE TITLE
Create Read the Docs account and publish Sphinx documentation

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/fontbakery#2145]
Associated issue report: https://github.com/googlefonts/fontbakery/pull/2106#issuecomment-435921265

Initial draft of Sphinx documentation merged in PR: #2106

**Comment by davelab6** [comment]
https://readthedocs.org/projects/font-bakery/ is now a thing, please lmk if I should change any setting

**Comment by chrissimpkins** [comment]
Looks great and built without issues.  You can find the site at http://font-bakery.readthedocs.io/

**Comment by davelab6** [comment]
One issue is that I don't see https://github.com/googlefonts/fontbakery/blob/master/docs/source/developer/writing-specifications.md in https://github.com/googlefonts/fontbakery/blob/master/docs/source/index.rst

**Comment by chrissimpkins** [comment]
Woops!  The Markdown file is in the docs/source/developer directory https://github.com/googlefonts/fontbakery/blob/master/docs/source/developer/writing-specifications.md

But it needs to be in the TOC on the home page so that is picked up for rendering.  I missed this.  I am going to add the Install documentation (currently missing and marked as TODO in docs) as it is currently drafted in the master branch to the [Install section](https://github.com/googlefonts/fontbakery/blob/master/docs/source/user/installation.md) tonight and will make sure that I add this too.
