### ISSUE TITLE
Register family check output as individual fonts?

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#2166]
While trying to make a reporter group per-font reports into sections and checks, I noticed that family checks are an annoying-to-deal-with edge case, because they embed which font a message object belongs to in-band (and only when the check does it).

I'd like to achieve something like this:
```
Spacing:
  Some spacing check:
    UFO1:
    - WARN: blah blah
    UFO2:
    - WARN: blah blah

  Some other spacing check (family check):
    UFO1:
    - WARN: blah blah
    UFO2:
    - WARN: blah blah
```
instead of 
```
Spacing:
  Some spacing check:
    UFO1:
    - WARN: blah blah
    UFO2:
    - WARN: blah blah

  Some other spacing check (family check):
    Family Check:
    - WARN: UFO1: blah blah
    - WARN: UFO2: blah blah
```
For this, the reporter currently needs intimate knowledge of where the checks store that information. Is there a better way?

**Comment by graphicore** [comment]
Not sure exactly what you mean. Is it, that in your second example the check is defined something like this: `def some_other_spacing_check(ufos)` and it is yielding the results of each ufo in one go?

You could try to: `def some_other_spacing_check(ufo, ufos)` which would call the check once for each ufo, though maybe you'd need to do the same calculations again for each call, thus:

Define a `@condition` `def family_spacing_analysis(ufos)` then  `def some_other_spacing_check(ufo, family_spacing_analysis)` and just yield the results for the current ufo stored in the return value of `family_spacing_analysis` the `@condition` would run just once and it's result would be cached.

**Comment by madig** [comment]
> Is it, that in your second example the check is defined something like this: def some_other_spacing_check(ufos) and it is yielding the results of each ufo in one go?

Yep. I'd like to have the check run on all fonts but return a separate check result dict for each, so that my reporter can be dumb and just treat everything as a check result for an individual font.

> Define a @condition def family_spacing_analysis(ufos) then def some_other_spacing_check(ufo, family_spacing_analysis) and just yield the results for the current ufo stored in the return value of family_spacing_analysis

Interesting idea. Will have a look, thanks.

**Comment by madig** [comment]
I don't think so, we settled on something or other internally.
