### ISSUE TITLE
Move FontVal check-wrap out of GF profile to its own profile

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2169]
## Observed behaviour

I am hearing from users privately that the Font Val check wrapper is confusing them because it warns about things in a way they can't make sense of (like glyph IDs which they can't match to anything in their font editor) or that are outright false negatives

## Expected behaviour

I expect we would not be shipping have any checks that are unclear or confusing any more. 

Therefore I propose we move the Font Val check out of the GF check profile to its own profile, until we can thoroughly review them all.

**Comment by felipesanches** [comment]
Sounds great! I agree with this proposal.

**Comment by felipesanches** [comment]
I have also updated the documentation to mention that now the wrapper is available via the new command:

```
fontbakery check-fontval *.ttf --verbose
```

**Comment by HinTak** [comment]
@davelab6 : FWIW, the bits of output from the FB wrapper that some users send to me is confusing to me too.

**Comment by m4rc1e** [comment]
> like glyph IDs which they can't match to anything in their font editor

Both FL and Glyphsapp can sort by ID.

![screen shot 2018-11-08 at 10 11 10](https://user-images.githubusercontent.com/7525512/48192054-a7f30800-e33e-11e8-8b68-25456cade6a2.png)
**Glyphsapp**

![screen shot 2018-11-08 at 10 10 38](https://user-images.githubusercontent.com/7525512/48192073-b0e3d980-e33e-11e8-991c-3a07d45f0c42.png)
**Fontlab**


I'm not sure of Robofont.

**Comment by davelab6** [comment]
> can sort by ID

What about the eg `.glyphs` file?

> the bits of output from the FB wrapper that some users send to me is confusing to me too

I'm not sure the direct FVal output is better. What should change in the FB wrapper?

**Comment by HinTak** [comment]
@davelab6 : one issue that came up was that message order are re-arranged (see https://github.com/Microsoft/Font-Validator/issues/65#issuecomment-436791711 and what follows)

**Comment by davelab6** [comment]
Got it! Thanks!
