### ISSUE TITLE
add instructions for pip install opentype-sanitizer to documentation

### ISSUE THREAD

**Issue by cjchapman** [googlefonts/fontbakery#2172]
Maybe I missed it, but I don't see `pip3 install opentype-santizer` mentioned in the documentation, e.g. here: https://font-bakery.readthedocs.io/en/latest/user/installation/install-macos.html

**Comment by felipesanches** [comment]
Installing fontbakery using pip (after version 0.6.0 pushed to PyPI yesterday) will automatically install as a dependency a package that wraps ots as a python module.

**Comment by cjchapman** [comment]
Ah, OK.

**Comment by felipesanches** [comment]
maybe you are still running an older version of fontbakery?
