### ISSUE TITLE
Wrong contour counts in glyphdata.py

### ISSUE THREAD

**Issue by mjlagattuta** [googlefonts/fontbakery#2178]
## Observed behaviour

When checking Inknut Antiqua, I was checking the Warnings for deviations from expected contours. There were two entries that to my knowledge are wrong: 'zerowidthjoiner' and 'zerowidthnonjoiner' both expect 1 contour, even though it should be 0.

## Expected behaviour

I expected both of these to be 0 contours, as they are both nonprinting characters, are zero-width, and to my knowledge have no countours.

## Resources and exact process needed to replicate

To replicate, [here](https://github.com/mjlagattuta/Inknut-Antiqua/blob/master/fonts/variable/InknutAntiquaBeta-VF.ttf) is the font file I was checking

**Comment by davelab6** [comment]
Sounds right
