### ISSUE TITLE
GF check 035 (ftxvalidator) WARNS when not available, should be ERROR

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2184]
```
com.google.fonts/check/035 Checking with ftxvalidator.

WARN  ftxvalidator returned an error code. Output follows :

b'ftxvalidator is not available!\n'
```

Why isn't that an error?

**Comment by HinTak** [comment]
I suppose the practical one like requiring an apple id (free registration) to download, and the usual Linux/open-source fanatic one, that not using a closed-source tool is all the better :-).

**Comment by HinTak** [comment]
Btw, ftxvalidator can probably be made to work on Linux, via darling.

**Comment by davelab6** [comment]
Additionally, ftxval didn't return that error code ;)

**Comment by felipesanches** [comment]
@davelab6 I gotta admit that I have indeed originally chosen WARN instead of ERROR because the dependency is non-free. A WARN subtly frames it as optional, rather than mandatory.

**Comment by felipesanches** [comment]
> Additionally, ftxval didn't return that error code ;)

agreed. I will investigate this issue and clarify the message.

**Comment by HinTak** [comment]
@davelab6 : well, that certainly begs the question - are you working towards making libre fonts work well on one of the major OSes?

**Comment by graphicore** [comment]
> Additionally, ftxval didn't return that error code ;)

Ah right, I get it. Well Font Bakery doesn't now, because that's a hack in the dashboard and technically `/bin/ftxvalidator` does return that ;-)

**Comment by graphicore** [comment]
PR #2199

**Comment by HinTak** [comment]
>> Btw, ftxvalidator can probably be made to work on Linux, via darling.

> Which sounds illegal to me.

It is no less and no more legal than running most windows software on wine. I have genuine Microsoft Windows on my laptop which is never used; and I own a Mac which is rarely used. I choose to run windows/mac software on emulation, because it is more convenient for me, having everything under Linux. I own a copy of Windows, and have apple hardware.
