### ISSUE TITLE
GF Check 130: Why is -20 the maximum italic angle?

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/fontbakery#2186]
## Observed behaviour

[Libre Caslon Italic](https://github.com/thundernixon/Libre-Caslon/tree/e26fcc13f576701299d8ab8f86e1600383307a2d/dist/2018-11-09-16_40) gets the following "fail" message:

> 🔥 FAIL: Checking post.italicAngle value.
>     - com.google.fonts/check/130
>     -  🔥 FAIL The value of post.italicAngle must be changed from -22.583 to -20. [code: >20 degrees]

However, the italic really does have an italic angle of more than 20 degrees. 

![image](https://user-images.githubusercontent.com/7355414/48292251-96495780-e447-11e8-8cca-a4f649765dad.png)

I can't find any specification that limits italicAngle to less than 20 degrees. The [MS Typography spec for `<post>`](https://docs.microsoft.com/en-us/typography/opentype/spec/post#header) simply says:

> Italic angle in counter-clockwise degrees from the vertical. Zero for upright text, negative for text that leans to the right (forward).

I imagine this is just a sanity check ... but calling it a "fail" seems like overkill.

## Expected behaviour

If there is no documented problem with >20° italic angles, we should either:

A. Remove this as a check 

or 

B. Make the >20° check into an "info" check, if we think people may have set it incorrectly when it's a high value. If this is the case, we might want to also adjust the message to reflect this objective – something like:

> :information_source: **INFO** The value of post.italicAngle is -22.583, which is significantly higher than most fonts. Check if the italic angle is set correctly. [code: >20 degrees]

**Comment by davelab6** [comment]
I think 20 is just made up as an absurdly high amount. Seems to be too low ;)

I think fail at 30 and warn at 20 is good. Should also check for negative values, if not already.

**Comment by thundernixon** [comment]
Is there documentation of the distinctions between fail/warn/info/pass, especially in context of what's expected for publication to the GFonts library? When I'm working, a `⚠️ WARN` feels like something in need of fixing, but maybe I'm just being too sensitive about the status symbols.

**Comment by m4rc1e** [comment]
I never understand why we sometimes limit ourselves to arbitrary values and provide no reason for it ;-)

The post table spec has no mention of there being a limit for this attrib, https://docs.microsoft.com/en-us/typography/opentype/spec/post

This check is actually made up of three separate checks, https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/specifications/googlefonts.py#L2484-L2522. I suggest we remove this part from the check.

**Comment by m4rc1e** [comment]
We should also remove this part, https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/specifications/googlefonts.py#L2492-L2498

There are fonts which slant in the opposite direction, http://fonds-perspektive.de/category/projekte/. I always find they look rather snazzy.

**Comment by davelab6** [comment]
> I never understand why we sometimes limit ourselves to arbitrary values and provide no reason for it ;-)

We check for sane values and the reason is taste by fiat. 

If checks like that are in the opentype profile, its bad, but if they are in the GF profile, the only thing bad is the lack of

**Comment by davelab6** [comment]
> Is there documentation of the distinctions between fail/warn/info/pass, especially in context of what's expected for publication to the GFonts library?

I guess I have described it in [the Typecon 2018 presentation deck](https://docs.google.com/presentation/d/14dU3cUXelwvpVokhKYmJ6jT51AASDaOFyEUSdxb0RAg/) but it does seem that this has not been properly documented. Let's track in another issue. 

Meanwhile, I made a PR to address this concern.
