### ISSUE TITLE
com.google.fonts/check/ttx-roundtrip: xml files are not removed once check has finished

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#2193]
The .xml files on my system are not removed once com_google_fonts_check_037 (Ms Font Val check) has finished.

![screen shot 2018-11-13 at 15 52 56](https://user-images.githubusercontent.com/7525512/48425187-36f78a00-e75c-11e8-8842-0b2d57fcf81d.png)

I'm running Fontbakery on OS X 10.13.6.
Fontbakery version 0.5.1.dev28+g39c4540c

**Comment by HinTak** [comment]
You sure that's from FontVal? I don't think it is possible to have output not in the "*.report.xml" form. Unless you rename the file after generation somehow.

**Comment by felipesanches** [comment]
That is not related to FontVal at all. Those XML files are left over from com.google.fonts/check/ttx-roundtrip

We should improve that check by adding a cleanup of the generated XML afterwards. Sorry about that.

**Comment by m4rc1e** [comment]
@felipesanches thanks for renaming the issue.
