### ISSUE TITLE
Grep DESCRIPTION.*.html for links, check they don't 404

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#220]
This is a non-font test, so the checker should have a module for that; also these checks should have a attribute for how freqently to run them (ie daily.)

**Comment by davelab6** [comment]
Here's how I ran this now, showing the output for the first family only:

```
$ for family in `ls -1 ~/fonts/*/*/DE*`; do echo $family; fontbakery-check-description.py $family; done
/Users/dcrossland/fonts/apache/aclonica/DESCRIPTION.en_us.html
note: FAIL: bakery_lint/fonttests/test_description.py: TestDescriptionHtmlEnUs.test_description_is_more_than_500b():  DESCRIPTION.en_us.html is more than 500 bytes : DESCRIPTION.en_us.html must have size larger than 500 bytes
note: FAIL: bakery_lint/fonttests/test_description.py: TestDescriptionHtmlEnUs.test_description_is_valid_html():  DESCRIPTION.en_us.html is not real html file : DESCRIPTION.en_us.html is not real html file
FAIL: test_description_is_more_than_500b: DESCRIPTION.en_us.html must have size larger than 500 bytes
FAIL: test_description_is_valid_html: DESCRIPTION.en_us.html is not real html file
...
```

This is broken in 4 ways:

- [ ] The duplication of lines is annoying. It looks like the 2 errors are repeated, once with the \@note decoractor and source code file included, and again without that information

- [ ] `FAIL: test_description_is_valid_html: DESCRIPTION.en_us.html is not real html file` is bogus. I didn't look at how it is determining this, but the DESCRIPTION files are html fragments, and the file in question - https://github.com/google/fonts/blob/master/apache/aclonica/DESCRIPTION.en_us.html - is perfectly valid.

- [ ] `FAIL: test_broken_links: http://ascendercorp.com is broken` This should be improved by giving the HTTP error code; this domain is a 301 redirect, and what I really am concerned about is 404s:  `http://gone.com is broken with HTTP error code 404`

- [ ] `FAIL: test_broken_links: mailto:astigma@astigmatic.com raises exception [InvalidSchema(u"No connection adapters were found for 'mailto:astigma@astigmatic.com'",)]` It should not raise an exception but fail on these, and say `Unable to check if email addresses are valid. Manually check $user@$host`

**Comment by felipesanches** [comment]
@davelab6 This is indeed still not working correctly. I'll work on fixing this one tomorrow.

**Comment by felipesanches** [comment]
The contents of the Aclonica's DESCRIPTION.en_us.html file are:

```<p>Aclonica is a strong and modern sans serif typeface with a slight deco/techno essence to it. Clean letterforms, a generous x-height for a friendlier feel and easily legible typestyle. Perfect for both display titling as well as body copy.</p>```

That's a snippet of HTML. But magic.from_file(f, mime=True) returns "text/plain"

I'll investigate that further.

**Comment by felipesanches** [comment]
Also, magic.from_file(f) returns "ASCII text, with no line terminators"

**Comment by davelab6** [comment]
magic won't help here because they are fragments. I suggest to simply grep for `<p>` as a basic check. Its possible lxml could quickly validate the fragment and if its bad just error and move on.

**Comment by felipesanches** [comment]
ok, good!

**Comment by felipesanches** [comment]
What about the requirement that "DESCRIPTION.en_us.html must have size larger than 500 bytes" ?

Should we keep this check? Does it make sense?

**Comment by felipesanches** [comment]
The rationale is that it must provide a longer/richer description?

**Comment by felipesanches** [comment]
Aclonica's description (that I pasted a few messages ago) has got 245 bytes...

**Comment by davelab6** [comment]
OK, the min can be 200 bytes; there should also be a max of 1000 bytes.
