### ISSUE TITLE
 com.google.fonts/check/033: CJK fonts should not be classed as monospace

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#2202]
I get the following for a CJK family

```
>> com.google.fonts/check/033 with (('font[0]', 'Xiaowei-Regular.ttf'),)
   Checking correctness of monospaced metadata.
 * FAIL: On monospaced fonts, the value of post.isFixedPitch must be set to 1 (fixed width monospaced), but got 0 instead. [code: mono-bad-post-isFixedPitch]
 * FAIL: On monospaced fonts, the value of OS/2.panose.bProportion must be set to 9 (proportion: monospaced), but got 0 instead. [code: mono-bad-panose-proportion]

   Result: FAIL

```

When I inspect the Apple CJK fonts and Source Han Sans, https://github.com/adobe-fonts/source-han-sans, they all have isfixedpitch set to 0. The character sets may also contain half width glyphs.

There's also this comment from kenlunde, https://github.com/adobe-fonts/source-han-sans/issues/154#issuecomment-223753000

**Comment by HinTak** [comment]
That depends
