### ISSUE TITLE
ERROR com.google.fonts/check/065 AttributeError: 'int' object has no attribute 'items'

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#2203]
## Observed behaviour

In http://35.225.170.228/report/a166a8f6-8668-412a-b9bd-c41b66547e8b

```
ERROR com.google.fonts/check/065 Is there kerning info for non-ligated sequences?

    ERROR
    Failed with AttributeError: 'int' object has no attribute 'items'
    traceback

      File "/usr/local/lib/python3.6/dist-packages/fontbakery/checkrunner.py", line 345, in _exec_check
        for sub_result in result:  # Might raise.
      File "/usr/local/lib/python3.6/dist-packages/fontbakery/specifications/gpos.py", line 58, in com_google_fonts_check_065
        for first, comp in ligatures.items():
```

## Expected behaviour

The `@conditon ligatures` (`shared_conditions`) does:

```
[...]
  except:
    return -1  # Indicate fontTools-related crash...
```

I guess we should expect the condition to return an integer sometimes. Also, maybe add a check to report the actual exception.

## Resources and exact process needed to replicate

Files should be upstream Slabo: https://github.com/TiroTypeworks/Slabo/tree/master/TTFs

**Comment by felipesanches** [comment]
![screenshot at 2018-12-02 19 34 02](https://user-images.githubusercontent.com/213676/49345266-712cbb00-f67a-11e8-8f42-ed03e69403ac.png)
