### ISSUE TITLE
Emit a FAIL when com.google.fonts/check/ttx-roundtrip  results in a parsing error (ExpatError) since a malformed XML most likely means an issue with the font

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#2205]
## Observed behaviour
http://35.225.170.228/report/36f73d26-a1a6-48e8-89ff-05ed386f7f77
or `$ fontbakery check-googlefonts -l ERROR ../fonts/ofl/abhayalibre/*` (with current google/fonts@master)

```
>> com.google.fonts/check/ttx-roundtrip with (('font[0]', '../fonts/ofl/abhayalibre/AbhayaLibre-Bold.ttf'),)
   Checking with fontTools.ttx
 * ERROR: Failed with ExpatError: not well-formed (invalid token): line 131405, column 12
           File "/home/commander/Projekte/fontdev/googlefonts/fontbakery/Lib/fontbakery/checkrunner.py", line 345, in _exec_check
             for sub_result in result:  # Might raise.
           File "/home/commander/Projekte/fontdev/googlefonts/fontbakery/Lib/fontbakery/specifications/general.py", line 765, in com_google_fonts_check_ttx_roundtrip
             f.importXML(font + ".xml")
           File "/home/commander/Projekte/fontdev/googlefonts/fontbakery/venv/lib/python3.6/site-packages/fontTools/ttLib/ttFont.py", line 336, in importXML
             reader.read()
           File "/home/commander/Projekte/fontdev/googlefonts/fontbakery/venv/lib/python3.6/site-packages/fontTools/misc/xmlReader.py", line 49, in read
             self._parseFile(self.file)
           File "/home/commander/Projekte/fontdev/googlefonts/fontbakery/venv/lib/python3.6/site-packages/fontTools/misc/xmlReader.py", line 74, in _parseFile
             parser.Parse(chunk, 0)
```

## Expected behaviour

Do not ERROR ? Maybe this is an issue in fonttools directly.

**Comment by graphicore** [comment]
Also with http://35.225.170.228/report/539a0077-275c-4cfd-88ad-170af3ae9585 `$ fontbakery check-googlefonts -l ERROR ../fonts/ofl/yaldevicolombo/*` from current google/fonts@master

**Comment by graphicore** [comment]
#2206 and this seem to be related somehow

**Comment by felipesanches** [comment]
This has no relation to #2206

**Comment by felipesanches** [comment]
![screenshot at 2018-11-17 19 31 44](https://user-images.githubusercontent.com/213676/48665959-34749780-eab0-11e8-957a-6fc84cffd35f.png)

![screenshot at 2018-11-17 19 31 03](https://user-images.githubusercontent.com/213676/48665960-39394b80-eab0-11e8-9faa-a42a0afe29cc.png)

Something is wrong at the name table entry with nameID=3, platID=3, encoding=1

**Comment by felipesanches** [comment]
![screenshot at 2018-11-17 19 36 57](https://user-images.githubusercontent.com/213676/48665990-f5931180-eab0-11e8-80bc-30908d40c50d.png)

![screenshot at 2018-11-17 19 37 09](https://user-images.githubusercontent.com/213676/48665991-fa57c580-eab0-11e8-82fb-4929d7105e85.png)

**Comment by felipesanches** [comment]
you need to remove those spurious zeroes (`\x00`) from that name table entry.

**Comment by felipesanches** [comment]
Since this is not a FontBakery issue, but actually a font-bug, I will close this issue.

**Comment by felipesanches** [comment]
On the other hand... I think we can detect this specific case of problem and emit a FAIL instead. With a more user friendly message before showing the raw error that was generated by ttx.

**Comment by anthrotype** [comment]
this is a long-standing fonttools issue: https://github.com/fonttools/fonttools/issues/71
I consider a limitation of fonttools that it emits invalid XML when some text contains control characters outside the accepted character range as defined in the XML spec.
We need to devise some alternative escaping mechanism (e.g. wrapping those characters with some custom defined XML elements like `<u>0001</u>`) and implement such scheme in our XMLReader and XMLWriter

**Comment by davelab6** [comment]
Yes that would be good!
