### ISSUE TITLE
ERROR com.google.fonts/check/098  The check <FontBakeryCheck:com.google.fonts/check/098> did not yield any status

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#2206]
## Observed behaviour

(venv) commander@ghoul:~/Projekte/googlefonts/fontbakery$ fontbakery check-googlefonts -l ERROR ../fonts/ofl/abhayalibre/*
[...]
>> com.google.fonts/check/098 with (('font[1]', '../fonts/ofl/abhayalibre/AbhayaLibre-ExtraBold.ttf'),)
   METADATA.pb font.name field contains font name in right format?
 * ERROR: The check com.google.fonts/check/098 did not yield any status

   Result: ERROR
```

## Expected behaviour

Do yield something.

## Resources and exact process needed to replicate

current google/fonts@master abhayalibre

**Comment by graphicore** [comment]
Also with http://35.225.170.228/report/539a0077-275c-4cfd-88ad-170af3ae9585 `$ fontbakery check-googlefonts -l ERROR ../fonts/ofl/yaldevicolombo/*` from current google/fonts@master

#2205 and this seem to be related somehow

**Comment by felipesanches** [comment]
That has no relation to #2205
