### ISSUE TITLE
Add tags for tests

### ISSUE THREAD

**Issue by xen** [googlefonts/fontbakery#221]
Currently tests are just informative and have no order. 

Tests should have some attributes that say how important the test is, and this should be done in a way that makes it easy to add other structured attributes later with other meanings:

- [x] mark priority: required/error/warning/note
- [x] color code this attribute in the test results tables, red/orange/yellow/blue
- [x] if required, abort the build if the test fails

**Comment by davelab6** [comment]
Closing as this will naturally happen during the reorg
