### ISSUE TITLE
com.google.fonts/check/102: copyright string pattern should check fonts as well

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#2210]
It would be great to have this check run on fonts as well. At the moment it just checks the METADATA.pb has the correct copyright string.

I want this because designers are not setting the copyright correctly in their upstream repos. Run Fontbakery on the following fonts to inspect, https://github.com/smc/manjari/releases/tag/Version1.700

**Comment by davelab6** [comment]
Agreed, p0

**Comment by m4rc1e** [comment]
This doesn't work for Rokkitt. Here is the upstream pr, https://github.com/googlefonts/RokkittFont/pull/4 and here is the pr to google/fonts https://github.com/google/fonts/pull/1868

PR to upstream thinks copyright is good, whilst it fails google/fonts.
