### ISSUE TITLE
PyPI needs a more detailed project description

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#2225]
## Observed behaviour

![screen shot 2018-11-26 at 10 05 33 am](https://user-images.githubusercontent.com/5162664/49022578-2f27e480-f163-11e8-86b5-ed1e2e1254b7.png)

## Expected behaviour

`svgis` is one example of a project with a helpful project description:
[https://pypi.org/project/svgis/](https://pypi.org/project/svgis/)

![screen shot 2018-11-26 at 10 16 51 am](https://user-images.githubusercontent.com/5162664/49023105-6a76e300-f164-11e8-9b6d-4d46fccb62d5.png)

**Comment by felipesanches** [comment]
Will only be seen after next Monday's release. Please re-open the issue if after the 0.6.4 release the PyPI page still needs further tweaks. Thanks for the tip, @eliheuer!
