### ISSUE TITLE
fontbakery 0.6.3 installed from PyPI doesn't run MS-FontVal

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#2226]
## Observed behaviour

I installed the recently released `fontbakery 0.6.3` from PyPI today and noticed I wasn't getting a fail for `com.google.fonts/check/037`, this seemed strange since I was not passing this test before installing the new update. I investigated by running the individual check and got the following result: 

![screen shot 2018-11-26 at 7 18 44 pm](https://user-images.githubusercontent.com/5162664/49051200-d41edd80-f1b4-11e8-9dc1-4eb64aff89d1.png)

## Expected behaviour

I'm not sure what is going on here. Was the ms-fontval test moved or changed in some way in this release? I don't have time to dig into this now, but will investigate further if this is still unresolved tomorrow.

## Resources and exact process needed to replicate

I'm using `fontbakery 0.6.3` installed from PyPI.

**Comment by davelab6** [comment]
in the 0.6.0 [release notes](https://github.com/googlefonts/fontbakery/blob/master/CHANGELOG.md#060-2018-nov-08) @felipesanches wrote, 

> moving FontVal wrapper to a separate spec (issue #2169)

That says to run

    fontbakery check-fontval *.ttf --verbose
