### ISSUE TITLE
Travis failing?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2228]
## Observed behaviour

Travis failing flake8 on master, https://travis-ci.org/googlefonts/fontbakery/jobs/459767778

<img width="1552" alt="screen shot 2018-11-27 at 3 48 02 pm" src="https://user-images.githubusercontent.com/261579/49116768-e011aa80-f25b-11e8-9efd-6963824e4ca3.png">

## Expected behaviour

Travis passes :)

**Comment by felipesanches** [comment]
yep. It seems that the linter got upgraded with a new check while we were performing a new release. (the actual PRs that we merged all passed Travis builds) I'll take care of addressing that. Thanks for the reminder.

**Comment by felipesanches** [comment]
These are the things we need to fix:

<img width="937" alt="captura de tela 2018-11-28 as 02 18 27" src="https://user-images.githubusercontent.com/213676/49128765-f8adaf00-f2b3-11e8-9692-eb2e1fec70c8.png">

They're not all new linter-checks. I am not sure how that happened.
