### ISSUE TITLE
Output for check 174

### ISSUE THREAD

**Issue by mjlagattuta** [googlefonts/fontbakery#2235]
## Observed behaviour

Fonts with GSUB feature variations will fail to be instantiated by varLib.mutator since they are not yet supported. This yields a FAIL in fontbakery when checking the font even though there is nothing wrong with the font file itself

## Expected behaviour

As instantiating with mutator is very important I think that it is okay to keep the result as a FAIL, but I think the message should mention that it is expected to fail if the font is using feature variations. 

Ideally fontbakery could check if the font is using feature variations, and if so, run check 174 with that stripped out, and if that stripped version of the font can be instantiated, then downgrade the result to WARN

## Resources and exact process needed to replicate

Came across this when checking Expletus Sans [here](https://github.com/mjlagattuta/Expletus-Sans/tree/master/fonts/variable)

**Comment by laerm0** [comment]
bump @felipesanches 😁

**Comment by simoncozens** [comment]
The mutator can now generate these files, and your font passes this check.
