### ISSUE TITLE
Rename checkIDs to conform to recommendations (and test they remain so)

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2238]
## Observed behaviour

Most GF check IDs are in a numeric form, that we don't recommend. Eg [`com.google.fonts/check/018`](https://github.com/felipesanches/fontbakery/blob/d825e128447dbaecf640a96a46a851b3a3c748a8/Lib/fontbakery/specifications/googlefonts.py#L530-L557)

## Expected behaviour

- [x] We should both rename specs to profiles (#2091) and rename checkIDs to follow our own recommendations.

Eg `com.google.fonts/check/018` becomes `com.google.fonts/check/vendor-ids`

@graphicore and @felipesanches had some thoughts about how to do this, but I think we should do it soon.

However, since its a pretty big change, I think both should be done in the 0.7.0 release. Maybe at the end of December 2018?

- [x] Additionally we should have code tests that do some basic heuristic/regex testing to try to keep checkIDs on-point in the future

**Comment by felipesanches** [comment]
Keep the `check` in the ID because it identifies the "type of object" we're dealing with. Nowadays it seems redundant because all we have in Font Bakery are checks. But in the past we had other kinds of objects. For instance, in the future we might want to give fixers a second try.

**Comment by graphicore** [comment]
> Keep the `check` in the ID

Yeah, it's future proof :-)

**Comment by davelab6** [comment]
Its also very verbose, and simplicity and brevity are virtues - there's nothing wrong with strong defaults being implicit. I prefer

    com.google.fonts/font/name/vendor-ids
    com.google.fonts/fix/font/name/vendor-ids

to

    com.google.fonts/check/font/name/vendor-ids
    com.google.fonts/fix/font/name/vendor-ids

:)

I like the scope idea; since we (should) have checks for fonts, families, superfamilies, metadata, descriptions, and all the other pieces that go into a release; and then we can refer to checkIDs with simple regexes. 

Seems like we need a collaborative spreadsheet with cols like this:

| current checkID | scope | slug name |
| --- | --- | --- |
| com.google.fonts/check/018 | font | vendor-ids |

**Comment by davelab6** [comment]
And perhaps all GF checks in a scope can go into their own files, so we avoid these gargantuan check file? :)

    com.google.fonts/font.py
    com.google.fonts/metadata.py
