### ISSUE TITLE
brainstorm a good set of new checkid values

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#2239]
We're considering changing check IDs to get rid of the legacy numbered ids such as **com.google.fonts/check/001**.

We should commit to some sort of regular structure for those check IDs so that they are easy to remember for users (CLI and dashboard).

In order to figure out what works well, I'd like to suggest that we try to come up with suggestions for the new names for the whole set of checks before we actually make it effective.

One way to deal with it can be a work-in-progress pull-request that adds new checkid suggestions to the check decorators (via a custom metadata entry or even just a plain comment)

**Comment by graphicore** [comment]
I just posted into #2238 which issue should we use ;-)

**Comment by felipesanches** [comment]
This task is specifically for the process of brainstorming a set of new names before making it effective and set in stone forever. It is our chance to experiment before a new (and hopefully definitive) hard-commitment.

**Comment by felipesanches** [comment]
This issue was too "meta".
