### ISSUE TITLE
VF check needed for named weight instances

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2258]
## Observed behaviour

Markazi Text, not Comfortaa, has named instances had non-standard axis values: For example Medium instance for Markazi was at 491 and not 500.

We can avoid this problem through extra data in the avar table.

## Expected behaviour

FB fails fonts with weight axis named instances not at hundred values

**Comment by felipesanches** [comment]
I'll call it **com.google.fonts/check/varfont_weight_instances**

**Comment by davelab6** [comment]
Winner
