### ISSUE TITLE
Deprecate FontForge checks - Implement our own native glyf checks.

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/fontbakery#2261]
original title of this issue was: **FontForge checks skipping, even though FontForge command line tools are installed**

## Observed behaviour

I have installed FontForge following @m4rc1e's [FontBakery installation instructions for Mac](https://github.com/m4rc1e/fontbakery/blob/master/INSTALL_MAC.md).

It seems to be correctly installed. In the same virtual environment I'm running FontBakery checks in, this is the result of running `fontforge -v`:

```
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 20:54 UTC  5-Dec-2018-D.
 Based on source from git with hash:
fontforge 20:54 UTC  5-Dec-2018
```

However, FontForge checks aren't running with FontBakery.

<details>
<summary>:zzz: <b>SKIP:</b> FontForge validation outputs error messages?</summary>

* [com.google.fonts/check/038](https://github.com/googlefonts/fontbakery/search?q={checkid})
* :zzz: **SKIP** Unfulfilled Conditions: fontforge_check_results

</details>
<details>
<summary>:zzz: <b>SKIP:</b> FontForge checks.</summary>

* [com.google.fonts/check/039](https://github.com/googlefonts/fontbakery/search?q={checkid})
* :zzz: **SKIP** Unfulfilled Conditions: fontforge_check_results

</details>## Expected behaviour

I expect to get FontForge checks. I'm not quite sure how to debug what's failing.

## Resources and exact process needed to replicate

This is likely specific to my computer's current setup. However, it's happening with the current state of [Encode Sans](https://github.com/thundernixon/Encode-Sans/tree/da493a1aed3808a2d6c65c719315945dd73d6f96).

Hopefully, if I can get a few minutes of Marc's time (or someone else's time), I can figure out what is wrong, then update and close this issue.

**Comment by m4rc1e** [comment]
I'm pretty sure headless fontforge is py2 only. Since we upgraded fontbakery to py3 only, these tests are broken.

I would love us to write our own glyf tests

**Comment by felipesanches** [comment]
Let's specify here, then, what are we supposed to be looking for on our native-python glyf checks.

**Comment by m4rc1e** [comment]
• glyph has correct contour directions
• glyph has no transformed composites
• glyph has no intersecting contours (for statics only)

Just off the top of my head. There may be more I can think of.

**Comment by thundernixon** [comment]
Would outline warnings apply to this area? We could potentially run checks similar to Red Arrows or FontLab Font Audit – especially
- inflected curves (not always a major issue, but they can indicate outline problems)
- kinks in variable interpolations (I would hope for the tolerance to be slightly higher than FontAudit has it, though.

Then again, these checks might just be better to leave as more of a "design" step, in software that is more suited to it (font editors).

**Comment by HinTak** [comment]
Not to discourage you: the last estimate of the c# part of FontVal is 18 months of full-time work (done many years ago by Microsoft folks). 1/3 of FontVal's C# code is the glyf test. I.e. It will take somebody working full-time for 6 months to replicate that work. I assume fontforge's glyf test is of equivalent effort. Cc @davelab6 . If you have nothing better to do for 6 months, by all means, spend your own time on it. Personally I's say fix /create the fontforge python 3 binding. Or just use fontforge/fontval as they are, and be happy that the work is already done, and twice also. Do it a 3rd time if you have 6 months of your own time to spare...

**Comment by frank-trampe** [comment]
Was there an issue compiling FontForge against Python 3 in your environment? If so, please report so that I can fix it. Much easier than starting from zero.

**Comment by HinTak** [comment]
@frank-trampe : I have since learned that python 3 binding of fontforge exists, so I assume the earlier complaint from @m4rc1e must be referring to headless-ness . That I think may be mistaken? Can't imagine you let python 3 binding differ from python 2 binding by that.

**Comment by felipesanches** [comment]
> Was there an issue compiling FontForge against Python 3 in your environment? If so, please report so that I can fix it. Much easier than starting from zero.

I came back to this problem earlier this week. I tried to compile FontForge with python 3 on Debian stretch. By doing `PYTHON=3.7 ./configure` I got it built sucessfully. The python scripting checks all pass when doing `make check`. But after `sudo make install`, I tried to run `import fontforge` on a python 3 interpreter and got exactly the same problem described at https://github.com/fontforge/fontforge/issues/2966 It seems to load an "empty" module.

Then I looked more carefully at the testsuite and I noticed that on `fontforge/tests/testsuite.at`, this is how python checks are invoked:
```
#--------------------------------------------------------------------------
# Fontforge Python Scripting test functions

m4_defun([run_python],[(${abs_top_builddir}/fontforgeexe/fontforge -lang py -script "${abs_srcdir}/$1" "$2" || /bin/false)])
```

It means that the check code is not running on a standalone python interpreter, but by invoking fontforge which then does something which I presume is to load its embedded copy of the python interpreter, or something like that.

**Comment by felipesanches** [comment]
This is not really a P0 issue, unless someone is able to pin-point what was critically important in the fontforge checks that we now lack natively in FontBakery.

**Comment by simoncozens** [comment]
The fontforge checks are now dead, and nobody seems to have missed them.
