### ISSUE TITLE
ots-sanitize warning: STAT Axis value out of range

### ISSUE THREAD

**Issue by mjlagattuta** [googlefonts/fontbakery#2267]
## Observed behaviour

When checking Cabin, linked VFs and final VFs I get this WARN message from ots-sanitize:
```
>> com.google.fonts/check/036 with (('font[0]', 'VF-final/Cabin-VF.ttf'),)
   Checking with ots-sanitize.
 * WARN: ots-sanitize passed this file, however warnings were printed:

WARNING: STAT: Axis value nameID out of range


   Result: WARN
```

## Expected behaviour

I checked the `<name>` and `<STAT>` tables in `ttx` and was unable to find a mismatched name ID, which is what I take the message to mean. Please correct me if I am wrong :)

I would expect the output to reference the name ID that was out of range so that it is easier to track what is causing the issue.

## Resources and exact process needed to replicate

Upstream fonts [here](https://github.com/mjlagattuta/Cabin/tree/master/fonts)

**Comment by m4rc1e** [comment]
If you're sure it's ok, I would post an issue to https://github.com/khaledhosny/ots/issues and add a test case.

**Comment by mjlagattuta** [comment]
For this font, the name ID is fine and adheres to the spec. Closing as this is an [ots issue](https://github.com/khaledhosny/ots/issues/180)
