### ISSUE TITLE
URLs in each check don't actually lead to check in repo

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/fontbakery#2272]
## Observed behaviour

Each check in a gh markdown fontbakery output has a URL that I can click.

No matter what one I click, it leads me to a search in the FontBakery repo of just the literal query `checkid`. 

![image](https://user-images.githubusercontent.com/7355414/50168162-cb539000-02b8-11e9-9c7f-bd56e0e56c6b.png)

## Expected behaviour

Clicking the URL in a check should take me to a search of check in the check specification, so I can see where the check is in the spec code and whether there are any issues involving the check.

## Resources and exact process needed to replicate

Use the current fontbakery to run a test with the flag `--ghmarkdown`. Then, click any of the URLs.

You can also simply see the output of a recent check at https://raw.githubusercontent.com/thundernixon/Encode-Sans/master/fonts/encodesans/EncodeSans-VF-fontbakery-report.md

Each check has a line like:

```
* [com.google.fonts/check/fontbakery_version](https://github.com/googlefonts/fontbakery/search?q={checkid})
* :information_source: **INFO** fontbakery (0.6.4)  - Well designed Font QA tool, written in Python 3
  INSTALLED: 0.6.5.dev4+gce698f3a.d20181205
  LATEST:    0.6.4

* :bread: **PASS** Font Bakery is up-to-date
```

Notice the end of the URL is `{checkid}` rather than a check number. This yields a search for `{checkid}`.

---

I've found the problem: a variable is getting broken by a line break in an formatted string (f string). I'm doing a PR right now. :)

**Comment by felipesanches** [comment]
thanks!
