### ISSUE TITLE
DeprecationWarning: method 'getbytes' on one of our dependencies

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#2281]
![screenshot at 2019-01-14 13 59 43](https://user-images.githubusercontent.com/213676/51124116-718da980-1815-11e9-9694-ad1ec8d7389c.png)

**Comment by felipesanches** [comment]
I think that this relates to the `fs` package which is installed as a dependency of our "ufo sources" profile.

**Comment by felipesanches** [comment]
@madig, can you take a look at it, please?

**Comment by madig** [comment]
Happens in fonttools ufoLib code. May be fixed in the next fonttools version. Feel free to ignore.

**Comment by felipesanches** [comment]
thanks for the clarification!
