### ISSUE TITLE
github pages branch has been blocking clean merges of pull requests

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#2283]
I can only "rebase and merge" a pull request by over-riding the warning that building the ghpages branch on travis did not suceed.

![screenshot at 2019-01-14 14 16 00](https://user-images.githubusercontent.com/213676/51125108-d0542280-1817-11e9-9a97-5974cc706cad.png)

That's been happening since circa mid-december 2018.
We need to tweak the travis setup to ignore the ghpages branch.

**Comment by felipesanches** [comment]
All we have in ghpages is a redirect:

![screenshot at 2019-02-14 18 40 15](https://user-images.githubusercontent.com/213676/52816299-dfd5be00-3098-11e9-896b-199068da7747.png)

The index.html also includes links to the old versions of the dashboard, and the gh-pages branch has the source code for that. But the page redirects so quickly to the new dashboard landing page that I suppose probably no-one really clicks those old links.

**Comment by felipesanches** [comment]
I have been investigating the TravisCI issue and found some people with similar problems since October 2018, such as:

https://github.com/travis-ci/travis-ci/issues/10187

**Comment by felipesanches** [comment]
I was unsure, so I also turned off "Build pushed branches" on the Fontbakery github repo settings page, but it did not seem to fix the problem. Anyway, I think it is good to only trigger Travis builds on pull-requests, so I will leave it that way.

![screenshot at 2019-02-14 18 44 21](https://user-images.githubusercontent.com/213676/52816591-87eb8700-3099-11e9-92f0-d0614e699e78.png)

**Comment by felipesanches** [comment]
This Github help page describes something that can serve as a workaround:

https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

![screenshot at 2019-02-14 18 46 52](https://user-images.githubusercontent.com/213676/52816713-c4b77e00-3099-11e9-8b60-05e8aec19999.png)

We may add the CNAME and a very simple index.html with a redirect to our `docs/` directory on master branch; and switch the GitHub pages setting to get the page content from the master branch. And then this may stop requiring a build of the gh-pages branch.

I hope. :-P

**Comment by felipesanches** [comment]
I have opened a dummy pull request for testing that. I may close it and reopen it a few times while testing this new setup. Please ignore those tests, such as this one: #2350

**Comment by felipesanches** [comment]
I merged the Github Pages index redirect into the master branch. As a result I got this email:

![screenshot at 2019-02-14 19 36 07](https://user-images.githubusercontent.com/213676/52819200-a608b580-30a0-11e9-9363-f3ebcf4f7e72.png)

The fontbakery.com webpage is working but if it fails, we'll know it was caused by the problem described in this email and we may have to bring back the setup on the gh-pages branch or address the IP issue (I have no idea yet how to address that).

**Comment by felipesanches** [comment]
hmmm... maybe the solution could be editing the settings of the github webhooks for TravisCI...

Maybe ticking "Page builds - Pagessite built." is what we want?

![screenshot at 2019-02-14 19 43 16](https://user-images.githubusercontent.com/213676/52819642-bb321400-30a1-11e9-908d-37399bb56d23.png)

**Comment by felipesanches** [comment]
Using the Github Status API I have inspected what's the current status of the latest commit in a given pull request and that's what I got:

https://api.github.com/repos/googlefonts/fontbakery/commits/805a3ae7186d7925a3d163be65ae032533232332/statuses

**Comment by felipesanches** [comment]
Initially I see 3 statuses:
* Two with `context: "continuous-integration/tracis-ci/pr"` /  `description: "The Travis CI build is in progress"`
* and one with `context: "googlebot"` / `description: "All necessary CLAs are signed"`

![screenshot at 2019-02-14 20 14 24](https://user-images.githubusercontent.com/213676/52821568-131f4980-30a7-11e9-9649-dee415e20fb4.png)

**Comment by felipesanches** [comment]
Then after a while two more statuses show up: one additional `"The Travis CI build is in progress"` and then the second one says `"The Travis CI build passed"` and `status: success`.

Presumably we have a couple of statuses for Travis because we have two build targets (namely, the linters and our code-tests)

![screenshot at 2019-02-14 20 26 23](https://user-images.githubusercontent.com/213676/52821752-ab1d3300-30a7-11e9-8e5e-32c8229fc8da.png)

So, it seems we are actually getting no status update from the `"github/pages"` context at all...

**Comment by felipesanches** [comment]
This is all very confusing and frustrating... :-(

**Comment by chrissimpkins** [comment]
I may have misunderstood this issue but I think that `github/pages` status notice is a Github Pages build status message rather than a Travis build status?  Can you turn off the Github pages setting on the Github side to deactivate the build that is hanging? Repository `Settings > Github Pages > Source`.  

<img width="398" alt="bjdbe-image" src="https://user-images.githubusercontent.com/4249591/52825659-929f1f80-308b-11e9-877a-bcbd89a6eb6d.png">

**Comment by felipesanches** [comment]
ok let's try that :-)

**Comment by felipesanches** [comment]
haha, nope. Weirdly the option to disable github pages is disabled :-P

![screenshot at 2019-02-14 22 11 29](https://user-images.githubusercontent.com/213676/52825836-41f0ec00-30b6-11e9-90df-9d1a0e2b83ba.png)

**Comment by chrissimpkins** [comment]
Strange, maybe that's a permissions issue on the repository?  You should be able to turn off Pages on a repo.

**Comment by chrissimpkins** [comment]
Wonder if it is trying to build the Sphinx source as a Jekyll site for some reason.  There are no Jekyll config files in the docs directory.  Bizarre.  Does the build status message ever time out and fail or end up succeeding?

**Comment by felipesanches** [comment]
it seems to keep waiting forever.

**Comment by felipesanches** [comment]
experimenting with temporarily removing sphinx code did not make any difference.

**Comment by chrissimpkins** [comment]
Maybe Dave can turn off Pages for the repo?

**Comment by felipesanches** [comment]
It would indeed be helpful to, at least temporarily, have github pages disabled in order to figure out what's going on. Can you do it, @davelab6 ?

**Comment by davelab6** [comment]
OK, this is how it was:

![screen shot 2019-02-15 at 2 54 25 pm](https://user-images.githubusercontent.com/261579/52881171-e19f9000-3131-11e9-8004-c151037c0fd5.png)

So, I branch the `gh-pages` branch to an archive branch, and then I went to the All Branches page and deleted it, plus other stale branches that were used for merged/closed PRs:

![screen shot 2019-02-15 at 2 55 41 pm](https://user-images.githubusercontent.com/261579/52881172-e19f9000-3131-11e9-9e0d-1fb73af16902.png)

So the All Branches that now looks like this:

![screen shot 2019-02-15 at 2 55 49 pm](https://user-images.githubusercontent.com/261579/52881173-e2382680-3131-11e9-9a2d-a249026b5efe.png)

And I disabled the GitHub Pages feature:

![screen shot 2019-02-15 at 2 56 16 pm](https://user-images.githubusercontent.com/261579/52881174-e2382680-3131-11e9-83eb-9f42bc4a6233.png)

I will update the DNS for the domain, and then reenable GitHub Page from the `master@/docs` branch/folder option.

**Comment by felipesanches** [comment]
thanks, @davelab6!

Let's hope this works ;-)

**Comment by simoncozens** [comment]
I think thi sis no longer an issue; we don't use Travis any more and the gh-pages build is working.
