### ISSUE TITLE
Check 157, 158 (& 156, 161, & 162?) fail VFs when they have a different default instance than 'Regular'

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/fontbakery#2297]
## Observed behaviour

I'm updating my font name tables to use the default instance for nameID 2, which is triggering a `FAIL` for Check 157 `FONT_FAMILY_NAME` and Check 158 `FONT_SUBFAMILY_NAME`, which I believe to be incorrect for a variable font.

My VF, Signika-Light.ttx has a default instance of Light. Therefore, gftools `fix-vf-meta` sets the first two name IDs as this:

```
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Signika
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Light
    </namerecord>
```

But this results in these two checks failing:

<details>
<summary>:fire: <b>FAIL:</b> Check name table: FONT_FAMILY_NAME entries. </summary>

* [com.google.fonts/check/157](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/157)
* :fire: **FAIL** Entry [FONT_FAMILY_NAME(1):WINDOWS(3)] on the 'name' table: Expected 'Signika Light' but got 'Signika'.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Check name table: FONT_SUBFAMILY_NAME entries. </summary>

* [com.google.fonts/check/158](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/158)
* :fire: **FAIL** Entry [FONT_SUBFAMILY_NAME(2):WINDOWS(3)] on the 'name' table: Expected 'Regular' but got 'Light'. [code: bad-familyname]
</details>
</br>

UPDATE: After another look, I think that checks 95, 156, 161, & 162 are also getting incorrectly triggered by this VF naming scheme. In each of these tests, FontBakery is checking non-RIBBI fonts for nameIDs 16 & 17 ("typographic names" for apps like InDesign). However, I don't think these are needed in a non-RIBBI-labeled VF, because the family name will already be correct (e.g. `Signika`) rather than a combined name (e.g. `Signika Light`).

<details>
<summary>:fire: <b>FAIL:</b> METADATA.pb font.name value should be same as the family name declared on the name table.</summary>

* [com.google.fonts/check/095](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/095)
* :fire: **FAIL** This font lacks a TYPOGRAPHIC_FAMILY_NAME entry (nameID=16) in the name table. [code: lacks-entry]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Font has all mandatory 'name' table entries ?</summary>

* [com.google.fonts/check/156](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/156)
* :fire: **FAIL** Font lacks entry with nameId=16 (TYPOGRAPHIC_FAMILY_NAME)
* :fire: **FAIL** Font lacks entry with nameId=17 (TYPOGRAPHIC_SUBFAMILY_NAME)

</details>
<details>
<summary>:fire: <b>FAIL:</b> Check name table: TYPOGRAPHIC_FAMILY_NAME entries. </summary>

* [com.google.fonts/check/161](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/161)
* :fire: **FAIL** non-RIBBI fonts must have a TYPOGRAPHIC_FAMILY_NAME entry on the name table. [code: non-ribbi-lacks-entry]
</details>
<details>
<summary>:fire: <b>FAIL:</b> METADATA.pb font.name value should be same as the family name declared on the name table.</summary>

* [com.google.fonts/check/095](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/095)
* :fire: **FAIL** This font lacks a TYPOGRAPHIC_FAMILY_NAME entry (nameID=16) in the name table. [code: lacks-entry]
</details>
<details>
<summary>:fire: <b>FAIL:</b> Check name table: TYPOGRAPHIC_SUBFAMILY_NAME entries. </summary>

* [com.google.fonts/check/162](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/162)
* :fire: **FAIL** non-RIBBI fonts must have a TYPOGRAPHIC_SUBFAMILY_NAME entry on the name table. [code: non-ribbi-lacks-entry]

</details>
</br>

## Expected behaviour

Check 157 is correctly checking that a _static_ Signika Light has `Signika Light` in nameID 1, so it doesn't interfere in RIBBI style linking. In static fonts, only the regular, italic, bold, & bold italic fonts should have simply the family name in nameID 1, so that their key style names can be in nameID 2.

However, as far as I know, that is no longer applicable to a VF, which should use the family name in nameID 1 and the default style in nameID 2.

So, I would expect this check to run differently on VFs, not throwing a fail for nameIDs 1 & 2 as shown above.

This is connected to #2214. I have only found it now because I am changing my nameID `2`s to the default instance name, rather than "Regular."

## Resources and exact process needed to replicate

Here's [the Signika project as of Jan 18, 2019](https://github.com/thundernixon/Signika/tree/0c95801d09770fb83584ba5acd2474f76470abb8)).

Here's [the full fontbakery check in question](https://github.com/thundernixon/Signika/blob/0c95801d09770fb83584ba5acd2474f76470abb8/fonts/signika/split_vf/Signika-Light-fontbakery-report.md)

**Comment by thundernixon** [comment]
If I am incorrect about checks 156, 161, and 162, @m4rc1e should update [the code in `fix-vf-meta` which currently removes these fields](https://github.com/googlefonts/gftools/blob/master/bin/gftools-fix-vf-meta.py#L100). However, it seems logical that these fields should be excluded in a VF, where nameID 1 is already correctly set as the true family name.

**Comment by mjlagattuta** [comment]
I believe the static naming (as far as band IDs 1 and 2 are concerned) is still applicable for variable fonts to resolve issues such as having 2 regular instances on Mac (when your default outlines in the VF are non-RIBBI), and then this necessitates the presence of name IDs 16 and 17 for the expected values of 1 and 2, at least that has been my experience and understanding of it thus far

**Comment by davelab6** [comment]
The statics should have the suffix in nameid 16 (& 1) imho

**Comment by mjlagattuta** [comment]
That is a good point on having statics and VFs coexist on a user's machine, I was not suggesting that nameID 16 be used for that, but it could be a good way to differentiate between the two.

> Do you think it still makes sense to do something like making nameID 1 into `Signika Light`, and nameID 2 into `Regular`? If so, why?

Yes, I think we should be doing exactly that. A setup like you decribed:
```
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Signika
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Light
    </namerecord>
```

Is not ideal for legacy applications. To my knowledge, legacy applications disregard all variable tables and just treat the .ttf as a static with the default outlines from the glyf table. This being the case, I believe it is important that the name table is structured accordingly:
```
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Signika Light
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Regular
    </namerecord>
    <namerecord nameID="16" platformID="3" platEncID="1" langID="0x409">
      Signika
    </namerecord>
    <namerecord nameID="17" platformID="3" platEncID="1" langID="0x409">
      Light
    </namerecord>
```
This will enable proper roman italic linking in legacy applications, plus it is in line with the OT spec for static fonts. If we want to include a suffix in statics once VFs are shipped as updates I agree with @davelab6 that both 16 and 1 should have the suffixed family name

**Comment by davelab6** [comment]
I think Static is good, then Stat, then St

**Comment by m4rc1e** [comment]
fix-vf-meta should now produce a nametable which shouldn't fail these checks. 

The solution was to use the default nametable which fontmake generates and add STAT name records for styles and sibling fonts.

**Comment by thundernixon** [comment]
Confirmed, this seems to be working well now. Cheers! 👍
