### ISSUE TITLE
Ensure dependencies are discoverable by BackYourStack

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2332]
## Observed behaviour

https://backyourstack.com/googlefonts/repositories doesn't show any dependencies detected for most projects in the gf org except the Korean minisite.

## Expected behaviour

https://backyourstack.com/googlefonts/repositories should show the fontbakery dependencies.

**Comment by felipesanches** [comment]
It currently detects dependencies from:
* JavaScript (NPM)
* PHP (Composer)
* .NET (Nuget)
* Go (dep)
* Ruby (Gem)

![screenshot at 2019-02-04 11 19 35](https://user-images.githubusercontent.com/213676/52210637-8fcc4f80-287f-11e9-8765-143f0f2a3e14.png)

**But not yet Python.**

**Comment by davelab6** [comment]
Haha well this is definitely a someday maybe thing 😉
