### ISSUE TITLE
Add check: If hinted, check fonts have head table flag bit 3 set

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2338]
## Observed behaviour

Per https://docs.microsoft.com/en-us/typography/opentype/spec/head, bit 3 of Head::flags decides whether PPEM should be rounded. This bit should always be set for hinted fonts. We do not have a check for this.

## Expected behaviour

We have a check for this.

**Comment by felipesanches** [comment]
@davelab6, @m4rc1e, @laerm0:
This is the current state of the OFL licenced portion of the Google Fonts collection regarding this new check:

![screenshot at 2019-02-12 17 51 31](https://user-images.githubusercontent.com/213676/52664133-293ed580-2f00-11e9-9292-e2b16245c262.png)

Notes:
* SKIP means the font is not hinted. Detection is based on the presence of a "fpgm" (Font Program) table.
* PASS means the font is hinted and has bit 3 of the head table flags properly set.
* FAIL means the font is hinted but does not set the bit.

**Comment by felipesanches** [comment]
@davelab6 would you prefer if I opened an issue on google/fonts issue tracker with this kind of collection-wide overview whenever a new check is implemented in fontbakery?

**Comment by laerm0** [comment]
I'm glad to know our collection is so colorful.

**Comment by thundernixon** [comment]
I've just come across this while rebuilding Encode with the latest FB. Does anyone know if this can be set in GlyphsApp, or if there's an existing GFtools script to set this?
