### ISSUE TITLE
Add check for 'subtle' interpolation errors

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2339]
## Observed behaviour

<img width="570" alt="screen shot 2019-02-07 at 12 07 28 pm" src="https://user-images.githubusercontent.com/261579/52428918-fa27fe80-2ad0-11e9-93a4-37c28183293e.png">

A common interpolation error is where the outlines are technically interpolation compatible, but the result is not right.

## Expected behaviour

We should have a check for this kind of error.

**Comment by felipesanches** [comment]
Where does the example in the image come from?

Is there a more detailed description of what went wrong to result in what we see in the image?

**Comment by mjlagattuta** [comment]
The case that @davelab6 is describing is the result of outlines that are compatible but have different starting points. I believe his sample images come from the preview bar in Glyphs App. Shown below is an example (also from Glyphs) with two compatible outlines compared side by side (one starts on bottom one starts on top). The corresponding points between these outlines are shown on right:

<img width="901" alt="diff-start-points" src="https://user-images.githubusercontent.com/35570153/52434354-f8a40980-2ac3-11e9-981a-a9bc3284dd57.png">


Within the scope of this suggested check I think we should also be checking for cases where outlines are compatible but path order is incorrect. As an example, here is the left double quote from an earlier version of Open Sans. Different path order on left, consistent path ordering on right:
<img width="725" alt="open_sans_dblquoteleft" src="https://user-images.githubusercontent.com/35570153/52433986-30f71800-2ac3-11e9-80d2-22a1cadc19fe.png">

**Comment by simoncozens** [comment]
We have this check now (`com.google.fonts/check/interpolation_issues`).
