### ISSUE TITLE
Exceptions/permissions to override FB fails/warns

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#2356]
Some projects like IBM Plex want special exceptions/permissions to override FB fails/warns into passes.

This seems to be better aligned to the goals of the Fontbakery Dashboard to add over-rides when checks fail, but are considered OK to ignore.

If the command-line tool had a similar feature I think one possible implementation could be to have user config files with white-lists of check-ids. But I am not coninced of the real need for this.

**Comment by graphicore** [comment]
I'd implement a feature like that, but I think we need a proper requirements statement or user stories and actual cases where and how it's going to be used. I don't like to implement features that are only theoretical at this point. 

- Is this to include/exclude certain checks?
- If we explicitly include checks and they are not (any more) in the specification, is that a fail or can they be optional? Actually, specifications are already doing something very similar …
- Another feature we're thinking about frequently are local result-overrides. I think I'd put these into a `fontbakery.yaml` file, so the history and reasoning of it is documented along with the family. This also only if we have an acute need and user for it.

**Comment by cjchapman** [comment]
Along these lines, there are a number of checks that we (at Adobe Fonts) would like to downgrade from `FAIL` to `WARN` in the `check-adobefonts` profile (rather than just completely exclude them). Some frequently occurring examples include:
* `com.google.fonts/check/dsig`
* `com.google.fonts/check/whitespace_glyphs`
* `com.google.fonts/check/valid_glyphnames`

**Comment by chrissimpkins** [comment]
Here is a custom profile that allows you to run the universal checks, filter out any that you do not need, and add project-specific custom checks:

https://github.com/googlefonts/fontbakery/pull/2714

**Comment by simoncozens** [comment]
This is now possible through the `exclude_checks` and `overrides` entries of the configuration file.
