### ISSUE TITLE
GitHub markdown not rendering on GitHub for Merriweather Sans

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/fontbakery#2358]
## Observed behaviour

Typically, I run FontBakery with the `--ghmarkdown` option, in order to get a report easily readable on GitHub. In fact, I just did this in a project of mine with the latest released version of fontbakery, and it again worked as expected.

However, I advised @EbenSorkin to use this option on his Merriweather Sans project, but for some reason that isn't immediately clear to me, the report isn't rendering with the usual GH markdown dropdowns, tables, etc – it just looks like the raw markdown:

https://github.com/EbenSorkin/Merriweather-Sans/blob/69e90335692f8572b2efc32e498ca60061ca51bc/checks/README.md

_(here's a screenshot)_
![image](https://user-images.githubusercontent.com/7355414/52888903-81b5e300-314b-11e9-9891-6e201009654b.png)

## Expected behaviour

I expect it to render with proper styling, as my GH markdown reports do. One example is from Libre Caslon:

https://github.com/thundernixon/Libre-Caslon/blob/f2e1c4e271abfb92753dd4b2c00dd1c698844c97/font_checks/LibreCaslonText-Bold-fontbakery-report.md

_(here's a screenshot)_
![image](https://user-images.githubusercontent.com/7355414/52889266-2f75c180-314d-11e9-9fc0-f2f7b9993759.png)

## Resources and exact process needed to replicate

I would need Eben to upload his Glyphs sources (or at minimum, the variable TTF) to the Merriweather repo in order for me to reproduce this issue. 

In the mean time, I was wondering if there is something obviously wrong in the `md` file generated in Merriweather, or if others know something that might prevent GitHub from rendering markdown as I expect. 

Was this an issue with a slightly older version of FontBakery? If so, I don't see the issue popping up, but we can try updating FB next time we run this.

Just wanted to ask someone about this, and asking here allows others to search for it in the future. Thanks for any insight!

**Comment by chrissimpkins** [comment]
Eben's file is saved in binary format for some reason. C/W his README in the root of his repo where the Markdown renders as expected:

<img width="423" alt="bemgr-image" src="https://user-images.githubusercontent.com/4249591/52892745-7ff81980-3163-11e9-8500-4e3f2311f17b.png">

and with your check MD files in the Libre-Caslon repo where they render as expected:

<img width="391" alt="omn2v-image" src="https://user-images.githubusercontent.com/4249591/52892747-8a1a1800-3163-11e9-806c-d9470aa9434d.png">

**Comment by thundernixon** [comment]
Oh wow, amazing find!

Eben did briefly open the .MD file, which opened in xcode on his computer. Maybe he saved it as a binary there?

**Comment by EbenSorkin** [comment]
I am not sure how it was made binary if it was. The file was made by
fontbakery using the --ghmarkdown checks.md command as part of a check ogf
an existing VF.

The whole line

(TestMerriweather) EbensiMacRetina:Merriweather-Sans ebensorkin$ fontbakery
check-googlefonts
/Users/ebensorkin/virtualenvs/variable_ttf/Merriweather-VF.ttf --ghmarkdown
checks.md

**Comment by chrissimpkins** [comment]
It may have happened during the transition from the fontbakery output file through XCode and back out as a new save.  I'm not sure why XCode would save a Markdown file as a binary...

Can you confirm that a repeat attempt at execution of the fontbakery command that you used in https://github.com/googlefonts/fontbakery/issues/2358#issuecomment-464281656 without opening the Markdown file in another application fixes the problem?

**Comment by thundernixon** [comment]
As an update to this, Eben and I just did a video hangout, and ran through the process again. We avoided opening anything in Xcode, and – surprisingly to me – still ended up with a binary file:

[fontbakery ghmarkdown file as binary](https://github.com/EbenSorkin/Merriweather/blob/326b72d92e51c535f6f0cb6263297c5d76b6f160/test.md)


## Process 

We used FontBakery `0.6.11`, and ran:

```
fontbakery check-googlefonts <font_file>.ttf --ghmarkdown test.md
```

We used the VScode terminal to do this (my typically method), then pushed via GitHub desktop (not my typical route). I don't think either of these things would have an effect, and they didn't in a test I just now ran ([outputting this file](https://github.com/thundernixon/Libre-Caslon/blob/ea4ca7549edef6c1e60089debcea6ee3dbfd3171/font_checks/LibreCaslonText-Bold-fontbake.md)).

Is there anything else on Eben's computer that might cause this unexpected formatting? We set up a virtual environment with python 3 and a fresh upgrade of FontBakery, but I imagine there's something in the dependencies that might be responsible, somehow...

**Comment by chrissimpkins** [comment]
@felipesanches @graphicore do you have any idea why there might be a within platform, same Py interpreter, same fontbakery version difference in the Markdown output here?  I don't know the answer and am having difficulty finding where the Markdown file write occurs in the library.

cc @EbenSorkin

**Comment by graphicore** [comment]
@thundernixon when you run the test with Ebens version of Merriweather, does it give you a problem.

I just did:

1. open https://github.com/EbenSorkin/Merriweather/blob/326b72d92e51c535f6f0cb6263297c5d76b6f160/test.md in a tab
2. click the edit symbol (the pencil next to Raw|Blame|History) which created a fork in my GitHub account
3. directly without changes clicked "Preview Changes" and got a mystical hint for free… ![selection_229](https://user-images.githubusercontent.com/393132/53598011-efc6c500-3ba3-11e9-9af4-a181ddaa2910.png)
4. removed the char https://github.com/graphicore/Merriweather/commit/995c881a8a195e4bc5bda10e2b425b6296880a49
5. saved with reference to this issue https://github.com/graphicore/Merriweather/blob/graphicore-bad-char/test.md

**Comment by EbenSorkin** [comment]
LOL

That's kind of crazy because i did successfully register that with MS years
ago. Maybe we should get a newer set of Data from MS?

-e.

**Comment by graphicore** [comment]
@felipesanches looks like we have an interesting bug where bad/wrong bytes are injected into output. I would kind of expect that python would choke on that char.

@EbenSorkin what is that char?

**Comment by EbenSorkin** [comment]
Oh - it isn't the code. ( STC ) it is the glyph after that.

But in the Glyphs UI it doesn't look like there is a space or glyph after
the STC.

Because this started life as a Fontlab file that may have something to do
with it.

If I output a UFO file might that shed some light on it? Or is this a
question to bring to Rainer/Georg/Adam?

-e.

**Comment by graphicore** [comment]
vim displays it as **^@** (`OS/2 VendorID value 'STC^@' is not`)

**Comment by graphicore** [comment]
@EbenSorkin let's figure what we got here ;-) FontBakery should detect this. If you can find out where the char originated, we may or may not have to bring in others.

excerpt from `$ hexdump -C ~/Downloads/test.md | less`:
```
00002080  4e 2a 2a 20 4f 53 2f 32  20 56 65 6e 64 6f 72 49  |N** OS/2 VendorI|
00002090  44 20 76 61 6c 75 65 20  27 53 54 43 00 27 20 69  |D value 'STC.' i|
000020a0  73 20 6e 6f 74 20 61 20  6b 6e 6f 77 6e 20 72 65  |s not a known re|
```

Looks like a [NULL](https://en.wikipedia.org/wiki/Null_character) character(`00`). It may very well come from FontLab, I don't know it that good, but maybe it used NULL as a value separator and somewhere in translation it was just expected that the `OS/2 VendorID` has always 4 chars, so the separator was also copied into the new file …

**Comment by graphicore** [comment]
Spec says [achVendID](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#achvendid) it's supposed to be a data type of [tag](https://docs.microsoft.com/en-us/typography/opentype/spec/otff#data-types): 

> Array of four uint8s (length = 32 bits) used to identify a table, design-variation axis, script, language system, feature, or baseline

So, maybe FontBakery just handles a 3(or 2 or 1)-unit tag, which is padded with NULL at the end, wrongly? cc @felipesanches

**Comment by graphicore** [comment]
Looks also like the warning is a false positive, which comes from treating the tag-type wrongly. Do we know other examples with less than four chars in the vendor ID?

**Comment by felipesanches** [comment]
yes, we do. And the code-test is prepared to endure our code is capable of dealing with those cases as well.

https://github.com/googlefonts/fontbakery/blob/785feab22f8ae3fdc3162b4b78b2fd7a204e1299/tests/specifications/googlefonts_test.py#L355-L393

**Comment by graphicore** [comment]
In this case `CFA ` is represented as `43 46 41 20` where `20` is the space char. But it seems that in a font it is represented as `43 46 41 00`, not with a space, but with a NULL.

**Comment by felipesanches** [comment]
So, the question now in my head is:

Is the NULL char a valid byte for the purpose of padding vendor IDs? Does it cause trouble to some third-party software? Should we treat it as a font-bug and  emit a WARN (or even FAIL) regarding that?

**Comment by graphicore** [comment]
Yeah, that's kind of the question.

We do the space-padding ourselves:

https://github.com/googlefonts/fontbakery/blob/785feab22f8ae3fdc3162b4b78b2fd7a204e1299/Lib/fontbakery/specifications/googlefonts.py#L652

Maybe we shouldn't.

Then in:

https://github.com/googlefonts/fontbakery/blob/785feab22f8ae3fdc3162b4b78b2fd7a204e1299/Lib/fontbakery/specifications/googlefonts.py#L672

remove NULL bytes from the end.

I doubt that spaces (`0x20` bytes) are correct padding.

**Comment by davelab6** [comment]
0x0020 is what I expect for padding

**Comment by graphicore** [comment]
> 0x0020 is what I expect for padding

How so? It seems to me that a space "could rather" be a legitimate part of a vendor ID, as other non-alphanumeric chars are accepted as well (`H&FJ`), NULL is put into the font binary if you give it a less than 4 chars string. So, if you want spaces, you got to put them into the binary explicitly. Maybe fontTools should remove the NULL padding when decompiling?

At least I can bust a fontTools roundtrip, look at `Out[48]: 'STC\x00'`:

```
In [43]: ttfont = TTFont('../testfonts/RobotoSlab-Regular.ttf')                                                                                                            

In [44]: ttfont['OS/2'].achVendID                                                                                                                                          
Out[44]: 'GOOG'

In [45]: ttfont['OS/2'].achVendID = 'STC'                                                                                                                                  

In [46]: ttfont.save('./mytestfont.ttf')                                                                                                                                   

In [47]: ttfont2 = TTFont('./mytestfont.ttf')                                                                                                                              

In [48]: ttfont2['OS/2'].achVendID                                                                                                                                         
Out[48]: 'STC\x00'

In [49]: ttfont['OS/2'].achVendID                                                                                                                                          
Out[49]: 'STC'

In [50]: ttfont['OS/2'].achVendID == ttfont2['OS/2'].achVendID                                                                                                             
Out[50]: False
```

**Comment by felipesanches** [comment]
this is now fixed
