### ISSUE TITLE
Check 001 "Checking file is named canonically" failing incorrectly for variable fonts

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/fontbakery#2396]
## Observed behaviour

In QAing Inter, I'm running into an unexpected and seemingly self-contradictory fail:

> 🔥 <b>FAIL:</b> Checking file is named canonically.</summary>
> 
> * [com.google.fonts/check/001](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/001)
> * 🔥 **FAIL** Style name used in "Inter-Regular.ttf" is not canonical. You should rebuild the font using any of the following style names: "Thin", "ExtraLight", "Light", "Regular", "Medium", "SemiBold", "Bold", "ExtraBold", "Black", "Thin Italic", "ExtraLight Italic", "Light Italic", "Italic", "Medium Italic", "SemiBold Italic", "Bold Italic", "ExtraBold Italic", "Black Italic".

This fail also occurs with the latest version of Comfortaa:

> com.google.fonts/check/001 with (('font[0]', '/Users/stephennixon/type-repos/google-font-repos/fonts/ofl/comfortaa/Comfortaa-Regular.ttf'),)
   Checking file is named canonically.
>  * FAIL: Style name used in "/Users/stephennixon/type-repos/google-font-repos/fonts/ofl/comfortaa/Comfortaa-Regular.ttf" is not canonical. You should rebuild the font using any of the following style names: "Th
in", "ExtraLight", "Light", "Regular", "Medium", "SemiBold", "Bold", "ExtraBold", "Black", "Thin Italic", "ExtraLight Italic", "Light Italic", "Italic", "Medium Italic", "SemiBold Italic", "Bold Italic", "Extra
Bold Italic", "Black Italic".
> 
>   Result: FAIL

...and with Encode Sans Condensed:

> com.google.fonts/check/001 with (('font[0]', '/Users/stephennixon/type-repos/google-font-repos/fonts/ofl/encodesanscondensed/EncodeSansCondensed-Thin.ttf'),)
   Checking file is named canonically.
>  * FAIL: Style name used in "/Users/stephennixon/type-repos/google-font-repos/fonts/ofl/encodesanscondensed/EncodeSansCondensed-Thin.ttf" is not canonical. You should rebuild the font using any of the following
 style names: "Thin", "ExtraLight", "Light", "Regular", "Medium", "SemiBold", "Bold", "ExtraBold", "Black", "Thin Italic", "ExtraLight Italic", "Light Italic", "Italic", "Medium Italic", "SemiBold Italic", "Bol
d Italic", "ExtraBold Italic", "Black Italic".
> 
>  Result: FAIL

Markazi Text matches a pattern closer to what I see in the check code, `MarkaziText-Roman-VF.ttf`, but it also fails with a related but slightly different result:

> com.google.fonts/check/105 with (('font[0]', '/Users/stephennixon/type-repos/google-font-repos/fonts/ofl/markazitext/MarkaziText-Roman-VF.ttf'),)
   METADATA.pb: Filename is set canonically?
> * FAIL: METADATA.pb: filename field ("MarkaziText-Roman-VF.ttf") does not match canonical name "MarkaziText-Regular.ttf".
> 
>   Result: FAIL

This fail _doesn't_ happen with IBM Plex Sans Regular or with Montserrat Regular – both static fonts. So, I'm guessing it's an issue with checking the file names of VFs. 

## Expected behaviour

1. Based on the check's fail message ("You should rebuild the font using any of the following style names...", the filenames should be acceptable, and not trigger this `fail`.

2. If we have settled on a different canonical naming structure for VFs, the fail message should tell the user what _is_ the accurate canonical naming pattern, and specify if this is particular to VFs.

## Resources and exact process needed to replicate

I'm experiencing this issue with the latest font files of Comfortaa and Markazi Text at google/fonts master and Fontbakery version `0.6.12`.

**Comment by felipesanches** [comment]
yes. it is broken and I figured out why. I am now working on a fix.

I am sad that out code tests did not catch this. I will also double check them. Thanks for reporting the problem.

**Comment by felipesanches** [comment]
here's the problem:

![Screenshot at 2019-03-15 08:06:40](https://user-images.githubusercontent.com/213676/54427459-73d78b80-4712-11e9-9f00-784bd08e1d21.png)

It is a variable font, but it is named as a static: "Comfortaa-Regular.ttf".

The code is correctly detecting the problem, but poorly reporting it. The bug is not on the detection, but on the log message which was poorly chosen. It should instead say something like:

`This is a variable font, but it is using a naming scheme typical of a static font. Please change the font filename to use one of the following valid suffixes for variable fonts: "VF", "Italic", "Italic-VF", "Roman" or "Roman-VF"`

**Comment by felipesanches** [comment]
I think a good move here would be to rename `STYLE_NAMES` to `STATIC_STYLE_NAMES` and then create a new constant like this:

```python
VARFONT_STYLE_NAMES = ["VF", "Italic", "Italic-VF", "Roman", "Roman-VF"]
```

And then refactor this code to use it:
![Screenshot at 2019-03-15 08:14:23](https://user-images.githubusercontent.com/213676/54427934-cf564900-4713-11e9-9d06-6791c427dd55.png)

**Comment by m4rc1e** [comment]
@felipesanches VF names are changing again. I think we're going to use the following proposal https://github.com/google/fonts/issues/1817#issuecomment-466556000. I recommend leaving it for the time being. We can implement vf names once the gf eng team have sorted the api.

**Comment by felipesanches** [comment]
I want to make this minimal fix and then adapt to the new specs once they are defined. Right now it is broken even with the previous spec.

**Comment by m4rc1e** [comment]
@felipesanchesfor google/fonts we are using `FamilyName-DefaultInstance.ttf`. For upstreams, we've used.

```
VARFONT_SUFFIXES = [ "VF", "Italic-VF", "Roman-VF"]
```

They must all end with VF.

**Comment by felipesanches** [comment]
ok... I sketched an initial fix for this, but I will later revise it to adapt to the info provided by your comments. Thanks, @m4rc1e

**Comment by thundernixon** [comment]
@m4rc1e just to be sure I understand ... 

1. You want files to have different names in upstream sources vs google/fonts? Does this change for not-yet-published fonts?

  - So, upstream might be `EncodeSans-Roman-VF.ttf` while google/fonts is `EncodeSans-Light.tff`?

  - And upstream might be `Inter-Light-VF.ttf` while google/fonts is `Inter-Light.ttf`?

2. Should we really expect to standardize upstreams, or is it only really necessary to standardize google/fonts? 
  - Inter is currently `build/fonts/var/Inter.var.ttf` build/fonts/var/Inter-upright.var.ttf`, etc, and this is quite clear, even if it doesn't match the style you're suggesting.
