### ISSUE TITLE
com.google.fonts/check/font_version - FAIL message prints version number incorrectly

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/fontbakery#2403]
This seems to be distinct from the [earlier issue of parsing in check 044](https://github.com/googlefonts/fontbakery/issues/2094).

## Observed behavior

Check 044 seems to be incorrectly parsing versions numbers incorrectly.

> 🔥 FAIL: Checking font version fields (head and name table).
> 
> com.google.fonts/check/044
> 🔥 FAIL head version is ('3', '004'), name version string for platform 3, encoding 1, is ('3', '400') [code: mismatch]

When the font is TTXed, the specific code looks like the following.

Head table:
```
<fontRevision value="3.004"/>
```

Name table:
```
<namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
      3.4;862d1a785
</namerecord>
```

### The problem

`3.4` from the name table is incorrectly reported as `3.400` by the fontbakery output.

## Expected behavior

I do think that the `fail` happens to be true in this case (though I'm not 100% sure on that), _however_ the fail message is inaccurate.

It reports `name version string for platform 3, encoding 1, is ('3', '400')` when it _should say_ `name version string for platform 3, encoding 1, is ('3', '4')`.

## Resources and exact process needed to replicate

More details at:
https://github.com/rsms/inter/issues/138

GH markdown check with fail:
https://github.com/thundernixon/inter/blob/862d1a78572ce58dd6a85e8215235dac79ef09fe/misc/googlefonts-qa/checks/Inter-Regular.checks.md

Exact version and instructions to reproduce, if desired:
https://github.com/thundernixon/inter/tree/862d1a78572ce58dd6a85e8215235dac79ef09fe/misc/googlefonts-qa

**Comment by felipesanches** [comment]
I cloned the Inter repo and tried to build the font binaries, but got a problem when setting up the buid environment:

![Screenshot at 2019-03-22 19:03:15](https://user-images.githubusercontent.com/213676/54855493-71ff6080-4cee-11e9-83b7-d392717e3069.png)


@thundernixon, could you please send me a copy of the binaries so that it is easier for me to replicate the fontbakery issue?

**Comment by thundernixon** [comment]
## [bin.zip](https://github.com/googlefonts/fontbakery/files/2998509/bin.zip)

Note: this goes into `build/venv`

![image](https://user-images.githubusercontent.com/7355414/54856585-a0227780-4cd1-11e9-9a8a-a9d25b226f32.png)

**Comment by felipesanches** [comment]
no, sorry... What I meant was a copy of the **font binaries**, meaning the built OpenType font files.

**Comment by felipesanches** [comment]
I used the term "binary" in opposition to "source" just like in typical software dev speak

**Comment by thundernixon** [comment]
Ohhh, haha, my bad. 

Here's the upright variable font binary, at that exact state:

[Inter-upright.var.ttf.zip](https://github.com/googlefonts/fontbakery/files/2998525/Inter-upright.var.ttf.zip)

I just ran:
```
 fontbakery check-googlefonts <font_path>/Inter-upright.var.ttf
```

and once again, got:

```
>> com.google.fonts/check/044 with (('font[0]', 'build/fonts/var/Inter-upright.var.ttf'),)
   Checking font version fields (head and name table).
 * FAIL: head version is ('3', '004'), name version string for platform 3, encoding 1, is ('3', '400') [code: mismatch]

   Result: FAIL
```

In terms of Inter, this is low-priority, as Rasmus made a padding hack on his end, and this fail is no longer triggered. However, this seems probably worth fixing for other fonts.

**Comment by felipesanches** [comment]
![Screenshot at 2019-03-22 21:32:00](https://user-images.githubusercontent.com/213676/54859294-73875380-4d03-11e9-9cf2-b2b7075c4edc.png)
