### ISSUE TITLE
new check: com.google/fonts/check/name/fullname_has_trailing_space

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#2417]
Add a new name table check that detects the problem described at https://github.com/google/fonts/issues/1903

We already have checks for ensuring METADATA.pb and name table entries are in sync.

**Comment by felipesanches** [comment]
hmmm... maybe rename the check and ensure no name table entry has trailing spaces at all

com.google/fonts/check/name/trailing_space

**Comment by davelab6** [comment]
This needs urgent attention :)
