### ISSUE TITLE
Check family character coverage is consistent

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2432]
## Observed behaviour

https://github.com/googlefonts/gftools/blob/master/bin/gftools-font-weights-coverage.py exists

## Expected behaviour

We use that to test fonts within a family have the same coverage. 

We might already have a check for that; if so, the logic should match the above.

**Comment by simoncozens** [comment]
This becomes less of a big deal now that we are primarily onboarding variable fonts. If it's still a need to do this with a set of statics, let's reopen to discuss.
