### ISSUE TITLE
fontbakery version check failure

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/fontbakery#2440]
## Observed behaviour

macOS 10.14.4
Python 3.7.3
fontbakery 0.7.1
subcommand: `check-universal`

Performed `pip3 install --upgrade fontbakery` to latest (v0.7.1) release of Fontbakery.  Then executed universal profile checks with:

```
$ fontbakery check-universal [FONTPATH] --ghmarkdown report.md
```

This led to the following exception:

```
>> com.google.fonts/check/fontbakery_version
   Do we have the latest version of FontBakery installed?
 * ERROR: Failed with TypeError: argument of type 'NoneType' is not iterable
           File "/usr/local/lib/python3.7/site-packages/fontbakery/checkrunner.py", line 345, in _exec_check
             for sub_result in result:  # Might raise.
           File "/usr/local/lib/python3.7/site-packages/fontbakery/profiles/universal.py", line 362, in com_google_fonts_check_fontbakery_version
             if not (is_latest or is_up_to_date(installed_str, latest_str)):
           File "/usr/local/lib/python3.7/site-packages/fontbakery/profiles/universal.py", line 321, in is_up_to_date
             has_githash = ".dev" in installed


   Result: ERROR
```

I can confirm that this same error occurs with execution of the `check-googlefonts` subcommand on my platform.

## Expected behaviour

No error message when I am using the latest release version of Fontbakery.

Let me know if I can provide additional information.

**Comment by chrissimpkins** [comment]
Is this perhaps the workaround for this issue: https://github.com/googlefonts/fontbakery/issues/2405#issuecomment-479572376 ?  `pip` == `pip2` not `pip3` on my system as with that report.

**Comment by felipesanches** [comment]
@chrissimpkins, can you confirm this issue is still affecting you? I was not yet able to replicate the problem here.

**Comment by chrissimpkins** [comment]
I can confirm that this remains a problem on fontbakery v0.7.1 and a problem after `pip3 install --upgrade fontbakery` to v0.7.2.  I took a look at the source and it appears that there is a `subprocess` call to the command `pip search fontbakery`.  On my macOS system with Homebrew Py2 and Py3 installs, `pip` is the Py2 version of the package manager.  Here is what happens when I try the command directly in the terminal:

### Py2 version of `pip` = `pip`

```
$ pip --version
pip 19.0.3 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)

$ pip search fontbakery
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
fontbakery (0.7.2)  - Well designed Font QA tool, written in Python 3
```

and on an attempt to uninstall any Py2 installed version of fontbakery:

```
pip uninstall fontbakery
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Skipping fontbakery as it is not installed.
```

### Py3 version of `pip` = `pip3`

```
$ pip3 --version
pip 19.0.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

$ pip3 search fontbakery
fontbakery (0.7.2)  - Well designed Font QA tool, written in Python 3
  INSTALLED: 0.7.2 (latest)
```

This occurs when I run without a venv.  Cowboy, I know :)  

Next, I created a new venv and installed a fresh version of fontbakery v0.7.2 source with `pip install fontbakery`.   When I execute the command that led to the problem outside of a venv there is no error.  

It looks like this due to system-installed Homebrew `pip` being a soft link to Python 2 `pip` on macOS.  It seems that the string that you get back on the subprocess call is not formatted according to the way that you are parsing it and you define the test variable with `None`?

I suppose the simple approach to this issue is to update the macOS installation documentation to instruct users to always use a venv and provide instructions/link to additional information on how to set up, start, and deactivate one.  Another approach would be to implement a check for `pip3` install and if it is present, use that instead of `pip` as this should eliminate use of a Py2 version over a Py3 version.

**Comment by felipesanches** [comment]
Is `pip3` globally available? Or are there systems with python 3 installed in which pip (version 3) is only available as `pip` and no `pip3` symlink?

I wonder whether it is safe for us to simply use `pip3` in that subprocess call...

**Comment by felipesanches** [comment]
@chrissimpkins you could perhaps experimentaly change the subprocess line to use pip3 and let me know if that change would fix the issue for you. Let me know if this sounds like a good way to address the issue.

**Comment by chrissimpkins** [comment]
As of v0.7.10 I am no longer seeing this message.  Check seems to work without issues.
