### ISSUE TITLE
Contour count / ttfautohint

### ISSUE THREAD

**Issue by jeremymickel** [googlefonts/fontbakery#2443]
## Observed behaviour

I have hinted the fonts with ttfautohint, and for all glyphs with components I'm getting errors on the character count check. When I open the TTF I see that a .ttfautohint glyph component is counted as an empty contour in each glyph that's reporting errors. Is this a real problem or an expected error?

```
   	[1;35;40mCheck if each glyph has the recommended amount of contours.	[0m
 * 	[1;33;40mWARN	[0m: This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: quoteright	Contours detected: 2	Expected: 1
Glyph name: quotesinglbase	Contours detected: 2	Expected: 1
Glyph name: quotedblright	Contours detected: 3	Expected: 2
Glyph name: quotedblbase	Contours detected: 3	Expected: 2

```
Link to one of the styles:
https://github.com/jeremymickel/RedHat

<img width="301" alt="Screen Shot 2019-04-03 at 7 55 47 PM" src="https://user-images.githubusercontent.com/2964496/55526575-84f92580-564a-11e9-9d6c-d5aab120f408.png">

**Comment by felipesanches** [comment]
This is indeed a bug. I have just added a filter to not count the .tthautohint clyph component and now your font family passes on this check.

Thanks @jeremymickel for reporting this!

I will push the fix into a pull request and this fix will be included in our next release, Font Bakery v0.7.2 next Monday.

----

## Fontbakery report

Fontbakery version: 0.7.2.dev1+g1a5459a

<details>
<summary><b>[1] RedHatDisplay-BlackItalic.ttf</b></summary>
<details>
<summary>🍞 <b>PASS:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/contour_count)
* 🍞 **PASS** All glyphs have the recommended amount of contours

</details>
<br>
</details>
<details>
<summary><b>[1] RedHatDisplay-Black.ttf</b></summary>
<details>
<summary>🍞 <b>PASS:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/contour_count)
* 🍞 **PASS** All glyphs have the recommended amount of contours

</details>
<br>
</details>
<details>
<summary><b>[1] RedHatDisplay-BoldItalic.ttf</b></summary>
<details>
<summary>🍞 <b>PASS:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/contour_count)
* 🍞 **PASS** All glyphs have the recommended amount of contours

</details>
<br>
</details>
<details>
<summary><b>[1] RedHatDisplay-Bold.ttf</b></summary>
<details>
<summary>🍞 <b>PASS:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/contour_count)
* 🍞 **PASS** All glyphs have the recommended amount of contours

</details>
<br>
</details>
<details>
<summary><b>[1] RedHatDisplay-Italic.ttf</b></summary>
<details>
<summary>🍞 <b>PASS:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/contour_count)
* 🍞 **PASS** All glyphs have the recommended amount of contours

</details>
<br>
</details>
<details>
<summary><b>[1] RedHatDisplay-MediumItalic.ttf</b></summary>
<details>
<summary>🍞 <b>PASS:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/contour_count)
* 🍞 **PASS** All glyphs have the recommended amount of contours

</details>
<br>
</details>
<details>
<summary><b>[1] RedHatDisplay-Medium.ttf</b></summary>
<details>
<summary>🍞 <b>PASS:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/contour_count)
* 🍞 **PASS** All glyphs have the recommended amount of contours

</details>
<br>
</details>
<details>
<summary><b>[1] RedHatDisplay-Regular.ttf</b></summary>
<details>
<summary>🍞 <b>PASS:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/contour_count)
* 🍞 **PASS** All glyphs have the recommended amount of contours

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 0 | 0 | 0 | 8 |
| 0% | 0% | 0% | 0% | 0% | 100% |
