### ISSUE TITLE
OS/2 fsSelection REGULAR bit should be set

### ISSUE THREAD

**Issue by jeremymickel** [googlefonts/fontbakery#2444]
## Observed behaviour

I'm getting this error message in Font Bakery:
` *  [1;31;40mFAIL [0m: OS/2 fsSelection REGULAR bit should be set. [code: bad-REGULAR]
`

## Expected behaviour

I've left fsSelection blank, since none of the available options seem applicable. Is there somewhere else this should be set?

<img width="571" alt="Screen Shot 2019-04-04 at 2 05 03 PM" src="https://user-images.githubusercontent.com/2964496/55588491-c210f680-56e2-11e9-93cb-71dc36e46a57.png">

## Resources and exact process needed to replicate

https://github.com/jeremymickel/RedHat

**Comment by eliheuer** [comment]
Here is a hacky way to fix this, If you can upload source files to the repo we can help with less hacky ways. 

1. Install fonttools
2. cd into the directory with the ttf that has the FAIL and run:
`mkdir ttx && ttx -d ttx -s RedHatDisplay-Black.ttf`
3. open the os2 table with a text editor
`vim ttx/RedHatDisplay-Black.O_S_2f_2.ttx`
4. find the fsSelection part of the XML and change the 6th bit from 0 to 1:
![fs](https://user-images.githubusercontent.com/5162664/55604596-96235e80-573e-11e9-831e-de0db22075bc.png)
More info on this here: https://docs.microsoft.com/en-us/typography/opentype/spec/os2#fsselection
5. Rebuild the ttf: 
`ttx ttx/RedHatDisplay-Black.ttx`
6. Run fontbakery and you wont get the FAIL
![fs2](https://user-images.githubusercontent.com/5162664/55604700-15189700-573f-11e9-9fb3-042174162fa0.png)

**Comment by m4rc1e** [comment]
We have a fix script in gftools, https://github.com/googlefonts/gftools/blob/master/bin/gftools-fix-fsselection.py

Once installed just do:
```
gftools fix-fsselection font.ttf --autofix
```
