### ISSUE TITLE
Family / Style name exceeds 20 characters

### ISSUE THREAD

**Issue by jeremymickel** [googlefonts/fontbakery#2447]
## Observed behaviour

I'm getting error messages about family / style names being too long.

```
>>  [1;36;40mcom.google.fonts/check/name/family_and_style_max_length [0m with (('font[0]', 'RedHatDisplay-Black.ttf'),)
    [1;35;40mCombined length of family and style must not exceed 20 characters. [0m
 *  [1;33;40mWARN [0m: The combined length of family and style exceeds 20 chars in the following 'MACINTOSH' entries: FONT_FAMILY_NAME = 'Red Hat Display Black' / SUBFAMILY_NAME = 'Regular'
 *  [1;33;40mWARN [0m: The combined length of family and style exceeds 20 chars in the following 'WINDOWS' entries: FONT_FAMILY_NAME = 'Red Hat Display Black' / SUBFAMILY_NAME = 'Regular'
```

## Expected behaviour

I've tested the fonts on Windows 10 and everything installs correctly. Is this a real error?

## Resources and exact process needed to replicate

https://github.com/jeremymickel/RedHat

**Comment by felipesanches** [comment]
Thanks for reminding me about this, @jeremymickel! 
We already have another issue about this at #2179 and I will increase this limit to 27 chars.

Please see the details on the other issue to understand the reasoning behind this.
