### ISSUE TITLE
[docs] bash completion `source` vs `.` (dot)

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#2451]
I just stumbled over this piece of our documentation https://github.com/googlefonts/fontbakery/blob/master/docs/source/user/bash-completion.md

> If you want to use the file directly in a running Bash shell:
>
>     $ source path-to/fontbakery/bin/bash-completion
>
> If you are using a python virtual environment (that is not a system-wide installation), run:
>
>     $ . path-to/fontbakery/bin/bash-completion

I thought `.` and `source` are synonymous, especially in bash. Did I miss something here? CC @chrissimpkins

**Comment by chrissimpkins** [comment]
That was copied verbatim from a previous version of the project docs that were in a different location. I don't know who the original author was...

**Comment by felipesanches** [comment]
well.. let's then simplify it to a single line instruction. Would you like to make the quick fix, @graphicore?

**Comment by graphicore** [comment]
Thanks!
