### ISSUE TITLE
Marc Foley's refactoring of name table checks

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#2453]
Review PR #2361 and maybe reimplement that (or fix the merge conflicts)

**Comment by felipesanches** [comment]
This is already a bit old. Do you plan to take a look at that PR again, @m4rc1e? Or do you have better ideas about how to handle these name table checks nowadays?

**Comment by simoncozens** [comment]
This is now *very* old. If there are still problems with the name checks, I suggest we start again.
