### ISSUE TITLE
autocomplete check-IDs on the command line

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#2457]
I think it would be useful.

**Comment by felipesanches** [comment]
In order to do so, we need a way to extract a list of all available checks of a given profile.

We do have a `--list-checks` command line options but it is currently very ugly (so I think nobody really uses it):

![Screenshot at 2019-04-11 02:07:01](https://user-images.githubusercontent.com/213676/55933623-7ea41400-5c1d-11e9-94b1-1a9a39c2cb98.png)

I will change its output to only include the check IDs

**Comment by felipesanches** [comment]
OK! Now `--list-checks` is a plain clean list useful for feeding bash completion:

![Screenshot at 2019-04-11 02:51:45](https://user-images.githubusercontent.com/213676/55933735-e8bcb900-5c1d-11e9-9e48-b7b3fde31030.png)


And I made `--list-checks --verbose` output a nice coloured description of the collection of checks:

![Screenshot at 2019-04-11 02:37:19](https://user-images.githubusercontent.com/213676/55933742-ef4b3080-5c1d-11e9-8d63-1102a919f050.png)

![Screenshot at 2019-04-11 02:36:22](https://user-images.githubusercontent.com/213676/55933749-f5411180-5c1d-11e9-9b59-38d7c3918a78.png)

**Comment by felipesanches** [comment]
I have updated the bash completion scripts to support auto-completion of check IDs. It detects which profile the user chose and only autocompletes the checks available in that profile.

It supports all of these: `-c`, `--checkid`, `-x` and `--exclude-checkid`

I have also updated `setup.py` so that the bash completion script is automatically installed with `pip install fontbakery`

**Comment by cjchapman** [comment]
I think this will be very helpful. Thank you!

**Comment by felipesanches** [comment]
:-D
