### ISSUE TITLE
404 error on fontbakery.com website

### ISSUE THREAD

**Issue by jarek-foksa** [googlefonts/fontbakery#2480]
original title of this issue was:
fontbakery.com website has been hijacked and defaced
----

I have already reported the [malicious user ](https://github.com/rifqigusfiliandi/)to Github as he has defaced my website as well. Please check [this HN post](https://news.ycombinator.com/item?id=19118740) for a detailed description of this vulnerability.

**Comment by felipesanches** [comment]
thanks for reporting this

**Comment by felipesanches** [comment]
Now it is not hacked anymore. Probably github worked on fixing it. But the page is not loading anymore (we now get a 404). I think we simply need to re-enable github pages

**Comment by felipesanches** [comment]
we do have an instance running at https://fontbakery.graphicore.de/ though... should we redirect?

**Comment by davelab6** [comment]
@jarek-foksa thanks again for reporting this. @felipesanches the domain is now working against the gh-pages branch here and redirects to RTD
