### ISSUE TITLE
What's the use for ascent/descent on the hhea table?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#2504]
@davelab6, @m4rc1e, the spec says at https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6hhea.html:

```The values for ascent, descent and lineGap represent the design intentions of the font's creator rather than any computed value, and individual glyphs may well exceed the the limits they represent.```

Why?

**Comment by felipesanches** [comment]
what we meant here yesterday (me, Tony de Marco and @MonicaRizzolli) is that if the glyphs can exceed these limits, then what's the actual computational usage of these values on the font rendering engines?

**Comment by m4rc1e** [comment]
Afaik hhea ascent and descent are used to set the vertical metrics on OS X, possibly IOS as well.

As the docs states, these values are set by the designer. We set the hhea metrics so they're the same as the typo metrics. This means that both win and mac have the same linespace appearance.

**Comment by felipesanches** [comment]
Yeah, makes sense... This is pretty much what I was speculating while chatting with @tonydemarco and @MonicaRizzolli earlier this week. Thanks, Marc!
