### ISSUE TITLE
broken_links check fails with XMLSyntaxError, but (I think) the syntax is fine

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/fontbakery#2507]
## Observed behaviour

I'm getting the following error when running checks on Inter:

<details>
<summary>💔 <b>ERROR:</b> Does DESCRIPTION file contain broken links?</summary>

* [com.google.fonts/check/description/broken_links](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/broken_links)
* 💔 **ERROR** Failed with XMLSyntaxError: xmlParseEntityRef: no name, line 2, column 44 (<string>, line 2)

</details>

However, the description is very simple and doesn't even have any links:

```
<p>
    Inter is a typeface carefully crafted & designed for computer screens.
</p>
<p>
    Inter features a tall x-height to aid in readability of mixed-case and lower-case text. Several OpenType features are provided as well, like contextual alternates that adjusts punctuation depending on the shape of surrounding glyphs, slashed zero for when you need to disambiguate "0" from "o", tabular numbers, etc.
</p>
```

## Expected behaviour

I don't see any syntax errors in the description. Am I missing something, or does this check maybe get messed up if there are zero links to check?

## Resources and exact process needed to replicate

I'm building the fonts, moving them to my google/fonts repo, and then running FB checks.

https://github.com/thundernixon/inter/tree/qa/misc/googlefonts-qa

**Comment by felipesanches** [comment]
I think it is interpreting the `&` in `crafted & designed` as syntax for an XML entity. Like we do with `&nbsp;` for declaring a non breaking space.

**Comment by thundernixon** [comment]
Ahh that makes so much sense, now that you've explained it.

Indeed, changing the `&` to `&amp;` fixed the issue, and the check is now passing.

Thanks!
