### ISSUE TITLE
Make docs building dependencies optional using "extras_require"

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#2513]
On gitter (https://gitter.im/fontbakery/Lobby?at=5cdef4f97c363c75a7f915eb), @madig asked:
> is there any particular reason fontbakery pulls in all the doc-making dependencies by default?

To which I replied:
> @madig that's because I was unable to figure out how to make ReadTheDocs install the docs extra-dependencies. I would be glad to merge a change that separates again the docs dependencies while keeping a good readthedocs setup

And @anthrotype suggested:
> you should use extras_require so one can do pip install fontbakery[docs] when needed. https://docs.readthedocs.io/en/stable/config-file/v1.html#python-extra-requirements

**Comment by chrissimpkins** [comment]
There are Fontbakery developer docs on how to install the docs dependencies :) 

https://font-bakery.readthedocs.io/en/latest/developer/doc-contrib-guide.html#documentation-contributor-guide

**Comment by felipesanches** [comment]
The challenge at the moment here is how to setup tox to install `fontbakery[docs]`
