### ISSUE TITLE
check/points_out_of_bounds -- CLI output needs readability improvement

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#2518]
## Observed behaviour
![fb-points](https://user-images.githubusercontent.com/5162664/58570953-e252c280-8206-11e9-9d9f-1a3375bca021.png)

## Expected behaviour
Readable output that isn't intimidating, hard to read or overly verbose.

## Resources and exact process needed to replicate
Most fonts return a `WARN` for this check. Public Sans is used in the screenshot above.

**Comment by felipesanches** [comment]
This is the formatting of the log messages after improving their readability:

<img width="1280" alt="Captura de Tela 2019-05-31 às 15 44 07" src="https://user-images.githubusercontent.com/213676/58709729-0d7e1300-83bb-11e9-9cef-fad532387a8d.png">

**Comment by eliheuer** [comment]
This is what running the check on the full collection before the fix

![pre-fix](https://user-images.githubusercontent.com/5162664/58709623-90d24100-8388-11e9-817a-6e4e570885f8.png)

**Comment by felipesanches** [comment]
And this is the state of the Google Fonts collection after fixing the rounding bug in this "points out of BBOX" check:

<img width="1280" alt="Captura de Tela 2019-05-31 às 01 14 27" src="https://user-images.githubusercontent.com/213676/58709933-7bc2d580-83bb-11e9-84df-3ac2f31619d8.png">

**Comment by felipesanches** [comment]
* 768+1950 = 2718
* 646 + 2073 = 2719
* 768-646 = 122
* 122/2718 = roughtly 4.5% of the originally reported WARN messages were false WARNs
* 646 / 2719 = 23.7% of the collection actually have a bounding box problem
