### ISSUE TITLE
New check needed to make sure DESCRIPTION.html has an upstream Git repo url

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#2523]
## Observed behaviour

Marc says this is needed and we don't have it.

## Expected behaviour

Check if the DESCRIPTION.html file has a link to an upstream git repo host. Otherwise instruct the user to add one.

**Comment by felipesanches** [comment]
please also add:
* a rationale metadata field describing the importance of this checking routine
* a CHANGELOG entry mentioning this new check
