### ISSUE TITLE
Add a command-line arg to output rationales along with check results?

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#2531]
## Observed behaviour

The checks show a basic doc string in the cli output, for example:

![check](https://user-images.githubusercontent.com/5162664/58759680-162a3280-84fc-11e9-95af-8ba212475be8.png)

## Expected behaviour

There is additional information in the rationale that can be very helpful, for example:

![rational](https://user-images.githubusercontent.com/5162664/58760128-c2bae300-8501-11e9-9519-b7d37eac68b5.png)

When fixing `FAILS` and `WARNS` users sometimes need to look at the rationale in the source code to get more context on issues. It isn't initially clear that you can or should do this.

We could add the rationale to the CLI output, which would make the output more verbose but might make using fontbakery easier for new users. For more experienced FontBakery users a flag could be used to hide the rationale part of the output.

**Comment by eliheuer** [comment]
Bump, in the email thread from today Dave asked: 
> Isn't there a command line arg to output the rationales along with the check results?

@felipesanches Can we add a command-line arg like `--print-rationale` to `Lib/fontbakery/commands/check_profile.py` so we can get rationale output in the terminal for each check?

**Comment by felipesanches** [comment]
I'd advocate for making it the default behaviour and then maybe add a `--hide-rationale` command-line arg.

**Comment by eliheuer** [comment]
Yeah, I like that, making it default would work. It would make it easier to notice when a rationale needs work and might push users to keep rationales updated and fill in the missing information.

**Comment by felipesanches** [comment]
sure!

I will then make it default behaviour and I will not add the `--hide-rationale` option unless somebody actively complains about the output being too verbose.

**Comment by felipesanches** [comment]
# text terminal output examples:

![Screenshot at 2019-10-23 01:50:54](https://user-images.githubusercontent.com/213676/67358722-cacafc00-f550-11e9-9ebc-5d3795ba1cef.png)

![Screenshot at 2019-10-23 01:50:29](https://user-images.githubusercontent.com/213676/67358724-cb639280-f550-11e9-9f1a-70db8729afdc.png)

# github markdown output example:
![Screenshot at 2019-10-23 01:52:49](https://user-images.githubusercontent.com/213676/67358787-fbab3100-f550-11e9-89a0-15389fec65f0.png)

**Comment by vv-monsalve** [comment]
> We could add the rationale to the CLI output, which would make the output more verbose but might make using fontbakery easier for new users.

It could be an option. Though currently there is a midway term that I think works great. Cl output has both: a short, functional text that says what must be done, and if you want or need more information about it, a link to Font Bakery documentation where you can find a good explanatory rationale.
E.g.
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/family/win_ascent_and_descent](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent)
* 🔥 **FAIL** OS/2.usWinAscent value should be equal or greater than 1049, but got 993 instead [code: ascent]
* 🔥 **FAIL** OS/2.usWinDescent value should be equal or greater than 370, but got 263 instead [code: descent]

</details>

**Comment by vv-monsalve** [comment]
And cases that could be improved are the ones when both, the output and the link have the same text and are not really informative or explicative.

<details>
<summary>⚠ <b>WARN:</b> Make sure all font files have the same version value.</summary>

* [com.google.fonts/check/family/equal_font_versions](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/head.html#com.google.fonts/check/family/equal_font_versions)
* ⚠ **WARN** Version info differs among font files of the same font project.
These were the version values found:
* Kufam-Black.ttf: 1.2
* Kufam-BlackItalic.ttf: 1.002
* Kufam-Bold.ttf: 1.2
* Kufam-BoldItalic.ttf: 1.002
* Kufam-Italic.ttf: 1.002
* Kufam-Medium.ttf: 1.2
* Kufam-MediumItalic.ttf: 1.002
* Kufam-Regular.ttf: 1.2
* Kufam-SemiBold.ttf: 1.2
* Kufam-SemiBoldItalic.ttf: 1.002
 [code: mismatch]

</details>
