### ISSUE TITLE
Do we still want to promote the EPAR table?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#2534]
@davelab6, this check (`com.google.fonts/check/epar`) mentions your name. Do you still want to promote adoption of the EPAR table?

<img width="740" alt="Captura de Tela 2019-06-03 às 02 55 46" src="https://user-images.githubusercontent.com/213676/58769859-6c09e380-85ab-11e9-9edd-4f58e0b63931.png">

**Comment by davelab6** [comment]
Let's move this to INFO results in all cases

**Comment by felipesanches** [comment]
yes, this check is already emitting an INFO if EPAR is not present.

https://font-bakery.readthedocs.io/en/latest/_modules/fontbakery/profiles/googlefonts.html#com_google_fonts_check_epar
