### ISSUE TITLE
Add quick check for DESC that mentions VFs

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2538]
## Observed behaviour

Families with variable fonts do not always mention that in their descriptions

## Expected behaviour

When searching all descriptions for variable fonts, I want to get accurate results.

Therefore there should be check for if a standard boilerplate sentence is in the DESCRIPTION for each families available as VF, that says `This family is available as a variable font.`

**Comment by felipesanches** [comment]
## Fontbakery report

Fontbakery version: 0.7.5

<details>
<summary><b>[1] AmstelvarAlpha-VF.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] ArchivoVFBeta-Italic.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] ArchivoVFBeta.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] Asap-VF.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] AsapVFBeta-Condensed.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] AsapVFBeta-Italic.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] AsapVFBeta.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] CabinVFBeta-Italic.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] CabinVFBeta.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] Comfortaa-Regular.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] CrimsonPro-ExtraLightItalic.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] CrimsonPro-ExtraLight.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] DecovarAlpha-VF.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] ElMessiri-VF.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] FaustinaVFBeta-Italic.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] FaustinaVFBeta.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] LemonadaVFBeta.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] Literata-Italic.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] Literata-Regular.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] MarkaziText-Roman-VF.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] MarkaziText-VF.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] MavenPro-Regular.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] MavenProVFBeta.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] Muli-Italic.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] Muli-Regular.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] Oswald-Regular.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] PodkovaVFBeta.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] RokkittVFBeta.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] Vollkorn-Italic.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] Vollkorn-Regular.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 30 | 0 | 2688 | 0 | 0 |
| 0% | 1% | 0% | 99% | 0% | 0% |

**Note:** The following loglevels were omitted in this report:
* **WARN**
* **SKIP**
* **INFO**
* **PASS**

**Comment by felipesanches** [comment]
The results in the previous message are stricly looking for the sentence `"This family is available as a variable font".`

I think it can be OK to be less strict and accept the mere presence of the term `variable font` as a **PASS**.

For instance, AmstelvarAlpha failed, even though it mentions "A serif text variable font, by David Berlow."

I will make the check less strict.

**Comment by felipesanches** [comment]
Current state of the GFonts collection with the strict check:
![Screenshot at 2019-06-05 17:53:44](https://user-images.githubusercontent.com/213676/58971807-bd80c100-87ab-11e9-84d8-15db7b791b19.png)

**Comment by felipesanches** [comment]
With the less strict check, here's what we get:

![Screenshot at 2019-06-05 18:14:48](https://user-images.githubusercontent.com/213676/58972534-49dfb380-87ad-11e9-84c8-3528c3ce10e5.png)


## Fontbakery report

Fontbakery version: 0.7.5

<details>
<summary><b>[1] Asap-VF.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] Comfortaa-Regular.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] ElMessiri-VF.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>
<details>
<summary><b>[1] MarkaziText-Roman-VF.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please include the following sentence in the DESCRIPTION.en-us.html file:

This family is available as a variable font.

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 4 | 0 | 2691 | 0 | 23 |
| 0% | 0% | 0% | 99% | 0% | 1% |

**Note:** The following loglevels were omitted in this report:
* **WARN**
* **SKIP**
* **INFO**
* **PASS**
