### ISSUE TITLE
 ERROR: Failed with KeyError: "'head' table not found"

### ISSUE THREAD

**Issue by bghryct** [googlefonts/fontbakery#2540]
**Observed Behavior**

After making Karla-Italic-VF.ttf in with fontmake as below

```fontmake -g sources/Karla-Italic.glyphs -o variable --output-path ./fonts/variable/Karla-Italic-VF.ttf```

When I put output  Karla-Italic-VF.ttf through fontbakery I get the following error

```>> com.google.fonts/check/version_bump with (('font[0]', 'Karla-Italic-VF.ttf'),)
   Version number has increased since previous release on Google Fonts?
 * ERROR: Failed with KeyError: "'head' table not found"
           File "/usr/local/lib/python3.7/site-packages/fontbakery/checkrunner.py", line 345, in _exec_check
             for sub_result in result:  # Might raise.
           File "/usr/local/lib/python3.7/site-packages/fontbakery/profiles/googlefonts.py", line 2072, in com_google_fonts_check_version_bump
             github_gfonts_v_number = github_gfonts_ttFont["head"].fontRevision
           File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 410, in __getitem__
             raise KeyError("'%s' table not found" % tag)
         

   Result: ERROR
```

 ## **Expected behaviour**

I was not expecting an error. The version number is set higher than 'live' karla on GF.
and when I TTX -t head Karla-Italic-VF.ttf a head table is dumped. 

##  **Resources and exact process needed to replicate**

https://github.com/bghryct/karmilla/tree/qa

running fontmake to build a VF on sources/Karla-Italic.glyphs should produce the offending .ttf for testing in FB

**Comment by felipesanches** [comment]
hey, Mirko! There was indeed a bug in fontbakery. I have just figured it out and fixed the issue Cheers! :-)

**Comment by davelab6** [comment]
Great work Mikro and Felipe!
