### ISSUE TITLE
Improve com.google.fonts/check/version_bump

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2543]
## Observed behaviour

https://github.com/google/fonts/pull/2017#issuecomment-500369925 has a ERROR; versions for new families doesn't make sense, so the check needs improvement :) 

## Expected behaviour

No error. 

<img width="714" alt="Screen Shot 2019-06-12 at 12 27 50 AM" src="https://user-images.githubusercontent.com/261579/59323534-06071580-8ca9-11e9-8552-fe5cd3be720e.png">

**Comment by felipesanches** [comment]
thanks, @davelab6 ! This issue gave me the clue I needed in order to fix not only this one but also #2540

**Comment by felipesanches** [comment]
Now the check will not emit an ERROR and will also not run if the family is not yet on github and on GFonts

**Comment by felipesanches** [comment]
it was fixed by #2544
