### ISSUE TITLE
Improve com.google.fonts/check/vendor_id

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2548]
## Observed behaviour

https://github.com/google/fonts/pull/2021#issuecomment-501169177 says

> Checking OS/2 achVendID.
>
> ⚠ WARN OS/2 VendorID value 'TT��' is not a known registered id. You should set it to your own 4 character code, and register that code with Microsoft at microsoft.com/typography/links/vendorlist.aspx [code: unknown]

But this exists on https://docs.microsoft.com/en-us/typography/vendors/ :

<img width="682" alt="Screen Shot 2019-06-12 at 10 06 01 AM" src="https://user-images.githubusercontent.com/261579/59357995-ccaac600-8cf9-11e9-9024-b028670fcb3a.png">

However, @m4rc1e says that the cached version doesn't have it. So I guess we need some better way  to do cache invalidation of that page's data..

## Expected behaviour

The value is correctly identified from current data.

**Comment by felipesanches** [comment]
The cached data does have that. And it is updated very frequently. It is always updated prior to our weekly releases.

The problem here is that fontbakery did not recognize NULL-padding, but only space-padding on vendor IDs.

I have just modified the code to accept NULL-padding.

**Comment by m4rc1e** [comment]
Thanks!

**Comment by davelab6** [comment]
Supporting both null and space seems fine to me

**Comment by felipesanches** [comment]
thanks, Dave!
