### ISSUE TITLE
[GF Profile] Make sure canonical style name checks are strongly enforced

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2573]
FontBakery GF Profile should be clear with users about https://github.com/google/fonts/pull/1908#issuecomment-507675621 so that my manual intervention is not needed.

**Comment by m4rc1e** [comment]
We do have an [Instance names](https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/profiles/googlefonts.py#L3718-L3738) check which will produce a FAIL if any instance is named incorrectly.

I was just seeing if we could wing it.

**Comment by felipesanches** [comment]
@m4rc1e originally said:

> rsheeter, it seems we have a slight issue with instance names. This font has "Extra Bold" when it should be "ExtraBold" etc. Will this cause any problems on your end? if not, we can merge once we've fixed the issues below.

to which @davelab6 replied:

> Yes, it causes problems with systems that look up styles based on style name. Needs to be fixed.

The FontBakery check that informed @m4rc1e about the "ExtraBold" issue was **com.google.fonts/check/varfont_instance_names**:

![Screenshot at 2019-07-11 18:43:28](https://user-images.githubusercontent.com/213676/61087371-f2c0a480-a424-11e9-9bda-bfc7d2eb505e.png)


I believe that what Dave is asking for here is just that the wording of the log messages should more explicitely make it clear that FAILing the check means that real problems will surface in some of the internal Google Fonts systems that deal with the fonts by looking up their style name / instance name.
