### ISSUE TITLE
[GF Profile] Add checks for descriptions

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2574]
Marc requested changes to descriptions in https://github.com/google/fonts/pull/1908#issuecomment-507170360 that we should have checks for.

**Comment by felipesanches** [comment]
## Description.en_us.html: mention the upstream url, e.g amaticsc 

This is checked by [com.google.fonts/check/description/git_url](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/git_url)

## Description.en_us.html: mention that the fonts are vf

This is checked by [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)

**Comment by felipesanches** [comment]
And those checks were indeed executed correctly on the Inter PR:

<img width="702" alt="Captura de Tela 2019-07-02 às 11 42 02" src="https://user-images.githubusercontent.com/213676/60521973-8d4f1400-9cbe-11e9-99c1-517c1b10d109.png">
