### ISSUE TITLE
[GF Profile] Check for static fonts

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2575]
## Observed behaviour

In https://github.com/google/fonts/pull/1908#issuecomment-508268830 I noticed that static fonts were supplied in a PR, but (a) in a subdirectory and (b) not referenced in the METADATA.pb file. 

## Expected behaviour

- [x] Check there are no subdirectories and WARN if there are any. 

- [x] Check that all `*.ttf` files are included in the METADATA file if they are present in the directory. 

- [x] Check that files included in the METADATA file are present, if we don't already have that check :)

**Comment by rsheeter** [comment]
otf too
