### ISSUE TITLE
check/name/ascii_only_entries: Improve FAIL message

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#2588]
For com.google.fonts/check/name/ascii_only_entries, we have the following fail message:

> There are N strings containing non-ASCII characters in the ASCII-only NAME table entries.

It would be great if the message could tell users which name record is at fault and what the characters are. Even better would be displaying a string segment.

Found in issue, https://github.com/magictype/gold/issues/1#issue-454116793

**Comment by felipesanches** [comment]
these strings are actually printed as INFO messages. Perhaps you don't see them because you filtered-out INFO messages.

![Screenshot at 2019-09-26 18:44:49](https://user-images.githubusercontent.com/213676/65727331-f5877900-e0a6-11e9-8301-cf361ffe7304.png)

**Comment by felipesanches** [comment]
I will change the "bad-string" messages to FAIL-level so that you will always see them.
