### ISSUE TITLE
How to set 3 set  on the flags of the head table

### ISSUE THREAD

**Issue by lettersoup** [googlefonts/fontbakery#2590]
Hi,
I become following fail from FB:

> * FAIL: This is a hinted font, so it must have bit 3 set on the flags of the head table, so that PPEM values will be rounded into and integer value.

Does anybody know how to fix the CFFs and the TTFs? The Fonts are produced with Glyphs App. Unfortunately at the moment there is no possibility to set it in GlyphsApp.

**Comment by m4rc1e** [comment]
I use `gftools fix-hinting`.

Gftools repo can be found here, https://github.com/googlefonts/gftools

We still haven't converted all script to py3 so pip installing it via pypi doesn't work. However, we can do the following:

```
# create virtualenv
python3 -m venv venv

# activate virtualenv
source venv/bin/activate

# install gftools
pip install git+https://www.github.com/googlefonts/tools
```

To run the script do:

`gftools fix-hinting font.ttf`

**Comment by lettersoup** [comment]
Unfortunately I got following error installing gftools:

Installing collected packages: pycairo, uharfbuzz, freetype-py, fontdiffenator, simplejson, pybrowserstack-screenshots, gfdiffbrowsers, gftools
  Running setup.py install for pycairo ... error
    ERROR: Complete output from command /Users/.../venv/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/w_/rp4ql6h12tvfqfxrsx6nsp840000gn/T/pip-install-inkovy67/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/w_/rp4ql6h12tvfqfxrsx6nsp840000gn/T/pip-record-1hh5ev3u/install-record.txt --single-version-externally-managed --compile --install-headers /Users/.../venv/include/site/python3.7/pycairo:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    creating build/lib.macosx-10.14-x86_64-3.7/cairo
    copying cairo/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/cairo
    copying cairo/__init__.pyi -> build/lib.macosx-10.14-x86_64-3.7/cairo
    copying cairo/py.typed -> build/lib.macosx-10.14-x86_64-3.7/cairo
    running build_ext
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'gobject-2.0', not found
    Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command "/Users/.../venv/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/w_/rp4ql6h12tvfqfxrsx6nsp840000gn/T/pip-install-inkovy67/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/w_/rp4ql6h12tvfqfxrsx6nsp840000gn/T/pip-record-1hh5ev3u/install-record.txt --single-version-externally-managed --compile --install-headers /Users/.../venv/include/site/python3.7/pycairo" failed with error code 1 in /private/var/folders/w_/rp4ql6h12tvfqfxrsx6nsp840000gn/T/pip-install-inkovy67/pycairo/

**Comment by felipesanches** [comment]
I think that you will not get that error is you create a clean virtual environment and then install it.

@m4rc1e's comment describes how to setup the virtualenv

**Comment by m4rc1e** [comment]
I think he tried installing installing it. The traceback looks like pycairo can't find libffi, this issue seems quite common, https://github.com/lovell/sharp/issues/1603#issuecomment-489300531

@lettersoup Can you try this command before installing gftools again.

`export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/opt/libffi/lib/pkgconfig"`

Then redo my previous instructions.

**Comment by felipesanches** [comment]
thanks, @m4rc1e

**Comment by chrissimpkins** [comment]
This Python 3 script will set bit 3 in the head table flags. Requires a [fontTools library](https://github.com/fonttools) install before you run it.

```python
from fontTools.ttLib import TTFont

# enter the path to your ttf or otf font file
FONT_PATH = "/path/to/your/font.ttf"

tt = TTFont(FONT_PATH)
head = tt["head"]

# print binary string before the edit
print(format(head.flags, "016b"))

# set head.flags bit 3 to 1
head.flags = head.flags | (1 << 3)

# print binary string after the edit
print(format(head.flags, "016b"))

# save the edited font file
tt.save()
```

Save above as `bit3set.py`, enter your font path on the `FONT_PATH` line, and run:

```
python3 bit3set.py 
```

Bit 3 will be the fourth number **from the right** in the strings that print to your terminal.  You should be able to verify that it flips from 0 to 1 from line 1 to line 2 of the output.

**Comment by simoncozens** [comment]
Looks like we have answered this question; `gftools fix-font` is the recommended way to fix "structural" issues reported by fontbakery. If you have any more problems installing `gftools`, please ask on that repo.
