### ISSUE TITLE
Add `check-cjk` CJK font quality assurance profile

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/fontbakery#2593]
It would be helpful to include a profile that has CJK-specific QA checks in the fontbakery project.  

This would allow developers of CJK typefaces to run:

`fontbakery check-cjk [CJK FONT PATH]`

in order to execute the entire panel of tests that are intended for CJK fonts.

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/fontbakery/pull/2594

**Comment by chrissimpkins** [comment]
Is it possible to define one or more tests that execute before all other tests in a profile and abort the remaining tests if it(they) fail?  I would like to define a "is this a CJK font?" style check on the font file prior to the QA checks.

**Comment by felipesanches** [comment]
you can create a condition and declare it on all checks that depend on it. If the condition is False we skip the check.

**Comment by chrissimpkins** [comment]
Let me check the docs / other profiles to see how I do that.  Thanks Felipe!

**Comment by felipesanches** [comment]
here's an example:

![Screenshot at 2019-07-25 14:33:16](https://user-images.githubusercontent.com/213676/61895487-51e0e780-af02-11e9-8241-d8828aa359de.png)


![Screenshot at 2019-07-25 14:32:45](https://user-images.githubusercontent.com/213676/61895497-560d0500-af02-11e9-8422-aebdff579ee5.png)

**Comment by chrissimpkins** [comment]
If the condition is not met for a given check, is the test result considered a SKIP?

**Comment by felipesanches** [comment]
exactly!
