### ISSUE TITLE
Feature Request: Downgrade from FAIL to WARN in a vendor profile

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#2602]
In #2356 @cjchapman writes: 

> Along these lines, there are a number of checks that we (at Adobe Fonts) would like to downgrade from `FAIL` to `WARN` in the `check-adobefonts` profile (rather than just completely exclude them). Some frequently occurring examples include:
> * `com.google.fonts/check/dsig`
> * `com.google.fonts/check/whitespace_glyphs`
> * `com.google.fonts/check/valid_glyphnames`

And for #2558 @felipesanches was "Adding keywords for all non-PASS messages" (#2589, #2596, #2601 [, …?]).

These keywords make it possible to write precise overrides for checks.

@felipesanches and I were discussing in https://gitter.im/fontbakery/Lobby?at=5d3f6892c356af25e04fc2ce about changing check results and figured that a vendor profile should do this kind of overriding in the profile directly, e.g. by wrapping the original check and applying overrides, possibly using the keywords, in the wrapper.

We can simply create documentation, how to create such a wrapper, or also add a generic approach to the library, so that not so much boilerplate needs to be created.

**Comment by felipesanches** [comment]
A `log_message_override(check_id, log_msg_keyword, loglevel_override)` method on the `Profile` class.

if there's a `com.google.fonts/check/foo` with a `FAIL` with keyword `bar` and a profile imports it but wants the `"bar"` message to become a mere `WARN` then the method would be invoked like this:

```python
profile.log_message_override("com.google.fonts/check/foo", "bar",
                             WARN,
                             """Vendor XYZ considers this to be a warn-level result
                                because of blah blah
                                and so on...
                             """)
```

**Comment by felipesanches** [comment]
This would then feed the internal data structures that aare used to generate the sphinx documentation for the profile so that the override is correctly reported on the docs

**Comment by felipesanches** [comment]
oh... but maybe we should think more carefully aobut the method name. Because we also may need to over-ride the actual log message strings instead of the severity level of the results!

We can have a couple methods (one for the message string and another for the message result-status) or we can have a method that does both things.

I have the impression that a single method for both would be better.
