### ISSUE TITLE
TYPOGRAPHIC_SUBFAMILY_NAME for Win is incorrect. It must be "Thin"

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontbakery#2607]
Might not be the right place to ask, but I thought I'd try anyway.

I don't understand the failure `TYPOGRAPHIC_SUBFAMILY_NAME for Win is incorrect. It must be "Thin"` at all.
Yes, I have instances in this Glyphs source that are called `Thin`.

How do I fix this?
Thanks!

**Comment by yanone** [comment]
Hi @felipesanches,
I’ve looked into this a bit further and I’m not sure why you labeled this as a support issue.

The FAIL in the end stems from a method called [`_win_style_name(string)`](https://github.com/googlefonts/fontbakery/blob/487dc43ba06f915fac481343dfc1c0925e072aaa/Lib/fontbakery/parse.py#L84), and it returns `Regular` for each style regardless of the actual style name of the font.

Now, either this is wrong, or checking win style names for a variable font at all is wrong. Sorry, I didn’t mention that it’s a variable font. Something doesn’t make sense here.

Please treat this as a programming issue.

**Comment by felipesanches** [comment]
I labeled it as "Support" because you said "I don't understand the failure" and "How do I fix this?" which sound like user support questions.

You new set of comments look more like a bug report.

**Comment by m4rc1e** [comment]
Perhaps the default instance in the VF is the Thin weight? This means it must use Typographic family and subfamily names since the font is non-RIBBI (Regular, Italic, Bold, Bold Italic).

**Comment by davelab6** [comment]
@felipesanches please prioritize

**Comment by felipesanches** [comment]
@yanone, I suppose that this issue may be related to your Big Shoulders project, right? I will now inspect those files with Font Bakery to see if I can replicate your issue locally.

**Comment by felipesanches** [comment]
These are the files I am inspecting:
![Screenshot at 2019-09-23 13:12:28](https://user-images.githubusercontent.com/213676/65443137-02913780-de1d-11e9-9a7b-7f626e0fc44c.png)

And these are the Font Bakery check results for `com.google.fonts/check/name/typographicsubfamilyname`:
![Screenshot at 2019-09-23 13:11:38](https://user-images.githubusercontent.com/213676/65443166-12a91700-de1d-11e9-809f-f57b234ab501.png)

**Comment by felipesanches** [comment]
I will now lookup the source code of this check.

**Comment by felipesanches** [comment]
But before looking at the source code, I have a hunch that Marc's https://github.com/googlefonts/fontbakery/issues/2607#issuecomment-525306606 may be the best explanation to the issue.

**Comment by felipesanches** [comment]
At https://github.com/felipesanches/fontbakery/commit/17dc55e1b23abd361d09778d292f99aefde0972d I have added the actual incorrect value of the name entry in the log message so that it is more explicit.

![Screenshot at 2019-09-23 16:48:51](https://user-images.githubusercontent.com/213676/65457490-324f3800-de3b-11e9-9d03-7cce17cd474d.png)

And then inspecting your variable font with ttx I found this:
![Screenshot at 2019-09-23 16:46:09](https://user-images.githubusercontent.com/213676/65457530-472bcb80-de3b-11e9-990e-1408db22be49.png)
