### ISSUE TITLE
ERROR: Check variable font instances have correct coordinate values

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontbakery#2608]
The `instance_parse()` method computes `wght` and `wdth` values to compare against, but my [font](https://github.com/xotypeco/big_shoulders/blob/master/source/Big%20Shoulders.glyphs) has `wght` and `opsz` axes.

```
 * ERROR: Failed with KeyError: 'opsz'
           File "/usr/local/lib/python3.7/site-packages/fontbakery/checkrunner.py", line 342, in _exec_check
             for sub_result in result:  # Might raise.
           File "/usr/local/lib/python3.7/site-packages/fontbakery/profiles/googlefonts.py", line 3711, in com_google_fonts_check_varfont_instances_coordinates
             if instance.coordinates[axis] != expected_instance.coordinates[axis]:
```

**Comment by m4rc1e** [comment]
Our [instance/name parser](https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/parse.py) cannot handle the opsz axis yet. Do we have any idea how we are going to name different opsz instances?

**Comment by davelab6** [comment]
"Family 000pt Width Weight" where 000 is the pt size of the opsz..

**Comment by laerm0** [comment]
> "Family 000pt Width Weight" where 000 is the pt size of the opsz..

So the idea here is that `000pt` would be replaced in an instance name by `10pt` `30pt` `72pt` and so on? This works for me. In #2708 (huh, exactly a hundred issues later) I discussed why naming an instance of `opsz` "Regular" makes no sense so this logic holds up much better.
