### ISSUE TITLE
FAIL: OS/2 sTypoAscender and hhea ascent must be equal. [code: ascender]

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontbakery#2611]
Google Fonts’ `fixfonts.py` doesn’t set enough vertical metrics (on [this font](https://github.com/xotypeco/big_shoulders/blob/master/source/Big%20Shoulders.glyphs)) to pass the `check-googlefonts` test (see subject).

When applying my own vertical metrics calculations that stem back from FSI’s conduct, fontbakery shows another error.

So I’m wondering if there is a canonical way that GF likes to calculate the vertical metrics? I could apply them manually to the source or prepare a PR to `fixfonts.py`, or we need to adjust the `check-googlefonts` test?

Thanks.

**Comment by m4rc1e** [comment]
fixfonts.py will only set the win metrics to the font's bounding box, if the family doesn't exist on GF. If it exists, it will attempt to make the vertical metrics have the same visual appearance.

> So I’m wondering if there is a canonical way that GF likes to calculate the vertical metrics

I proposed this [schema](https://github.com/googlefonts/fontbakery/issues/2164#issuecomment-436595886) last year.

**Comment by yanone** [comment]
Thanks, @m4rc1e 

Could you please look over the attached Glyphs script that I wrote according to your proposed schema?
And please pay extra attention to the negative numbers. I'm not sure whether I set `winDescent` correctly to be an absolute number.

```
from GlyphsApp import *
f = Glyphs.font

import unicodedata

def recursiveDecompositionUnicodes(char):
	'''Recursively lists all unicodes that a given character is composed of, using Python’s own unicodedata module. 
	Example:
		A -> ['0041']
		Ă -> ['0041', '0306']
		Ắ -> ['0041', '0306', '0301']'''

	import unicodedata
	
	unicodes = []
	decompositionList = unicodedata.decomposition(char).split(' ')

	# Catch '<compat>' value	
	try:
		l = [int(x, 16) for x in decompositionList if x]
	except:
		return []

	if decompositionList:
		recursive = []	
		for code in decompositionList:
			if code:
				r = recursiveDecompositionUnicodes(unichr(int(code, 16)))
				recursive.extend(r)
		
		if recursive:
			unicodes.extend(recursive)
		else:
			unicodes.extend([str(hex(ord(char)).split('x')[1].zfill(4))])
	
	return unicodes


def verticalBBox(glyph):
	
	_max = None
	_min = None
	
	for layer in glyph.layers:
		
		top = layer.bounds.origin.y + layer.bounds.size.height
		bottom = layer.bounds.origin.y
		
		if not _max:
			_max = top
		else:
			_max = max(_max, top)
		if not _min:
			_min = bottom
		else:
			_min = min(_min, bottom)

	return _min, _max		
		
			
			
# According to https://github.com/googlefonts/fontbakery/issues/2164#issuecomment-436595886

tallestSingleAccentCap = None
lowestLowercase = None
yMax = None
yMin = None

for g in f.glyphs:	

	bbox = verticalBBox(g)
	_min, _max = bbox

	if g.string:

		# tallestSingleAccentCapGlyph
		if unicodedata.category(g.string) == 'Lu' and len(recursiveDecompositionUnicodes(g.string)) == 2:
			if not tallestSingleAccentCapGlyphTop:
				tallestSingleAccentCap = _max
			else:
				tallestSingleAccentCap = max(tallestSingleAccentCap, _max)

		# tallestSingleAccentCapGlyph
		if unicodedata.category(g.string) == 'Ll' and len(recursiveDecompositionUnicodes(g.string)) == 1:
			if not lowestLowercase:
				lowestLowercase = _min
			else:
				lowestLowercase = min(lowestLowercase, _min)
				
	# yMax/yMin
	if _min:
		if not yMin:
			yMin = _min
		else:
			yMin = min(yMin, _min)
	if _max:
		if not yMax:
			yMax = _max
		else:
			yMax = max(yMax, _max)
		
		
print 'hheaAscender', tallestSingleAccentCap
print 'hheaDescender', lowestLowercase
print 'hheaLineGap', 0
print 'typoAscender', tallestSingleAccentCap
print 'typoDescender', lowestLowercase
print 'winAscent', yMax
print 'winDescent', abs(yMin)

```

**Comment by yanone** [comment]
I created a PR with the above Glyphs script to `gs-glyphs-scripts` after confirming with the "The Webfont Strategy, more general" section at https://glyphsapp.com/tutorials/vertical-metrics that the values make sense.

We can discuss how to integrate the script into `gs-glyphs-scripts`, but I'm closing this issue here, as the `fontbakery` test now passes on this.

PR: https://github.com/googlefonts/gf-glyphs-scripts/pull/52
