### ISSUE TITLE
FAIL: Verify that each group of fonts with the same nameID 1 has maximum of 4 fonts

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery#2613]
## Observed behavior

After running QA in at least 3 different families with more than 4 weights this Fail emerged:
🔥 FAIL: Verify that each group of fonts with the same nameID 1 has maximum of 4 fonts
com.adobe.fonts/check/family/max_4_fonts_per_family_name
🔥 FAIL Family 'Solway' has 5 fonts (should be 4 or fewer).

Despite Family Name and Style Name fields seems to be ok in the file, as indicated in [Glyphs](https://glyphsapp.com/tutorials/naming), and that they were set in the same way that other fonts that don't report this error.

Note: Gelasio used to report this same Fail, but now after ftxvalidator was fixed, for some reason it doesn't happen anymore for this font, while it remains in Solway and Kufam. Same checks on Font Names were followed in Glyphs file of each project.

## Expected behavior

To obtain the same positive results after following alike procedures, and to get on clearer reasons or instructions on what could be missing or must be fixed.

## Resources and exact process needed to replicate

Looking for possible clues I downloaded Montserrat project to check how is managed there. But, while the Glyphs file seems to follow the same protocol, after running FontBakery on Roman ttf's the same Fail was reported.

![QA-Montserrat](https://user-images.githubusercontent.com/48698976/63312185-4ba61700-c2c6-11e9-9ce8-d4942ffc8f83.png)

Gelasio last [md report](https://github.com/vv-monsalve/Gelasio/tree/QA-Gelasio/Gelasio_TTFqa/qaGelasio4/Fontbakery)
Solway last [md report](https://github.com/vv-monsalve/Solway/tree/QA-Solway/Solway%20Font%20Files/SolwayTTF_qa/qaSolway8/Fontbakery)
Kufam last [md report](https://github.com/vv-monsalve/kufam/tree/QA-Kufam/Fonts_ttf/qaKufamR9/Fontbakery)

**Comment by m4rc1e** [comment]
Thanks for reporting this.

This test only fails on families which contain Mac name records.

@felipesanches this check should only run on Win name records. Our Mac records are not set in the same manner as the win records. They do not use typo family (16) and typo subfamily (17) name records. 

For ref, here's Montserrat Medium:

id | string
--- | --- | 
(0, 1, 0, 0) | Copyright 2011 The Montserrat Project Authors (https://github.com/JulietaUla/Montserrat)
(1, 1, 0, 0) | Montserrat
(2, 1, 0, 0) | Medium
(3, 1, 0, 0) | 7.200;ULA ;Montserrat-Medium
(4, 1, 0, 0) | Montserrat Medium
(5, 1, 0, 0) | Version 7.200
(6, 1, 0, 0) | Montserrat-Medium
(8, 1, 0, 0) | Julieta Ulanovsky
(9, 1, 0, 0) | Julieta Ulanovsky
(11, 1, 0, 0) | http://www.zkysky.com.ar/
(12, 1, 0, 0) | http://www.zkysky.com.ar/
(13, 1, 0, 0) | This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL
(14, 1, 0, 0) | http://scripts.sil.org/OFL
(0, 3, 1, 1033) | Copyright 2011 The Montserrat Project Authors (https://github.com/JulietaUla/Montserrat)
(1, 3, 1, 1033) | Montserrat Medium
(2, 3, 1, 1033) | Regular
(3, 3, 1, 1033) | 7.200;ULA ;Montserrat-Medium
(4, 3, 1, 1033) | Montserrat Medium
(5, 3, 1, 1033) | Version 7.200
(6, 3, 1, 1033) | Montserrat-Medium
(8, 3, 1, 1033) | Julieta Ulanovsky
(9, 3, 1, 1033) | Julieta Ulanovsky
(11, 3, 1, 1033) | http://www.zkysky.com.ar/
(12, 3, 1, 1033) | http://www.zkysky.com.ar/
(13, 3, 1, 1033) | This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL
(14, 3, 1, 1033) | http://scripts.sil.org/OFL
(16, 3, 1, 1033) | Montserrat
(17, 3, 1, 1033) | Medium

**Comment by m4rc1e** [comment]
Making a pr now/

**Comment by felipesanches** [comment]
thanks, but please note that this check is in the opentype profile, which means it should enforce a requirement of the OpenType spec.
