### ISSUE TITLE
Family name check should reject underscores

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2615]
## Observed behaviour

Marc passed a family to the GF eng team that had underscores in the family names. This caused problems downstream.

## Expected behaviour

Underscores in filenames and therefore family names should be rejected.

**Comment by rsheeter** [comment]
We should just have a common function for the correct filename of a font. This may already exist somewhere.

**Comment by felipesanches** [comment]
I have just used an underscore in place of the usual dash and `com.google.fonts/check/canonical_filename` already detects that it is a bad filename.

![Screenshot at 2019-09-24 17:05:20](https://user-images.githubusercontent.com/213676/65547216-925fe000-df08-11e9-96ce-66039d5db23a.png)

What exactly was Marc's bad filename with an underscore?

**Comment by felipesanches** [comment]
I think that an underscore in the actual familyname would not be detected though. I will add this restriction to the check code.

**Comment by felipesanches** [comment]
@rsheeter, we have a function that computes the expected filename for variable fonts called `variable_font_filename` and declared on `Lib/fontbakery/profiles/googlefonts_conditions.py`.

For static files we only check if the filename contains one of the canonical style strings.
