### ISSUE TITLE
check id and function name mismatch -- ok?

### ISSUE THREAD

**Issue by bobh0303** [googlefonts/fontbakery#2616]
A noob question but: Is there a requirement that the id of a check and the check's function name match?

For example, I just noticed in `googlefonts.py`:
```
@check(
  id = 'com.google.fonts/check/varfont_instance_coordinates',
  conditions = ['is_variable_font'],
)
def com_google_fonts_check_varfont_instances_coordinates(ttFont):
```
and
```
@check(
  id = 'com.google.fonts/check/varfont_instance_names',
  conditions = ['is_variable_font'],
)
def com_google_fonts_check_varfont_instances_names(ttFont):
```
where one has "instance" and the other "instances"

**Comment by graphicore** [comment]
Not a requirement really. We do it as a convention though.

**Comment by bobh0303** [comment]
ok thanks.

Assuming there is no interest in updating the function name to match the id, feel free to close this issue.

**Comment by felipesanches** [comment]
fixed! Thanks for filling this issue, @bobh0303

**Comment by bobh0303** [comment]
I see one was fixed but not the second.

**Comment by felipesanches** [comment]
oh! That's right! I'll fix that other one as well. Thanks!
