### ISSUE TITLE
Feature Request: Downgrade from WARN to INFO on a per-project basis

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2623]
Following https://github.com/googlefonts/fontbakery/issues/2602 it should be possible to addd a `.fontbakery.yml` file that overrides some check results, to eg ignore WARNs that are known to be OK in a project. 

(The fontbakery dashboard should provide a UI for marking results as to be ignored (or urgently actioned) that will be stored in this mechanism upstream long term, but that's another issue :)

**Comment by graphicore** [comment]
This is related to #2356 and #2558

**Comment by davelab6** [comment]
Closing as duplicate :)
