### ISSUE TITLE
nbsp is not valid AGL glyph name

### ISSUE THREAD

**Issue by bobh0303** [googlefonts/fontbakery#2624]
Currently in [`com_google_fonts_check_whitespace_glyphnames`](https://github.com/googlefonts/fontbakery/blob/b0af8caa30917685ae12f0d3c8d5b55911c83653/Lib/fontbakery/profiles/universal.py#L419), the allowed glyph names for U+00A0 are `uni00A0`, `nonbreakingspace`, `nbspace`, and `nbsp`. However, `nbsp` is not [AGL](https://github.com/adobe-type-tools/agl-aglfn)-compliant and should not be among the allowed names for this glyph.

Further, although `nonbreakingspace` and `nbspace` will be correctly recognized, the _recommended_ name for this glyph (according to Adobe's Glyph List For New Fonts) is `uni00A0` and the FAIL message for this test should encourage this name.

**Comment by drj11** [comment]
I agree.

In principle I'm happy to submit a PR to fix this.

It is my understanding that `u00A0` would also be AGL-compliant for this glyph. I would appreciate someone with more expertise backing me up or correcting me on this point.

I propose:

- Only the name `uni00A0` generates a PASS;
- `nonbreakingspace`, `nbspace`, and (my favourite) `u00A0` generates a WARN;
- everything else generates FAIL

**Comment by bobh0303** [comment]
You are correct that `u00A0` is AGL-compliant. However Adobe discourages using the `u` prefix for BMP characters.

I agree with your proposal.

**Comment by drj11** [comment]
Thanks for looking at this @bobh0303 . I've made a proposal for a Pull Request, it will probably need tidying up once the system for testing for WARNs and so on is modified.
