### ISSUE TITLE
Check suggestion: flag PairPos format 2 tables with unreachable kerning

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#2646]
## Observed behaviour

There is a feaLib bug that splits class kerning tables (PairPos format 2) into two with overlapping coverage if there is more than one value format used within the same lookup, leading one of the split off kerning tables to become unreachable. From my understanding, this seems to be most easily triggered if you kern something RTL (e.g. alef-hb) against something LTR (one-hb, a smaller Latin one reachable via GSUB substitution) because it triggers a kerning direction reversal using a different format. You can detect this split by looking for overlapping PairPos format 2 coverage within the same lookup.

## Expected behaviour

Lookup PairPos format 2 subtables have no overlapping coverage and therefore no unreachable kerning.

## Resources and exact process needed to replicate

The original issue with XML and feature file dumps is at https://github.com/googlefonts/ufo2ft/issues/341, see https://github.com/harfbuzz/harfbuzz/issues/1991 for a test TTF.

**Comment by simoncozens** [comment]
I'm not sure this is a worthwhile check these days; it was a problem caused by a specific font building software (which doesn't actually do any damage), and ufo2ft fixed the issue three years ago. I might be wrong so feel free to disagree and reopen...
