### ISSUE TITLE
com.google.fonts/check/varfont/has_HVAR when width is not actually variable

### ISSUE THREAD

**Issue by jenskutilek** [googlefonts/fontbakery#2673]
Report: https://fontbakery.graphicore.de/report/0c144f3e-c48d-4485-a41c-93f63c1d6b43

My variable font produces a FAIL with `com.google.fonts/check/varfont/has_HVAR`. Is `HVAR` really required for variable fonts in which the glyph widths are not actually variable?

This font does have a width axis, which may be not the best axis name because it only changes the width of the outlines, but not the advance widths.

## Resources and exact process needed to replicate

https://github.com/jenskutilek/homecomputer-fonts/blob/master/fonts/Sixtyfour%5Bwdth%2Cwght%5D.ttf

**Comment by anthrotype** [comment]
> Is HVAR really required for variable fonts in which the glyph widths are not actually variable?

even in TTF, it is recommended to still have an HVAR even if empty, otherwise the rendering engine has to check the each glyph's glyf phantom points before knowing whether advances do vary or not.

**Comment by anthrotype** [comment]
https://github.com/fonttools/fonttools/pull/1671#issuecomment-515479258

**Comment by jenskutilek** [comment]
Thanks!
