### ISSUE TITLE
com.google.fonts/check/gpos_kerning_info and monospaced fonts

### ISSUE THREAD

**Issue by jenskutilek** [googlefonts/fontbakery#2674]
https://fontbakery.graphicore.de/report/0c144f3e-c48d-4485-a41c-93f63c1d6b43

`com.google.fonts/check/gpos_kerning_info` produces a warning even though the font is monospaced. Are monospaced fonts ever expected to have kerning? fontbakery could make this warning dependent on the `post.isFixedPitch` flag.

## Resources and exact process needed to replicate

https://github.com/jenskutilek/homecomputer-fonts/blob/master/fonts/Sixtyfour%5Bwdth%2Cwght%5D.ttf

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/fontbakery/pull/3074
