### ISSUE TITLE
Add check to upstream profile: Ensure all needed files (eg license) are included

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2675]
## Observed behaviour

https://github.com/google/fonts/pull/2194 and then https://github.com/google/fonts/pull/2220 were merged, but they  should not have  been merged because they had no license file, and therefore https://github.com/google/fonts/pull/2220 was required.

## Expected behaviour

When FontBakery is run as a CI check, it must ensure that

- [ ] all files in the METADATA file exist, and
- [ ] likewise all files that exist are enumerated in the METADATA files where they can be, and also that 
- [ ] all files that should exist, do exist.

**Comment by graphicore** [comment]
Just got curious, interestingly, the CI checker *ignores all none-font files*. See the difference in SKIP statuses in the FBD report and the CI report in this case google/fonts#2208. I don't know how to get to the travis logs in a closed PR, so take this google/fonts#2207 instead, same symptoms: much more skips in CI than in FBD. The SKIPs are probably mainly (but we can't see this) `Unfulfilled Conditions: license`, `Unfulfilled Conditions: description`, `Unfulfilled Conditions: family_metadata` and so on.


In https://travis-ci.org/google/fonts/builds/598902567?utm_source=github_status&utm_medium=notification Font Bakery is called like this:
```
159.05s$ gftools qa -pr https://github.com/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST -gfb -a -o qa -ogh
INFO:__main__:No regression checks possible since there are fonts before == None
INFO:__main__:Running Fontbakery
```

Digging down, we find that the function `download_fonts_in_pr` from `Lib/gftools/utils.py` is used, [money quote](https://github.com/googlefonts/gftools/blob/9c0433eaaa646aedb7a9009094ab974feee5ea11/Lib/gftools/utils.py#L115):

```py
            if filename.endswith(".ttf") and item["status"] != "removed":
```

With the result that files not ending with `.ttf` are skipped entirely.

This means the CI is blind for all metadata checks concerned with `DESCRIPTION.en_us.html`, `METADATA.pb`, `OFL.txt`.

So, for this check to do anything at all, you must at least also:

- [ ] ensure that METADATA file exist

**Comment by felipesanches** [comment]
@davelab6, fontbakery does all that already.

There's a caveat, though. Some time ago people asked that the license detection also looked for license files on othe directory in which fontbakery is executed.

The Tomorow PR was created by commiting the files placed in a staging directory for testing purposes on the upstream repo, see that the .travis.yml in that repo explicitely creates an empty directory, the copies METADATA.pb and DESCRIPTION.*.html and the built TTFs to that directory and finally runs fontbakery there.

The caveat is that the license in the repo root masked the fact that the staging directory lacked one.

**Comment by felipesanches** [comment]
here's the buils.sh script invoked by .travis.yml in the Tomorrow repo:
https://github.com/MonicaRizzolli/Tomorrow/blob/master/build.sh

**Comment by felipesanches** [comment]
<img width="613" alt="Captura de Tela 2019-10-24 às 22 36 10" src="https://user-images.githubusercontent.com/213676/67536689-c61c5a00-f6ae-11e9-9049-51f5fbadcaf3.png">

**Comment by m4rc1e** [comment]
This is my fault. `gftools qa -pr` doesn't add these files. I can simply update the travis file in google/fonts to check for this.

**Comment by m4rc1e** [comment]
I see. I'm also guilty since running -pr will only fetch the fonts. It needs to grab the metadata, description and license as well if it's there.

**Comment by felipesanches** [comment]
what a debate of lords about who's guilty haha

**Comment by felipesanches** [comment]
#2671 is the kind of feature that caused this sort of problem!

**Comment by felipesanches** [comment]
I think this is done, from a fontbakery codebase perspective. I will double-check this soon before closing, though.

**Comment by felipesanches** [comment]
> all files in the METADATA file exist

**com.google.fonts/check/metadata/filenames** does that.

> likewise all files that exist are enumerated in the METADATA files where they can be, and also that

After @thundernixon's observations at https://github.com/googlefonts/fontbakery/issues/2737#issue-551538392, it seems `static/*.ttf` on VF projects should not be listed on METADATA.pb
