### ISSUE TITLE
Check case of non-MS axes are all caps

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2679]
## Observed behaviour

https://github.com/agyeiarcher/Krspy-VF/issues/32

## Expected behaviour

FB should ensure all axes tags are capitalized correctly; MS' axes are lowercase and others are caps.

## Resources and exact process needed to replicate

https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxisreg#registered-axis-tags

**Comment by simoncozens** [comment]
From a GF perspective, we implement this by checking that the tags are valid according to the axisregistry. @davelab6, please reopen if you still want a check for non-GF uses.
