### ISSUE TITLE
Command-line interface: rationales need consistent formatting

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#2681]
## Observed behaviour

While using the command-line interface the rationales appear to be formatted in an inconsistent and arbitrary way. See the screenshot below for an example.

![cli-fb-test](https://user-images.githubusercontent.com/5162664/67710086-a8444300-f995-11e9-8ed3-dadf789f8608.png)

## Expected behaviour

The rationales should all align with the preceding purple doc string and be prefaced with an indicator explaining what the text is. For example:
```
>> com.google.fonts/check/epar with (('font[0]', 'Lemonada[wght].ttf'),)
   EPAR table present in font?

   Check Rationale: The EPAR table is/was a way of expressing common 
   licensing permissions and restrictions in metadata; while almost nothing 
   supported it, Dave Crossland wonders that adding it to everything in
   Google Fonts could help make it more popular.

   More info is available at:
   https://davelab6.github.io/epar/
```

Ideally the `Check Rationale:` preface would be in a color that sets it apart from the rest of the rationale text, like the green used for `PASS`.

![pass](https://user-images.githubusercontent.com/5162664/67711423-551fbf80-f998-11e9-8b1f-08179718bdb7.png)

Finally, the line length of the rationale text should be consistent, note that it isn't in the above screenshot. I suggest keeping all the rationale text as close to 80 character wide as possible.

## Resources and exact process needed to replicate

Use Fontbakery from the `b138b9e6` commit onward.

**Comment by felipesanches** [comment]
here' s what we got on the terminal output now:
![Screenshot from 2019-11-03 20-11-52](https://user-images.githubusercontent.com/213676/68093651-9c192380-fe76-11e9-90bc-49d535b7e448.png)

I hope you like it ;-)
