### ISSUE TITLE
com.google.fonts/check/glyph_coverage: Please print all missing glyphs

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontbakery#2690]
I regularly run into the issue that fontbakery prints a number of missing glyphs and then "and 10 more" without specifying them. The new rationale printing at least mentions the `GF-latin-core` glyph-set, but I couldn't find that glyph set anywhere, either.
So the work gets stuck at this point. 

Please print out all the missing glyphs, and add a URL to the glyph set to the rationale for reference.
Thank you.

**Comment by felipesanches** [comment]
There are two opposite user requests about this. Some users complain that log messages are too verbose and requested that we shorten the lists of items to "some exemples and N more".

**Comment by yanone** [comment]
Sounds like the need for a verbose level option.

I don't see how fontbakery can do a meaningful service when reports are shortened without options.
I need to find out what those missing glyphs are. Meanwhile I found the definition of the glyph set in the code. Need to write my own script now to calculate the missing glyphs while the answer has already been calculated but hidden from me.

**Comment by graphicore** [comment]
Maybe log the N more with INFO?

**Comment by felipesanches** [comment]
hmmm... the INFO solution sounds interesting indeed!

**Comment by felipesanches** [comment]
I hope you like it :-)

![Screenshot from 2019-11-11 19-57-10](https://user-images.githubusercontent.com/213676/68627800-7cf54400-04bd-11ea-8a2d-ccdf9a917021.png)

**Comment by yanone** [comment]
Thank you. Keep it in the back of your head, though, that this is only a workaround and not a solution to the necessity to display different levels of verbosity to different people.

**Comment by graphicore** [comment]
@yanone what do you suggest instread?

**Comment by yanone** [comment]
A verbosity level switch at the command line like so many programs have them. With this amount of output, it almost screams for one.

**Comment by felipesanches** [comment]
We do already have a `--verbose` flag which is equivalent to `--log-level PASS`

The `--log-level` flag allows one to select the verbosity in one dimension: which kinds of check results one is interested in seeing.

We also have a similar flag for the verbosity within a check, meaning one can filter which kinds of log-messages one wants to see.

Yet another verbosity flag would surely sound confusing. We would need to completely rethink how we express verbosity at all.

And I think using an INFO message to show details is not a hack or workaround, but actually a reasonable thing to do. After all, that's what INFO messages are supposed to offer: more detailed info collected by the checking routines.

**Comment by graphicore** [comment]
I think the issue is still that we do print INFO logs of the check by default, because the default log level is INFO.

To remove INFO messages you can to do one of the following: 
```
# show results of WARN or higher and only logs of WARN or higher
fontbakery check-googlefonts  -c glyph_cov ~/Desktop/NotoSansMongolian-Regular.ttf -l WARN

# show  only results of INFO or higher and only logs of WARN or higher
fontbakery check-googlefonts  -c glyph_cov ~/Desktop/NotoSansMongolian-Regular.ttf -m WARN
```
As far as suggestions go, I have three:  
* just use fontbakery with `-m WARN`
*  `-m WARN` could be the default (it's equal to `-l / {loglevel}`  at the moment which itself defaults to INFO)
* or the full glyphs list should be logged at a lower log level, where only DEBUG would make sense, because neither PASS or SKIP are semantically a fit. We could output a hint into the FAIL messages with the shortened list, like: `FAIL: Missing required codepoints: 0x0022 (QUOTATION MARK), 0x0023 (NUMBER SIGN), 0x0024 (DOLLAR SIGN), 0x0025 (PERCENT SIGN) and 203 more. Use the "-m DEBUG" log level option to see the full list. [code: missing-codepoints]
`
As a reference, here's the relevant output of `fontbakery check-googlefonts  -h`:

```
  -v, --verbose         Shortcut for `-l PASS`.
  -l LOGLEVEL, --loglevel LOGLEVEL
                        Report checks with a result of this status or higher.
                        One of: DEBUG, PASS, SKIP, INFO, WARN, FAIL, ERROR.
                        (default: INFO)
  -m LOGLEVEL_MESSAGES, --loglevel-messages LOGLEVEL_MESSAGES
                        Report log messages of this status or higher.
                        Messages are all status lines within a check.
                        One of: DEBUG, PASS, SKIP, INFO, WARN, FAIL, ERROR.
                        (default: LOGLEVEL)
```

**Comment by graphicore** [comment]
Also possible: set the default log level to "WARN".

**Comment by felipesanches** [comment]
DEBUG does not make sense semantically for this use-case. INFO does.

**Comment by felipesanches** [comment]
In other words, DEBUG is for information on debugging fontbakery itself. INFO is for actual informative check-result messages (more detailed info than the basic info provided on the usual WARN/FAIL messages which are meant to be less verbose).

**Comment by yanone** [comment]
I'm typing on my phone on vacation. Just so much: you're mixing up log level and verbosity. I want to be able to choose both. In my case, I want to see warnings only, but in maximum verbosity. Printing additional information to my warning as info is such a mess. It's possible, but you said "rethink", so I suggest to clearly differentiate between the two different concepts.

**Comment by graphicore** [comment]
>  you're mixing up log level and verbosity.

No, you are separating it.

>  Printing additional information to my warning as info is such a mess.

I'm sorry that you feel that way, but the intention of having many different log entries with different log levels in one check output is to be able to do exactly that.
