### ISSUE TITLE
[macOS] ftxvalidator install path as of macOS Catalina / XCode 11.1

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/fontbakery#2691]
After an upgrade to macOS Catalina and XCode 11.1, the `ftxvalidator` executable was no longer found on my system PATH.  I attempted a new installation of the `Font_Tools_for_Xcode_11.dmg` installer that is distributed by Apple and this did not fix the issue.

Documentation embedded in the installer states the following:

>The command-line utilities are installed in /Library/Apple/usr/bin/. They presuppose some familiarity with using the Terminal application and the Unix shell. Older releases of the installer placed these utilities in /usr/bin or /usr/local/bin. These are not deleted by the installer. Make sure you have removed such copies (if necessary), or that in your $PATH environment variable starts with /Library/Apple/usr/bin/.

### Fix 1

Use the `Font_Tools_for_Xcode_11.dmg` installer distributed by Apple.  After the installation is complete, execute the following (this assumes that `/usr/local/bin` is defined on your system PATH):

```
$ cp /Library/Apple/usr/bin/ftxvalidator /usr/local/bin
$ ftxvalidator --version
```

### Fix 2

Use the `Font_Tools_for_Xcode_11.dmg` installer distributed by Apple.  Add `/Library/Apple/usr/bin/` to your system PATH definition.

**Comment by laerm0** [comment]
Oof, Catalina. I'm definitely not upgrading.
