### ISSUE TITLE
Reference to 'gftools fix-hinting'

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/fontbakery#2710]
When I get a fail for `🔥 FAIL: PPEM must be an integer on hinted fonts.`
The rationale suggests:
`This can be accomplished by using the 'gftools fix-hinting' command.`
But there's no such thing as a `gftools fix-hinting` command? Only `gftools fix-nonhinting`. Is that what it's supposed to refer to?

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/gftools/blob/master/bin/gftools-fix-hinting.py
