### ISSUE TITLE
Color scheme in Terminal

### ISSUE THREAD

**Issue by arialcrime** [googlefonts/fontbakery#2733]
## Observed behaviour

Not entirely sure if this is on purpose, but with the most recent fontbakery version a few of the text blocks got a light background, which looks odd in a dark terminal window.

<img width="1201" alt="Screen Shot 2020-01-16 at 13 10 20" src="https://user-images.githubusercontent.com/2954154/72529803-4c8ba680-386e-11ea-86a3-b392fe136077.png">

## Expected behaviour

Ideally the (background) color scheme is less intrusive.

**Comment by felipesanches** [comment]
The latest release v0.7.17 introduced color theme support. There are 3 themes: dark, light and no-colors. By default, we are using the light one on MacOS and the dark one everywhere else. Users can over-ride the default by using `--dark-theme` or `--light-theme`.

**Comment by graphicore** [comment]
Maybe it's time for a ~/.fontbakery user defaults file.
