### ISSUE TITLE
Seemingly conflicting checks – VF font dir must include static subdir, but warns against subdir

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/fontbakery#2737]
## Observed behaviour

If I PR a variable font with no statics, FontBakery tells me to add a subdirectory and include statics.

```
🔥 FAIL: A static fonts directory with at least two fonts must accompany variable fonts

    com.google.fonts/check/repo/vf_has_static_fonts

    Rationale

Variable font family directories kept in the google/fonts git repo must include
a static/ subdir containing static fonts.
These files are meant to be served for users that still lack support for
variable fonts in their web browsers.


    🔥 FAIL Please create a subdirectory called "static/" and include in it static font files. [code: missing]
```

When I follow that advice, I get a contradictory set of `WARN` messages:

```
>> com.google.fonts/check/metadata/undeclared_fonts
    Ensure METADATA.pb lists all font binaries.
    

      Rationale:                                                                
      The set of font binaries available must match exactly those declared on the METADATA.pb file.                                                     
                                                                                
      Also, to avoid confusion, we expect that font files are not placed on subdirectories.    

* WARN: The file "./static/Inter-Medium.ttf" is a font binary in a subdirectory.
Please keep all font files directly on the root directory side-by-side with its corresponding METADATA.pb file. [code: font-on-subdir]
    * WARN: The file "./static/Inter-Light.ttf" is a font binary in a subdirectory.
Please keep all font files directly on the root directory side-by-side with its corresponding METADATA.pb file. [code: font-on-subdir]
    * WARN: The file "./static/Inter-ExtraLightItalic.ttf" is a font binary in a subdirectory.

etc etc
```

## Expected behavior

As far as I'm aware, `METADATA.pb` should not list fonts in the `static/` subdirectory, but those fonts _should_ be there to support users who might sync the google/fonts repo to their local design environments.

If this is true, the behavior I expect is:

**If a variable font is at the top level of a directory, don't warn against binaries statics in subdirectories.**

## Resources and exact process needed to replicate

Relevant to: https://github.com/google/fonts/pull/1908

**Comment by felipesanches** [comment]
thanks for reporting this

**Comment by rsheeter** [comment]
In general there shouldn't be any statics, just a METADATA.pb plus the VFs. We generate instances during deployment based on the fallback positions defined in the google fonts axis registry (such as hundred-weights).

**Comment by laerm0** [comment]
Oh, interesting, thanks @rsheeter. I guess we can deprecate this check now, eh @felipesanches?

**Comment by felipesanches** [comment]
The conversation at #2738 convinces me that we should still keep the check for statics and so I will fix the behaviour of the other check so that it does not complain about a subdir if it's called "statics".
