### ISSUE TITLE
FontBakery not detecting static/ folder in PR

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/fontbakery#2738]
## Observed behaviour

At https://github.com/google/fonts/pull/1908#issuecomment-575748119, the gf-bot is including a fail that I believe is invalid. My changed files include a `static` folder with static fonts, but I am still getting this flagged:

```
🔥 FAIL: A static fonts directory with at least two fonts must accompany variable fonts

    com.google.fonts/check/repo/vf_has_static_fonts

--- Rationale ---

Variable font family directories kept in the google/fonts git repo must include
a static/ subdir containing static fonts.
These files are meant to be served for users that still lack support for
variable fonts in their web browsers.
```

Here's the specific commit:

https://github.com/google/fonts/commit/ba8c4ed7144c0425fb29b49ad84954ecb98468c4

Here's the folder:

![image](https://user-images.githubusercontent.com/45946693/72639101-de5ce780-3932-11ea-8109-1bc64f51f2c6.png)

## Expected behaviour

If there is a `static/` folder, it should accurately detect it. Unless I've made a spelling error that I'm just not seeing?

## Resources and exact process needed to replicate

This is occurring at https://github.com/google/fonts/pull/1908#issuecomment-575748119. My changed files include a `static` folder with static fonts, but I am still getting this issue.

**Comment by felipesanches** [comment]
This is not a fontbakery issue. It is a `gftools qa` one. Please post this directly to the google/fonts issue tracker (or perhaps the gftools one)
