### ISSUE TITLE
com.google.fonts/check/name/familyname failing on family name with camelcase

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/fontbakery#2741]
I am getting this fail from fontbakery because it looks like fontbakery made a family name with spaces by adding a space before every upper case letter but my name ID 1 is meant to be in camelcase:

> <summary>🔥 <b>FAIL:</b> Check name table: FONT_FAMILY_NAME entries.</summary>
> 
> * [com.google.fonts/check/name/familyname](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/familyname)
> <pre>--- Rationale ---
> 
> Checks that the family name infered from the font filename matches the string
> at nameID 1 (NAMEID_FONT_FAMILY_NAME) if it conforms to RIBBI and otherwise
> checks that nameID 1 is the family name + the style name.
> 
> 
> </pre>
> 
> * 🔥 **FAIL** Entry [FONT_FAMILY_NAME(1):WINDOWS(3)] on the "name" table: Expected "Georama X Cn" but got "GeoramaXCn". [code: mismatch]

These are the name tables: 
ID 1 FONT_FAMILY_NAME: BananasXCn
ID 2 FONT_SUBFAMILY_NAME: Regular
ID 4 FULL_FONT_NAME: BananasXCn Regular
ID 6 POSTSCRIPT_NAME: BananasExtraCondensed-Regular
ID 16 TYPOGRAPHIC_FAMILY_NAME: Bananas ExtraCondensed

And the filename is: BananasXCn-Regular.ttf

ID 1 and ID 4 are shortened in this way across the family to meet the 27 character maximum elsewhere in the family. Wouldn't this issue come up anytime there's a font family name which has camelcase?

**Comment by felipesanches** [comment]
In general we currently avoid camel case family names. We might add special cases for those, but that would require hard-coding such exceptions in fontbakery itself, which is probably a very bad solution.

Also, I think "XCn" to represent "Extra Condensed" is extremely non-intuitive for the font users.

**Comment by felipesanches** [comment]
This issue seems related to #2448, so I suggest we close it now and weigh in that other issue.
