### ISSUE TITLE
Colors on Mac Terminal

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#2752]
Colors have recently changed which looks a bit broken on my Mac. I guess you've made them white to match the default Mac terminal theme?

<img width="842" alt="Screenshot 2020-02-05 at 16 52 30" src="https://user-images.githubusercontent.com/7525512/73863482-0fe11880-4838-11ea-97dd-23b46fe51804.png">

I'm using: 
OS X 10.15.1
Terminal v2.10 (433)
My Terminal Theme is Pro

**Comment by felipesanches** [comment]
yes. Default fontbakery color theme is light on Mac and dark everywhere else. This is meant to fit the most common usage scenarios.

You can overide this with `--dark-theme`

**Comment by felipesanches** [comment]
See also:
* https://github.com/googlefonts/fontbakery/issues/2733
* https://github.com/googlefonts/fontbakery/issues/2031
* https://github.com/googlefonts/fontbakery/issues/2734

**Comment by m4rc1e** [comment]
Thanks

**Comment by m4rc1e** [comment]
Just seen pytest can handle different themes nicely.

<img width="1202" alt="Screenshot 2020-02-05 at 17 08 25" src="https://user-images.githubusercontent.com/7525512/73864845-36a04e80-483a-11ea-9ab0-ec715428ddee.png">

Perhaps this is something we can think about or is it a pita?

**Comment by felipesanches** [comment]
huh! Sounds interesting! We should take a look at what trick is used in there to acchieve it. We could do something similar. I'll lookup pytest sources later to try to figure that out. Thanks for the tip!
