### ISSUE TITLE
GF_latin_core list does not match latin_unique-glyphs.nam

### ISSUE THREAD

**Issue by mattlag** [googlefonts/fontbakery#2755]
## Observed behaviour

Submitting a font to Google Fonts, it passes the Font Bakery test (has all the glyphs in const `GF_latin_core` from constants.py) but does not include some glyphs mentioned in [latin_unique-glyphs.nam](https://github.com/googlefonts/gftools/blob/master/Lib/gftools/encodings/latin_unique-glyphs.nam) - which seems to be the required list for submitting to Google Fonts

## Expected behaviour

If latin_unique-glyphs.nam is the source of truth, `GF_latin_core` list should match.  Based on a very quick eyeball comparison of the two lists, there are at least three missing glyphs from `GF_latin_core`

0x2122  ™ TRADE MARK SIGN

0x2191  ↑ UPWARDS ARROW

0x2193  ↓ DOWNWARDS ARROW

**Comment by mattlag** [comment]
I did a full comparison of the two lists - it seems as if GF_latin_core is missing the following glyphs.  latin_unique-glyphs.nam is not missing any glyphs from GF_latin_core.
```
0x02BB : ʻ MODIFIER LETTER TURNED COMMA exists in latin_unique-glyphs.nam but not GF_latin_core 
0x02BC : ʼ MODIFIER LETTER APOSTROPHE exists in latin_unique-glyphs.nam but not GF_latin_core 
0x2002 :   EN SPACE exists in latin_unique-glyphs.nam but not GF_latin_core 
0x200B :   ZERO WIDTH SPACE exists in latin_unique-glyphs.nam but not GF_latin_core 
0x2009 :   THIN SPACE exists in latin_unique-glyphs.nam but not GF_latin_core 
0x2032 : ′ PRIME exists in latin_unique-glyphs.nam but not GF_latin_core 
0x2033 : ″ DOUBLE PRIME exists in latin_unique-glyphs.nam but not GF_latin_core 
0x2122 : ™ TRADE MARK SIGN exists in latin_unique-glyphs.nam but not GF_latin_core 
0x2191 : ↑ UPWARDS ARROW exists in latin_unique-glyphs.nam but not GF_latin_core 
0x2193 : ↓ DOWNWARDS ARROW exists in latin_unique-glyphs.nam but not GF_latin_core 
0xFEFF :   ZERO WIDTH NO-BREAK SPACE (BOM) exists in latin_unique-glyphs.nam but not GF_latin_core 
0xFFFD : � REPLACEMENT CHARACTER exists in latin_unique-glyphs.nam but not GF_latin_core
```

**Comment by felipesanches** [comment]
hi, @mattlag,

Sorry about that. If you are a type designer working on fonts for the Google Fonts collection, you should look at the `GF Glyph Sets` folder, instead!

The `GF Glyph Sets` directory is here:
https://github.com/googlefonts/gftools/tree/master/Lib/gftools/encodings/GF%20Glyph%20Sets

**Comment by davelab6** [comment]
Matt, great to hear from you and thanks for pointing this out :)

Those should be added to core; I expect we'll do a new 2020 set of glyphsets for type designers

**Comment by felipesanches** [comment]
If I understood it correctly, I think I can help by pushing a commit to gftools include these glyph to `GF Glyph Sets/GF-latin-core_unique-glyphs.nam` and then update FontBakery to also require these glyphs.

Is that correct, @davelab6?

**Comment by felipesanches** [comment]
Oh! And I gotta ask you whether all these glyphs mentioned by @mattlag at https://github.com/googlefonts/fontbakery/issues/2755#issuecomment-583975444 should be added to `GF Glyph Sets/GF-latin-core_unique-glyphs.nam`. Can you confirm that, @davelab6?

**Comment by mattlag** [comment]
I guess related to this is the list of glyphs mentioned in the Contributing document:

https://github.com/google/fonts/blob/master/CONTRIBUTING.md

Which is where I got the `latin_unique-glyphs.nam` list.  I was running the fontbakery test, and assuming everything matched up, so @felipesanches if the real list is `GF Glyph Sets/GF-latin-core_unique-glyphs.nam`, that's totally fine.  It would be good whatever the 'real' list is, it was reflected in both the Google Fonts Contributing document and the fontbakery test for Google Fonts.

**Comment by vv-monsalve** [comment]
I've compared the two lists plus the GF Latin Core filter list. This is a [spreadsheet](https://docs.google.com/spreadsheets/d/1bs6NBtEup-M3bQiiEfn68oKhB1mQYyjBVeOX96otqgU/edit?usp=sharing) with it, I hope it can be helpful to unify or update them.

**Comment by vv-monsalve** [comment]
After a double-check, I've found some of the "missing glyphs" on the Latin Core are already part of the Pro or Plus encodings. 

Current state:

**latin_unique-glyphs.nam**
```
0xFEFF :   ZERO WIDTH NO-BREAK SPACE (BOM) 
0xFFFD : � REPLACEMENT CHARACTER
0x2002 :   EN SPACE
0x2191 : ↑ UPWARDS ARROW
0x2193 : ↓ DOWNWARDS ARROW  
```
**GF-latin-pro_unique-glyphs.nam**
```
0x02BB : ʻ MODIFIER LETTER TURNED COMMA
0x200B :   ZERO WIDTH SPACE
0x2009 :   THIN SPACE
0x2032 : ′ PRIME
0x2033 : ″ DOUBLE PRIME
```
**GF-latin-plus_unique-glyphs.nam**
```
0x02BC : ʼ MODIFIER LETTER APOSTROPHE
0x2122 : ™ TRADE MARK SIGN
0x2032 : ′ PRIME (repeated on this encoding)
0x2033 : ″ DOUBLE PRIME (repeated on this encoding)
```

IMO this could be a distribution given the relevance and coordination of the glyphs with each encoding:

**GF-latin-core**
```
0x2002 :   EN SPACE
0x2122 : ™ TRADE MARK SIGN
0x2191 : ↑ UPWARDS ARROW
0x2193 : ↓ DOWNWARDS ARROW 
```
**GF-latin-pro**
```
0x200B :   ZERO WIDTH SPACE
0x2009 :   THIN SPACE
0x2032 : ′ PRIME
0x2033 : ″ DOUBLE PRIME

```
**GF-latin-plus**
```
0x02BB : ʻ MODIFIER LETTER TURNED COMMA
0x02BC : ʼ MODIFIER LETTER APOSTROPHE
0xFEFF :   ZERO WIDTH NO-BREAK SPACE (BOM)
0xFFFD : � REPLACEMENT CHARACTER

```
Although I don't know id @m4rc1e has a specific reason for 0xFEFF and 0xFFFD to be on Latin Core

**Comment by vv-monsalve** [comment]
Maybe we should also delete U+02DA spacing modifier ring glyph, as it was discussed here [https://github.com/TiroTypeworks/Castoro/issues/5#issuecomment-676810052](https://github.com/TiroTypeworks/Castoro/issues/5#issuecomment-676810052)

**Comment by felipesanches** [comment]
the glyphset described on fontbakery constants module is currently identical to the "GF Glyph Sets 2016" one documented at the gftools repo.
