### ISSUE TITLE
Check if OFL.txt contains copyright string

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#2764]
An OFL.txt file's first line should be the font copyright e.g "Copyright 2019 The Montserrat Project Authors (https //github.com/julietaula/montserrat)"

We just pushed https://github.com/google/fonts/pull/2323 and it didn't contain this line. I don't think we have an FB check to catch this.

cc @bghryct

**Comment by m4rc1e** [comment]
This issue could be bundled with #2688

**Comment by felipesanches** [comment]
thanks, @m4rc1e!

**Comment by m4rc1e** [comment]
Thanks to @bghryct for finding these edge cases.

**Comment by bghryct** [comment]
@m4rc1e that's a polite way of saying i did an oops

**Comment by m4rc1e** [comment]
Nah, the checks should catch it.

**Comment by felipesanches** [comment]
And they will do it! Very soon ;-)

**Comment by felipesanches** [comment]
The `google/fonts` repo has a poor record on these criteria... lets hope we can improve it by having this check in place ;-)

![Screenshot from 2020-02-22 02-41-56](https://user-images.githubusercontent.com/213676/75087297-3f24a480-551d-11ea-9da6-e62ec37a21c9.png)
