### ISSUE TITLE
FATAL ERROR: The rationale metadata on 'com.google.fonts/check/metadata/valid_copyright' must be indented by 4 spaces!

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/fontbakery#2772]
## Observed behaviour

When I run `fontbakery check-googlefonts WorkSans-Italic\[wght\].ttf --ghmarkdown WorkSans-Italic\[wght\].md` I get this error:

```
FATAL ERROR: The rationale metadata on 'com.google.fonts/check/metadata/valid_copyright' must be indented by 4 spaces!
```

And no .md output.

**Comment by felipesanches** [comment]
Thanks, @weiweihuanghuang!

**Comment by felipesanches** [comment]
New emergency release addressing this problem:
https://pypi.org/project/fontbakery/0.7.20/
