### ISSUE TITLE
Line-breaks in Name Table (move this check to googlefonts profile)

### ISSUE THREAD

**Issue by ClintGoss** [googlefonts/fontbakery#2778]
## Observed behaviour

Font Bakery complains about name table entries with line-breaks. Could you explain, or point me to, the rationale for this?

## Expected behaviour

Line-breaks in the license description field - for example the text of the OFL - seem (to me) to be significant. The OFL without line breaks appears (to me) rather ugly. And might stripping line-breaks possibly change the semantics of the license?

**Comment by felipesanches** [comment]
Could you please tell us the check-id of the specific check that is giving you this WARN/FAIL message?

I suppose this must be in the `googlefonts` profile and it means we want the license description field to be very short and simple, instead of the full license text

**Comment by felipesanches** [comment]
hmmm... interesting!
This is check-id `com.google.fonts/check/name/line_breaks` on the `universal` profile, indeed!

I think we should move this into the `googlefonts` profile as I see how this is not necessarily an industry-wide well accepted good-practice, but instead a requirement we decided to have for the Google Fonts collection. Thanks for reporting this ;-)

**Comment by felipesanches** [comment]
oh! It is even worse than that! It is currently on the `opentype` profile, which is certainly a wrong place for it. Excuse us for that mistake! This is definitely moving to the `googlefonts` profile right now! :-|

**Comment by felipesanches** [comment]
Done. This change will be included in the upcoming release, **FontBakery v0.7.21** which should be published tomorrow during the day.

**Comment by ClintGoss** [comment]
Thanks **so much** for the _shockingly_ fast action on this ...

**Comment by felipesanches** [comment]
:-D

**Comment by felipesanches** [comment]
@ClintGoss, here it is: https://pypi.org/project/fontbakery/0.7.21/

update with `pip install --upgrade fontbakery`

Be sure to send further issue reports if you see anything wrong or stuff that could be improved.
While updating the cache of vendor-IDs I saw yours, `goss` and checked out the website at https://www.goss.com/

Glad to see your fine work. You may want to join our FontBakery chat channel at https://gitter.im/fontbakery/Lobby

Happy Hacking!

**Comment by schriftgestalt** [comment]
A test like this could be useful for all the "name" entries (ID 1, 2, 4, 6, 16, 17, 18 ...)? But then check for more control characters.

(But maybe there is one already? I only found 'com.google.fonts/check/name/trailing_spaces')

**Comment by felipesanches** [comment]
@schriftgestalt The line_breaks one checks every name entry

**Comment by tphinney** [comment]
I am still left wondering WHY Google thinks a line break would be unacceptable in the description field, even in their own fonts.

**Comment by felipesanches** [comment]
> I am still left wondering WHY Google thinks a line break would be unacceptable in the description field, even in their own fonts.

@tphinney, this is described in the documentation for the check at
https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/line_breaks
![Screenshot from 2020-03-08 00-06-01](https://user-images.githubusercontent.com/213676/76155839-a53e2980-60d0-11ea-97eb-8012c57d57a9.png)

**Comment by schriftgestalt** [comment]
> @schriftgestalt The line_breaks one checks every name entry

I know. What I meant was to make a new check that only checks those I mentioned.

**Comment by felipesanches** [comment]
please open a new issue describing the proposed new check in detail

**Comment by m4rc1e** [comment]
I still don't see the point of this check.

There's nothing wrong with having line breaks in name records. I agree there shouldn't be line breaks in nameIDs which are related to familyName and subFamilyName though.

After reading the check description, I reckon this check was implemented because too many fonts included the full license text? if this was the case, I'd prefer us to just fail name records which include license text or are too long. Again failing by length may be too arbitrary.
