### ISSUE TITLE
ftxvalidator install instructions steer towards Apple Font Tools v9. Should it (can it?) be 11?

### ISSUE THREAD

**Issue by tphinney** [googlefonts/fontbakery#2784]
Font Bakery can call Apple’s ftxvalidator, if present. This can be installed from Apple’s "Font Tools for Xcode."

## Observed behaviour

Current Font Bakery instructions at https://font-bakery.readthedocs.io/en/latest/user/installation/install-macos.html say to install "Font_Tools_for_Xcode_9.dmg"

However, the latest version seen at https://developer.apple.com/download/more/?=font is "Font Tools for Xcode 11", released Oct 1, 2019.

## Expected behaviour

I would love to know whether:
- Font Bakery specifically requires the the Xcode 9 version
- Font Bakery works fine with the Xcode 11 version
- the answer is unknown; FB is known to be good with 9, but 11 is uncertain

I would like to see it clarified in the docs.

**Comment by felipesanches** [comment]
I suspect that version 9 was the only one available when this instruction was placed in the documentation. I do not remeber any kind of comment about a specific version requirement. So I really think it means "9 or later"

As far as I know, there's no reason to believe that 11 is worse than 9, unless we have explicit evidence to conclude that.

**Comment by felipesanches** [comment]
> "Should it (can it?) be 11?"

yes, it can, unless stated otherwise.

I will update the documentation now.

**Comment by chrissimpkins** [comment]
I am using XCode 11 version in fontbakery without issues.
