### ISSUE TITLE
whitespace_ink check for ZWNBSP conflicts with SIL NRSI Recommendation

### ISSUE THREAD

**Issue by ClintGoss** [googlefonts/fontbakery#2785]
## Observed behaviour

Running v0.7.21 with check-universal throws FAIL on com.google.fonts/check/whitespace_ink for the glyph named "zerowidthnobreakspace". 

## Expected behaviour

This is mapped to U+FEFF - the classic BOM character. There is a SIL NRSI _Recommended characters for Non-Roman fonts_ article at https://scriptsource.org/entry/gg5wm9hhd3 which opines:

"Arabic Presentation Forms-B | FEFF | BYTE ORDER MARK, **making this visible might be helpful**"

... so I made it visible (Note 4 on this article has more detail on my handling of this code point).

I actually do no know the downsides for font users of following the SIL recommendation and setting U+FEFF to a visible glyph ... there seems to be no clear opinion / direction on this issue ...

**It would be great to have a specific use-case that refutes the SIL recommendation to use a visible glyph for U+FEFF.**

## Resources and exact process needed to replicate

fontbakery check-universal (font with visible glyph mapped to U+FEFF)

**Comment by ClintGoss** [comment]
Looking at the documentation, I now realize that check-universal includes the googlefonts checks. Didn't realize that. I was thinking that, when check-universal said "_best practices agreed upon on the type design community_" it meant the intersection of checks, not a union.

So I should probably be using check-opentype (which is not in the USAGE.html documentation? I just guessed and it work) ... and check-opentype does not complain about whitespace_ink, so I guess this is a non-issue ... Sorry 'bout this!

... but I am still unsure about whether to follow the SIL recommendation to use a visible glyph for U+FEFF.

**Comment by felipesanches** [comment]
I've split out the universal profile problem into a new issue so we can tackle the problems separately. Thanks for reporting both problems.

**Comment by felipesanches** [comment]
I've double-checked and indeed `whitespace_ink` is currently placed in the `universal` profile, so it does indeed is meant to be a "best practice agreed upon on the type design community" even though it conflicts with the SIL recommendation.

Should we then remove `zerowidthnobreakspace` from this `universal` check and create a vendor-specific check on the `googlefonts` profile to that specific case?

**Comment by ClintGoss** [comment]
> Should we then remove zerowidthnobreakspace from this universal check and create a vendor-specific check on the googlefonts profile to that specific case?

I now think this should not be done, in light of Lorna Evans' recent response to my query on Scriptsource. Quoting from https://scriptsource.org/cms/scripts/page.php?item_id=entry_detail&uid=gg5wm9hhd3#comment5

"Putting a glyph into what is intended to be an invisible character would likely cause problems for when the character is really needed. For documentation purposes I can see your point and we (SIL) have tried making a font where we have a feature called "Show invisibles" and then there is an alternate glyph that displays something like what you are suggesting. However, that feature has not worked well and we've begun to remove that feature from at least some of our fonts."

**Comment by felipesanches** [comment]
ok, great. So that means SIL Recommendation is not realy conflicting with our current implementation of this check? If so, I'll close this issue. Let me know what you think, @ClintGoss

**Comment by ClintGoss** [comment]
Yes, I believe this issue should be closed ... I do assume that the (essential) retraction by Lorna Evans on the SIL recommendation for a visible glyph for the normally non-visible ZWNBSP code point applies to all such non-visible code points.

I will be removing such visible glyphs from my own fonts, and they should now pass these fontbakery checks.

**Comment by felipesanches** [comment]
great! :-D
