### ISSUE TITLE
[com.google.fonts/check/usweightclass] Fail with weightclass 100 in variable font

### ISSUE THREAD

**Issue by arialcrime** [googlefonts/fontbakery#2788]
## Observed behaviour

The (wip) [spec](https://gist.github.com/m4rc1e/8f4c4498519e8a36cd54e16a004275cb#supported-styles) recommends setting the OS2 weightclass for Thin to 100, but Google Fonts’ [usweightclass](https://github.com/googlefonts/fontbakery/blob/d5552379c669cc65383b656234c4cb9922193aad/Lib/fontbakery/profiles/googlefonts.py#L827) check returns a FAIL if I follow the spec.

The error message reads:
`FAIL: OS/2 usWeightClass expected value for '9pt Thin' is 250 but this font has 100.`

## Expected behaviour

Not sure. Either no fail in the check, or a clearer explanation what the value can/should be.

**Comment by m4rc1e** [comment]
Yep, we need to fix this.

For CFF we apparently want 250, for TT 200.

**Comment by tphinney** [comment]
> For CFF we apparently want 250, for TT 200.

I understand why 250 is needed for CFF, but I can’t imagine why 200 would be a breakpoint. Did you mean to say 100—the normally correct value for Thin? Or is there some way in which TT behavior is particularly surprising (to me, anyway)?

**Comment by m4rc1e** [comment]
Apologies, For TT we want 100 for Thin and 200 for ExtraLight.

**Comment by m4rc1e** [comment]
I'm writing a wip [spec/docs](https://gist.github.com/m4rc1e/8f4c4498519e8a36cd54e16a004275cb#supported-styles) atm that has this info. Hopefully we can just use this as a single source of truth instead of github issues.

**Comment by thlinard** [comment]
[Issue 1706](https://github.com/google/fonts/issues/1706) ("Establish mapping for usWidthClass to css font-stretch") is still open.

**Comment by m4rc1e** [comment]
It's wip, https://gist.github.com/m4rc1e/8f4c4498519e8a36cd54e16a004275cb#axes

**Comment by m4rc1e** [comment]
We must prioritise fixing this issue. Every vendor complains about it, https://github.com/xotypeco/big_shoulders/issues/9#issuecomment-623573511

**Comment by m4rc1e** [comment]
Working on this today.

**Comment by felipesanches** [comment]
Thanks, @m4rc1e
