### ISSUE TITLE
[com.google.fonts/check/repo/vf_has_static_fonts] does not seem to reflect current practice.

### ISSUE THREAD

**Issue by kontur** [googlefonts/fontbakery#2792]
## Observed behaviour

None of the "…vfalpha/…vfbeta" fonts in [the Google fonts repo](https://github.com/google/fonts) seem to have a `static` folder.

## Expected behaviour

Not quite sure what to expect, but I am wondering what this check does if not force me to have a certain folder structure that will not be used anyway.

**Comment by m4rc1e** [comment]
Those betas were created years ago when we didn't have as hardcore requirements :-)

Please include a static dir for the time being. We are debating whether to get rid of this subfolder in the future.

**Comment by felipesanches** [comment]
thanks, Marc

**Comment by thlinard** [comment]
I have submitted a [PR 2260](https://github.com/google/fonts/pull/2260) to clean some folders, but no one commented on it…

The PR proposed to restore the static versions of two VF (Jura and Vollkorn), and to delete some VF Beta which now exist in final version.
