### ISSUE TITLE
ftxvalidator fails to run with dyld: warning LC_RPATH 

### ISSUE THREAD

**Issue by tphinney** [googlefonts/fontbakery#2801]
Attempting to run freshly installed ftxvalidator. I may have gotten this same error at install time.

## Observed behaviour

dyld: warning, LC_RPATH @executable_path/../Frameworks in /Library/Frameworks/FontToolbox.framework/Versions/A/FontToolbox being ignored in restricted program because of @executable_path

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>kATSFontTestResultKey</key>
	<array>
		<string>kATSFontTestSeverityMinorError</string>
		<string>kATSFontTestSeverityInformation</string>
		<string>kATSFontTestSeverityTechnicalError</string>
		<string>kATSFontTestSeverityMajorError</string>
	</array>
</dict>
</plist>

## Expected behaviour

Some kind of actual output.

## Resources and exact process needed to replicate

This appears to be specific to my install, not something easily replicated elsewhere.

**Comment by tphinney** [comment]
I can of course just use Font Book, but that isn’t as easily automated, and if I get an error I won’t get as much info. As we are currently error-free with Font Book this is not urgent, but nice to sort out.

**Comment by HinTak** [comment]
Something similar to https://github.com/HinTak/mono-modification/blob/macosx-10.13/mono-codesign-fix.py might be able to "adjust" the mac os x binary for recent mac os x.

**Comment by tphinney** [comment]
Thanks for the feedback! I'm currently on the latest/last Mojave (10.14.6). Probably going to move to Catalina soon.

So, the workaround is just to run ftxvalidator manually from outside of fontbakery, then?

**Comment by HinTak** [comment]
what version of the ftxvalidator are you using? I asked because apple re-signed all their past versions in October (obvious for stricter upcoming security), with the exception of the antique 8+ years old version called beta 4. Most of the install instructions on the web seem to be for that version, unfortunately.
