### ISSUE TITLE
Contributing pshinting_impact check / psautohint_stats condition

### ISSUE THREAD

**Issue by kontur** [googlefonts/fontbakery#2802]
I liked the output of the [hinting impact](https://github.com/googlefonts/fontbakery/blob/5a845aab4bb3edc0ad596f9cd201a7c88f3b63ad/Lib/fontbakery/profiles/googlefonts.py#L1145) check, so I wrote a similar condition and check for _psautohinted_ `cff` fonts.

Is there any use to include this in the public checks of the repo, and if so, where would I add it in a PR?

**Comment by felipesanches** [comment]
I think it may be good to extend the existing check to support CFF hints as well, instead of adding a new one.
