### ISSUE TITLE
[com.google.fonts/check/varfont_instance_names] Add ExtraBlack 1000 weight support

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#2803]
The [Cairo PR](https://github.com/google/fonts/pull/2380) needed a ExtraBlack 1000 weight added, both Dave and Marc approved this, and it looks like it has been added to the [wip spec](https://gist.github.com/m4rc1e/8f4c4498519e8a36cd54e16a004275cb).

In the [Cairo PR](https://github.com/google/fonts/pull/2380), the latest gf-bot report using Fontbakery version: 0.7.21 gives a fail for the check `com.google.fonts/check/varfont_instance_names`:
```
🔥 FAIL: Check variable font instances have correct names
com.google.fonts/check/varfont_instance_names

🔥 FAIL Instance name "ExtraBlack" is incorrect. It should be "Black" [code: bad-name]

🔥 FAIL Check has either failed or produced a warning. See our wip spec for further info https://gist.github.com/m4rc1e/8f4c4498519e8a36cd54e16a004275cb [code: bad-instance-names]
```
It seems like this check needs to be updated to support a ExtraBlack 1000 weight.

**Comment by felipesanches** [comment]
I 'm working on this one, thanks for reporting, @eliheuer

**Comment by eliheuer** [comment]
Thanks! If you haven't seen it yet, https://github.com/googlefonts/fontbakery/issues/2804 is a closely related issue.

**Comment by felipesanches** [comment]
yeah!

**Comment by m4rc1e** [comment]
Thanks Felipe!
