### ISSUE TITLE
It is challenging to find the list of checks/tests in the docs

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/fontbakery#2814]
## Observed behaviour

I have been chatting with a couple of font designers/developers about FontBakery recently, and I went to find where in the docs the current checks were listed. I eventually found the list of profiles:

https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/index.html

## Expected behaviour

It's probably a fairly common question for people researching the project for the first time:

> What does this test for?

So, I would expect a link to the full set of tests available to be highlighted more prominently on the front page of the docs. 

Also, maybe there could be a more obvious name to get there than "profiles"? That title requires some familiarity with how FontBakery is set up to even search for. Possibly, the top-level navigation could be something like "Tests" or "Checks" or possible "Test Profiles"? Not sure what the best answer is, but if we can think of what a newcomer might be looking for, it would probably be helpful.

**Comment by felipesanches** [comment]
The README on this git repo has this:
`"For a quick overview, check out the list of checks currently offered."`

with a link to https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/index.html

Maybe we should add the same sentence to the beginning of the documentation homepage at https://font-bakery.readthedocs.io/en/latest/
