### ISSUE TITLE
Superfamily check fails

### ISSUE THREAD

**Issue by kontur** [googlefonts/fontbakery#2818]
## Observed behaviour

In a directory with files like:

```
fonts/
fonts/Family/*.ttf
fonts/FamilySC/*.ttf
```

Running `fontbakery check-googlefonts fonts/Family/*` fails with:

```
    * ERROR: Failed with IndexError: list index out of range
           File "/Users/johannes/.pyenv/versions/3.7.6/envs/signika/lib/python3.7/site-packages/fontbakery/checkrunner.py", line 339, in _exec_check
             result = check(**args)  # Might raise.
           File "/Users/johannes/.pyenv/versions/3.7.6/envs/signika/lib/python3.7/site-packages/fontbakery/callable.py", line 99, in __call__
             return self.__wrapped__(*args, **kwds)
           File "/Users/johannes/.pyenv/versions/3.7.6/envs/signika/lib/python3.7/site-packages/fontbakery/profiles/universal.py", line 790, in com_google_fonts_check_superfamily_list
             Message("family-path", os.path.split(family[0])[0])


    Result: ERROR
```

## Expected behaviour

I had a look at the superfamily condition, but I don't understand where or what are the `sibling_directories` being passed to the condition and why they are failing. I don't know what the `superfamily/list` check _should_ output, but I guess in my case it would be `Family` and `FamilySC` (folder names?)?

P.S.: For debugging, how do I a) easily run only a specific test, so I can only run the one that I want to debug, and b) print or log something so it will be output when running the CLI checks? I tried with raising Exceptions but I would want to non-intrusively print debug statements to see what is going on?

**Comment by felipesanches** [comment]
works for me... I wonder what may be different in your setup

![Screenshot from 2020-04-09 11-46-34](https://user-images.githubusercontent.com/213676/78907993-d86d3300-7a57-11ea-9907-1b877bd71f7a.png)

**Comment by felipesanches** [comment]
@kontur, are you running this against files from a public git repo? If so, let me know which one (and which branch) so that I can try to replicate the bug here

**Comment by kontur** [comment]
Hm. I can't reproduce this. Not sure if that is a good thing or a bad thing 😄 
I'll close and reopen if I figure out why I was stuck on that failing error message for an hour but cannot get it to fail now. I wonder if this has something to do with nested folders, or folders that have no files; not sure.
Thanks for the `-c` hint 👍

**Comment by felipesanches** [comment]
:-D
