### ISSUE TITLE
Tell users what check classes mean

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2823]
## Observed behaviour

Similar to https://github.com/googlefonts/fontbakery-dashboard/issues/170 we need to tell users what the check statuses mean as they don't know, in the CLI as well as the web UI.

**Comment by felipesanches** [comment]
![Screenshot from 2020-04-16 03-56-42](https://user-images.githubusercontent.com/213676/79424304-510f4a80-7f96-11ea-8a8d-4e8261f911aa.png)
