### ISSUE TITLE
VF unitsPerEm check is too fussy

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2827]
## Observed behaviour

https://github.com/vv-monsalve/Varta/issues/5 says

> Even though unitsPerEm (2048) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations. `[code: legacy-value]`

## Expected behaviour

That message makes no sense, as reducing unitsPerEm from 2048 to 2000, will not avoid excessive rounding of coordinates on interpolations.

If the UPM is above 2000, we don't need to warn.

**Comment by davelab6** [comment]
https://github.com/google/fonts/issues/2426 reported an edge case issue with the latest check, so I think it can be improved further.

2000 is a minimum for VF because lower than that creates less smooth interpolation; and larger than 2048 causes a filesize increase.

Perhaps the check result should be a WARN rather than a FAIL for values between 2000 to 4096.

**Comment by felipesanches** [comment]
thanks, @davelab6 
I'll address this now

**Comment by felipesanches** [comment]
The code-test works like a sort of spec of expected check results and summarizes the behaviour we enforce:
![Screenshot from 2020-04-22 19-05-41](https://user-images.githubusercontent.com/213676/80038665-805d1480-84cc-11ea-8b09-8a3a810199c5.png)
