### ISSUE TITLE
check-notofonts CLI option not available in v0.7.4?

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/fontbakery#2830]
## Observed behavior

The FontBakery docs ([USAGE](https://font-bakery.readthedocs.io/en/stable/user/USAGE.html)) list `check-notofonts` as a possible subcommand.

However, I cannot find or use the command. Maybe I am doing something incorrectly?

```bash
▶ fontbakery --list-subcommands
build-contributors check-adobefonts check-fontval check-googlefonts check-opentype check-profile check-ufo-sources check-universal generate-glyphdata

▶ fontbakery check-notofonts fonts/NotoSansNushu-Regular.ttf
usage: fontbakery [-h] [--list-subcommands] [--version]
                  [{build-contributors,check-adobefonts,check-fontval,check-googlefonts,check-opentype,check-profile,check-ufo-sources,check-universal,generate-glyphdata}]
fontbakery: error: argument subcommand: invalid choice: 'check-notofonts' (choose from 'build-contributors', 'check-adobefonts', 'check-fontval', 'check-googlefonts', 'check-opentype', 'check-profile', 'check-ufo-sources', 'check-universal', 'generate-glyphdata')

▶ fontbakery --version
0.7.4
```

I do have the file `venv/lib/python3.7/site-packages/fontbakery/commands/check_notofonts.py` in the venv I'm working in, but for some reason, this isn't working. I’m not quite sure why it might be failing, but I'm guessing it's just a syntax error or missing file or something?

Calling that file does work as expected, cueing the Noto checks:

```bash
▶ python venv/lib/python3.7/site-packages/fontbakery/commands/check_notofonts.py fonts/NotoSansNushu-Regular.ttf
```

## Expected behavior

I am trying to run fontbakery checks on a Noto font ([Noto Sans Nushü](https://github.com/LisaHuang2017/noto-sans-nushu)), and expecting the `check-notofonts` subcommand to trigger a series of checks.

**Comment by felipesanches** [comment]
Please update your fontbakery installation. If you are using 0.7.4, then it means you are using a 18 releases old program, as we're currently at 0.7.22 :-)

  > pip install fontbakery --upgrade

Then let me know if you can run the `check-notofonts` command.

**Comment by felipesanches** [comment]
please reopen the issue if you still can't run the command after upgrading
