### ISSUE TITLE
Can't find font family on Google Fonts API if family name contains multiple words, e.g. Libre Caslon Text

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/fontbakery#2848]
## Observed behaviour

At https://github.com/google/fonts/pull/2432, one of the `WARN`s is 

> WARN: METADATA.pb: Fontfamily is listed on Google Fonts API?

However, Libre Caslon Text _is_ listed on the API.

I believe this issue may come from the faulty assumption that family names are a single word. The check that throws this warn ultimately depends on proper splitting in the following function:

https://github.com/googlefonts/fontbakery/blob/1f894dcb95b143242fc59c382541c3bb9516e386/Lib/fontbakery/profiles/googlefonts_conditions.py#L325-L334

https://github.com/googlefonts/fontbakery/blob/1f894dcb95b143242fc59c382541c3bb9516e386/Lib/fontbakery/profiles/googlefonts_conditions.py#L260-L267

If I'm following correctly, for `LibreCaslonText[wght].ttf`, it:
- gets the string before `.ttf`
- splits at `[`
- ends up as ["LibreCaslonText"]
- (unsuccessfully) tries to replace `" "` with `"+"`
- searches for `http://fonts.googleapis.com/css?family=LibreCaslonText` when it should actually search for `http://fonts.googleapis.com/css?family=Libre+Caslon+Text`

## Expected behaviour

We need to find a reliable way to search for the correct CSS URL, e.g. `http://fonts.googleapis.com/css?family=Libre+Caslon+Text`. I'm not sure what approach would be best between all families.

Maybe we should seek out camel-casing, and split the family name where there are capital letters? I'm not quite sure what spillover effects that might have, or what the best approach might be.

**Comment by felipesanches** [comment]
oh! Yeah, I'd split camel-cased names. But I agree we might have some problems with that, as you pointed out...

**Comment by felipesanches** [comment]
maybe the check should query both just to be sure ;-) That would keep us safe

**Comment by felipesanches** [comment]
I started by updating the code-test for this check to include examples of multiple-word familynames both camel-cased or space-separated.

![Screenshot from 2020-04-22 19-43-17](https://user-images.githubusercontent.com/213676/80041033-bf419900-84d1-11ea-9d6e-3ae65a3eee91.png)


This will enforce the expected check behaviour. And with the current implementation it will not pass on Travis. Next step is to implement the actual change in the check code.

**Comment by felipesanches** [comment]
well... it passed on Travis and now I figured out why! Because the code-test is incomplete. It completely bypasses calling the `familyname` condition, instead directly feeding a space-separated name.

I will improve the code-test until it fails on Travis.

**Comment by felipesanches** [comment]
Great!

Now that the code-test properly detects the problem I can move on to make the implementation pass the test-suite :-)

![Screenshot from 2020-04-22 20-56-00](https://user-images.githubusercontent.com/213676/80044726-c79ed180-84db-11ea-8558-fe16c3d73e15.png)
https://travis-ci.org/github/googlefonts/fontbakery/jobs/678396579

**Comment by felipesanches** [comment]
@arrowtype, I am being more verbose than usual here in the hope of illustrating the way I typically deal with these issues and how I like to fix them by first capturing the bad behaviour in our code-tests.

**Comment by felipesanches** [comment]
And now the fix:

![Screenshot from 2020-04-22 22-06-15](https://user-images.githubusercontent.com/213676/80048067-814e7000-84e5-11ea-9031-d4ed7476847f.png)

**Comment by arrowtype** [comment]
Hey @felipesanches, thanks for so clearly documenting the process of fixing this! It's really interesting to read now, and I'm bookmarking it for the future when I try to make a similar fix myself. Thanks also for fixing this so quickly. :)
