### ISSUE TITLE
static dir check running on upstream repos

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#2853]
According to Viviana the static directory check is running on upstream font repos.

**Comment by felipesanches** [comment]
@m4rc1e, could you please describe in more details here what's your suggestion of how to handle this?

**Comment by felipesanches** [comment]
@davelab6 suggested fontbakery could generate TTFs and compare them to the ones on that folder and do something if they differ. I do not think this would work as I believe the binaries would differ 100% of the time due to non-deterministic build factors.

**Comment by m4rc1e** [comment]
When I inspect checks which should only be run on the google/fonts repo, I see they all require the `family_directory` condition. This condition is a bit too simple since it doesn't determine whether we're checking fonts within the google/fonts. What we really need is a new condition, something like `gf_family_directory`:

```
@condition
def gf_family_dir(font):
    dirname = os.path.dirname(font)
    # determine if we're checking a font in the google/fonts repo
    if "ofl" not in os.listdir(os.path.join(dirname, "..", "..")):
        return None
    return dirname
```

I haven't considered all of the edgecases but this seems to work.

**Comment by graphicore** [comment]
Stuff like this is making it harder and harder to isolate just one test case. Font Bakery Dashboard would have to create a dummy `ofl` directory when testing an apache font.

similar btw, and FDB can handle it: [condition `gfonts_repo_structure`](https://github.com/googlefonts/fontbakery/blob/2b9dc66291c6a06e12115143ceb474053629b64e/Lib/fontbakery/profiles/googlefonts_conditions.py#L532).

maybe combining `family_directory` and `gfonts_repo_structure` could do the trick, either as condition, or directly in the check.

```py
@condition
def gf_family_dir(family_directory, gfonts_repo_structure):
    if not family_directory or not gfonts_repo_structure:
        return None
    return family_directory
```

Though, I think `gfonts_repo_structure` should probably check that all `fonts` are in the same directory, or at least in the gfonts repo structure, it currently only looks at `fonts[0]`.

**Comment by felipesanches** [comment]
I agree with @graphicore 

I can add `gfonts_repo_structure` as a condition to the static dirt check.
