### ISSUE TITLE
Vendor ID warning & reporters to explain result level 

### ISSUE THREAD

**Issue by lettersoup** [googlefonts/fontbakery#2855]
Fontbakery warns that my Vendor ID is not known registered id. And it should have a 4 character code. Actually a lot of Vendor ID has 2 character codes. And my id: LS is registered. Could you advise?

<img width="1395" alt="Bildschirmfoto 2020-04-28 um 09 22 53" src="https://user-images.githubusercontent.com/6229652/80459876-54f68180-8933-11ea-8328-05de6d531b56.png">

**Comment by m4rc1e** [comment]
Was your vendorID added recently?

When I check our cached vendor list, https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/data/fontbakery-microsoft-vendorlist.cache, I can see LS isn't there.

@felipesanches perhaps we also need to strip the trailing spaces from font vendorIDs? I understand that a font vendorID is meant to be four characters long. However, I think the MS list removes these spaces since it's html.

**Comment by lettersoup** [comment]
Hi Marc,
yes its added recently.

**Comment by m4rc1e** [comment]
Ok cool. I guess your vendorID will be included in the next fontbakery update. For the time being, please ignore this check.

Also, checks which produce a `warn` are not fatal. Think of them as alerts that something may not be quite right.

**Comment by lettersoup** [comment]
Cool! Many thanks!

**Comment by davelab6** [comment]
@felipesanches please don't close this after confirmation of the latest update fixing this vendor ID. The the first step. But the fact that the meaning of the return levels isn't clear should also be addressed, so please keep this issue open and propose a way to address this in the various reporters :)

**Comment by felipesanches** [comment]
my proposal is to say that the ID was not yet recognized, but if the user can see it listed on microsoft's website, then it is all fine.

**Comment by felipesanches** [comment]
Our code-tests have a set of test-cases whith examples of good and bad vendor IDs. As you can see here, 2-char IDs are OK, but with some caveats:

![Screenshot from 2020-05-07 16-45-12](https://user-images.githubusercontent.com/213676/81337916-2b033480-9082-11ea-971b-125f889888ca.png)

**Comment by felipesanches** [comment]
I've just updated the list of vendor IDs and it includes `LS` for **LetterSoup**:

![Screenshot from 2020-05-07 16-52-34](https://user-images.githubusercontent.com/213676/81338545-330fa400-9083-11ea-9362-812dca9ef2ea.png)

**Comment by laerm0** [comment]
@felipesanches I've got a plus sign in mine - `M+F` - just in case you want another weird glyph to allow. 😜

**Comment by felipesanches** [comment]
> @felipesanches I've got a plus sign in mine - M+F - just in case you want another weird glyph to allow. 😜

I believe that one is already considered good. Let me know if you ever see a legitimate one that is not accepted.

**Comment by lettersoup** [comment]
@felipesanches Many thanks!

**Comment by felipesanches** [comment]
You're welcome! :-)
