### ISSUE TITLE
 Bug, new ERRORs after 0.7.24

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery#2858]
## Observed behavior

After running last 0.7.24 FontBakery version I got some new errors 
The report is included on Resources

## Expected behavior

The Error to be solved 

## Resources and exact process needed to replicate

Fontbakery version: 0.7.24

<details>
<summary><b>[7] Gupter-Bold.ttf</b></summary>
<details>
<summary>💔 <b>ERROR:</b> Glyphs are similiar to Google Fonts version?</summary>

* [com.google.fonts/check/production_glyphs_similarity](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/production_glyphs_similarity)

* 💔 **ERROR** Failed with TypeError: __new__() missing 6 required positional arguments: 'xx', 'xy', 'yx', 'yy', 'dx', and 'dy'

</details>

**Comment by vv-monsalve** [comment]
At the same time, it would be great to have the meaning of checks included in the report.md file. Made a comment on this [here](https://github.com/googlefonts/fontbakery-dashboard/issues/170#issuecomment-621416546)

**Comment by felipesanches** [comment]
@vv-monsalve, I initially thought this ERROR would be in a PR to the `google/fonts` repo, but I could not find a Gupter PR there.

Then I cloned https://github.com/vv-monsalve/GUPTER.git and tried to run the latest fontbakery (form git master) on the bold ttf from the `FONTS/TTF/` directory. FontBakery passes the check:

<img width="834" alt="Captura de Tela 2020-04-30 às 04 03 52" src="https://user-images.githubusercontent.com/213676/80681724-a029a500-8a97-11ea-9896-9f1eef8ddc29.png">

Please let me know where I can find files that cause the ERROR.

**Comment by vv-monsalve** [comment]
I ran the FB cheks in my local files that are up to date with my master branch of the upstream repo, I didn't change anything on them, so this is more strange to me now.

I did this on this project actually because I wanted to test the upgrade of Fontbakery on an already proved working job. Before it, I tried to upgrade it in another project, but even though I received the "successfully installed 0.7.24" after three attempts, it remained in 0.7.22. It only got updated after I delete the venv and reinstall the gftools. 
It had not happened to me before when updating Fontbakery btw.

[Link to a copy of my local Gupter folder. ](https://github.com/vv-monsalve/GUPTER/blob/master/GUPTER.zip)On FONTS/TTF, you can find the resulted folders of the two last QA processes performed and a .txt file with the terminal output, so you can check if I did something wrong.

**Comment by felipesanches** [comment]
@vv-monsalve, thanks for the feedback!

**Comment by felipesanches** [comment]
@vv-monsalve, I have the impression that you have `python 2.7` in your virtual environment. Please delete your venv and create a new one using python 3:

`virtualenv venv -ppython3`

then install fontbakery and try to run the check agains Gupter again and let me know if that solves the issue.

**Comment by vv-monsalve** [comment]
@felipesanches The venv was built on python 3.6. 
Nevertheless, I confirmed it and replicated the process and got the same three Errors. New report.md and terminal output [here](https://github.com/vv-monsalve/GUPTER/tree/master/FONTS/TTF/qaGupterTest2)

**Comment by felipesanches** [comment]
oh, ok! So maybe you had an older `venv` folder with py2 in that ZIP file.

Anyway... I'll keep trying to replicate the bug. Thanks for sending more files. I'll look them up now.

**Comment by vv-monsalve** [comment]
Sure, no problem. I gave it a quick look and didn't see python 2.7, strange. I hope the new files are of any help!

**Comment by vv-monsalve** [comment]
It seems like this was caused by conflicts between python versions indeed. After checking this locally with @m4rc1e  I created a new venv with selected python 3.7 and everything worked ok with FB.
Closing this here :)
