### ISSUE TITLE
Add check for STAT table misplaced "Italic" strings

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2863]
## Observed behaviour

IBM Plex VF in https://www.axis-praxis.org/samsa/ today has a bad STAT table, as the Weights have "Italic" in their style names.

## Expected behaviour

FB should check that "Italic" should not be seen in a list of style names for the Weight axis.

Thanks @lorp for pointing this out

**Comment by felipesanches** [comment]
I'm adding this new check to the `universal` profile with the check-id **com.google.fonts/check/STAT_strings**

**Comment by kontur** [comment]
For this [VF](https://www.dropbox.com/s/p77p6dmehaoe0x9/Signika%5BNEGA%2Cwght%5D.ttf?dl=0) with `NEGA` and `wght` and this ttx STAT table:

```
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="4.9">

  <STAT>
    <Version value="0x00010001"/>
    <DesignAxisRecordSize value="8"/>
    <!-- DesignAxisCount=2 -->
    <DesignAxisRecord>
      <Axis index="0">
        <AxisTag value="wght"/>
        <AxisNameID value="256"/>  <!-- Weight -->
        <AxisOrdering value="0"/>
      </Axis>
      <Axis index="1">
        <AxisTag value="NEGA"/>
        <AxisNameID value="257"/>  <!-- Negative -->
        <AxisOrdering value="1"/>
      </Axis>
    </DesignAxisRecord>
    <!-- AxisValueCount=0 -->
    <ElidedFallbackNameID value="2"/>  <!-- Regular -->
  </STAT>

</ttFont>
```

Fontbakery fails with:

```
 >> com.google.fonts/check/STAT_strings
    Check correctness of STAT table strings
    with fonts/signikavf/Signika[NEGA,wght].ttf

      Rationale:
      On the STAT table, the "Italic" keyword must not be used on AxisValues
      for variation axes other than 'ital'.

    * ERROR: Failed with AttributeError: 'NoneType' object has no attribute 'AxisValue'
           File "/Users/johannes/.pyenv/versions/3.7.6/envs/signika/lib/python3.7/site-packages/fontbakery/checkrunner.py", line 344, in _exec_check
             for sub_result in result:  # Might raise.
           File "/Users/johannes/.pyenv/versions/3.7.6/envs/signika/lib/python3.7/site-packages/fontbakery/profiles/universal.py", line 574, in com_google_fonts_check_STAT_strings
             for value in ttFont["STAT"].table.AxisValueArray.AxisValue:


    Result: ERROR
```

**Comment by kontur** [comment]
Happens in `0.7.25` as well.

**Comment by felipesanches** [comment]
> For this VF with NEGA and wght and this ttx STAT table:

@kontur, whenever you're about to make a comment on a closed issue, please consider opening a new one instead (and reference the closed one for hyperlinking purposes). Otherwise we risk forgetting about your comment.

Is this still a problem for you? If so, please open a new issue so that we can track progress on a fix for it.
