### ISSUE TITLE
Documentation needed on Metadata.pb checks

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery#2872]
## Observed behaviour

After performing Dispatcher process for Varta Vf, two FAILS were reported on FB checks regarding if Metadata.pb information matches os2 weightclass and postScriptName, each one with a short line that is not explanatory.

Given FB on Dispatcher doesn't display the rationales, I looked on [googlefonts fontbakery profiles](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/os2_weightclass) and there is no major explanation either.

On the other hand, there was a Fail about not mentioning "variable font" on the Description file that wasn't reported on the local FB checks.

## Expected behaviour 

To have better documentation on what might be happening or how to proceed.
Cl Fontbakery to include the "variable font" check for the Description file.

## Resources and exact process needed to replicate

Link to the [Dispatcher Fontbakery](https://fontbakery.graphicore.de/report/13c3e1c7-60aa-4057-b964-87ece4ca9d11) results 
Link to [Last Cl FB QA](https://github.com/vv-monsalve/Varta/blob/QA-VartaST/fonts/variable/qaVartaVf-fm2-nodeva/Fontbakery/report.md) folder 
Upstream [https://github.com/vv-monsalve/Varta/tree/QA-VartaST](https://github.com/vv-monsalve/Varta/tree/QA-VartaST)

**Comment by tphinney** [comment]
Can you give the specific error messages?

**Comment by graphicore** [comment]
@tphinney messages:

FAIL com.google.fonts/check/metadata/os2_weightclass Checking OS/2 usWeightClass matches weight specified at METADATA.pb.

    FAIL
    OS/2 usWeightClass (300:"Light") does not match weight specified at METADATA.pb (400:"Regular").
    code mismatch

index 65
job_id "0"

FAIL com.google.fonts/check/metadata/match_weight_postscript METADATA.pb weight matches postScriptName.

    FAIL
    METADATA.pb: Mismatch between postScriptName ("Varta-Light") and weight value (400). The name must be ended with "Regular" or "Italic".

index 66
job_id "0"

FAIL com.google.fonts/check/repo/vf_has_static_fonts A static fonts directory with at least two fonts must accompany variable fonts

    FAIL
    Please create a subdirectory called "static/" and include in it static font files.
    code missing

index 101
job_id "1"

<hr />


METADATA.pb ([from the package](https://fontbakery.graphicore.de/download/persistence/4f08e9f13780e246e91e16b3b3bd42028ab0f1b1419ecdd09a973865a041e80f:0/Varta.zip) of the [FBD process](https://fontbakery.graphicore.de/dispatcher/process/59539cc7-f6b0-4e29-b43d-0a9410829d8c))

```
name: "Varta"
designer: "Joana Correia, Viktoriya Grabowska, Eben Sorkin"
license: "OFL"
category: "SANS_SERIF"
date_added: "2015-05-13"
fonts {
  name: "Varta"
  style: "normal"
  weight: 400
  filename: "Varta[wght].ttf"
  post_script_name: "Varta-Light"
  full_name: "Varta Light"
  copyright: "Copyright 2019 The Varta Project Authors (https://github.com/SorkinType/Varta)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
axes {
  tag: "wght"
  min_value: 300.0
  max_value: 700.0
}
```

**Comment by vv-monsalve** [comment]
This Issue was split on independent ones for each Fail. Closing this here

**Comment by felipesanches** [comment]
thanks!
