### ISSUE TITLE
Include [com.google.fonts/check/description/variable_font] in the Cl Fontbakery

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery#2875]
Splitting #2872 into individual Issues for each Fail

## Observed behaviour

The Fail was reported after running the FB checks from Dispatcher, but was not included when local [qa] was performed.

## Expected behaviour

It would be important to get it from the local FB checks

## Resources and exact process needed to replicate

Link to the [Dispatcher Fontbakery](https://fontbakery.graphicore.de/report/13c3e1c7-60aa-4057-b964-87ece4ca9d11) results 
Link to [Last Cl FB QA](https://github.com/vv-monsalve/Varta/blob/QA-VartaST/fonts/variable/qaVartaVf-fm2-nodeva/Fontbakery/report.md) folder 
Upstream [https://github.com/vv-monsalve/Varta/tree/QA-VartaST](https://github.com/vv-monsalve/Varta/tree/QA-VartaST)

**Comment by felipesanches** [comment]
it is not clear to me what happened here...

* You tried running fontbakery locally (via `gftools qa --fontbakery`?) on some font files and the check ***com.google.fonts/check/description/variable_font*** was not executed?
* But when running it on FB-dashboard the check was properly executed?

**Comment by felipesanches** [comment]
@vv-monsalve, have you tried to run fontbakery directly on these files to see if the problem also happens or if maybe it is a bug in `gftools-qa`  instead?

**Comment by vv-monsalve** [comment]
> * You tried running fontbakery locally (via `gftools qa --fontbakery`?) on some font files and the check _**com.google.fonts/check/description/variable_font**_ was not executed?

Yes. I did it with the `gftools qa -f <path to font>` command and this Fail wasn't reported.

> * But when running it on FB-dashboard the check was properly executed?

Yes, the Fail was reported on FB-dashboard process. I couldn't say "properly executed", I don't know how far the local FB checks must look at repository content or files. I know there is a [check](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/license/OFL_copyright) for the license file to have a good copyright string, so I thought this could be an excellent one to include in the local Cl FB checks.

> have you tried to run fontbakery directly on these files to see if the problem also happens or if maybe it is a bug in gftools-qa instead?

[qa] is the usual command I perform, I didn't think of it as a possible [qa] bug. I ran the command `fontbakery check-googlefonts Sora\[wght\].ttf -l FAIL` to a new project before and after creating the Description file, and the FAIL wasn't reported either, which reinforces my reasoning about the local FB checks don't look for all the information files in the repo. Here is the [Terminal Saved Output](https://github.com/vv-monsalve/sora-font/blob/QA-sora/fonts/variable/Terminal%20Saved%20Output.txt). 

The purpose of the issue was more a suggestion given it would help the user to ensure the needed information as requested before proceeding with PR. With the increasing number of users aware of Fontbakery and having in mind that the Spec requires a specific [repository structure](https://github.com/googlefonts/gf-docs/tree/master/Spec#upstream-repo-structure), I still think it would be helpful to include this sort of checks in the Cl FB. Unless they are and there is a particular command in fontbakery for that and I'm not aware of it, if so, please tell me which would it be.

Finally, to prevent this Fail, I added this as a [requisite for the Description file](https://github.com/googlefonts/gf-docs/pull/64), but I understand Marc proposed to remove this Variable Font check at all in #2885

**Comment by felipesanches** [comment]
yes, I will follow @m4rc1e's recommendation. Thanks, @vv-monsalve!
