### ISSUE TITLE
Improve Vertical Metrics check for Latin+CJK Fonts

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2893]
## Observed behaviour

@minjooham and @mark2mark raised an urgent issue with me directly on this, because their https://github.com/hyper-type/hahmlet project is blocked on this question; it also seems related to #2841 and #2796:

When we have Latin+CJK font families, then neither the vertical metrics requirements FB checks today, and the CJK-specific vertical metrics guide from Ken Lunde, make sense. 

At time of posting this, a FontBakery Dashboard results page at  
https://fontbakery.graphicore.de/report/2c6f9580-865a-4593-8304-3567ae68b15e shows FAILs for the fonts in that repo:

* com.google.fonts/check/family/win_ascent_and_descent
  * Checking OS/2 usWinAscent & usWinDescent.
  * OS/2.usWinAscent value should be equal or greater than 1219, but got 1160 instead code ascent
  * OS/2.usWinDescent value should be equal or greater than 317, but got 288 instead code descent
* com.google.fonts/check/os2_metrics_match_hhea
  * Checking OS/2 Metrics match hhea Metrics.
  * OS/2 sTypoAscender (880) and hhea ascent (1160) must be equal. code ascender

Ken Lunde's guide suggest a Typo Descender of `-120`, but this would only make sense for CJK-only fonts, as for Latin+CJK fonts the Latin descender will necessarily be lower. 

So, what should we do for CJK font vertical metrics in 2020? :)

**Comment by m4rc1e** [comment]
> Ken Lunde's guide suggest a Typo Descender of -120, but this would only make sense for CJK-only fonts, as for Latin+CJK fonts the Latin descender will necessarily be lower.

No. The Adobe CJK fonts and Noto fonts all include Latin and use the schema specified here, https://github.com/googlefonts/gf-docs/tree/master/Spec#cjk-vertical-metrics.

We simply need to finished off #2797 and update the webapp.

**Comment by felipesanches** [comment]
@m4rc1e, could you please reassess the status of this issue in light of #2797 having been merged earlier this week?

**Comment by m4rc1e** [comment]
Implementing #2797 has fixed this issue.
