### ISSUE TITLE
Add check: Repo README has sample image inline?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2898]
## Observed behaviour

Many project READMEs do not show a sample image in the first ~10 lines, so when users first visit the repo, they don't see what it looks like. 

## Expected behaviour

- [x] Repo has a sample image, PNG or JPEG (WARN if not)
- [x] /README.md shows that image inline (WARN if not)
- [x] /README.md shows that image inline in the first ~10 lines (WARN (lower priority) if not)

Maybe FAILs for this is too strict and WARN is OK... 

## Resources and exact process needed to replicate

https://github.com/hyper-type/hahmlet/pull/3 is an example of me addressing this (repo had image, was not inlined in README)

https://github.com/MonicaRizzolli/Tomorrow is a good example (has image)

https://github.com/impallari/Raleway is currently a bad example (no image)

**Comment by felipesanches** [comment]
![Screenshot from 2021-09-15 14-53-23](https://user-images.githubusercontent.com/213676/133484532-bb997365-9f71-4174-9479-9b421a7c0bf7.png)

**Comment by felipesanches** [comment]
![Screenshot from 2021-09-15 14-54-39](https://user-images.githubusercontent.com/213676/133484700-65e6b905-ed05-4fcb-a41d-c6b5ab406922.png)

**Comment by felipesanches** [comment]
![Screenshot from 2021-09-15 14-56-24](https://user-images.githubusercontent.com/213676/133484958-6521df55-55f0-4e92-8c13-532a11e11191.png)

**Comment by felipesanches** [comment]
![Screenshot from 2021-09-15 14-59-10](https://user-images.githubusercontent.com/213676/133485357-63c32a97-822d-4bb0-9e8b-d0292ea5e0e1.png)
