### ISSUE TITLE
Add check: No ZIPs in upstream repos

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2903]
## Observed behaviour

Sometimes people check in ZIPs into their repos. While I defend the practice of checking in binaries at all - a source purist position is that only source files and build scripts should be checked in - for me a ZIP is a step too far ;)

## Expected behaviour

So we should have an upstream repo check for file extensions for common zip formats, and FAIL if they are found. 

## Resources and exact process needed to replicate

https://github.com/agyeiarcher/Crispy-VF/issues/67 is an example of this

**Comment by davelab6** [comment]
https://github.com/LauraMeseguer/Questrial-Font/tree/3c090f81f21472876b3d1acd6432800e1a0515d8 is another example of a repo in this state

**Comment by felipesanches** [comment]
thanks!
