### ISSUE TITLE
ERROR in com.google.fonts/check/family/vertical_metrics

### ISSUE THREAD

**Issue by drj11** [googlefonts/fontbakery#2917]
## Observed behaviour

When running

    fontbakery check-universal jam8.ttf

I get

    * ERROR: Failed with KeyError: 'OS/2'

The full error is:

 >> com.google.fonts/check/family/vertical_metrics
    Each font in a family must have the same set of vertical metrics values.
    

      Rationale:                                                                
      We want all fonts within a family to have the same vertical metrics so    
      their line spacing is consistent across the family.                       

    * ERROR: Failed with KeyError: 'OS/2'
           File "/home/drj/miniconda3/envs/font-bakery/lib/python3.8/site-packages/fontbakery/checkrunner.py", line 344, in _exec_check
             for sub_result in result:  # Might raise.
           File "/home/drj/miniconda3/envs/font-bakery/lib/python3.8/site-packages/fontbakery/profiles/universal.py", line 818, in com_google_fonts_check_family_vertical_metrics
             vmetrics['sTypoAscender'][full_font_name] = ttFont['OS/2'].sTypoAscender
           File "/home/drj/miniconda3/envs/font-bakery/lib/python3.8/site-packages/fontTools/ttLib/ttFont.py", line 381, in __getitem__
             data = self.reader[tag]
           File "/home/drj/miniconda3/envs/font-bakery/lib/python3.8/site-packages/fontTools/ttLib/sfnt.py", line 105, in __getitem__
             entry = self.tables[Tag(tag)]
         

    Result: ERROR

## Expected behaviour

I'm pretty sure the file does not have the `OS/2` table, so probably a FAIL?

## Resources and exact process needed to replicate

Font: https://gitlab.com/drj11/jam8/-/blob/24d0d9b3bd5b58bf04d1e98b988bc8f768539d14/jam8.ttf

This is a TTF file created using tools of my own devising, so I am fully aware that it is probably broken in many ways. I guess the question is, to what extent do you want `fontbakery` to report reasonable results for unreasonable files?

I have about 30 more ERRORs if you want them.

**Comment by m4rc1e** [comment]
Perhaps your font doesn't have an OS/2 table yet?

The vertical metrics check needs this table.

**Comment by graphicore** [comment]
@m4rc1e right, but the check should catch this exception and emit a FAIL. cc @felipesanches

**Comment by felipesanches** [comment]
yep! I'll take care of this one ;-)
