### ISSUE TITLE
ERROR: Failed with TTLibError: illegal use of getGlyphOrder()

### ISSUE THREAD

**Issue by drj11** [googlefonts/fontbakery#2918]
## Observed behaviour

When running

    fontbakery check-universal jam8.ttf

I get an error from `com.google.fonts/check/mandatory_glyphs`

    * ERROR: Failed with TTLibError: illegal use of getGlyphOrder()

Full error is:

 >> com.google.fonts/check/mandatory_glyphs
    Font contains .notdef as first glyph?
    with jam8.ttf

      Rationale:                                                                
      The OpenType specification v1.8.2 recommends that the first glyph is the  
      .notdef glyph without a codepoint assigned and with a drawing.            
                                                                                
      https://docs.microsoft.com/en-us/typography/opentype/spec                 
      /recom#glyph-0-the-notdef-glyph                                           
                                                                                
      Pre-v1.8, it was recommended that a font should also contain a .null, CR  
      and space glyph. This might have been relevant for applications on MacOS  
      9.                                                                        

    * ERROR: Failed with TTLibError: illegal use of getGlyphOrder()
           File "/home/drj/miniconda3/envs/font-bakery/lib/python3.8/site-packages/fontbakery/checkrunner.py", line 344, in _exec_check
             for sub_result in result:  # Might raise.
           File "/home/drj/miniconda3/envs/font-bakery/lib/python3.8/site-packages/fontbakery/profiles/universal.py", line 354, in com_google_fonts_check_mandatory_glyphs
             ttFont.getGlyphOrder()[0] == ".notdef"
           File "/home/drj/miniconda3/envs/font-bakery/lib/python3.8/site-packages/fontTools/ttLib/ttFont.py", line 441, in getGlyphOrder
             glyphOrder = self['post'].getGlyphOrder()
           File "/home/drj/miniconda3/envs/font-bakery/lib/python3.8/site-packages/fontTools/ttLib/tables/_p_o_s_t.py", line 66, in getGlyphOrder
             raise ttLib.TTLibError("illegal use of getGlyphOrder()")
         

## Expected behaviour

a FAIL

## Resources and exact process needed to replicate

font file: https://gitlab.com/drj11/jam8/-/blob/24d0d9b3bd5b58bf04d1e98b988bc8f768539d14/jam8.ttf

It's entirely possble that this file has bad cmap tables (I wrote them myself and Format 4 is a headache), but even so, the tool ought to report FAILs.

**Comment by felipesanches** [comment]
thanks for reporting this. I'll take a look

**Comment by felipesanches** [comment]
the problem here is that a whole lot of checks will result in this ERROR if the file is malformed. So it is not really a bug in a specific check, but simply a way too corrupt font file. It would be to much noise to add logic to the checks to catch this problem. We may have to do it at some other level within FontBakery's check runner core. It is not trivial. I'll have to think more carefully about it.

**Comment by drj11** [comment]
I agree. It turns out an awful lot of things get upset if you don't have a `.notdef` glyph

**Comment by bobh0303** [comment]
If there is a concern about the structure of the font file, I'd suggest testing with Font Validator first.

**Comment by simoncozens** [comment]
I don't think there's a real problem here. If fontbakery reports 17 errors on a particular font, that should be taken as a pretty clear indication that the font is extremely broken... These days, most of the fontbakery checks which don't error report that the font is missing an OS/2 table, which is what ots-sanitize is upset about.
