### ISSUE TITLE
GDEF warnings accurate ?

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#2925]
## Observed behaviour

I have two warnings about the GDEF tables that look contradictory:
```
The following spacing glyphs may be in the GDEF mark glyph class by mistake:
acutecomb, acutecomb.case, circumflexcomb_hookcomb.case, dotbelowcomb, dotbelowcomb.case, gravecomb, gravecomb.case, hookabovecomb, hookabovecomb.case, tildecomb and 56 more.
```
```
The following mark characters could be in the GDEF mark glyph class:
U+0300, U+0301, U+0302, U+0303, U+0304, U+0306, U+0307, U+0308, U+0309, U+030A, U+030B, U+030C, U+030F, U+0311, U+0312, U+031B, U+0323, U+0324, U+0326, U+0327, U+0328, U+032E, U+0331, U+0335, U+0336, U+0337 and U+0338
```
## Expected behaviour

- Is "Could be" a suggestion, or a warning? It's ambiguous. Moreover, list of unicodes refers to the same list of comb-marks in the first warning, which are indeed in the GDEF table according to 1st warning, but apparently by mistake. 
- Correct me if I am wrong but comb-marks should be non-spacing glyphs, therefore they should be in the GDEF table: 1st warning shouldn't appear.

I checked in the ttf : comb accents have 0 width as expected (although they have a negative right sidebearing instead of a traditional negative left sidebearing), and non-comb accent have a positive width.

## Resources and exact process needed to replicate

Place anchors in a comb accent, export font and generate report with gftools qa. 
There is the URL of the PR where the actual report is:
[Epilogue PR11](https://github.com/Etcetera-Type-Co/Epilogue/pull/11)

**Comment by felipesanches** [comment]
Here's the new release :-)

https://pypi.org/project/fontbakery/0.7.27/

I've tested it with your font project and the GDEF checks PASS. There's nothing wrong with your fonts (regarding these specific checks which were broken in the 0.7.26 version, sorry for the noise)

**Comment by felipesanches** [comment]
@RosaWagner, please consider joining our Gitter chat at https://gitter.im/fontbakery/Lobby

cheers!
