### ISSUE TITLE
com.google.fonts/check/font_version seems overly strict

### ISSUE THREAD

**Issue by drj11** [googlefonts/fontbakery#2928]
## Observed behaviour

Oh font versions.

On running

    $ fontbakery check-universal -c com.google.fonts/check/font_version -n jam8.ttf

I get the FAIL message:

    * FAIL: head version is "2020.061" while name version string (for platform 3, encoding 1) is "Version 2020.0611". [code: mismatch]

More output:
```
Start ... running 1 individual check executions.
 >> com.google.fonts/check/font_version
    Checking font version fields (head and name table).
    with jam8.ttf

    * FAIL: head version is "2020.061" while name version string (for platform 3, encoding 1) is "Version 2020.0611". [code: mismatch]


    Result: FAIL
```

## Expected behaviour

a PASS?

This font does have `Version 2020.0611` in the `name` table; that part is correct.

The `fontVersion` field has the value 0x07e40fa4 which is the closest multiple of 1/65536 to 2020.0611, (0x07e40fa4/65536 is exactly 2020.06109619140625).

The current code appears to assume that version fields are only ever given to 3 decimal places and checks that the `fontVersion` field in the `head` table when converted to decimal with 3 decimal places is exactly the string in the `name` table.

I can't find any documentation that support this 3 decimal place idea, but do point me at it if there is some.

I think the check should be that the `fontVersion` field is within some tolerance of the `name` entries. Good conversion routines should put this tolerance at 0.5/65536, but for the sake of software that might convert fractional numbers poorly, maybe the tolerance should be 1/65536 or the more relaxed 0.00001 or even 0.0005 (the latter is effectively requiring that they match to 3 decimal places).

I'm happy to code up that approach if the maintainers agree in principle (I think it would be simpler too)

## Resources and exact process needed to replicate

jam8.ttf is here: https://gitlab.com/drj11/jam8/-/blob/5124415bcfc165c1744014548c32eedf9f8c35a2/jam8.ttf

(note: not all my `jam8.ttf` files are the same, so make sure you get the right one)

(Please provide here an URL to a font file that appears to cause the issue, and the exact steps from updating to the latest code on the `master` branch to reproduce the Observed Behaviour. We need this in for replicating the issue and fixing it :)

**Comment by felipesanches** [comment]
thanks for filing and fixing this one, @drj11

**Comment by drj11** [comment]
For the historical record (me, looking at this 2 years later), I did find the Microsoft recommendations that discuss keeping versions to 3 decimal places:

https://docs.microsoft.com/en-us/typography/opentype/spec/recom#head-table

Annoyingly, the same document specifically recommends using a wrong a value for 1.001: The Microsoft recommendations suggest 0x10041 which is closer to 1.0099 than 1.001; 0x10042 is 1.001007 and is closer to 1.001; it would be correct the value to use.

**Comment by felipesanches** [comment]
does it mean it owuld be better to revert these changes?

**Comment by drj11** [comment]
No, I think the changes are still good. With these changes, you only get a FAIL if the version in the `head` table and a string version in the `name` table differ by more than 0.0005 when computed exactly. This is better than comparing to 3 decimal places, because it allows more precise version strings to also pass the check. For example, my version strings are all precise to 4 decimal places.

I really was just answering my own question where I said "I can't find any documentation that support this 3 decimal place idea, but do point me at it if there is some." in the original report.

**Comment by drj11** [comment]
In particular, someone using 0x10041 in the `head` table, and "1.001" in the `name` table, won't get a FAIL, but they will get a WARN

**Comment by felipesanches** [comment]
thanks
