### ISSUE TITLE
STAT FVAR check: Font families with Italic styles should have an ital axis

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#2934]
**Should be triggered if "Italic" is part of the file name, or `NameID2`, or `NameID17`.**
The ticked cases indicates where you can already find it.

### `Ital` axis should be set in `STAT` table
`<AxisTag value="ital"/>`

**Profile**
- [ ] in google-font profile
- [ ] in universal profile
- [ ] in opentype profile

**Format**
- [ ] in VF check
- ~in static check~

Initial issue posted:
-----
## Observed behaviour

I have this Fontbakery fail :
```
Check correctness of STAT table strings
* [com.google.fonts/check/STAT_strings](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/STAT_strings)

On the STAT table, the _Italic_; keyword must not be used on AxisValues for
variation axes other than _ital_.

 **FAIL** The following AxisValue entries on the STAT table should not contain "Italic":
 ['Thin Italic', 'ExtraLight Italic', 'Light Italic', 'Italic', 'Medium Italic', 'SemiBold Italic', 'Bold Italic', 'ExtraBold Italic', 'Black Italic', 'Thin Italic', 'ExtraLight Italic', 'Light Italic', 'Italic', 'Medium Italic', 'SemiBold Italic', 'Bold Italic', 'ExtraBold Italic', 'Black Italic'] [code: bad-italic]
```

## Expected behaviour

Uprights and italics are separated in 2 variable fonts. Therefore there is no _ital_ axis and the word 'italic' is only used to describe the instances name. But I have a poor experience with STAT table so I actually don't know if it is a bug from Fontbaky, from Fontmake or the build script.

## Resources and exact process needed to replicate

Report and fonts can be found in this PR : [Epilogue-PR12](https://github.com/Etcetera-Type-Co/Epilogue/pull/12)

**Comment by felipesanches** [comment]
This is the issue where @davelab6 requested this check: #2863 

Let us know if you think your use-case does not apply to what Dave wanted to enforce with the new check. I gotta be honest that I still do not understand it very well as well.

**Comment by felipesanches** [comment]
If we're able to clarify how it works, then it is yet another case in which we should craft a better rationale description for the check.

**Comment by RosaWagner** [comment]
Which STAT Guru could we invoke for this matter?

**Comment by felipesanches** [comment]
@davelab6, last May 8th we had a "Samsa Review" video call in which, if I recall correctly, there's been some discussion about the STAT table and also some examples of Samsa being used to inspect a font with a properly setup STAT table. I also had the impression that a video recording of the call would be posted to youtube soon. Can you confirm that?

Other than the opentype spec itself, would you point us at any other place where we can find more info on the correct way of building this table?

**Comment by punchcutter** [comment]
Ideally you would have an `ital` axis in both fonts set to 0 in the Upright and 1 in the Italic. Like the check above says there shouldn't be 'Italic' in the axis value names of the Italic STAT table. They should have the same names as the Upright. 'Italic' should also be defined as the elidable name in the Italic STAT table. That way software that understands STAT tables can generate the proper name based on these settings.

**Comment by felipesanches** [comment]
I love the internet! :-D

**Comment by felipesanches** [comment]
I'll try to reuse some of this into a good rationale description for the check. Thanks for all the info, @punchcutter ;-)

(by the way, I see Tokyo on your profile. Did we have a chance to meet during ATypI last year? Your face looks somewhat familiar to me :-D)

**Comment by punchcutter** [comment]
@felipesanches Yes, I was at ATypI last year. I was the first speaker! 

I'm in the middle of writing a bunch of STAT validation tests that I'm planning to submit to fontbakery soon.

**Comment by felipesanches** [comment]
Awesome! I'm glad to hear that ;-)

**Comment by m4rc1e** [comment]
I've nearly finished writing an update to our STAT table generator. @thlinard is very kindly reviewing the output. I recommend we create a better STAT check once we can generate a table correctly.

**Comment by felipesanches** [comment]
thanks, Marc!

**Comment by felipesanches** [comment]
This is the youtube video I was talking about at https://github.com/googlefonts/fontbakery/issues/2934#issuecomment-646307700:
https://www.youtube.com/watch?v=T75bZ7ooiFQ

**Comment by vv-monsalve** [comment]
Profiles where it should be included
- [x] in google-font profile
- [x] in universal profile
- [x] in opentype profile
