### ISSUE TITLE
There is truncated text in the faliing text for `valid_glyphnames`

### ISSUE THREAD

**Issue by drj11** [googlefonts/fontbakery#2938]
## Observed behaviour

When running

    fontbakery check-universal -c com.google.fonts/check/valid_glyphnames -n jam8.ttf

and the check fails I see

```
    * FAIL: The following glyph names do not comply with naming conventions: .version and 

 such as the special character ".notdef". The glyph names "twocents", "a1", and "_" are all valid, while "2cents" and ".twocents" are not. [code: found-invalid-names]
```

## Expected behaviour

The text starting "such as the special" appears from the middle of nowhere. It's in the source code like that too.

I did some digging and found that the longer and more useful has been (accidentally?) cropped in a change earlier this year: https://github.com/googlefonts/fontbakery/commit/294c3d3ddc0a632119477db7cf041b6597dfdcb5#diff-b713212316016e2c07a81da38641522c

## Resources and exact process needed to replicate

This version of my jam8.ttf file shows this bug: https://gitlab.com/drj11/jam8/-/blob/931d961c90297803cf7035ac3523a6b122bca39d/jam8.ttf

**Comment by felipesanches** [comment]
thanks!
