### ISSUE TITLE
com.google.fonts/check/metadata/os2_weightclass: ExtraLight/200

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontbakery#2947]
## Observed behaviour

Checks for ExtraLight with weightClass 200 fail, but should pass imo.
The weights in METADATA.pb are also 200.

```
 >> com.google.fonts/check/metadata/os2_weightclass
    Check METADATA.pb font weights are correct.
    with /Users/yanone/Projekte/Google/Onboarding/fonts/ofl/nunito/Nunito-ExtraLight.ttf

      Rationale:                                                                
      Check METADATA.pb font weights are correct.                               
                                                                                
      For static fonts, the metadata weight should be the same                  
      as the static font's OS/2 usWeightClass.                                  
                                                                                
      For variable fonts, the weight value should be 400 if the                 
      font's wght axis range includes 400, otherwise it should be the           
      value closest to 400.                                                     

    * FAIL: OS/2 usWeightClass (200:"bad Google Fonts API weight value") does not match weight specified at METADATA.pb (200:"ExtraLight"). [code: mismatch]


    Result: FAIL
```

## Resources and exact process needed to replicate

Here's a branch of my fork specifically for this issue:
https://github.com/yanone/fonts/tree/nunito-gh-issue-weightclass-200/ofl/nunito

**Comment by m4rc1e** [comment]
Thanks for the tests fonts!

[com_google_fonts_check_metadata_os2_weightclass](https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/profiles/googlefonts.py#L2465-L2473) Checks that a static font's usWeightClass is between 250-900. This is old behaviour. What we want is the following:

static ttf: 100-900
static otf: 250-900
static vf: 100-900

I'll update the check later. For the time being, having 200 for ExtraLight is fine.

**Comment by felipesanches** [comment]
thanks @yanone and @m4rc1e!
