### ISSUE TITLE
com.google.fonts/check/STAT_strings: ERROR on VF

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontbakery#2949]
## Observed behaviour

The test `com.google.fonts/check/STAT_strings` fails with:

```
    * ERROR: Failed with AttributeError: AxisIndex
           File "/usr/local/lib/python3.7/site-packages/fontbakery/checkrunner.py", line 344, in _exec_check
             for sub_result in result:  # Might raise.
           File "/usr/local/lib/python3.7/site-packages/fontbakery/profiles/universal.py", line 609, in com_google_fonts_check_STAT_strings
             if value.AxisIndex != ital_axis_index: nameIDs.append(value.ValueNameID)
           File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 548, in __getattr__
             raise AttributeError(attr)
```

I looked into the [code](https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/profiles/universal.py#L609) and manually checked the font with `fontTools` and found that not all values contain the `AxisIndex` attribute.

In my font, only one value of `Format 1` contained `AxisIndex`, the others (all `Format 4`) didn't.

I read through the [specs](https://docs.microsoft.com/en-us/typography/opentype/spec/stat): `Format 1–3` contain the `AxisIndex` attribute, and `Format 4` contains an `AxisValue` attribute which in turn contains records with `AxisIndex` attributes.

I can only comment formally. Whether one needs to traverse in case of `Format 4` or stick with one or more of the other three formats is beyond my understanding.

## Resources and exact process needed to replicate

The font I'm working on is in a private repo atm, please email me at post@yanone.de if necessary.

**Comment by felipesanches** [comment]
I've just sent a request for some font samples on the email address Yanone provided.

**Comment by felipesanches** [comment]
unfortunately, @yanone can't remember exactly which files were affected by this.
