### ISSUE TITLE
Naming compatibility between static and VF when both installed

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#2950]
Since GF distribute static and VF fonts, both TrueType,
Since name IDs of the VF are built from the font-name and the style-name of the font-origin,
Since both formats are often installed together,,
We have conflict if static and VF fonts are installed all together on the same machine (conflict between one instance (font origin of the VF) and the VF. 

The spec require a different file-name for the VF, but the name IDs are still the same.
Why not warning users from that problem in Fontbakery? and maybe advise them to modify the family name of the VF or the static (I don't know which one it is preferable to mark as static or variable). 

Ultimately Fontmake could take into account the custom parameter "Variable font file name" and "Variable font family name" to help for this matter.
Related issues (but it is not exactly the same issue) : 
https://github.com/googlefonts/fontmake/issues/666

Fontbook error:
![Capture d’écran 2020-06-30 à 12 19 15](https://user-images.githubusercontent.com/12222436/86116223-5f68ff00-bacd-11ea-91ba-eba7bfd86b47.png)

**Comment by m4rc1e** [comment]
> We have conflict if static and VF fonts are installed all together on the same machine (conflict between one instance (font origin of the VF) and the VF.

This was an intentional decision. Users should use either the VFs or TTFs.

**Comment by RosaWagner** [comment]
But how do you do when you want to use VF in indesign and static in Word ? Id you have a font installed in the Adobe font folder and a copy in the user font folder it is going to create a conflict…

**Comment by m4rc1e** [comment]
You should not be using VFs anywhere other than the web imo.

Both PDF 2.0 and postscript specs do not support VFs and this may take many years to happen, https://community.adobe.com/t5/indesign/variable-fonts/td-p/9548293?page=1

**Comment by m4rc1e** [comment]
I've sent a mail to GF eng about this. Let's see what they say.

**Comment by RosaWagner** [comment]
I get it so let's close this issue then. I also think it would be useful to warn users about this because it is quite restrictive and can create cache issues they may don't know how to resolve, thanks for the email. Let's also precise it in the spec ?

In the meanwhile it really bothers me for local testing, but I will find a workaround ^^
