### ISSUE TITLE
[code: non-mark-chars] incorrect clasiification of marks

### ISSUE THREAD

**Issue by typoman** [googlefonts/fontbakery#2951]
## Observed behavior

    * WARN: The following non-mark characters should not be in the GDEF mark glyph class:
	 U+FBB2, U+FBB3, U+FBB4, U+FBB5, U+FBB6, U+FBB7, U+FC5E, U+FC60, U+FC61 and U+FC63 [code: non-mark-chars]

## Expected behavior

These characters are used in Arabic script as marks. There shouldn't be any warning.

**Comment by bobh0303** [comment]
According to Unicode, these are not marks but rather they are spacing characters. Therefore they should not be used as marks in a font and thus they should not be in the GDEF table.

**Comment by bobh0303** [comment]
Note that all of these are intended for use in isolation such as when writing about the symbols.

**Comment by simoncozens** [comment]
Yep, I agree with Bob. I can understand why people encode their marks with these codepoints, but they shouldn't, and fontbakery is right here.
