### ISSUE TITLE
Why "Unable to detect what's the latest version of FontBakery available" fails the font? IMHO, it should be an ERROR 

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/fontbakery#2966]
I'm running standalone fontbakery with a good internet connection...

The first error I got was F "Unable to detect what's the latest version of FontBakery available" ... This could be an error in the program... Maybe my firewall is such that it doesn't allow you to do what you want to do... Which leads me to a second point ...
Why is this an F against the font (i.e. my font failing the check) as opposed to fontbakery ERROR? This has NOTHING to do with my font under test...

instance_ttf % fontbakery check-notofonts -x monospace NotoSansTagalog-Regular.ttf 
Start ... running 67 individual check executions.
 >> com.google.fonts/check/fontbakery_version
    Do we have the latest version of FontBakery installed?
    

    * FAIL: Unable to detect what's the latest version of FontBakery available. Maybe we're offline? Please check Internet access and try again.

    Result: FAIL

**Comment by felipesanches** [comment]
If I recall correctly, the reasoning was that in order to be considered good to push to the Google Fonts collection, a font must pass all checks in the latest available version of fontbakery. So, if something went wrong with ensuring that the latest set of checks was indeed used to validate the quality of the font, then it can't proceed, thus a FAIL.

But I agree that it alse feels like an ERROR. Maybe because it is semantically both.

**Comment by marekjez86** [comment]
Note when I run it as a github action it runs fine... When I run it on my Mac standalone it fails

**Comment by marekjez86** [comment]
@felipesanches : My conjecture "pip" is the problem (running on Catalina on my macbookpro):

here are the outputs of pip and pip3 commands. 


Notice that

- pip is tied to my Python 2.7; doesn't seem to return any strings containing INSTALLED not LATEST
- pip3 is tied to Python 3.8... ; doesn't seem to return any strings containing LATEST but it has INSTALLED


macbookpro5% _pip search fontbakery_ 
_DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
fontbakery (0.7.28)  - Well designed Font QA tool, written in Python 3_
macbookpro5% _pip3 search fontbakery_
_fontbakery (0.7.28)  - Well designed Font QA tool, written in Python 3
  INSTALLED: 0.7.28 (latest)_
macbookpro5% 


..... just copied and pasted the Python code so I can try to debug it

import subprocess
    installed_str = None
    latest_str = None
    is_latest = False
    failed = False
    pip_cmd = ["pip", "search", "fontbakery"]
    pip_output = subprocess.check_output(pip_cmd, stderr=subprocess.STDOUT)
    for line in pip_output.decode().split('\n'):
      if 'INSTALLED' in line:
        installed_str = line.split('INSTALLED')[1].strip()
      if 'LATEST' in line:
        latest_str = line.split('LATEST')[1].strip()
      if '(latest)' in line:
        is_latest = True

**Comment by marekjez86** [comment]
**<name>:~**$ _pip search fontbakery
fontbakery (0.7.28)  - Well designed Font QA tool, written in Python 3_
**<name>:~**$ _pip3 search fontbakery
fontbakery (0.7.28)  - Well designed Font QA tool, written in Python 3_


looks that search doesn't return 'LATEST' -- it returns "Well designed Font QA tool," :-)
