### ISSUE TITLE
Could you add a Rupee Sign check for the indic fonts and fail if there's none?

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/fontbakery#2967]
Per Bureau of Indian Standards every font supporting one of the official Indian languages (see the list below) needs to include Unicode Character “₹” (U+20B9) Indian Rupee Sign.

I don't know if googlefonts want to adhere to this standard (but I face user comments when they don't find Rupee Sign in their fonts.google.com download and they expect it, so my recommendation is to add this to your checks). However, I'm REQUIRED to support these for all notofonts.

Could you add a Rupee check for the indic fonts and fail if there's none?

Bengali U+0988
Devanagari U+0908
Gujarati U+0A88
Gurmukhi U+0A08
Kannada U+0D08
Malayalam U+0B08
Meetei Mayek U+ABC8
OlChiki U+1C58
Oriya U+0B08
Tamil U+0B88
Telugu U+0C08

I don't know if you know that you are dealing with one of the above scripts, but I included the Unicode value for the 8th character from the block for these scripts (they all exist). If you want a "kludgy" check then see if any of the U+ values are in the font, if yes then check if U+20B9 is also present. If present then PASS if absent then FAIL.

**Comment by felipesanches** [comment]
This sounds very reasonable! I can try to use that in the implementation of a check that I'd call **com.google.fonts/check/rupee**

**Comment by marekjez86** [comment]
thank you!

**Comment by felipesanches** [comment]
can you give me an URL to a font file to be used when testing this new check?

**Comment by marekjez86** [comment]
I'll give you three in about 15 min... One non-indic [shouldn't fail] , one indic without rupee [shouldn't fail], one indic with rupee [should fail]

**Comment by felipesanches** [comment]
great!

**Comment by marekjez86** [comment]
Irrelevant (non-Indic) https://github.com/notofonts/NotoRashiHebrew/tree/master/fonts/ttf/unhinted/instance_ttf (IMHO, silent in this case - no message)
Indic with Rupee: https://github.com/notofonts/NotoSerifDevanagari/tree/master/fonts/ttf/unhinted/instance_ttf 
Indic without Rupee: https://github.com/notofonts/NotoSansOlChiki/tree/master/fonts/ttf/unhinted/instance_ttf

**Comment by felipesanches** [comment]
thanks

**Comment by felipesanches** [comment]
**PASS**
![Screenshot from 2020-07-10 01-43-00](https://user-images.githubusercontent.com/213676/87117538-34aa4380-c24f-11ea-9e23-43f3ea7a0611.png)

**FAIL**, `missing-rupee`
![Screenshot from 2020-07-10 01-42-39](https://user-images.githubusercontent.com/213676/87117568-425fc900-c24f-11ea-905e-3f59771c870d.png)

**SKIP** with non-indic font
![Screenshot from 2020-07-10 01-43-17](https://user-images.githubusercontent.com/213676/87117736-ada99b00-c24f-11ea-9976-eceffd323a20.png)

**Comment by marekjez86** [comment]
Great thank you
