### ISSUE TITLE
New check: Check METADATA.pb category

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#2972]
Just pushed an update to Encode whose category was "SAN_SERIF" when it should've been "SANS_SERIF".

https://github.com/google/fonts/pull/2515

Check should ensure that the METADATA.pb category is one of the following ["MONOSPACE", "SANS_SERIF", "SERIF", "DISPLAY", "HANDWRITING"]

**Comment by felipesanches** [comment]
I'll start with this as a code-test to describe (and enforce) the expected behavior for the proposed new check:

![Screenshot from 2020-07-15 17-43-13](https://user-images.githubusercontent.com/213676/87594012-b15f7680-c6c2-11ea-983d-f3e8e3a10f7d.png)
