### ISSUE TITLE
Accept status code 429 on com.google.fonts/check/metadata/broken_links

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#2974]
<img width="973" alt="Captura de Tela 2020-07-16 às 18 11 34" src="https://user-images.githubusercontent.com/213676/87723322-07e6b680-c790-11ea-926a-85736d83e040.png">

429 = `"too many requests"`

I think this should be considered evidence of a good / live URL, so the check should accept it.

**Comment by graphicore** [comment]
It should maybe also check the same link only once.

**Comment by felipesanches** [comment]
yeah, makes sense!

**Comment by graphicore** [comment]
From [HTTP 429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429):

> A Retry-After header might be included to this response indicating how long to wait before making a new request.

When it checks the same link only once, you could still see if there's a [`Retry-After` Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) and try one more time. But, I'd expect you won't see the 429 any more.

**Comment by felipesanches** [comment]
deduplicating the requests from a given check will make log messages clearer. But may still cause status 429 because a single fontbakery run may invoke the same check up to 18 times (once per style).

I think, in principle, we can accept 429, as "too many requests", means it would have been properly served if requested less often. So we don't need to wait and retry.

**Comment by felipesanches** [comment]
I should add that I do not want to deduplicate URL requests globally as it would mean I'd have to make the check dependent on an external global state. I'd prefer to restrict url deduplication to the single check execution scope.

**Comment by felipesanches** [comment]
This change shoudl also be made to **com.google.fonts/check/description/broken_links**

**Comment by graphicore** [comment]
> means it would have been properly served if requested less often.

That's an assertion that is not explicitly like that in the specification, so it could be interpreted differently by the server implementation.

> I should add that I do not want to deduplicate URL requests globally as it would mean I'd have to make the check dependent on an external global state. I'd prefer to restrict url deduplication to the single check execution scope.

You could put it in an condition, that checks all of the urls and returns a dictionary `{url: result_data}`. That way the scope is global to check runner session but not external.

> make the check dependent on an external global state

That's a big NEVER of course. It will break stuff if you do it in whatever case.

**Comment by graphicore** [comment]
It would be good to have the check once per METADATA.pb file and not once per style. Within that check, you could deduplicate. If you run one check per style, you'll have in multiprocessing cases where you still need to create that condition once per worker, so not much gain there.

**Comment by felipesanches** [comment]
I've double-checked (no pun intended) and both checks run one per family (the metadata one and the description_html one)

**Comment by graphicore** [comment]
> I've double-checked (no pun intended) and both checks run one per family (the metadata one and the description_html one)

I think that's reasonable.
