### ISSUE TITLE
New check: Check VFs do not contain duplicated instances

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#2986]
It seems there's nothing stopping a VF from having duplicate instances.

<img width="228" alt="Screenshot 2020-07-20 at 14 48 39" src="https://user-images.githubusercontent.com/7525512/87945073-230b3c00-ca98-11ea-9fbb-669adc1f7984.png">

We should fail a font if it contains duplicates.

Found in https://github.com/google/fonts/pull/2537#issuecomment-661049627

**Comment by felipesanches** [comment]
I wanted to assign @yanone to this issue but I was not able to. Not sure why.
