### ISSUE TITLE
Can fb METADATA checks compare versions?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2989]
It may be possible to prevent the issue in https://github.com/google/fonts/issues/2559 in fontbakery... Maybe this is more for the dispatcher?

**Comment by graphicore** [comment]
I think Font Bakery should check this.

**Comment by m4rc1e** [comment]
I also recommend that `gftools add-font` can only append new codepages. Atm, it will rewrite them each time the tool is run.

I'll add this functionality this week.

**Comment by davelab6** [comment]
If add font would drop them, it suggests there may be a problem with the font not including the needed glyphs any more?

**Comment by m4rc1e** [comment]
Poppins had no missing devanagari glyphs when compared to the previous release. The issue is that the devanagari subset was added by hand, hence why it got overwritten when we reran add-font on the family.
