### ISSUE TITLE
ERROR in com.google.fonts/check/STAT_strings (universal profile)

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontbakery#2992]
## Observed behaviour

Testing the Commissioner VF in [this PR](https://github.com/google/fonts/pull/2561) results in an ERROR of `com.google.fonts/check/STAT_strings`:

```
    * ERROR: Failed with AttributeError: AxisIndex
           File "/usr/local/lib/python3.7/site-packages/fontbakery/checkrunner.py", line 344, in _exec_check
             for sub_result in result:  # Might raise.
           File "/usr/local/lib/python3.7/site-packages/fontbakery/profiles/universal.py", line 666, in com_google_fonts_check_STAT_strings
             if value.AxisIndex != ital_axis_index: nameIDs.append(value.ValueNameID)
           File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 548, in __getattr__
             raise AttributeError(attr)
```
I played around with it a bit today by adding a `print` statement just before the line in question which checks for `AxisIndex`, which always prints `True`, so I aborted my trials. It's both present and not.

`print(hasattr(value, 'AxisIndex'))`

See https://github.com/yanone/fontbakery/tree/error-in-com_google_fonts_check_STAT_strings for the added print statement.

**Comment by felipesanches** [comment]
This is useful for debugging in scenarios like the one you described:
```python
import ipdb; ipdb.set_trace()
```

note: be sure to `pip install ipdb` (the interactive python debugger)

**Comment by yanone** [comment]
Leads to the same result, `AxisIndex` value is defined and is `0`

**Comment by felipesanches** [comment]
> It's both present and not.

There are 15 values in `ttFont["STAT"].table.AxisValueArray`. The last 3 ones lack `AxisIndex` and that's what was crashing the code.

**Comment by felipesanches** [comment]
I looked more carefully and, by inspecting the font file with ttx, I see that these last 3 entries in the array actually have more than a single axis. For that reason, they lack an AxisIndex. But there are AxisIndices inside AxisValueRecords.

![Screenshot from 2020-07-21 19-27-01](https://user-images.githubusercontent.com/213676/88113434-2da4fe80-cb88-11ea-8647-1cdee9676528.png)
