### ISSUE TITLE
Use Python PEP8 style 4-space indentation

### ISSUE THREAD

**Issue by josh-hadley** [googlefonts/fontbakery#2997]
Change indentation to PEP8 style 4 spaces for consistency across other Python-based font projects (fontTools, AFDKO).

**Comment by felipesanches** [comment]
I am using the `autopep8` module to make the bulk of the work. It is not perfect, but it saves me a lot of time. I'm then reviewing the result and fine-tunning.

**Comment by felipesanches** [comment]
this is the command I'm using:
```autopep8 path/to/file.py --select=E101,E121 --in-place```

**Comment by felipesanches** [comment]
I've also used the `--recursive` flag to apply the changes to the entire codebase.

**Comment by anthrotype** [comment]
I recommend using black autoformatter. It's become the de facto standard, used by many big projects including new modules in the Python standard library.

**Comment by felipesanches** [comment]
I considered using black, but ended up using autopep8 and now I am halfway done. I doubt the tools differ in such a specific purpose (I'm focusing exclusively on 4-spaces indentation in this PR) so I'll finish it with the same tool.

**Comment by felipesanches** [comment]
done! :-D
