### ISSUE TITLE
flake8 mccabe and bugbear 

### ISSUE THREAD

**Issue by josh-hadley** [googlefonts/fontbakery#3000]
Working on #2998 I later discovered that setup.cfg contains a `[flake8]` block (which for some reason was not getting picked up when I ran flake8 locally, even though setup.cfg is one of the places flake8 looks 🤷 ). It is interesting because it `select`s `C` (mccabe) and `B` (bugbear) violation codes, but the CI flake8 check does not invoke `--max-complexity` nor is `flake8-bugbear` included in requirements. Perhaps it was copied/pasted from some other project, or just orphaned in some refactoring.

At any rate, now that #2998 is complete, this block is redundant and should be removed from setup.cfg. If the `C` checks are desired, we should define a suitable `max-complexity` (a quick analysis indicates that the current max of fontbakery code is 32). If `B` checks are desired, [`flake8-bugbear`](https://pypi.org/project/flake8-bugbear/) should be added to `requirements.txt` and possibly to the CI deps list.

**Comment by simoncozens** [comment]
I think this is stale; we don't do this any more - in `.flake8` we `select = E,F,W`.
