### ISSUE TITLE
FB checking for regression with GF when no previous release

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3008]
## Observed behaviour

I have these errors only in ExtraLight styles for all the diff-checks, although the font is not on GF yet.

💔 ERROR The condition FontBakeryCondition:remote_styles had an error: ConnectionError: HTTPConnectionPool(host='fonts.googleapis.com', port=80): Max retries exceeded with url: /css?family=Piazzolla (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x116d75350>: Failed to establish a new connection: [Errno 65] No route to host'))

## Resources and exact process needed to replicate

https://github.com/huertatipografica/piazzolla/issues/9

**Comment by felipesanches** [comment]
at a first glance this looks like bad internet connection

**Comment by RosaWagner** [comment]
Ah haha ! That makes sense since I am lost in country side right now ^^
Thank you, I close this issue then.
