### ISSUE TITLE
Validate METADATA axes values are within gf-axisregistry bounds

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3010]
Sparked from a discussion in https://github.com/googlefonts/gftools/issues/234 I realise that now we have `/axisregistry` within github.com/google/fonts we should have METADATA checks that validate that each range in a METADATA file is registered, and within the bounds of the axis definition.

**Comment by graphicore** [comment]
First things that comes to my mind is that `/axisregistry` is then a dependency of Font Bakery. However, we should not have all of `google/fonts` as a dependency IMHO.

**Comment by felipesanches** [comment]
a fontbakery check can fetch a github URL instead of have the whole repo as a dependency

**Comment by graphicore** [comment]
It will have to fetch a whole directory of files. I'm not a huge fan of all the network requests (not only in this case in each of them). We could perhaps cache files on disk and only fetch when the git hash has changed or when new file was added. That way, it's one GitHub GraphQL query most of the time. Also, remember, if we always do these requests, in multiprocessing the number of requests would multiply by `min(the number of workers, number of fonts)`, in the worst case.

**Comment by davelab6** [comment]
@graphicore it is such a small amount of data, and so slowly changing, that I suggest we simply have a fb developers' script that copies the files into the fb tree, and run it as part of the release process to check that there is no diff, so it is updated at least as often as FB releases happen. I could even see the script could convert the textproto files into python dictionary per file within a fb source code tree subfolder, so its more pythonic. 

https://github.com/google/fonts/pull/2577#issuecomment-669502406 is a real world example of where we needed such checks :)

**Comment by davelab6** [comment]
We could also mirror it to a new github.com/googlefonts/gf-axisregistry repo, if you prefer

**Comment by graphicore** [comment]
> it is such a small amount of data, and so slowly changing, that I suggest we simply have a fb developers' script that copies the files into the fb tree,

That's good enough for me. Very similar to `fontbakery-microsoft-vendorlist.cache` as well.

> I could even see the script could convert the textproto files into python dictionary per file within a fb source code tree subfolder, so its more pythonic.

I don't think we need that.

> We could also mirror it to a new github.com/googlefonts/gf-axisregistry repo, if you prefer

Overkill.

**Comment by felipesanches** [comment]
ok, I can do it. ;-)

**Comment by felipesanches** [comment]
I also agree with the approach proposed by Dave

**Comment by m4rc1e** [comment]
Axis metadata also exists in http://fonts.google.com/metadata/fonts. Why not just cache this like we do for the vendors list?

**Comment by felipesanches** [comment]
agreed!

**Comment by graphicore** [comment]
About that API endpoint  http://fonts.google.com/metadata/fonts: 

It's "JSON" begins with `)]}'` did anyone tell that to the devs ever? I've seen something like a `json_string[4:]` hack somwhere.

**Comment by felipesanches** [comment]
yeah, I mentioned that on a conversation with @m4rc1e a couple weeks ago. Not sure why they do that.

**Comment by m4rc1e** [comment]
maybe to stop bots from parsing it?

**Comment by graphicore** [comment]
> maybe to stop bots from parsing it?

That should be handled differently, with authorization, e.g. via the API keys system.
