### ISSUE TITLE
New GF Checks: Ensure VFs conform to GF axis registry

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#3022]
So we've now got a [Google Fonts axis registry](https://github.com/google/fonts/tree/master/axisregistry). We need to make sure that variable fonts intended for Google Fonts follow it, otherwise the fonts won't get pushed.

Off the top of my head, we can use it to make the following checks:

- Flag a WARN if a VF includes an axis which is not part of the registry
- Check VF's axes ranges are within the allowed ranges specified in each axis registry.
- Check that instance/STAT particle names match the fallback names in each axis registry.

Nate may move the axis registry to its own repo. We can then submodule it in this repo and google/fonts.

**Comment by davelab6** [comment]
Those 3 checks are good and should FAIL not WARN.

**Comment by felipesanches** [comment]
@davelab6, one of the checks here was also suggested at #3010, and was implemented as **com.google.fonts/check/metadata/gf-axisregistry_valid_tags** "VF axis tags are registered on GF Axis Registry" on PR #3050 

Another one, **com.google.fonts/check/metadata/gf-axisregistry_bounds** "VF axes have ranges compliant to the bounds specified on the GF Axis Registry", was also added in that same PR that I have just merged.

Now we still have to work on the third one, which I'll probably call **com.google.fonts/check/STAT/gf-axisregistry_names**

**Comment by felipesanches** [comment]
@m4rc1e I need some feedback from you to make sure the current implementation at the pull request #3056 is indeed what you expected. Please reassign the issue to me if you approve that implementation, so that I can implement the code-test and then merge it.

**Comment by felipesanches** [comment]
In particular, I have this question:

"Check that instance/STAT particle names match the fallback names in each axis registry"
Should only names of axis coordinates match the registry? Or should we also enforce their values?

In my initial implementation I check for both things.

**Comment by davelab6** [comment]
@felipesanches is https://github.com/google/fonts/issues/2772 prevented by the latest FB?

**Comment by yanone** [comment]
Positive, I just checked.
