### ISSUE TITLE
Add vf check for name id 25

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3024]
https://typedrawers.com/discussion/comment/48638/#Comment_48638
https://adobe-type-tools.github.io/font-tech-notes/pdfs/5902.AdobePSNameGeneration.pdf

**Should be triggered if "Italic" is part of the file name, or `NameID2`, or `NameID17`.**
The ticked cases indicates where you can already find it.

### `Name ID25` is present and "Italic" is appended to the family name (without space)
Adobe recommend the presence of `name ID 25` in all variable fonts. We found out it is actually necessary to allow style linking between Upright and Italic variable fonts. According to their documentation, this should be the Font Family Name only. Although, it seems that a bug in Indesign forces us to append "Italic" in the `name ID 25` to be able to use properly the fonts. See issue: https://github.com/googlefonts/gftools/issues/297 for more debate on the subject.

This should be a WARN cause comes from a bug in Adobe Indesign, this is controversy but GF tries to enforce it to avoid complains until this bug is resolved. We should check regularly if it got resolved btw, in February 2022 it was not.

**Profile**
- [ ] in google-font profile
- ~in universal profile~
- ~in opentype profile~

**Format**
- [ ] in VF check
- ~in static check~

**Comment by eliheuer** [comment]
I assigned this to myself because I would like to try looking into this.

**Comment by felipesanches** [comment]
I presume you've not been dealing with this lately, @eliheuer

**Comment by eliheuer** [comment]
Yes, I got busy. I moved this to my personal to-do list just in case no one else gets to it soon and I have time.

**Comment by arrowtype** [comment]
This is still an issue in Illustrator, as of Illustrator 2024, v28.4.1 (the latest version as of April 26, 2024).
