### ISSUE TITLE
Fix the CI!

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontbakery#3026]
## Observed behaviour

CI tests are currently failing on `test_check_vertical_metrics_regressions` in `tests/profiles/googlefonts_test.py`

## Expected behaviour

CI tests should pass so we have confidence about new PRs.

## Resources and exact process needed to replicate

More interesting question is why it is failing. `test_check_vertical_metrics_regressions` runs a test "with a remote family which does not have typo metrics enabled and the fonts being checked don't take this fact into consideration". In this case, the test family *has* the typo metrics bit set and the remote family (Cabin) *does not*:

```Python
>>> typo_metrics_enabled(gf_font)
False
```

`gf_has_typo_metrics` is False and `fam_has_typo_metrics` is True, so we pick up the expected ascender from `usWinAscent`:

https://github.com/googlefonts/fontbakery/blob/9bbf2da4947b7e5ce82c06a8ce7b484185ddac67/Lib/fontbakery/profiles/googlefonts.py#L4444-L4450

``gf_font['OS/2'].usWinAscent * upm_scale`` (for Cabin Regular) is 1150:

```Python
>>> ttFonts[0]['head'].unitsPerEm
1000
>>> gf_font['head'].unitsPerEm
2000
>>> upm_scale
0.5
>>> gf_font['OS/2'].usWinAscent
2300
>>> gf_font['OS/2'].usWinAscent * upm_scale
1150.0
```

However, our test has set the ascender to 1139:

https://github.com/googlefonts/fontbakery/blob/9bbf2da4947b7e5ce82c06a8ce7b484185ddac67/tests/profiles/googlefonts_test.py#L3386-L3387

Hence the test fails.

I guess the fix is to change the test font's ascender to 1150? But I am not really aware of the subtleties of what is going on here.

**Comment by m4rc1e** [comment]
@simoncozens thanks for catching this. I'm guessing this check is failing because we recently updated Cabin on Google Fonts with a new VF. I reckon this update has typo metrics enabled.

**Comment by m4rc1e** [comment]
By recently I mean a few hours ago.

Perhaps a better option for this test is to create a mock of the remote_styles  instead of sending a network request.

**Comment by felipesanches** [comment]
yes, I noticed that yesterday at night while working on a branch. I simply commented out a portion of the code-test, which is a dirty work around. Would you be able to make a better fix for that, @m4rc1e? (I'm asking you because this check was originally implemented by you, if I recall correctly)

**Comment by simoncozens** [comment]
Even if the update has typo metrics enabled, note that we explicitly disable them in the tests:

https://github.com/googlefonts/fontbakery/blob/master/tests/profiles/googlefonts_test.py#L3377-L3378

It's not that; it's just that the metrics really are different.
