### ISSUE TITLE
Add check for collisions via collidoscope 

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3032]
## Observed behaviour

https://github.com/simoncozens/collidoscope exists, but we don't use it. 

## Expected behaviour

We detect collisions and WARN, by taking the Unicodes supported in a font and running collidoscope on that unicode range on that font.

**Comment by simoncozens** [comment]
I have this implemented locally, and in the Qalam repository. Will submit a PR.

**Comment by felipesanches** [comment]
thanks! :-)

**Comment by simoncozens** [comment]
This is done, through the opentype shaping checks.

**Comment by felipesanches** [comment]
thanks, @simoncozens
