### ISSUE TITLE
Log messages should be normalized

### ISSUE THREAD

**Issue by DavidRaymond** [googlefonts/fontbakery#3038]
## Observed behaviour

For some checks, with the same ttf files, the log messages write lists of items in different orders.  This makes comparing results from subsequent runs using a diff tool difficult.

For example, with the com.google.fonts/check/required_tables check, two runs can produce different INFO messages, eg
```
   * INFO: This font contains the following optional tables [GSUB, GPOS, loca]
   * INFO: This font contains the following optional tables [GPOS, loca, GSUB]
```

## Expected behaviour

Lists in log messages should be sorted so, unless the font or check has changes, there should be no difference in the message.

I regularly run Font Bakery against 24 different font projects to identify if either changes to fonts or new versions of Font Bakery have changed the results, and the current code produces false positives.

## Resources and exact process needed to replicate

- Download the ttf fonts from [github.com/silnrsi/font-alkalami/releases/tag/v1.200](https://github.com/silnrsi/font-alkalami/releases/tag/v1.200)
- Run
 - - `fontbakery check-googlefonts -c com.google.fonts/check/required_tables Alkalami-Regular.ttf ../Temp/Alkalami-Light.ttf`
 - - `fontbakery check-googlefonts -c com.google.fonts/check/required_tables Alkalami-Regular.ttf`
- The INFO messages for the regular font may be different

(I say "may" since it could depend on other environmental factors like Python version or Font Bakery version)

## Notes

With the required_tables check, changing
```
        yield INFO, ("This font contains the following"
                     " optional tables [{}]").format(", ".join(optional_tables))
```
to
```
        yield INFO, ("This font contains the following"
                     " optional tables [{}]").format(", ".join(sorted(optional_tables)))
```
resolves the issue.

I've seen the same issue with `com.google.fonts/check/production_glyphs_similarity` and other checks in the past that I don't have a note of.

**Comment by felipesanches** [comment]
That's interesting! The reason for this behaviour comes from the fact that iterating a python set results in arbitrary ordering. So, there's no guarantee that successive runs will result in the same ordering.

I agree with you that this is problematic, so I will address it by using a list instead of a set.

**Comment by felipesanches** [comment]
I've addressed the problem in a few checks. Maybe there could be more cases. Please open new issues if you find any other case of this kind of problem.

Cheers!
