### ISSUE TITLE
Document code style requirements

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3039]
## Observed behaviour

In https://github.com/googlefonts/fontbakery/pull/3017#pullrequestreview-466916851 @felipesanches asked for some code style changes, with a detailed explanation. 

## Expected behaviour

It would be good to document these, perhaps in https://font-bakery.readthedocs.io/en/stable/developer/source-contrib-guide.html ?

**Comment by felipesanches** [comment]
thanks, Dave!

**Comment by madig** [comment]
Even if noone wants to hear this, the best solution is to use https://pypi.org/project/black/ and never worry about something as silly as code style ever again.

**Comment by simoncozens** [comment]
We now use black and have a linter, so there is now feedback for PR submitters on code style.
