### ISSUE TITLE
 Fontbakery 0.7.30 FATAL ERROR when --ghmarkdown used

### ISSUE THREAD

**Issue by bghryct** [googlefonts/fontbakery#3044]
## Fontbakery 0.7.30 FATAL ERROR when --ghmarkdown used

when I run 
``` fontbakery check-googlefonts ./source/vf/*.ttf --dark-theme --ghmarkdown jost_problems.md ```

on the ttf below 

[jost[slnt,wght].ttf.zip](https://github.com/googlefonts/fontbakery/files/5285576/jost.slnt.wght.ttf.zip)

I get 

``` FATAL ERROR: The rationale metadata on 'com.google.fonts/check/metadata/includes_production_subsets' must be indented by 8 spaces! ```

## Expected behaviour

I expected to get a .md file with my checks. 

## Resources and exact process needed to replicate

Resources are in the above .ttf

furthermore I'm in a venv 
and here's what's in it

```
Package            Version
------------------ ------------
absl-py            0.10.0
appdirs            1.4.4
attrs              20.2.0
beautifulsoup4     4.9.1
cached-property    1.5.2
certifi            2020.6.20
cffi               1.14.3
chardet            3.0.4
click              7.1.2
commandlines       0.4.1
defcon             0.7.2
Deprecated         1.2.10
Flask              1.1.2
font-v             1.0.3
fontbakery         0.7.30
fonttools          4.15.0
fs                 2.4.11
gftools            0.4.3
gitdb              4.0.5
GitPython          3.1.8
glyphsLib          5.2.0
idna               2.10
itsdangerous       1.1.0
Jinja2             2.11.2
lxml               4.5.2
MarkupSafe         1.1.1
opentype-sanitizer 8.0.0.post2
Pillow             7.2.0
pip                20.2.3
pip-api            0.0.14
protobuf           3.13.0
pycparser          2.20
pygit2             1.3.0
PyGithub           1.53
PyJWT              1.7.1
pyparsing          2.4.7
python-dateutil    2.8.1
pytz               2020.1
requests           2.24.0
ruamel.yaml        0.16.12
ruamel.yaml.clib   0.2.2
setuptools         41.2.0
six                1.15.0
smmap              3.0.4
soupsieve          2.0.1
strictyaml         1.1.0
tabulate           0.8.7
ttfautohint-py     0.4.3
typing-extensions  3.7.4.3
ufoLib2            0.8.0
ufolint            1.0.1
unicodedata2       13.0.0.post2
Unidecode          1.1.1
urllib3            1.25.10
vttLib             0.9.1.post2
Werkzeug           1.0.1
wrapt              1.12.1
```

**Comment by bghryct** [comment]
I should clarify, I don't receive this error, when running only:

```fontbakery check-googlefonts ./source/vf/*.ttf --dark-theme```

**Comment by felipesanches** [comment]
Please install fontbakery from git and ensure the problem is properly fixed. I will make a new release right after you confirm all is good. Otherwise, I'll address anything else you find.

**Comment by felipesanches** [comment]
in order to install form git, clone the repo and then do:
```
virtualenv venv -ppython3
. venv/bin/activate
pip install -e .```

(there's a dot in the end of the last command!)

**Comment by felipesanches** [comment]
you know what? The FATAL ERROR message is maybe a dumb idea. I think I have a better approach for this. I will remove that runtime check now and later add a more robust routine to validate this in our test-suite.

**Comment by felipesanches** [comment]
OK, after some minor confusion I completely deleted the FATAIL ERROR runtime test.

Please update you local copy of git master and re-test the program. If you still have the problem, then it is poltergeist! LOL

**Comment by bghryct** [comment]
will do, brb

**Comment by felipesanches** [comment]
great!

**Comment by felipesanches** [comment]
https://pypi.org/project/fontbakery/0.7.31/
