### ISSUE TITLE
Add Check for VF Axis Order

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3049]
As per https://github.com/google/fonts/issues/2702#issuecomment-702163538 when the GF axis registry has a axis order defined, we'll need to check all the STAT tables to make sure they match in order.

**Comment by felipesanches** [comment]
This is the current status of the entire Google Fonts collection:

<img width="645" alt="Captura de Tela 2020-10-23 às 02 46 31" src="https://user-images.githubusercontent.com/213676/96963582-3f77a400-14df-11eb-8b11-d814b4e788be.png">
