### ISSUE TITLE
Does Travis / tox use the dependency versions declared at requirements.txt? Or does it install the latest versions of each package instead? 

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3058]
At pull request #3057, I noticed that an unrelated opentype-sanitizer code-test was failing:

The Python wrapper for ots has just been updated by @anthrotype and it seems that Travis may have installed the newer version when running the build for that PR. This should not happen. Travis should be setup to install a manually pinned version of all our dependencies.

**Comment by chrissimpkins** [comment]
I believe that tox installs from setup.py defs by default.  It looks like you can specify a requirements.txt file with the [`install_command` configuration](https://tox.readthedocs.io/en/latest/config.html#conf-install_command).  The most straightforward approach may be to abandon tox in the CI and just use the Travis Python runner env with pip install and pytest commands.

**Comment by felipesanches** [comment]
I like using tox because it enables me to run locally the same thing that runs on Travis, so my intention is to keep it.

**Comment by anthrotype** [comment]
If you want to have tox install from requirements.txt you simply need to tell it to do so, by adding `-rrequirements.txt` to the list of `deps`

**Comment by anthrotype** [comment]
Yes, like Felipe just did 👌
