### ISSUE TITLE
Add check for outline glitches

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3064]
## Observed behaviour

https://github.com/googlefonts/noto-source/issues/245 has an outline glitch

## Expected behaviour

I wonder if there is some way to detect it.

**Comment by simoncozens** [comment]
It’s going to be very difficult to distinguish a cut like that from an ink trap.

**Comment by simoncozens** [comment]
Here’s an idea: take every pair of successive segments and treat them as a sub path. Close the sub path with a line segment and calculate the area. If the area is less than epsilon, there is a glitch.

**Comment by kalapi** [comment]
FontBakery v0.12.9

I'm getting a lot of false positives on the `com.google.fonts/check/outline_jaggy_segments` check. In very large families double checking all the warnings to ensure if any are actually affecting output can become very cumbersome and time consuming. Is there a way we can make this algorithm more efficient?

The algorithm in its current state might flag mild to extreme condensed designs.

Some examples:

> ⚠️ **WARN** The following glyphs have jaggy segments:
> * M (U+004D): L<<276.0,86.0>--<163.0,592.0>>/L<<163.0,592.0>--<163.0,143.0>> = 12.588740511051117
> * M (U+004D): L<<584.0,143.0>--<584.0,592.0>>/L<<584.0,592.0>--<443.0,0.0>> = 13.396859158897033
> * trademark (U+2122): L<<586.0,400.0>--<519.0,664.0>>/L<<519.0,664.0>--<519.0,434.0>> = 14.2403237429406

Warning 1 'M': is related to the selected segments in the image below:

<img src="https://github.com/user-attachments/assets/41c0c648-450d-49ab-98e7-ccc7897fb2cd" width="400">

Warning 2 'M': is related to the selected segments in the image below:

<img src="https://github.com/user-attachments/assets/0128ba6d-1656-4ebb-b87a-d3c9ccccc7c4" width="400">

Warning 3 'trademark': is related to the selected segments in the image below:

<img src="https://github.com/user-attachments/assets/408df541-4ce6-4cbd-b59d-32caaa7208d6" width="400">
