### ISSUE TITLE
Crash with permissions error

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontbakery#3070]
## Observed behaviour

fontbakery hangs indefinitely after the final check ("Font contains unique glyph names") when called from Python

## Expected behaviour

fontbakery should correctly finish.

## Resources and exact process needed to replicate

When running https://github.com/simoncozens/fontbakery-ui/tree/c2c923 on Ubuntu Linux, the progress bar gets to 100% but the `distribute_generator` call never terminates. Confirmed by placing print statements before and after the call to `distribute_generator`.

**Comment by simoncozens** [comment]
OK, it's weirder than that. It's not hanging, but terminating *if* it can't write to the directory where the font lives. So this:

```
from fontbakery.checkrunner import (
    get_module_profile,
    CheckRunner,
    distribute_generator,
)
from fontbakery.commands.check_profile import get_module, log_levels
from fontbakery.reporters.html import HTMLReporter

paths = ["/usr/share/fonts/truetype/mononoki/mononoki-Bold.ttf"]
loglevels = [log_levels["INFO"]]

profile = get_module_profile(
    get_module("fontbakery.profiles.googlefonts")
)
runner = CheckRunner(profile, values={"fonts": paths})
hr = HTMLReporter(runner=runner, loglevels=loglevels)
reporters = [hr.receive]
status_generator = runner.run()
print("Starting")
distribute_generator(status_generator, reporters)
print("Done")
```

says "Starting" and then *exits*, with no exception/error message. But replace the path with something where the user can write to, and it works fine.

**Comment by graphicore** [comment]
I just found one case where Font Bakery creates a file where it should not in the universal profile `com.google.fonts/check/ttx-roundtrip`:

https://github.com/googlefonts/fontbakery/blob/0e672ee0bbb56311794d7bff57ff26d272938625/Lib/fontbakery/profiles/universal.py#L836-L838

Maybe that's related, in any case, I strongly believe Font Bakery should not just write to disk, using the `tempfile` module instead.

**Comment by graphicore** [comment]
When you try the `opentype` profile it should work, as that profile does not include `universal`, which e.g. `googlefonts` includes. As a side note: the `universal` profile should also be selectable in the ui.

**Comment by simoncozens** [comment]
We now do use tempfile, so I'm guessing this is now OK.
