### ISSUE TITLE
GPOS kerning test does not check if the font is monospaced

### ISSUE THREAD

**Issue by aaronbell** [googlefonts/fontbakery#3072]
## Observed behaviour

⚠ WARN: Does GPOS table have kerning information?
com.google.fonts/check/gposkerninginfo

⚠ WARN GPOS table lacks kerning information. [code: lacks-kern-info]

## Expected behaviour

Given that the font (Cascadia Code) is a monospaced font, I wouldn't expect that the warning should appear. 

## Resources and exact process needed to replicate

https://github.com/microsoft/cascadia-code/releases/tag/v2009.22

**Comment by aaronbell** [comment]
Covered by #2674

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/fontbakery/pull/3074
