### ISSUE TITLE
For CJK fonts, sTypoAscender and hhea ascent will not match

### ISSUE THREAD

**Issue by aaronbell** [googlefonts/fontbakery#3078]
## Observed behaviour

I'm running fontbakery on a CJK project that follows [Google's specifications regarding vertical metrics for CJK fonts](https://github.com/googlefonts/gf-docs/tree/master/Spec#cjk-vertical-metrics) wherein the sTypo metrics and hhea metrics do not align. 

Here is the exact specification:

Attrib | Value | Example using 1000upm font
-- | -- | --
OS/2.sTypoAscender | 0.88 * font upm | 880
OS/2.sTypoDescender | -0.12 * font upm | -120
OS/2.sTypoLineGap | 0 | 0
hhea.ascender | Set to look comfortable (~1.16 * upm) | 1160
hhea.descender | Set to look comfortable (~0.288 * upm) | -288
hhea.lineGap | 0 | 0
OS/2.usWinAscent | Same as hhea.ascent | 1160
OS/2.usWinDescent | abs(value) of hhea.descent | 288
OS/2.fsSelection bit 7 | Do not set |  

 For fonts that include CJK characters, the above vertical metrics should be recommended.

**Comment by davelab6** [comment]
Please could you explain why the CJK metrics should be different to the default metrics?

**Comment by aaronbell** [comment]
You mean the metrics defined for not CJK fonts? The specification explains things were set this way based on the work for the Noto project.
