### ISSUE TITLE
Add check: profile paths are valid (fail if not)

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3083]
@rsheeter asked,

> John Hudsons designer pb gives the wrong filename and is blocking the dev push. Hopefully fixed in https://github.com/google/fonts/commit/2064c5162c40a4131073c344e83bd8ec3243fb21 Can we add confirmation that the image paths are valid?

Should fail if not. 

Also, castoro introduced jpg profile images; add a check to warn if not png.

I suggest, maybe we could do a one off tool to do a conversion, optipng/optijpg pass, and then filesize comparison, and tell us if the jpeg is larger or smaller than the png.

**Comment by felipesanches** [comment]
I'm working on this check today. I feel that we lack an easy way to map a font project METADATA.pb to its designer entries on the catalog. A naive approach could be to get each of the designer names from the METADATA.pb `designer` field and remove spaces, convert to all lowercase and remove diacritics (restricting it to 7-bit ASCII) and then lookup the catalog trying to find a directory with that name.

A better approach would be to actually have entries on METADATA.pb pointing to the entries of the designers catalog.

**Comment by felipesanches** [comment]
@davelab6 Are only PNGs allowed? Or whatever image file format has the smallest file size? What's the policy and why?

**Comment by felipesanches** [comment]
this was included in FB v0.7.32
