### ISSUE TITLE
Fontbakery not identifying .notdef as first glyph when it is

### ISSUE THREAD

**Issue by aaronbell** [googlefonts/fontbakery#3086]
Receiving this bug:

⚠ WARN: Font contains .notdef as first glyph?
com.google.fonts/check/mandatory_glyphs
--- Rationale ---
The OpenType specification v1.8.2 recommends that the first glyph is the .notdef glyph without a codepoint assigned and with a drawing.

https://docs.microsoft.com/en-us/typography/opentype/spec /recom#glyph-0-the-notdef-glyph

Pre-v1.8, it was recommended that a font should also contain a .null, CR and space glyph. This might have been relevant for applications on MacOS 9.

⚠ WARN Font should contain the .notdef glyph as the first glyph, it should not have a Unicode value assigned and should contain a drawing.

However, when opening the font, it is the first glyph:
<img width="475" alt="Screen Shot 2020-11-06 at 11 43 57 AM" src="https://user-images.githubusercontent.com/8460297/98407983-64aefb00-2025-11eb-9a22-949077e8074d.png">

And here is the font file:
[HachiMaruPop-Regular.ttf.zip](https://github.com/googlefonts/fontbakery/files/5503159/HachiMaruPop-Regular.ttf.zip)

**Comment by felipesanches** [comment]
ok, I am reviewing this check and it looks good. The problem with this font file is that its .notdef glyph is empty. The OpenType specification v1.8.2 recommends that it should contain some drawing.

I am now updating the check implementation to emit more precise WARN messages explicitely describing which of the criteria was not met. (the check evaluates 3 different requirements)

**Comment by felipesanches** [comment]
in other words, the way FontBakery was reporting a problem was not clear enough and gave you the wrong impression that FB thought .notdef was not the first glyph. But in reality the real offender was the lack of ink on it.

**Comment by aaronbell** [comment]
Thanks for the clarification! I'll add ink to those glyphs.
