### ISSUE TITLE
Framework for grouping related tests

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontbakery#3087]
#3064 got me thinking. There are various path tests we could do - outline glitches, colinear points, short segments, etc. - but currently each test will need to do the same work of looping over all the glyphs, dividing them into segments, etc. This is inefficient. It would be nice if there was a way that a test could do the loop once, set up the segments for each glyph, and then inside the loop, call a list of subtests to do the checking. I don’t know the architecture too well but there may be similar gains in eg source level tests as we open and parse the source once and do the subtests together instead of parsing the source independently for each tests.

**Comment by graphicore** [comment]
look at `@condition` the return value is cached and reused for each check/condition that has it as its argument. You would gather high level information in a structure e.g. a dict and have the checks just report/interprete what you found. You could even put the check status + message into the structure and have different checks pick which statuses to yield, so the actual implementation is in the @condition and possibly in other functions you call from there.

**Comment by graphicore** [comment]
> as we open and parse the source once and do the subtests together instead of parsing the source independently for each tests.

That's exactly what the `@condition` `ttFont` is doing, though I have seen some calls of `ttFont(font)` in the wild, which is definitely not supposed to happen.

**Comment by graphicore** [comment]
https://github.com/googlefonts/fontbakery/blob/3fb45d1fe619a94da5ba5a0a4a5a334e1416113b/Lib/fontbakery/profiles/shared_conditions.py#L10-L13

**Comment by graphicore** [comment]
I just recall, in the `cff` profile is a good example of an `@condition` called `cff_analysis` which behaves similar to what I have in mind. It produces an `analysis` structure and that is shared in several checks to produce reports, it also calls its own sub-routines: 

https://github.com/googlefonts/fontbakery/blob/3fb45d1fe619a94da5ba5a0a4a5a334e1416113b/Lib/fontbakery/profiles/cff.py#L101-L135

**Comment by simoncozens** [comment]
OK, that's nice. I can maybe read all the glyph contours into a data structure and share that.
