### ISSUE TITLE
Failing on Localized Name table 

### ISSUE THREAD

**Issue by aaronbell** [googlefonts/fontbakery#3089]
## Observed behaviour

🔥 FAIL: Check name table: FONTFAMILYNAME entries.
com.google.fonts/check/name/familyname
--- Rationale ---
Checks that the family name infered from the font filename matches the string at nameID 1 (NAMEIDFONTFAMILY_NAME) if it conforms to RIBBI and otherwise checks that nameID 1 is the family name + the style name.

🔥 FAIL Entry [FONTFAMILYNAME(1):MACINTOSH(1)] on the "name" table: Expected "Shippori Antique B1" but got "しっぽりアンチックB1". [code: mismatch]
🔥 FAIL Entry [FONTFAMILYNAME(1):WINDOWS(3)] on the "name" table: Expected "Shippori Antique B1" but got "しっぽりアンチックB1". [code: mismatch]

The failing is happening on languageID 11, nameID 1.

## Expected behaviour

Font Bakery shouldn't be doing checks on the localized names compared to English names. 

## Resources and exact process needed to replicate

Sample font that shows the error. 
[ShipporiAntique-Regular.ttf.zip](https://github.com/googlefonts/fontbakery/files/5533889/ShipporiAntique-Regular.ttf.zip)

**Comment by davelab6** [comment]
In https://github.com/google/fonts/pull/2903 this came up again; there is a false FAIL about the name table containing Kana characters for `com.google.fonts/check/name/familyname`
