### ISSUE TITLE
Most elegant way of overriding existing conditions?

### ISSUE THREAD

**Issue by madig** [googlefonts/fontbakery#3098]
Somewhere between 0.7.31 and 0.7.33, some conditions like `is_italic` were moved to `shared_conditions.py`. Now Google Sans' CI QA action errors out because it defines those conditions itself in its own profile.

## Observed behaviour

```
[...]
   File "qa/check-googlesans.py", line 384, in <module>
    profile.auto_register(globals())
[...]
fontbakery.checkrunner.NamespaceError: Name "is_italic" is already registered in "conditions" (value: <FontBakeryCondition:is_italic>). Requested registering in "conditions" (value: <FontBakeryCondition:is_italic>).
```

## Expected behaviour

Conditions overwrite existing ones if told to do so.

## Resources and exact process needed to replicate

See Google Sans CI status.

**Comment by graphicore** [comment]
Use the `force` ;-)

It's even documented somehow: https://font-bakery.readthedocs.io/en/stable/developer/writing-profiles.html#explicit-namespace-overrides-force-true

> #### Explicit Namespace Overrides `force=True`
>
>In order to make it possible to create checks and conditions that depend on values unknown in advance, it is possible to forcefully override certain namespace entries with a later definition. For this `FontBakeryCondition` and `FontBakeryExpected` value have an `force=True` optional parameter and for the other namespace types `profile.add_to_namespace` can be used directly, which provides the same parameter. *Just don't over do it and take care of namspace clashes carefully!*

So, e.g.:

```
@condition(force=True)
def is_italic(ttFont):
    return random() > 0.5
```

**Comment by madig** [comment]
Ah! Kthx, didn't grep for `force` :o
