### ISSUE TITLE
Static subdirectory could be a WARN instead of FAIL

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3099]
Since we actually don't need the static ttf unless they are manually hinted, this check could be downgraded to WARN.
Do @m4rc1e and/or @davelab6 agree and confirm ?

`🔥 FAIL: A static fonts directory with at least two fonts must accompany variable fonts`
[com.google.fonts/check/repo/vf_has_static_fonts](url)

**Comment by felipesanches** [comment]
This is super-quick to implement, but I will wait for @davelab6 or @m4rc1e to answer Rosalie's question.

**Comment by felipesanches** [comment]
Should we completely deprecate this check? Or should we just make it a WARN-level one?

**Comment by felipesanches** [comment]
I've just downgraded the check to WARN-level. There's still a FAIL message in there for the case when a static folder is empty (it should be deleted or font files should be included in it).

I am closing this issue, but I also noticed that the rationale for this check does not seem to be precise. It currently reads as:
```
Variable font family directories kept in the google/fonts git repo may include a static/ subdir containing static fonts.
        These files are meant to be served for users that still lack support for variable fonts in their web browsers.
```

If you think it could be improved, please let me know and I can update the text.

**Comment by RosaWagner** [comment]
From what I understood from Dave, we would just need the tt hinting program from it, if it has been done manually

**Comment by felipesanches** [comment]
so would it be accurate if I rephrased the rationale text like this?

```
These files are meant to preserve the hints of font files that were manually hinted.
```

**Comment by RosaWagner** [comment]
I think it's perfect :) Marc confirmed at the meeting last friday, so I guess we are all good.
