### ISSUE TITLE
Bug in check com.google.fonts/check/STAT/gf-axisregistry

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery#3106]
## Observed behaviour

The following ERROR has been reported in the latest test I've performed running the `googlefonts` profile

<details>
<summary>💔 <b>ERROR:</b> Validate STAT particle names and values match the fallback names in GFAxisRegistry. </summary>

* [com.google.fonts/check/STAT/gf-axisregistry](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/STAT/gf-axisregistry)
<pre>--- Rationale ---

Check that particle names and values on STAT table match the fallback names in
each axis registry at the Google Fonts Axis Registry, available at
https://github.com/google/fonts/tree/master/axisregistry

</pre>

* 💔 **ERROR** Failed with AttributeError: AxisIndex

</details>

## Resources and exact process needed to replicate

Full reports and fon tiles:
[Sofia Sans](https://github.com/vv-monsalve/Sofia-Sans/tree/QA-Sofia/fonts/ttf)
[Big Shoulders](https://github.com/vv-monsalve/big_shoulders/tree/QA-BigShoulders/fonts/variable)

**Comment by felipesanches** [comment]
@vv-monsalve, I was not able to replicate these ERRORs by running fontbakery agains the ttf files in those branches of Sofia Sans and Big Shoulders from your repo. It is working ok for me.

Do you have a link to the Travis (or GHAction) build that has the ERRORs?

**Comment by vv-monsalve** [comment]
@felipesanches, sorry it was the wrong resources to replicate. This is the one:
[Geologica[SHRP,ital,slnt,wght].ttf.zip](https://github.com/googlefonts/fontbakery/files/5638673/Geologica.SHRP.ital.slnt.wght.ttf.zip)

Whit those same sources I got another Error for `com.google.fonts/check/metadata/consistentaxisenumeration` but probably you already got it if you replicate the process. If not, please tell me so that I open a new issue for it.

**Comment by felipesanches** [comment]
ok, the issue is that the check does not yet support STAT table Format 4. I'll have to look at it more carefully to propaerly understand the table variant and then to correctly implement support for that format.

**Comment by vv-monsalve** [comment]
I see, thanks for the explanation.

> Whit those same fonts I got another Error for `com.google.fonts/check/metadata/consistentaxisenumeration` but probably you already got it if you replicated the process. If not, please tell me so that I open a new issue for it.

And did you get to see this one in the report for Big Shoulders and Sofia Sans? Do I open a new Issue for it or do you have it already covered?

**Comment by felipesanches** [comment]
please report the other problem

**Comment by vv-monsalve** [comment]
Done in https://github.com/googlefonts/fontbakery/issues/3122

**Comment by felipesanches** [comment]
thanks
