### ISSUE TITLE
Improve rationale or change title for com.google.fonts/check/varfont/unsupported_axes

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery#3108]
## Observed behaviour

When reporting the Fail in Geologisk @kosbarts pointed out:

> Btw, I think the text for the FAIL report re ital axis should be updated. Description says "... do not contain slnt or ital axes" but Rationale talks about "ital" and "opsz".

<details>
<summary>🔥 <b>FAIL:</b> Ensure VFs do not contain slnt or ital axes. </summary>

* [com.google.fonts/check/varfont/unsupported_axes](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont/unsupported_axes)
<pre>--- Rationale ---

The &#x27;ital&#x27; axis is not supported yet in Google Chrome. The &#x27;opsz&#x27; axis also has
patchy support.

For the time being, we need to ensure that VFs do not contain either of these
axes. Once browser support is better, we can deprecate this check.

For more info regarding ital and opsz browser support, see:
https://arrowtype.github.io/vf-slnt-test/

</pre>

* 🔥 **FAIL** The "ital" axis is not yet well supported on Google Chrome. [code: unsupported-ital]

</details>

## Expected behaviour

If Slant axis is still not fully supported, the rationale would need to include information about it, otherwise, the axis should not be included in the Fail

**Comment by felipesanches** [comment]
The check had been updated on PR #2933 but the old rationale was kept (by our mistake) which led to this confusion.
Based on https://github.com/googlefonts/fontbakery/issues/2866#issuecomment-633864875 I am now updating the rationale text as well.
