### ISSUE TITLE
Fontbakery should recognize "GOOG" OS/2 vendor ID

### ISSUE THREAD

**Issue by tphinney** [googlefonts/fontbakery#3113]
Seems like the vendor IDs are not getting updated as often as they should be?

## Observed behaviour

    * WARN: OS/2 VendorID value 'GOOG' is not yet recognized. If you registered it recently, then it's safe to ignore this warning message. Otherwise, you should set it to your own unique 4 character code, and register it with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx
 [code: unknown]

Note: the URL above redirects to: https://docs.microsoft.com/en-us/typography/vendors/ where "GOOG" has been listed for Google for some time now.

## Expected behaviour

Fontbakery should recognize Google

## Resources and exact process needed to replicate

Change any font's vendor ID to GOOG (or presumably if you run Noto through Fontbakery)

**Comment by graphicore** [comment]
I think I saw the same recently with "GRCR" (Graphicore). Shame on me I did not file an issue.

**Comment by felipesanches** [comment]
I've been updating the vendor IDs list everytime I cut a new release. I will double check this. Thanks for reporting!

**Comment by felipesanches** [comment]
I've just added a code-test to ensure GOOG is listed and it is passing. I suppose you may be using a FontBakery release which did not include this ID.

**Comment by felipesanches** [comment]
On the other hand, looking at `git blame` output I see that `GOOG` was listed on the cached data since before July 2018.

See: 136d4f825

**Comment by felipesanches** [comment]
same thing for `GRCR`

There may be some other problem here then... I will try to replicate it locally.

**Comment by felipesanches** [comment]
I've added another code-test which makes me pretty sure GOOG is properly recognized as a valid vendor ID. We will need stronger evidence of a bug in order to address it. Please reopen the issue if you still experience the problem and can describe how this can be replicated.
