### ISSUE TITLE
Rationale seems to be cut in the Fail com.google.fonts/check/glyfnestedcomponents

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery#3124]
## Observed behaviour

Int seems there are some words missing at the beginning of the rationale in the Fail

![Screen Shot 2020-12-07 at 17 36 15](https://user-images.githubusercontent.com/48698976/101413980-430a9300-38b3-11eb-8c5c-cfb8430b9400.png)

**Comment by felipesanches** [comment]
That's been fixed yesterday at #3115

**Comment by felipesanches** [comment]
thanks for reporting it anyway! ;-D
