### ISSUE TITLE
Check that axis defaults are valid axis registry fallbacks

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3132]
## Observed behaviour

In https://github.com/google/fonts/pull/2862 we had to update the fallbacks of an axis because the default override of Newsreader wasn't (yet) defined as a fallback. 

## Expected behaviour

We should have a check that axis defaults are valid axis registry fallbacks

**Comment by felipesanches** [comment]
implementado em #3141 e estará disponível no próximo release, FB v0.7.35
