### ISSUE TITLE
com.google.fonts/check/font_copyright isn't allowing a date-range (?)

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery#3135]
## Observed behaviour

From what was discussed on #2393, it would be expected that a date-range could be specified in the copyright string. Nevertheless, the check is reporting a Fail for:

> 🔥 FAIL Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)" But instead we have got: "Copyright 2001-2020 by the STIX Fonts Project Authors (https://github.com/stipub/stixfonts)" [code: bad-notice-format]

## Expected behaviour

As a fix for it was included in #2895, it would be expected to be possible to specify a date-range. Or, if there is a particular format that the date-range should follow, to receive an explanation on how it should be written.

## Resources and exact process needed to replicate

https://github.com/stipub/stixfonts/tree/master/fonts at commit [f2d81e7](f2d81e73d5493fa4e4b8098c3eb221eb69db3ee4)

**Comment by khaledhosny** [comment]
I think the error results from the presence of `by` after the date, not the date range itself.

**Comment by vv-monsalve** [comment]
> I think the error results from the presence of `by` after the date, not the date range itself.

That must be the case. I read once and again the string and didn't see it. 
Closing this here, at least until we run new QA checks on fixed files.
