### ISSUE TITLE
grammar and spelling checks for descriptions

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#3142]
Since our descriptions are written in American English, there are often grammar and spelling mistakes since English isn't everyone's first language. It would be handy to check the text of the descriptions.

**Comment by felipesanches** [comment]
you mean automatically as a linting step? Or do you mean a person should read it all while tweaking it to fix typos & mispellings?

**Comment by m4rc1e** [comment]
Just lint. I only want to to flag possible grammatical and spelling errors. It should then be fixed by the user.

**Comment by felipesanches** [comment]
Any suggestion on useful python modules for that task?

**Comment by m4rc1e** [comment]
I see Grammarly now has a beta api, https://developer.grammarly.com/. Would be nice to see if we can integrate this.

**Comment by AndrewDiMola** [comment]
@m4rc1e - No longer in beta (we're now publicly available as v2.0) if you're interested in further exploring this project!

**Comment by simoncozens** [comment]
> @m4rc1e - No longer in beta (we're now publicly available as v2.0) if you're interested in further exploring this project!

Life comes at you fast...

"Grammarly for Developers, along with the SDK functionality and user experience, will be discontinued on January 10, 2024"

I think we're better off manually reviewing and posting issues the new find things.
