### ISSUE TITLE
add new check: kern table, if present, does not contain non-unicode kern pairs

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#3148]
Here are two tweets by @aaronbell for the rational:

https://twitter.com/aaronbell/status/1351988850940211200

> @Fontlab Question—I’m trying to export a kern table and Fontlab 7 includes non-Unicode kern pairs. Is there a way to filter them out?

and https://twitter.com/aaronbell/status/1352269806477561856

> In case you’re not aware, inclusion of non-Unicode fluids in a kern table causes it to fail in PowerPoint, which is one of the few places one still needs a kern table. So would be nice :)

**Comment by felipesanches** [comment]
on Twitter, I asked for sample files to aid in the development of this proposed new check and @aaronbell said he'd have to generate some file for us since the ones he's got can't be easily shared.

**Comment by felipesanches** [comment]
please post them here, @aaronbell (or a link to wherever we can download them from)

Thanks!

**Comment by aaronbell** [comment]
[Lato-Regular.ttf.zip](https://github.com/googlefonts/fontbakery/files/5852281/Lato-Regular.ttf.zip)

I downloaded Lato and then added a bad kern to it and exported. The kern table is now reported as 'failing'. This should work for your test purposes.

**Comment by felipesanches** [comment]
great, thanks!

**Comment by felipesanches** [comment]
sorry, but I do not understand exactly what is the problem at hand. What do you mean by "non-Unicode kern pairs" on the kern table? Can you show me some examples?

**Comment by aaronbell** [comment]
Sure. I mean a kern pair that involves a glyph (either left or right) that is not included in the cmap. In the case of the font I uploaded, kern pair 4643 is between glyph 267 and glyph 267, neither of which are present in the cmap (perhaps not an expected kern to add, but consider instead kerns used on pnum / tnum figures).

As such, the kern table will fail silently when you try to use it in PowerPoint on Windows.

**Comment by felipesanches** [comment]
while using ttx, I am having a hard time trying to find these specific glyphs and kern pairs you mentioned

**Comment by felipesanches** [comment]
can you also identify them by glyphname?

**Comment by aaronbell** [comment]
hmm, the kern pair number that I got out of fontval and code # don't seem to line up. Interesting. Anyway, it looks like if you have a post table v2, you can also identify them by glyphname. But they are still not contained in the cmap. 

For this font, I inserted this pair:
`<pair l="acute.case" r="acute.case" v="1422"/>`

acute.case is a non-unicode glyph. Therefore it causes the table to error.

**Comment by aaronbell** [comment]
Actually, a clarification. When you use TTX, fonttools decomposes the kern table, using the post table to convert glyph IDs to glyph names. If you use OTMA to look at the data directly (with no conversions), you will see that the kern pair is # 4643, and that the glyph ID is used in the table itself (and then OTMA shows the glyph names to the right since the post table is present):
<img width="446" alt="Screen Shot 2021-01-22 at 6 30 31 AM" src="https://user-images.githubusercontent.com/8460297/105503367-56af6480-5c7b-11eb-91f1-e209c4e46ca1.png">

**Comment by moyogo** [comment]
I've opened the PR https://github.com/googlefonts/fontbakery/pull/3167 to address the issue. With it the kern table check fails when a glyph in the kern table is not in the cmap. There's also a warning when none of the subtables in the kern table are format-0, the only known subtable format on Windows.
