### ISSUE TITLE
Improve language

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3150]
The following term(s) that should be replaced:

- [x] master -> main
- [x] whitelist -> allowlist
- [x] blacklist -> blocklist

These were found in the following file(s):
```
CHANGELOG.md

docs/source/developer/writing-profiles.md
```

**Comment by felipesanches** [comment]
I've left URLs of other repos that still use a `master` branch such as the `google/fonts` repo. We'll have to update those URLs only after the other projects adhere to the improved language policy.

**Comment by felipesanches** [comment]
I've changed all fontbakery repo URLs, so I will now change the default branch in this repo form `master` to `main`.

**Comment by felipesanches** [comment]
There's been some instances of `font mastering` being replaced by `font finalization` in some sample font files such as FONTLOG.txt in this repo. Maybe fontbakery could have a `googlefonts` profile check to **WARN** whenever such language is seen on font files being checked.
