### ISSUE TITLE
Add check for families being able to render themselves

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3159]
## Observed behaviour

A base expectation is that a font family's regular/default (400 roman) style can render its 'menu name' (nameID 1) in itself. 

We should have a check that confirms this.

If a font can't do so, or is 'special' (like a barcode font or Adobe Blank and so on), then it needs to be flagged in its PR for the GF eng team to handle specially.

A current example is that Noto Tamil Supplement can't render it's menu name; and it should comes from Noto Sans (latin).

It would be helpful to run this check over the central github repo to confirm which fonts fail this check and list that here.

**Comment by felipesanches** [comment]
The simplest approach is also naive and may not work for all cases, which would be to assume that the family name will not involve ligatures, glyph substitutions or any complex shaping. Then, assuming a 1-to-1 char/glyph mapping, by iterating the string we can look for those individual glyphs on the font.

For the cases where this approach would not work, a better implementation would likely involve actually attempting to render the text using something like harfbuzz perhaps.

**Comment by felipesanches** [comment]
If I recall correctly, family names in the Google Fonts collection are supposed to be all ASCII-only text, right? If so, the naive approach will be good enough, I think.
