### ISSUE TITLE
Relative imports in profiles fall down go boom

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontbakery#3161]
## Observed behaviour

```
  File "fbprofiles/check-test.py", line 10, in <module>
    from .utils import Foo
ModuleNotFoundError: No module named 'fontbakery.__file_modules'
```

## Expected behaviour

No obscure error.

## Resources and exact process needed to replicate

Assuming `fbprofiles/check-test.py` is:

```
from fontbakery.fonts_profile import profile_factory
from fontbakery.checkrunner import FAIL, PASS, Section
from fontTools.ttLib import TTFont

profile_imports = ()
profile = profile_factory(
    default_section=Section("A Test")
)

from fbprofiles.utils import Foo
```

I don't get an error with `PYTHONPATH=.`. But with:

```
from .utils import Foo
```

I get an error. Maybe this is because profiles aren't *really* modules? In which case I would prefer to see the original Python error:

```
ImportError: attempted relative import with no known parent package
```

rather than some ``__file_modules`` gobbledygook.

**Comment by chrissimpkins** [comment]
+1 for most intriguing issue title of the day :)

**Comment by graphicore** [comment]
You load a profile from a file system location `./fbprofiles/check-test.py` and then you expect that your file system location magically becomes a module and can be imported like `from fbprofiles.utils import Foo`.

I'd love to see this, but it is rather the way python loads stuff that fails than the fact that you can load a profile directly from a file. Loading profiles directly from files is useful for convenience e.g. to get started in a workshop or tutorial.

> Maybe this is because profiles aren't really modules? 

It depends how you load them or install them in your python. Python has loads of documentation how to create a module. A good starting point is to create a `setup.py` file.

> In which case I would prefer to see the original Python error:

I don't agree  that the "original Python error" should necessarily be an `ImportError`. One fact is things are loaded differently in different situations, another fact is that `fbprofiles` is not a module. But in the end, all of these errors are "original", as in they are raised by Python/the standard lib and not caught and changed by Font Bakery in any way.


Here's a bash session:

```

~/Projects/googlefonts> tree fbprofiles/
fbprofiles/
├── __init__.py
├── simple_fail.py
└── util.py

0 directories, 3 files
~/Projects/googlefonts> cat fbprofiles/simple_fail.py 
from fbprofiles.utils import Foo

~/Projects/googlefonts> python fbprofiles/simple_fail.py 
Traceback (most recent call last):
  File "fbprofiles/simple_fail.py", line 1, in <module>
    from fbprofiles.utils import Foo
ModuleNotFoundError: No module named 'fbprofiles'
```

In this case no Font Bakery is involved and we get a `ModuleNotFoundError`

When I use your original `fbprofiles/check-test.py` with `from fbprofiles.utils import Foo` like:

```
$ fonbakery check-profile fbprofiles/check-test.py

[...]
  File "fbprofiles/check-test.py", line 10, in <module>
    from fbprofiles.utils import Foo
ModuleNotFoundError: No module named 'fbprofiles'
```

and when I use `from .utils import Foo`:

```
$ fonbakery check-profile fbprofiles/check-test.py

[...]
  File "fbprofiles/check-test.py", line 10, in <module>
    from .utils import Foo
ModuleNotFoundError: No module named 'fontbakery.__file_modules'
```

When I use the relative import in my `fbprofiles/simple_fail.py` I finally get:

```
$ fonbakery check-profile fbprofiles/check-test.py

[...]
Traceback (most recent call last):
  File "fbprofiles/simple_fail.py", line 1, in <module>
    from .utils import Foo
ImportError: attempted relative import with no known parent package
```

Whatever, here's the thing you are asking for, in `checkrunner.py` line 1909:

```
diff --git a/Lib/fontbakery/checkrunner.py b/Lib/fontbakery/checkrunner.py
index bed85c6b..29e6c754 100644
--- a/Lib/fontbakery/checkrunner.py
+++ b/Lib/fontbakery/checkrunner.py
@@ -1906,7 +1906,7 @@ class Profile:
         return result
 
 
-FILE_MODULE_NAME_PREFIX = 'fontbakery.__file_modules.'
+FILE_MODULE_NAME_PREFIX = '.'
 def get_module_from_file(filename):
     # filename = 'my/path/to/file.py'
     # module_name = 'file_module.file_py'
lines 1-13/13 (END)
```

Gets rid of the "gobbledygook":

```
$ fonbakery check-profile fbprofiles/check-test.py

[...]
  File "fbprofiles/check-test.py", line 10, in <module>
    from .utils import Foo
ImportError: attempted relative import with no known parent package
```

That said, the multiprocessing mode `-j`, which uses the `FILE_MODULE_NAME_PREFIX` "gobbledygook" to figure how to load the profile in a worker. making `FILE_MODULE_NAME_PREFIX` an empty string breaks `-j` making it `'.'`a dot works from a quick test.

I will make a PR with the change, but I'm not fully confident it will not break anything else.

**Comment by graphicore** [comment]
If there are problems with #3162 we could discuss to change 

```
FILE_MODULE_NAME_PREFIX = 'fontbakery.__file_modules'
```

Into something that makes

```
ModuleNotFoundError: No module named 'fontbakery.__file_modules'
```

less obscure.


```
FILE_MODULE_NAME_PREFIX = 'fake_profile_module_loaded_from_file.'

results in:

ModuleNotFoundError: No module named 'fake_profile_module_loaded_from_file'
```

Another thought is that at least `'fontbakery.__file_modules' was super easy to find in the sources when I looked into this issue, If the `.` dot pops up in an error message it will be really hard to `grep`.
