### ISSUE TITLE
Allow source fonts to be used in profiles

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontbakery#3169]
## Observed behaviour

Checking UFO/Designspace/whatever fonts currently requires a custom profile to make the argparser not ignore the file.

## Expected behaviour

We want to be able to support testing of all files, and filtering out what tests should be applied based on conditions which test the file type. I think this means we need to:

* Loosen up the file handling patterns in `FontsProfile.setup_argparse`.
* Do *something* with the `ttFont` dependency in `FontsProfile.profile_factory` but I don't know what.
* Create new `is_binary`, `is_ufo`, `is_designspace`, `is_glyphs` etc. conditions in `shared_conditions` and have `ttFont` depend on `is_binary`.

However, I don't *really* understand how this works so I am just guessing.

**Comment by graphicore** [comment]
> Loosen up the file handling patterns in FontsProfile.setup_argparse.

Coming up with an CLI that puts filenames/paths into different lists would be the first step:

* `binary` => `fonts` this will ensure everything keeps working, `ttFont` is created from the items in `fonts`
* `ufo` => `ufos`
* `designspace` => `designspaces`
* `glyphs` => `glyphs`

Could work. But maybe we also put all source formats into a `sources` list and then conditions like `is_ufo` etc. could be used, and we'd get SKIP messages. (We could make something that silences those.)

It depends on how we want to use these things. There's also the option to change the `checkrunner`, e.g. I can imagine  smarter iterators/generators that e.g can decide to skip/not yield certain items. This would be a bit more complicated to implement but also may be worthwhile, if we know what we want.

> Do something with the ttFont dependency in FontsProfile.profile_factory but I don't know what.

probably nothing to do here

**Comment by simoncozens** [comment]
> Coming up with an CLI that puts filenames/paths into different lists would be the first step:

I'm not sure what you mean by CLI here, but I would not want to force the user to do things that the computer can easily do. The user should not have to specify that a certain file is binary, UFO, Glyphs, etc. when the computer can look at the extension and work it out for itself. (I'm also looking at you, fontmake, and your annoying `-g`/`-m`/`-u` options!)

Just take a list of files and sniff the extension to see which tests are appropriate. That way we don't get needless SKIPs either.

**Comment by graphicore** [comment]
> Just take a list of files and sniff the extension to see which tests are appropriate. That way we don't get needless SKIPs either.

Yeah, that's a definition of an interface for the command line (CLI)
