### ISSUE TITLE
New Check : Impose character limitation for bio.html

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3171]
**Proposition of new check for the catalog (warn)**

A while ago with @vv-monsalve we thought about the length of the bio.html to give some instructions to designers. We settled on a maximum of 300-350 characters.

The main reasons are:
- Size: When there are multiple designers, we don't want the specimen page to be super long with a lot of small text paragraphs.
- Equality: Some designers want to write a novel about themselves, and some prefer 3 words. We din't want one designer to particularly stand out with a long bio. 300-350 characters looked like a good compromise.

Other reasons for limitation to something quite short:
- Efficiency: People don't read long texts on the specimen page, I tend to think that the best way to make the users acknowledge one author's history, is to have a maximum a keywords in a minimum of sentences.
- Workflow: It is more time-consuming to review and correct a long bio

@davelab6 can you give your opinion on this ?

**Comment by vv-monsalve** [comment]
After some new cases, my only concern is about the actual length.

If we take into consideration the HTML tags needed, a basic bio with only one paragraph and a couple of links (twitter + webpage) would use ~120 characters in the tags. In that case, the actual length for the designer's text would be only 230 characters, and even less. 

I've asked designers for texts of 250 characters max. But once the text is formatted into HTML it gets larger.
Eg. Designer text: 240. after HTML: 379 

Thus, I think we could ask designers for a max of 250 characters (even 200), but the actual length for the HTML should fail only at something like 400. And probably we should restrict the number of hyperlinks in that case. There are cases published with up to four links.

Minimum characters used would be:

```
<p>
</p>
<p>
<a href="https://twitter.com/UserName">Twitter</a> | 
<a href="https://www.UserWebPage.com">UserWebpage</a>
</p>
```

**Comment by RosaWagner** [comment]
200-250 seems super short though for a bio, no? I would say max 350 characters, recommended 250 for the designer's text. So a size of 500 octets for the html, like half of the description limit could be a nice ratio?

I agree on 1 link (or 2) is enough, so we would have less outdated links.

**Comment by RosaWagner** [comment]
Keeping in mind that this limit is not an absolute thing, it is more an indication to designers. I mean if they send a 380 characters bio, we shouldn't spend ages correcting it to match the size limit, the idea of this check is to be more efficient on the catalog task.

**Comment by vv-monsalve** [comment]
> 200-250 seems super short though for a bio, no?

Precisely, so it was why my concern. Anyhow the designers tend to send longer texts, so probably we could stick to 250 - 300 and yes 500 for the html.

>  we shouldn't spend ages correcting it to match the size limit, the idea of this check is to be more efficient on the catalog task.

Agree

**Comment by RosaWagner** [comment]
> Anyhow the designers tend to send longer texts

So truuuuuue
