### ISSUE TITLE
com.google.fonts/check/version_bump silently FAILs

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontbakery#3172]
## Observed behaviour

A font I onboarded got blocked because I hadn't bumped the version number. As I was about to fix it, I was wondering if not a check already exists for that or whether I should propose one.

I found the [check](https://github.com/googlefonts/fontbakery/blob/main/Lib/fontbakery/profiles/googlefonts.py#L2691), but it silently fails because of [these lines](https://github.com/googlefonts/fontbakery/blob/main/Lib/fontbakery/profiles/googlefonts_conditions.py#L460-L461) in the condition.

Apparently, the `license` parameter is indeed `None` for `github_gfonts_ttFont(ttFont, license)`, so the condition returns `None`, so the check isn’t even executed.

I could not understand how the conditions are constructed or executed, in particular where the `license` parameter is constructed, so I couldn’t investigate further. 

## Expected behaviour

`github_gfonts_ttFont(ttFont, license)` is expected to receive a valid content for `license` so that the check can execute.

## Resources and exact process needed to replicate

You can run the check on [this font in this particular commit](https://github.com/yanone/Benne/blob/3cc3a77404c6fa30d822e420fbb7aaa18da40d6a/TTF/Benne-Regular.ttf).

**Comment by felipesanches** [comment]
The reason for the check being skipped was the presence of more than a single `OFL.txt` file in your project's repo. The `license` condition assumed that only a single license file should exist in the repo. If multiple license files were found, it would consider it a problem and simply did not pick an arbitrary one. As a result, it returned None and the check was skipped.

Now it returns the first license found. It assumes the files are identical whenever multiple files are found.
We should create a new fontbakery check to ensure that the contents of the license files are identical in such cases, to avoid self-contradictory licensing terms on a project repo. I'll add a new issue for that task.

**Comment by yanone** [comment]
That's awesome, thanks. I've seen it so many times that people have several OFL.txt in so many different places in their repo. So many people don't know what they're doing...
