### ISSUE TITLE
needed: an override for pretty_print_list?

### ISSUE THREAD

**Issue by bobh0303** [googlefonts/fontbakery#3173]
## Observed behaviour

An error or warning lists some (typically 10) but not all of the glyphs that have a particular issue. I may be missing it, but I do not see a commandline override option to get fontbakery to output the complete list of problematic glyphs.

From what I can see, this means I have to fix the first 10, re-build the fonts and re-run the fontbakery profile, fix the next 10 and repeat until done. Painful.

## Expected behaviour

I expect some kind of commandline option that will disable the list truncation thus getting the complete list, not just the first 10.

Looking at the code, I understand that [`pretty_print_list()`](https://github.com/googlefonts/fontbakery/blob/c795c32dbe237d36651905be4c3268c16fd13b26/Lib/fontbakery/utils.py#L100) is used to truncate the list (typically to 10 glyphs) to prevent overwhelming output. This would be the perfect spot to add some code that, based on a command line option, outputs the entire list instead of truncating it.

## Resources and exact process needed to replicate

I doubt you really need a way to replicate, but you can grab [this dev version of Lateef Regular](https://build.palaso.org/repository/download/Fonts_Lateef/254098:id/Lateef-1.285--dev-08969f.zip!/Lateef-1.285--dev-08969f/Lateef-Regular.ttf) and run:

```
fontbakery check-profile -c com.google.fonts/check/gdef_spacing_marks fontbakery.profiles.gdef Lateef-Regular.ttf
```

and in the output find:

```
    * WARN: The following spacing glyphs may be in the GDEF mark glyph class by mistake:
         _noon, uni08B6, uni08B6.fina, uni08B6.init, uni08B6.medi, uni08B7, uni08B7.fina, uni08B7.init, uni08B7.medi, uni08B9 and 5 more. [code: spacing-mark-glyphs]
```

**Comment by bobh0303** [comment]
particularly problematic are lists like this:

```
⚠️ WARN The following glyphs have colinear vectors:
* A: L<<287.0,370.0>--<269.0,322.0>> -> L<<269.0,322.0>--<187.0,89.0>>
* A: L<<442.0,797.0>--<287.0,370.0>> -> L<<287.0,370.0>--<269.0,322.0>>
* A: L<<590.0,319.0>--<572.0,370.0>> -> L<<572.0,370.0>--<402.0,788.0>>
* A: L<<683.0,89.0>--<590.0,319.0>> -> L<<590.0,319.0>--<572.0,370.0>>
* Aacute: L<<287.0,370.0>--<269.0,322.0>> -> L<<269.0,322.0>--<187.0,89.0>>
* Aacute: L<<442.0,797.0>--<287.0,370.0>> -> L<<287.0,370.0>--<269.0,322.0>>
* Aacute: L<<590.0,319.0>--<572.0,370.0>> -> L<<572.0,370.0>--<402.0,788.0>>
* Aacute: L<<683.0,89.0>--<590.0,319.0>> -> L<<590.0,319.0>--<572.0,370.0>>
* Acircumflex: L<<287.0,370.0>--<269.0,322.0>> -> L<<269.0,322.0>--<187.0,89.0>>
* Acircumflex: L<<442.0,797.0>--<287.0,370.0>> -> L<<287.0,370.0>--<269.0,322.0>> and 51 more. [code: found-colinear-vectors]
```

because now that I see the 'A' outline and what has caused these warnings, I have decided these are intentional and I don't intend to "fix" them. However I can't get a list of the other potentially problematic glyphs.

**Comment by bobh0303** [comment]
@felipesanches Any prospect for a fix?  The colinear vectors test is particularly useless without it.

**Comment by felipesanches** [comment]
As suggested by @NightFurySL2001 at https://github.com/googlefonts/fontbakery/issues/3512#issue-1059277011 I will implement this as `-F, --full-list`
