### ISSUE TITLE
[new check] designer pic is png

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3175]
Would raise a FAIL is the designer's avatar is other than png

**Comment by felipesanches** [comment]
do we know why PNGs are not acceptable?

**Comment by RosaWagner** [comment]
Once a push to sandbox got block because an image was jpeg. I agree it not a great explanation. But request came from Rod at the time.

**Comment by RosaWagner** [comment]
Dave got confirmation that jpeg were also now accepted; this PR passed to sandbox and production: https://github.com/google/fonts/pull/4557
