### ISSUE TITLE
Since updating the license condition, families without a licence will produce many check errors

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#3201]
Since merging https://github.com/googlefonts/fontbakery/pull/3192, families which don't contain a license file now produce many check errors, https://github.com/googlefonts/fontbakery/pull/3192#issuecomment-795438614

**Comment by davelab6** [comment]
@felipesanches please prioritize this one as it's key to others workflows, even reverting that pr will be good if a fix can't be made today :)

**Comment by felipesanches** [comment]
the fire has been quickly put out ;-)

**Comment by davelab6** [comment]
Thanks again for the quick response here
