### ISSUE TITLE
HTML reporter outputs plain Markdown. It should parse it and output HTML tables instead.

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontbakery#3207]
## Observed behaviour

fontbakery-UI isn't rendering tables in HTML (https://github.com/googlefonts/fontbakery-ui/issues/21). But I think this is a problem with the fontbakery architecture.

`com_google_fonts_check_hinting_impact` wants to render a table, so it sends back raw Markdown(!!!) in a Message object:

```python
    yield INFO,\
          Message("size-impact",
                  f"Hinting filesize impact:\n"
                  f"\n"
                  f"\t|  | {font} |\n"
                  f"\t|:--- | ---:|\n"
                  f"\t| Dehinted Size | {dehinted_size} |\n"
                  f"\t| Hinted Size | {hinted_size} |\n"
                  f"\t| Increase | {increase} |\n"
                  f"\t| Change   | {change:.1f} % |\n")
```

When this object is passed to a `GHMarkdownReporter`, you get a table. Hooray!

When this object is passed to any other kind of reporter, especially the `HTMLReporter`, you get rubbish.

## Expected behaviour

The message should render as a table in all reporters.

How can we achieve this? One way is to add a set of methods onto the Message class such as `add_table`, `add_image`, `add_header` etc.

Another is to allow the check functions to report specific information to specific reporters. This would be helpful in the shaping profile, so that the HTML report (and only the HTML report) could have the SVG images of shaping regressions.

Maybe there is a need for both.

**Comment by graphicore** [comment]
> Maybe there is a need for both.

I agree. But, the SVG images of the second example could be used in Markdown as well, possibly inline as `svg` tags.

Handling files creation i.e. via `add_image` or maybe `add_file` is interesting if they need to be available in a directory eventually; Filenames must not collide, but they should also be available to other reporters, e.g. HTML, so it can put them into the 'src' attribute. Could also be handled via [data urls](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs).

If a reporter can't render e.g. SVG, like the terminal-reporter, it could still decide to mention it, if it knows the type.

**Comment by felipesanches** [comment]
My plan is to use Markdown for everything: log messages, doc strings, rationales. Then, the Markdown reporter would use them as-is, while other reporters would render the content by translating Markdown to whatever output needed. Our documentation at Read The Docs also benefits from this.

@aurium is working on generating good output for the text terminal based on parsing markdown and outputting ANSI text. (see #2559)

**Comment by graphicore** [comment]
Having e.g. image attachments to a `Message` would still make sense; also a way to a reference them in the markdown.
