### ISSUE TITLE
listed_on_gfonts_api always warn

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3220]
This check is always popping, even when the font is already published on GF.

⚠ WARN Family not found via Google Fonts API. [code: not-found]

**Comment by RosaWagner** [comment]
I didn't see this check for a while but appeared in this PR: https://github.com/google/fonts/pull/4614#issuecomment-1170184428

I don't understand this check tbh, can the rational be more explicit or can we just disable it?

cc @m4rc1e @vv-monsalve

**Comment by RosaWagner** [comment]
Please let's just disable the check, it warns for any new font and it doesn't make sense.

**Comment by felipesanches** [comment]
thanks, I'll try to address it this week
