### ISSUE TITLE
FAILS for ligature lookup I don't understand

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3238]
Apparently the font file is corrupted or malformed, and I don't know why. Maybe the feature order?

🔥 FAIL Failed to lookup ligatures. This font file seems to be malformed. For more info, read: googlefonts/fontbakery#1596 [code: malformed]

Happening there: https://github.com/kosmynkab/Bona-Nova

**Comment by felipesanches** [comment]
I think I've seen this before. I will have to take a look. If I recall correctly, it probably means fontbakery is actually not interpreting it correctly while the file is good. (but I have to inspect the file to be sure)

**Comment by yanone** [comment]
Here’s another one: https://github.com/google/fonts/pull/3326

**Comment by yanone** [comment]
One more remark: I did check the fonts of the above PR with fontbakery today using the latest version directly from the git repo, and didn't see this and a few other FAILs except the `avar` one which is a legitimate FAIL here.

**Comment by m4rc1e** [comment]
I think https://github.com/googlefonts/fontbakery/pull/3246 will solve this.

**Comment by vv-monsalve** [comment]
> Apparently the font file is corrupted or malformed, and I don't know why. Maybe the feature order?

I had opened an [Issue](https://github.com/googlefonts/fontbakery/issues/3131) for this a while ago.

Happy if Denis's PR solves it!

**Comment by davelab6** [comment]
Can this issue be closed?

**Comment by moyogo** [comment]
This can be closed. This has been fixed by #3246.
