### ISSUE TITLE
Inaccurate verticalmetricsregressions check

### ISSUE THREAD

**Issue by aaronbell** [googlefonts/fontbakery#3242]
## Observed behaviour

I am [updating the existing Shippori Mincho and Shippori Mincho B1 font families](https://github.com/google/fonts/pull/3316) on Google Fonts. However, FontBakery is finding an error when it runs com.google.fonts/check/verticalmetricsregressions:

* 🔥 **FAIL** Shippori Mincho Bold: hhea Ascender is 1160 when it should be 880 [code: bad-hhea-ascender]
* 🔥 **FAIL** Shippori Mincho Bold: hhea Descender is -288 when it should be -120 [code: bad-hhea-descender]
* 🔥 **FAIL** Shippori Mincho ExtraBold: hhea Ascender is 1160 when it should be 880 [code: bad-hhea-ascender]
* 🔥 **FAIL** Shippori Mincho ExtraBold: hhea Descender is -288 when it should be -120 [code: bad-hhea-descender]
* 🔥 **FAIL** Shippori Mincho Medium: hhea Ascender is 1160 when it should be 880 [code: bad-hhea-ascender]
* 🔥 **FAIL** Shippori Mincho Medium: hhea Descender is -288 when it should be -120 [code: bad-hhea-descender]
* 🔥 **FAIL** Shippori Mincho Regular: hhea Ascender is 1160 when it should be 880 [code: bad-hhea-ascender]
* 🔥 **FAIL** Shippori Mincho Regular: hhea Descender is -288 when it should be -120 [code: bad-hhea-descender]
* 🔥 **FAIL** Shippori Mincho SemiBold: hhea Ascender is 1160 when it should be 880 [code: bad-hhea-ascender]
* 🔥 **FAIL** Shippori Mincho SemiBold: hhea Descender is -288 when it should be -120 [code: bad-hhea-descender]
* 🔥 **FAIL** Shippori Mincho B1 Bold: hhea Ascender is 1160 when it should be 880 [code: bad-hhea-ascender]
* 🔥 **FAIL** Shippori Mincho B1 Bold: hhea Descender is -288 when it should be -120 [code: bad-hhea-descender]
* 🔥 **FAIL** Shippori Mincho B1 ExtraBold: hhea Ascender is 1160 when it should be 880 [code: bad-hhea-ascender]
* 🔥 **FAIL** Shippori Mincho B1 ExtraBold: hhea Descender is -288 when it should be -120 [code: bad-hhea-descender]
* 🔥 **FAIL** Shippori Mincho B1 Medium: hhea Ascender is 1160 when it should be 880 [code: bad-hhea-ascender]
* 🔥 **FAIL** Shippori Mincho B1 Medium: hhea Descender is -288 when it should be -120 [code: bad-hhea-descender]
* 🔥 **FAIL** Shippori Mincho B1 Regular: hhea Ascender is 1160 when it should be 880 [code: bad-hhea-ascender]
* 🔥 **FAIL** Shippori Mincho B1 Regular: hhea Descender is -288 when it should be -120 [code: bad-hhea-descender]
* 🔥 **FAIL** Shippori Mincho B1 SemiBold: hhea Ascender is 1160 when it should be 880 [code: bad-hhea-ascender]
* 🔥 **FAIL** Shippori Mincho B1 SemiBold: hhea Descender is -288 when it should be -120 [code: bad-hhea-descender]

As this is a CJK font, the established hhea values (1160 / -288) are accurate, but what is more confusing is why the code is claiming that it should be 880 and -120. The existing Shippori Mincho and Shippori Mincho B1 families do not have those hhea values. 

## Expected behaviour

The error should not occur. 

## Resources and exact process needed to replicate

Please download the Shippori Mincho fonts from the PR linked above and run Font Bakery check-googlefonts on any file. Error appears.

**Comment by felipesanches** [comment]
@m4rc1e would you like to take a look at this one?

**Comment by m4rc1e** [comment]
Sure

**Comment by m4rc1e** [comment]
Fixed in #3243
