### ISSUE TITLE
Fonts used for in-car display must have specific proportions

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontbakery#3250]
(related to #1832)

## Observed behaviour

According to section 4.5.3 of ISO 15008 (the standard which governs the use of in-car displays), fonts used in this environment should "not be too narrow or too wide". Specifically, the width of the letter H divided by the height of the letter H should be between 0.65 and 0.80.

fontbakery should check for this.

## Expected behaviour

There should be a check in a (new) `iso15008` profile, with:

* an ID of `com.google.fonts/check/iso15008_proportions`
* the following rationale:

> According to ISO 15008, fonts used for in-car displays should not be too narrow or too wide.
> To ensure legibility of this font on in-car information systems, it is recommended that the ratio of H width to H height is between 0.65 and 0.80.
> (Note that PASSing this check does not guarantee compliance with ISO 15008.)

**Comment by davelab6** [comment]
@simoncozens can this be closed?

**Comment by simoncozens** [comment]
Yes!
