### ISSUE TITLE
post table for variable fonts 

### ISSUE THREAD

**Issue by punchcutter** [googlefonts/fontbakery#3259]
The current expectation causes a FAIL for all variable fonts with post table format 3.0, but some fonts like Source Han Sans VF/Noto Sans CJK VF cannot use format 2 and _must_ use format 3 for both the CFF2 and TTF variable fonts. This could either be changed to a WARN or the glyph count could be checked to see if format 2 is impossible for the current font.

**Comment by chrissimpkins** [comment]
We've used post v3 for file size savings in targeted use cases.

**Comment by punchcutter** [comment]
Not a big deal, but currently the Noto CJK fonts with 65,535 glyphs FAIL when running with `check-notofonts`. I just ignore it because it's absolutely not a fail since it's impossible for these to have a format 2 post table. Anyway, it would be nice to not fail here. Even just having some hard-coded exception for the Noto CJK fonts could be nice.

**Comment by punchcutter** [comment]
Fixed by https://github.com/googlefonts/fontbakery/issues/3635
