### ISSUE TITLE
Unable to upgrade fontbakery to 0.7.35

### ISSUE THREAD

**Issue by xconsau** [googlefonts/fontbakery#3269]
## Observed behaviour

I am trying to upgrade FontBakery to the latest version 0.7.35 (as seen in the changelog file). I am using the following command after uninstalling old version 0.7.34:

<pre>pip install fontbakery --no-cache-dir</pre>

Still it downloads 0.7.34 only. If I use the upgrade command, it says:
<pre>Requirement already satisfied: fontbakery in e:\...\env\lib\site-packages (0.7.34)</pre>

## Expected behaviour
Upon using <code>pip install fontbakery --upgrade</code> it should upgrade to 0.7.35 version (which is the latest one).

I am trying to upgrade to the latest version as I am getting a FAIL message for missing avar upon checking a variable font.

<pre>* FAIL: This variable font does not have an avar table. [code: missing-avar]</pre>

I suppose this has been given some relaxation in 0.7.35.

**Comment by m4rc1e** [comment]
0.7.35 hasn't been released yet, https://github.com/googlefonts/fontbakery/releases.

Once it's been released, you won't get that avar message any more.

Btw, you can install the dev version by doing `pip install git+https://github.com/googlefonts/fontbakery`. If you're just a casual user, I recommend you just wait for a new official release to be cut.

**Comment by felipesanches** [comment]
yeah, we gradually add entries to the next release on the Changelog, but you will see that the release date has a few question marks since it was not yet actually released.
