### ISSUE TITLE
Improve camelcase check result explanation and whitelisting process

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3270]
@vv-monsalve mentioned a new family has to have a camelcase name, and fontbakery FAILs this, but without explaining how to create an exception. 

To direct address this and make a PR, one needs to add the new family name to this list:

https://github.com/googlefonts/fontbakery/blob/b4bb6a063324a40c463a9696abd6662ad263510b/Lib/fontbakery/profiles/googlefonts_conditions.py#L402-L416

However, I think it would be helpful to have the list in a side file, so that the process to add it is even more simple, "Just add the family name to a new line in this file."

**Comment by RosaWagner** [comment]
We could also continue the list until it is obsolete…

**Comment by m4rc1e** [comment]
> What's your plan to make this obsolete?

Instead of using the filename to derive the family name, we will instead use nameID 16 or nameID 1.

> Is it related to the ongoing refactoring of the name table checks?

Yep

**Comment by vv-monsalve** [comment]
> We could also continue the list until it is obsolete…

I think it would depend on how close we are to make it obsolete
