### ISSUE TITLE
ERROR: check/canonical_filename with MutatorSans-VF

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3274]
@justvanrossum reported at https://github.com/googlefonts/fontbakery/issues/3273#issuecomment-839572283 that the VF in [MutatorSans-VF.ttf.zip](https://github.com/googlefonts/fontbakery/files/6464599/MutatorSans-VF.ttf.zip) errors on `com.google.fonts/check/canonical_filename` because "the name table doesn't contain a required entry."

**Comment by felipesanches** [comment]
@justvanrossum, your font indeed looks broken. Can you add the needed name table entries such as `FONT_FAMILY_NAME`?

![Screenshot from 2021-05-12 14-32-41](https://user-images.githubusercontent.com/213676/118019237-23c6d480-b32f-11eb-90dd-d9161414cf06.png)

**Comment by justvanrossum** [comment]
I could, but isn't it fontbakery's job to point out such problems without crashing? :)

(It's not a blocker for me, I just noticed the behavior. Feel free to close as "won't fix" as you can fairly argue this font is too broken to even be analyzed.)

**Comment by felipesanches** [comment]
I agree we should report in the most user-friendly way as possible. I'm just trying to figure out how to achieve that without making the source code bloated with sanity checks everywhere. I want to think a bit more about this one before simply dismissing it as "wont fix".

**Comment by felipesanches** [comment]
the problem here is that the name table entries are treated as the source of truth to figure out the familyname. If that's not provided, it seems that we can't move forward in this specific case.

**Comment by felipesanches** [comment]
I will split out the `def variable_font_filename(ttFont):
` inner-function into a proper condition and make the check not run at all if the condition can't be computed. I think that will give the user a clearer message as well.

**Comment by felipesanches** [comment]
This is what the report looks like now:

I am sure we still can do better, by actually saying why the varfont filename could not be computed. But that's another issue we're already tracking at #3277

**Comment by justvanrossum** [comment]
SKIP sounds rather harmless and ignorable. Perhaps the previous raw ERROR is better after all, even if a FAIL would be more appropriate. (I think I understand how that's hard to do, given the error is in the condition.)

**Comment by felipesanches** [comment]
Project policy is that **ERROR** is never acceptable, since it means either a bug or a bad system setup. So our only choice here is either **SKIP** or **WARN** / **FAIL**.

**Comment by felipesanches** [comment]
This makes me wish for something similar to this (that does not yet really exist):
```
    conditions = ['FAIL:variable_font_filename'],
```

or, alternatively:

```
    fail_conditions = ['variable_font_filename'],
```

(good thing about the first proposed syntax is that it would also allow other levels of result such as WARN or INFO, while the second syntax would require individual decorator keys for each possible log-level)

**Comment by graphicore** [comment]
You can calculate "raw condition" that contains metadata/details and have a check report on details about that calculation, if it is a FAIL etc. You would then add a second condition for consumption by checks, that one unboxes the result value of the raw condition. There are examples of schemes similar to this.

**Comment by felipesanches** [comment]
yeah, I know... but that makes 2 checks out of one. There could be a simpler way...

**Comment by felipesanches** [comment]
the second check would be something like: "FontBakery deduces the familyname of a variable font by inspecting the name table entries. This check ensures that the font provides all the info needed to compute that."

Such a check would sound too "meta", though!

**Comment by graphicore** [comment]
You could have left the condition in the check, catch the Error and report it as a fail.

> the second check would be something like: "FontBakery deduces the familyname of a variable font by inspecting the name table entries. This check ensures that the font provides all the info needed to compute that."

Well, if it's reasonable to do it this way, and the font fails to adhere to that scheme, it qualifies for another check, not?


I'm just looking at the check, it parses the font itself: `ttFont = TTFont(font)`, so, there's probably more refactoring that should be done.

**Comment by felipesanches** [comment]
OK, I think this is better now, right, @justvanrossum? Now we actually **FAIL** in that specific case:

![Screenshot from 2021-05-12 18-36-14](https://user-images.githubusercontent.com/213676/118047343-0145b300-b351-11eb-8a8f-4c9c0b656a31.png)
