### ISSUE TITLE
Error with ttfautohint since update

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3276]
## Observed behaviour

```
ERROR: Font has old ttfautohint applied?
com.google.fonts/check/old_ttfautohint
💔 ERROR ttfautohint is not available. [code: not-available]
```

## Resources and exact process needed to replicate

https://github.com/google/fonts/pull/3417
https://github.com/google/fonts/pull/3410

**Comment by felipesanches** [comment]
yeah, you should install it as a standalone program. @anthrotype's ttfautohint-py was handy in that sense, but we (at least temporarily) removed that dependency because we did not yet know how to address the broken build on newer Mac hardware. Maybe we reintroduce that dependency at some point if we ever figure it out. But for now you need to install ttfautohint manually on your system.

**Comment by RosaWagner** [comment]
Thanks for the answer Felipe.

**Comment by RosaWagner** [comment]
But how can I do to avoid having the Fontbakery CI broken in repos where I set up a github action to build the fonts?

**Comment by chrissimpkins** [comment]
If this remains a requirement to run FB without errors:

If you are building in a Linux env you can use `apt` to install the [Ubuntu ttfautohint package](https://packages.ubuntu.com/focal/ttfautohint) with a `sudo apt-get install ttfautohint` (see [SO article](https://stackoverflow.com/a/58002908/2848172) on apt + GHA) dependency installation step in your workflow.  

I believe that the macOS GHA env's support `brew` installs with `brew install ttfautohint`.

Not sure about Windows.  I've never built/installed ttfa on the platform...

If you point to a repo where you need this, we can come up with something concrete.

**Comment by chrissimpkins** [comment]
Here are better GitHub docs on how to install software on each of the runner types:

https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners

**Comment by RosaWagner** [comment]
Thanks Chris, I have this repo among other: https://github.com/Omnibus-Type/Texturina/pull/7

**Comment by chrissimpkins** [comment]
Let's see if this does the trick: https://github.com/Omnibus-Type/Texturina/pull/8

You may need to merge to a branch or main to test it.  GH has set up new blocks on automated GHA runs from external branch PR's after the cryptomining fiasco

**Comment by RosaWagner** [comment]
haha true. I asked the author to merge or to give me writing access, I'll keep you updated. Many thanks.

**Comment by chrissimpkins** [comment]
No worries.  No need to merge that but it does provide an example.  If you have write access to another repo, you can C/P the lines into the other GHA configs to test.  I think that should work.

**Comment by chrissimpkins** [comment]
> I think that should work

* for builds on the Ubuntu runners
