### ISSUE TITLE
ERROR reported on com.google.fonts/check/old_ttfautohint when making a PR for a font

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery#3287]
## Observed behaviour

Under version 0.7.35. There is one ERROR reported by the CI process as part of the [PR](https://github.com/google/fonts/pull/3422) of MonteCarlo but wasn't reported when running the same FB version locally.

## Resources and exact process needed to replicate

Link to the PR: https://github.com/google/fonts/pull/3422
Upstream Repo: https://github.com/googlefonts/monte-carlo

**Comment by chrissimpkins** [comment]
Duplicate of #3276?

**Comment by vv-monsalve** [comment]
> #3276

It seems so. Closing this here.

**Comment by chrissimpkins** [comment]
Let me know if you need a hand setting up your workflows Viviana.  The config that I added on Rosalie's repo should work for you.  It is just a few lines that need to be copy/pasted into your GH action configuration that includes the fontbakery testing.

**Comment by vv-monsalve** [comment]
Thank you, Chris. I took the lines from Rosalie's repo and worked perfectly :)

**Comment by RosaWagner** [comment]
Yes, it worked once I merged the PR I was trying to test :)

**Comment by chrissimpkins** [comment]
Good to hear!
