### ISSUE TITLE
Mismatch of com.google.fonts/check/name/familyname & com.google.fonts/check/name/subfamilyname with specs

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontbakery#3299]
Got the 2 FAILs:

```
 >> com.google.fonts/check/name/familyname
    Check name table: FONT_FAMILY_NAME entries.
    with Google-Fonts-Fixes/IBM-Plex-Sans/fonts/complete/ttf/IBMPlexSans-Thin.ttf

      Rationale:                                                                
      Checks that the family name infered from the font filename matches the    
      string at nameID 1 (NAMEID_FONT_FAMILY_NAME) if it conforms to RIBBI and  
      otherwise checks that nameID 1 is the family name + the style name.       

     FAIL Entry [FONT_FAMILY_NAME(1):MACINTOSH(1)] on the                       
          "name" table: Expected "IBM Plex Sans" but got "IBM Plex Sans Thin".  
          [code: mismatch]                                                      


    Result: FAIL

 >> com.google.fonts/check/name/subfamilyname
    Check name table: FONT_SUBFAMILY_NAME entries.
    with Google-Fonts-Fixes/IBM-Plex-Sans/fonts/complete/ttf/IBMPlexSans-Thin.ttf


     FAIL SUBFAMILY_NAME for Mac "Regular" must be "Thin"                       
          [code: bad-familyname]                                                


    Result: FAIL
```

after I correctly applied the name values from https://github.com/googlefonts/gf-docs/tree/main/Spec#supported-styles.
There's a mismatch. Which one is correct? Which other values could be mismatched?

I’m assuming the specs are incomplete, but I don't know better, so I'm posting it here.
I'll update the specs if someone tells me what is correct.

@m4rc1e @davelab6

**Comment by yanone** [comment]
For example here: https://github.com/googlefonts/plex/tree/master/Google-Fonts-Fixes/IBM-Plex-Sans/fonts/complete/ttf
The current hotfix script is here: https://github.com/googlefonts/plex/blob/master/Google-Fonts-Fixes/convert.py

It's totally work in progress. I didn't make a separate fork just for this issue.

The fonts shouldn't matter in this case. I just implemented the specs precisely, and get FAILs for it now.

**Comment by yanone** [comment]
I think I got the hang of it: Mac and Windows name IDs are different for ID 1 & 2.
Basically, I reverse-implemented the specs from the `fontbakery` checks.

I didn't know I had write-permission to the `gf-docs` repo, so my changes are already live now, sorry for that:
https://github.com/googlefonts/gf-docs/tree/main/Spec#supported-styles
Compare to the last version prior to my changes:
https://github.com/googlefonts/gf-docs/tree/094750a6f6bea04c948bc2aa992d6e1acf622960/Spec#supported-styles
(The changelog view is garbage for this ASCII-formatting for the table, so better compare in HTML view)

Other than the diversification into Mac&Win, the old version had the following mistakes:
* Name ID 1 for ExtraBold & Black was missing the style name
* OS/2.fsSelection for Bold Italic was 5+1, must be 5+0

@m4rc1e please review this as my changes are live.

**Comment by RosaWagner** [comment]
There shouldn't be Mac names in the name tables. We dumped platform 1 ages ago, Fontmake doesn't generate those anymore.

**Comment by yanone** [comment]
Marc said in chat that they are optional. I will keep the columns but clearly mark them as optional.
