### ISSUE TITLE
Error with com.google.fonts/check/fontdata_namecheck

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3300]
## Observed behaviour

💔 ERROR: Familyname must be unique according to namecheck.fontdata.com
com.google.fonts/check/fontdata_namecheck
💔 ERROR Failed to access: http://namecheck.fontdata.com.
This check relies on the external service http://namecheck.fontdata.com via the internet. While the service cannot be reached or does not respond this check is broken.

Happens only for the Italic font of the PR https://github.com/google/fonts/pull/3430

**Comment by felipesanches** [comment]
It works for me. Maybe it was indeed a timeout when the check was run serverside.
There's nothing we can do here unless we're able to replicate the problem.
Feel free to reopen the issue if you see the problem happening again.
