### ISSUE TITLE
Q: unidecode dependency is GPL: problem or not?

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontbakery#3306]
I noticed that the `unidecode` dependency (https://pypi.org/project/Unidecode/) is GPL.

I haven't found clear answers on how that would affect the licensing of code that uses it, such as fontbakery, but at least some answers suggest that simply writing `import some_gpl_module` makes your code derivative and therefore should be GPL.

**Comment by felipesanches** [comment]
@davelab6 do you know the answer to this?

**Comment by felipesanches** [comment]
tracking progress of this at #3316
