### ISSUE TITLE
ReadTheDocs not updating. Build of docs is broken?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3313]
After writing https://github.com/googlefonts/material-icons-vf/issues/296#issuecomment-849335038 I updated the docs in this repo but noticed that the ReadTheDocs page still displays outdated content.

Then looking at https://readthedocs.org/projects/font-bakery/builds/ I see that most of the builds of the docs are labeled as "Failed" throughout the past few years. It is weird that we do see updated content online. Maybe it is just a portion of the content that is breaking the server-side build, while the rest is rendered correctly. I will need to investigate this more carefully.

**Comment by felipesanches** [comment]
I also noticed that, as of today, the page at https://font-bakery.readthedocs.io/en/latest/ has "0.7.34" in its title (visible on the web-browser title bar).

This gives us a hint on roughly when the docs got broken.

The current version of fontbakery on the latest PyPI package is actually 0.7.38, instead. And the code from git which will become 0.7.39 is what the "latest" docs should reflect, while the "stable" docs should show 0.7.38.

Looking at https://font-bakery.readthedocs.io/en/stable/ we can see it is also currently broken, displaying the same 0.7.34 docs.

**Comment by felipesanches** [comment]
well... I built it successfully on my local machine, but it still shows the old 0.7.34 on the readthedocs server. Also, the control panel only seems to list stable release builds, and none of the "latest" ones, which I suppose should match the contents of the git repo's master HEAD as of the date & time of each build.

Maybe the builds take a long time to trigger. I'll give the servers a chance and will double check this only tomorrow. Crossing fingers...

**Comment by felipesanches** [comment]
This still did not work :-P

https://readthedocs.org/projects/font-bakery/builds/14614183/

It builds nicely on my local machine, but remote RTD servers still use the incorrect sphinx version. I am not sure what's the proper way of specifying the sphinx version to run on ReadTheDocs. We'll have to figure it out and try again on v0.8.3 release.

**Comment by simoncozens** [comment]
Try this syntax in the .readthedocs.yml:

```
python:
   version: 3.7
   install:
      - requirements: docs/requirements.txt
      - requirements: requirements.txt
```
