### ISSUE TITLE
Add --icon-font / --not-icon-font flags to override auto-detection

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3324]
#3323 should be addressed before this one.

@tphinney said: "FB could have a flag to force it to treat a font as an icon/non-icon font (flag would override default behaviour of the `is_icon_font` condition)"

Since auto-detection can give us incorrect results, it would be good to have these command-line flags to allow the user to explicitly tell FontBakery that the font family being checked is (or isnt) an icon font project.

**Comment by simoncozens** [comment]
I'm going to do this as a config file thing, *not* as an extra command line argument which only affects a small handful of checks (currently one). So =>#3325
