### ISSUE TITLE
new googlefonts check: check upstream.yaml has required fields

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#3338]
We need a check to ensure that the upstream.yaml files which are created by the gftools packager have all the required fields.

I've just noticed some CJK families are missing the `repository_url` field. https://github.com/google/fonts/pull/3523#pullrequestreview-681610314

Obviously, this check should only be run if the font project contains an upstream.yaml file.

**Comment by felipesanches** [comment]
@m4rc1e what's the severity of this check from 1=lowest to 10=highest?
