### ISSUE TITLE
com.google.fonts/check/whitespace_ink: NotoSansOgham fails

### ISSUE THREAD

**Issue by ctrlcctrlv** [googlefonts/fontbakery#3345]
Ogham fonts require its space character to have ink in most cases. This is a bug.

![image](https://user-images.githubusercontent.com/838783/121928584-4a04d900-cd0e-11eb-9fbc-0539d7a750cc.png)

![image](https://user-images.githubusercontent.com/838783/121928853-951eec00-cd0e-11eb-932a-237cf8c3b841.png)

U+1680,  , OGHAM SPACE MARK, is the only Unicode whitespace character that typically has ink.

This being the case however, I think this check should be downgraded to a warning. Some fonts will want ink in normal U+0020 whitespace, e.g. [FRBAmericanCursive](https://github.com/ctrlcctrlv/FRBAmericanCursive), in its fonts which have guidelines.

**Comment by felipesanches** [comment]
This was a bug in a python expression lacking parentheses. This is fixed now. Thanks for reporting ;-)

**Comment by felipesanches** [comment]
I will keep the check at FAIL level for now. I looked up FRBAmericanCursive, and its usage of a guideline is clearly a corner-case exception.
