### ISSUE TITLE
Ensure OFL licenses have correct body text

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#3352]
We recently pushed some families which had malformed OFL.txt files. Nate had to fix one of them manually, https://github.com/google/fonts/commit/cd0053a201ed4f6c672e7daaa2e43ab3a0b61074

@felipesanches I'm partway through writing the check.

**Comment by felipesanches** [comment]
thanks, @m4rc1e

**Comment by felipesanches** [comment]
Please be sure to specify the severity key on misc_metadata (1=lowest, 10=highest)
