### ISSUE TITLE
Feature, script and language checks

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontbakery#3355]
Fontbakery should provide checks to ensure that all feature, script and language tags referenced in the font are valid according to the OpenType specification.

Rationale: Incorrect tags can be indications of typos, leftover debugging code or questionable approaches, or user error in the font editor. Such typos can cause features and language support to fail to work as intended.

(Examples of the above rationale: Rosarivo has a `lig ` feature instead of `liga`; Noto Sans Mahajani has a dummy `DUMM` feature; Bhavuka has a feature called `    `.)

I propose a new file `Lib/fontbakery/profiles/layout.py` containing the following checks:

* com.google.fonts/check/layout_valid_feature_tags
* com.google.fonts/check/layout_valid_script_tags
* com.google.fonts/check/layout_valid_language_tags

(There'll be another check in same file but I'll open a separate issue for it.)

**Comment by felipesanches** [comment]
Sounds like an `opentype` profile check, right?

**Comment by simoncozens** [comment]
Yes, the checks will be referred to from the opentype profile.
