### ISSUE TITLE
Check for Debg table

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontbakery#3357]
Rationale: The `Debg` table is a useful for testing and debugging layout issues, but does not belong in a production font.

There should be a check ID `com.google.fonts/check/no_debg_table` which reports FAIL if the `Debg` table is present in the font.

**Comment by simoncozens** [comment]
I'm going to change this to `no_debugging_tables` and make it more general. fonttools has the `Debg` table, but there may be other non-production tables (possibly FFTM?) which should be stripped before release.

**Comment by simoncozens** [comment]
Wait, I'm having second thoughts about the whole concept. The GF subsetter removes stuff like FFTM (and *probably* Debg?) before serving. So do we even need it?

**Comment by felipesanches** [comment]
The fact that a specific tool fixes a problem doesn't mean we shouldn't check it. ;-)
