### ISSUE TITLE
incorrect-ofl-body-text: template incomplete

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3372]
## Observed behaviour

This PR https://github.com/google/fonts/pull/3517 is failing because of the Reserve Font Name mention in the OFL.txt.

## Expected behaviour

GF doesn't want font with RFN although some are already onboarded with one, and some may be granted with authorization to have one. Therefore we should allow it in the ofl_body_text check, knowing that it warns about it already.

**Comment by RosaWagner** [comment]
The template should contain the entire header of the license because the middle part is often missing.
Note that `http` and `https` are both allowed.

```
Copyright 20** My Font Project Authors (https://github.com/googlefonts/My-Font-Repository)

This Font Software is licensed under the SIL Open Font License, Version 1.1.
This license is copied below, and is also available with a FAQ at:
https://scripts.sil.org/OFL


SIL Open Font License v1.1
====================================================
```

**Comment by felipesanches** [comment]
It is better to have a few intentional exceptions to the rule than to remove the checking and thus risk having unjustified new RFNs silently ending up on license files.

**Comment by m4rc1e** [comment]
So the issue is that some OFL licenses use http while others use https.

<img width="1392" alt="Screenshot 2021-07-15 at 14 07 11" src="https://user-images.githubusercontent.com/7525512/125793195-0d6a4c85-9b8a-424e-a7ad-d1d5d5c66670.png">


I guess we can use a regular expression so we can allow both.
