### ISSUE TITLE
Check request: verify font.sfntVersion against the presence of glyf and CFF/CFF2

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontbakery#3388]
It's possible to build fonts that have the wrong sfntVersion field, say a TTF with a glyf table, yet with an sfntVersion of "OTTO". Such fonts are rejected by FreeType.

See also: https://github.com/fonttools/fonttools/issues/2370

(I just saw that ots already warns about this, so perhaps it's redundant for fontbakery.)

**Comment by justvanrossum** [comment]
Although: ots only warns for it, for fontbakery it should be a FAIL IMO, as FreeType rejects such fonts.

**Comment by felipesanches** [comment]
> I just saw that ots already warns about this, so perhaps it's redundant for fontbakery.

In general we're happy to substitute 3rd party checks with our own fontbakery checks, specially if we're able to document them with more detailed rationale metadata.

**Comment by felipesanches** [comment]
Correct me if I'm wrong, please. I'm proposing to classify this as a maximum severity check as it seems the font is completely broken if it does not pass this check, right?

**Comment by justvanrossum** [comment]
It depends: FreeType rejects a font with `sfntVersion="OTTO"` and a `glyf` table, yet doesn't have a `CFF ` or `CFF2` table, but other font consumers may not have problems with it. I can't really judge, I'm not familiar enough with fontbakery's severity gradations.

**Comment by felipesanches** [comment]
> I'm not familiar enough with fontbakery's severity gradations.

At this point they're still experimental. We're gradually coming up with a way to categorize checks by perceived severity, but this is still very much subjective.

**Comment by miguelsousa** [comment]
@felipesanches please assign this to me, and add it to the 0.8.9 queue.
