### ISSUE TITLE
Why don't we use an auto formatter such as Black?

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#3396]
This isn't issue, I'm just curious why we don't use something like Black?

I find manually formatting files tedious. I just want to sling code and let an auto formatter do the grunt work.

If there's a way to automate fb code formatting so it passes pylint, I'm all ears.

**Comment by felipesanches** [comment]
No tool currently auto-formats in the style that we use here. I have considered adapting some auto formatter to enforce our code-style, but I still haven't done so.
