### ISSUE TITLE
Stop rejecting MVAR table

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#3400]
## Observed behaviour

fontbakery issues a FAIL message for fonts with MVAR table (`com.google.fonts/check/unwanted_tables`).

## Expected behaviour

Do nothing, MVAR is a valid font table despite some early implementation some three years ago having a bug with it. 

## Resources and exact process needed to replicate

https://github.com/google/fonts/pull/3602

**Comment by davelab6** [comment]
@khaledhosny thanks, I agree that this check ought to change by around now. That was always the idea, to make a decision that was good for the situation at that time and as that situation improve then change the check. So, @m4rc1e please could you queue up redoing the QA testing work you did a few years ago that led to this check decision, so we can document more details about why we'll change it.
