### ISSUE TITLE
remove check "missing link" (designer profile)

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3409]
```
com.google.fonts/check/metadata/designer_profiles
🔥 FAIL Designer Robert Leuschke still does not have a webpage link on the catalog. Please provide one. [code: missing-link]
```

The link entry in the info.pb is actually super useless, having a webpage link in there doesn't do anything in the API, and we actually add the actual webpage link per tradition in the `bio.html`. So it is good to remind to remove the Google+ link, but since few month we leave the entry empty to not break the protobuf. It has been tested and approved. 

Like this:
```
designer: "Robert Leuschke"
link: ""
avatar {
  file_name: "robertleuschke.png"
}
```

**Comment by felipesanches** [comment]
Will the protobuf change to not have that field anymore soon? Or will the link field become more useful later?

I propose downgrading that to a WARN, as structured metadata is a good thing to have.

**Comment by RosaWagner** [comment]
No, not a warn :)

The link entry is still here so the protobuf don't break, and the structure is intact. It is just empty, and we have been doing that for the last 2-3 month are so. Today, we are going to remove all the links from all the catalog. And it will be like that for all the new designer profiles… so really, the check is just asking to do something we don't want and that we correct every time.

**Comment by RosaWagner** [comment]
To resume.

we want this:
`link: ""`

not this:
`link:"www.whateverwebpage.com"`

nor this:
`link: "https://profiles.google.com/117991409563960417265/about"`

Maybe this link entry will one day be useful again and we will be able to fill it up, but asking for html page which is supposed to be in the bio.html, just create bad copy-pasta and errors. It is also more annoying to update info in the protobuf, cause the modification only gets pushed if the bio or the image has changed… or we have to notify specifically the eng team, which is a lot of useless effort for a link that is actually not used in the API.

**Comment by RosaWagner** [comment]
ps: if we remove the link completely, it breaks the push to sandbox. So the eng team told us to not remove it, but having it empty instead.

**Comment by felipesanches** [comment]
Here are the links being removed, in case we may want to find them in the future to be included on the `bio.html` files:
https://github.com/google/fonts/pull/3696/commits/753430f716857836f634b15e6787bd05b8b583e1
