### ISSUE TITLE
Add check to METADATA to ensure sample_text can render in the fonts

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3419]
@twardoch pointed out on chat today that we should have a fontbakery GF METADATA profile check that can help prevent tofu from being seen on fonts.google.com. 

The check needs to intersect 3 things:

1. the full set of Unicode characters in each font in the family
2. what’s in the [subset "encoding" definitions](https://github.com/googlefonts/gftools/blob/main/Lib/gftools/encodings) from gftools, listed in the family's [METADATA](https://github.com/googlefonts/gf-docs/tree/main/METADATA#subsets) file
3. what's in the sample texts for those families, that will be shown on fonts.google.com, which is a new set of `sample_text` data in METADATA files. [Example, Noto Sans Vai](https://github.com/google/fonts/blob/1531a1e46b7c4a719e023cb63aad1bf8b17d0836/ofl/notosansvai/METADATA.pb#L19-L30)

I believe we may have a new public repo for even more sample text data, and perhaps even the code that produces METADATA.pb's `sample_glyphs` data; and perhaps that code can itself do this intersection.

**Comment by felipesanches** [comment]
I think that the **can_shape** method of @simoncozens' `vharfbuzz` python module (which fontbakery uses) can decide whether all those glyphs and sample strings can be rendered.

**Comment by felipesanches** [comment]
We'll need the updated description of the METADATA.pb protobuf schema. I see that the one in gftools still does not include these `sample_glyphs` or `sample_text` fields.

We've already had this kind of problem in past updates of the schema. I'd like to request that the METADATA.pb schema be kept in a public repo so that our tools can be kept in sync.

And I have the same request for the designers catalog `info.pb` schema.

**Comment by simoncozens** [comment]
> I think that the **can_shape** method of @simoncozens' `vharfbuzz` python module (which fontbakery uses) can decide whether all those glyphs and sample strings can be rendered.

D'oh. I forgot that method exists and re-implemented it in `fontbakery.utils`...

**Comment by felipesanches** [comment]
well.. I think I was actually referring to your `fontbakery.utils` implementation that I've just learned about this morning :-)
