### ISSUE TITLE
Upstream repo check: Is repo set up for Bower?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#342]
As per https://twitter.com/savinger/status/478940097086111744 it would be good to do an upstream test to see if the repo is set up with Bower.

This issue is currently a placeholder for the idea, which needs more thought. 

http://www.polymer-project.org/articles/distributing-components-with-bower.html may be relevant.

**Comment by davelab6** [comment]
Do we check upstream repos?

**Comment by felipesanches** [comment]
we don't

**Comment by davelab6** [comment]
I'm reopening as this is on the roadmap... v2.0.0 is a fine milestone for it

**Comment by felipesanches** [comment]
cool, thanks!

**Comment by felipesanches** [comment]
we don't test upstream sources

**Comment by felipesanches** [comment]
well... I see that @davelab6 likes to keep it as a future milestone... so reopening.

**Comment by simoncozens** [comment]
I don't think we want to check for bower (we don't use that in our template repo, now that we have one), and we have a separate issue (#1772) for checking the upstream repo, so let's carry on the discussion there.
