### ISSUE TITLE
Add check for gf repo dir name

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3421]
`fonts/ofl/azeret` was added and METADATA has

    name: "Azeret Mono"

therefore the directory should be 

`fonts/ofl/azeretmono`

So I'd like to propose a FB METADATA check that checks the dir name against the METADATA name key, lowercased and spaces removed. 

We'll then need an allowlist of legacy exceptions to this.

cc @RosaWagner

**Comment by RosaWagner** [comment]
Good idea.
This is a bit strange cause the all process was made with Packager, which is supposed to do that already, no?
