### ISSUE TITLE
Font Bakery installation problems

### ISSUE THREAD

**Issue by retypefoundry** [googlefonts/fontbakery#3437]
(**NOTE:** If your issue is related to a specific check, please consider mentioning its check-id on the issue title.)

## Observed behaviour

I've tried to install Font Bakery under Big Sur but I can't go beyond the command:

`pip3 install fontbakery`

because the terminal will always return:

`Killed: 9` (full output)

Any idea on how to sort this out?

## Expected behaviour

(Describe here what you expected to happen, or what you wish was different)

## Resources and exact process needed to replicate

M1 iMac running OSX 11.5.1.

**Comment by anthrotype** [comment]
Segfault is no good. Can you copy and paste the full console log before that? Maybe try to pip install --verbose

**Comment by jenskutilek** [comment]
Maybe the installation doc should not recommend installing via homebrew: https://justinmayer.com/posts/homebrew-python-is-not-for-you/

I always use the official Python installers from python.org and haven’t had any problems with them.

**Comment by felipesanches** [comment]
@RosaWagner could you please verify whether your installation procedures on M1 would also work for @retypefoundry here?

**Comment by simoncozens** [comment]
I think we have smoothed out most of the M1 issues now, and as unfortunately we didn't get any additional information from @retypefoundry I'm going to close this.
