### ISSUE TITLE
com.google.fonts/check/license/OFLbodytext bug when no OFL file is found

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery#3455]
## Observed behaviour

When running FB tests on a project that doesn't have an OFL file yet in the folder, the check is reporting it as an `ERROR` with a final message `TypeError: argument of type 'NoneType' is not iterable`.

<details>
<summary>💔 <b>ERROR:</b> Check OFL body text is correct.</summary>

* [com.google.fonts/check/license/OFL_body_text](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/license/OFL_body_text)
<pre>--- Rationale ---
Check OFL body text is correct. Often users will accidently delete parts of the
body text.</pre>

* 💔 **ERROR** The condition <FontBakeryCondition:is_ofl> had an error: TypeError: argument of type 'NoneType' is not iterable

</details>

## Expected behaviour

You would like to have a `FAIL` instead of an `ERROR` with a clearer message about you are missing the file. 
Perhaps the rationale could say something like: "No license file was found for this project. Please, include one following this template https://github.com/googlefonts/Unified-Font-Repository/blob/main/OFL.txt"

**Comment by felipesanches** [comment]
Works fine here on version 0.8.7

Perhaps I may have fixed it a while ago. Please reopen if you ever see this ERROR again.

**Comment by felipesanches** [comment]
Oh! I see now that it was fixed by #3394 and that this issue was a duplicate of #3393

**Comment by felipesanches** [comment]
> Perhaps the rationale could say something like: "No license file was found for this project. Please, include one following this template https://github.com/googlefonts/Unified-Font-Repository/blob/main/OFL.txt"

This is a nice suggestion, aligned with what's proposed at issue #3277
