### ISSUE TITLE
FAIL if legacy accents have anchor or width=0

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3490]
@yanone, you mentioned this today on a video call.

Could you please describe the proposed new check in more details?

**Comment by yanone** [comment]
The `gravecomb` (and related) accents is expected to have a width of `0` and is used for accented glyph composition, while the legacy `grave` character (and related) are expected to have a positive width as they are used in text setting such as for the backtick.

I would check for width of `0` for the `*comb` accents, and for positive sidebearing (not just positive width) for the legacy accents.

**Comment by yanone** [comment]
Oh, about the severity:

`*comb` accents to have a positive width or sidebearing is okay, as they are positioned in the font using anchors, so maybe a WARN here?

But legacy accents to have a negative sidebearing on either side should be a FAIL in my opinion, as these are used in text.

**Comment by RosaWagner** [comment]
Note: there is a similar WARN-check for marks in GDEF. But There should be a particular FAIL if one of the 13 legacy accents end up in the GDEF table, or have anchors, or have 0-width.

**Comment by yanone** [comment]
Currently, anchor support is not easy to calculate using fontTools.

But in any case, I'm combining several checks related to legacy accents into one (width being one of them), so I'm closing this issue and continue here: https://github.com/googlefonts/fontbakery/issues/3959
