### ISSUE TITLE
[com.google.fonts/check/STAT/gf-axisregistry] Add support for `wdth: Medium`?

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/fontbakery#3505]
I get a Font Bakery error telling me that `Medium` is not a supported `wdth` axis name: https://github.com/cbcrc/radiocanadafonts/runs/4181596599?check_suite_focus=true
```
 >> Check:   com.google.fonts/check/STAT/gf-axisregistry
    Desc:    Validate STAT particle names and values match the fallback names in GFAxisRegistry. 
    Files:   Radio-Canada-Italic[wdth,wght].ttf

     FAIL On the font variation axis 'wdth', the name 'Medium'                  
          is not among the expected ones (UltraCondensed, ExtraCondensed,       
          Condensed, SemiCondensed, Normal, SemiExpanded, Expanded,             
          ExtraExpanded, UltraExpanded) according to the Google Fonts Axis      
          Registry. [code: invalid-name]                                        
    Result: FAIL
```

But see the OpenType docs, Medium is the default here: https://docs.microsoft.com/en-us/typography/opentype/spec/os2#uswidthclass

And also in Glyphs: 
<img width="308" alt="glyphs-medeum" src="https://user-images.githubusercontent.com/5162664/141354838-8d88d4c6-332c-4ef2-b3f5-4674479e7498.png">

**Comment by felipesanches** [comment]
yes, but on the GF Axis Registry it is called `"Normal"` instead:

https://github.com/google/fonts/blob/main/axisregistry/width.textproto#L26

**Comment by eliheuer** [comment]
Glyphs defaults to `Medium` and it is not easy to change that to `Normal` in the Glyphs UI.

**Comment by felipesanches** [comment]
Perhaps we should open an issue on the `google/fonts` git repo then, to add this as yet another valid name on the GFAxisRegistry.

**Comment by felipesanches** [comment]
What I mean is that this FontBakery check simply enforces whatever the GFAxisRegistry specifies.

**Comment by eliheuer** [comment]
Got it, I'll make an issue there. Thanks!

**Comment by felipesanches** [comment]
I've just read @RosaWagner's remarks at https://github.com/google/fonts/issues/4058#issuecomment-966979222

What could we do in FontBakery to clarify this matter to our users?

**Comment by RosaWagner** [comment]
I don't think there is not much to clarify for that particular case, the usWidthClass is not a parameter that has an incidence on the STAT table. 

What we can say is:

Setting up a proper STAT table in Glyphs (the way GF is expecting it) is not possible in a simple way at the moment. We recommend to patch it on binaries with [gftools gen-stat](https://github.com/googlefonts/gftools/blob/main/bin/gftools-gen-stat.py) — using either default settings (data from the [Axis Registry](https://github.com/google/fonts/tree/main/axisregistry)), or a `.yaml` file for custom values. 

`gftools builder` is a special tool for exporting fonts that wraps Fontmake and several post-process scripts. You can customise the STAT table directly in the same config yaml file as the one used for the `builder`, see [Texturina's config file](https://github.com/Omnibus-Type/Texturina/blob/master/sources/config.yaml) as an example.

**Comment by davelab6** [comment]
Sadly I think we need to close this as WAI. @eliheuer do you agree?

**Comment by felipesanches** [comment]
FYI, IIRC, WAI means "Works As Intended"

**Comment by eliheuer** [comment]
Yes, closing now. :-)
