### ISSUE TITLE
check-universal missing in 0.8.4?

### ISSUE THREAD

**Issue by NightFurySL2001** [googlefonts/fontbakery#3510]
When upgrading from 0.7.38 to 0.8.4 using `pip3 install -U fontbakery`, most of the check listed on https://font-bakery.readthedocs.io/en/stable/user/USAGE.html is missing (including `check-universal`), only leaving `check-googlefonts` available (and a new undocumented `check-opentype`).

```
usage: fontbakery [-h] [--list-subcommands]
                  [{build-contributors,check-googlefonts,check-opentype,check-specification,check-ufo-sources,generate-glyphdata}]

Run fontbakery subcommands. Subcommands have their own help messages. These
are usually accessible with the -h/--help flag positioned after the
subcommand, i.e.: fontbakery subcommand -h

positional arguments:
  {build-contributors,check-googlefonts,check-opentype,check-specification,check-ufo-sources,generate-glyphdata}
                        The subcommand to execute

optional arguments:
  -h, --help            show this help message and exit
  --list-subcommands    print the list of subcommnds to stdout, separated by a
                        space character. This is usually only used to generate
                        the shell completion code.
```

**Comment by felipesanches** [comment]
Is it only missing on the usage message? Or is the universal profile really unavailable in your local installation?

**Comment by felipesanches** [comment]
Also, what's the operating system in which you're trying this?

**Comment by NightFurySL2001** [comment]
Oops, sorry just found out that the version identified is my mistake when upgrading by using `pip` instead of `pip3`, which installs fontbakery 0.4. A clean uninstall of fontbakery on `pip` and `pip3` and then reinstall solve the issue.
