### ISSUE TITLE
com.google.fonts/check/contour_count -> Suggestion for ⅘ uni2158

### ISSUE THREAD

**Issue by NightFurySL2001** [googlefonts/fontbakery#3511]
Not sure if it is the right place, but ⅘ can be done with 3 contour if the design of 4 is open-ended. The test did not warn the contour count for 4 or other related contour to 4, so I am guessing it is overlooked.

```
The following glyphs do not have the recommended number of contours:

 • Glyph name: uni2158     Contours detected: 3    Expected: 4

[code: contour-count]
```

**Comment by felipesanches** [comment]
yes, the issue tracker is **always** the right place to report problems ;-)

The data used in this check was inferred from a preexisting collection of font files from the Google Fonts collection. This is obviously biased and likely lacks cases like the one you brought up. We're happy to gradually improve the check by incorporating suggestions like this one.

I'll review this and likely include your case in the expected contour count data.

**Comment by felipesanches** [comment]
yes, your suggestion makes total sense ;-)
