### ISSUE TITLE
Wrong Fail on OS/2 usWeight class 

### ISSUE THREAD

**Issue by Fonthausen** [googlefonts/fontbakery#3524]
(**NOTE:** If your issue is related to a specific check, please consider mentioning its check-id on the issue title.)

## Observed behaviour

Fontbakery failed the OS/2 usWeight values on the Radio Canada fonts. All weight classes should have been 400 according to fontbakery.
 
## Expected behaviour

Weight classes are ok in yaml file. So it should not be a FAIL

## Resources and exact process needed to replicate

https://github.com/cbcrc/radiocanadafonts/issues/20

**Comment by RosaWagner** [comment]
Should be "Radio Canada" with a space, if the family name is not the exact same as in the file (name ID 16), then the instances won't generate

**Comment by eliheuer** [comment]
I merged the [PR with the space in the name](https://github.com/cbcrc/radiocanadafonts/pull/24), but Fontbakery still reports the same number of fails, including many `Checking OS/2 usWeightClass` fails like below:

```shell
 >> Check:   com.google.fonts/check/usweightclass
    Desc:    Checking OS/2 usWeightClass.
    Files:   Radio-Canada-Light.ttf

     FAIL OS/2 usWeightClass is '300' when it should be '400'.                  
          [code: bad-value]                                                     
    Result: FAIL
```

**Comment by RosaWagner** [comment]
The family name of the font in Glyphs is still "Radio-Canada" with an hyphen

**Comment by eliheuer** [comment]
The hyphen in the name is how CBCRC stylizes the name, and was the family name in the original fonts.
<img width="321" alt="radio-canada-name" src="https://user-images.githubusercontent.com/5162664/144428228-2a2dddab-3972-4c9e-b8e8-46e628ff9cf1.png">

https://www.behance.net/gallery/56728851/Radio-Canada-typeface

**Comment by RosaWagner** [comment]
Then this is an edge case that might messes up with the naming scheme and how the builder and/or fontbakery are checking instances names? We are supposed to have family name on one side of the hyphen, and stylename on the other side.

I would suggest to build the font with a standard family name (no hyphen) to see if it resolves the fontbakery fails and then see from there. 

Also if the font goes into GF Library, I am not sure if the hyphen would be wise. People could have a hard time searching/finding the font if there is an hyphen in the family name. Maybe validate that with @davelab6 and we see how to make an exception for Fontbakery not raising fails for that?

**Comment by eliheuer** [comment]
I asked Julie at Radio-Canada about the name change and this was the response:
> In the Google suite it's actually named Radio Canada without a hyphen. We were fine with that considering the original OTTT / TTF have the proper name Radio-Canada.

**Comment by felipesanches** [comment]
I can improve the user experience in cases like this one by providing a special warning message if more than a single hyphen is used on a given font file name.
