### ISSUE TITLE
Add GF check for METADATA subsets with zero support

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3533]
https://github.com/google/fonts/commit/7e9614e62788866e92749c2d9b35881cbdbb60a5

This was caught by an internal lint check, 

> Ruslan Display declares cyrillic-ext but supports none of the codepoints

There should be a fontbakery check for this that FAILs the PR before it gets merged :)

cc @RosaWagner

**Comment by felipesanches** [comment]
I think the best way to handle this would be to migrate the .nam files describing the GF glyph sets to a separate repo and add a few python methods that parse these .nam files, and then use this as a FB dependency (as well as in any other tool that might need it)

**Comment by felipesanches** [comment]
`GF_latin_core`  is currently hardcoded in fontbakery's codebase (on the constants.py file), but we should have a generic solution for all subsets, that's what I mean.

**Comment by felipesanches** [comment]
![Screenshot from 2021-12-13 22-54-30](https://user-images.githubusercontent.com/213676/145918727-1230e6f3-4682-4db6-a15c-6b1c0fcdb291.png)

**Comment by felipesanches** [comment]
Now we have a check for that ;-)

It is not implemented in the ideal manner though... I wish we could support all subsets. But for that we'll need some major refactoring on how we handle GF glyphsets in our tooling. I'll try to come up with something reasonable soon.

**Comment by davelab6** [comment]
That's ok, coming back to fix it later is good, but currently this only checks 2 of the subsets, so it's not making the push process all that much less error prone. 

Since the checks change very rarely, I suggest to hard code them all like these 2 and refactor later

**Comment by felipesanches** [comment]
I've migrated the relevant portions of gftools to a new python package that I called `glyphsets`. Its first release (v0.1.0) is here: https://pypi.org/project/glyphsets/0.1.0/

**Comment by felipesanches** [comment]
now, using that new python module, all subsets are properly checked

**Comment by felipesanches** [comment]
next step is to make gftools use the new module, to avoid data duplication
