### ISSUE TITLE
SVG markup renders upside-down on check/shaping/collides

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3558]
![Screenshot from 2022-01-25 23-55-26](https://user-images.githubusercontent.com/213676/151101569-8babc1fd-bf0d-4952-a640-9ba9fcc69494.png)

when copying and pasting this SVG snippet, saving it into a proper `output.svg` file and loading it in Inkscape I see the glyphs rendered upside-down (it should be `ïï`):
![Screenshot from 2022-01-25 23-54-49](https://user-images.githubusercontent.com/213676/151101724-3a77dea0-6bf9-4b1d-9076-f73d54f9d356.png)

(issue originally found at #3554)

**Comment by simoncozens** [comment]
When using the HTML and MD reports (which is the only sensible way to view this information ;-) browsers apply the transform matrix in the SVG element which makes it the right way around.

Ideally I would like to provide a summary in the console report, but I don't think we have the facility to provide separate reporting based on output format.

**Comment by simoncozens** [comment]
I don't think this is a bug. It's more of a "Doctor, it hurts when I do this..." The fix is "don't cut and paste terminal output into a SVG file".
