### ISSUE TITLE
com.google.fonts/check/varfont/grade_reflow: cleanup output

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#3561]
com.google.fonts/check/varfont/grade_reflow is a fabulous check. However, it returns a list of glyphs which often contains duplicates. It may be better to use a set instead.

**Comment by felipesanches** [comment]
This can be seen by running the check against `ofl/robotoflex/RobotoFlex[GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght].ttf`

![Screenshot from 2022-01-26 21-27-15](https://user-images.githubusercontent.com/213676/151269319-5725fbea-91a8-4a9a-8956-d15fb50780dc.png)

**Comment by felipesanches** [comment]
@m4rc1e, now it is working as expected:

![Screenshot from 2022-01-26 22-04-46](https://user-images.githubusercontent.com/213676/151272728-8ffef2c6-bc83-498f-beac-ccdb9676bf4a.png)
