### ISSUE TITLE
PyPI Source Releases

### ISSUE THREAD

**Issue by yellowsquid** [googlefonts/fontbakery#3573]
## Observed behaviour

I attempted to create a [Guix](https://guix.gnu.org) package for fontbakery by downloading the `v0.8.5` source code from PyPI. However, there is no source release on PyPI.

## Expected behaviour

Like almost all other packages, I expected there to be a source release on PyPI

## Resources and exact process needed to replicate

Navigate to the [PyPI releases page](https://pypi.org/project/fontbakery/#files) and observe there are no source releases. Compare with other tools (e.g. all of the [current requirements](https://github.com/googlefonts/fontbakery/blob/3228e20d108726fc35bd0e09211e7ffe38559029/requirements.txt)) and observe they do have a source release.

**Comment by yellowsquid** [comment]
Looking through the maintainer notes, [this line](https://github.com/googlefonts/fontbakery/blob/3228e20d108726fc35bd0e09211e7ffe38559029/docs/source/maintainer/maintainer-notes.md?plain=1#L91) appears to be the problem.

The [Python Packaging User Guide](https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives) suggests that you should run `python3 -m build`. The maintainer guide says to run `python setup.py bdist_wheel --universal`, which only generates the binary archive.

I do not know enough about PyPI to know whether source releases can be added retroactively.

**Comment by felipesanches** [comment]
hey, that's great news! Thanks for putting the effort to package it to a software freedom respecting distro endorsed by the FSF ;-)

I have just read the pypi documentation you referred to and it seems really straight forward to also publish source packages on PyPI. I am about to cut a new FontBakery 0.8.6 release and I'll take the opportunity to try this now.

**Comment by felipesanches** [comment]
https://pypi.org/project/fontbakery/#files
![Screenshot from 2022-01-29 03-29-07](https://user-images.githubusercontent.com/213676/151650354-bb6a6c75-70f2-4b00-8927-0df89757f57d.png)

**Comment by felipesanches** [comment]
I've also uploaded to PYPI the sources of the last few releases (the entire 0.8.x series).

Here's an example (https://pypi.org/project/fontbakery/0.8.0/#files):
![Screenshot from 2022-01-29 03-31-21](https://user-images.githubusercontent.com/213676/151650413-295ca88e-6bf1-4a9b-beb3-974de0299e9e.png)

**Note:** even though it says `py2` / `py3`, fontbakery is actually python3-only. I'm glad that the new way of building the PyPI packages takes care of fixing that mislabeling as well.

**Comment by felipesanches** [comment]
I've also generated the 39 packages of the 0.7.x series and uploaded them to PyPI this way:

```
rm dist/*
for tag in $(git tag | grep v0.7); do git checkout "$tag"; python3 -m build; done
python3 -m twine upload dist/*.tar.gz
```

Not sure if there's any value in posting source packages for the entire history of releases since `v0.1.0`... If you think it is worth doing so, I can run the same script for the rest of the git tags. But I'd like to wait a bit just to be sure there's nothing wrong with these packages I've posted today.

**Comment by felipesanches** [comment]
@yellowsquid, is this good for you?

**side-note:** I've been starting to learn a bit about Debian packaging. And I may work a bit (on my free time) on packaging some of fontbakery's dependencies (and maybe someday FontBakery itself) on Debian.

The tar.gz source files made available on PyPI seems to be good (and seems to be exactly what's needed for Debian, which should really not be much different from what any other distro would need. So I assume it is all good.

I'm closing the issue now, but please feel free to reply here anyway ;-)

**Comment by yellowsquid** [comment]
> @yellowsquid<https://github.com/yellowsquid>, is this good for you?

It looks good to me. Thanks for the work!
