### ISSUE TITLE
Is the right glyphset checked for minimal glyphs coverage?

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3583]
Last update of Fontbakery brought a bunch of missing codepoints that are actually not required in `GF Latin Core`.

In report for ABeeZee I got these fails:
(https://github.com/google/fonts/issues/4227#issuecomment-1027736423)

```
🔥 FAIL: Check `Google Fonts Latin Core` glyph coverage.
com.google.fonts/check/glyph_coverage
--- Rationale ---
Google Fonts expects that fonts in its collection support at least the minimal
set of characters defined in the `GF-latin-core` glyph-set.
🔥 FAIL Missing required codepoints:

0x02BB (MODIFIER LETTER TURNED COMMA)

0x02BC (MODIFIER LETTER APOSTROPHE)

0x2002 (EN SPACE)

0x2009 (THIN SPACE)

0x200B (ZERO WIDTH SPACE)

0x2032 (PRIME)

0x2033 (DOUBLE PRIME)

0x2122 (TRADE MARK SIGN)

0x2191 (UPWARDS ARROW)

0x2193 (DOWNWARDS ARROW)

0xFEFF (ZERO WIDTH NO-BREAK SPACE)

And 0xFFFD (REPLACEMENT CHARACTER)
[code: missing-codepoints]
```

None of those are in:
https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/GF%20Glyph%20Sets/GF-latin-core_unique-glyphs.nam

--> Fontbakery should check `Latin Core`, and not another one.

**Comment by RosaWagner** [comment]
Having this issue with 0.8.7

`Soft-hyphen` and `division slash` are not in the nam file anymore. So I wonder if we are now using the last version of the glyphset.

```
🔥 FAIL: Check `Google Fonts Latin Core` glyph coverage.
* [com.google.fonts/check/glyph_coverage](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage)
🔥 FAIL Missing required codepoints:

0x00AD (SOFT HYPHEN)

0x00AF (MACRON)

0x2074 (SUPERSCRIPT FOUR)

And 0x2215 (DIVISION SLASH) [code: missing-codepoints]
```

**Comment by felipesanches** [comment]
I will review this.

**Comment by felipesanches** [comment]
I'm sorry, I'll have to postpone this to the next release because #3675 is critical and urgently requires a new release as it is already fixed on git.

**Comment by felipesanches** [comment]
The recent work by @RosaWagner and @m4rc1e at #3753 is supposed to have fixed this. Please reopen the issue otherwise.

**Comment by vv-monsalve** [comment]
Inspecting this [FB report](https://github.com/google/fonts/issues/3756#issuecomment-1079109361), I see `division slash` is still reported as missing. Is the check using the latest [.nam file](https://github.com/googlefonts/glyphsets/blob/main/GF_glyphsets/Latin/nam/GF_Latin_Core.nam)?

**Comment by vv-monsalve** [comment]
I've seen the FB version was `0.8.8.dev29+g809e15c6` so closing the issue.
