### ISSUE TITLE
ABeeZee camelcase still not allowed

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3584]
I allowed ABeeZee in #3569 
Version used is 0.8.6

But report still failing for the camelcase name. Or maybe I am missing something in the sources or I should have done something more in Fontbakery… I don't know. 
cf https://github.com/google/fonts/issues/4227#issuecomment-1027736423

**Comment by felipesanches** [comment]
yeah, that's right. I have jut figured out the problem. I'm working on a fix now. Thanks, @RosaWagner
