### ISSUE TITLE
Name ID 16 and 17 not required for variable fonts.

### ISSUE THREAD

**Issue by moontypespace** [googlefonts/fontbakery#3597]
## Observed behaviour

Hi,
for me it makes not too much sense to have name ID 16 and 17 set in a variable font. 
Often we only have two fonts linked to each other 'Upright' and 'Italic', why name ID 1 and 2 are enough.
I am with you when it comes to static fonts.

## Expected behaviour

The following should not fail when there is a variable font with no name ID 16 and 17:
https://github.com/googlefonts/fontbakery/blob/702eb54cb6bc1453975ed5db1e377ce900484bb6/Lib/fontbakery/profiles/googlefonts.py#L3510-L3516

## Resources and exact process needed to replicate

I am very sorry, but cannot share any fonts with you.

**Comment by m4rc1e** [comment]
The name table, fsSelection, usWeight class bits etc should be set according to the default values of the fvar table. If the default values are {"wght": 200, "width": 100}, one would expect there to be nameIDs 16, 17 since we use the RIBBI naming schema.

> A variable font has a default instance, with axis parameter values set to the defaults defined for each axis in the 'fvar' table. Several tables in the font provide default values for many different data items — such as positions of glyph outline points in the 'glyf' table, or a font-wide ascender distance in the OS/2 table. The default instance of a font uses the default values for such items without any adjustments, and the variation-specific tables are not needed. If the variation-specific tables — 'fvar', 'gvar', MVAR, etc. — were to be removed from the font or ignored, the remaining data would comprise a complete font for the default instance.

https://docs.microsoft.com/en-us/typography/opentype/spec/otvaroverview#introduction

**Comment by moontypespace** [comment]
@m4rc1e  Thanks a lot for your fast, great and valid feedback. I really much appreciate the quality of the conversations :)

When reading the definition you shared, it sounds like in the case of {"wght": 200, "width": 100} you would need to name it 'ExtraLight' as well. Something like that:
name ID 1: Family Name ExtraLight
name ID 2: Regular
name ID 16: Family Name
name ID 17: ExtraLight
name ID 25: Family Name

But this is not what I would do in a variable font, just because the default value is 200, even thou the default outlines are 'ExtraLight'.
Mmmhh, not sure what the right approach is.

**Comment by m4rc1e** [comment]
I mean a VF is merely a static font with a few more VF tables. Doesn't it make more sense to ensure that if you stripped away the VF tables, you'd end up with a static font where the bits and name records match? this is kind of the point I was alluding to with the quote,

> If the variation-specific tables — 'fvar', 'gvar', MVAR, etc. — were to be removed from the font or ignored, the remaining data would comprise a complete font for the default instance.

**Comment by moontypespace** [comment]
Sure, makes totally sense. But then you would always have to have the default set to 'Regular', because otherwise you end up having weird variable font names with weight names like 'ExtraLight' in name ID 1 or 17. And that makes no sense to me.
Usually I try to make the default of a variable font to be 'Regular'. But in my case having the 'Light' as the default instance makes the file size of the font a lot smaller.

**Comment by RosaWagner** [comment]
Ah I was writing about that yesterday for the new spec:

> The important thing to know is that the font origin will be the actual default instance displayed in environments that don’t support the variable font format. For example, if the font origin of the font is the `Thin` style, then in some environments, only the Thin instance will be displayed. GF tends to seek consistency between the name and the displayed font. and the full name of the variable font will be `Font Name Thin`. It often happens that designers are annoyed by that. The only way to workaround that is to generate a `Regular` master and make it the zero origin of the font, or to modify directly the name tables (as GlyphsApp does if you export from it). We don’t recommend any of those tricks; the first one will increase the file size, and the second one will create an inconsistency between the style displayed by default and the style name.

My idea, is that it is a foundry decision. On browsers and OS version that don't support VF, only the default master will be displayed. On GF side, a lot of users are reacting on any inconsistencies, so we prefer the font name to be consistent with the default instance. If you see a light instance by default but it is called Regular, it creates confusion.
