### ISSUE TITLE
Italic metadata are consistent in Italic fonts (universal?)

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3611]
I am working on fixing Nunito (variable) that has one source with an ital axis, and we slice it in post-process to generate 2 VFs. Some stuff related to the italic font were missing and Fontbakery didn't raise any warning.

Also this is useful cause GlyphsApp doesn't still set the italic style linking properly to link 2 VFs, and you can only see it if you look inside the font tables. These are also common practice and wouldn't kill to have it in Universal Profile.

I attach here the test case, a "good" and a "bad" with the current report:
[ItalicStyleLinking.zip](https://github.com/googlefonts/fontbakery/files/8132507/ItalicStyleLinking.zip)

All these checks should be triggered if "Italic" is part of the file name, or `NameID2`, or `NameID17`.

- [x] #3663 
- [x] #3664
- [x] #3665
- [x] #3666
- [x] #3667
- [x] #3024 
- [x] #2934 
- [x] #3668
- [x] #3669
- [x] #3670

**Comment by RosaWagner** [comment]
@felipesanches I finished my review but I would also like opinion from @vv-monsalve and @m4rc1e before doing the fragmented issues.

**Comment by felipesanches** [comment]
@RosaWagner, thanks for all the effort put in here, but I feel this is "a fish too big to fry". There's way too much stuff in a single issue, so I would be happy if you could indeed split it into smaller / more focused issues, as you mentioned a few messages above.

@m4rc1e and @vv-monsalve, have you already read this issue? What are your thoughts?

**Comment by RosaWagner** [comment]
Done @felipesanches 
I think 3 weeks are enough to wait for feedback. Let's go with no comment, no problem.
I didn't link the test case in all of them, but it is in this issue, with all the issues mentioned.

**Comment by felipesanches** [comment]
thanks a lot! :-D

**Comment by vv-monsalve** [comment]
I was finally able to go through all the items included. It was a good compiling @RosaWagner.
Although I have to say that having them in separated issues really made it more accessible, so I see better now Felipe's point on requesting it to be that way ;)

I've left comments on the separated issues, but the in first one #3663 is the reasoning done for all the others.

**Comment by colinmford** [comment]
+1 for adding these checks, I just ran into the exact same situation as you describe in the original post — a font made from a DS document with an ital axis was missing some italic style linking details and FontBakery didn't raise a single issue. I think these checks would be very helpful!

**Comment by yanone** [comment]
@colinmford Glad to read you’re using fontbakery. Fistbump.

**Comment by felipesanches** [comment]
thanks, @yanone

**Comment by yanone** [comment]
Wohoo 🎉
