### ISSUE TITLE
Question: Why no GH releases?

### ISSUE THREAD

**Issue by miguelsousa** [googlefonts/fontbakery#3628]
Is there a particular reason for not issuing GitHub releases?
I'm interested in being notified when a new version of Font Bakery is out, but there's no way to subscribe to tags.

It's fairly simple to automate the process, which can even include uploading the wheel files to PyPI.
Below are a couple of examples of how we do it. These GH Actions only trigger when tags are pushed.
Since Font Bakery is a Python-only project, the build steps will be even simpler than these examples.
The AFDKO project attaches the wheels to the GH release, whereas PSAutohint doesn't.
- https://github.com/adobe-type-tools/afdko/blob/develop/.github/workflows/build_wheels.yml
- https://github.com/adobe-type-tools/psautohint/blob/master/.github/workflows/build_wheels.yml

**Comment by felipesanches** [comment]
Thanks for pointing this out. I'll see what I can do.

**Comment by miguelsousa** [comment]
👍 Thanks. LMK if you have any questions.

**Comment by miguelsousa** [comment]
BTW, the best way to test any WIP actions that make calls to PyPI is to use pre-release tags. So for example, if your upcoming release is `0.8.8` you can safely use `0.8.8a0`, `0.8.8a1`, `0.8.8a2`, `0.8.8b0`, `0.8.8b1`, etc. as tags, without messing up your release plans. Keep in mind that, once a release (be it pre- or final) is posted to PyPI it cannot be replaced or modified, and the tags of any subsequent release must be higher. Mentioning it in case you're not aware of these gotchas.
