### ISSUE TITLE
Downgrade post format 3 FAIL to WARN in universal profile

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/fontbakery#3635]
The current rationale for the post table format 3 fail points to Apple documentation that indicates the following:

> Apple recommends against using 'post' table format 3 under most circumstances, as it can create problems with some printer drivers and PDF documents. The savings in disk space usually does not justify the potential loss in functionality.

There has been discussion about this issue in a different forum that I'll summarize here with a recommendation to downgrade the universal profile presence of post 3 format table FAIL to a WARN in TT font format builds.

#### @khaledhosny 

> I checked fonts shipped with Windows a while ago and almost all of them used version 3 post table, so I think the printer driver issue is a red herring.

#### @tphinney 

> So, 'post' format 3 is for TT only, and it omits the glyph names. So it is a tiny bit smaller.
>
>The POSSIBLE problem is that under the right combo of circumstances, one can generate PDF from such a font, and not have accurate backing store for any text that has non-default glyphs for a given codepoint. It will look fine but not be searchable. This can affect Latin text with high-end typography, and some complex script writing systems, especially with higher-quality fonts.
>
>Those circumstances generally involve creating a PDF by first printing a PostScript stream to disk, and then creating a PDF from that stream without reference to the original source document.
>
>There are some workflows where this is a thing, but… not at ALL common today.
> 
>I would definitely consider this WARN and not FAIL, today. Hell, even back say in 2015 I would have said so.
>
>Back in the 90s we at Adobe considered it a corner case worth caring about, especially seeing as we were responsible for PDF and Acrobat was one of our products. But I sure wouldn’t sweat it much, today.
>
>Even early 00s. But not now.

#### @simoncozens 

> Any PDF generator worth its salt should be putting ActualText records in there anyway.

#### @twardoch 

> ... and even the more primitive PDF Engines will at least put ToUnicode = a "cmap" for of thing that maps codepoints to glyphs. 
>
>(Just to summarize for others, there are basically 3 methods of extracting text from PDF: the ActualText data structure stores full Unicode text strings, ToUnicode is embedded alongside a font and maps Unicode codepoints to glyphs, and only if that does not exist, glyph name parsing. Well, finally there's the 4th one, which is OCR of course.)

#### @tphinney 

>>> Any PDF generator worth its salt should be putting ActualText records in there anyway.

>Yes—although under the particular gnarly scenarios in question, it would be unable to do so correctly.
>
>Still, these are just super corner cases, and it isn’t crazy to tell people in these situations that their workflow is TEH BROKEN, and they may have to use another font.
>
>I have to admit, my memory of details on some of this are shaky. It has been 15+ years since I really had to worry about it!

#### @davelab6 

> Ok I'm convinced, I suggest we update the universal profile with this as warn and explain why Apple's note is stale

**Comment by chrissimpkins** [comment]
It appears that the check also enforces fails when the following conditions are not met:

- OTF CFF2 var fonts must have post 2 table
- OTF fonts otherwise must have post 3 table

Do we need these to remain in place (at all?, as warns?)

**Comment by khaledhosny** [comment]
Fonts with `CFF` table are treated exceptionally because the `CFF` table stores glyph names itself, but `CFF2` table does not and it should be handled the same as fonts with `glyf` table in regard to glyph names.

**Comment by chrissimpkins** [comment]
> Fonts with `CFF` table are treated exceptionally because the `CFF` table stores glyph names itself, but `CFF2` table does not and it should be handled the same as fonts with `glyf` table in regard to glyph names.

If we make the change to allow TTF format builds to use post 3, then your statement means that we can also allow it in CFF / OTF builds?  

Here is where I am with the rationale statement based on the source changes that I'll open in the PR:

```
post format 2.5 was deprecated in OpenType 1.3 and should not be used.
        
According to Thomas Phinney, the possible problem with post format 3 is that under the right combination of circumstances, one can generate PDF from a font with a post format 3 table, and not have accurate backing store for any text that has non-default glyphs for a given codepoint. It will look fine but not be searchable. This can affect Latin text with high-end typography, and some complex script writing systems, especially with higher-quality fonts. Those circumstances generally involve creating a PDF by first printing a PostScript stream to disk, and then creating a PDF from that stream without reference to the original source document.  There are some workflows where this applies,but these are not common use cases.

Apple recommends against use of post format version 4 as "no longer necessary and should be avoided". Please see the Apple TrueType reference documentation for additional details. 
https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6post.html

Acceptable post format versions are 2 and 3 for TTF and OTF builds.
```

**Comment by chrissimpkins** [comment]
The post 2.5 and 4 checks will be new FAILs.  I didn't address post 1.

**Comment by chrissimpkins** [comment]
#3637

**Comment by chrissimpkins** [comment]
> Yes. CFF requires post version 3 any way.

OK I need to update the tests in the pull request to add one additional FAIL condition then.  Thanks.

**Comment by chrissimpkins** [comment]
> > Yes. CFF requires post version 3 any way.
> 
> OK I need to update the tests in the pull request to add one additional FAIL condition then. Thanks.

https://github.com/googlefonts/fontbakery/pull/3637/commits/ec7a514440a10397706440df474cd35230adfa6e

**Comment by madig** [comment]
As another point, I found that Apple seems to be running some autohinting on post v2 fonts but not post v3 fonts. I have no idea why or what exactly is going on there.

**Comment by chrissimpkins** [comment]
What grid fit differences do you see?

**Comment by madig** [comment]
It's subtle. post v2 vs v3:

![Animation](https://user-images.githubusercontent.com/380829/157056458-e99782d0-57f8-4e70-af01-72237fae41fd.gif)

**Comment by twardoch** [comment]
Oh yeah, it is animated 🤩

**Comment by khaledhosny** [comment]
Is the difference related to post table version or the autohinter expecting a specific glyph naming scheme e.g. AGL. For example, does using uniXXXX names for all the glyphs trigger the same difference?

**Comment by felipesanches** [comment]
I've only reopened this issue because there's an ongoing conversation here ;-)

Feel free to close it once you believe there's no further FontBakery changes to be implemented here.

**Comment by chrissimpkins** [comment]
> Is the difference related to post table version or the autohinter expecting a specific glyph naming scheme e.g. AGL. For example, does using uniXXXX names for all the glyphs trigger the same difference?

@madig do you have any additional info on this issue that might point us to some way to address it?  It isn't clear to me what role post names might have in grid fit.

**Comment by madig** [comment]
I haven't looked into it further and also haven't contacted Apple about it, though some day I want to do the latter.
