### ISSUE TITLE
New check: presence of GSUB5/GPOS7

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontbakery#3643]
Versions of fonttools  >=4.14.0 (19 August 2020) perform an optimisation on chained contextual lookups, expressing GSUB6 as GSUB5 and GPOS8 and GPOS7 where possible (when there are no suffixes/prefixes for all rules in the lookup).

However, `makeotf` has never generated these lookup types and they are rare in practice. Perhaps before of this, Mac's CoreText shaper (and probably other environments) do not correctly interpret these lookup types, meaning that these lookups will be ignored by the shaper, and fonts containing these lookups will have unintended positioning and substitution errors.

I think this should not be a FAIL because the fonts are technically correct (it's totally Apple's fault), but it should be a very severe WARN! I'll work on a PR for it.

**Comment by felipesanches** [comment]
I think this should be a FAIL because even though the fonts "are technically correct (it's totally Apple's fault)", the problem exists and must be avoided.

**Comment by anthrotype** [comment]
> should be a FAIL

not if a font targets non-apple platform. Unless there's a way to disable or demote severity of checks

**Comment by simoncozens** [comment]
It feels wrong to FAIL correct fonts.

**Comment by bobh0303** [comment]
For the font developers, is there a simple way to turn off these fontTools optimizations? @simoncozens seems to hint at that in his [tweet](https://twitter.com/simoncozens/status/1499860659437285382).

**Comment by devosb** [comment]
Thank you for finding this @simoncozens I am sorry to point out a typo, in the phrase _GSUB6 as GSUB5 and GPOS8 and GPOS7_ I think the second _and_ should be _as_. This typo has now made it into the Font Bakery code as well.

**Comment by Fuzzypeg** [comment]
The warning text says "To fix this warning, rebuild the font with a recent version of fonttools."
I have installed the latest version of fonttools and still get the problem. I think the warning text may be misleading.
