### ISSUE TITLE
More checks where log messages need to be normalized.

### ISSUE THREAD

**Issue by DavidRaymond** [googlefonts/fontbakery#3654]
As a follow-on to https://github.com/googlefonts/fontbakery/issues/3038 I've noticed a few more checks where the log messages need to be normalized:

com.google.fonts/check/dotted_circle
com.google.fonts/check/layout_valid_language_tags
com.google.fonts/check/production_glyphs_similarity
com.google.fonts/check/unreachable_glyphs

Note my testing only covers checks that work directly on .ttf files, so I won't be noticing any other checks where log messages need normalizing.

**Comment by davelab6** [comment]
@DavidRaymond is this good for you? Any more similar issues?

**Comment by DavidRaymond** [comment]
@davelab6 I've just run my standard tests twice (against 160 ttfs from 40 font projects) and there was no difference in the results, so all looks good from that. Thanks!
I did wonder whether some such testing could be added to your automated tests - simply running twice with, say, csv output and checking the results were identical.
