### ISSUE TITLE
com.google.fonts/check/linegaps failed with KeyError: 'OS/2'

### ISSUE THREAD

**Issue by miguelsousa** [googlefonts/fontbakery#3656]
Font Bakery v0.8.7

When a font does not have the `OS/2` table, **com.google.fonts/check/linegaps** fails with a KeyError.
https://github.com/googlefonts/fontbakery/blob/a9fc45fb563350fa806107f3afd878db63eb03c5/Lib/fontbakery/profiles/hhea.py#L21

Looking at other parts of `hhea.py` makes me think that sooner or later other ERRORs caused by `KeyError` are going to be triggered by other lines such as this,
https://github.com/googlefonts/fontbakery/blob/a9fc45fb563350fa806107f3afd878db63eb03c5/Lib/fontbakery/profiles/hhea.py#L17
or this,
https://github.com/googlefonts/fontbakery/blob/a9fc45fb563350fa806107f3afd878db63eb03c5/Lib/fontbakery/profiles/hhea.py#L37

Which makes me wonder:
**Is there a widespread need throughout the codebase for a mechanism akin to what was implemented to fix #2921?**

**Comment by felipesanches** [comment]
There already is a mechanism for auto-skipping checks that do not fulfill certain conditions. We could setuup conditions like this:

```python
@condition
def has_OS2_table(ttFont):
    return "OS/2" in ttFont.keys()

def has_hhea_table(ttFont):
    return "hhea" in ttFont.keys()
```

Then use them in the checks like this:

```python
@check(
    id = 'com.google.fonts/check/linegaps',
    conditions = ["has_hhea_table",
                 ["has_OS2_table"],
    proposal = 'legacy:check/041'
)
def com_google_fonts_check_linegaps(ttFont):
    """Checking Vertical Metric Linegaps."""
    if ttFont["hhea"].lineGap != 0:
        yield WARN,\
              Message("hhea",
                      "hhea lineGap is not equal to 0.")
    elif ttFont["OS/2"].sTypoLineGap != 0:
        yield WARN,\
              Message("OS/2",
                      "OS/2 sTypoLineGap is not equal to 0.")
    else:
        yield PASS, "OS/2 sTypoLineGap and hhea lineGap are both 0."
```

**Comment by felipesanches** [comment]
But if in some specific checks you'd want to emit a FAIL if a table is missing, then it would probably still be done manually in the check implementation.

**Comment by felipesanches** [comment]
I made a few quick fixes to the code examples above because they contained some mistakes/typos.
