### ISSUE TITLE
italicAngle check should apply in all correct profiles

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3663]
**Should be triggered if "Italic" is part of the file name, or `NameID2`, or `NameID17`.**
The ticked cases indicates where you can already find it.

### italicAngle in `post` table is not 0.
> Italic angle in counter-clockwise degrees from the vertical. Zero for upright text, negative for text that leans to the right (forward). https://docs.microsoft.com/en-us/typography/opentype/spec/post#header

```
🔥 FAIL: Checking post.italicAngle value.
* [com.google.fonts/check/italic_angle](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/italic_angle)
🔥 FAIL Font is italic, so post.italicAngle should be non-zero. [code: zero-italic]
```
**Profile**
- [x] in google-font profile
- [ ] in universal profile
- [ ] in opentype profile

**Format**
- [ ] in VF check
- [x] in static check

**Comment by felipesanches** [comment]
Let me reword this, then... You are requesting the italic angle check to be migrated from the vendor-specific `googlefonts` profile to the much broader `opentype` profile, right?

Since the semantics of the italic-angle value are defined in the OpenType spec, I think you're right!

**Comment by vv-monsalve** [comment]
I think I don't follow what you mean by "all correct profiles" but I think this check is valid and yes it should be included in the OpenType profile.

**Comment by vv-monsalve** [comment]
Although I've seen some other checks like `FAIL: CFF table FontName must match name table ID 6` are also included in the Universal profile, shouldn't this one be there too?

**Comment by vv-monsalve** [comment]
Profiles where it should be included
- [x] in google-font profile
- [x] in universal profile
- [x] in opentype profile

**Comment by RosaWagner** [comment]
The ticked cases in the issue are the ones where the check is already included, and the one unticked are the one _to do_.

**Comment by RosaWagner** [comment]
> Let me reword this, then... You are requesting the italic angle check to be migrated from the vendor-specific googlefonts profile to the much broader opentype profile, right?

Yes, then I don't know if opentype profile is included in Universal, but that's the idea.

**Comment by vv-monsalve** [comment]
Inspecting again the profiles in Fontbakery I can confirm now that almost all (if not all) the Italics checks listed should be included in the OpenType set, which would be included then in the universal and therefore in the google-fonts vendor-specific.

### Opentype
The checks of the [opentype profile](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/opentype.html) are separated in one sub-profile for each of the Open Type tables as listed below

### Universal
The checks on the [universal profile](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html), documented below, evaluate adherence to the best practices shared among the type design community. Additionally, it also includes the checks from the [opentype](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/opentype.html) profile.

### Google-Fonts
All vendor-specific profiles such as the [googlefonts](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html) one also include the checks from the [universal](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html) profile.
