### ISSUE TITLE
head macStyle ITALIC check should apply in all correct profiles

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3664]
**Should be triggered if "Italic" is part of the file name, or `NameID2`, or `NameID17`.**
The ticked cases indicates where you can already find it.

### Style linking must be set in `head` table:

```
🔥 FAIL: Checking head.macStyle value.
* [com.google.fonts/check/mac_style](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/mac_style)
🔥 FAIL head macStyle ITALIC bit should be set. [code: bad-ITALIC]
```
**Profile**
- [x] in google-font profile
- [ ] in universal profile
- [ ] in opentype profile

**Format**
- [ ] in VF check
- [x] in static check

**Comment by vv-monsalve** [comment]
I think this check should be part of the Universal profile
