### ISSUE TITLE
OS/2 fsSelection (italic) check should apply in all correct profiles

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3665]
**Should be triggered if "Italic" is part of the file name, or `NameID2`, or `NameID17`.**
The ticked cases indicates where you can already find it.

### Style linking must be set in `OS/2` table:

```
🔥 FAIL: Checking OS/2 fsSelection value.
* [com.google.fonts/check/fsselection](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/fsselection)
```
**Profile**
- [x] in google-font profile
- [ ] in universal profile
- [ ] in opentype profile

**Format**
- [ ] in VF check
- [x] in static check

**Comment by vv-monsalve** [comment]
Profiles where it should be included
- [x] in google-font profile
- [x] in universal profile
- [ ] in opentype profile

**Comment by khaledhosny** [comment]
The only part that should be in OpenType profile is italic angle being zero for italic fonts and vice versa, the other checks are GF-specifc. For example, and Arabic “italic” can lean from right to left and this has a positive italic angle, `FAIL`ing a font for +ve italic angle is a mistake. The same goes for the other arbitrary limit on the italic angle value.
