### ISSUE TITLE
Subfamily Name Italic check applies in all correct profiles

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3666]
**Should be triggered if "Italic" is part of the file name, or `NameID2`, or `NameID17`.**
The ticked cases indicates where you can already find it.

### `Name ID2` in `name` table should be "Italic" (or "Bold Italic")
```
🔥 FAIL: Check name table: FONT_SUBFAMILY_NAME entries.
* [com.google.fonts/check/name/subfamilyname](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/subfamilyname)
🔥 FAIL SUBFAMILY_NAME for Win "Regular" must be "Italic" [code: bad-familyname]
```
**Profile**
- [x] in google-font profile
- [x] in universal profile
- [ ] in opentype profile

**Format**
- [x] in VF check
- [x] in static check

**Comment by vv-monsalve** [comment]
This one should also be part of the Universal profile
