### ISSUE TITLE
Family name checks (italic) applies to all correct profiles

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3667]
**Should be triggered if "Italic" is part of the file name, or `NameID2`, or `NameID17`.**
The ticked cases indicates where you can already find it.

### `Name ID1` and `Name ID16` in `name` table should not contain "italic"

```
🔥 FAIL: Check name table: FONT_FAMILY_NAME entries.
* [com.google.fonts/check/name/familyname](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/familyname)
🔥 FAIL Entry [FONT_FAMILY_NAME(1):WINDOWS(3)] on the "name" table: Expected "Style Linking" but got "Style Linking Italic". [code: mismatch]
```
```
🔥 FAIL: Check name table: TYPOGRAPHIC_FAMILY_NAME entries.
* [com.google.fonts/check/name/typographicfamilyname](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/typographicfamilyname)
🔥 FAIL Font style is "Italic" and, for that reason, it is not expected to have a [TYPOGRAPHIC_FAMILY_NAME(16):WINDOWS(3)] entry! [code: ribbi]
```
**Profile**
- [x] in google-font profile
- [ ] in universal profile
- [ ] in opentype profile

**Format**
- [ ] in VF check
- [x] in static check

**Comment by vv-monsalve** [comment]
**Profile**
- [x] in google-font profile
- [x] in universal profile
- [ ] in opentype profile

**Comment by RosaWagner** [comment]
It should also be included in the opentype profile, since per opentype spec, if italic is in family name (and so not in style name), then style linking between Regular and Italic doesn't work. Regular, Bold, Italic, Bold Italic must be the 4 styles that never go in name ID1/16 (https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids), and that must always be in Name ID 2/17.
