### ISSUE TITLE
'ital' axis in STAT table should be last in axis order

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3669]
### `Ital` axis should be the last axis in the axis order:
Since STAT table can be use to create new instances, it can be important that the naming of new instance is consistent with the subfamily traditional scheme (RIBBI / WWS) where "Italic" is always last. This is required by GF, recommended by opentype, and usual universal practice. 
For example if  `<!-- DesignAxisCount=3 -->` then `<Axis index="2">` for Italic.

**Profile**
- [ ] in google-font profile (FAIL)
- [ ] in universal profile (WARN)
- [ ] in opentype profile (WARN)

**Format**
- [ ] in VF check
- ~in static check~

**Comment by vv-monsalve** [comment]
Profiles where it should be included

- [x] in google-font profile (FAIL)
- [x] in universal profile (WARN)
- ~~in opentype profile (WARN)~~

**Comment by vv-monsalve** [comment]
I've updated the above comment after reading again the FB profiles schema. I've added a new [comment](https://github.com/googlefonts/fontbakery/issues/3663#issuecomment-1077792954) around this in the first check proposal.
