### ISSUE TITLE
In italic fonts, Caret Slope shouldn't be 1

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3670]
**Should be triggered if "Italic" is part of the file name, or `NameID2`, or `NameID17`, or italicAngle != 0, or is italic.**
The ticked cases indicates where you can already find it.

### Caret Slope shouldn't be 1:
WARN 
Since those values are calculated by the font editor, which can lead to differences in rounding, I would not check for the exact value, but fail if, in `hhea` table, `caretRise = 1`, and if `caretRun = 0` which are values for upright fonts, and eventually suggest calculated values (according to italicAngle and UPM).

https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6hhea.html
> The caretSlopeRise and caretSlopeRun are used to specify the mathematical slope of the proper angle for the caret when displayed with this font. The slope is equal to caretSlopeRise divided by caretSlopeRun. Thus, a rise of 1 and run of 0 will specify a vertical caret (infinite slope). A rise of 0 and run of 1 will specify a horizontal caret (zero slope). Something in-between will be desirable for fonts whose glyphs are obliqued or italic. For example, one could use a rise of 2048 and a run of 270 for a slope of 7.6, which corresponds to an angle of 82.5°. (tan(82.5°) = 7.6)

**Currently in Profile**
- [ ] in google-font profile
- [ ] in universal profile
- [ ] in opentype profile 

**Currently in Format**
- [ ] in VF check
- [ ] in static check

**Comment by vv-monsalve** [comment]
Profiles where it should be included
- [x] in google-font profile
- [x] in universal profile
- [x] in opentype profile

Format
- [x] in VF check
- [x] in static check
