### ISSUE TITLE
Ot check for dotted circle 

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3673]
## Observed behaviour

https://github.com/googlefonts/noto-fonts/issues/2303 explains all fonts with combining masks should have a dotted circle character. I guess @simoncozens can provide more explanation detail. 

I guess this should be in the Universal profile. 

## Expected behaviour

Check, if any combining character (there's a concrete Unicode range that I guess Simon can quickly enumerate), does the dotted circle character exist with 5? Or more contours? If no, fail.

**Comment by felipesanches** [comment]
we already have a dotted circle check, added recently

**Comment by felipesanches** [comment]
#3602

**Comment by simoncozens** [comment]
We even have a fontmake filter to add one if it’s not there…
