### ISSUE TITLE
notofonts profile should do everything notolint does

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontbakery#3680]
This is a scratchpad issue for me. Ignore it.

* Name table checks
	* ~Check for unused entries in name table (>256)~ (Surely this was written before the days of variable fonts)
	* ~Check names 0-14, 16, 17, 21, 22 contain expected values~
	  * partially covered by `com.google.fonts/check/font_copyright` , `com.google.fonts/check/version_format` , `com_google_fonts_check_name_postscriptname`, `com.google.fonts/check/name/license`, `com.google.fonts/check/name/license_url`
	* ~Check version in head == version in name~ This is `com.google.fonts/check/font_version`.

* cmap checks
	*  ~Allowable cmap formats [(4, 3, 1), (12, 3, 10), (14, 0, 5), (4, 0, 3), (12, 0, 4)] + (6, 1, 1/2/3/25) for CJK~ This is `com.google.fonts/check/cmap/unexpected_subtables`.
	*  if we have both 4,3,1 and 4,0,3, they should be aliases similarly if we have both 12,3,10 and 12,0,4
	* ~Need format 4~ Will crash `com.google.fonts/check/family/equal_unicode_encodings`, so implicitly checked
	*  ~if there is a format 12 table, it should have non-BMP characters~
	*  ~format 4 table should be included in format 12~
	* ~ Check [0x0000, 0x000D, 0x0020] are encoded~ Null no longer required, space/nbspace covered in `com.google.fonts/check/whitespace_glyphs`
	*  Check "needed" characters are encoded
	*  ~There should be no (non-required) private use characters~
	*  ~No surrogate pairs: `list(range(0xFDD0, 0xFDEF + 1)) + [0xFFFE + plane_no * 0x10000 for plane_no in range(0, 17)] + [0xFFFF + plane_no * 0x10000 for plane_no in range(0, 17)]`~
	* ~No ASCII in deliverable fonts~ (We want to add ASCII subsets for some deliverables)
	* No "unexpected" characters
	* ~Variation selectors should be encoded for chars which have them~ I think we'll handle this with shaping tests.

* OS/2
	* ~unicoderange bits should be set correctly~ `com.google.fonts/check/unicode_range_bits`
	* ~fsType should be zero~ `com.google.fonts/check/fstype`
	* ~achVendID should be GOOG for Google fonts~
	* ~fsselection flags should be set correctly~ `com.google.fonts/check/fsselection`
	* Panose should be set correctly: family value = 2, serif bit = 2-10 for serif, 11-15 otherwise, proportion = 9 for mono, 2-4 otherwise

* hhea
	* ~hhea ascent/descent should be set correctly and equal to OS2 ascender/descender~ `com.google.fonts/check/family/win_ascent_and_descent` and `com.google.fonts/check/os2_metrics_match_hhea`
	* ~hhea/vhea linegap should be zero, sTypoLineGap should be zero~ `com_google_fonts_check_linegaps` but `vhea` needed

* glyf
	* Glyph bounding boxes should be within UI limits if UI font (MAX_UI_HEIGHT = 2163, MIN_UI_HEIGHT = -555, UI_ASCENT = 2189, UI_DESCENT = -600)
	* else Glyph bounding boxes should be within sTypoAscent / sTypoDescent
	* Check for intersections and off curve extrema

* GDEF
  * ~Check GlyphClassDef if non-spacing marks~
  * ~Check all encoded marks are class 3 in GlyphClassDef~ `com.google.fonts/check/gdef_mark_chars`
  * ~Encoded glyphs which are not Mn category should not be class 3 (unless in noto_data.ACCEPTABLE_AS_COMBINING)~ `com.google.fonts/check/gdef_non_mark_chars`
  * ~check for duplicate / out of order attachment points in AttachList table~ covered by opentype-sanitizer
  * ~check that every ligature has a ligature caret in GDEF~ `com.google.fonts/check/ligature_carets`
    * and that every ligcaret refers to a class 2 glyph

* GSUB/GPOS
  * ~all named stylistic sets (UINameId) to have name ids in the table~ `com.google.fonts/check/stylisticset_description`
  * ~isol/init/medi/fina for all glyphs with such things~  I think we'll handle this with shaping tests.
  * ~GPOS and GSUB present except for scripts which don't need them~  I think we'll handle this with shaping tests.

* ~For each bidi mirroring character in the font, we wake sure that: if it is in OMPL, its mirror pair should also be in the cmap, and the first character should not mapped by 'rtlm'. If the character is not in OMPL, it should be mapped by 'rtlm'.~  I think we'll handle this with shaping tests.

* ~No unreachable glyphs~ `com.google.fonts/check/unreachable_glyphs`

* hmtx
	* ~Encoded (Latin) digits should all have the same advance~
	* ~comma/period should have the same advance~
	* ~In monospaced fonts [tab_char, nbsp_char] + list(range(0x2000, 0x200B)) should have same advance as space~ (Picked up in monospace checks)
	* ~In non-monospaced fonts, tab and nsbp should be same as space and 0x2000-0x2006 should have correct widths per em square, 0x2007 should be same as digit, 0x2008 should be same as punctuation, 0x2009 should be 5/6ths, 0x200a should be 10/16ths, 0x200B should be zero~
	* ~"02C8 02CA-02D7 02DE 02DF 02EC 02ED 02EF-02F2 02F4-02FF" should be spacing (nonzero advance)~ Not doing this because it's a very Latin-centric rule for a global project.

**Comment by felipesanches** [comment]
See also: https://github.com/googlefonts/fontbakery/issues/2598#issuecomment-560999477

**Comment by simoncozens** [comment]
-> #3681
