### ISSUE TITLE
DeprecationWarning: draw_glyph() is deprecated, use get_glyph_shape() instead

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3684]
![Screenshot from 2022-03-31 04-16-03](https://user-images.githubusercontent.com/213676/160999291-9cf8ac7a-2f4e-4191-b8f9-b1eead7845f4.png)

**Comment by miguelsousa** [comment]
I believe this requires an update from upstream vharfbuzz first https://github.com/simoncozens/vharfbuzz/blob/ce74003ad07fb5bc1048f04f3ab56615d755f909/lib/vharfbuzz/__init__.py#L226

**Comment by felipesanches** [comment]
thanks

**Comment by felipesanches** [comment]
This is pending code-review by @simoncozens upstream: https://github.com/simoncozens/vharfbuzz/pull/5

Once there's a `vharfbuzz` **v0.1.3** release with the fix, we can update our `requirements.txt` and close this issue.
