### ISSUE TITLE
Check for mismatch between subfamily name and stylename

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontbakery#3688]
## Observed behaviour

This happened in certain versions of glyphsLib:

```xml
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Noto Kufi Arabic Light
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Regular 
    </namerecord>
    <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
      2.106;GOOG;NotoKufiArabic-Light
    </namerecord>
    <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
      Noto Kufi Arabic Light
    </namerecord>
    <namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
      Version 2.106
    </namerecord>
    <namerecord nameID="6" platformID="3" platEncID="1" langID="0x409">
      NotoKufiArabic-Light
    </namerecord>
```

## Expected behaviour

A font like that should fail a fontbakery check.

## Resources and exact process needed to replicate

https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf/NotoKufiArabic/

**Comment by khaledhosny** [comment]
What is the bug here? Name ID 2 is required to be one of the regular/bold/italic/bold italic styles for backward compatibility, while name ID 17 doesn't have this restriction: https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids

**Comment by miguelsousa** [comment]
I've looked at the font's name table records and I don't see anything wrong with them.
NameIDs 1 & 2 only support the [“R/B/I/BI” family model](https://docs.microsoft.com/en-us/typography/opentype/spec/stat#alternate-font-family-models).

The Noto Kufi Arabic typeface family has more than 4 styles, which requires breaking them up into multiple (font-menu) sub-families (by nameID 1), and to include nameIDs 16 & 17.

```xml
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Noto Kufi Arabic Light
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Regular
    </namerecord>
    <namerecord nameID="16" platformID="3" platEncID="1" langID="0x409">
      Noto Kufi Arabic
    </namerecord>
    <namerecord nameID="17" platformID="3" platEncID="1" langID="0x409">
      Light
    </namerecord>
```

In an app such as InDesign, all 9 styles will be listed under the **Noto Kufi Arabic** family name.

In an app like MS Word,
- 2 styles (Regular, Bold) will be listed under the **Noto Kufi Arabic** sub-family name. The name table of these 2 fonts also doesn't include nameIDs 16 & 17.
- 1 style (Thin) will be listed under the **Noto Kufi Arabic Thin** sub-family name.
- 1 style (Extra Light) will be listed under the **Noto Kufi Arabic Extra Light** sub-family name.
- 1 style (Light) will be listed under the **Noto Kufi Arabic Light** sub-family name.
- 1 style (Medium) will be listed under the **Noto Kufi Arabic Medium** sub-family name.
- 1 style (Semi Bold) will be listed under the **Noto Kufi Arabic Semi Bold** sub-family name.
- 1 style (Extra Bold) will be listed under the **Noto Kufi Arabic Extra Bold** sub-family name.
- 1 style (Black) will be listed under the **Noto Kufi Arabic Black** sub-family name.

**Comment by RosaWagner** [comment]
@simoncozens I also don't see the problem here as long as the font contains nameID16 and 17. Can this issue be closed?

**Comment by simoncozens** [comment]
Yeah, I'm probably not correct here.
