### ISSUE TITLE
HTML Output is not well displayed: outline_alignment_miss, outline_jaggy_segments, outline_short_segments

### ISSUE THREAD

**Issue by moontypespace** [googlefonts/fontbakery#3691]
## Observed behaviour

HTML Output is not well displayed:
FontBakeryCheck:com.google.fonts/check/outline_alignment_miss
FontBakeryCheck:com.google.fonts/check/outline_jaggy_segments
FontBakeryCheck:com.google.fonts/check/outline_short_segments

## Expected behaviour

It should look like:
FontBakeryCheck:com.google.fonts/check/outline_semi_vertical

## Resources and exact process needed to replicate

Here a screenshot for reference:
<img width="1312" alt="Screenshot 2022-04-04 at 15 09 22" src="https://user-images.githubusercontent.com/21055547/161551783-c6bb3ffa-a9f3-4747-978d-e2f9501512ea.png">

**Comment by felipesanches** [comment]
![Screenshot from 2022-04-05 14-51-25](https://user-images.githubusercontent.com/213676/161818879-774b49d0-1517-43cd-9083-43a6ddeb9e23.png)

**Comment by felipesanches** [comment]
The screenshot above is the result of the changes at PR #3692
