### ISSUE TITLE
Improve implementation of `is_italic` condition and provide an `is_bold` counterpart

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3693]
@moontypespace suggested changes to the `is_italic` condition at his pull request #3649

That PR is mostly concerned with the addition of a new check to the FontWerk profile. But this check uses the is_italic condition from the `shared_conditions` module, so I took precaution of reviewing the usage of this condition on other profiles, since a modification could trigger side-effects in other checks.

It seems, though, that the `is_italic` condition is not used a lot in our entire codebase:
![Screenshot from 2022-04-06 11-55-10](https://user-images.githubusercontent.com/213676/162004129-d0654a9a-ed1b-4d1a-9aab-e33342363ea8.png)

The first 3 results are an in-line re-definition of an `is_italic` helper function exclusively to be used on the implementation of **com.google.fonts/check/metadata/canonical_style_names** and the fourth result is the definition of `@condition is_italic`.

The final result is the definition of `@condition is_not_italic` which is used by **com.google.fonts/check/outline_semi_vertical**.

----
@moontypespace's suggested modification to `is_italic` (and a counterpart `is_bold`) involves also checking whether nameId 4 (FULL_FONT_NAME) has "italic" (or "bold"), which I think it better than looking for it on all first 256 nameIDs (which is what the custom in-line `is_italic` does on **com.google.fonts/check/metadata/canonical_style_names** since even broader criteria got narrowed at #2304).

But @moontypespace's PR uses the fontTools method `getDebugName`, which has a terrible name, in my opinion (why "debug" ? What does that mean?)

As the function lacks a docstring, all I can do is read its source code and try to grasp what it does:
https://github.com/fonttools/fonttools/blob/7ee2c9d8918be4158340ca584996ef13cbe9cd84/Lib/fontTools/ttLib/tables/_n_a_m_e.py#L102-L121
![Screenshot from 2022-04-06 13-41-29](https://user-images.githubusercontent.com/213676/162025070-a8056527-6654-42d7-8f9a-d41289734b9f.png)

My understanding is that if tries to find the first entry in english or, in the absence of it, any entry at all with the requested nameID (which happens to be the last entry found, but I suspect this is an irrelevant side-effect of the implementation).

----
So, I'd rather not use that fontTools method and, instead, update our is_italic condition to be very similar to the inline one, but only checking nameID 4. And then use it on **com.google.fonts/check/metadata/canonical_style_names** as well as in @moontypespace's new check. Also, I don't think this change will have any negative consequences to **com.google.fonts/check/outline_semi_vertical**.

**Comment by moontypespace** [comment]
@felipesanches It's probably a bit late, but in the meantime I wrote a different function for fonttools with a better name ;) What do you think about using 'getBestFullName' instead:
https://github.com/fonttools/fonttools/blob/7ee2c9d8918be4158340ca584996ef13cbe9cd84/Lib/fontTools/ttLib/tables/_n_a_m_e.py#L142
