### ISSUE TITLE
fvar check proposal: Validate nameID value used in InstanceRecord.subfamilyNameID

### ISSUE THREAD

**Issue by miguelsousa** [googlefonts/fontbakery#3703]
Quote from the [`fvar` documentation](https://docs.microsoft.com/en-us/typography/opentype/spec/fvar) in OpenType spec v1.9 (my emphasis):

> The subfamilyNameID field provides a name ID that can be used to obtain strings from the 'name' table that can be treated as equivalent to name ID 17 (typographic subfamily) strings for the given instance. **Values of 2 or 17 can be used; otherwise, values must be greater than 255 and less than 32768.**

I hereby propose a new `fvar` check that validates that the value of subfamilyNameID used by each InstanceRecord be 2, 17, or greater than 255 and less than 32768.
The check should FAIL if the conditions are not met.

**Comment by behdad** [comment]
> Values of 2 or 17 can be used; otherwise, values must be greater than 255 and less than 32768.

FWIW I find this wording problematic. Any value *can* be used if the corresponding name is what the user desires...

**Comment by behdad** [comment]
> @behdad That's the exact wording in the [OT fvar spec](https://docs.microsoft.com/en-us/typography/opentype/spec/fvar).

I understand it is.

**Comment by behdad** [comment]
> > @behdad That's the exact wording in the [OT fvar spec](https://docs.microsoft.com/en-us/typography/opentype/spec/fvar).
> 
> I understand it is.

It's just one of those arbitrary requirements of the spec that is misguided. I'm sure I filed an extensive report about it somewhere but can't find right now.
