### ISSUE TITLE
GF Profile: Make RFN list a standalone txt file

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3707]
Folllowing https://github.com/googlefonts/fontbakery/issues/1380 @RosaWagner requested making the allowlist a separate text file in the codebase, to make maintaining the list more easy.

**Comment by RosaWagner** [comment]
@felipesanches ping me when done, I'll deal with adding the necessary families (it doesn't follow exactly the spreadsheet we set since some fonts won't actually be onboarded even if we have the permission).

**Comment by felipesanches** [comment]
@RosaWagner, now the exceptions are in text files at the **Lib/fontbakery/data/googlefonts** directory.
