### ISSUE TITLE
fvar check proposal: Validate the subfamilyNameID and postScriptNameID values of the default instance

### ISSUE THREAD

**Issue by miguelsousa** [googlefonts/fontbakery#3708]
Quotes from the [`fvar` documentation](https://docs.microsoft.com/en-us/typography/opentype/spec/fvar) in OpenType spec v1.9 (my emphasis):

> [...] The values 2 or 17 should only be used if the named instance corresponds to the font’s default instance.
> [...] The value 6 should only be used if the named instance corresponds to the font’s default instance.
> [...]
> The default instance of a font is that instance for which the coordinate value of each axis is the defaultValue specified in the corresponding variation axis record. An instance record is not required for the default instance, though an instance record can be provided. When enumerating named instances, the default instance should be enumerated even if there is no corresponding instance record. **If an instance record is included for the default instance** (that is, an instance record has coordinates set to default values), **then the nameID value should be set to either 2 or 17, and the postScriptNameID value should be set to 6.**
>> Note: Since an instance record for the default instance is not required, a variable font that has no instance records defined in the 'fvar' table (instanceCount is zero) still has one named instance.

I hereby propose a new `fvar` check that validates that when an instance record is included for the default instance, its subfamilyNameID value should be set to either 2 or 17, and its postScriptNameID value should be set to 6.
The check should FAIL if the conditions are not met.

**Comment by justvanrossum** [comment]
The check for this fails several font builds that have totally ordinary designspace files. fontmake by default does not seem to reuse the nameID==2 ("Regular" in our case) for an fvar "Regular" named instance. 

Also, our default named instances do not specify a postScriptNameID at all.

It seems this check does two things, and the report is not clear about which of the two or both are wrong.

The postScriptNameID is easy to fix I suppose, by editing the designspace file. But what to do about the nameID==2/17 check? Fontmake just doesn't build it that way.

**Comment by BlackFoundry** [comment]
Maybe Fontmake should build the `fvar` differently for the default instance nameID so that this test passes? @anthrotype

**Comment by felipesanches** [comment]
People should not necessarily be changing what they're doing **just** because a FontBakery check is failing. Ideally we should understand what the check is trying to validate and, if we agree the check is legitimate, then address our font building processes. If, on the other hand, the check is missing nuances, then the check itself should be updated to reflect the best practices in the font engineering community.

Clarity of the reasoning behind a check is a goal here. So if the rationale description is not clear, then it is also a bug we'd like to fix.

**Comment by miguelsousa** [comment]
I wrote the check. This is the commit that added it 7f603ac0847d0fb7de1c8b4ff21946a11cf0dde2

> Also, our default named instances do not specify a postScriptNameID at all.

That's perfectly fine. Named instances are not required to have PostScript names. However, if one has it, all must have it. Since, in your case, one of the named instances matches the default instance, that named instance will inherit the varfont's PS name, thus forcing the other named instances to have PS names as well.

> It seems this check does two things, and the report is not clear about which of the two or both are wrong.

It's true, the check validates two distinct things; but it also has separate messages for each of them. Let me know which parts aren't clear.

https://github.com/googlefonts/fontbakery/blob/d032820b3eba866c71e99f0e6caced3352e1f7a6/Lib/fontbakery/profiles/fvar.py#L469-L474

https://github.com/googlefonts/fontbakery/blob/d032820b3eba866c71e99f0e6caced3352e1f7a6/Lib/fontbakery/profiles/fvar.py#L478-L485

**Comment by miguelsousa** [comment]
> Maybe Fontmake should build the fvar differently for the default instance nameID so that this test passes?

The check exists and is written the way it is **because of the OT spec**. So the motivation to change FontMake should be to make fonts abide to the spec, not to please Font Bakery.

**Comment by justvanrossum** [comment]
Thank you, I understand the messages now. I got confused by the check intro vs the actual check message.

TBH, I think this is a typical case where the spec is [being overly restrictive](https://github.com/MicrosoftDocs/typography-issues/issues/946).

**Comment by anthrotype** [comment]
> Named instances are not required to have PostScript names. However, if one has it, all must have it. Since, in your case, one of the named instances matches the default instance, that named instance will inherit the varfont's PS name, thus forcing the other named instances to have PS names as well.

Well.. so the mere presence of a named instance matching the default instance would mean, according to your interpretation, that _all_ the named instances should declare an explcit postScriptNameID.. That would make it no longer optional!

I disagree (cf. https://github.com/MicrosoftDocs/typography-issues/issues/946#issuecomment-1167236067)

**Comment by anthrotype** [comment]
> That would make it no longer optional!

ok no, it would still be optional since the instance record for the default instance is optional. From the point of view of a compiler, I would prefer doing the latter to adding ps names to all the instances just because one matches the default.

**Comment by anthrotype** [comment]
Peter Constable said that "should" simply means a "recommendation, not a requirement" (https://github.com/MicrosoftDocs/typography-issues/issues/946#issuecomment-1167523649) so IMO you could relax this FAIL to a WARNING...

**Comment by justvanrossum** [comment]
Given the final remarks in [this discussion](https://github.com/MicrosoftDocs/typography-issues/issues/946),
I think this check should be reworked to check for "name record equality" instead of a hard == 2/17 check, and likewise for the ps name vs nameID 6.
