### ISSUE TITLE
Adobe Fonts profile: Check that nameID 1 supports English language in Windows platform

### ISSUE THREAD

**Issue by miguelsousa** [googlefonts/fontbakery#3714]
Add a new check for nameID 1 (Font Family name), platformID 3 (Windows), encodingID 1 (Unicode), languageID 1033/0x409 (US-English).
Yield FAIL if string is empty or None, and PASS otherwise.

**Comment by felipesanches** [comment]
@miguelsousa This sounds like a very generic check. What's the rationale? It may be good for inclusion in the `universal` profile.

**Comment by miguelsousa** [comment]
The rationale is that there's a part of our pipeline that requires it 😅
I wouldn't mind including it in the Universal profile, but it might become an unnecessary requirement for other people's workflow.
