### ISSUE TITLE
Remove `designspace` checks from Universal profile

### ISSUE THREAD

**Issue by miguelsousa** [googlefonts/fontbakery#3725]
This is somewhat related to #3724 

Currently, [the Universal profile includes checks that validate `.designspace` files](https://github.com/googlefonts/fontbakery/blob/3e08267464055a9fe6922d4460e7bb47dd74235e/Lib/fontbakery/profiles/universal.py#L29-L34), essentially making them "universal" as well.

The designspace checks are not necessary for workflows that only care about running Font Bakery on font binaries.
I'd like to propose taking them out of the universal imports.
They could either be moved to the `ufo_sources` profiles, or to a whole new profile.

**Comment by felipesanches** [comment]
The scope of Font Bakery profiles is not defined by file-types.
More detailed reasoning provided at https://github.com/googlefonts/fontbakery/issues/3724#issuecomment-1104290316
