### ISSUE TITLE
update com.google.fonts/check/metadata/parses to accept "archive_url" field

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3731]
We have this fail with this PR: https://github.com/google/fonts/pull/4535:

🔥 FAIL: Check METADATA.pb parse correctly. ([com.google.fonts/check/metadata/parses](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/parses))
🔥 FAIL Family metadata at ofl/andika failed to parse.
TRACEBACK:
50:3 : Message type "google.fonts_public.SourceProto" has no field named "archive_url". [code: parsing-error]

It has been implemented recently the possibility to package fonts from tagged releases (so the "fonts" directory is not necessary anymore), therefore metadata.pb now takes "archive_url" as field (https://github.com/googlefonts/gftools/pull/517)

cc @m4rc1e

**Comment by m4rc1e** [comment]
I've just made a pr which updates the fonts_public.proto file. This should solve the issue. Lemme check quickly.

**Comment by m4rc1e** [comment]
Yep updating the proto files worked.
