### ISSUE TITLE
[com.google.fonts/check/name/rfn] Should not fail if the reserved name is not part of the current font name

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#3739]
## Observed behaviour

`com.google.fonts/check/name/rfn` is a hard **FAIL** for any font using RFN clause, even if it is not a practical issue e.g. a font A using parts of font B that uses RFN. Font A has to keep the clause of font B, but font A itself does not have a RFN clause so people modifying font A don’t have to rename it.

## Expected behaviour

No **FAIL** if RFN name is not part of the current font name.

## Resources and exact process needed to replicate

Alternatively, give an exception to [Aref Ruqaa](https://github.com/aliftype/aref-ruqaa/issues/37) that uses AMS Euler and has to keep its RFN clause.

**Comment by felipesanches** [comment]
**Note:** I've edited the issue title and @khaledhosny's original message just replacing the term "error" and using "FAIL" instead.

**Comment by davelab6** [comment]
@khaledhosny thanks! 

> Alternatively, give an exception

That's our first approach and @felipesanches should be able to add this family to the allowlist quickly.

> Font A has to keep the clause of font B

This is a great explanation; our RFNs checks are in their infancy; agreed that OFL users must retain RFN notices and change the name, so the RFN check should ideally have a heuristic to extract the RFNs and compare them to the current family name and only FAIL when the RFNs are used in the family name IDs and not in the allowlist; and WARN if an RFN exists to take extra care with naming
