### ISSUE TITLE
https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/transformed_components

### ISSUE THREAD

**Issue by twardoch** [googlefonts/fontbakery#3767]
https://github.com/google/fonts/pull/4615

lists

“FAIL: Ensure component transforms do not perform scaling or rotation. ([com.google.fonts/check/transformed_components](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/transformed_components))”

and the link is:

https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/transformed_components

but the link goes to a page where “transformed” is nowhere to be found

**Comment by felipesanches** [comment]
This was fixed recently (see https://github.com/googlefonts/fontbakery/commit/7ea27c8ea79a93bb45572d2b5215cd18b7bf04d6 and #3677) and the change will be included in the upcoming v0.8.9 release.

In the mean time, change `latest` to `stable` on the readthedocs URL:
https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/transformed_components

**Comment by felipesanches** [comment]
This is also related, though, to a known bug still pending a proper fix: #3770
