### ISSUE TITLE
Bug - Copyright string - com.google.fonts/check/font_copyright

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/fontbakery#3774]
(**NOTE:** If your issue is related to a specific check, please consider mentioning its check-id on the issue title.)

I think this is a bug 

## Observed behaviour

>> Check:   com.google.fonts/check/font_copyright
    Desc:    Copyright notices match canonical pattern in fonts
    Files:   PinyonScript-Regular.ttf

     FAIL Name Table entry: Copyright notices should match a                    
          pattern similar to: "Copyright 2019 The Familyname Project Authors    
          (git url)" But instead we have got: "Copyright 2019 **Pinyon Script**     
          Project Authors (https://github.com/SorkinType/Pinyon)" [code:        
          bad-notice-format]                                                    
    Result: FAIL

## Expected behaviour

I expected the above to be OK but instead, I had to change it to this 

**PinyonScript**

Note that now there is no space between Pinyon and Script

I don't think it should require the removal of the space - ideally speaking - because we are referring to the name of the project not a file that can't have spaces in this string. Probably parsing something that has spaces is harder though and I get that has to be true.

Alternatively, if this MUST stay this way ( no spaces in names permitted ) what about including a note that spaces are not OK if that's the reason for the fail? Is there a note in the template instructions saying to remove the space? In my case I was lucky and I guessed correctly and got rid of the fail but... I was just guessing.

## Resources and exact process needed to replicate

If you clone (https://github.com/SorkinType/Pinyon/) and you take the space out of the copyright string in the Glyphs file and push and run the push you should see the fail.

**Comment by RosaWagner** [comment]
@EbenSorkin The check is just rising an inconsistency between the OFL file and the font metadata, check that the copyright string is written the same everywhere.

Right now I see this in your OFL.txt:
`Copyright 2022 The Pinyon Script Project Authors (https://github.com/SorkinType/Pinyon)`

And this in your font file:
`Copyright 2022 The PinyonScript Project Authors (https://github.com/SorkinType/Pinyon)`

The fail should be resolved once you add a space in the copyright string of your source file and re-build the font
