### ISSUE TITLE
command line color codes not working in fontbakery report on windows 10 and made it a bit unreadable

### ISSUE THREAD

**Issue by aminabedi68** [googlefonts/fontbakery#3779]
```
 >> com.google.fonts/check/hinting_impact
    Show hinting filesize impact.
    with Estedad[KSHD,wght].ttf

      Rationale:
      This check is merely informative, displaying and useful comparison of
      filesizes of hinted versus unhinted font files.

     INFO Hinting filesize impact:

          ←[1;30;44m               ←[0m←[30;44m ←[0m←[1;30;44m ←[0m←[1;30;44mEstedad[KSHD,wght].ttf←[0m←[1;30;44m ←[0m  
          ←[37;40m ←[0m←[37;40mDehinted Size←[0m←[37;40m ←[0m←[30;40m ←[0m←[37;40m ←[0m←[37;40m               282.2kb←[0m←[37;40m ←[0m
          ←[37;40m ←[0m←[37;40mHinted Size  ←[0m←[37;40m ←[0m←[30;40m ←[0m←[37;40m ←[0m←[37;40m               282.2kb←[0m←[37;40m ←[0m
          ←[37;40m ←[0m←[37;40mIncrease     ←[0m←[37;40m ←[0m←[30;40m ←[0m←[37;40m ←[0m←[37;40m              24 bytes←[0m←[37;40m ←[0m
          ←[37;40m ←[0m←[37;40mChange       ←[0m←[37;40m ←[0m←[30;40m ←[0m←[37;40m ←[0m←[37;40m                 0.0 %←[0m←[37;40m ←[0m

          [code: size-impact]


    Result: INFO
```

**Comment by felipesanches** [comment]
you can disable colors with `--no-colors`

**Comment by felipesanches** [comment]
Are you using Windows' default text terminal? I thought it supported colors...

**Comment by aminabedi68** [comment]
> you can disable colors with `--no-colors`

ok, thank you 👍


> Are you using Windows' default text terminal? I thought it supported colors...

yes, but it's not supported in my version apparently, don't know why.

**Comment by aminabedi68** [comment]
not working:
```
usage: fontbakery check-googlefonts [-h] [--configuration CONFIGFILE] [-c CHECKID] [-x EXCLUDE_CHECKID] [-v]
                                    [-l LOGLEVEL] [-m LOGLEVEL_MESSAGES] [--succinct] [-S] [-L] [-F] [--dark-theme]
                                    [--light-theme] [--json JSON_FILE] [--badges DIRECTORY] [--ghmarkdown MD_FILE]
                                    [--html HTML_FILE] [-g ITERATED_ARG] [-o ORDER] [-J JOBS] [-j]
                                    [files ...]
fontbakery check-googlefonts: error: unrecognized arguments: --no-colors
```

**Comment by felipesanches** [comment]
That's weird, because it works for me!

I know you said you're using the latest version, but could you please verify that by telling me what's the output of `fontbakery --version`?

**Comment by aminabedi68** [comment]
yes, np:
`0.8.8`

**Comment by felipesanches** [comment]
yeah, that's definitely weird :-P

**Comment by felipesanches** [comment]
@madig, disabled `--no-progress` and `--no-colors` on Windows in this commit back in 2018: 752be2f21f669781955d8032a4075793e1b8dfbb 

There's some debate about it at PR #1882

Given that you're a user on Windows who needs to disable colors, I think it is reasonable to start a conversation here about this.

As an immediate measure, I think these two flags should be re-enabled, as it sounds nonsensical to me that a feature would be enabled by default but also lack flags to disable it on a specific platform. I think this was a mistake and must be fixed ASAP. (meaning: "as soon as we release Font Bakery v0.8.9")

**Comment by madig** [comment]
I can take a look tomorrow. I'm using [Windows Terminal](https://github.com/Microsoft/Terminal) now which should not have any problems with colors anymore. I think the world can drop support for other kinds of Windows terminals.

**Comment by madig** [comment]
Windows Terminal displays colors fine. You can remove the win32 workaround.
