### ISSUE TITLE
[com.google.fonts/check/contour_count] U+0024 DOLLAR SIGN should be allowed to have 5 contours

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/fontbakery#3780]
## Observed behavior

`com.google.fonts/check/contour_count` expects the glyph for U+0024 DOLLAR SIGN to have 1 or 3 contours.

## Expected behavior

`com.google.fonts/check/contour_count` should also allow the glyph for U+0024 DOLLAR SIGN to have 5 contours, to support glyphs with two strokes.

## Resource

https://software.sil.org/downloads/r/abyssinica/AbyssinicaSIL-2.100.zip

**Comment by felipesanches** [comment]
yep! Sounds good ;-)
