### ISSUE TITLE
[com.google.fonts/check/family/underline_thickness] Outdated link in rationale

### ISSUE THREAD

**Issue by arialcrime** [googlefonts/fontbakery#3793]
## Observed behaviour

Rationale of underline thickness check currently reads:
```
      Rationale:                                                                
      Dave C Lemon (Adobe Type Team) recommends setting the underline thickness 
      to be consistent across the family.                                     
      If thicknesses are not family consistent, words set on the same line which
      have different styles look strange.                                       
                                                                                
      See also:                                                                 
      https://twitter.com/typenerd1/status/690361887926697986
```
Unfortunately the linked tweet does not exist anymore.

## Expected behaviour
If a link is present in a rationale, it should lead somewhere and be helpful.

**Comment by felipesanches** [comment]
Yeah... I think we need to start using Internet Archive links in cases like. Or we could have our own repo with captures of the contents of these referenced online resources.

**Comment by felipesanches** [comment]
I'm glad that the rationale-text already seems to have kept a copy of the bulk of the idea from that tweet. But I'm afraid that reactions from other people in the type community (that must have happened as tweet-responses in that thread) may have been lost forever.
