### ISSUE TITLE
Missing glyphs threshold wrong way around?

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontbakery#3812]
I've just been told (https://github.com/google/fonts/pull/4806#issuecomment-1160303772) that my font is missing glyphs like:

```
 FAIL Missing required codepoints:

0x030B (COMBINING DOUBLE ACUTE ACCENT)
0x0304 (COMBINING MACRON)
0x02D9 (DOT ABOVE)
0x0102 (LATIN CAPITAL LETTER A WITH BREVE)
...
```

I'm sure these are optional, not mandatory, codepoints in GF Latin Core. This code:

https://github.com/googlefonts/fontbakery/blob/666b3425b14f6c59a43cddf30279ca2fdc6e714e/Lib/fontbakery/profiles/googlefonts.py#L1059-L1060

looks like it's the wrong way around.

**Comment by RosaWagner** [comment]
Codepoints don’t seem wrong though… did you compare with the new GF Latin Core in the glyphsets repo? As you know we have been working on redefining the required core glyphset for several month now.

**Comment by simoncozens** [comment]
Aah, right. Kernel now exists, I shall use that instead!
