### ISSUE TITLE
Is this a bug in fb version check?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3813]
![Screenshot from 2022-06-20 10-20-04](https://user-images.githubusercontent.com/213676/174610814-d78655d1-757d-4190-92aa-2c6f9001347c.png)

It looks like it thinks v0.8.10 is older than v0.8.9

https://github.com/googlefonts/fontbakery/runs/6934094547

**Comment by graphicore** [comment]
looks like it's comparing strings not numbers:

```py
>>> '10' > '9'
False

>>> 10 > 9
True
```

**Comment by felipesanches** [comment]
yeah, I guess that's it
