### ISSUE TITLE
False FAIL in com.google.fonts/check/glyph_coverage

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontbakery#3814]
(**NOTE:** If your issue is related to a specific check, please consider mentioning its check-id on the issue title.)

## Observed behaviour

The attached font fails with:

```
$ fontbakery check-googlefonts -c com.google.fonts/check/glyph_coverage NotoSansBuhid-Regular.ttf
     FAIL Missing required codepoints:
...
          │ - 0x00AF (MACRON)                                                  │
...
```

## Expected behaviour

The font contains a macron so should not fail.

```
$ hb-shape NotoSansBuhid-Regular.ttf -u 0x00AF
[overscore=0+500]
```

## Resources and exact process needed to replicate

[NotoSansBuhid-Regular.ttf.gz](https://github.com/googlefonts/fontbakery/files/8957943/NotoSansBuhid-Regular.ttf.gz)

**Comment by RosaWagner** [comment]
Do we require standard production name? Or only the codepoint should be checked?

**Comment by simoncozens** [comment]
I don't think we should require a production name, at least for this check; the check is about "glyph coverage" and "required codepoints", and the font supports that codepoint. Maybe a production names check could be a different check?

**Comment by simoncozens** [comment]
Oh, that's probably what's now causing *this*:

<img width="740" alt="Screenshot 2022-07-01 at 11 33 18" src="https://user-images.githubusercontent.com/106728/176878315-41871e17-3310-4d76-aa52-e6cf43308964.png">

**Comment by felipesanches** [comment]
does #3833 fix this problem as well?

**Comment by m4rc1e** [comment]
This should be solved now.
