### ISSUE TITLE
Variable Fonts with Roman and Italic, what to do ?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3826]
### Discussed in https://github.com/googlefonts/fontbakery/discussions/3824

<div type='discussions-op-text'>

<sup>Originally posted by **SolennBor** July  4, 2022</sup>
We have 2 Variable Fonts for the same Family, one for Romans and one for Italics, they should be style linked.
Fontbakery raise `Fails` about the italic VF:
- ‘fvar’:
    - `The “wght” axis coordinate of the “Regular” instance must be 400. Got None instead. [code: wght-not-400]` obviously the font doesn’t have Regular but Italic instead
    -  `The “wght” axis coordinate of the “Bold” instance must be 700. Got None instead. [code: wght-not-700]` same thing, no Bold but Bold Italic instead
- ‘STAT’: `The following AxisValue entries on the STAT table should not contain “Italic”: [‘nameID 258: Light Italic’, ‘nameID 259: Regular Italic’, ‘nameID 260: Bold Italic’, ‘nameID 261: ExtraBold Italic’] [code: bad-italic]`
Q: Should we add an `ital` axis with `default=“1" maximum=“1” minimum=“1"` for specifying the font is italic even though it doesn’t vary on this axis? (similarly the Roman VF could have this `ital` axis set with `default=“0” maximum=“0" minimum=“0”`)
Is there a standard way at solving this issue that must be quite common indeed?
Thanks for your input.</div>

**Comment by benkiel** [comment]
Will just say that the `fvar` for italic thing from above is happening to me currently, using 0.8.9

**Comment by felipesanches** [comment]
Hi, @benkiel! Please, read https://github.com/googlefonts/fontbakery/discussions/3824#discussioncomment-3140227 and let me know if your case is identical to that, or if you have other considerations on this.
