### ISSUE TITLE
💔 ERROR: Check Google Fonts glyph coverage.

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/fontbakery#3827]
## Observed behaviour

I had first a classic missing glyphs fail:
🔥 FAIL: Check Google Fonts glyph coverage. ([com.google.fonts/check/glyph_coverage](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage))
🔥 FAIL Missing required codepoints:
 0x0312 (COMBINING TURNED COMMA ABOVE) [code: missing-codepoints]

And when I added the missing glyph, updated features, this error appeared: 

💔 ERROR: Check Google Fonts glyph coverage. ([com.google.fonts/check/glyph_coverage](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage))
💔 ERROR Failed with IndexError: list index out of range

Do you know how to solve that?

## Resources and exact process needed to replicate

From the source folder: gftools builder config.yaml
Repo: https://github.com/emmamarichal/Lora-Cyrillic

Thank you!

**Comment by simoncozens** [comment]
I'm getting it everywhere in Noto. Glad it's not just me. I'll have a look into it.

**Comment by simoncozens** [comment]
OK, so the problem seems to be that this check is confused about whether it is checking for *glyphs* or *characters*. GF Latin Core now requires some unencoded glyphs like `i.loclTRK`. If those are not in your font, here's what happens:

```
    # We check to see which mandatory glyphs are missing...
    missing_mandatory_glyphs = glyph_data.missing_glyphsets_in_font(ttFont, threshold=0.0)

    if "GF_Latin_Core" in missing_mandatory_glyphs:
        passed = False
        # The test has not passed because i.loclTRK is mandatory but not in the font

        missing = missing_encoded_glyphs(missing_mandatory_glyphs["GF_Latin_Core"])
        # We filter by encoded glyphs, but this list is empty because the only missing glyphs are unencoded

        yield FAIL,\
              Message("missing-codepoints",
                      f"Missing required codepoints:\n\n"
                      f"{bullet_list(config, missing)}")
        # This goes boom because we're trying to format an empty list.
```

Before we fix this, we need to decide if the check should report "required codepoints" or "required glyphs". If it's "required codepoints", we need to test again after assigning to `missing` to see if there's anything in that list. If it's "required glyphs", then we don't want to filter the glyphs based on whether they're encoded or not.

**Comment by driehuis** [comment]
Two observations.  `missing_encoded_glyphs` specifically ignores anything without a unicode value. And glyphs like i.loclTRK make no sense in isolation, so I think if features like that become required, specific tests for language support should be added (I already have PLK support for kreska and ROM support for commabelow).

For now, I'm going to jury-rig it to ignore `"GF_Latin_Core" in missing_mandatory_glyphs` if `missing_encoded_glyphs` returns an empty array and I'll see what a future update will bring :-)
