### ISSUE TITLE
com.google.fonts/check/varfont/regular_wght_coord and Italic fonts

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontbakery#3828]
## Observed behaviour

I get this fail:

The variable font 'wght' (Weight) axis coordinate must be 400 on the 'Regular' instance.
Check ID: <FontBakeryCheck:com.google.fonts/check/varfont/regular_wght_coord>
🔥 fonts/NotoSerif/googlefonts/variable-ttf/NotoSerif-Italic[wdth,wght].ttf
🔥 FAIL
The "wght" axis coordinate of the "Regular" instance must be 400. Got None instead. [code: wght-not-400]

## Expected behaviour

The check is assuming that a font will have a `Regular` instance, but an italic VF (according to https://googlefonts.github.io/gf-guide/variable.html#fvar-instances) will have fvar instances called `Italic`, `Bold Italic`, etc.

## Resources and exact process needed to replicate

Run any italic VF on the googlefonts profile.

**Comment by jenskutilek** [comment]
The check also fails if there are other axes in addition to the weight axis.

E.g. I have a stencil font with a weight and a bridge axis. The bridge axis ranges from 1 to 10. There is no defined default value for bridge, but the default instance is at bridge == 1. So in fvar, the default instance is called "Regular 01", at wght=400, BRDG=1. The check looks for Regular and doesn't find it.

**Comment by simoncozens** [comment]
That's not a problem for the Google Fonts spec. The spec says:

> Google Fonts only allows the following named instances:

| Roman      | Italic            |
|------------|-------------------|
| Thin       | Thin Italic       |
| Light      | Light Italic      |
| Regular    | Italic            |
| Medium     | Medium Italic     |
| SemiBold   | SemiBold Italic   |
| Bold       | Bold Italic       |
| ExtraBold  | ExtraBold Italic  |
| Black      | Black Italic      |

So if you're running a test against the Google Fonts profile, it's correct to look for "Regular" (*or* "Italic") and so OK to fail if there's no Regular.

**Comment by jenskutilek** [comment]
Ok, thanks. It's not a Google font.

**Comment by felipesanches** [comment]
> That's not a problem for the Google Fonts spec. The spec says:
> 
> > Google Fonts only allows the following named instances:
> 
> Roman 	Italic
> Thin 	Thin Italic
> Light 	Light Italic
> Regular 	Italic
> Medium 	Medium Italic
> SemiBold 	SemiBold Italic
> Bold 	Bold Italic
> ExtraBold 	ExtraBold Italic
> Black 	Black Italic
> 
> So if you're running a test against the Google Fonts profile, it's correct to look for "Regular" (_or_ "Italic") and so OK to fail if there's no Regular.

**com.google.fonts/check/varfont/regular_wght_coord** is an `OpenType` profile check.

It is overridden on the `Adobe Fonts` profile, but simply included by inheritance on the `Google Fonts` profile.

**Comment by simoncozens** [comment]
Ah, oops. Yeah, that's a problem then.

**Comment by simoncozens** [comment]
This now passes, thanks to #3834.
