### ISSUE TITLE
Error in com.google.fonts/check/glyph_coverage with font missing only unencoded glyphs

### ISSUE THREAD

**Issue by FriedOrange** [googlefonts/fontbakery#3836]
My WIP font currently has all glyphs from GF Latin Core that have Unicode codepoints, but not the unencoded ones like `periodcentered.loclCAT`, etc.

## Observed behaviour

Console output:
```
 >> Check:   com.google.fonts/check/glyph_coverage
    Desc:    Check Google Fonts glyph coverage.
    Files:   LibreDotMatrix-Regular.ttf

    ERROR Failed with IndexError: list index out of range                       
          ↳ File                                                                
          "C:\Users\neilb\AppData\Local\Programs\Python\Python310\lib\site-packa
          ges\fontbakery\checkrunner.py", line 194, in _exec_check              
          for sub_result in result:  # Might raise.                             
          ↳ File                                                                
          "C:\Users\neilb\AppData\Local\Programs\Python\Python310\lib\site-packa
          ges\fontbakery\profiles\googlefonts.py", line 1068, in                
          com_google_fonts_check_glyph_coverage                                 
          f"{bullet_list(config, missing)}")                                    
          ↳ File                                                                
          "C:\Users\neilb\AppData\Local\Programs\Python\Python310\lib\site-packa
          ges\fontbakery\utils.py", line 215, in bullet_list                    
          pretty_print_list(config,                                             
          ↳ File                                                                
          "C:\Users\neilb\AppData\Local\Programs\Python\Python310\lib\site-packa
          ges\fontbakery\utils.py", line 210, in pretty_print_list              
          return f"{joined_items_str} {glue} {str(values[-1])}"                 
    Result: ERROR
```

## Expected behaviour

It seems that the font was correctly identified as missing glyphs from the set, but `pretty_print_list` is attempting to index an empty list here, as that list only ever contains encoded glyphs. 

Perhaps `com_google_fonts_check_glyph_coverage` should be changed to report unencoded glyphs as well as encoded ones.

## Resources and exact process needed to replicate

This could probably be reproduced with any font that covers GF Latin Core, minus one or more of the unencoded glyphs. [Here](https://github.com/FriedOrange/LibreDotMatrix/releases/download/v0.200/LibreDotMatrix-fonts.zip) are the fonts which produced the error for me.

**Comment by felipesanches** [comment]
I believe that this was fixed 3 days ago by PR #3833 
If that's the case, then you'll either want to wait for the next release (v0.8.10) or use fontbakery from git `main` branch.

Please, let me know if we should re-open this issue in case you have evidence that there are still problems even after the 3833 fix.
