### ISSUE TITLE
ensure google/fonts/noto* have articles

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#3841]
Noto prs to google/fonts must have an `article/` dir which contains a file called `ARTICLE.en_us.html` e.g https://github.com/google/fonts/tree/main/ofl/notomusic/article.

**Comment by m4rc1e** [comment]
This is becoming quite a pressing issue. I suggest we implement this asap since Simon is making many noto prs.

cc @vv-monsalve @chrissimpkins

**Comment by chrissimpkins** [comment]
> This is becoming quite a pressing issue. I suggest we implement this asap since Simon is making many noto prs.
> 
> 
> 
> cc @vv-monsalve @chrissimpkins 

@simoncozens

**Comment by simoncozens** [comment]
I'm really sorry about this. I'll implement it.

**Comment by vv-monsalve** [comment]
@simoncozens COuld this issue be closed by #3891? Or is there something still in progress?

**Comment by simoncozens** [comment]
Yes, I think this is now fixed.
