### ISSUE TITLE
Should com.google.fonts/check/mandatory_avar_table be a warning?

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontbakery#3856]
## Observed behaviour

If a variable font doesn't have an `avar` table,`com.google.fonts/check/mandatory_avar_table` FAILs

## Expected behaviour

Our font really doesn't need `avar`. Is this check perhaps a little too strict?

## Reference

https://github.com/justvanrossum/nabla/issues/25

**Comment by felipesanches** [comment]
please post your considerations at issue #3100
