### ISSUE TITLE
Override freetype_rasterizer to make it mandatory for Google Fonts

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3871]
At https://github.com/googlefonts/fontbakery/commit/8bf12c8db5dd4855a37070948fc618a0396ba173, I noticed that it would be wise for the Google Fonts profile to also override the freetype_rasterizer check from SKIP (if freetype dependency is not installed) to a FAIL, just like Adobe Fonts does.

We will also need to setup the google/fonts CI rules so that we install freetype before running fontbakery on font PRs.

The check, on the Universal Profile, emits a SKIP by default because it is considered an optional check. But I think it should be mandatory for Google Fonts.

For the record, here's what the check does:
![Screenshot from 2022-08-22 18-34-50](https://user-images.githubusercontent.com/213676/186023035-4055aab0-b2c7-44b1-bf91-98f69e908b09.png)

**Comment by davelab6** [comment]
SGTM
