### ISSUE TITLE
Reduce the footprint of default install

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3874]
Description written by @miguelsousa:
----

The footprint of Font Bakery's default install is quite large. Several large packages are installed by default, but they're only used by a few profiles.

<img width="333" alt="fontbakery_deps" src="https://user-images.githubusercontent.com/2119742/186104620-65ae039f-ad62-4ac0-ac75-b6e7f003dda8.png">

Move more packages to `extras_require`.
Relates to #3715

**Comment by miguelsousa** [comment]
## Current dependency tree
![deps](https://user-images.githubusercontent.com/2119742/205769573-61b78479-f9f9-4258-a3be-85875e17df82.png)
(created with [pipdeptree](https://pypi.org/project/pipdeptree/))

fontbakery==0.8.11a7.dev14+gb9d7e253
  - axisregistry [required: >=0.3.0, installed: 0.3.9]
    - fonttools [required: Any, installed: 4.38.0]
    - protobuf [required: >=3.19.4, installed: 3.20.3]
  - beautifulsoup4 [required: Any, installed: 4.11.1]
    - soupsieve [required: >1.2, installed: 2.3.2.post1]
  - beziers [required: >=0.5.0, installed: 0.5.0]
    - pyclipper [required: Any, installed: 1.3.0.post4]
  - cmarkgfm [required: Any, installed: 2022.10.27]
    - cffi [required: >=1.15.0, installed: 1.15.1]
      - pycparser [required: Any, installed: 2.21]
  - collidoscope [required: ==0.4.1, installed: 0.4.1]
    - beziers [required: >=0.0.3, installed: 0.5.0]
      - pyclipper [required: Any, installed: 1.3.0.post4]
    - fonttools [required: Any, installed: 4.38.0]
    - glyphtools [required: Any, installed: 0.8.0]
      - babelfont [required: >0.2.0, installed: 3.0.0]
        - cu2qu [required: >=1.6.7,<2.0.0, installed: 1.6.7.post2]
          - fonttools [required: >=3.32.0, installed: 4.38.0]
        - fontfeatures [required: >=1.0.6,<2.0.0, installed: 1.7.3]
          - beziers [required: >=0.1.0, installed: 0.5.0]
            - pyclipper [required: Any, installed: 1.3.0.post4]
          - fontTools [required: >=4.28.0, installed: 4.38.0]
          - fs [required: Any, installed: 2.4.16]
            - appdirs [required: ~=1.4.3, installed: 1.4.4]
            - six [required: ~=1.10, installed: 1.16.0]
          - lxml [required: Any, installed: 4.9.1]
        - fonttools [required: >=4.21.1, installed: 4.38.0]
        - glyphsLib [required: >=5.3.2, installed: 6.1.0]
          - fonttools [required: >=4.33.0, installed: 4.38.0]
          - openstep-plist [required: >=0.3.0, installed: 0.3.0.post1]
          - ufoLib2 [required: >=0.6.2, installed: 0.14.0]
            - attrs [required: >=22.1.0, installed: 22.1.0]
            - fonttools [required: >=4.0.0, installed: 4.38.0]
        - openstep-plist [required: >=0.2.2, installed: 0.3.0.post1]
        - orjson [required: >=3.5.1,<4.0.0, installed: 3.8.3]
        - ufoLib2 [required: >=0.11.1, installed: 0.14.0]
          - attrs [required: >=22.1.0, installed: 22.1.0]
          - fonttools [required: >=4.0.0, installed: 4.38.0]
      - beziers [required: Any, installed: 0.5.0]
        - pyclipper [required: Any, installed: 1.3.0.post4]
      - glyphsLib [required: Any, installed: 6.1.0]
        - fonttools [required: >=4.33.0, installed: 4.38.0]
        - openstep-plist [required: >=0.3.0, installed: 0.3.0.post1]
        - ufoLib2 [required: >=0.6.2, installed: 0.14.0]
          - attrs [required: >=22.1.0, installed: 22.1.0]
          - fonttools [required: >=4.0.0, installed: 4.38.0]
      - numpy [required: Any, installed: 1.23.5]
    - uharfbuzz [required: Any, installed: 0.32.0]
  - defcon [required: Any, installed: 0.10.2]
    - fonttools [required: >=4.10.0, installed: 4.38.0]
  - dehinter [required: >=3.1.0, installed: 4.0.0]
    - fontTools [required: Any, installed: 4.38.0]
  - font-v [required: Any, installed: 2.1.0]
    - fonttools [required: Any, installed: 4.38.0]
    - gitpython [required: Any, installed: 3.1.29]
      - gitdb [required: >=4.0.1,<5, installed: 4.0.10]
        - smmap [required: >=3.0.1,<6, installed: 5.0.0]
  - fontTools [required: >=4.36.0, installed: 4.38.0]
  - gflanguages [required: >=0.3.0, installed: 0.4.3]
    - protobuf [required: >=3.7.0,<4, installed: 3.20.3]
  - glyphsets [required: >=0.5.0, installed: 0.5.4]
    - defcon [required: Any, installed: 0.10.2]
      - fonttools [required: >=4.10.0, installed: 4.38.0]
    - FontTools [required: Any, installed: 4.38.0]
    - glyphsLib [required: Any, installed: 6.1.0]
      - fonttools [required: >=4.33.0, installed: 4.38.0]
      - openstep-plist [required: >=0.3.0, installed: 0.3.0.post1]
      - ufoLib2 [required: >=0.6.2, installed: 0.14.0]
        - attrs [required: >=22.1.0, installed: 22.1.0]
        - fonttools [required: >=4.0.0, installed: 4.38.0]
  - lxml [required: Any, installed: 4.9.1]
  - munkres [required: Any, installed: 1.1.4]
  - opentype-sanitizer [required: >=7.1.9, installed: 9.0.0]
  - opentypespec [required: Any, installed: 1.8.4]
  - packaging [required: Any, installed: 21.3]
    - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.9]
  - pip-api [required: Any, installed: 0.0.30]
  - protobuf [required: >=3.7.0,<4, installed: 3.20.3]
  - PyYAML [required: Any, installed: 6.0]
  - requests [required: Any, installed: 2.28.1]
    - certifi [required: >=2017.4.17, installed: 2022.9.24]
    - charset-normalizer [required: >=2,<3, installed: 2.1.1]
    - idna [required: >=2.5,<4, installed: 3.4]
    - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.13]
  - rich [required: Any, installed: 12.6.0]
    - commonmark [required: >=0.9.0,<0.10.0, installed: 0.9.1]
    - pygments [required: >=2.6.0,<3.0.0, installed: 2.13.0]
  - stringbrewer [required: Any, installed: 0.0.1]
    - rstr [required: Any, installed: 3.2.0]
    - sre-yield [required: Any, installed: 1.2]
  - toml [required: Any, installed: 0.10.2]
  - ufo2ft [required: >=2.25.2, installed: 2.28.0]
    - booleanOperations [required: >=0.9.0, installed: 0.9.0]
      - fonttools [required: >=4.0.2, installed: 4.38.0]
      - pyclipper [required: >=1.1.0.post1, installed: 1.3.0.post4]
    - cffsubr [required: >=0.2.8, installed: 0.2.9.post1]
      - fontTools [required: >=4.10.2, installed: 4.38.0]
    - cu2qu [required: >=1.6.7, installed: 1.6.7.post2]
      - fonttools [required: >=3.32.0, installed: 4.38.0]
    - fonttools [required: >=4.34.0, installed: 4.38.0]
  - ufolint [required: Any, installed: 1.2.0]
    - commandlines [required: Any, installed: 0.4.1]
    - fontTools [required: >=4.18.0, installed: 4.38.0]
  - unicodedata2 [required: Any, installed: 15.0.0]
  - vharfbuzz [required: Any, installed: 0.1.4]
    - fontTools [required: Any, installed: 4.38.0]
    - uharfbuzz [required: Any, installed: 0.32.0]

**Comment by madig** [comment]
This annoys me as well and I was actually thinking of looking into this if the maintainers agree.

E.g. last I checked, lxml is pulled in and then used in just a couple places for reading some XML... which would be fine, if lxml would be more reliable with posting working wheels for platforms (Windows, Apple Silicon) and new Python versions :(

**Comment by felipesanches** [comment]
Perhaps other module such as beautifulsoup could be used to replace lxml on those few checks. 

But lxml is also a dependency via `collidoscope -> glyphtools -> babelfont -> fontfeatures -> lxml`.

**Comment by miguelsousa** [comment]
`lxml` is also a [FontTools dependency](https://github.com/googlefonts/fontbakery/blob/95808595a65a19f0de031096c6673d4e2b6965e5/setup.py#L74) when there's a requirement to handle UFOs and DesignSpace files.

As a start, I think we should,
1. [create at least two new **extras**](https://github.com/googlefonts/fontbakery/blob/95808595a65a19f0de031096c6673d4e2b6965e5/setup.py#L99-L108),
    - `ufo`
    - `harfbuzz`

2. then shift the dependencies to them,
3. and finally adjust the checks that depend on them.

**Comment by madig** [comment]
lxml is optional in fontTools as I understand it, because Cosoimo wrote an adapter that opportunistically uses lxml when available and the built-in XML module otherwise, see https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/misc/etree.py. So, maybe direct uses of the lxml API can be replaced by fontTools' etree module :)

**Comment by felipesanches** [comment]
At https://github.com/googlefonts/fontbakery/pull/4163#issuecomment-1577235067 @miguelsousa said:

> I think it comes down to clarifying Font Bakery's mission.
Font Bakery's mission is stated at https://font-bakery.readthedocs.io/en/latest/product/Overview.html#conclusion-font-bakery-s-secret-master-plan

> Right now it seems to be mostly about providing an all-encompassing toolset for validating that font binaries, their source files and their metadata [...]
... are all properly setup. Correct!

> [...] are all setup according to the needs of the Google Fonts service.
That's the definition of the Google Fonts profile.

> Was there ever a discussion somewhere about what belongs in the Universal profile, or did it just grow organically as the requirements of the Google Fonts service evolved?

Yes, it grew organically based on user feedback. But it was discussed in the issue tracker with all users, not only Google Fonts users. Also, the creation of the Adobe Fonts profile helped in the process of figuring out the intersection. Ideally, (in the absence of other major vendor-specific profiles) the Universal profile would be the exact intersection between googlefonts and adobefonts profiles. But there are checks that are placed in universal because either myself or other users have agreed that it belongs there even though adobefonts profile does not want them.

**Comment by felipesanches** [comment]
If we really end up employing extras to solve the problem of customizing the dependency tree footprint, then I think we may use something similar to what is described at https://stackoverflow.com/questions/64685527/pip-install-with-all-extras/64791668#64791668:
![Screenshot from 2023-06-05 19-23-38](https://github.com/googlefonts/fontbakery/assets/213676/daa0316e-fa76-436d-b248-8fb814e5f0bf)


So that instead of doing this:
`python -m pip install -U 'fontbakery[ufo,shaping,etc]`

One would do something like this:
`python -m pip install -U 'fontbakery[googlefonts]`

where googlefonts would include all these vendor-specific dependencies (and maybe other ones):
* axisregistry
* gflanguages
* glyphsets
* protobuf

That way, for a user experience point of view, it would be trivial to install fontbakery with support for a given vendor-specific profile. It would be just a matter of installing it with the extra with the same name of the profile needed. And it would be up to us maintainers to keep that extra definition in sync with future code-changes. Otherwise, already deployed instances of fontbakery (such as on github action setups) would face problems when new extras for specific dependencies are created.

**Comment by miguelsousa** [comment]
> [...] I think we may use something similar to what is described at https://stackoverflow.com/questions/64685527/pip-install-with-all-extras/64791668#64791668 [...] That way, for a user experience point of view, it would be trivial to install fontbakery with support for a given vendor-specific profile. It would be just a matter of installing it with the extra with the same name of the profile needed.

I like that approach. Some profiles may not even need any extras.

> And it would be up to us maintainers to keep that extra definition in sync with future code-changes.

Definitely.

> Otherwise, already deployed instances of fontbakery (such as on github action setups) would face problems when new extras for specific dependencies are created.

The CI installs everything that is listed in [requirements.txt](https://github.com/googlefonts/fontbakery/blob/main/requirements.txt) (and [testing-requirements.txt](https://github.com/googlefonts/fontbakery/blob/main/testing-requirements.txt)) which means that the `extras_require` setup we end up using doesn't really play a role there. Maintainers should keep updating **requirements.txt** regardless of the profile they maintain. The CI environment requires all profiles' dependencies to be installed.

The per-profile slimming down of the dependencies is for the benefit of end-usage.

**Comment by davelab6** [comment]
Would anyone like to change the mission statement? 

I have asked Felipe to organize a "fontbakery summit" event with all current and prospective organizations that use and contribute it, but so far there have been other priorities. Would this summer be a good moment to make it happen?

**Comment by miguelsousa** [comment]
@davelab6 Please open a new issue or start a discussion at https://github.com/googlefonts/fontbakery/discussions

**Comment by khaledhosny** [comment]
I think (if someone is willing to do the required work), fine grained dependencies are a good thing. For example, I use fontbakery to test a font I’m working on and I have a lot of shaping tests (arguably this should have been a separate tool to begin with), but I don’t have any collision tests and from the graphs above collidoscope seems to be the heaviest dependency, even though it is a tool probably a handful of fonts need it.

**Comment by felipesanches** [comment]
> > Otherwise, already deployed instances of fontbakery (such as on github action setups) would face problems when new extras for specific dependencies are created.
> 
> The CI installs everything that is listed in [requirements.txt](https://github.com/googlefonts/fontbakery/blob/main/requirements.txt) (and [testing-requirements.txt](https://github.com/googlefonts/fontbakery/blob/main/testing-requirements.txt)) which means that the `extras_require` setup we end up using doesn't really play a role there. Maintainers should keep updating **requirements.txt** regardless of the profile they maintain. The CI environment requires all profiles' dependencies to be installed.
> 
> The per-profile slimming down of the dependencies is for the benefit of end-usage.

I was referring to deployments of Font Bakery on CI jobs of font-project repositories, so that QA is performed automatically during the font family development.

**Comment by madig** [comment]
> But for universal, it seems we're in a tie, since I believe shaping checks as well as outline quality checks are important checks for "the general functionality of an OpenType font". 

FWIW, I completely disregard checks like the jagged lines one, if that's what you mean, both internally and for a certain proprietary font project you know. I never find the results useful (especially if you interpolate instances) and the check happens at the wrong time. It must happen within the designer's editor, because it won't be fixed after the sources have left the designer and move to the QA stage, as they aren't important enough.

I had a quick look at the deps and found:

* you can drop defcon if you use ufoLib2 instead
* if you just read TOML files, you can drop `toml` on Python >= 3.11 because it ships with https://devdocs.io/python~3.11/library/tomllib

**Comment by felipesanches** [comment]
As a result of the latest commit on main branch (0af772ffb4b1c15262eec00c4dda890b66c657c9), there's still more work needed here.

We figured out a good approach for handling vendor-specific dependencies and I think we're moving in the right direction here by using `extras` named after each of the vendor-specific profiles.

I reassigned the issue to me, because I will resume work on this today, as I'm happy with what we've come up with in the discussions of this thread.

**Comment by simoncozens** [comment]
I'm not opposed to reducing unnecessary dependency, but I'm a little confused as to what the actual problem you're trying to solve is here. FontBakery is big, OK... and then what? If you want certain functionality and you don't want to write it yourself, you have to pay for it in dependencies; that's the deal we all bought into when we started using libraries. If I can install all the dependencies in one go with `pip install fontbakery`, I don't *really* care what they are or how many they are.

"It's so big my hard disk drive is full" is a problem, but I don't believe we're there. "It uses lots of dependencies (but I have many of them installed anyway because I do lots of font work)" is not a real problem. There may be a real problem here, and hearing that would help us to know how best to solve it. But I'm not convinced that "it's big" is enough information.

**Comment by madig** [comment]
FWIW, my original impulse for looking at deps was that I wanted to speed up a certain secret font project and looked at Pypy. Turns out that installing lxml into a Pypy venv actually makes compilation slower, but the project was set up such that fontbakery and the compiler were installed into the same venv and it was annoying to pry them apart. lxml was a hard dep for various fontbakery deps I wasn't using anyway, so it wasn't easy to drop.

Internally, we install fontbakery into project venvs with pinned deps, and the large dep tree brings in various binary wheels that make upgrading Python versions harder (no wheels for newer Pythons years later), even when we aren't using the features the deps are brought in for.

Really, lxml is the most annoying dep because the project still has not released working 3.11 universal2 wheels, so you have to deploy compilers to people's Macs or follow releases and make them yourself...

**Comment by simoncozens** [comment]
"Replace lxml with another parsing library" as a limited goal makes a lot of sense. Within fontbakery it's only used for reading the results of Microsoft Font Validator (is that a useful check any more?!)  and link checking. I use it in fontFeatures but only for serialisation and I'm happy to turn that into an extras dependency.
