### ISSUE TITLE
`-L`/`--list-checks` option broken?

### ISSUE THREAD

**Issue by miguelsousa** [googlefonts/fontbakery#3878]
The `-L`/`--list-checks` option allows a user to get a list of all the checks of a given profile.

I'm getting an error when I try this:

    fontbakery check-googlefonts -L

However, the option works if I provide a file:

    fontbakery check-googlefonts -L MyFont.ttf

Is this behavior by design?
As a user I think it's more intuitive NOT to have to reference a file.

**Comment by felipesanches** [comment]
it may be a bug. I agree with you that it should not be necessary to provide a file

**Comment by miguelsousa** [comment]
[The fix](https://github.com/miguelsousa/openbakery/commit/3145ce8f1cfd3c4f78d3216f1f13c77fb21d1418) is simple. The challenge was finding how and where to do it.

**Comment by simoncozens** [comment]
This is fixed, due to the above commit! Thanks both!
