### ISSUE TITLE
com.google.fonts/check/varfont/bold_wght_coord doesn't distinguish between "no Bold instance" and "Bold instance wght != 700"

### ISSUE THREAD

**Issue by josh-hadley** [googlefonts/fontbakery#3898]
## Observed behaviour

com.google.fonts/check/varfont/bold_wght_coord fails when there is no Bold instance present, using the same status code (`wght-not-700`) as for when the Bold instance's wght coord is not 700, for example:

```
     FAIL The "wght" axis coordinate of the "Bold" instance                     
          must be 700. Got None instead. [code: wght-not-700]                   
```

Thus the check effectively enforces that a Bold instance _must be present_ which some profiles might wish to override, while retaining enforcement of "if a Bold instance is present, its wght coord must be 700".

## Expected behaviour

It would be better to have a separate status code for the case of "no Bold instance" to enable profiles to override the different conditions should they wish to selectively enforce this check (for example, WARN on "no bold instance" but still FAIL on "bold instance is present but its wght coord != 700").

## Resources and exact process needed to replicate

Run `fontbakery check-adobefonts` (or other profile that uses this check) on the attached [nobold.otf.zip](https://github.com/googlefonts/fontbakery/files/9568887/nobold.otf.zip) which contains a `wght` axis but has no "Bold" named instance. Observe the failure with message "The "wght" axis coordinate of the "Bold" instance must be 700. Got None instead. [code: wght-not-700]".

**Comment by miguelsousa** [comment]
The fix is included in pre-release `v0.8.11a1`. You can install it with this command:

    python -m pip install --upgrade --pre fontbakery'[freetype]'
