### ISSUE TITLE
Proposal of slnt direction outline check

### ISSUE THREAD

**Issue by yanone** [googlefonts/fontbakery#3902]
Fontbakery needs a check to see whether slant direction as part of a `slnt` axis is following the specs (as per https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_slnt): Right-leaning has negative values, which is *totally* counter-intuitive, so people do make that mistake.

I offer to write this myself, so I've assigned myself. This should go into the universal profile in my opinion.

**Comment by felipesanches** [comment]
implemented at PR #3910
