### ISSUE TITLE
ERROR when STAT table contains Format 4 Axis Values

### ISSUE THREAD

**Issue by punchcutter** [googlefonts/fontbakery#3904]
Both com.adobe.fonts/check/stat_has_axis_value_tables and com.fontwerk/check/inconsistencies_between_fvar_stat assume that an AxisValue has an AxisIndex, but Format 4 does not so we get an ERROR. 

https://github.com/googlefonts/fontbakery/blob/bcffc0339009116adb2f45bed3f960ce1d9e77b3/Lib/fontbakery/profiles/fontwerk.py#L145

https://github.com/googlefonts/fontbakery/blob/bcffc0339009116adb2f45bed3f960ce1d9e77b3/Lib/fontbakery/profiles/stat.py#L78

These both need to check for the presence of Format 4 before trying to access AxisIndex.

**Comment by justvanrossum** [comment]
We just ran into this as well. @blackfoundry @frankrolf

**Comment by felipesanches** [comment]
thanks, @miguelsousa
