### ISSUE TITLE
[com.google.fonts/check/contour_count] U+0E3F THAI CURRENCY SYMBOL BAHT should be allowed to have 5 contours

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/fontbakery#3914]
## Observed behavior

`com.google.fonts/check/contour_count` expects the glyph for U+0E3F THAI CURRENCY SYMBOL BAHT to have 3 contours.

## Expected behavior

`com.google.fonts/check/contour_count` should also allow the glyph for U+0E3F THAI CURRENCY SYMBOL BAHT to have 5 contours, to support glyphs where the vertical stroke crosses the counters.

**Comment by vv-monsalve** [comment]
@dscorbett, if that was reported as a `Warn`, please keep in mind that they are reported to highlight things that are likely but not certainly wrong. Following the warning, the type developer could check for it to validate if it's an actual issue with the font or something that is working as expected and thus could be ignored.

**Comment by dscorbett** [comment]
It shouldn’t even be a warning. A five-contour glyph is extremely common for this character. It is probably more common than the three-contour glyph Font Bakery endorses.
