### ISSUE TITLE
What to do when Python crashes running fontbakery?

### ISSUE THREAD

**Issue by guidoferreyra** [googlefonts/fontbakery#3918]
## Observed behaviour

Sometimes when running fontbakery with a custom profile, Pyrhon crashes and displays the following window.

<img width="416" alt="imagen" src="https://user-images.githubusercontent.com/1755590/193945061-61add54d-3f0a-42a4-8f9b-a37df6f5885e.png">

I thought it was something wrong on my custom checks but I removed those and it keeps crashing. This is what the terminal shows:

```
░ [PSWPPPPPFPPPPPIPPPPSPSF.............................................................................]
 23%
[1]    5228 segmentation fault  fontbakery check-profile   --html report.html
```

What can I do to debug this?

**Comment by felipesanches** [comment]
does it also crash without using the html reporter?

**Comment by guidoferreyra** [comment]
Yes

**Comment by guidoferreyra** [comment]
I made a new virtual environment where only fontbakery (and its dependencies) are installed and it doesn’t crash anymore. So I think we can close this issue.
