### ISSUE TITLE
[com.google.fonts/check/slant_direction] errors on some fonts

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#3934]
Just seen this check failing on https://github.com/google/fonts/pull/5009#issuecomment-1293085616

**Comment by felipesanches** [comment]
![Screenshot from 2022-10-27 10-30-39](https://user-images.githubusercontent.com/213676/198248220-f870b7ad-cb6e-4aaf-9135-54518f038d22.png)
