### ISSUE TITLE
With ufo2ft==2.29.0 I can't access ttf.reader on an object returned by compileTTF

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#3940]
![Screenshot from 2022-11-02 22-01-09](https://user-images.githubusercontent.com/213676/199610912-8974d6d2-bf45-46a6-8cf3-33813abf29b2.png)

**Comment by anthrotype** [comment]
That's a feature, not a bug ;)

In the ufo2ft postProcessor were previously always compiling the ttfont to an in-memory bytesIO buffer and reloading it off that, but that was only necessary when renaming glyphs so we don't do that any more unconditionally. The TTFont instance you get from ufo2ft is created from scratch not read from disk so you should not expect it to have a reader attribute, that's only for TTFonts read from a file.

**Comment by anthrotype** [comment]
If you require that your test font has a reader, you need to do what we were doing in ufo2ft, that is save it to a temporary BytesIO and open a new TTFont from that, which will then be as if it were read from a file (only that the file is an in memory stream)

**Comment by felipesanches** [comment]
Thanks! I will try that.
