### ISSUE TITLE
[GF Profile] space width != nbspace width check should FAIL for all GF fonts (not only Noto)

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/fontbakery#3944]
space width != nbspace width should be FAIL for all fonts (not only Noto)
otherwise a font will not be eligible (aka rejected) for use in Google Workspace apps

**Comment by marekjez86** [comment]
@davelab6 : please add any additional justification

**Comment by davelab6** [comment]
I am surprised that a GF profile run would not FAIL a font where nbspace advanceWidth doesn't equal space; I believe this was one of the first checks I personally wrote myself back in like 2012.

**Comment by felipesanches** [comment]
I'll try to figure out what happened and report here.

**Comment by felipesanches** [comment]
For me this looks perfectly fine:

* Check-ID: **com.google.fonts/check/whitespace_widths**
* Profile: `Universal`

![Screenshot from 2022-11-08 20-15-19](https://user-images.githubusercontent.com/213676/200666342-8eeed34f-2430-47d5-8072-b279f4c6dee3.png)

**Comment by twardoch** [comment]
> Advance width rule : The advance width of the no-break space should be equal to the width of the space.

— https://learn.microsoft.com/en-us/typography/develop/character-design-standards/whitespace

**Comment by felipesanches** [comment]
For completeness, here's also the implementation of the `condition` for this check (also looks fine to me):

![Screenshot from 2022-11-08 20-18-41](https://user-images.githubusercontent.com/213676/200666909-02760f8e-3b23-424c-9d26-fdf0958f522f.png)

**Comment by felipesanches** [comment]
> space width != nbspace width should be FAIL for all fonts (not only Noto)

@marekjez86, what did you mean by "not only Noto"? Do you have a sample font file with diverging widths for space and nbspace that does not FAIL when running the `universal` profile but has the problem properly detected when running the `notofonts` profile?

That would not make much sense because the `notofonts` profile automatically includes all checks from the `universal` profile.

**Comment by marekjez86** [comment]
@felipesanches @simoncozens : this was based on the conversation with Simon who replied with the following to my question:

![space-width](https://user-images.githubusercontent.com/13322623/200669749-a43f2c4a-2760-4825-9d8d-dbe31c96ad56.jpg)

I haven't looked at the code and from https://github.com/googlefonts/fontbakery/issues/3944#issuecomment-1307777680 it looks that it fails when they are different. I haven't ran it against any font that would fail. Please feel free to close it.

**Comment by felipesanches** [comment]
thanks, @marekjez86
