### ISSUE TITLE
DSIG check and fixer

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#396]
- [x] Check for DSIG table. "OT/TTF fonts with layout features are only recognized as such in Windows if they have a DSIG (digital signature) table." [– this forum thread](http://typedrawers.com/discussion/192/making-ot-ttf-layout-features-work-in-ms-word-2010#latest),
- [x] Make a fixer. Same forum thread contains this code for a fix method from Ben Kiel:
```py
def makeDSIG(font):
    from fontTools.ttLib.tables.D_S_I_G_ import SignatureRecord
    newDSIG = ttLib.newTable("DSIG")
    newDSIG.ulVersion = 1
    newDSIG.usFlag = 1
    newDSIG.usNumSigs = 1
    sig = SignatureRecord()
    sig.ulLength = 20
    sig.cbSignature = 12
    sig.usReserved2 = 0
    sig.usReserved1 = 0
    sig.pkcs7 = '\xd3M4\xd3M5\xd3M4\xd3M4'
    sig.ulFormat = 1
    sig.ulOffset = 20
    newDSIG.signatureRecords = [sig]
    font.tables["DSIG"] = newDSIG
```

**Comment by davelab6** [comment]
@felipesanches why is https://github.com/googlefonts/fontbakery/blob/master/fontbakery-check-ttf.py#L1397-L1413 better than what Behdad posted 2 years ago?

**Comment by felipesanches** [comment]
I'll take a look at this.

@davelab6 As a side-note, please try to use commit-specific URLs when referencing snippets of code like this one:
https://github.com/googlefonts/fontbakery/blob/e83e9a9ada2f549852bb309dda67b917d52726b7/fontbakery-check-ttf.py#L1397-L1413

URLs with line ranges referencing the master branch (as the one on your previous message) are problematic because, as time goes by, code at master branch gets modified and the lines do not match the intended snippet anymore.

**Comment by davelab6** [comment]
Ah yes, good point. I will try :)

**Comment by felipesanches** [comment]
@davelab6 @behdad The forum post suggested not only adding a DSIG table but also attaching a dummy signature to it. It is not clear to me it an empty (zero-signature) DSIG table would be enough to make OpenType Features work in MSOffice2010, so for now I think it is better to keep the dummy signature in the hotfix routine. It seems harmless, even though it is clearly a hack to bypass Microsoft's dumb policy. One potential issue is that whatever works now (or worked when the blogpost was published) may change in the future versions of MSOffice (and perhaps other programs).

The DSIG table documentation at microsoft's website (here: https://www.microsoft.com/en-us/Typography/dsig.aspx) mention that: "Windows will soon require installed software components, including fonts, to be signed. Internet browsers will also give users and administrators the ability to screen out unsigned objects obtained on-line, including web pages, fonts, graphics, and software components."

Any idea if this trend is actually moving on or if it's already being left behind? I know about secure-boot and digital signature requirements for executable binaries. But extending this to graphics on webpages seems a bit of a stretch...

**Comment by davelab6** [comment]
Okay, sounds good

**Comment by davelab6** [comment]
Not sure what happned with the potential to require signing; I believe it was dropped.
