### ISSUE TITLE
Installation: Building wheel for kurbopy (pyproject.toml) did not run successfully.

### ISSUE THREAD

**Issue by kosmynkab** [googlefonts/fontbakery#3965]
As mentioned – I can't seem to get through the installation of fontbakery – I keep running into an issue with krubopy (pyproject.toml):

error: subprocess-exited-with-error:

× Building wheel for kurbopy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [86 lines of output]
      Running `maturin pep517 build-wheel -i /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11`
      📡 Using build options bindings from pyproject.toml
         Compiling target-lexicon v0.12.5
         Compiling proc-macro2 v1.0.47
         Compiling once_cell v1.16.0
         Compiling quote v1.0.21
         Compiling libc v0.2.137
         Compiling unicode-ident v1.0.5
         Compiling autocfg v1.1.0
         Compiling syn v1.0.104
         Compiling parking_lot_core v0.9.4
         Compiling scopeguard v1.1.0
      error: could not compile `quote` due to 2 previous errors
      warning: build failed, waiting for other jobs to finish...
      error: could not compile `syn` due to 2 previous errors
      error: could not compile `libc` due to 2 previous errors
      error: could not compile `proc-macro2` due to 2 previous errors
      error: could not compile `parking_lot_core` due to 2 previous errors
      error: could not compile `target-lexicon` due to 2 previous errors
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --release --lib -- -C link-arg=-undefined -C link-arg=dynamic_lookup -C link-args=-Wl,-install_name,@rpath/kurbopy.cpython-311-darwin.so`
      🍹 Building a mixed python/rust project
      🔗 Found pyo3 bindings
      🐍 Found CPython 3.11 at /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11
      error: linking with `cc` failed: exit status: 1
-----------------

then there's bunch of paths, notes and errors, pointing to incompatible architecture (have (x86_64), need (arm64)
and mentioning error: linking with 'cc' failed: exit status: 1

-----------------
at the very end it also mentions:

Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11'] returned non-zero exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for kurbopy
Failed to build kurbopy
ERROR: Could not build wheels for kurbopy, which is required to install pyproject.toml-based projects
-----------------

Not sure if I have not installed everything or if it's a general issue with m1??

My system setup is:
Apple Mac Mini M1 2020 running Monterey 12.6

**Comment by miguelsousa** [comment]
Have you tried using a version of Python older than 3.11? Font Bakery has a lot of dependencies and most likely not all of them are ready for Python 3.11.

**Comment by miguelsousa** [comment]
This seems to be the same problem as #3970. Closing
