### ISSUE TITLE
Installation error reported

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery#3970]
**Describe the issue**
A `metadata-generation-failed` error was reported during installation under a new `venv`

**To Reproduce**
Create a new venv, update pip (`Successfully uninstalled pip-22.3`) and run the `pip install fontbakery` command 

Attaching here the complete report.
[FB-installation-ERROR-messages.rtf.zip](https://github.com/googlefonts/fontbakery/files/10125724/FB-installation-ERROR-messages.rtf.zip)

**Comment by miguelsousa** [comment]
I've ran into this as well. The problem seems to be coming from the `kurbopy` dependency.
Bellow is the result when running this simple install command on a new environment,

    pip install fontbakery

```
Collecting kurbopy>=0.8.32
  Downloading kurbopy-0.8.32.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 9.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by miguelsousa** [comment]
@simoncozens any ideas of what be going on?

**Comment by miguelsousa** [comment]
Looking at the available wheels of the [latest version of `kurbopy`](https://pypi.org/project/kurbopy/0.8.32/#files) I see that for the Mac platform the only wheel available is for Python 3.10 on arm64 architecture. This is a big problem.

@simoncozens Are you able to add the missing wheels for MacOS? Font Bakery is supposed to support all the 3 major platforms, from Python 3.7 onward.

**Comment by colinmford** [comment]
Seeing this as well — I was installing with Python 3.11, albeit on an Intel mac. I had to install rustup to get around it — certainly not ideal at all.

**Comment by miguelsousa** [comment]
@colinmford thanks for the input

**Comment by simoncozens** [comment]
Yep, sorry; I thought I had uploaded all the architectures but obviously not for that version. Will fix.

**Comment by miguelsousa** [comment]
Thank you!

**Comment by miguelsousa** [comment]
@simoncozens What's the dependency that requires `kurbopy`? The [macOS builds](https://github.com/googlefonts/fontbakery/actions/runs/3590363209) didn't fail, but they also didn't install `kurbopy`.

**Comment by simoncozens** [comment]
The shaper profile requires collidoscope, which (now) requires kurbopy.

**Comment by simoncozens** [comment]
Mac OS x86 wheel now uploaded.

**Comment by simoncozens** [comment]
And I've just uploaded a bunch of universal wheels, which should cover M1 on other Python versions.

**Comment by JamieClarkeType** [comment]
I'm seeing this as well, just now. Python 3.11 Intel Mac. Should I install rustup or wait for fix?

**Comment by simoncozens** [comment]
Give me a sec, I didn't even know there *was* a Python 3.11. I'll add it to the build matrix.

**Comment by JamieClarkeType** [comment]
Thank you Simon. No urgency from me!

**Comment by JamieClarkeType** [comment]
Thanks Simon. I'm getting this error now:

 running build_ext
      building 'lxml.etree' extension
      creating build/temp.macosx-10.9-universal2-cpython-311
      creating build/temp.macosx-10.9-universal2-cpython-311/src
      creating build/temp.macosx-10.9-universal2-cpython-311/src/lxml
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DCYTHON_CLINE_IN_TRACEBACK=0 -I/usr/include -Isrc -Isrc/lxml/includes -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/lxml/etree.c -o build/temp.macosx-10.9-universal2-cpython-311/src/lxml/etree.o -w -flat_namespace
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      Compile failed: command '/usr/bin/clang' failed with exit code 1
      creating var
      creating var/folders
      creating var/folders/ds
      creating var/folders/ds/53wr35kx6g38qqmqgj1vc21c0000gn
      creating var/folders/ds/53wr35kx6g38qqmqgj1vc21c0000gn/T
      cc -I/usr/include -I/usr/include/libxml2 -c /var/folders/ds/53wr35kx6g38qqmqgj1vc21c0000gn/T/xmlXPathInitcia2lmb8.c -o var/folders/ds/53wr35kx6g38qqmqgj1vc21c0000gn/T/xmlXPathInitcia2lmb8.o
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      Perhaps try: xcode-select --install
      *********************************************************************************
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: pip3 install --upgrade pip

**Comment by simoncozens** [comment]
That one's not me (building the lxml library). This is another area where there should be a binary wheel but it looks like there isn't one released for 3.11 yet. You need Xcode installed at least to build it from source, then follow https://lxml.de/build.html#building-lxml-on-macos-x

**Comment by JamieClarkeType** [comment]
Will do. Thanks

**Comment by miguelsousa** [comment]
> The shaper profile requires collidoscope, which (now) requires kurbopy.

Sorry, it's still unclear to me what makes `kurbopy` to be installed.
Is it because of a particular version of a primary Font Bakery dependency?
Is it because of a Font Bakery setting?

**Comment by simoncozens** [comment]
> Sorry, it's still unclear to me what makes kurbopy to be installed.

Collidoscope is a primary dependency of fontbakery because `fontbakery.profiles.shaping` imports `collidoscope`:

https://github.com/googlefonts/fontbakery/blob/cc9195912eecfa9a965db885d30a4ab4f33b5b79/Lib/fontbakery/profiles/shaping.py#L29

Kurbopy is a primary dependency of collidoscope because collidoscope imports `kurbopy`:

https://github.com/simoncozens/collidoscope/blob/master/Lib/collidoscope/__init__.py#L7

**Comment by JamieClarkeType** [comment]
This is all a little over my head. Is there an easier way to use Font Bakery without in-depth programming knowledge?

**Comment by miguelsousa** [comment]
@simoncozens thanks, that helped.
To summarize: The CI isn't failing because it installs [collidoscope v0.4.1](https://github.com/googlefonts/fontbakery/blob/47fececcfcbd0a6e6741091603ae1ae352c1c121/requirements.txt#L6), whereas Font Bakery's general installation is [not pinned to that version](https://github.com/googlefonts/fontbakery/blob/df92e643cd021f565c6b58e0fe6272c10b98739e/setup.py#L66); this meant that a later version of `collidoscope` was used, which has the `kurbopy` dependency.

**Comment by miguelsousa** [comment]
> Is there an easier way to use Font Bakery without in-depth programming knowledge?

Using Font Bakery is not complicated. ([Here's a brief manual in case it helps](https://github.com/adobe-type-tools/afdko/wiki/How-to-use-Font-Bakery)). What sometimes gets in the way is the state of Font Bakery's external dependencies. I believe that [Font Bakery's default installation is overbloated](https://github.com/googlefonts/fontbakery/issues/3874); reducing the dependencies that get installed by default will make the lives of the general Font Bakery user a lot easier.
In your case, you're also using a **very new** version of Python, which not all dependencies are ready to support yet.

**Comment by JamieClarkeType** [comment]
Thanks Miguel. 
I'll see if I can roll back a few versions of Python

**Comment by miguelsousa** [comment]
@simoncozens This problem is still happening on Windows. Please add the missing wheels for Windows (e.g. Python 3.9).

**Comment by JamieClarkeType** [comment]
Hi, I tried installing again today since FB updates. 
I got this error, any ideas?:

  DEPRECATION: lxml is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for lxml ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for lxml did not run successfully.
  │ exit code: 1
  ╰─> [121 lines of output]

**Comment by simoncozens** [comment]
> the 'wheel' package is not installed.

That may be your problem. Do `pip install wheel` and try again.

**Comment by JamieClarkeType** [comment]
Thanks @simoncozens 
I did that, then got this, (still something missing on my end?):
 xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      Perhaps try: xcode-select --install
      *********************************************************************************
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

**Comment by madig** [comment]
kurbopy 0.9.0 ships with binary wheels for macOS, Windows and Linux for all Python versions >= 3.7, so hopefully this is solved now.
