### ISSUE TITLE
Installing Freetype

### ISSUE THREAD

**Issue by beppeartz** [googlefonts/fontbakery#3977]
Hello i'm having this issues.
I'm running python on Monterey iMac 2015.

`
gs-iMac:~ giuseppesalerno$ python -m pip install --upgrade fontbakery'[freetype]'
Collecting fontbakery[freetype]
  Could not fetch URL https://pypi.python.org/simple/fontbakery/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping
  Could not find a version that satisfies the requirement fontbakery[freetype] (from versions: )
No matching distribution found for fontbakery[freetype]`

**Comment by miguelsousa** [comment]
Does it work if you remove the single quotes?

    python -m pip install --upgrade fontbakery[freetype]

**Comment by beppeartz** [comment]
unfortunately not

`gs-iMac:~ giuseppesalerno$ python -m pip install --upgrade fontbakery[freetype]
Collecting fontbakery[freetype]
  Could not fetch URL https://pypi.python.org/simple/fontbakery/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping
  Could not find a version that satisfies the requirement fontbakery[freetype] (from versions: )
No matching distribution found for fontbakery[freetype]
`

**Comment by miguelsousa** [comment]
Do you mind trying the command without the `[freetype]` part? That will tell us if there a problem with how Font Bakery extras are requested, or if it's something else.

**Comment by beppeartz** [comment]
Sure, i did.
Same error.

**Comment by miguelsousa** [comment]
Thanks. That suggests that there's something wrong with your system that may not be specific to fontbakery.
Try something as basic as the command below, which updates pip itself. You can use any other package available at pypi.org if you prefer. 

    python -m pip install --update pip

**Comment by beppeartz** [comment]
it's strange coz i'm using Font Bakery for checking and works fine.

**Comment by beppeartz** [comment]
`gs-iMac:~ giuseppesalerno$ python3 --version
Python 3.11.0
gs-iMac:~ giuseppesalerno$ 


`

**Comment by miguelsousa** [comment]
> it's strange coz i'm using Font Bakery for checking and works fine.

What works fine? I'm confused now

**Comment by beppeartz** [comment]
no...

`Last login: Sun Dec  4 14:32:06 on ttys004

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
gs-iMac:~ giuseppesalerno$ python -m pip install --update pip

Usage:   
  /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -m pip install [options] <requirement specifier> [package-index-options] ...
  /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -m pip install [options] -r <requirements file> [package-index-options] ...
  /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -m pip install [options] [-e] <vcs project url> ...
  /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -m pip install [options] [-e] <local project path> ...
  /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -m pip install [options] <archive url/path> ...

no such option: --update
gs-iMac:~ giuseppesalerno$ 
















`

**Comment by beppeartz** [comment]
no unfortunately

`gs-iMac:~ giuseppesalerno$ python -m pip install --update pip

Usage:   
  /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -m pip install [options] <requirement specifier> [package-index-options] ...
  /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -m pip install [options] -r <requirements file> [package-index-options] ...
  /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -m pip install [options] [-e] <vcs project url> ...
  /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -m pip install [options] [-e] <local project path> ...
  /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -m pip install [options] <archive url/path> ...

no such option: --update
`

**Comment by miguelsousa** [comment]
OK, I see what's going on. You have both Python 2.7 and 3.11 installed. In your system the `python` command will invoke 2.7, which Font Bakery no longer supports. So in your case the installation command should be,

    python3 -m pip install --upgrade fontbakery'[freetype]'

BUT because you have 3.11 installed the command will likely fail because Font Bakery depends on the `lxml` package which at the moment hasn't published a wheel for 3.11.

**Comment by miguelsousa** [comment]
> no such option: --update

My bad, the correct option is `--upgrade`

**Comment by beppeartz** [comment]
Works!

Thank you so much
