### ISSUE TITLE
[com.google.fonts/check/varfont/wdth_valid_range] The check is more strict than the OT spec

### ISSUE THREAD

**Issue by guidoferreyra** [googlefonts/fontbakery#3984]
## Observed behaviour

The check Fails when a font has an instance with a wdth value greater than 1000. but the spec says the following:

> Valid numeric range: Values must be strictly greater than zero.
https://learn.microsoft.com/en-gb/typography/opentype/spec/dvaraxistag_wdth

This is why I’m getting on the report:

> The variable font 'wdth' (Width) axis coordinate must be within spec range of 1 to 1000 on all instances.
> Check ID: <FontBakeryCheck:com.google.fonts/check/varfont/wdth_valid_range>
> 
> According to the Open-Type spec's registered design-variation tag 'wdth' available at https://docs.microsoft.com/en-gb/typography/opentype/spec/dvaraxistag_wdth
> 
> On the 'wdth' (Width) axis, the valid coordinate range is 1-1000
> 🔥 /MyFont-VF.ttf
> 
>     🔥 FAIL Found a bad "wdth" coordinate with value 1270.0 outside of the valid range from 1 to 1000. [code: wdth-out-of-range]

**Comment by josh-hadley** [comment]
closed by #4002

**Comment by guidoferreyra** [comment]
Thanks!
