### ISSUE TITLE
[com.google.fonts/check/required_tables] bullet_list adds unecessary And

### ISSUE THREAD

**Issue by punchcutter** [googlefonts/fontbakery#4006]
In the optional table report we get "And GSUB" which looks bad. `bullet_list` doesn't need to add an "And" for cases like this.

```
     INFO This font contains the following optional tables:                     
                                                                                
          - BASE                                                                
                                                                                
          - GPOS                                                                
                                                                                
          - And GSUB                                                            
```

**Comment by guidoferreyra** [comment]
I agree with this, I always find the "And" unnecessary

**Comment by felipesanches** [comment]
It is a left-over from the code that placed an "and" on comma separated list.

When I reused that code for bullet lists, the "and" ended up staying there. But yeah, if people prefer to not have it, it is trivial to fix. I'll do it now. Thanks for pointing this out.
