### ISSUE TITLE
Issue with Blaka Ink COLR family in Chrome

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#4020]
On Fri, Jan 13, 2023 at 10:00 PM Chris Simpkins <@chrissimpkins> wrote:
---

Hi Dominik!

Tobias recognized an issue with our [Blaka Ink COLR family](https://fonts.google.com/specimen/Blaka+Ink) in the Chrome browser.  The font worked at COLR launch last year but has at some point since started to use what appears to be the foreground color either partially or completely across the glyph in the Chrome browser.  I tested in macOS 13.1 with Chrome Version 109.0.5414.87 and can confirm that this family does work appropriately in current versions of Firefox and Safari on macOS 13.1.

Here are several screenshots with examples of the problem.
<img width="1775" alt="6MhiGLHtaBVrMSF" src="https://user-images.githubusercontent.com/213676/213331281-f093aa55-d019-45e0-b32e-d88e8d22ba51.png">
<img width="1778" alt="9SyTSpuVR6rD2pw" src="https://user-images.githubusercontent.com/213676/213331286-8417b9d5-b33b-4d78-ab86-b2f1beb72e61.png">
<img width="1786" alt="AdbyXphdpVwamJB" src="https://user-images.githubusercontent.com/213676/213331290-0d0a4aea-c030-4fbd-8a57-457b21afc012.png">

Do you happen to have any thoughts about why this is happening?

Thanks!

On Sat, Jan 14, 2023 at 7:19 AM Cosimo Lupo <@anthrotype> wrote:
---

I believe it might be related to this https://bugs.chromium.org/p/chromium/issues/detail?id=1404678 chrome bug that was fixed recently, which affects COLRv1 fonts that do not have explicit ClipBoxes (which are optional), in fact Blaka Ink has none.

I think all the COLRv1 fonts that are generated with nanoemoji will [include explicit clipboxes](https://github.com/googlefonts/nanoemoji/blob/5e6281b1c881ca3597760a9c0e0ad60ebaed71f4/src/nanoemoji/write_font.py#L641), whereas those (like Blaka Ink?) that are built using fontmake from .glyphs sources currently do not have explicitly defined ClipBoxes.

For ref., this is glyphsLib's code that populates ufo.lib with COLRv1 layers and color palettes, but unlike nanoemoji, no clipboxes: https://github.com/googlefonts/glyphsLib/blob/6d4aba6e2f61621b19a97863d27a77efeb101bec/Lib/glyphsLib/builder/color_layers.py#L167

On Sat, Jan 14, 2023 at 2:10 PM Cosimo Lupo <@anthrotype> wrote:
---

I just tried to load the Blaka Ink page using Chrome Canary 111.0.5538.0 on macOS 13.1 and it is displaying correctly, so maybe that bug has already been fixed.

Still curious to know what caused it and if there's a way to work around it

**Comment by anthrotype** [comment]
I think this can be closed since Chrome 111 was released earlier this month and contains the fix.
If you would like to make sure that the Blaka Ink font works on Chrome < 111, you may want to rebuild it using the latest ufo2ft 2.31.0 released today which can automatically compute clipboxes (adding a non empty ClipList works around that Chrome bug).
