### ISSUE TITLE
Improve code-test for com.google.fonts/check/italic_axis_last (opentype & googlefonts profiles)

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#4026]
Figure out whats the difference between these files:

* `shantell/ShantellSans-Italic[BNCE,INFM,SPAC,wght].fixed.ttf`
* `shantell/ShantellSans-Italic[BNCE,INFM,SPAC,wght].fixed-b.ttf`

Then substitute the `-b` file by the first one plus fontTools commands on the code-test, so that the difference is explicitly understood by whoever reads our code-tests.

The `-b` file was added by me while refactoring pull request #4023 by @yanone

Since there was an update to the ttf that was breaking a pre-existing code-test, I decided to split it into two files so that the code-tests are independent. It works, but the code-testing procedures are unclear by doing so. The testing is very opaque this way. So explicit python code would be better.

**Comment by yanone** [comment]
The difference is that one file has the ital axis last in the order in STAT and the other not. I'm preparing a PR

**Comment by felipesanches** [comment]
ok. #4027 was a good improvement.

But the testing is still opaque due to the actual difference between these 2 files not being explicitly stated on the code-test (preferably using fonttools scripting to perform the fixing):
* shantell/ShantellSans-Italic[BNCE,INFM,SPAC,wght].ttf
* shantell/ShantellSans-Italic[BNCE,INFM,SPAC,wght].fixed.ttf

**Comment by yanone** [comment]
So the file without `.fixed` is the result of splitting a VF with a complete `ital` axis into the Upright and Italic, but without adjusting the name table. This file is necessary to test for the name table adjustments as a _wrong_ file. But it's also used for testing whether both the Upright and the Italic still have an `ital` axis in `STAT`. If I rename the non-`.fixed` file here, I also need to rename the related Upright file.

Wait, I think I can rename the non-`.fixed` to `.unfixednametable` and remove `.fixed` from that other file and it should also work. I'll try that and maybe send you another PR

**Comment by felipesanches** [comment]
It is not a matter of file-naming. But of explaining the content of those files, or even better replicating the fixes via code, so that we can better trust them.

**Comment by yanone** [comment]
Oh, I see. Okay, I'll do it

**Comment by yanone** [comment]
There's at least one problem here: I don't know how to reorder STAT axes in code. I tried but failed and then decided to revert to a separate test file. Do you know how to do that?

**Comment by yanone** [comment]
Wait, I'm getting the hang of it

**Comment by yanone** [comment]
Done: https://github.com/googlefonts/fontbakery/pull/4028

**Comment by felipesanches** [comment]
thanks, @yanone!
