### ISSUE TITLE
[com.google.fonts/check/name/italic_names] Incorrectly Failing NID2 (Font Subfamily Name)

### ISSUE THREAD

**Issue by colinmford** [googlefonts/fontbakery#4061]
## Observed behaviour

Fonts with the following Name ID setup are failing this new test added because of #3666:

NID1 **My Font Medium**
NID2 **Italic**
NID16 **My Font**
NID17 **Medium Italic**

I get the error `🔥 FAIL
Name ID 2 (Subfamily Name) does not conform to font style. Expected: 'Medium Italic' Got: 'Italic'. [code: bad-subfamilyname]`

## Expected behaviour

This setup should pass. The only acceptable values for NID2 are "Regular", "Italic", "Bold" and "Bold Italic", [according to spec](https://learn.microsoft.com/en-us/typography/opentype/spec/name#name-ids). NID2 should not contain the weight/style beyond that.

**Comment by bobh0303** [comment]
We're seeing this also.

**Comment by bobh0303** [comment]
This test's results supply incorrect information to font developers. Please fixed or disable the test.

**Comment by yanone** [comment]
Looking into it now
