### ISSUE TITLE
[com.google.fonts/check/metadata/nameid/font_name] looks at nameID1 instead of 16?

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#4086]
## Observed behaviour

🔥 FAIL: METADATA.pb font.name value should be same as the family name declared on the name table. ([com.google.fonts/check/metadata/nameid/font_name](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/nameid/font_name))
🔥 FAIL Unmatched familyname in font: TTF has familyname = "Anybody Thin" while METADATA.pb has font.name = "Anybody". [code: mismatch]

## Expected behaviour

The name tables are correct and Fontbakery shouldn't fail. Consistency between Metadata.pb's Name field should match the real family name of the font: `nameID 16` if present,, and `nameID 1` if `no nameID 16`.

## Resources and exact process needed to replicate

https://github.com/google/fonts/pull/5976

**Comment by felipesanches** [comment]
Do you mean it should be the space-concatenated contents of nameIDs 16 and 17?

**Comment by felipesanches** [comment]
![Screenshot from 2023-03-15 17-28-57](https://user-images.githubusercontent.com/213676/225392428-49030ab2-9486-4cdd-8f69-5a7fead82724.png)

**Comment by RosaWagner** [comment]
The family name is only name ID 16.
Name ID 17 is the style name. Metdata.pb is only displaying the family name as "font name".

For example the family name of Anybody is "Anybody", not "Anybody Thin". If Thin ends up in NameID 1 it's because name ID2 is for style linking purpose, it can only contains RIBBI style names.

So it should really be:
- name ID 16
- name ID 1 if no nameID 16 (in the case of an actual RIBBI style)
