### ISSUE TITLE
New check: FAIL when description file has mailto: link or similar

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#4110]
## What needs to be checked?

Email address in description file.

## Detailed description of the problem 
The firsts families onboarded on GF were displaying the personal contact of the designer in the description file. Such thing should be removed. 

Fontbakery should FAIL whenever we upgrade a font and the description has the email of a designer in it.

## Resources and exact process needed to replicate

Here a description file containing such issue:
[DESCRIPTION.en_us.html.zip](https://github.com/googlefonts/fontbakery/files/11170756/DESCRIPTION.en_us.html.zip)

## Expected Profile

Please suggest in which profile should it be included. (You could inspect the Profiles's list at https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/index.html). Most common are:

- [x] Vendor-specific: Google Fonts
- [ ] Vendor-specific: Adobe Fonts
- [ ] OpenType (requirements imposed by the OpenType specification)
- [ ] Universal (broadly accepted best practices on the type design community)
- [ ] Other:

## Expected Result

Which log result level should it have:

- [x] 🔥 **FAIL** (Something that must be addressed for the propper functioning of the font)
- [ ] ⚠️ **WARN** (Highlights potential issues that are suggested to address)

## Severity assessment
5
(On a 1 to 5 level, how "buggy" would the font be considered if not including the aspect checked? Where 1 is something ideal to include but that would not affect the behavior of the font, and 5 is something that could lead to bad performance.)

**Comment by felipesanches** [comment]
This check already exists, but simply emits an INFO-level result:

![Screenshot from 2023-04-14 12-07-53](https://user-images.githubusercontent.com/213676/232028416-df012084-db42-43d3-9569-9b0a1a10e54c.png)

**Comment by felipesanches** [comment]
So, I will interpret this issue as a request to promote that INFO into a FAIL.

**Comment by felipesanches** [comment]
I'm also making email addresses a FAIL on METADATA.pb
