### ISSUE TITLE
New check: [name] Consistent Family Font names in 'name' table across fonts in family

### ISSUE THREAD

**Issue by kaydeearts** [googlefonts/fontbakery#4112]
I've looked through Fontbakery to see if there's a check that already does this, and could not find one. If there _is_ one that exists that I seem to have missed, please let me know. Otherwise, I can contribute a PR for adding this check very soon!

## What needs to be checked?

Validate that the family names in the name table are consistent across all fonts in the family. It checks Typographic Family name (nameID 16) if present, otherwise uses Font Family name (nameID 1)

## Detailed description of the problem 

We need to check if fonts in a font family all have consistent names for the font family name field in the name table (name ID 1). This is described in the [OpenType name table spec](https://learn.microsoft.com/en-us/typography/opentype/spec/name). Inconsistent font family names across fonts in a family can result in unexpected behaviors, such as style linking not working properly.

## Optional fix

Using [fonttools ttx](https://fonttools.readthedocs.io/en/latest/ttx.html):
ttx font.otf — running this will output a font.ttx file
Correct the font family name field (nameID 1) in the name table to be consistent with other fonts in the family
ttx -o fixed-font.otf -f font.ttx

## Resources and exact process needed to replicate

I've attached two files, one Upright and one Italic (modified CabinVFBeta fonts) here demonstrating the check.
- [Cabin-Regular.ttf.zip](https://github.com/googlefonts/fontbakery/files/11207479/Cabin-Regular.ttf.zip) — this font's Font Family Name field in the name table is "Cabin Different Family Name"
- [Cabin-Italic.ttf.zip](https://github.com/googlefonts/fontbakery/files/11207502/Cabin-Italic.ttf.zip) — this font's Font Family Name field in the name table is "Cabin".
Therefore, these two fonts have differing font family names despite being in the same family.

## Expected Profile

- [ ] Vendor-specific: Google Fonts
- [x] Vendor-specific: Adobe Fonts
- [x] OpenType (requirements imposed by the OpenType specification)
- [ ] Universal (broadly accepted best practices on the type design community)
- [ ] Other:

## Expected Result

- [x] 🔥 **FAIL** (Something that must be addressed for the propper functioning of the font)
- [ ] ⚠️ **WARN** (Highlights potential issues that are suggested to address)

**Comment by felipesanches** [comment]
sounds good!

**Comment by kaydeearts** [comment]
@felipesanches awesome, thanks! I'll work on a fix and push a PR soon.
