### ISSUE TITLE
FAIL: Checking OS/2 usWeightClass fixed in Roman but not in Italic

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/fontbakery#4113]
**Describe the issue**
🔥 FAIL: Checking OS/2 usWeightClass. ([com.google.fonts/check/usweightclass](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/usweightclass))
🔥 FAIL OS/2 usWeightClass is '300' when it should be '400'. [code: bad-value]

The weightclass is indeed 300 because the variable font origin is Light (we don't have regular master). The fail seems fixed in the Roman but not in Italic? Any ideas why? 🤔

Related to this: https://github.com/google/fonts/pull/6026#issuecomment-1506660472

**To Reproduce**
You can export the fonts from here, and run fontbakery: https://github.com/googlefonts/Playfair

**Screenshots**
<img width="1159" alt="Capture d’écran 2023-04-13 à 11 36 26" src="https://user-images.githubusercontent.com/64773544/231725793-8f8ec1fc-09ca-498c-9fae-01c0bd2f75ee.png">

**Comment by felipesanches** [comment]
thanks, @m4rc1e
