### ISSUE TITLE
Tool for checking and autofixing DESCRIPTION files

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#413]
For each DESCRIPTION.en_us.html file in every fontdirectory repo, reformat so that each tag is on its own line, and each sentence is on its own line. Example, http://fontdirectory.github.io/yesevaone/description.html

**Comment by davelab6** [comment]
@felipesanches looks like this was done but not applied. Relates to #220

**Comment by davelab6** [comment]
In `0.1.0` branch this is now renamed to `tools/fontbakery-check-description-fix.py`

**Comment by felipesanches** [comment]
There's a set of checks for DESCRIPTION files at our new codebase. It does validate a few things but it does not perform this specific check. I can added that if you need it.

The current tests nowadays live at https://github.com/googlefonts/fontbakery/blob/master/fontbakery-check-description.py

**Comment by davelab6** [comment]
Yes, I still need it :)

**Comment by davelab6** [comment]
So, the next action on this is to unify the checks across the check-ttf.py script and the check-description.py script, and add an autofix method that reformats the description files as described at the top of this issue.

**Comment by davelab6** [comment]
You must not delete the single-purpose tools like `fontbakery-check-description.py` because I use these all the time, and don't want the hassle of dealing with all the other stuff the big tester deals with :)

**Comment by davelab6** [comment]
> the next action on this is to unify the checks across the check-ttf.py script and the check-description.py script, and add an autofix method that reformats the description files as described at the top of this issue.

What I meant in this is that the stand-alone and big-check scripts should have the same logic for checking and autofixing, probably with copy and paste to keep it ultra simple, but they should both exist :)

**Comment by felipesanches** [comment]
alright! I can bring that one back :-) I thought you meant to move functionality away from a standalone script, towards integration in the main tool. But if you like to have both, that's good also (even though there's some code duplication involved)

**Comment by felipesanches** [comment]
alright!

I'll close the day now bringing that back. :-)

**Comment by felipesanches** [comment]
I think we're good to close the issue now, @davelab6

**Comment by davelab6** [comment]
> even though there's some code duplication involved

I understand why this is bad, but I prefer to keep things racially simple
