### ISSUE TITLE
Users need better help installing and using Font Bakery on Windows

### ISSUE THREAD

**Issue by Typedesigners** [googlefonts/fontbakery#4130]
> The `pip` command has to be run from the command line directly, not from within python. so type `exit()` and then run the pip command again.

![Screenshot 2023-05-02 103613](https://user-images.githubusercontent.com/124695645/235619121-8ae7c9eb-e673-4e52-bc54-129e56d35d3f.jpg)
Unfortunately, the installation of Font Bakery does not work.

_Originally posted by @Typedesigners in https://github.com/googlefonts/fontbakery/issues/4128#issuecomment-1531088954_

**Comment by Typedesigners** [comment]
@schriftgestalt 

I uninstalled Python and then installed it again. Now I was able to install Font Bakery. 

I specified the line  

fontbakery check-adobefonts -l FAIL

Unfortunately, I cannot copy the .ttf font into the window by dragging and dropping it after this line. What is the reason?

**Comment by Typedesigners** [comment]
As you can see from these examples, using Font Bakery is not possible for people who are not familiar with scripts and Python. It can't be that as a font designer you have to try the installation several times and look for errors. I hope that a user-friendly interface will be created that allows this software to be used immediately.

**Comment by felipesanches** [comment]
On the other hand, "getting familiar with scripts and python" is pretty much a requirement for professional font engineering nowadays. There will always be some level of technical knowledge required to work with fonts. In the past it was "machinery for melting metal to cast type blocks", nowadays it is mostly about software.

**Comment by Typedesigners** [comment]
With software like FontForge, FontLab and Glyphs, you can produce fonts without having to deal with Python. I don't believe that such famous type designers as Adrian Frutiger or Hermann Zapf, for example, have dealt with Python. But Python knowledge doesn't hurt, of course. If you want to develop software for as broad a target group as possible, this software should be user-friendly, preferably self-explanatory and manage without installing third-party software such as Python.

**Comment by miguelsousa** [comment]
@Typedesigners follow the instructions at https://github.com/adobe-type-tools/afdko/wiki/How-to-use-Font-Bakery#how-to-install-font-bakery

**Comment by Typedesigners** [comment]
@miguelsousa Thank you for this instruction. In which folder must the font be located so that it can be checked?

**Comment by Typedesigners** [comment]
I first tried to test OpenSans with Font Bakery as an example. Unfortunately, something doesn't seem to be working. I get the following message:
![Screenshot 2023-05-03 094830](https://user-images.githubusercontent.com/124695645/235859709-7d36329c-7a92-4529-96ae-4693ae93f260.jpg)

**Comment by Typedesigners** [comment]
@miguelsousa Although your instructions are clear and understandable, something doesn't seem to be working. I use Windows 11. It would be helpful if you could create a YouTube video tutorial that explains step by step how to install and use Font Bakery.

**Comment by graphicore** [comment]
@Typedesigners it doesn't look too bad though! Try using disabling the progress bar with the `-n` option, e.g.:

```
> fontbakery check-adobefonts -n "MyFont-Regular.ttf"
```

As the error is coming from a function called `draw_progressbar`.

I remember some years ago, @madig added  code to turn off the progress bar on windows, but it seems to not be a general problem anymore. 

**"Disable color output and progress bar on Windows by default "**: https://github.com/googlefonts/fontbakery/commit/9dfcb5bca4d73744bb6319ee055337643bd8a3da

That was removed again with **"Windows Terminal displays colors fine."**: https://github.com/googlefonts/fontbakery/commit/43266188361d78eea903f1a66590037f8eb44bac

Maybe it helps if you update to the latest PowerShell, as it is suggested by your shell, go to: https://aka.ms/PSWindows


>  I don't believe that such famous type designers as Adrian Frutiger or Hermann Zapf, for example, have dealt with Python

I'm not sure about Frutiger, but I believe Zapf was technically very proficient, working with Donald Knuth (etc.) on the Euler Metafont I'm sure he had to understand some of the stuff happening in the Metafont code. Python was not a thing back then. Even if he didn't write code himself, his influence on computer typography was massive! https://en.wikipedia.org/wiki/Hermann_Zapf

**Comment by miguelsousa** [comment]
> In which folder must the font be located so that it can be checked?

The font can be in any folder.

> I first tried to test OpenSans with Font Bakery as an example. Unfortunately, something doesn't seem to be working.

Yeah, that is an unusual error. From the traceback I can see that you're using Python 3.11. Do you mind using Python 3.10 instead?

**Comment by Typedesigners** [comment]
@miguelsousa @graphicore I have installed Python 3.10. My test: 
![Screenshot 2023-05-03 201710](https://user-images.githubusercontent.com/124695645/236008143-3fbb0254-10d7-424d-b3c4-81c93ab623e1.jpg)

**Comment by miguelsousa** [comment]
@Typedesigners looks like you got Font Bakery to work. Awesome! 😀 🧁

**Comment by Typedesigners** [comment]
@Typedesigners Thank you for your support! The Font Bakery is easy to install and use. The problem was with the current Python version. With Python 3.10 everything works fine.

**Comment by Typedesigners** [comment]
Unfortunately, the HTML report does not work for me. 

`fontbakery check-adobefonts --html report.html MyFont-Regular.ttf`

What could be the reason? The previous test with was successful

`fontbakery check-adobefonts -n "MyFont-Regular.ttf"`
![Screenshot 2023-05-05 180548](https://user-images.githubusercontent.com/124695645/236511319-f892e36a-18f4-4db5-899b-864f37f1e24c.jpg)

**Comment by miguelsousa** [comment]
@Typedesigners try using Lasse's suggestion of disabling the progress bar by using the `-n`/`--no-progress` option:

    fontbakery check-adobefonts -n --html report.html MyFont-Regular.ttf

**Comment by Typedesigners** [comment]
> @Typedesigners try using Lasse's suggestion of disabling the progress bar by using the `-n`/`--no-progress` option:
> 
> ```
> fontbakery check-adobefonts -n --html report.html MyFont-Regular.ttf
> ```

The test is successful, but where is HTML Report?
![Screenshot 2023-05-05 183054](https://user-images.githubusercontent.com/124695645/236515468-15f6de9b-3010-40ab-9b86-1d6a48ca8523.jpg)

**Comment by miguelsousa** [comment]
> The test is successful, but where is HTML Report?

You should now have a file named **report.html** in the **C:\Users\hello** directory.

**Comment by Typedesigners** [comment]
@miguelsousa Thank you very much!
