### ISSUE TITLE
Update color checks

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontbakery#4131]
Update the checks added in https://github.com/googlefonts/fontbakery/issues/3886 to match guidance in https://github.com/googlefonts/googlefonts.github.io/pull/82 once merged. Note in particular SVG is required only for static COLRv1.

**Comment by felipesanches** [comment]
"If the font is variable it must not have an SVG table"

Why? I vaguely recall someone explained this at a recent video call. Could you please describe the reasoning for this requirement?
