### ISSUE TITLE
[Check ID] <FontBakeryCheck:com.typenetwork/check/PUA_encoded_glyphs> 

### ISSUE THREAD

**Issue by glenda-tn** [googlefonts/fontbakery#4142]
(**NOTE:** Please include the check-id on the issue title. Check-id example [com.google.fonts/check/metadata/parses])

## Observed behaviour
This is a request to improve the rationale for the PUA encoding check.

Current PUA Rationale::
> Since it’s not frequent the use of PUA encoded glyphs, we want WARN when a font can be a bad use of it, like to encode small caps glyphs.

## Expected behaviour

Proposed PUA Rationale:
Using Private Use Area (PUA) encodings is not recommended. They are defined by users and are not standardized. That said, PUA are font specific so they will break if the user tries to copy/paste, search/replace, or change the font. Using PUA to encode small caps, for example, is not recommended as small caps can and should be accessible via Open Type substitution instead.

If you must encode your glyphs in the Private Use Area (PUA), do so with great caution.

## Resources and exact process needed to replicate

(Please provide here an URL to a font file that appears to cause the issue, and the exact steps from updating to the latest code on the `main` branch to reproduce the Observed Behaviour. We need this in for replicating the issue and fixing it :)

**Comment by simoncozens** [comment]
I'm really confused - I can't find this check at all, or any evidence that it ever existed?! Was this an internal profile you were using?

**Comment by glenda-tn** [comment]
oof, sorry @simoncozens, this was confused with the _unreachables_ check. TN's @guidoferreyra wrote this check. Thanks for checking!
