### ISSUE TITLE
[com.google.fonts/check/STAT/gf_axisregistry] Exception for ExtraBlack?

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/fontbakery#4146]
## Observed behaviour

Similar to this issue: https://github.com/googlefonts/fontbakery/issues/2804

Several fonts have an ExtraBlack style (Nunito Sans, DM Sans), and it seems to work well.
But I still have these FAILS: 
<details><summary>🔥 <b>FAIL:</b> Check a font's STAT table contains compulsory Axis Values. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/STAT">com.google.fonts/check/STAT</a>)</summary><div>

* 🔥 **FAIL** Compulsory STAT Axis Values are incorrect:

 | Name | Axis | Current Value | Current Flags | Current LinkedValue | Expected Value | Expected Flags | Expected LinkedValue |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Thin | wght | 100.0 | 0 | None | 100.0 | 0 | None |
| ExtraLight | wght | 200.0 | 0 | None | 200.0 | 0 | None |
| Light | wght | 300.0 | 0 | None | 300.0 | 0 | None |
| Regular | wght | 400.0 | 2 | 700.0 | 400.0 | 2 | 700.0 |
| Medium | wght | 500.0 | 0 | None | 500.0 | 0 | None |
| SemiBold | wght | 600.0 | 0 | None | 600.0 | 0 | None |
| Bold | wght | 700.0 | 0 | None | 700.0 | 0 | None |
| ExtraBold | wght | 800.0 | 0 | None | 800.0 | 0 | None |
| Black | wght | 900.0 | 0 | None | 900.0 | 0 | None |
| ExtraBlack | wght | 1000.0 | 0 | None | N/A | N/A | N/A |
 [code: bad-axis-values]
</div></details>

<details><summary>🔥 <b>FAIL:</b> Validate STAT particle names and values match the fallback names in GFAxisRegistry.  (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/STAT/gf_axisregistry">com.google.fonts/check/STAT/gf_axisregistry</a>)</summary><div>

* 🔥 **FAIL** On the font variation axis 'wght', the name 'ExtraBlack' is not among the expected ones (Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold, Black) according to the Google Fonts Axis Registry. [code: invalid-name]
</div></details>

## Expected behaviour

Could we make an exception for this style? (ExtraBlack=1000)
Or maybe there is a way to solve them that I didn't find!

## Resources and exact process needed to replicate

See: 
https://github.com/googlefonts/NunitoSans
https://github.com/googlefonts/dm-fonts

**Comment by m4rc1e** [comment]
There's currently no ExtraBlack in the axisregistry, https://github.com/googlefonts/axisregistry/blob/main/Lib/axisregistry/data/weight.textproto.

I know several families have an ExtraBlack so we should probably add it to the axisregistry if there are no objections.

**Comment by RosaWagner** [comment]
related discussions:

https://github.com/googlefonts/axisregistry/issues/103
https://github.com/googlefonts/axisregistry/issues/40

**Comment by emmamarichal** [comment]
Ah great thanks, so I can close this one
