### ISSUE TITLE
Do not run UFO checks on non-ufo files

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#424]
Do not run UFO checks on non-ufo files. These checks aren't needed and slow the process down:

```
git clone git@github.com:fontdirectory/GUPTER.git;
cd GUPTER;
fontbakery .;
$ bakery-lint.py upstream Gupter-Bold.otf
...
bakery_lint.tests.upstream.test_check_ufo_……..
```

**Comment by davelab6** [comment]
@felipesanches you had mentioned seeing this lately. Confirmed?

**Comment by felipesanches** [comment]
yeah! This is a duplicate of https://github.com/googlefonts/fontbakery/issues/623 (or vice-versa ;-D)
