### ISSUE TITLE
Use the Apple validation tools if they are available

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#445]
Apple offers a font validation tool, and https://blog.idrsolutions.com/2013/09/using-os-xs-font-validator/ describes how to use it. 

We should wrap this, similar to OTS (and MS Font Val) 

- [ ]  check if the command `ftxvalidator` is available on this system, perhaps using the `which` command:

```
    $ which ftxvalidator;
    /usr/local/bin/ftxvalidator
    $ which something-that-doesnt-exist
    $
```

- [ ] Run the tool on each file. 

To produce an XML (well, PLIST) output with 

    ftxvalidator -r -t all -o Font-Style.ats-fontlint.plist Font-Style.ttf

I think we just want the plain output for now, and if the output returned is the same as that returned for fonts that are known to be error free, as below, then we report `fb.ok("ftxvalidator passed the font.")` and if the output is not the same then we re-run it as `ftxvalidator -T font.ttf` (for a human readable table output) and include that multiline string in the log. 

```
$ ftxvalidator  fonts/apache/arimo/Arimo-Regular.ttf 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>kATSFontTestResultKey</key>
	<array>
		<string>kATSFontTestSeverityInformation</string>
		<string>kATSFontTestSeverityMinorError</string>
	</array>
</dict>
</plist>
$
```

* * * 

While I hoped this could be used on Travis's OS X environment, the URL http://adcdownload.apple.com/Mac_OS_X/os_x_font_tools/osxfonttools.dmg isn't available to anonymous GET requests, instead requiring an Apple ID login cookie. 

Long term, the `ftxvalidator` tool just wraps the `ATSFontTestCreateReport` method of the OS X `ATS` API, so we could make our own :)

- [ ] Make a small C program `ats-fontlint` that runs on Mac OS X that wraps the `ATSFontTestCreateReport` method's output and outputs a plist - same as `ftxvalidator`
- [ ] add a downstream test that only runs if the `ats-fontlint` command is available
- [ ] as a reference use `ftxvalidator -r -t all -o Font-Style.ats-fontlint.plist Font-Style.ttf` on each font
- [ ] add a parser to the Angular app that looks for this file and, if existing, then appends a row to the results table for each test
- [ ] refactor the graphs to account for these tests (perhaps so they work by counting the classes of the rows in the tables)

**Comment by davelab6** [comment]
@frank-trampe got stuck because the headers from apple aren't available to build a redistributable tool :(

**Comment by davelab6** [comment]
GAH. The installer in osxfonttools.dmg will not run on Mac OS X 10.11, so `ftxvalidator` is no longer available. What a pest.

**Comment by sladen** [comment]
What happens with a manual `hdiutil attach osxfonttools.dmg` from the command-line (or alternative way of looking directly inside).

**Comment by davelab6** [comment]
The disk image mounts, the .pkg installer inside will not run.

**Comment by sladen** [comment]
What happens with eg. `pkgutil --expand *.pkg foo`?

**Comment by davelab6** [comment]
Aha! 

```
cd ~/Downloads/ ;
hdiutil attach osxfonttools.dmg ;
mkdir -p /tmp/ftx ;
cd /tmp/ftx ;
cp "/Volumes/OS X Font Tools/OS X Font Tools.pkg" . ;
xar -xf "OS X Font Tools.pkg" ;
cd fontTools.pkg/ ;
cat Payload | gunzip -dc | cpio -i ;
./ftxvalidator 
ftxvalidator, build 200
Usage:  ftxvalidator [-hlrSTvV] [-t testList] [-o outputfile] fontfile
Options:
	-e An optional list of tests to exclude
	-h Output this message
	-l List available tests
	-o An optional output file for test results; stdout is used if this parameter is not specified
	-r Generate a full report
	-S Generate a summary report
	-t The tests to execute.  Valid inputs are:
		"all", execute all tests,
		"core", execute the core test set,
		"default", execute the default test set,
		or a list of font test types, separated by commas,
		or a list of test identifiers, separated by commas`	
	-T Generate a tabular report
	-v Verbose operation, additional data is output to stderr
	-V Output the tool's version to stdout
```

**Comment by HinTak** [comment]
Apple released a 'Font Tools for Xcode 8 beta' 2 weeks ago, apparently supposed to support 10.11 .

BTW, the next version of Font Validator already uses some of AppKit and CoreFoundation (due to using Apple's Webkit to get the built-in XML viewer to work) on Mac OS X, so it might be interesting to integrate more of Apple's font validation functionality in ATS into FontVal.

**Comment by davelab6** [comment]
@HinTak thanks for the tip about this :) The command line is still the same, it seems.

**Comment by davelab6** [comment]
@felipesanches I updated the tasks at the top

**Comment by felipesanches** [comment]
A major problem with this one is that I can't run the tool on my development computer. I may blindly code it (based on the expected output as described above) and ask for you to test and provide feedback, @davelab6

**Comment by davelab6** [comment]
yes please :)

**Comment by felipesanches** [comment]
plan for this:

- [ ] simple boilerplate for the test (commited at 9d4441927006a652459669725767c99625e6e647)
- [ ] warn if tool is not available
- [ ] print tool output (basic check implementation)
- [ ] add a new script to let the user select a known good font to use as output reference
- [ ] make this script save to a $HOMEDIR/.fontbakery/ftxvalidator_pass.xml file
- [ ] make the main test check for the availability of this file and use it, if available to compare and trigger the -T variabt of the tool invocation (for human-readable table output)
- [ ] make the check inform the user about the need to run the auxiliary setup script to select a good font in case the file is not found

Note that this is a bit similar to the caching of vendorIDs. But it is not the same. For vendorID we keep the cache file on /tmp so that we have to redo the procedure after every reboot (since we don't want the cache to last forever)

For the reference output, it is enough to bug the user only once. (there's the very unlikely issue of ftxvalidator changing its output formatting, but it can be handled by rerunning the setup script after such ftxvalidator update)

**Comment by davelab6** [comment]
The known good XML is  short and doesn't change. By using an external file
we complicate the tool. Please keep it simple and online the XML as a
string.

**Comment by felipesanches** [comment]
alright! Sounds Good. May break in the future when Apple perform some change on their ftxvalidator tool. But I'm OK to letting this to be dealt in the future whenever (and if) it happens at all.

**Comment by felipesanches** [comment]
@davelab6 Can you please provide the reference XML output for a known good font?
I'm unable to run the non-free tool myself.

**Comment by davelab6** [comment]
I did above on the top of the issue

**Comment by HinTak** [comment]
"known good font" is a tricky thing :-) - only about 2/3 of the Apple shipped fonts pass microsoft's font test.

Besides, I think you want to cater for "interesting reports". Being able to processing reports of perfect fonts (for a value of "perfect"...) is nice, but the task is quite pointless if you fail to process the "interesting" reports about buggy fonts...

For that, I think you actually want the XML output for a known *bad* font.

**Comment by HinTak** [comment]
A font that is sufficiently broken to generate an interesting report, but not so broken that the tool just gives up and refuses to process.

**Comment by felipesanches** [comment]
assigned @davelab6 since I'm waiting feedback on whether or not the test changes implemented at https://github.com/felipesanches/fontbakery/commit/0327b1bb0c1675a6932d7009f655383b91122fe9 work well or if I still need to tweak it somehow.

**Comment by madig** [comment]
`ftxvalidator` is a hard dependency it seems, so it's not possible to fully check a font for GF compatibility on non-Macs?
