### ISSUE TITLE
Check bakery.yaml is consistent for ttfautohint

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#446]
Would be nice to add a test in test_repo like https://travis-ci.org/googlefonts/fontbakery-cli/builds/37427151 so that if a devanagari subset is specified in `bakery.yaml` then there is a test that there `-f deva` option is used in all ttfautohint options in `bakery.yaml`

**Comment by davelab6** [comment]
We no longer create subsets, but knowing the subset potential of the fonts in the family and using that to advise ttfautohint options is good.

**Comment by felipesanches** [comment]
Old stuff. Not relevant anymore.
