### ISSUE TITLE
Consolidate repos

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#461]
- [x] Lets move the fontbakery-cli repo contents back to the fontbakery repo as its master branch, and
- [x] move the fontdirectory.github.io repo contents to the fontbakery repo as its gh-pages branch, and 
- [x] add a CNAME file containing fontbakery.com so that the dashboard is available from that URL.

**Comment by felipesanches** [comment]
Where was the old repo so that I can trace-back code history? I am performing some software archaeology looking for the origins of the "linegaps must be zero" check (nowadays called **com.google.fonts/check/041** - `"Checking Vertical Metric Linegaps."`)
