### ISSUE TITLE
FontBakery fails silently

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#480]
`fontbakery-build.py` fails silently on this TTX file which is rage inducing:

```
$ git clone https://github.com/davelab6/timmana.git;
$ cd timmana;
$ fontbakery-build.py .
$
```

- [ ] Ensure that fontbakery always prints what it is about to do, and when it completes doing something, so that when it fails you can see what failed and why

**Comment by davelab6** [comment]
@felipesanches I like the idea of

> Ensure that fontbakery always prints what it is about to do, and when it completes doing something, so that when it fails you can see what failed and why

for 2.0

**Comment by felipesanches** [comment]
@davelab6 Agreed! I had similar thoughts recently.

**Comment by davelab6** [comment]
@felipesanches how does the current script fare?

**Comment by davelab6** [comment]
> Ensure that fontbakery always prints what it is about to do, and when it completes doing something, so that when it fails you can see what failed and why

I think we are good on this
