### ISSUE TITLE
Support Jenkins CI

### ISSUE THREAD

**Issue by n8willis** [googlefonts/fontbakery#482]
Only supporting Travis-CI makes it less feasible to run fontbakery on a self-hosted Git repository.

It does not appear that Travis has any interest in supporting services other than GitHub; supporting Jenkins (or other self-hostable CI frameworks) would fix that and, thus, remove the current hard dependency on GitHub.com.

There are Jenkins-based services out there available to develop & test against, most notably BuildHive ( https://buildhive.cloudbees.com/ ).

**Comment by davelab6** [comment]
@n8willis the current single-file design means it should now be simple to get it going on Jenkins or other systems
