### ISSUE TITLE
Add check for unique family name based on the namecheck.fontdata.com web service

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#494]
Remove all the code for fontbakery-crawl.py, lets move that to its own standalone tool.

**Comment by vitalyvolkov** [comment]
Please create repo I will move there

**Comment by davelab6** [comment]
https://github.com/googlefonts/namecheck

**Comment by vitalyvolkov** [comment]
great, thanks

**Comment by vitalyvolkov** [comment]
Check the repo. There is setup script so you can install it. then run checknames.py from commandline.

**Comment by davelab6** [comment]
Sounds good

**Comment by davelab6** [comment]
@felipesanches This wasn't completed as https://github.com/googlefonts/fontbakery/blob/master/setup.py#L91 exists

**Comment by davelab6** [comment]
@felipesanches please port this namecheck tool into a single file program similar to other recent simple single file tools, `fontbakery-check-family-name.py`

**Comment by felipesanches** [comment]
@davelab6 It is not clear to me what "this namecheck tool" refers to. I looked at the repository at the state it was back in July 6th, 2016 as well as at a January 9th, 2015 and I could not locate the script that @vitalyvolkov mentioned in his comment above.

By looking at the fontbakery-crawl.py source code, I can only understand that it commands a web-crawler of some sort, but as the scrapy.cfg is not available, I can't figure out which specific webpage it targets. Some keywords make me believe it scraps webpages with font family names (perhaps Google Fonts repo pages?)

What exactly do you need here?

**Comment by davelab6** [comment]
Basically we need to check names are not already used, and today the best place to check that is https://namecheck.fontdata.com

**Comment by felipesanches** [comment]
https://namecheck.fontdata.com is down.

https://twitter.com/juca_gnu/status/935247794000064512

**Comment by felipesanches** [comment]
![screenshot at 2017-11-27 18 48 10](https://user-images.githubusercontent.com/213676/33288464-89ec1276-d3a3-11e7-8485-88092d6b757c.png)

**Comment by felipesanches** [comment]
Actually... http://namecheck.fontdata.com is still available. Only the HTTPS URL is broken.

**Comment by felipesanches** [comment]
So... it seems that this would be a new fontbakery check, emitting an **FAIL** if the family name is not unique.

The request of a standalone tool to query namecheck.fontdata.com, though, is now something for **gftools** so I'll also open a corresponding issue there.

**Comment by davelab6** [comment]
Perfect, thanks
