### ISSUE TITLE
Update pypi

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#525]
https://pypi.python.org/pypi/fontbakery/ has 0.0.3 but with https://github.com/googlefonts/fontbakery/commit/c45423b10ba1a196fd6fe3b9a3456d14a010b9e2 we are 0.0.6 :)

**Comment by vitalyvolkov** [comment]
I think it would be better to close bugs #523, #526, #532, #528  then make version to 0.0.7 :)

**Comment by davelab6** [comment]
Agree

**Comment by vitalyvolkov** [comment]
current version is 0.0.11
