### ISSUE TITLE
Add test to nbspace check for U+0009 having same width as nbspace and space

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#535]
According to the Microsoft spec at https://www.microsoft.com/typography/otspec/recom.htm, the TAB (U+0009) character should have an advance width equal to that of space.

**Comment by adrientetar** [comment]
It's just an "additional recommendation" though, personally I can't say I've ever seen the need for this.

**Comment by davelab6** [comment]
We should map the tab and nbspace glyphs to the space char so it cant get
bad when the space is updated
