### ISSUE TITLE
Fix the OpenType Name fixer

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#545]
```sh
git clone https://github.com/girish-dalvi/Ek-Mukta.git ;
cd Ek-Mukta/TTX ; 
ttx *ttx;
rm *ttx;
fontbakery-setup.py . ;
cat bakery.yaml ;

commit: HEAD
compiler: fontforge
license: OFL.txt
process_files: [EkMukta-Bold.otf, EkMukta-ExtraBold.otf, EkMukta-Extralight.otf, EkMukta-Light.otf,
  EkMukta-Medium.otf, EkMukta-Regular.otf, EkMukta-Semibold.otf]
pyftsubset: --notdef-outline --name-IDs=* --hinting
subset: [devanagari, latin, latin-ext]
ttfautohint: -l 7 -r 28 -G 50 -x 13 -w "G" -f deva -D deva

cd builds/066dc51;
mkdir OTF
cp ../../EkMukta-Regular.otf OTF/ ;
ttx -s sources/EkMukta-Regular.otf ;
mkdir TTF ; 
cp EkMukta-Regular.ttf TTF ; 
ttx -s TTF/EkMukta-Regular.ttf ;
meld OTF/ TTF/;
```

Here are the OTF and TTFs compared in this way. The NAME tables should be identical:

![screen shot 2015-06-02 at 3 25 49 pm](https://cloud.githubusercontent.com/assets/261579/7944929/b5170742-093b-11e5-96e1-36798d6bbcec.png)

![screen shot 2015-06-01 at 3 34 50 am](https://cloud.githubusercontent.com/assets/261579/7951887/22b8ee5c-097b-11e5-8cab-bee6479e6858.png)
![screen shot 2015-06-01 at 3 33 32 am](https://cloud.githubusercontent.com/assets/261579/7951886/22b8c076-097b-11e5-93cf-ff6a96dc31ed.png)
![screen shot 2015-06-01 at 3 33 59 am](https://cloud.githubusercontent.com/assets/261579/7951885/22b88ae8-097b-11e5-87b0-3b7f48e0cef2.png)
![screen shot 2015-06-01 at 3 35 11 am](https://cloud.githubusercontent.com/assets/261579/7951883/22b7fba0-097b-11e5-817d-844eced93579.png)
![screen shot 2015-06-01 at 3 34 30 am](https://cloud.githubusercontent.com/assets/261579/7951884/22b881a6-097b-11e5-8064-2311864418c7.png)
![screen shot 2015-06-01 at 3 36 47 am](https://cloud.githubusercontent.com/assets/261579/7951882/22b6ec56-097b-11e5-9885-d06625037814.png)

**Comment by vitalyvolkov** [comment]
That's because we change name record value with some values. Checker and fixer looks at what fsSelection, macStyle, italicAngle value has been set. With them it define what value for concrete name record it should be.

**Comment by davelab6** [comment]
Where is this code exactly?

The overall effect is wrong, I guess we need to be clear about which value
is the Source Of Truth.

Until it's working reliably, disable the fixing and just have it report
what should be changed.

Since the web ui is rotten, outputting the log as markdown to submit to
github issue on the designers repo could be best

**Comment by vitalyvolkov** [comment]
https://github.com/googlefonts/fontbakery/blob/master/bakery_cli/utils.py#L309

**Comment by vitalyvolkov** [comment]
I made it print to output in this format

```
EkMukta-Regular.ttf

NAMEID 1: "Ek Mukta Regular"
NAMEID 2: "Regular"
NAMEID 4: "Ek Mukta Regular"
NAMEID 6: "EkMukta-Regular"
NAMEID 16: "Ek Mukta"
NAMEID 1: "Ek Mukta Regular"
NAMEID 2: "Regular"
NAMEID 4: "Ek Mukta Regular"
NAMEID 6: "EkMukta-Regular"
NAMEID 16: "Ek Mukta"
NAMEID 17: "Regular"
NAMEID 18: "Ek Mukta Regular"
```

**Comment by davelab6** [comment]
It should be

```
NAMEID 1: "Ek Mukta Regular"
NAMEID 2: "Regular"
NAMEID 4: "Ek Mukta"
NAMEID 6: "EkMukta-Regular"
```

**Comment by davelab6** [comment]
We need to sit down and review this together :)

**Comment by vitalyvolkov** [comment]
Agree

**Comment by davelab6** [comment]
- [ ] The list at https://github.com/googlefonts/fontbakery/blob/master/bakery_cli/utils.py#L303 should be

```py
    styles = ['Thin', 'ExtraLight', 'Light', 'Regular', 'Medium',
              'SemiBold', 'Bold', 'ExtraBold', 'Black', 'Thin Italic',
              'ExtraLight Italic', 'Light Italic', 'Italic',
              'Medium Italic', 'SemiBold Italic', 'Bold Italic', 'ExtraBold Italic',
              'Black Italic']
```

**Comment by davelab6** [comment]
- [ ]  the check in https://github.com/googlefonts/fontbakery/blob/master/bakery_cli/utils.py#L311 doesn't quite make sense, 

```py
for x in fontdata['names'] if x['nameID'] in [1, 2, 4, 6, 16, 17, 18]]
```

because name ID 6 has no spaces, and is in a 'no spaces and a dash family/style separator' form (eg `FamilyCamelCase-StyleCamelCase` + `OpenSans-BoldItalic`) while name IDs 1, 2, 4, 16, 17, 18 are in a 'spaces ok and a space to separate family/style' form (eg `Family With Spaces Style With Spaces` + `Open Sans Bold Italic`) then this can't work

**Comment by davelab6** [comment]
https://github.com/googlefonts/fontbakery/issues/566 and https://github.com/googlefonts/fontbakery/issues/565 will help us to resolve this

**Comment by davelab6** [comment]
> The CFF FontName ( aka PostScript Font Name)  field is important and must be the same as the name table name ID 6 FontName

- Read Roberts in http://forum.fontlab.com/fontlab-studio-tips-and-tricks/optimizing-old-style-'kern'-table-kerning-export/

**Comment by davelab6** [comment]
This still isn't quite right. For example:

```
cd ~/src/github.com/;
mkdir weiweihuanghuang ;
cd weiweihuanghuang;
git clone https://github.com/weiweihuanghuang/Work-Sans.git;
cd Work-Sans ;
fontbakery-setup.py . ;

cat bakery.yaml ;
commit: HEAD
compiler: fontforge
license: LICENSE.txt
process_files: [fonts/webfonts/ttf/WorkSans-Black.ttf, fonts/webfonts/ttf/WorkSans-Bold.ttf,
  fonts/webfonts/ttf/WorkSans-ExtraBold.ttf, fonts/webfonts/ttf/WorkSans-ExtraLight.ttf,
  fonts/webfonts/ttf/WorkSans-Light.ttf, fonts/webfonts/ttf/WorkSans-Medium.ttf, fonts/webfonts/ttf/WorkSans-Regular.ttf,
  fonts/webfonts/ttf/WorkSans-SemiBold.ttf, fonts/webfonts/ttf/WorkSans-Thin.ttf]
pyftsubset: --notdef-outline --name-IDs=* --hinting
ttfautohint: -l 7 -r 28 -G 50 -x 13 -w "G"

fontbakery-build.py . ;

<output>

cd builds/6f14b37/ ;
mkdir TTF;
mkdir GIT;
cp *ttf TTF/;
cp ~/fonts/ofl/worksans/*ttf GIT/;
ttx -s */*ttf;
meld GIT TTF;
``

<img width="1811" alt="screen shot 2016-02-01 at 18 39 53" src="https://cloud.githubusercontent.com/assets/261579/12735109/25524a52-c913-11e5-8d36-097b7da1fab3.png">

Here we same name ID 4 is wrong on the right. 

Its close, though :)

**Comment by davelab6** [comment]
https://github.com/googlefonts/fontbakery/issues/748 is a child of this issue; closing that for now.

**Comment by davelab6** [comment]
https://github.com/googlefonts/fontbakery/issues/632 is a child of this issue; closing that for now.

**Comment by davelab6** [comment]
https://github.com/googlefonts/fontbakery/issues/628 is a child of this

**Comment by davelab6** [comment]
https://github.com/googlefonts/fontbakery/issues/631 is a child of this

**Comment by davelab6** [comment]
https://github.com/googlefonts/fontbakery/issues/649 is a child of this - it has the key information about PID1 namerecords

**Comment by davelab6** [comment]
@felipesanches what is the status of this?

**Comment by davelab6** [comment]
#281 is a child of this

**Comment by davelab6** [comment]
#782 is yet another child of this

**Comment by davelab6** [comment]
The `*_n_a_m_e*ttx` files in https://github.com/davelab6/glyphs-export/tree/master/Separate/TTF/TTX can be used as reference for this in name IDs 1, 2, 4, 6, 16, 17, 18

**Comment by felipesanches** [comment]
I'm bashing my head against this one and I can't really make sense out of it.
The examples in the previous comments are somewhat outdated and there's no clarity on what really needs to be done here.

I'm closing this one for good and I suggest a new issue be opened with a clear description of the problem and of the desired behaviour of the checker/fixer for the NAME table.

**Comment by davelab6** [comment]
The *_n_a_m_e*ttx files in https://github.com/davelab6/glyphs-export/tree/master/Separate/TTF/TTX can be used as reference for this in name IDs 1, 2, 4, 6, 16, 17, 18

**Comment by felipesanches** [comment]
This does not seem to be enough information for me to understand your request.

**Comment by felipesanches** [comment]
Does it mean that only the nameid entries that we see in https://github.com/davelab6/glyphs-export/tree/master/Separate/TTF/TTX should be in fonts tested by fontbakery?

**Comment by davelab6** [comment]
Yes, and fonts that do not follow the family/style pattern in those files should be error'd

**Comment by felipesanches** [comment]
ok. That's a bit more clear now, I think. I'll ask here if I have any further questions.

**Comment by felipesanches** [comment]
While reviewing all checks that alter the name table entries, I did implement one (that was requested as a "TODO: URGENT" comment in the source code). It was commited at https://github.com/googlefonts/fontbakery/commit/ac0f8d0ecfbd2df64803eefb71cee7086f5a3822 and is called "Assure theres no 'description' namerecord".

But then I found this other one which seems **almost** equivalent:

```
    logging.debug("Namerecord 10s (descriptions) exist?")
    new_names = []
    changed = False
    for name in font['name'].names:
      if 'opyright' in name.string.decode(name.getEncoding())\
         and name.nameID == NAMEID_DESCRIPTION:
        changed = True
        continue
      new_names.append(name)
    if changed:
      font['name'].names = new_names
      fb.hotfix("Namerecord 10s (descriptions)"
                " were removed (perhaps added by"
                " a longstanding FontLab Studio 5.x bug.)")
    else:
      fb.ok("Namerecord 10s (descriptions) do not exist.")
```

What's the rationale behind nameID #10 (Descriptions) ? Should none of these remain in the font table or only those with a 'copyright' substring?

**Comment by davelab6** [comment]
I think https://github.com/googlefonts/fontbakery/pull/829 sorts this out. Its not that there should be no descriptions, but they shouldn't be very long. I think 100 chars is good.

**Comment by felipesanches** [comment]
thanks

**Comment by felipesanches** [comment]
One of the reasons why this is sort of hard to tackle is the fact that we currently have tons of checks related to the name table entries. I feel that maybe these can be somewhat redundant perhaps.

In order to keep track of what's going on, these are all the current checks that deal with name table entries (line numbers refer to current master as of commit a583ec6d1d768e2ebb5e93e7bf9622e009ab49aa):

- [ ] 688: "Checking OS/2 achVendID"
- [ ] 740: "substitute copyright, registered and trademark symbols in name table entries"
- [ ] 889: "Check copyright namerecords match license file"
- [ ] 984: "Checking name table for items without platformID = 1 (MACHINTOSH)" '''Currently disbled!''' (It was commented out a while ago due to concerns pointed out at https://github.com/googlefonts/fontbakery/issues/797)
- [ ] 1018: "name record 10s (descriptions) are reasonable?"
- [ ] 1047: "StyleName recommendation"
- [ ] 1422: "Checking font version fields"
- [ ] 1665: "Version format is correct in NAME table?"
- [ ] 1797: "Does full font name begin with the font family name?"
- [ ] 1858: "Font follows the family naming recommendations?"
- [ ] 1971: "Font names are consistent across platforms?"
- [ ] 1990: "Are there non-ASCII characters in ASCII-only NAME table entries ?"
- [ ] 2011: "Font has a valid license url ?"
- [ ] 2295: "Font on disk and in METADATA.pb have the same family name ?"
- [ ] 2313: "Checks METADATA.pb 'postScriptName' matches TTF 'postScriptName'"
- [ ] 2332: "METADATA.pb 'fullname' value matches internal 'fullname' ?"
- [ ] 2350: "METADATA.pb fonts 'name' property should be same as font familyname"
- [ ] 2402: "METADATA.pb 'name' contains font name in right format ?"
- [ ] 2584: "Metadata key-value match to table name fields?"
- [ ] 2679: "METADATA.pb lists fonts named canonicaly?"
- [ ] 2704: "Font styles are named canonically?"

**Comment by felipesanches** [comment]
@davelab6 Would you like to separate these name-table checks to a standalone python script so that it's easier to read? I'd call it fontbakery-check-name-entries.py or something like that.

**Comment by davelab6** [comment]
A separate file doesn't effect readability. Please make a new section of
the main checker that runs before any of these.

**Comment by felipesanches** [comment]
I think you mean a section of the checker that runs all of these, right?

**Comment by davelab6** [comment]
Ignore the previous checks.

**Comment by felipesanches** [comment]
ok. So the immediate next step here is:

To implement a new checker that runs before any of the other name table related ones.
Each entry in the name table has a criteria for validity and the new checker must test if all entries in the name table are in conformance with that, right?
And this applies only to name IDs 1, 2, 4, 6, 16, 17, 18

**Comment by davelab6** [comment]
Right

**Comment by felipesanches** [comment]
I've compiled a set of rules that each name entry must obey according to the references @davelab6 posted here.

Please confirm if that's the way this should be tested.

NAMEID_FONT_FAMILY_NAME:
- must contain at least 1 space character (separating a couple words or more words)
- each word must begin in an uppercase character
- example: "Family Sans"

NAMEID_FONT_SUBFAMILY_NAME:
- Must be an empty string or one of the following: 'Thin', 'ExtraLight', 'Light', 'Medium', 'SemiBold', 'Bold', 'ExtraBold', 'Black'
- example: "ExtraBold"

NAMEID_FULL_FONT_NAME:
- Must be a space character separated concatenation of the strings declared in NAMEID_FONT_FAMILY_NAME and NAMEID_FONT_SUBFAMILY_NAME
- example: "Family Sans ExtraBold"

NAMEID_POSTSCRIPT_NAME:
- Must be a dash character separated concatenation of NAMEID_FONT_FAMILY_NAME (stripping any spaces and converting into CamelCase) and NAMEID_FONT_SUBFAMILY_NAME
- example: "FamilySans-ExtraBold"

NAMEID_TYPOGRAPHIC_FAMILY_NAME:
- Same rules as for NAMEID_FONT_FAMILY_NAME

NAMEID_TYPOGRAPHIC_SUBFAMILY_NAME:
- Same rules as for NAMEID_FONT_SUBFAMILY_NAME

**Comment by felipesanches** [comment]
Also a few questions:
- FamilySansExtraBold lacks an NAMEID_COMPATIBLE_FULL_MACONLY entry. Is that OK?
- This ExtraBold font has a "Regular" string in one of its NAMEID_FONT_SUBFAMILY_NAME entries... This confused me a bit:
https://github.com/davelab6/glyphs-export/blob/fdd7eb657455a97f9f2827a2804d0030299e467b/Separate/TTF/TTX/FamilySans-ExtraBold._n_a_m_e.ttx#L54 Is that OK?

**Comment by felipesanches** [comment]
Also there's something weird about nameID="4", since it differs among platforms:

* "Family Sans ExtraBold" on platformID="1"
* "FamilySans-ExtraBold" on platformID="3"

Is this correct? Should we have platform-specific rules for these entries?

**Comment by khaledhosny** [comment]
The MS platform convention for name id 4 has been dropped from the latest OpenType spec (and it was for OpenType-CFF fonts only IIRC) so there should be no difference in new fonts.

**Comment by felipesanches** [comment]
This PR has got an implementation of the checker: https://github.com/googlefonts/fontbakery/pull/836

I'm not sure if this is the correct implementation, but it is based on my understanding of the issue as described at https://github.com/googlefonts/fontbakery/issues/545#issuecomment-231895475

@davelab6 please review that comment (and perhaps also the code if you wish).

**Comment by davelab6** [comment]
> The MS platform convention for name id 4 has been dropped from the OpenType spec a while ago (and it was for OpenType-CFF fonts only IIRC) so there should be no difference in new fonts.

The sample files are from @schriftgestalt 's default export, which seem to offer the widest compatibility with software that people use, so even if its technically valid and working okay for all current releases, I think we should make fonts work as widely as possible and thus conform to old spec restrictions.

**Comment by davelab6** [comment]
> I've compiled a set of rules that each name entry must obey according to the references @davelab6 posted here.

Great!

> Please confirm if that's the way this should be tested.

OK :) 

My main advice is do not be clever with concatention and so on. There are only 18 possible cases. The filename is the source of truth about which case to check against. I think you have to discard all the code you wrote in e33fcbe722b94bf6f8db5f0a98f2bb7d97b07204 and take another approach that is much more simple, taking only the file name as input to construct the expected strings, by splitting family and style on a dash, and adding spaces before the 2nd capitalised character in the string to get the "with spaces" version. Where there are families in the collection that don't meet this rule, whitelist them. 

> NAMEID_FONT_FAMILY_NAME:

No, you need to distinguish NAMEID_FONT_FAMILY_NAME and PID together. 

NAMEID_FONT_FAMILY_NAME, both PIDS:

> - must contain at least 1 space character (separating a couple words or more words)

No, for family names that are single words there are no spaced. Rahter I would say, 

must space separate the family name

> - each word must begin in an uppercase character

Yes

Also:

- the string be ascii alphanumerical (a-z, A-Z, 0-9)
- the first character must be alphabetical, not a number
- must be a string

> - example: "Family Sans"

Yes, or "Family"

For PID=1 then it will always be the same across all styles. 

For PID=3 then it will only be the same for the 4 'core' or 'ribbi' styles (Regular, Italic, Bold, Bold Italic) and for the others it will be Family + Weight, eg "Italic" must never appear here.

Example: "Family Sans Thin" or "Family Medium"

> NAMEID_FONT_SUBFAMILY_NAME:
> 
> - Must be an empty string or one of the following: 'Thin', 'ExtraLight', 'Light', 'Medium', 'SemiBold', 'Bold', 'ExtraBold', 'Black'

No. It must be a string. For PID=1 then one of the following:

'Thin', 'ExtraLight', 'Light', 'Regular', 'Medium', 'SemiBold', 'Bold', 'ExtraBold', 'Black', 'Thin Italic', 'ExtraLight Italic', 'Light Italic', 'Italic', 'Medium Italic', 'SemiBold Italic', 'Bold Italic', 'ExtraBold Italic', 'Black Italic'

For PID=3 then one of the following:

'Regular'
'Italic'
'Bold'
'Bold Italic'

The style names 'Bold' and 'Bold Italic' are only used for those actual styles; everything else is 'Regular' if its a roman style and 'Italic' if its an italic style. 

> - example: "ExtraBold"
> 
> NAMEID_FULL_FONT_NAME:
> 
> - Must be a space character separated concatenation of the strings declared in NAMEID_FONT_FAMILY_NAME and NAMEID_FONT_SUBFAMILY_NAME

No. The above rules mean that this concatention approach won't work. 

> - example: "Family Sans ExtraBold"

Yes, that's 1 valid possibilty of 18. 

> NAMEID_POSTSCRIPT_NAME:
> 
> - Must be a dash character separated concatenation of NAMEID_FONT_FAMILY_NAME (stripping any spaces and converting into CamelCase) and NAMEID_FONT_SUBFAMILY_NAME

No. The above rules mean that this concatention approach won't work. 
 
> - example: "FamilySans-ExtraBold"

Yes, that's 1 valid possibilty of 18. 

> NAMEID_TYPOGRAPHIC_FAMILY_NAME:
> 
> - Same rules as for NAMEID_FONT_FAMILY_NAME

No. For PID=1 this should not exist. For PID=3 this should be the family name itself, without the style name included. 

> NAMEID_TYPOGRAPHIC_SUBFAMILY_NAME:
> 
> - Same rules as for NAMEID_FONT_SUBFAMILY_NAME

No. For PID=1 this should not exist. For PID=3 this should be the style name itself. 

Example, "Thin Italic"

There's also nameID=18 for PID=1. 

> Also a few questions:
> 
> - FamilySansExtraBold lacks an NAMEID_COMPATIBLE_FULL_MACONLY entry. Is that OK?

This must be included for PID=1.

> - This ExtraBold font has a "Regular" string in one of its NAMEID_FONT_SUBFAMILY_NAME entries... This confused me a bit:
> https://github.com/davelab6/glyphs-export/blob/fdd7eb657455a97f9f2827a2804d0030299e467b/Separate/TTF/TTX/FamilySans-ExtraBold._n_a_m_e.ttx#L54 Is that OK?

The file is correct. 

I hope the above explanation clarifies. 

> Also there's something weird about nameID="4", since it differs among platforms:
> 
> * "Family Sans ExtraBold" on platformID="1"
> 
> * "FamilySans-ExtraBold" on platformID="3"
> 
> Is this correct? Should we have platform-specific rules for these entries?

Yes. 

The file is correct. 

I hope the above explanation clarifies.

**Comment by khaledhosny** [comment]
I highly doubt that there is any software that relies on the old name id 4 restriction, plenty of fonts don’t do this (FontForge never did as well) and it was just there as a historical artefact. If it really mattered to Windows it would have not been just dropped from the spec, the whole name table structure is a legacy mess anyway.

**Comment by davelab6** [comment]
I hope @schriftgestalt can explain why Glyphs does it this way

**Comment by felipesanches** [comment]
https://github.com/davelab6/glyphs-export/blob/fdd7eb657455a97f9f2827a2804d0030299e467b/Separate/TTF/TTX/FamilySans-BlackItalic._n_a_m_e.ttx lacks a nameId="18"

@davelab6 Per https://github.com/googlefonts/fontbakery/issues/545#issuecomment-231926359 (specifically where you say "There's also nameID=18 for PID=1" and "must be included for PID=1") is this to be considered an issue with that font file?

**Comment by felipesanches** [comment]
actually... I just verified that none of the TTX files at your glyphs-export repo hane a name entry with nameid=18

**Comment by davelab6** [comment]
> I just verified that none of the TTX files at your glyphs-export repo hane a name entry with nameid=18

So did I :) Sorry, I misremembered :) Forget that comment :)

**Comment by felipesanches** [comment]
alright. Can I merge the pull request and close this issue then?

**Comment by felipesanches** [comment]
implementation merged into master!

**Comment by davelab6** [comment]
@felipesanches there is a branch open https://github.com/googlefonts/fontbakery/tree/issue_545 related to this issue; is this branch stale?

**Comment by felipesanches** [comment]
I never delete old branches.

Maybe I could. But I don't.

**Comment by davelab6** [comment]
I do ;) https://github.com/googlefonts/fontbakery/branches/all

**Comment by felipesanches** [comment]
oh! I see!

My personal fork has got them all in there. But I pushed this specific one to upstream instead of origin and so it was kept there forgotten. It can be safely deleted.

**Comment by felipesanches** [comment]
I've jsut deleted it.

**Comment by davelab6** [comment]
Thanks!
