### ISSUE TITLE
setup.py: missing ttfautohint should result in warning

### ISSUE THREAD

**Issue by sladen** [googlefonts/fontbakery#548]
Currently `python setup.py install` results in a hard failure if `ttfautohint` can't be found; as this is not needed for the majority of tests, it should not prevent general installation.

This is triggered by an assert at:

*  https://github.com/googlefonts/fontbakery/blob/master/setup.py#L29

Ideally the `setup.py` assert could be converted to a soft-failure (warning/hint) to the user; and any actual runtime callout to `ttfautohint` (should it occur) should result in helpful guidance about how to upgrade/install `ttfautohint`, and which minimum version is required.

**Comment by davelab6** [comment]
Fontforge too, since we are slowly moving away from fontforge to fonttools

**Comment by vitalyvolkov** [comment]
What best practice for showing messages? In setup steps and show the notification inside build logs?

**Comment by davelab6** [comment]
I think you should hold the message and print it at the very end of the process.

**Comment by vitalyvolkov** [comment]
Removed from setup and show the error message in the end of build.
