### ISSUE TITLE
fixers.py: should not crash on "from fontTools.ttLib.tables.D_S_I_G_ import SignatureRecord"

### ISSUE THREAD

**Issue by sladen** [googlefonts/fontbakery#549]
Running
* `~/…/kurale$ /usr/local/bin/fontbakery-check-ttf.py`

should not result in a backtrace from `fixers.py` ending with:
* `from fontTools.ttLib.tables.D_S_I_G_ import SignatureRecord`

This is likely dependent on the particular version of `fonttools` installed.  Possible solutions are to `try: … except:` the import and/or to validate the availability before import—either based on version, or preferably on just trying to do it and failing gracefully at point of use, instead of point of import.

import statement at:
* https://github.com/googlefonts/fontbakery/blob/master/bakery_cli/fixers.py#L29

Ideally, if the problem is truly fatal we should endeavour to help and guide the user towards an understandable solution to their predicament.  Some example guidance could be:

 *"The 'foo.ttf' font does not have an existing digital signature proving its authenticity, so Fontbakery needs to add one. To do this requires version N.NN of Fonttools to be installed. Please upgrade at.…"*

**Comment by davelab6** [comment]
Are you running latest fonttools from GitHub.com/behdad ? :)

**Comment by sladen** [comment]
(No, but) neither is our average user when trying to install this on $random_machine…

**Comment by anthrotype** [comment]
however, the README does say that one needs to 
```
pip install git+https://github.com/behdad/fontTools.git
```

**Comment by anthrotype** [comment]
but maybe Paul is right, it could be made more explicit.

**Comment by sladen** [comment]
I've tacked on another line to the summary to (try) and make it clearly that this is about the software trying to help the guide the user towards a solution

This the extreme case that could well be a combination of the suggestions above leading to something like "The 'foo.ttf' font does not have an existing digital signature proving its authenticity so Fontbakery needs to add one.  To do this requires version N.NN of Fonttools to be installed.  Please upgrade at.…"

**Comment by davelab6** [comment]
Generally I think at this point we should forget entirely about any use who
isn't us and actually get this working for us. At that point we can
consider growing the user base.

Specifically here I'm very keen that we don't spend time making stuff with
on the 2.4 version that is years old but widely packaged. There is an open
issue on behdads issue tracker for pypi packaging and if you think it is
important to run on a released version not git HEAD then let's help make a
new release

**Comment by sladen** [comment]
It might make sense to see what else I/we turn up; and then do a mid-year point-release of known-good "look here's the set of things we're working with and know work" on ~1 July 2015.  (That might then give a clear baseline).

**Comment by davelab6** [comment]
Oh I see - sorry my last reply was drafted offline before I saw your update to the summary; I agree that would be great
