### ISSUE TITLE
Check NAME id 5 (version) is correct

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#553]
As per https://github.com/google/fonts/issues/63 fb must check the NAME id 5 string value follows the pattern `Version X.Y`
- X is an int, 1+
- Y is an int, 0+

**Comment by adrientetar** [comment]
Although three numbers is conventionally used these days, it wasn’t always the case and spec says any numbers count is compliant for version minor. Also semicolon is not a requirement, anything that’s not a number terminates the number string. Termination is also optional.  
What should actually be enforced is `Version X.Y` where X and Y are any number of integers. If anything follows in the string that’s not numbers, it is ignored for the test.

**Comment by davelab6** [comment]
I agree, updated

**Comment by vitalyvolkov** [comment]
@davelab6 done

**Comment by davelab6** [comment]
@adrientetar since the `head` table doesn't allow for MAJOR.MINOR.PATCH I think a MAJOR.MINOR numbering scheme is best.
