### ISSUE TITLE
Package afdko for homebrew

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#567]
Following #564, lets

- [ ] set up a brew tap with a `afdko.rb` formula for macs

**Comment by davelab6** [comment]
@felipesanches did you make any documentation improvements when you installed it? just curious, no worries if not

**Comment by simoncozens** [comment]
Here's a start which builds and installs the executables. It also installs the Python scripts but it does *not* correct the `AFDKO_Python` and `AFDKO_Scripts` paths in `setFDKPaths`. This should be done with [inreplace](http://www.rubydoc.info/github/Homebrew/brew/master/Utils/Inreplace).

    class Afdko < Formula
      desc "Adobe Font Development Kit for Opentype"
      homepage "http://www.adobe.com/devnet/opentype/afdko.html"
      head "https://github.com/adobe-type-tools/afdko.git"

      def install
        cd "FDK/Tools/Programs/"
        system "./BuildAll.sh"
        cd ".."
        prefix.install "SharedData"
        bin.install Dir.glob("osx/*")
      end

      test do
        system "false"
      end
    end

**Comment by simoncozens** [comment]
And here is another version, which fixes up the paths but does not install the dependent Python modules.

    class Afdko < Formula
      desc "Adobe Font Development Kit for Opentype"
      homepage "http://www.adobe.com/devnet/opentype/afdko.html"
      head "https://github.com/adobe-type-tools/afdko.git"

      def install
        cd "FDK/Tools/Programs/"
        system "./BuildAll.sh"
        cd "../.."
        inreplace "Tools/osx/setFDKPaths" do |s|
            s.gsub! /AFDKO_Python.*/, "AFDKO_Python="+which("python")
            s.gsub! /AFDKO_Scripts=.*/, "AFDKO_Scripts="+prefix+"/Tools/SharedData/FDKScripts"
        end
        prefix.install "Tools"
        rmtree "#{prefix}/Tools/linux"
        rmtree "#{prefix}/Tools/Programs"
        rmtree "#{prefix}/Tools/win"
        prefix.cd do
            bin.install Dir["Tools/osx/*"]
            rmdir "Tools/osx"
            symlink "../bin", "Tools/osx"
        end
      end

      test do
        system "false"
      end
    end

**Comment by davelab6** [comment]
@simoncozens any news on this? :)

**Comment by davelab6** [comment]
I think at this point we should use fontmake, so closing.
