### ISSUE TITLE
Document scripts

### ISSUE THREAD

**Issue by n8willis** [googlefonts/fontbakery#568]
It would be really helpful to document the scripts. It looks like there was a doc directory circa https://github.com/googlefonts/fontbakery/issues/13 that disappeared?

**Comment by n8willis** [comment]
( ...and I would be happy to work on that, just in case it wasn't clear....)

**Comment by davelab6** [comment]
I think its too early to bother writing documentation, the tools aren't proven useful yet

**Comment by n8willis** [comment]
Well I wasn't thinking of a book, but something to help get new contributors oriented would be useful.

**Comment by davelab6** [comment]
@felipesanches I think the time is right for this, as it will help us when thinking of v2.0

**Comment by davelab6** [comment]
@felipesanches the argparse work you did a few weeks ago should make this easier :)

**Comment by felipesanches** [comment]
This is the last issue on milestone 0.1.0 and I'll be working on this one once I get back from the extended hollidays, on Sept. 8th.

**Comment by davelab6** [comment]
@felipesanches what is the status of this?

**Comment by felipesanches** [comment]
A quick thought here:

* doxygen?
* manpages?
* a simple README.md section?

**Comment by felipesanches** [comment]
Pending sub-tasks:
- [ ] https://github.com/googlefonts/fontbakery/issues/1065
- [ ] https://github.com/googlefonts/fontbakery/issues/1067
- [ ] https://github.com/googlefonts/fontbakery/issues/1068
- [ ] https://github.com/googlefonts/fontbakery/issues/1069

**Comment by felipesanches** [comment]
done!
