### ISSUE TITLE
fontbakery-fix-nbsp.py incorrect message

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#569]
Currently:
```
ER: Mitr-SemiBold.ttf space 330 nbsp 450: Change space to 450
```

Should be

```
ER: Mitr-SemiBold.ttf space 330 nbsp 450: Change nbsp to 330
```

**Comment by felipesanches** [comment]
@davelab6 Apparently this was already addressed by @vitalyvolkov commit https://github.com/googlefonts/fontbakery/commit/25d57f61b25e3befd0cff43b56d4598a8ce972b0 which was merged into master a while ago.

Please reopen this issue if you disagree.

**Comment by davelab6** [comment]
Yes, the issues assigned to me are for me to review and confirm the fix was
applied.

**Comment by felipesanches** [comment]
ok. So I better not touch them and leave it to you for review, then :-)

**Comment by davelab6** [comment]
Okay cool; I think you might not have enough context to close them.
