### ISSUE TITLE
Add fixer to fontbakery-fix-fsselection.py & fontbakery-fix-macstyle.py

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#570]
When building with fontbakery today, I found that the OS/2 table fsSelection and head table macstyle bits are not correctly set. 

https://www.microsoft.com/typography/otspec/os2.htm#fss describes how they should be:

<img width="900" alt="screen shot 2015-09-04 at 18 17 41" src="https://cloud.githubusercontent.com/assets/261579/9695589/46780d28-5331-11e5-8a0b-e38814aa10d9.png">

```
$ cd ~ ;
$ git clone https://github.com/google/fonts.git ;
$ mkdir -p ~/src/github.com/itfoundry ;
$ cd ~/src/github.com/itfoundry ;
$ git clone https://github.com/itfoundry/hind-vadodara.git ;
$ cd hind-vadodara/build/ ;
$ fontbakery-setup.py . ;
$ cat bakery.yml ;

commit: HEAD
compiler: fontforge
license: OFL.txt
process_files: [HindVadodara-Bold.otf, HindVadodara-Light.otf, HindVadodara-Medium.otf,
  HindVadodara-Regular.otf, HindVadodara-SemiBold.otf]
pyftsubset: --notdef-outline --name-IDs=* --hinting

$ fontbakery-build.py . ;
....
$ fontbakery-fix-fsselection.py *otf ;
filename                   fsSelection
-------------------------  -----------------
HindVadodara-Bold.otf      00000001 10100000
HindVadodara-Light.otf     00000001 10000000
HindVadodara-Medium.otf    00000001 10000000
HindVadodara-Regular.otf   00000001 11000000
HindVadodara-SemiBold.otf  00000001 10000000

$ fontbakery-fix-fsselection.py builds/e337be8/*ttf ;
filename                   fsSelection
-------------------------  -----------------
HindVadodara-Bold.ttf      00000001 10000000
HindVadodara-Light.ttf     00000001 10000000
HindVadodara-Medium.ttf    00000001 10000000
HindVadodara-Regular.ttf   00000001 10000000
HindVadodara-SemiBold.ttf  00000001 10000000

$ python ~/fonts/tools/sanity_check.py builds/e337be8/
...
FAIL: HindVadodara-Bold.ttf normal/700 fsSelection marked_bold 0 (builds/e337be8)
```

- [x] I would like the `fontbakery-fix-fsselection.py` tool to have an --autofix mode that corrects the fsSelection values 0 (italic) 5 (bold) and 6 (regular) based on the filename. Something like:

```
for bit in fsSelection:
   bit = 0
if filename contains "-Regular":
   fsSelection bit 6 = 1
if filename contains "-Bold":
   fsSelection bit 5 = 1
if filename contains "Italic":
   fsSelection bit 0 = 1
```

In particular this would correct the OS/2 fsSelection of the Bold. It is currently:

```
    <fsSelection value="00000001 10000000"/>
```

It should be:

```
    <fsSelection value="00000001 10100000"/>
```

I also see in the table at the top that the `head` table `macStyle` bits must match the `OS/2 fsSelection` bits:

> macStyle	
> Bit 0: Bold (if set to 1); 
> Bit 1: Italic (if set to 1) 
> Bit 2: Underline (if set to 1) 
> Bit 3: Outline (if set to 1) 
> Bit 4: Shadow (if set to 1) 
> Bit 5: Condensed (if set to 1) 
> Bit 6: Extended (if set to 1) 
> Bits 7-15: Reserved (set to 0).

These are correct in the OTF:

```
$ fontbakery-fix-macstyle.py *otf
filename                   macStyle
-------------------------  -----------------
HindVadodara-Bold.otf      00000000 00000001
HindVadodara-Light.otf     00000000 00000000
HindVadodara-Medium.otf    00000000 00000000
HindVadodara-Regular.otf   00000000 00000000
HindVadodara-SemiBold.otf  00000000 00000000
```

but not in the Font Bakery output:

```
$ fontbakery-fix-macstyle.py builds/e337be8/*ttf
filename                   macStyle
-------------------------  -----------------
HindVadodara-Bold.ttf      00000000 00000000
HindVadodara-Light.ttf     00000000 00000000
HindVadodara-Medium.ttf    00000000 00000000
HindVadodara-Regular.ttf   00000000 00000000
HindVadodara-SemiBold.ttf  00000000 00000000
```

- [x] I would like the `fontbakery-fix-macstyle.py` tool to have an --autofix mode that corrects the macstyle value 0 (bold) and 1 (italic) based on the filename.

```
for bit in macstyle:
   bit = 0
if filename contains "-Bold":
   macstyle bit 0 = 1
if filename contains "Italic":
   macstyle bit 1 = 1
```

- [x] I would also like to be able to set each macstyle bit manually using the tool.

**Comment by vitalyvolkov** [comment]
To set fsSelection and macStyle there is a script fontbakery-fix-italic.py, I think we should move fsSelection part of this to fix-fsSelection and macStyle part to fix-macstyle scripts. then remove the fontbakery-fix-italic as dup of those scripts.

**Comment by vitalyvolkov** [comment]
To set manually macStyle bits use --bit-bold and --bit-italic arguments.

```
fontbakery-fix-macstyle.py --bit-italic=1 --bit-bold=0 *ttf
```
