### ISSUE TITLE
New METADATA tester/fixer to compare google/fonts.git repo to API production files

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#573]
I'd like to request a standalone `fontbakery-metadata-vs-api.py` script:

- [x] first arg: `key` = string, key for Google Fonts Developer API
- [x] second arg: `repo` = path, to a directory tree that contains directories with `METADATA.json` files (eg a director where the google/fonts.git repo is checked out, or, a path to a build directory) 
- [x] optional arg: `cache` path, to a directory to store a copy of the files in the [fonts developer api](https://developers.google.com/fonts/docs/developer_api), default `/tmp/fontbakery-compare-github-api`
- [x] option: `verbose` to print additional information
- [x] option: `autofix` to apply automatic fixes to files
- [x] option: `api` = a domain string to use to request the  (default `fonts.googleapis.com`)

* * * 

- [x] Fetch `'https://www.googleapis.com/webfonts/v1/webfonts?key=' + $key` to get a list of all the families in production, and their ttf file urls, and other metadata
- [x] Walk the $repo tree and make a list of each path found with a METADATA.json file
- [x] For each METADATA file's family value not found in the API, print
```
ER: $family is not in production
```

- [x] For each METADATA file's family value found in the API
- [x] fetch all the font files, re-creating the directory structure of the URL inside $cache which is the equivalent of `mkdir fonts.gstatic.com/s/zeyada/v6/` (and the equivalent of `wget -x`)
- [x] Match the API `family` keys' values with the METADATA.json family keys

* * * 

- [x] For each family, match the API `subsets` list with the METADATA.json `subsets` list. 
- [x] If $verbose, print
```
OK: $family has $subset in Github and API
```
- [x] Print a list of the each `subset` list item not matched in the API 
```
ER: $family has $subset in Github but not in API
```
- [x] Print a list of the `subset` list items not matched in the git repo, eg
```
ER: $family has $subset in API but not in Github
```

* * * 

- [x] For each family, match the API `files` keys with the METADATA.json `fonts/weight` + `fonts/style` values, to match the API `files` values with the METADATA.json `fonts/filename` values
- [x] If $verbose, for each match, print
```
OK: $filename in Github and in API
```
- [x] Print a list of the `fonts/filename` values not matched in the API `files` eg
```
ER: $filename in Github but not in API
```
- [x] Print a list of the API `files` values not matched in any METADATA `files`
```
ER: $family-$style in API but not in Github
```
- [x] For each file that does match, check if they have the same md5 files. If $verbose, print 
```
OK: $METADATA.json/fonts/filename is in production
```
- [x] For each family where all files match, check the METADATA.json `visibility` value is "External". If $verbose, print 
```
OK: $METADATA.json/family visibility
```
- [x] Or if it not and $autofix is not set, print
```
ER: $METADATA.json/family visibility is "$family" should be "External"
```
- [x] Or if it not and $autofix is set, then write a fixed `METADATA.json.fix` file and print
```
ER: $METADATA.json/family visibility was "$family" is now "External"
```

**Comment by vitalyvolkov** [comment]
Please check

**Comment by davelab6** [comment]
@felipesanches this is now broken, because of the switch from json to pb. See #592

**Comment by felipesanches** [comment]
@davelab6 I just added support for reading those protobuffers and it seems to work. Please test it and reopen this issue if it still needs any further tweaks.
