### ISSUE TITLE
404 on generated build report when running with an account other than fontdirectory.github.io

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#575]
After all of the changes of pull request #574 , I finally got something that looks like a buildlog report on my gh-pages branch at https://github.com/felipesanches/ClintonST

But the link that it places on README.md (as well as the redirection I get when explicitely accessing felipesanches.github.io/ClintonST) brings me to a 404 page with the following address:
http://fontdirectory.github.io/collection/#/felipesanches/ClintonST/

It seems wrong behaviour to me. I think it should redirect to the subdomain of my own repository and not that of "fontdirectory". Apparently it is hardcoded to work only when run on the fontdirectory github account, which is obviously something we should change.

And indeed there are hardcoded references to fontdirectory.github.io here:

```sh
bakery_cli/report/utils.py
31:    repo_slug = os.environ.get('TRAVIS_REPO_SLUG', 'fontdirectory/dummy')
151:        self.repo_slug = os.environ.get('TRAVIS_REPO_SLUG', 'fontdirectory/dummy')
255:            <meta http-equiv="refresh" content="0; url=http://fontdirectory.github.io/collection/#/{slug}/" />"
264:        tmpl = '[{}](http://fontdirectory.github.io/collection/#/{}/)'.format(self.repo_slug, self.repo_slug)
```

**Comment by felipesanches** [comment]
OK. As I understand the issue now, the redirection should be made to URLs of the following format:
http://googlefonts.github.io/fontbakery/#/felipesanches/CoinyTests/

**Comment by davelab6** [comment]
Yes that sounds good
