### ISSUE TITLE
References to old GoogleCode Mercurial repository

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#576]
Data is fetched from the old GoogleCode Mercurial repository here:

```
bakery_lint/fonttests/test_metadata.py
136:        fp = urllib.urlopen('https://googlefontdirectory.googlecode.com/hg/designers/profiles.csv')
```

The access to a file on google code mercurial still works nowadays, but perhaps we should fetch this from the new repository on github, right?

https://github.com/google/fonts/blob/master/designers/profiles.csv

**Comment by davelab6** [comment]
Exactly
