### ISSUE TITLE
FontTool.get_tables test fails

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#579]
```bash
File "/home/travis/build/googlefonts/fontbakery/bakery_cli/ttfont.py", line 586, in bakery_cli.ttfont.FontTool.get_tables

Failed example:

    FontTool.get_tables("tests/fixtures/ttf/Font-Regular.ttf")

Expected:

    ['DSIG', 'FFTM', 'GDEF', 'GPOS', 'GSUB', 'OS/2', 'cmap', 'gasp', 'glyf', 'head', 'hhea', 'hmtx', 'kern', 'loca', 'maxp', 'name', 'post']

Got:

    ['head', 'hhea', 'maxp', 'OS/2', 'hmtx', 'cmap', 'loca', 'glyf', 'kern', 'name', 'post', 'gasp', 'DSIG', 'GDEF', 'GSUB', 'GPOS', 'FFTM']
```

**Comment by felipesanches** [comment]
The only difference between the expected opentype tables list and what it actually gets is the ordering.
Is the ordering really important? Or could we only test for the sorted contents of the list of table names?

**Comment by felipesanches** [comment]
I also see that the new ordering of table names in the tests was introduced in https://github.com/googlefonts/fontbakery/commit/d757db269fb8ca49271266290caf0921a89499cb by @davelab6 last month. What was the rationale for that change, Dave? It seems that it was that commit that broke the test.

**Comment by felipesanches** [comment]
@davelab6 Can you comment on this, please?

**Comment by davelab6** [comment]
That commit was to fix the same error. I suggest a true fix is to sort the
result and test then compare.
