### ISSUE TITLE
issues brought up by flake8 report

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#581]
The flake8 report lists 369 issues on the current codebase.

Most of these issues are related to code-style (bad indentation, whitespaces, etc..) except for these, which I suggest MUST be fixed:

- [ ] ./fontbakery-check-otf.py:50:38: F821 undefined name 'test' (moved to https://github.com/googlefonts/fontbakery/issues/582)
- [x] ./fontbakery-fix-italic.py:172:20: F821 undefined name 'getSuggestItalicAngle'
- [x] ./fontbakery-fix-nameids.py:49:27: F821 undefined name 'headers'
- [x] ./compute_font_weight_and_width.py:48:1: F401 'os' imported but unused
- [x] ./fontbakery-fix-familymetadata.py:56:9: F841 local variable 'row' is assigned to but never used
- [x] ./fontbakery-fix-macstyle.py:4:1: F401 'logging' imported but unused
- [ ] ./fontbakery-report.py:29:5: F401 'jinja2' imported but unused (It seems OK. See https://github.com/googlefonts/fontbakery/issues/581#issuecomment-160751830 Moved this to #584)
- [x] ./fontbakery-setup.py:21:1: F401 'sys' imported but unused

I'll be checking the boxes above when each of these already fixed by a commit.

**Comment by felipesanches** [comment]
The name getSuggestItalicAngle is not defined anywhere in the whole codebase, but we do have 
getPossibleItalicAngle which is also defined but not used anywhere. Both were introduced by vitalyvolkov on commit bd20074421189d33aa4e0544f1f9f73b3f0255f8 and the implementation seems correct, so I'll simply rename getPossibleItalicAngle.

Also I'll use the name getSuggestedItalicAngle to harmonize with the naming convention of other methods in our codebase (such as getSuggestedFontNameValues)

**Comment by felipesanches** [comment]
The jinja2 "imported but unused" message is not really an issue. It is just a side-effect of detecting early whether or not the module is installed. It forces the user to have jinja2 installed even if the user does not end up using any feature that depends on this module.

**Comment by davelab6** [comment]
Previous versions used it to make a web ui as a static site, but the web ui
was refactored to client side AngularJS so jinja2 imports can be removed now

**Comment by davelab6** [comment]
Yes rename getPossibleItalicAngle sounds good
