### ISSUE TITLE
cleanup "imported but unused" and "assigned but never used"

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#587]
This does not cause runtime errors. Fixing these warnings is only meant to clean the clutter. Thus, it is not something critical, but it is good to have it cleaned.

- [ ] ./bakery_cli/fixers.py:299:13: F401 'Bakery' imported but unused
- [ ] ./bakery_cli/fixers.py:34:1: F401 'nameTableRead' imported but unused
- [ ] ./bakery_cli/pipe/font_crunch.py:17:1: F401 'fnmatch' imported but unused
- [ ] ./bakery_cli/pipe/font_crunch.py:52:13: F401 'fontcrunch' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:10:1: F401 'Checkout' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:11:1: F401 'Zip' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:1:1: F401 'CopyDescription' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:1:1: F401 'CopyFontLog' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:1:1: F401 'Copy' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:1:1: F401 'CopyLicense' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:1:1: F401 'CopyMetadata' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:1:1: F401 'CopyTxtFiles' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:12:1: F401 'MetadataLint' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:13:1: F401 'UpstreamLint' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:14:1: F401 'FontCrunch' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:3:1: F401 'Build' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:4:1: F401 'TTFAutoHint' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:5:1: F401 'PyFtSubset' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:6:1: F401 'PyFontaine' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:7:1: F401 'Metadata' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:8:1: F401 'FontLint' imported but unused
- [ ] ./bakery_cli/pipe/__init__.py:9:1: F401 'Optimize' imported but unused
- [ ] ./bakery_cli/report/description.py:20:1: F401 'markdown' imported but unused
- [ ] ./bakery_cli/report/index.py:19:1: F401 'os' imported but unused
- [ ] ./bakery_cli/report/review.py:19:1: F401 'defaultdict' imported but unused
- [ ] ./bakery_cli/report/review.py:19:1: F401 'OrderedDict' imported but unused
- [ ] ./bakery_cli/report/review.py:21:1: F401 'markdown' imported but unused
- [ ] ./bakery_cli/utils.py:24:1: F401 're' imported but unused
- [ ] ./bakery_lint/fonttests/test_metadata.py:19:1: F401 'html5lib' imported but unused
- [ ] ./bakery_lint/fonttests/test_metadata.py:20:1: F401 'skip' imported but unused
- [ ] ./bakery_lint/fonttests/test_ttf.py:37:1: F401 'FontTool' imported but unused
- [ ] ./bakery_lint/__init__.py:17:1: F401 'fonttests' imported but unused
- [ ] ./bakery_lint/unicodeTools.py:1974:1: F811 redefinition of unused 'unicodedata' from line 1
- [ ] ./setup.py:18:1: F401 'os' imported but unused
- [ ] ./setup.py:25:5: F401 'fontforge' imported but unused
- [ ] ./tools/fontbakery-report.py:29:5: F401 'jinja2' imported but unused
- [ ] ./bakery_cli/fixers.py:165:17: F841 local variable 'has_errors' is assigned to but never used
- [ ] ./bakery_cli/fixers.py:225:13: F841 local variable 'cat' is assigned to but never used
- [ ] ./bakery_cli/fixers.py:793:9: F841 local variable 'suggestedvalues' is assigned to but never used
- [ ] ./bakery_cli/pipe/copy.py:107:9: F841 local variable 'task' is assigned to but never used
- [ ] ./bakery_cli/pipe/copy.py:46:17: F841 local variable 'args' is assigned to but never used
- [ ] ./bakery_lint/base.py:52:34: F841 local variable 'e' is assigned to but never used

**Comment by davelab6** [comment]
Closing due to rewrite
