### ISSUE TITLE
Unclear message: ['LICENSE.txt', 'OFL.txt'] does not exist in project

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#590]
The confusing test result message is:

```
required: FAIL: bakery_lint/fonttests/test_upstream.py: CheckTextFilesExist.test_licensetxt_exists():  Font folder should contain LICENSE.txt : ['LICENSE.txt', 'OFL.txt'] does not exist in project
```

why it is confusing:
* It says the folder should contain LICENSE.txt
* But it also mentions OFL.txt
* This message was displayed for a project that actualy contains an OFL.txt file. So does it mean it is required to have both files (OFL.txt and LICENSE.txt)?!
* Looking at the implementation of assertExists, it seems to have been coded with the intention of passing the test if at least one of the files is found. But that's not what I'm observing when running the tool on the CoinyTest repository. (https://travis-ci.org/felipesanches/CoinyTests)

**Comment by felipesanches** [comment]
Similarly, a repository containing a bakery.yml file triggers an error message about such file not being there...

```
note: FAIL: bakery_lint/fonttests/test_upstream.py: TestUpstreamRepo.test_bakery_yaml_exists():  Repository contains bakery.yaml configuration file? : File `bakery.yaml` does not exist in root of upstream repository
```

* This is the repository: https://github.com/felipesanches/CoinyTests
* And here's the error log on Travis: https://travis-ci.org/felipesanches/CoinyTests/builds/94977761

**Comment by davelab6** [comment]
Yikes. Proposed text:

required: FAIL: bakery_lint/fonttests/test_upstream.py:
CheckTextFilesExist.test_licensetxt_exists():  Font folder should
contain a license file ('LICENSE.txt' or 'OFL.txt') but none exists in
this project.

**Comment by davelab6** [comment]
This should be part of the fontbakery-check-onboarding.py

**Comment by davelab6** [comment]
@felipesanches what is the status of this?

**Comment by felipesanches** [comment]
this has been fixed a while ago. We nowadays say: "No license file was found. Please add an OFL.txt or a LICENSE.txt file."
