### ISSUE TITLE
Confirm requirements.txt is accurate

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#591]
I had to install these packages after installing the latest fontbakery in order for its scripts to run...
```
sudo pip install pyasn1 ;
sudo pip install characteristic ;
sudo pip install cryptography ;
sudo pip install zope.interface ;
```

**Comment by felipesanches** [comment]
This is my current set of installed pip packages as listed out by the command
***pip freeze***:

```bash
apt-xapian-index==0.45
BeautifulSoup==3.2.1
beautifulsoup4==4.2.1
bzr==2.7.0.dev1
bzr-fastimport===0.13.0.final.0
cffi==1.3.1
characteristic==14.3.0
chardet==2.0.1
colorama==0.2.5
configobj==4.7.2
cryptography==1.1.1
cssselect==0.9.1
cu2qu==1.0
decorator==3.4.0
defcon==0.1
defusedxml==0.4.1
dnspython==1.11.1
docutils==0.11
duplicity==0.6.23
ecdsa==0.10
Electrum==2.4.4
enum34==1.0.4
fastimport==0.9.2
feaTools==0.1
flake8==2.1.0
fontaine==1.3.10
fontbakery==0.0.13
FontCrunch==0.1
fonttools==3.0
futures==3.0.3
gitdb==0.6.4
GitPython==0.3.2rc1
html5lib==0.999
httplib2==0.8
idna==2.0
ipaddress==1.0.15
ipython==1.2.1
Jinja2==2.8
keyring==3.5
launchpadlib==1.10.2
lazr.restfulclient==0.13.3
lazr.uri==1.0.3
libxml2dom==0.5
livestreamer==1.12.2
lockfile==0.8
lxml==3.5.0
Mako==0.9.1
Markdown==2.6.4
MarkupSafe==0.23
matplotlib==1.3.1
mccabe==0.2.1
mercurial==2.8.2
mock==1.0.1
numpy==1.8.2
oauth==1.0.1
paramiko==1.10.1
pbkdf2==1.3
pep8==1.4.6
pexpect==3.1
Pillow==2.3.0
pingo==0.2.0
plyfile==0.4
protobuf==2.5.0
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.14
pycrypto==2.6.1
pycups==1.9.66
pycurl==7.19.3
pyflakes==0.8.1
pygame===1.9.1release
Pygments==1.6
pygobject==3.12.0
pygpgme==0.3
PyICU==1.9.2
PyMata==2.10
pyOpenSSL==0.15.1
pyparsing==2.0.1
pyserial==2.7
pysmbc==1.0.14.1
python-apt===0.9.3.5-7.0trisquel1
python-dateutil==1.5
python-debian===0.1.21-nmu2ubuntu2
python-magic==0.4.10
python-xlib==0.14
pytz==2012rc0
pyxdg==0.25
PyYAML==3.11
qrcode==4.0.1
queuelib==1.4.2
reportlab==3.0
requests==2.8.1
robofab==1.2
roman==2.0.0
Scrapy==1.0.3
SecretStorage==2.0.0
service-identity==14.0.0
simplegeneric==0.8.1
simplejson==3.3.1
singledispatch==3.4.0.3
six==1.5.2
slowaes==0.1a1
smmap==0.9.0
Sphinx==1.2.2
tabulate==0.7.5
Twisted==15.4.0
ufo2fdk==0.1
ufo2ft==0.1
ufoLib==1.2
ufonormalizer==0.1
Unidecode==0.4.18
urlgrabber==3.9.1
urllib3==1.7.1
urwid==1.3.1
w3lib==1.13.0
wadllib==1.3.2
wheel==0.24.0
xdot==0.5
zope.interface==4.0.5
```

There's plenty of unecessary packages (for fontbakery) installed on my system.

@davelab6 maybe you could output the list of packages from your system and we can perform an intersection of both lists ? :-)

To verify the precise set of dependencies required by fontbakery I have setup a virtualenv so that I could install packages individually from scratch, but fontbakery complains about not finding the python-fontforge package.

Trying to install it with pip results in:

```bash
pip install fontforge
Collecting fontforge
/home/felipe/devel/github_felipesanches/fontbakery/TesteVENV/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement fontforge (from versions: )
No matching distribution found for fontforge
```

Outside of the virtual environment I can run fontbakery's python setup install without issues (because it uses the fontforge-python package installed with apt-get)

**Comment by davelab6** [comment]
Please verify with a clean install, using a virtual machine

**Comment by felipesanches** [comment]
If we look at the travis config file, we'll notice that these are the pip packages that are installed in the Travis CI virtual machine:

- pip install pyicu
- pip install git+https://github.com/behdad/fontTools.git
- pip install git+https://github.com/googlefonts/fontcrunch.git
- pip install git+https://github.com/googlefonts/fontbakery.git

And, additionally, the GCC 4.8 compiler is installed, as well as the following deb packages:

- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo add-apt-repository --yes ppa:fontforge/fontforge
- sudo apt-get update -qq
- sudo apt-get install python-fontforge ttfautohint swig libicu-dev
- sudo apt-get install -qq g++-4.8

**Comment by davelab6** [comment]
Well, I had to install those packages after installing the latest fontbakery in order for its scripts to run, so there is a problem somewhere. 

> pip install pyicu
> pip install git+https://github.com/behdad/fontTools.git
> pip install git+https://github.com/googlefonts/fontcrunch.git
> pip install git+https://github.com/googlefonts/fontbakery.git

These should all be in requirements.txt, right?

**Comment by felipesanches** [comment]
yes. all of these should be in fontbakery's requirements.txt:

* pip install pyicu
* pip install git+https://github.com/behdad/fontTools.git
* pip install git+https://github.com/googlefonts/fontcrunch.git

except the last one, obviously:
* pip install git+https://github.com/googlefonts/fontbakery.git

I presume that the other packages that you installed manually but that are not listed in the travis setup are the ones that may already come pre-bundled in the Travis VM environment. We clearly  should add those to requirements.txt as well.

**Comment by felipesanches** [comment]
I'll open a pull request with our current understanding of what's needed in a requirements.txt file for fontbakery and then we can validate and/or improve it as needed.

**Comment by davelab6** [comment]
@girish-dalvi was able to install okay so I think we are now good here.
