### ISSUE TITLE
Replace all METADATA.json touchpoints with protocolbuffers support

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#592]
Following https://github.com/google/fonts/pull/162 we need to 

- [x] update fontbakery-build-metadata.py to support protocolbuffers
- [x] replace all other METADATA.json touchpoints with protocolbuffers support

**Comment by felipesanches** [comment]
@davelab6 Maybe we should first update the AngularJS app (on gh-pages) to accept protobuf data, given that valid data is already available from the hundreds of specific font projects at the google/fonts repo.

**Comment by davelab6** [comment]
Sadly, no - fontbakery has 2 purposes, the first and primary is to provide
tools I can use to onboard fonts to the GF API by hand, and the second
longer team purpose is to provide a CI system for fonts.

I need to be able to generate METADATA.pb files as part of (1) :)

**Comment by felipesanches** [comment]
ok, so generating the pb files is the number 1 priority and then consuming them on the webapp is just a secondary next-step, right?

**Comment by davelab6** [comment]
Yes :)

**Comment by davelab6** [comment]
https://github.com/google/fonts/blob/master/tools/add_font.py provides code for this.

**Comment by davelab6** [comment]
> Maybe we should first update the AngularJS app (on gh-pages) to accept protobuf data

The web app just treats the previous json files as text, so this will be a very small piece of work :)
