### ISSUE TITLE
fontbakery-fix-version.py

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#601]
I need a `fontbakery-fix-version.py` that allows easy getting/setting of the version metadata in a font file. 

First, getting them:
- [x] A head table's `<fontRevision>` eg `1.001` which https://www.microsoft.com/typography/otspec/head.htm says is of type 'fixed'
- [x] A name table's `<namerecord nameID="5">` records (which can be several) eg `Version 1.001` which https://www.microsoft.com/typography/otspec/name.htm says, 

> Version string. Should begin with the syntax 'Version <number>.<number>' (upper case, lower case, or mixed, with a space between “Version” and the number). The string must contain a version number of the following form: one or more digits (0-9) of value less than 65,535, followed by a period, followed by one or more digits of value less than 65,535. Any character other than a digit will terminate the minor number. A character such as “;” is helpful to separate different pieces of version information. The first such match in the string can be used by installation software to compare font versions. Note that some installers may require the string to start with “Version ”, followed by a version number as above.
- [x] name table `<namerecord nameID="3">` records (which can be several) may have a number at the start followed by a semicolon, eg `1.100;ABCD;Family-Regular` - this can also include a year date of format NNNN which should not be confused :)
- [x] If present, a CFF table's `<version value="001.000">` attribute, eg `001.000` 

Eg,

```
$ fontbakery-fix-version.py font.otf ;
head.fontRevision: 1.001
name.5.1.0.0: Version 1.001
name.5.3.1.1033:  Version 1.001
name.3.1.0.0: 1.001;ABCD;Family-Regular
name.3.3.1.1033: 1.001;ABCD;Family-Regular
cff.version: 001.000
$
```

Then, setting them
- [x] The script should allow trivially incrementing the major values,
- [x] The script should allow trivially incrementing the minor values,

Eg,

```
$ fontbakery-fix-version.py --increment-minor font.otf ;
Was:
head.fontRevision: 1.001
name.5.1.0.0: Version 1.001
name.5.3.1.1033:  Version 1.001
name.3.1.0.0: 1.001;ABCD;Family-Regular
name.3.3.1.1033: 1.001;ABCD;Family-Regular
cff.version: 001.001
Now:
head.fontRevision: 1.002
name.5.1.0.0: Version 1.002
name.5.3.1.1033:  Version 1.002
name.3.1.0.0: 1.002;ABCD;Family-Regular
name.3.3.1.1033: 1.002;ABCD;Family-Regular
cff.version: 001.002
$ fontbakery-fix-version.py --increment-major font.otf ;
Was:
head.fontRevision: 1.002
name.5.1.0.0: Version 1.002
name.5.3.1.1033:  Version 1.002
name.3.1.0.0: 1.002;ABCD;Family-Regular
name.3.3.1.1033: 1.002;ABCD;Family-Regular
cff.version: 001.002
Now:
head.fontRevision: 2.002
name.5.1.0.0: Version 2.002
name.5.3.1.1033:  Version 2.002
name.3.1.0.0: 2.002;ABCD;Family-Regular
name.3.3.1.1033: 2.002;ABCD;Family-Regular
cff.version: 002.002
$
```

Then, detecting "malformed" values. Eg, the major number should be 1 or more, and the minor number should not be smaller than 1.001 (but 1.000 is ok, but not 1.0001)
- [x] Add a `set` arg, eg

```
$ fontbakery-fix-version.py --set 2.002 font.otf ;
Was:
head.fontRevision: 1.002
name.5.1.0.0: Version 1.002
name.5.3.1.1033:  Version 1.002
name.3.1.0.0: 1.002;ABCD;Family-Regular
name.3.3.1.1033: 1.002;ABCD;Family-Regular
cff.version: 001.002
Now:
head.fontRevision: 2.002
name.5.1.0.0: Version 2.002
name.5.3.1.1033:  Version 2.002
name.3.1.0.0: 2.002;ABCD;Family-Regular
name.3.3.1.1033: 2.002;ABCD;Family-Regular
cff.version: 002.002
$
```

Felipe said below:

before closing this, I think I still need to:
- [ ] add the printing of previous values

```
Was:
head.fontRevision: 1.002
name.5.1.0.0: Version 1.002
name.5.3.1.1033:  Version 1.002
name.3.1.0.0: 1.002;ABCD;Family-Regular
name.3.3.1.1033: 1.002;ABCD;Family-Regular
cff.version: 001.002
Now:
[etc...]
```

**Comment by davelab6** [comment]
I've added a 'set' arg to the checklist above

**Comment by felipesanches** [comment]
before closing this, I think I still need to:
- [ ] add the printing of previous values
```
Was:
head.fontRevision: 1.002
name.5.1.0.0: Version 1.002
name.5.3.1.1033:  Version 1.002
name.3.1.0.0: 1.002;ABCD;Family-Regular
name.3.3.1.1033: 1.002;ABCD;Family-Regular
cff.version: 001.002
Now:
[etc...]
```

**Comment by davelab6** [comment]
Sounds good but lets postpone this to a more systematic project to make all the tools work the same way, with same default output styles, same output modes, etc etc

**Comment by felipesanches** [comment]
migrated to (merged into) https://github.com/googlefonts/tools/issues/20
