### ISSUE TITLE
Remove creation of static subsets

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#604]
The Google Fonts API now generates static subsets serverside, so this part of the `fontbakery-setup.py` script and related subsetting procedure in the build process can be removed:

```
What subsets do you want to create?
[X] cyrillic-menu (33%, 11%)
[ ] devanagari (1%)
[X] greek (2%)
[ ] greek-menu (23%, 7%)
[ ] latin (38%, 32%, 93%, 97%, 33%, 98%)
[X] latin-ext (22%, 26%)
[ ] vietnamese (16%, 15%)
[ ] vietnamese-menu (60%, 80%)
```

**Comment by felipesanches** [comment]
Maybe we should also ditch usage of pyftsubset?
Or is it also used by some other portion of the fontbakery code?

**Comment by davelab6** [comment]
> Maybe we should also ditch usage of pyftsubset? Or is it also used by some other portion of the fontbakery code?

It is used to subset the font to its own character set, dropped unneeded glyphs and tables.
