### ISSUE TITLE
New fontbakery-fix-whitespace-characters.py script

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#608]
In discussing #597, @rsheeter noted there are 3 nbsp problems:

1. fonts without an `&nbsp;`
2. fonts with an `&nbsp;` that is not the same width as `space`
3. fonts with an `&nbsp;` that has ink (that is, draws something. e.g. Voces)

Today we cover 1 & 2 in https://github.com/googlefonts/fontbakery/blob/master/bakery_cli/fixers.py#L370

So there should be a new script to 

- [ ] detect if whitespace characters have ink: non-0 contours or non-0 composites for glyf  (eg FontTools `glyph.isComposite()` `glyf.numberOfContours > 0`) and 
- [x] ~~similarly for the cff table equivalents~~ (we don't deal with CFF at the moment.)

- [ ] We also need to check anything with a width matches space

https://en.wikipedia.org/wiki/Whitespace_character provides the following list:

U+0009
U+000A
U+000B
U+000C
U+000D
U+0020
U+0085
U+00A0
U+1680
U+2000
U+2001
U+2002
U+2003
U+2004
U+2005
U+2006
U+2007
U+2008
U+2009
U+200A
U+2028
U+2029
U+202F
U+205F
U+3000
U+180E
U+200B
U+200C
U+200D
U+2060
U+FEFF

**Comment by davelab6** [comment]
Related to https://github.com/googlefonts/fontbakery/issues/535

**Comment by davelab6** [comment]
@felipesanches this should be part of the main ttf checker tool

**Comment by davelab6** [comment]
We also need to check anything with a width matches space

**Comment by felipesanches** [comment]
We already cover all of the above-listed issues in the ttf checker.

We have these checks:
* "Font contains glyphs for whitespace characters?"
* "Font has **proper** whitespace glyph names?"
* "Whitespace glyphs have ink?" (also checks coherence of advanceWidth values)

I think that the only thing missing is the list of whitespace characters and making sure the tests are run on any of those.
