### ISSUE TITLE
review google/fonts/tools/space_check.py

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#610]
In https://github.com/googlefonts/fontbakery/issues/597 @davelab6 said that:

" https://github.com/google/fonts/blob/master/tools/space_check.py has been released which provides much more thorough checking of the nbsp glyph, but no autofixing. "

Review this to see if some new space-related checks can be added to bakery_cli/fixers.py

**Comment by felipesanches** [comment]
The main test in there that we don't have yet in fontbakery seems to be "SPACE_HAS_INK", which verifies whether or not the space and nbsp glyphs contain "ink" (i.e. contours).

This seems to be a legitimate test, but I also doubt people would draw shapes on a space glyph on purpose.

**Comment by davelab6** [comment]
Not on purpose but by mistake

Voces and Atomic Age are live in production  with this  issue

**Comment by felipesanches** [comment]
Fair enough! So, I'll add these tests and a fixer that simply deletes any contours found in these glyphs.
