### ISSUE TITLE
bakery_lint/fonttests/test_ttf.py TTFTestCase.test_ots() fails

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#615]
> required: ERROR: bakery_lint/fonttests/test_ttf.py: TTFTestCase.test_ots():  Is TTF file correctly sanitized for Firefox and Chrome : run() got an unexpected keyword argument 'log'

https://github.com/felipesanches/scope-one/blob/gh-pages/build_info/data/buildlog.txt#L87-L88

**Comment by felipesanches** [comment]
I think this is the origin of the issue (and incomplete refactoring):

commit 1bcd61a83b915c529bdd36695b6b56f1a6f2a8b4
Author: vitalyvolkov <hash.3g@gmail.com>
Date:   Wed Jan 21 10:18:17 2015 +0200

    Codesource Enhancement #499
    
    * Extracted logging to logger module

**Comment by felipesanches** [comment]
I'll study that portion of the code and try to finish that refactoring to make this wrapper use the external logger module created by the aforementioned commit.

**Comment by felipesanches** [comment]
ok, I fixed it by simply not passing a logger object. The run method implementation (a wrapper around popen) already takes care of using the new logger infrastructure.

After making this change, I noticed though that we have another dependency for fontbakery, which is the OpenType Sanitizer, by @khaledhosny 

On my system I did fetch the latest master commit of his git tree at:
https://github.com/khaledhosny/ots

And then I built it with the classic:
```bash
./autogen.sh
./configure
make
sudo make install
```

Now Scope-One passes this test. We'll need to add something like this to the travis setup. I could not find a deb package, so it seems that, at least for now, travis will have to build always it from source.

**Comment by davelab6** [comment]
Please file an issue for setting up a ots ppa

**Comment by felipesanches** [comment]
OK, sure!

My attempt to building it from source on Travis has just succeeded. But indeed having a PPA sounds better.

**Comment by felipesanches** [comment]
After this fix, the OTS error does not show up anymore on the Scope-One build log at:
https://github.com/felipesanches/scope-one/blob/gh-pages/build_info/data/buildlog.txt
