### ISSUE TITLE
Deduplicate lines in buildlog.txt

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#616]
It seems that almost everything in buildlog.txt is duplicated... eg https://github.com/felipesanches/scope-one/blob/gh-pages/build_info/data/buildlog.txt#L1-L2

This should not happen.

**Comment by felipesanches** [comment]
OK. I reviewed several parts of the test codes in fontbakery trying to trace where exactly the double invocation happens, to no avail. Then I suspected it could be a side effect of the travis setup. I fiddled a bit with it as well with no good result.

I then noticed that when running fontbakery-check-ttf.py agains a single TTF in my local installation, I get no doubling of lines in the output error log.

So, what seems to be happening is that fontbakery is running the testsuite agains more than one font file simultaneously and this is causing one log error per test for each font file under examination.

I could replicate that behaviour by explicitely passing a couple TTF files to fontbakery-check-ttf.py on my local installation.

The couple files being tested simultaneously on travis seem to be the main font file and its latin subset, as described in the fonts field of the METADATA.json file.

@dave, do you agree with my analysis?

Also:
* How can we settle this issue, then?
* Should the test be run only on the main file, ignoring subsets?

**Comment by davelab6** [comment]
It should not be generating subsets any more.

**Comment by felipesanches** [comment]
So, it seem my explanation is flawed and I havent yet found what triggers the double output.

The experimentation on my local install seems to indicate that the check scripts are being invoked with a couple of files instead of a single one. I'll dig deeper in the code, then.

**Comment by felipesanches** [comment]
I have an insight that it may be showing the error messages once when a test fails and then it may be showing the same message again due to a failed attempt to fix the problem.

I'll investigate the code to see if that's the case.

The reason for my insight is that I noticed that a debugging print statements shows up only once when a test passes, but shows up twice when the test fails.

**Comment by felipesanches** [comment]
The following are 2 sets of the same errors being reported by different parts of the code (and using different notation):

These are the messages that the tests themselves print once failures are detected:
```
ER: test_check_menu_contains_proper_glyphs: 
FAIL: test_charset_latin: Raleway-BlackItalic.latin subset does not exist
FAIL: test_charset_latin_ext: Raleway-BlackItalic.latin-ext subset does not exist
FAIL: test_charset_menu: Raleway-BlackItalic.menu subset does not exist
FAIL: test_metadata_designer_exists_in_profiles_csv: Designer Multiple Designers is not in profiles.csv
FAIL: test_copyright_contains_correct_rfn: "Copyright (c) 2010 - 2013, Matt McInerney (matt@pixelspread.com), Pablo Impallari (impallari@gmail.com), Rodrigo Fuenzalida (hello@rfuenzalida.com) with Reserved Font Name "Raleway"" contains "Reserved Font Name"
FAIL: test_copyright_is_consistent_across_family: Copyright is inconsistent across family
FAIL: test_check_subsets_exists: The subset file for the Raleway-Thin.latin subset does not exist
FAIL: test_check_italic_style_matches_names: macStyle second bit is set but postScriptName "Raleway" is not ended with "Italic"
FAIL: test_the_same_names_of_glyphs_across_family: Family has a different glyphs's names in fonts
FAIL: test_the_same_number_of_glyphs_across_family: Family has a different glyphs's count in fonts
FAIL: test_menu_file_agreement: Raleway-Thin.menu does not exist
FAIL: test_check_canonical_weights: 250 != 100
FAIL: test_font_weight_same_as_in_metadata: METADATA.pb has weight 100 but in TTF it is 250
```

And these are the same messages, but printed by a sort of "final report" after all tests have been executed:
```
required: FAIL: bakery_lint/fonttests/test_metadata.py: MetadataSubsetsListTest.test_charset_latin(): Raleway-BlackItalic.latin is real TrueType file: Raleway-BlackItalic.latin subset does not exist
required: FAIL: bakery_lint/fonttests/test_metadata.py: MetadataSubsetsListTest.test_charset_latin_ext(): Raleway-BlackItalic.latin-ext is real TrueType file: Raleway-BlackItalic.latin-ext subset does not exist
required: FAIL: bakery_lint/fonttests/test_metadata.py: MetadataSubsetsListTest.test_charset_menu(): Raleway-BlackItalic.menu is real TrueType file: Raleway-BlackItalic.menu subset does not exist
required: FAIL: bakery_lint/fonttests/test_metadata.py: MetadataTest.test_metadata_designer_exists_in_profiles_csv():  Designer exists in GWF profiles.csv : Designer Multiple Designers is not in profiles.csv
info: FAIL: bakery_lint/fonttests/test_metadata.py: CheckMetadataContainsReservedFontName.test_copyright_contains_correct_rfn():  Copyright notice does not contain Reserved Font Name : "Copyright (c) 2010 - 2013, Matt McInerney (matt@pixelspread.com), Pablo Impallari (impallari@gmail.com), Rodrigo Fuenzalida (hello@rfuenzalida.com) with Reserved Font Name "Raleway"" contains "Reserved Font Name"
info: FAIL: bakery_lint/fonttests/test_metadata.py: CheckMetadataContainsReservedFontName.test_copyright_is_consistent_across_family():  Copyright notice is the same in all fonts? : Copyright is inconsistent across family
note: FAIL: bakery_lint/fonttests/test_metadata.py: CheckSubsetsExist.test_check_subsets_exists():  Check that corresponding subset files exist for fonts : The subset file for the Raleway-Thin.latin subset does not exist
note: FAIL: bakery_lint/fonttests/test_metadata.py: CheckItalicStyleMatchesMacStyle.test_check_italic_style_matches_names():  Check metadata.pb font.style `italic` matches font internal : macStyle second bit is set but postScriptName "Raleway" is not ended with "Italic"
note: ERROR: bakery_lint/fonttests/test_metadata.py: CheckMenuSubsetContainsProperGlyphs.test_check_menu_contains_proper_glyphs():  Check menu file contains proper glyphs
note: FAIL: bakery_lint/fonttests/test_metadata.py: CheckGlyphConsistencyInFamily.test_the_same_names_of_glyphs_across_family():  The same names of glyphs across family? : Family has a different glyphs's names in fonts
note: FAIL: bakery_lint/fonttests/test_metadata.py: CheckGlyphConsistencyInFamily.test_the_same_number_of_glyphs_across_family():  The same number of glyphs across family? : Family has a different glyphs's count in fonts
required: FAIL: bakery_lint/fonttests/test_metadata.py: CheckFontsMenuAgreements.test_menu_file_agreement():  Check fonts have corresponding menu files : Raleway-Thin.menu does not exist
note: FAIL: bakery_lint/fonttests/test_metadata.py: CheckCanonicalWeights.test_check_canonical_weights():  Check that weights have canonical value : 250 != 100
note: FAIL: bakery_lint/fonttests/test_metadata.py: CheckFontWeightSameAsInMetadata.test_font_weight_same_as_in_metadata():  Font weight matches metadata.pb value of key "weight" : METADATA.pb has weight 100 but in TTF it is 250
```

I think we should delete the code that generates this final report so we do not have any more duplication of error messages.

**Comment by felipesanches** [comment]
These errors are the output of tools/fontbakery-check-metadata.py and the "final report" is output by this block of code: https://github.com/felipesanches/fontbakery/blob/master/tools/fontbakery-check-metadata.py#L61-L72

**Comment by felipesanches** [comment]
Similar summary reporting may be causing duplicate messages in other scripts in the tools/ directory.

**Comment by davelab6** [comment]
I agree; while its nice to (for example) have the final report sorted by priority, it could just as easily be done with a unix pipe `| sort ` style, if the priorities are named nicely.

**Comment by davelab6** [comment]
I think for now just comment out the second blocks where you find them, and then for the 1.0.0 we should switch to using the python standard library Logging module.

**Comment by davelab6** [comment]
However, the 2nd style of output is the one I want (with the levels and filenames)

**Comment by felipesanches** [comment]
Alright! It seems I posted the 2 blocks above inverted. The first one is the "final report" and the second one is what the tests themselves are outputting. So I think that by simply commenting out the final report code, we'll get what we want. I'll open a pull request with this kind of changes.
