### ISSUE TITLE
test_font_unencoded_glyphs() should only error on glyphs inaccessible to opentype features 

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#618]
`bakery_lint/fonttests/test_ttf.py TTFTestCase.test_font_unencoded_glyphs()` should list which glyphs are unencoded **and** not accessible by OpenType features; the presence of unencoded glyphs themselves is acceptable if they are accessible by OpenType features. 
- [x] As an intermediate fix, just note this.
- [ ] explicitly mention which are the unencoded glyphs in the font.
- [ ] Use harfbuzz to determine if any glyphs can not be accessed; that is a real error.

**Comment by davelab6** [comment]
Currently the unencoded glyphs check is disabled in the check-ttf.py script; using harfbuzz like this is a 2.0 feature so I've moved this issue to that milestone

**Comment by simoncozens** [comment]
We have this check now (com.google.fonts/check/unreachable_glyphs).
