### ISSUE TITLE
When a project file is not an UFO, the tests from check-ufo.py should not be executed

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#623]
I noticed that the buildlog of the CoinyTests repo contain error messages from the check-ufo test suite. But the Coiny font project does not contain UFO files (the font sources are an SFD - fontforge - file).

So these tests shouldn't be even running at all...

**Comment by davelab6** [comment]
Totally agree!

**Comment by davelab6** [comment]
Fixed as consequence of rewrite
