### ISSUE TITLE
Fix up fontbakery-fix-gasp.py and set gasp table correctly when ttfautohint not used

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#624]
- [x] `fontbakery-fix-gasp.py` seems to not be working at all, as it doesn't detect gasp tables in fonts that have them:

```
$ fontbakery-fix-gasp.py ~/fonts/ofl/merriweather/Merriweather-Regular.ttf 
no table gasp
$ ttx -t gasp ~/fonts/ofl/merriweather/Merriweather-Regular.ttf 
Dumping "Merriweather-Regular.ttf" to "Merriweather-Regular.ttx"...
Dumping 'gasp' table...
$ cat ~/fonts/ofl/merriweather/Merriweather-Regular.ttx
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="3.0">

  <gasp>
    <gaspRange rangeMaxPPEM="65535" rangeGaspBehavior="15"/>
  </gasp>

</ttFont>
$
```

- [x] If ttfautohint is not used, the gasp table could be like,

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ttFont ttLibVersion="3.0">

  <gasp>
    <gaspRange rangeMaxPPEM="65535" rangeGaspBehavior="2"/>
  </gasp>

</ttFont>
`````

but it should be,

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ttFont ttLibVersion="3.0">

  <gasp>
    <gaspRange rangeMaxPPEM="65535" rangeGaspBehavior="15"/>
  </gasp>

</ttFont>

```

**Comment by felipesanches** [comment]
@davelab6 It is not clear to me what's the expected behaviour for the tool in the aforementioned "If ttfautohint is not used" case. Can you ellaborate on that?

**Comment by davelab6** [comment]
The gasp value should be set to that shown in the xml

**Comment by davelab6** [comment]
@felipesanches does this make sense now?

**Comment by davelab6** [comment]
To complete this you need to figure out how to use fontTools to set the gaspRange so that the XML output of the result is as follows. 

```
<?xml version="1.0" encoding="UTF-8"?>
<ttFont ttLibVersion="3.0">

  <gasp>
    <gaspRange rangeMaxPPEM="65535" rangeGaspBehavior="15"/>
  </gasp>

</ttFont>
```

**Comment by davelab6** [comment]
Also I note that ttfautohint will do that, but this is for fonts where the design is not for text and hinting isn't helpful.

**Comment by felipesanches** [comment]
ok, I see. Thanks!

**Comment by davelab6** [comment]
https://www.microsoft.com/typography/otspec/gasp.htm seems straightforward to me; basically there are several code paths in a font renderer, and the gasp table allows the font to select which renderer mode is used.
