### ISSUE TITLE
Better handling of Unicode fields ?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#626]
There are several instances of code like this in our codebase:

```python
    if name.platformID == 3 and name.isUnicode():
        name.string = title.encode('utf-16-be')
    else:
        name.string = title
```

I have the impression that this is error-prone and that it should be substituted by something more general like this:
```python
    name.string = title.encode(name.getEncoding())
```

I feel I should ask if @behdad agrees with that understanding. What do you think?

**Comment by anthrotype** [comment]
The `table__n_a_m_e` class has a `setName` method to do that:
https://github.com/behdad/fonttools/blob/0b09d33d8a24e649672ee5c77c87ff0d38564bb0/Lib/fontTools/ttLib/tables/_n_a_m_e.py#L114

**Comment by felipesanches** [comment]
I know... but using setName does not look as clean as seting the strings value directly:

Using setName:
```python
    name.setName(title, name.nameID, name.platformID, name.platEncID, name.langID)
```

Not using it:
```python
    name.string = title.encode(name.getEncoding())
```

**Comment by behdad** [comment]
I'm fairly sure if you set name.string to a Unicode string, fonttools takes care of the encoding for you.

**Comment by behdad** [comment]
> name.string = title.encode(name.getEncoding())

Yes, this is correct.

**Comment by felipesanches** [comment]
@behdad There's a weird code snippet at https://github.com/googlefonts/fontbakery/blob/master/bakery_cli/ttfont.py#L306-L312

```python
    @staticmethod
    def bin2unistring(record):
        if b'\000' in record.string:
            return record.string.decode('utf-16-be')
        elif not isinstance(record.string, unicode):
            return unicode(record.string, 'unicode_escape')
        return record.string
```

Not sure how to refactor this one...

**Comment by felipesanches** [comment]
I don't think this is safe as well:

https://github.com/googlefonts/fontbakery/blob/master/bakery_cli/pipe/pyftsubset.py#L25-L30

```python
def bin2unistring(string):
    if b'\000' in string:
        string = string.decode('utf-16-be')
        return string.encode('utf-8')
    else:
        return string
```

**Comment by behdad** [comment]
There's a bunch of hacks I've added to fonttools, that should replace this piece of code IMO:

https://github.com/behdad/fonttools/blob/ba90369af93f4a73679d4d72ddf41ef15cf887a5/Lib/fontTools/ttLib/tables/_n_a_m_e.py#L151

**Comment by behdad** [comment]
Yeah, all of those should be replaced by name.toUnicode() IMO.

**Comment by davelab6** [comment]
Thanks for your input here Behdad! :D

**Comment by felipesanches** [comment]
yeah! Thanks, @behdad :-)
