### ISSUE TITLE
Tools to prepare font families for inclusion in github.com/google/fonts

### ISSUE THREAD

**Issue by bardware** [googlefonts/fontbakery#627]
The title of this repository says `Tools to prepare font families for inclusion in github.com/google/fonts`. That repo seems gone. Where is it?

**Comment by loremipsumdolor** [comment]
+1. I can't find a single announcement on its disappearance, and even the Google Fonts site points to the (now nonexistent) repo.

**Comment by bardware** [comment]
The Repo is up again.
