### ISSUE TITLE
fontbakery-fix-nameids.py --autofix to rm namerecords with platformID="1"

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#628]
https://github.com/googlefonts/fontbakery/issues/566 specified a tool to print name ids, `tools/fontbakery-fix-nameids.py`

This now needs an `--autofix` arg/method, that removes all namerecords with platformID="1".

cc @girish-dalvi

**Comment by felipesanches** [comment]
I'm working on this one now

**Comment by felipesanches** [comment]
@davelab6 I did implmement it and it works as specified (all nameRecords with platformID=1 are removed from the font file). But I'm curious to learn why this deletion is useful for you.

**Comment by felipesanches** [comment]
Also, it makes me wonder if you don't prefer to have a parameter to specify which platformID value shuld trigger the deletion of nameRecords. Or will this tool ever only be useful for deleting nameRecords with platID equal to 1 ?

Also, the tool name does not make it obvious that a side effect of its --autofix will be this deletion of nameRecords. I'd like to have a better understanding of the usage scenario for this tool.
