### ISSUE TITLE
fix-familymetadata.py output is too wide for the text terminal

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#629]
This script outputs a table. But it is unreadable on an 80-column text terminal. It should perhaps default to the CSV output format (which is already supported but currently not turned on by default)

Alternatively, we could figure out some smarterr way of printing out the table to the terminal, but I think it is not really worth the effort at all.

**Comment by davelab6** [comment]
Just make your terminal font smaller and the window larger.
