### ISSUE TITLE
FamilyAndStyleNameFixer seems to be broken

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#632]
getOrCreateNameRecord method imediately returns spiting out an error message and leaving unreachable code in the rest of the function implementation block.

```python
    def getOrCreateNameRecord(self, nameId, val):
        logger.error('NAMEID {}: "{}"'.format(nameId, val))
        return
```
https://github.com/googlefonts/fontbakery/blob/master/bakery_cli/fixers.py#L723-L751

And also outputs some more error messages here:
https://github.com/googlefonts/fontbakery/blob/master/bakery_cli/fixers.py#L766-L772

@davelab6  Please clarify what's the intended behaviour for this fixer class and I'll append the description as documentation in the class declaration and I'll also later work on implementing it properly.

**Comment by davelab6** [comment]
I believe this is meant to fix the family and style names to their canonical form... eg filenames and PS names as follows

FontFamily-Thin.ttf for a 100 weight font
FontFamily-ThinItalic.ttf for a 100 weight font
FontFamily-ExtraLight.ttf for a 200 weight font
FontFamily-ExtraLightItalic.ttf for a 200 weight font
FontFamily-Light.ttf for a 300 weight font
FontFamily-LightItalic.ttf for a 300 weight font
FontFamily-Regular.ttf for a 400 weight font
FontFamily-Italic.ttf for a 400 weight font
FontFamily-Medium.ttf for a 500 weight font
FontFamily-MediumItalic.ttf for a 500 weight font
FontFamily-SemiBold.ttf for a 600 weight font
FontFamily-SemiBoldItalic.ttf for a 600 weight font
FontFamily-Bold.ttf for a 700 weight font
FontFamily-BoldItalic.ttf for a 700 weight font
FontFamily-ExtraBold.ttf for a 800 weight font
FontFamily-ExtraBoldItalic.ttf for a 800 weight font
FontFamily-Black.ttf for a 900 weight font
FontFamily-BlackItalic.ttf for a 900 weight font

and following https://docs.google.com/spreadsheets/d/1ckHigO7kRxbm9ZGVQwJ6QJG_HjV_l_IRWJ_xeWnTSBg/edit#gid=0
