### ISSUE TITLE
Various issues in metadata-vs-api script

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#637]
See also:
https://github.com/googlefonts/fontbakery/pull/634#commitcomment-15603813

**Comment by davelab6** [comment]
https://github.com/googlefonts/gf-docs/blob/master/METADATA.md explains some of this.

This field was set to "External" if the family is to appear in the www.google.com/fonts directory; there are families that we want to have in the git repo that are not visible in the directory but are served by the API. 

As an example (a real one but with names changed) the family 'Acme Foo' by Paul Impaler was subject to a trademark dispute from the font foundry "Acme Design Inc" who have a US registered trademark on their foundry name, and reasonably claimed that any font called "Acme Something" is confusing to the public as they assume it is from them. So we renamed it 'Foo' and removed 'Acme Foo' from the directory, but keep serving it to existing websites, by setting it to "Internal."

The field was initially always set to "Sandbox" which meant that it would not be pushed to the production API; the field was then set by the engineering team when it was pushed, and thus got out of sync.

**Comment by felipesanches** [comment]
Thanks for the clarification!

The fontbakery metadava-vs-api script should simply inform which visibility category the font is inferred to be? Or should it also error is the inferred visibility is not "External" ? Or possibly even some other desired  behaviour?

**Comment by felipesanches** [comment]
Code merged. Please reopen if more changes are required.

**Comment by davelab6** [comment]
Its not quite right :) 

```
...
Downloading 'Amiri' from http://fonts.gstatic.com/s/amiri/v7/ATARrPmSew75SlpOw2YABQ.ttf
OK: ATARrPmSew75SlpOw2YABQ.ttf from Amiri copied
Downloading 'Amiri' from http://fonts.gstatic.com/s/amiri/v7/WQsR_moz-FNqVwGYgptqiA.ttf
OK: WQsR_moz-FNqVwGYgptqiA.ttf from Amiri copied
Downloading 'Amiri' from http://fonts.gstatic.com/s/amiri/v7/uF8aNEyD0bxMeTBg9bFDSPesZW2xOQ-xsNqO47m55DA.ttf
OK: uF8aNEyD0bxMeTBg9bFDSPesZW2xOQ-xsNqO47m55DA.ttf from Amiri copied
Downloading 'Amiri' from http://fonts.gstatic.com/s/amiri/v7/3t1yTQlLUXBw8htrqlXBrw.ttf
OK: 3t1yTQlLUXBw8htrqlXBrw.ttf from Amiri copied
OK: Amiri has arabic in Github and API
OK: Amiri has latin in Github and API
ER: Amiri has menu in Github but not in API
ER: Amiri-regular in API but not in Github
ER: Amiri-700 in API but not in Github
OK: Amiri-BoldSlanted.ttf in Github and in API
OK: Amiri-BoldSlanted.ttf in production
ER: Amiri-italic in API but not in Github
ER: Amiri-Regular.ttf in Github but not in API
ER: Amiri-Slanted.ttf in Github but not in API
ER: Amiri-Bold.ttf in Github but not in API
...
```

- [ ] The styles should be declared to avoid confusing semi-repeated info. Eg these lines:

```
Downloading 'Amiri' from http://fonts.gstatic.com/s/amiri/v7/ATARrPmSew75SlpOw2YABQ.ttf
OK: ATARrPmSew75SlpOw2YABQ.ttf from Amiri copied
```

should be like this:

```
Downloading 'Amiri-Regular.ttf' from http://fonts.gstatic.com/s/amiri/v7/ATARrPmSew75SlpOw2YABQ.ttf`
OK: Copied ATARrPmSew75SlpOw2YABQ.ttf to Amiri-Regular.ttf
```

- [ ] The menu check isn't working. eg 

```
ER: Amiri has menu in Github but not in API
```

Well, you can see it is in the API:

http://fonts.googleapis.com/css?family=Amiri&subset=menu says

```
@font-face {
  font-family: 'Amiri::MENU';
  font-style: normal;
  font-weight: 400;
  src: local('Amiri'), local('Amiri-Regular'), url(http://fonts.gstatic.com/s/amiri/v7/nKCr-uq4_KW74EqUkJzDHKCWcynf_cDxXwCLxiixG1c.woff2) format('woff2');
}
```

Since we no longer generate these menu subsets offline and store the resulting Family-Style.menu files in git, then the existing check should simply be removed. 

- [ ] However, instead, we should check that each style downloaded and in git has all the characters in the METADATA.pb "family" field. 

- [ ] When reordering the output to group by style, there is clearly a problem matching API styles to filenames:

```
OK: Amiri-BoldSlanted.ttf in Github and in API
OK: Amiri-BoldSlanted.ttf in production

ER: Amiri-regular in API but not in Github
ER: Amiri-Regular.ttf in Github but not in API

ER: Amiri-Slanted.ttf in Github but not in API
ER: Amiri-italic in API but not in Github

ER: Amiri-Bold.ttf in Github but not in API
ER: Amiri-700 in API but not in Github
```

**Comment by felipesanches** [comment]
Do you like it this way?

```
Downloading 'Amiri' from http://fonts.gstatic.com/s/amiri/v7/ATARrPmSew75SlpOw2YABQ.ttf
OK: Copied ATARrPmSew75SlpOw2YABQ.ttf [Amiri regular] to /tmp/fontbakery-compare-github-api/fonts.gstatic.com/s/amiri/v7/ATARrPmSew75SlpOw2YABQ.ttf
```

```
Downloading 'Amiri' from http://fonts.gstatic.com/s/amiri/v7/WQsR_moz-FNqVwGYgptqiA.ttf
OK: Copied WQsR_moz-FNqVwGYgptqiA.ttf [Amiri 700] to /tmp/fontbakery-compare-github-api/fonts.gstatic.com/s/amiri/v7/WQsR_moz-FNqVwGYgptqiA.ttf
```

**Comment by felipesanches** [comment]
alternatively I could make it output this:

```
Downloading 'Amiri regular' from http://fonts.gstatic.com/s/amiri/v7/ATARrPmSew75SlpOw2YABQ.ttf
OK: [Amiri regular] Saved to /tmp/fontbakery-compare-github-api/fonts.gstatic.com/s/amiri/v7/ATARrPmSew75SlpOw2YABQ.ttf
```

```
Downloading 'Amiri 700' from http://fonts.gstatic.com/s/amiri/v7/WQsR_moz-FNqVwGYgptqiA.ttf
OK: [Amiri 700] Saved to /tmp/fontbakery-compare-github-api/fonts.gstatic.com/s/amiri/v7/WQsR_moz-FNqVwGYgptqiA.ttf
```

**Comment by davelab6** [comment]
2nd seems better, as it reduces duplication.

It would be nice to create symlinks with the filenames found in
METADATA.pb, eg

$ ln -s /tmp/fontbakery-compare-github-api/{
fonts.gstatic.com/s/amiri/v7/WQsR_moz-FNqVwGYgptqiA.ttf,Amiri-Bold.ttf};

**Comment by felipesanches** [comment]
yeah! That sounds good!

**Comment by felipesanches** [comment]
This is the relevant portion of JSON data about the Amiri family returned by a query to
https://www.googleapis.com/webfonts/v1/webfonts?key=SOME_API_KEY:

```json
  {
   "kind": "webfonts#webfont",
   "family": "Amiri",
   "category": "serif",
   "variants": [
    "regular",
    "italic",
    "700",
    "700italic"
   ],
   "subsets": [
    "arabic",
    "latin"
   ],
   "version": "v7",
   "lastModified": "2015-04-07",
   "files": {
    "regular": "http://fonts.gstatic.com/s/amiri/v7/ATARrPmSew75SlpOw2YABQ.ttf",
    "italic": "http://fonts.gstatic.com/s/amiri/v7/3t1yTQlLUXBw8htrqlXBrw.ttf",
    "700": "http://fonts.gstatic.com/s/amiri/v7/WQsR_moz-FNqVwGYgptqiA.ttf",
    "700italic": "http://fonts.gstatic.com/s/amiri/v7/uF8aNEyD0bxMeTBg9bFDSPesZW2xOQ-xsNqO47m55DA.ttf"
   }
  },
```

It's subsets list contains only "arabic" and "latin". Shoulding the API list "menu" here, as well? This JSON respond is at least misleading...

**Comment by davelab6** [comment]
The menu subsets are undocumented, so this is working as intended.

**Comment by felipesanches** [comment]
I don't understand the meaning of this sentence:
"we should check that each style downloaded and in git has all the characters in the METADATA.pb 'family' field."

Can you clarify? I see no 'family' field in google/fonts/ofl/amiri/METADATA.pb

**Comment by davelab6** [comment]
Sorry, the 'name' field. Well, each TTF file in git and from the API should
have the ascii character in the name; this is probably a waste of time
though. Let's drop the whole menu subset test for now.

**Comment by felipesanches** [comment]
ok :-)

I just merged all of the commits above. Closing this one then.

**Comment by davelab6** [comment]
>> When reordering the output to group by style, there is clearly a problem matching API styles to filenames:

I still see this:

```
ER: Arimo-700 in API but not in Github
ER: Arimo-Bold.ttf in Github but not in API
```

**Comment by davelab6** [comment]
This is also strange duplication:
```
OK: Arimo-BoldItalic.ttf in Github and in API
OK: Arimo-BoldItalic.ttf in production
```

What is the difference between "in API" and "in production"? I think there isn't any

**Comment by felipesanches** [comment]
The "in production" message is printed when the md5 checksum of the github file is identical to the md5 of the corresponding file fetched from Google. We can change the message to say "OK: {} in Github and in API have identical files". Or we could simply remove this "OK" message, given that an 'ER' message will be printed in case there's a checksum mismatch.

**Comment by felipesanches** [comment]
Also, perhaps we should say "local repo" instead of "GitHub", throughout this script, don't you agree?

**Comment by davelab6** [comment]
> Also, perhaps we should say "local repo" instead of "GitHub", throughout this script, don't you agree?

`s/github/git`

> The "in production" message is printed when the md5 checksum of the github file is identical to the md5 of the corresponding file fetched from Google. We can change the message to say "OK: {} in Github and in API have identical files". Or we could simply remove this "OK" message, given that an 'ER' message will be printed in case there's a checksum mismatch.

`OK: {} is identical in git and API` is good

**Comment by davelab6** [comment]
> It would be nice to create symlinks with the filenames found in METADATA.pb, eg
>     $ ln -s /tmp/fontbakery-compare-github-api/{fonts.gstatic.com/s/amiri/v7/WQsR_moz-FNqVwGYgptqiA.ttf,Amiri-Bold.ttf};

Please also do this :)

**Comment by davelab6** [comment]
Ah, superceded by https://github.com/felipesanches/fontbakery/commit/d609c0b21eb82f9086d990da22ae2f0e4e30b40b ?

**Comment by davelab6** [comment]
- [ ] The filename definition 

    filename = '{}-{}.ttf'.format(family, variant)

from https://github.com/googlefonts/fontbakery/blob/master/tools/fontbakery-metadata-vs-api.py#L76 isn't quite right; it means the log is a but confusing and the symlink filenames are also not right, eg

```
/tmp/fontbakery-compare-github-api/fonts.gstatic.com/s/cantarell/v6 $ ls -1
Cantarell-700.ttf
Cantarell-700italic.ttf
Cantarell-italic.ttf
Cantarell-regular.ttf
DTCLtOSqP-7dgM-V_xKUjqCWcynf_cDxXwCLxiixG1c.ttf
Yir4ZDsCn4g1kWopdg-ehC3USBnSvpkopQaUR-2r7iU.ttf
p5ydP_uWQ5lsFzcP_XVMEw.ttf
weehrwMeZBXb0QyrWnRwFXe1Pd76Vl7zRpE7NLJQ7XU.ttf
$
```

The METADATA.pb file tells us the filenames:

```
$ grep ttf ~/fonts/ofl/cantarell/METADATA.pb 
  filename: "Cantarell-Regular.ttf"
  filename: "Cantarell-Oblique.ttf"
  filename: "Cantarell-Bold.ttf"
  filename: "Cantarell-BoldOblique.ttf"
```

so we should use them :) 

Then this

```
Downloading http://fonts.gstatic.com/s/averiaseriflibre/v5/yvITAdr5D1nlsdFswJAb8SmC4gFJ2PHmfdVKEd_5S9M.ttf as Averia Serif Libre-300.ttf
Downloading http://fonts.gstatic.com/s/averiaseriflibre/v5/YOLFXyye4sZt6AZk1QybCG2okl0bU63CauowU4iApig.ttf as Averia Serif Libre-300italic.ttf
Downloading http://fonts.gstatic.com/s/averiaseriflibre/v5/yvITAdr5D1nlsdFswJAb8Q50KV5TaOVolur4zV2iZsg.ttf as Averia Serif Libre-700.ttf
Downloading http://fonts.gstatic.com/s/averiaseriflibre/v5/YOLFXyye4sZt6AZk1QybCNxohRXP4tNDqG3X4Hqn21k.ttf as Averia Serif Libre-700italic.ttf
Downloading http://fonts.gstatic.com/s/averiaseriflibre/v5/fdtF30xa_Erw0zAzOoG4BZqY66i8AUyI16fGqw0iAew.ttf as Averia Serif Libre-regular.ttf
Downloading http://fonts.gstatic.com/s/averiaseriflibre/v5/o9qhvK9iT5iDWfyhQUe-6Ru_b0bTq5iipbJ9hhgHJ6U.ttf as Averia Serif Libre-italic.ttf
OK: Averia Serif Libre subset latin in sync
OK: AveriaSerifLibre-Light.ttf in sync
OK: AveriaSerifLibre-LightItalic.ttf in sync
OK: AveriaSerifLibre-Bold.ttf in sync
OK: AveriaSerifLibre-BoldItalic.ttf in sync
OK: AveriaSerifLibre-Italic.ttf in sync
OK: AveriaSerifLibre-Regular.ttf in sync
```

becomes

```
Downloading http://fonts.gstatic.com/s/averiaseriflibre/v5/yvITAdr5D1nlsdFswJAb8SmC4gFJ2PHmfdVKEd_5S9M.ttf as AveriaSerifLibre-Light.ttf 
Downloading http://fonts.gstatic.com/s/averiaseriflibre/v5/YOLFXyye4sZt6AZk1QybCG2okl0bU63CauowU4iApig.ttf as AveriaSerifLibre-LightItalic.ttf
Downloading http://fonts.gstatic.com/s/averiaseriflibre/v5/yvITAdr5D1nlsdFswJAb8Q50KV5TaOVolur4zV2iZsg.ttf as AveriaSerifLibre-Bold.ttf
Downloading http://fonts.gstatic.com/s/averiaseriflibre/v5/YOLFXyye4sZt6AZk1QybCNxohRXP4tNDqG3X4Hqn21k.ttf as AveriaSerifLibre-BoldItalic.ttf
Downloading http://fonts.gstatic.com/s/averiaseriflibre/v5/fdtF30xa_Erw0zAzOoG4BZqY66i8AUyI16fGqw0iAew.ttf as AveriaSerifLibre-Regular.ttf
Downloading http://fonts.gstatic.com/s/averiaseriflibre/v5/o9qhvK9iT5iDWfyhQUe-6Ru_b0bTq5iipbJ9hhgHJ6U.ttf as AveriaSerifLibre-Italic.ttf
OK: Averia Serif Libre subset latin in sync
OK: AveriaSerifLibre-Light.ttf in sync
OK: AveriaSerifLibre-LightItalic.ttf in sync
OK: AveriaSerifLibre-Bold.ttf in sync
OK: AveriaSerifLibre-BoldItalic.ttf in sync
OK: AveriaSerifLibre-Italic.ttf in sync
OK: AveriaSerifLibre-Regular.ttf in sync
```

- [ ] Download checking/resuming. 

Currently we have an arg to avoid re-downloading the fonts, `--ignore-copy-existing-ttf` but its bad because if the file exists from 2 weeks ago, and it was updated since then, it won't be correct.

We download the files with

    fp.write(urllib.urlopen(fonturl).read())

at https://github.com/googlefonts/fontbakery/blob/master/tools/fontbakery-metadata-vs-api.py#L81

This simply always downloads the files. If the files are already downloaded, or partially (wifi dropped, etc) then it will not skip or resume. 

We could use wget or curl for this, or are a couple of pure python examples that handle it,

* http://code.activestate.com/recipes/83208-resuming-download-of-a-file/
* https://pypi.python.org/pypi/fileDownloader.py/0.2.1 is helpful 

Also, while the above implies removing this code, I'm curoius - why is there this `if / continue` structure at https://github.com/googlefonts/fontbakery/blob/master/tools/fontbakery-metadata-vs-api.py#L72-L75 - it seems odd to me. Why not put the 'with' part under the if? :) Sorry for a noob question

**Comment by davelab6** [comment]
Ah, looks like

    repoFileName = metadata.fonts[filenameWeightStyleIndex].filename

from https://github.com/googlefonts/fontbakery/blob/master/tools/fontbakery-metadata-vs-api.py#L122

will fix the first thing.

**Comment by davelab6** [comment]
- [ ] Similar to subsets, we should also compare the category field. Needs a bit of string manipulation:

```
$ grep category ~/fonts/*/*/MET* | cut -d: -f3 | cut -d\" -f2 | sort | uniq
DISPLAY
HANDWRITING
MONOSPACE
SANS_SERIF
SERIF
$ curl -s "https://www.googleapis.com/webfonts/v1/webfonts?key=KEY" | grep category | cut -d\" -f4 | sort | uniq
display
handwriting
monospace
sans-serif
serif
```

**Comment by davelab6** [comment]
- [ ] Error `ER: Available in repository but not in API` lacks context

**Comment by felipesanches** [comment]
This was just reopened by @davelab6 due to the pending task described on https://github.com/googlefonts/fontbakery/issues/637#issuecomment-175243241

That's right, dave?

**Comment by davelab6** [comment]
Yes
