### ISSUE TITLE
[metadata-vs-api] resuming of font file downloads

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#659]
- [ ] partially downloaded files should resume instead of starting from scratch.
- [ ] too old files should be re-downloaded even if cache is used (i.e. invalidate download cache after a certain amount of time (how much time?))

**Comment by davelab6** [comment]
>  invalidate download cache after a certain amount of time (how much time?))

Invalidate it if they filesize is different comparing the file on disk in the cache and the HTTP `Content-Length` value?

**Comment by felipesanches** [comment]
So, only invalidate based on length mismatch, but not based on time?

This would be a cache management policy based on the assumption that typically file length changes upon file edits. Which may not always hold true.

**Comment by davelab6** [comment]
No no no. This is all wrong :) We are wasting time with this. I think it would be better to just use `wget` to handle this, then we'd get all the complexity sorted just by passing it the `--continue` arg

**Comment by felipesanches** [comment]
alright! Makes sense.

**Comment by felipesanches** [comment]
migrated to https://github.com/googlefonts/tools/issues/21
