### ISSUE TITLE
New fontbakery-fix-glyphnames.py script

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#664]
Using the [renaming-glyphs.py](https://github.com/behdad/fonttools/pull/511) snippet in part, we should be able to check and fix glyph naming to make them correct.

**Comment by davelab6** [comment]
References: 

* https://github.com/googlei18n/glyphs2ufo/issues/12
* https://github.com/adobe-type-tools/agl-aglfn

**Comment by twardoch** [comment]
@davelab6: @schriftgestalt has just published a subset of GlyphData.xml (just the basic stuff i.e. Unicode-to-Glyphs-glyphname mapping and some categorization, without the additional metadata) under the MIT license: 
https://github.com/schriftgestalt/GlyphsInfo

This can be used as an auxiliary source for converting the internal Glyphs glyphnames into production glyphnames.

**Comment by davelab6** [comment]
Yes, I (and perhaps you) had requested this a while ago and I am happy that @schriftgestalt has done it :)

**Comment by davelab6** [comment]
Apropos the discussion this morning about finding references/sources/citations for out tests, here's a good source for the glyph naming stuff: https://github.com/silnrsi/FDBP/commit/332db981cf81f0d710865149fc8196a82fd22756

**Comment by felipesanches** [comment]
migrated to https://github.com/googlefonts/tools/issues/19
