### ISSUE TITLE
New fontbakery-fix-ttfautohint.py script

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#665]
A lot of fonts in the gf collection have old versions of ttfautohint applied, and it would be great to have a script that initially uses the methods in `fontbakery-fix-version.py` that...
- [x] finds which version was used, grepping the name table or reading the ttfa table (which are created if the `-I` or `-t` args respectively were passed to ttfautohint, to record its args in the ttf file) (there is a pypi package https://pypi.python.org/pypi/font-ttfa for reading the ttfa table, although per https://github.com/source-foundry/font-ttfa/issues/1 it might be better to inline the code... :) 
- [ ] has an `--autofix` arg/method that runs the latest version of ttfautohint using the options from the name table. 

I encountered this while updating Raleway, https://github.com/impallari/Raleway/issues/2

**Comment by chrissimpkins** [comment]
Feel free to grab and use anything that proves useful from [font-ttfa](https://pypi.python.org/pypi/font-ttfa) or let me know if you'd like me to submit a PR here rather than in https://github.com/twardoch/fonttools-utils as you suggested in the issue report.

**Comment by davelab6** [comment]
Fontbakery is a bit bloated and this update tool is a bit different to yours, so adams' repo is better, I think :)

**Comment by chrissimpkins** [comment]
:+1:

**Comment by davelab6** [comment]
The 0.1.0 rewrite should do this

**Comment by davelab6** [comment]
@felipesanches what is the status of this?

**Comment by davelab6** [comment]
994ea77 introduces a script that will print the table information if present. The next action is to implement the autofix method as described above. This is a 'misc' category task with relatively low importance.

**Comment by simoncozens** [comment]
These days we don't fix fonts in fontbakery, but we already have a check for making sure that ttfautohint is up to date. Feel free to reopen if I've misunderstood.
