### ISSUE TITLE
WebPanel for CoinyTest fails to load properly

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#676]
For testing the webapp I have setup a repository of the Coiny font project:

https://github.com/felipesanches/CoinyTests

And I configured it to run fontbakery build and report as a travis job:

https://travis-ci.org/felipesanches/CoinyTests

The result of the travis job is automatically commited to the gh-pages branch:

https://github.com/felipesanches/CoinyTests/tree/gh-pages

With a README.md link to the webapp with the font build and test results report panel:

http://googlefonts.github.io/fontbakery/#/felipesanches/CoinyTests/

The panel page shows up for a while, but then prints a 404 file not found error and then quickly redirects the browser to a 404 error page. I need to further investigate this and get the web panel to work properly again.

**Comment by felipesanches** [comment]
I just diagnosed that the issue is related to the fact that the webapp does not yet know anything about the protobuffers format used for METADATA.pb (it still tries to read a json file in there...)

**Comment by felipesanches** [comment]
I may make the webapp happy by providing a METADATA.json generated from the METADATA.pb we have. (but it feels like cheating :-P)

Or I could parse METADATA.pb in javascript. There may already be some solution for that I guess.

**Comment by davelab6** [comment]
What does it need the METADATA values for?

**Comment by felipesanches** [comment]
hmmm... All test results summary data is output by fontbakery python code and fed to the webapp using json. I think I'll stick to generating json here as well...

**Comment by felipesanches** [comment]
@davelab6  gotcha! Let me check that as well!

**Comment by davelab6** [comment]
Yes, the test summary data is json and that is still true.

But the METADATA.json file was not (AFAIK) actually parsed, it was just
pulled as a plain text file into a js txt editor

**Comment by felipesanches** [comment]
hmmm... not really. The metadata JSON is actually parsed and its field values are accessed by the webapp in some places:

* an example here: https://github.com/googlefonts/fontbakery/blob/gh-pages/static/js/controllers/mainController.js#L92-L101 (here is reads some metadata fields and then selects a main font, ideally a "regular")

* and another example here: https://github.com/googlefonts/fontbakery/blob/gh-pages/static/js/directives.js#L62 (font_regular is an item read from the "fonts" dict in METADATA.json)

**Comment by davelab6** [comment]
Okay cool. proto bufs has loads of JS libraries so reading the file instead
of JSON should be straightforawrd

**Comment by felipesanches** [comment]
This commit adds the FamilyProto message parsing in javascript, so the webapp does not require METADATA.json anymore: https://github.com/googlefonts/fontbakery/commit/270317c5321a6f0cbf0c80015d85e9ead5883f31
