### ISSUE TITLE
Ensure all code passes Google-style pylint

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#679]
Per https://stackoverflow.com/questions/29597618/is-there-a-tool-to-lint-python-based-on-the-google-style-guide/33487398 we can have travis check we are following the Google-style python code style guide.

**Comment by felipesanches** [comment]
This is redundant with https://github.com/googlefonts/fontbakery/issues/838 and https://github.com/googlefonts/fontbakery/issues/801
