### ISSUE TITLE
Font Classification

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#684]
https://github.com/googlefonts/fontbakery/blob/master/tools/compute_font_weight_and_width.py is meant to generate data to aid in updating https://github.com/google/fonts/blob/master/tools/font-metadata.csv
#### Round 1 tasks: Making a read-only table

~~This probably uses the files in the github repo, but it could also use the [gfonts developer api](https://developers.google.com/fonts/docs/developer_api) in a similar way to the [fontbakery-metadata-vs-api.py](https://github.com/googlefonts/fontbakery/blob/master/tools/fontbakery-metadata-vs-api.py) tool does, so that it operates on the files in the API.~~ Since we can preview the font with an image, no need to link to the font with `@font-face` for now.
- [x] For angle, the automatic value can simply be made by using the `italicAngle` property of the font, if present, re-using the code in `fontbakery-fix-italicangle.py` (a84fd227ba2b4c1adacafc37454c0de9eb7c8467)
- [x] Extend the preview page made with the script to allow reviewing everything in a huge table with cols as follows:

| filename | weight | width | angle | usage | preview |
| --- | --- | --- | --- | --- | --- |
| fonts/apache/arimo/Arimo-BoldItalic.ttf | 0.278132834804 | 902 | -12.0 | head | IMG |

There is then one row for each font file (08c2c5aa4c844e5811f11280efd914616085292f)
- [x] The table should be sortable, eg using the existing tableSort.js from fontbakery (fbdcf7adc0b71bfa95f5724f10e1eaea320eb06a)
- [x] Extend the script with an `--existing` arg that takes as input a `font-metadata.csv` file, and shows these values in the table, with `filename` value = `font-metadata.csv` (93bc121c4ff104e1f5b3d167dc1db8f803d76474)

| filename | gfn | weight | width | angle | usage | preview |
| --- | --- | --- | --- | --- | --- | --- |
| fonts/apache/arimo/Arimo-BoldItalic.ttf | Arimo:italic:700 | 0.278132834804 | 902 | -12.0 | header | IMG |
| font-metadata.csv | Arimo:italic:700 | 7 | 4 | 7 | header | IMG |
- [x] add a col for `gfn` that matches the 1st col in `font-metadata.csv` (93bc121c4ff104e1f5b3d167dc1db8f803d76474)
- [x] autofill the `gfn` col for new fonts with data that matches the 1st col in `font-metadata.csv`. This will require checking the directory of the file for a METADATA.pb, and then checking that for the fonts keys that match the filename.ext, to know the weight and if its roman or italic. 
#### Round 2 tasks: Making the table correctable

(All these should be postponed until Round 1 is complete)
- [x] Extend the script with an `--output` arg that takes as input a filepath, and 
- [x] table is inside a form and all values are all editable
- [x] form has a submit button before the table (at the top) that sends all the values back to the python webserver, which then writes a new `font-metadata.csv` to the `--output` path
- [x] bring back the font preview image col
- [x] reconfigure editableGrid to use anglo decimal period not latin comma
- [x] Make `-o` more resilient, as `compute_font_metrics.py -o out.csv` crashes
#### Round 3 tasks: Accurate Angle Correction
- [x] Italic Angle visualisation

There will be script fonts and similar where the font metadata value isn't set, or is set incorrectly. To make hand corrections faster, show key glyphs with flat sides, `H M N U`, on top of a protractor graphic. If we were fancy we could do some interactive SVG but the simple thing is to just have 10 images with red lines at an angle from 0' (vertical bars) to 30' (like `////` or [sort of like this](http://4.bp.blogspot.com/-YR_Eh-eA26c/US7JFl3dDtI/AAAAAAAADJM/zkTfPUz23D0/s1600/sine.gif)) and setting them as the background image based on the value of the cell, using jQuery. 

The images can probably be created with pillow... the first example on https://pillow.readthedocs.org/en/3.1.x/reference/ImageDraw.html is already close :) 

``` py
from PIL import Image, ImageDraw
im = Image.open("lena.pgm")

draw = ImageDraw.Draw(im)
draw.line((0, 0) + im.size, fill=128)
draw.line((0, im.size[1], im.size[0], 0), fill=128)
del draw

# write to stdout
im.save(sys.stdout, "PNG")
```
#### Round 4 tasks: Nicer JS
- [x] ~~For rows with existing data, can we put the image from the font file that has the same gfn on their row~~ changed to deduplication
- [x] When reading existing CSV values, use them in a way that is deduplicative: so that GFN becomes the 'UID' key for the data, and the autodetected row values are in cols next to cols for the existing values. 
- [x] Add an additional table at the top of the page that has the same head rows, and a single content row with checkboxes that toggle the cols of the main table, so that we can focus
- [ ] Add filter, perhaps as a new 2nd row, so that each col to only show rows where the cell contents matches what is in the filter. So we can see e.g., only rows with `weight_int=8` and `width_int=5`
- [x] Add JS to move down a row in same col when exiting a value with ~~return~~ TAB key (as, really, moving DOWN the row is what matters most.)
- [ ] Add JS to move up a row in same col when exiting a value with shift-TAB key
- [ ] Add JS from https://jsbin.com/quzoro/edit?html,js,output to allow in/decrementing values with up/down arrow keys (or `x` and `z` or whatever)
- [ ] Improve the `usage` col interaction to be really fast (probably using the autocomplete functionality of editableGrid)

Nice to haves, don't bother if it takes more than 10 mins:
- [ ] ~~Add JS from https://jsbin.com/quzoro/edit?html,js,output to allow  in/decrementing values on hover with scrollwheel (there is some conflict with the editableGrid code :(~~ forget it :)
- [ ] Add flask methods so it it served on http://127.0.0.1:5000 directly, then remove the print line telling the current URL
#### Round 5 tasks: Nice stuff (postponed)

Some ideas:

Better Auto Angle Detection. OpenCV should make this easy:
- [ ] http://felix.abecassis.me/2011/09/opencv-detect-skew-angle/

Hiding Cols
- [x] Using jQuery, add a new table to the top of the page with the same cols as the main table, but just 1 row, with a 'show/hide' checkbox that when clicked toggles the visibility (`.css("display": "none")`) of the corresponding col in the main table.

Automatic initialisation of `usage_type` values
- [ ] Perhaps similar to weight: render the family's Regular `400r` font but at a fairly small size, then blur it (with pillow or imagemagick) and the average grey value will be white or light grey for very thing display fonts, and black or dark grey for heavy display fonts. With 'training data' already available in the file, you can make a histogram of all the font files in the collection and seeing where the grey values of the fonts already classified as 'text' or 'display' could work.
- [ ] Use https://github.com/behdad/fonttools/blob/master/Snippets/symfont.py to detect slant 

Improve the way new values match existing ones from in `font-metadata.csv`:
- [x] Normalise our float values to int values from 1 to 10, so they compare to original data. 
- [ ] With 75e7169b911c2b444ec375cf5a5170020cbd1e65 67f2cc0573185ab3486a39c0c41d6d9d261a793f 864f111cdb5a2ea0ba1f1ee5a1a4f2d2da18fdd9 then the values are normalised within their own set, but making them match the original data needs more work. However, this may not be needed, as our data could be better than the original.

**Comment by davelab6** [comment]
For angle, the automatic value can simply be made by using the `italicAngle` property of the font, if present. Then for script fonts or whatever where it isn't set or is set incorrectly, something to hand correct it can involve a few key glyphs like `H M N U`  each with an interactive SVG that works like a protractor to set the angle; then this is arranged in a huge table with each row having one font file, that can be operating with arrow keys, up and down to move between fonts, and left and right to de/increment the angle value. 

There is also a 4th key, "usage type". I think this could be automatically calculated similarly to weight but at a very small size; eg if you render the family's Regular `400r` font with hb-view (similar to https://github.com/googlei18n/nototools/blob/master/nototools/shape_diff.py#L115-L118) at a fairly small size then blur it, the average grey value will be white or light grey for very thing display fonts, and black or dark grey for heavy display fonts. With 'training data' already available in the file, making a histogram of all the font files in the collection and seeing where the grey values of the fonts already classified as 'text' or 'display' could work. And again for the review, a table with each row being a font, up/down to move through the table, and left/right to toggle text/headings.

**Comment by davelab6** [comment]
- [ ] fix this

```
python2 src/github.com/googlefonts/fontbakery/tools/compute_font_weight_and_width.py --metric=width --folder="fonts/ofl/corben/Corben-*.ttf" --debug=True

Traceback (most recent call last):
  File "src/github.com/googlefonts/fontbakery/tools/compute_font_weight_and_width.py", line 251, in <module>
    main()
  File "src/github.com/googlefonts/fontbakery/tools/compute_font_weight_and_width.py", line 124, in main
    properties.append(get_width(fontfile))
  File "src/github.com/googlefonts/fontbakery/tools/compute_font_weight_and_width.py", line 201, in get_width
    text_width, text_height = font.getsize(TEXT)
  File "/usr/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 141, in getsize
    size, offset = self.font.getsize(text)
IOError: invalid reference
```

**Comment by felipesanches** [comment]
it does that when reaching this file:

```
fontfile: '../../github_google/fonts/ofl/corben/Corben-Bold.ttf'
```

I'm investigating the issue.

**Comment by felipesanches** [comment]
I placed "Corben" on the BLACKLIST and now we have a new issue:

```
fontfile: '../../github_google/fonts/ofl/suwannaphum/Suwannaphum.ttf'
Traceback (most recent call last):
  File "tools/compute_font_metrics.py", line 268, in <module>
    main()
  File "tools/compute_font_metrics.py", line 126, in main
    properties.append(get_width(fontfile))
  File "tools/compute_font_metrics.py", line 222, in get_width
    return {'value': text_width, 'fontfile': fontfile, 'base64img': get_base64_image(img)}
  File "tools/compute_font_metrics.py", line 255, in get_base64_image
    img.save(output, "PNG")
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1468, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python2.7/dist-packages/PIL/PngImagePlugin.py", line 624, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0,0)+im.size, 0, rawmode)])
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFile.py", line 462, in _save
    e.setimage(im.im, b)
SystemError: tile cannot extend outside image
```

**Comment by davelab6** [comment]
Blacklist all the failures and address later

**Comment by felipesanches** [comment]
All black-listed. Does not crash anymore.

**Comment by davelab6** [comment]
I'm hacking away at this in https://github.com/googlefonts/fontbakery/compare/compare?expand=1

**Comment by felipesanches** [comment]
yeah. It looks good. Although now we could perhaps set the "base64img" field of the dictionary in a dedicated method to avoid redundancy in the code.

**Comment by davelab6** [comment]
Potentially we can use 2 different methods/images for each so I'd like to
keep it like this for now

**Comment by felipesanches** [comment]
ok, cool

**Comment by davelab6** [comment]
> Add JS from https://jsbin.com/quzoro/edit?html,js,output to allow in/decrementing values on hover with scrollwheel (there is some conflict with the editableGrid code :(

I have added the basic code, I can't see why some code runs and others does not :(

**Comment by davelab6** [comment]
@felipesanches issue is updated

**Comment by davelab6** [comment]
Analysing everything like this

    ~$ python2 src/github.com/googlefonts/fontbakery/tools/compute_font_metrics.py --files="fonts/*/*/*.ttf" --existing=fonts/tools/font-metadata.csv -o font-metadata-new.csv

I see Inknut ExtraBold has very tall vertical metrics, which mean its image has more weight, so its autoweight is misclassified

<img width="1562" alt="screen shot 2016-02-25 at 02 17 54" src="https://cloud.githubusercontent.com/assets/261579/13312602/036d6a56-db66-11e5-9d66-e707fc7042d7.png">

I see Seaweed Script's italic angle is not set in the font, so its angle need to be corrected:

<img width="1552" alt="screen shot 2016-02-25 at 02 19 14" src="https://cloud.githubusercontent.com/assets/261579/13312634/3d03427c-db66-11e5-837a-d30d646f785e.png">

So on to round 4 asap! We are close! :)

**Comment by davelab6** [comment]
Updated the issue

**Comment by davelab6** [comment]
Running

    ~$ python2 src/github.com/googlefonts/fontbakery/tools/compute_font_metrics.py --files="fonts/*/*/*.ttf" --existing=fonts/tools/font-metadata.csv -o font-metadata-new.csv

Then sorting the table by `ANGLE_INT`, I see

<img width="1178" alt="screen shot 2016-02-25 at 16 53 11" src="https://cloud.githubusercontent.com/assets/261579/13335718/6a3c4570-dbe0-11e5-95c7-40857ed671ae.png">

**Comment by davelab6** [comment]
The end goal of the project is to add new data for the fonts that have not already been categorised. 

To that end, I think we now JUST need a few simple filters :)

I've updated https://github.com/googlefonts/fontbakery/issues/684 yet again.

**Comment by davelab6** [comment]
I'd love to see these 2 tasks completed asap :) 

- [ ] When reading existing CSV values, use them in a way that is deduplicative: so that GFN becomes the 'UID' key for the data, and the autodetected row values are in cols next to cols for the existing values.

- [ ] Add an additional table at the top of the page that has the same head rows, and a single content row with checkboxes that toggle the cols of the main table, so that we can focus

**Comment by felipesanches** [comment]
I'm trying to interpret the meaning of "When reading existing CSV values, use them in a way that is deduplicative: so that GFN becomes the 'UID' key for the data, and the autodetected row values are in cols next to cols for the existing values."

I noticed that several fonts fail to auto-detect a GFN value. Apparently that's because they lack a METADATA.pb file. For instance:

```
felipe@guarana:~/devel/github_felipesanches/fontbakery$ ls ../../../davefonts-old/ofl/tharlon/
DESCRIPTION.en_us.html  EARLY_ACCESS.category  OFL.txt  Tharlon-Regular.ttf
```

How should we deal with these?

**Comment by davelab6** [comment]
Add to blacklist

**Comment by davelab6** [comment]
Or, better, deduce the GFN value from the filename/NAME table, using code
in the add_font.py

**Comment by felipesanches** [comment]
ok, good

**Comment by felipesanches** [comment]
Alright... so with this last commit we leave out as GFN="unknown" only really bad guys like:

* ../../../davefonts-old/ofl/cwtexming/cwTeXMing-zhonly.ttf
* ../../../davefonts-old/ofl/jomolhari/Jomolhari-alpha3c-0605331.ttf
* ../../../davefonts-old/ofl/hanna/BM-HANNA.ttf
* ../../../davefonts-old/ofl/lohitdevanagari/Lohit-Devanagari.ttf
* and so on...

These lack a METADATA.pb file and also fail to have the GFN value auto-detected because they do not follow the Google Fonts naming guidelines. I guess an extra effort could be to lookup the data from the NAME table of these files.

**Comment by felipesanches** [comment]
@davelab6 
Now with the aid of the name table entries, all fonts get good GFN values, except for a single misbehaved font:
* ../../../davefonts-old/ofl/hanna/BM-HANNA.ttf

It seems it's got an empty entry at NAMEID_FONT_FAMILY_NAME

**Comment by davelab6** [comment]
On 20 April 2016 at 20:22, Felipe Corrêa da Silva Sanches <
notifications@github.com> wrote:

> These lack a METADATA.pb file and also fail to have the GFN value
> auto-detected because they do not follow the Google Fonts naming
> guidelines. I guess an extra effort could be to lookup the data from the
> NAME table of these files.
>
No, it can just be dealt with manually as its a small set.

Blacklist BM-HANNA.

**Comment by felipesanches** [comment]
"GFN becomes the 'UID' key for the data" implemented at https://github.com/googlefonts/fontbakery/commit/410acd5d4643a74ca2a24fb69b13c00176e23b3c

**Comment by davelab6** [comment]
@impallari what is the code for calculating http://www.impallari.com/tools/darkness/index.php ?

**Comment by davelab6** [comment]
In a chat Felipe said

> This issue is a little monster now with lots of requirements stitched together adhoc... perhaps we should open a new issue with a clear description of what's still missing and what we want to get done nowadays with that tool.

The high level aim is to get a csv with these values for all fonts, and have a FB check that the data for each font is available, and if not, generate it and make it easy for a user to submit it

**Comment by felipesanches** [comment]
The tool is nowadays called `build-fontmetadata` hosted at the `gftools` repo: https://github.com/googlefonts/tools/blob/master/bin/gftools-build-fontmetadata.py

I'd suggest we move this issue to that repository and continue discussing it there.

**Comment by felipesanches** [comment]
... and perhaps we should take this as an opportunity to write a fresh new description of what's still missing and what we want to get done nowadays with this tool.

**Comment by felipesanches** [comment]
I moved the code from gftools into a new repo at https://github.com/felipesanches/FontClassificationTool

All pending issues will be reported there. I will copy things from here into individual issues there.

**Comment by felipesanches** [comment]
Done.
