### ISSUE TITLE
Speed up travis with containers

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#690]
We can speed up travis by using their container system, that wasn't available when the FB travis system was last updated. See https://github.com/FlossFoundry/Raleway/blob/master/.travis.yml for an example.

**Comment by felipesanches** [comment]
Yeah! That would be really important! The sluggishness of the current Travis setup makes it tiresome to validate experimental server-side code during development.

**Comment by davelab6** [comment]
I think we need to have test cases set up now.

**Comment by davelab6** [comment]
With the new single file script, the travis file seems pretty simple and the elapsed time of the last travis build was 71 seconds, which I think is fine, so closing this.
