### ISSUE TITLE
Do we really use git-python for anything ?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#691]
There's a snippet of code at  tools/fontbakery-build.py (line 83) that uses git-python, if available:

```
        if GITPYTHON_INSTALLED:
            try:
                repo = Repo(sourcedir)
                builddir = repo.git.rev_parse('HEAD', short=True)
            except git.exc.InvalidGitRepositoryError:
                pass
```

but the next line, overwrites the value of builddir, nothing else uses the repo object and it seels there's no collateral effect in play here. So, this seems useless leftover code, or perhaps the abandones beginning of some new feature in the past.

Do you know where does this come from, @davelab6 ? Or can I simply delete it and move on?

**Comment by davelab6** [comment]
A long time ago there was a table showing the git history. This seems out of scope for anything in the BRIEF.md so throw it away.
