### ISSUE TITLE
Add a .github folder with templates for issues and pull requests

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#694]
The https://github.com/dear-github/dear-github letter has a practical response in https://github.com/blog/2111-issue-and-pull-request-templates

We should add a .github folder with templates for
- [ ] issues and 
- [ ] pull requests

I think it is good to leave the CONTRIBUTING.md file in the root so it is more visible.

**Comment by vmesel** [comment]
@davelab6 I have one of this in one of my repositories, can I try to make some templates for the Fontbakery repo?

**Comment by felipesanches** [comment]
@vmesel sounds good :-)

**Comment by davelab6** [comment]
Keeping thsi open for me to review later
