### ISSUE TITLE
Check TTFs have post table version 2

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#698]
FontBakery needs to check TTFs have a post table version 2 per https://github.com/google/fonts/issues/215

However, this is really a symptom of a CFF -> TTF build process, so rather than spending time on a fixer, to reliably convert `post` v3 to v2, it should just be a 'note' warning that alerts us that the post table is v3 and it should be v2, likely by avoiding a CFF to TTF build process.

(Meta comment: This could be a good opportunity to write a checker in a new way. Perhaps as subclassing https://github.com/googlei18n/nototools/ like https://github.com/google/roboto/blob/master/scripts/run_web_tests.py)

**Comment by felipesanches** [comment]
implemented at https://github.com/googlefonts/fontbakery/commit/07fbcb14918c69eb200295195885c2005c45f9fc
