### ISSUE TITLE
review TestDiacritic.test_diacritic_made_as_* tests

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#700]
...to make sure they're working properly.

**Comment by davelab6** [comment]
@felipesanches can this be closed?

**Comment by felipesanches** [comment]
yes. These were UFO source file tests we had here:
https://github.com/googlefonts/fontbakery/blob/bde6a9a13da475dab7fd1ffccd33964fb6d3436c/bakery_lint/fonttests/test_ufo.py
