### ISSUE TITLE
Contribute PR for EditableGrid TAB-navigation direction param

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#719]
Port this into a proper pull request for EditableGrid upstream:
https://github.com/googlefonts/fontbakery/commit/da37192ee4ff7f98f1f882de7598981256d5a9b7

**Comment by davelab6** [comment]
@felipesanches do you remember if you made the PR to EditableGrid ?

**Comment by felipesanches** [comment]
No I haven't.

**Comment by davelab6** [comment]
@felipesanches will you be able to do this in August?

**Comment by felipesanches** [comment]
I'm not really much worried about doing this at all...

**Comment by davelab6** [comment]
Cool :)
