### ISSUE TITLE
Missing bakery_yaml.json

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#723]
As mentioned in issue #611, the build and deploy process fails to place a bakery_yaml.json file in the deployed gh-pages branch of a font project.

The collateral effect is that the "Setup" tab of the webapp displays an infinite "loading" icon.
http://googlefonts.github.io/fontbakery/#/felipesanches/CoinyTests/setup

**Comment by davelab6** [comment]
Closing as its for the old codebase
