### ISSUE TITLE
coverage.misc.CoverageException: Couldn't read '/home/travis/build/googlefonts/fontbakery/.coveragerc' as a config file

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#726]
```
$ coveralls

Traceback (most recent call last):

  File "/home/travis/virtualenv/python2.7.9/bin/coveralls", line 11, in <module>

    sys.exit(wear())

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/coveralls/__init__.py", line 86, in wear

    coverage = coveralls(data_file=args.data_file, config_file=args.config_file)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/coverage/control.py", line 140, in __init__

    "Couldn't read '%s' as a config file" % config_file

coverage.misc.CoverageException: Couldn't read '/home/travis/build/googlefonts/fontbakery/.coveragerc' as a config file
```

**Comment by davelab6** [comment]
`.coveragerc` doesn't exist, but https://coveralls.io/github/googlefonts/fontbakery is okay. @vitalyvolkov did you set up coveralls? If so, do you have a `.coveragerc` file?

**Comment by davelab6** [comment]
@felipesanches do you think coveralls is useful?

**Comment by felipesanches** [comment]
By looking at https://coveralls.io/ I think I can see that this could be useful. But this is not currently in my typical development toolbox. What do you think?

**Comment by davelab6** [comment]
We don't have a test suite, do we?

**Comment by felipesanches** [comment]
FB is a testsuite for font files. But yes, it lacks a testsuite for itself at the moment.

**Comment by felipesanches** [comment]
We currently only run the flake8 linter on the codebase on every pullrequest, but we do not have proper test cases.

**Comment by davelab6** [comment]
Then - today - coveralls is irrelevant.
