### ISSUE TITLE
Rewrite FamilyAndStyleNameFixer as smaller single-purpose Fixers

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#741]
Current implementation is completely wrong!

Ideally this should be ditched and reimplemented as a set of 4 independent fixers:
- [x] bakery_cli.fixers.StyleNameRecomendationFixer
- [x] bakery_cli.fixers.OpentypeFamilyNameFixer
- [x] bakery_cli.fixers.OpentypeFullnameFixer
- [x] bakery_cli.fixers.SubfamilyNameFixer

**Comment by davelab6** [comment]
This is high priority :)

**Comment by felipesanches** [comment]
yeah, sure! :-)

**Comment by davelab6** [comment]
> Recomendation

typo, it is Recommendation

**Comment by felipesanches** [comment]
ok, thanks
