### ISSUE TITLE
Task for Dave: Text strings

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#747]
@davelab6 
As described in https://github.com/googlefonts/fontbakery/pull/746 you said you'd better open an issue for tweaking those test descriptions and error log messages. So here it is :-)

**Comment by felipesanches** [comment]
All other pending issues were already filled as individual issues. This issue here is only concerned with the text strings editing proposals that you presented on #746.

**Comment by davelab6** [comment]
Great :)

**Comment by davelab6** [comment]
This is being fixed as part of the porting effort.
