### ISSUE TITLE
Improvements to test_platformID_1_exists

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#748]
At https://github.com/googlefonts/fontbakery/pull/746 @davelab6 made these comments regarding """ Is there any item with platformID=1 on the NAME table? """:

"So, in fact, it seems there should be, but only items 0 1 2 3 4 5 6 18"

"This is so the fonts work in Mac Word before 2014 (iirc)"

**Comment by felipesanches** [comment]
Does it mean that for all items in the NAME table we should only fail the test if platformID=='1' and nameID not in [0, 1, 2, 3, 4, 5, 6, 18] ?

**Comment by davelab6** [comment]
Yes, but there are some other tests that we should do to check that the contents of nameIDs [0, 1, 2, 3, 4, 5, 6, 18] with platformID=='1' are correct. I will send you some sample files when we turn to this.

**Comment by felipesanches** [comment]
ok. sure!

**Comment by felipesanches** [comment]
@davelab6 
please, send me those sample files :-)

**Comment by davelab6** [comment]
Sent

**Comment by felipesanches** [comment]
The font file that you sent me by mail alongside the message ""This has a correct name table"" has got nameRecords with platformId="3"

Do you mean the test should also allow 3 as a correct platformID value? (the meaning for that specific platformID value is "Windows encoding")

**Comment by davelab6** [comment]
Its more than that; the test should allow items with PID=3 and then check the conform to the patterns in that file
