### ISSUE TITLE
Improvements to test_check_names_are_ascii_only

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#751]
Regarding """ Is there any non-ascii character in NAME or CFF tables? """ @davelab6 said:

"This test should only check NAME IDs 0 to 18 inclusive"

**Comment by felipesanches** [comment]
This means that if nameID is not in the inclusive range from 0 to 18, then the test should not fail even if there are non-ascii characters, right?

If so, then I can easily filter the test to only consider the nameIDs in that range.

**Comment by felipesanches** [comment]
I'd be glad though to better understand the rationale for that.

**Comment by davelab6** [comment]
Yes, that's right. The reason is that higher NameID items are expressly for localising the ASCII only IDs into Hindi/Arabic/etc
