### ISSUE TITLE
fontbakery-fix-glyphs.py

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#754]
Per https://github.com/googlefonts/fontbakery/blob/master/BRIEF.md#4-source-management there should be a `.glyphs` file checker. 

Generally binaries exported from Glyphs are good quality, but some of the application's defaults are not what we want, and it is easy to set them to what we do want with Custom Parameters. 

The changes I've requested/made so far are:
- [x] Font copyright set correctly
- [ ] Font vendorID set correctly
- [x] Font fsType, set to “not set” or "Installable" (empty)
- [x] Font license set correctly
- [x] Font licenseURL set correctly
- [x] Masters (or instances) 8 Vertical Metrics set correctly
- [x] Instance ExtraLight weightClass set to 275
- [ ] Instances italicAngle set to 0, if the master/instance slant value is not 0
- [x] Instance named Regular (400) for families with a single instance
- [x] Instance Bold style linking set for families with a 400 and 700 instance
- [x] Source master and instance interpolation values match the stem widths? ([reference](https://github.com/googlefonts/gf-docs/commit/805751608bd166632d73a6f7da392d3ee1be34eb))

It may be possible to detect and autofix these with https://github.com/googlei18n/glyphs2ufo/ but operating on the file as a plain text file will probably work well enough for detection, and autofixing can be postponed.

**Comment by felipesanches** [comment]
I'm using the parsing stage of glyphsLib (because it would be pointless for me to write my own parser).
While loading an Inknut-Antiqua glyphs file, I found a bug in glyphsLib and reported it here:
https://github.com/googlei18n/glyphsLib/issues/55

While we don't get the upstream bug fixed, I'm simply altering the Inknut-Antiqua glyphs file to get rid of the data that triggers the bug, so that I can continue development of the fontbakery-fix-glyphs.py script.

**Comment by felipesanches** [comment]
I'm sticking to python2 for now, due to glyphsLib not supporting python3.

**Comment by felipesanches** [comment]
OK.. I did sketch an initial draft for the fontbakery-fix-glyphs.py script, but as the priority of this bug has been droped to "P4 someday maybe" I'll leave it for improving later.

Next improvements needed are:
- [ ] print the fields from instances
- [ ] validate all fields to warn the user if they're bad

**Comment by davelab6** [comment]
@m4rc1e I'm assigning this to you

**Comment by davelab6** [comment]
@m4rc1e could you check off at the top which of the things your current GlyphsApp preflight tool already checks?

**Comment by m4rc1e** [comment]
@davelab6 I've been working on one for glyphsapp. [fix-gf-spec](https://github.com/m4rc1e/mf-glyphs-scripts/blob/master/Fixes/fix_gf_spec.py)

It is still really ghetto. I'm adding bits as I'm fixing repos and discovering new things.

It currently fixes the following:

• Names match spec
• CR, nbspace get added if they don't exist and their widths are the same as space
• NULL gets created if it doesn't exist and width == 0
• Embedding is set to 0
• Licence and licenceurl get updated to our spec.

I will port it for FontTools ;)

**Comment by davelab6** [comment]
> I will port it for FontTools ;)

No, don't do that. We already have all 5 of those checks :) 

I checked the 3 items in the list at the top that you already have.

**Comment by davelab6** [comment]
@m4rc1e please check off the items at the top that your glyphs script tool already handles :)

**Comment by m4rc1e** [comment]
@davelab6 [gf-glyphs-scripts](https://github.com/googlefonts/gf-glyphs-scripts) now QAs and fixes the selected bullet points automatically :-)

**Comment by felipesanches** [comment]
Migrated to https://github.com/googlefonts/tools/issues/18
