### ISSUE TITLE
[META] v0.1.0 tasks for Felipe

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#767]
This is an issue to track the priorities of improvements being developed at branch v0.1.0

**Comment by felipesanches** [comment]
@davelab6 Can you please add a prioritized list of subtasks to the description above?

**Comment by davelab6** [comment]
https://github.com/googlefonts/fontbakery/issues?q=is%3Aopen+milestone%3A0.1.0+assignee%3Afelipesanches
