### ISSUE TITLE
fsSelection check needs review

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#769]
On a font that is set correctly, I see
```
~/src/github.com/googlefonts/fontbakery$ python fontbakery-check-ttf.py /path/to/*ttf;
...
ERROR    HOTFIXED: fsSelection REGULAR bit Fixes: OS/2 fsSelection from 64 to 0  
```
So fsSelection check needs review; it should work the same as sanity_check.py.

**Comment by felipesanches** [comment]
I'm inspecting this. Can you provide a specific font that triggers the bad behaviour? I tried with a few but couldn t find yet any font where I get the "64 to 0" hotfix.

**Comment by davelab6** [comment]
I think it was Cousine

**Comment by felipesanches** [comment]
I just tested it with Cousine but that's not the one. I'll leave this for later. Please, post a message here if you find it again.

**Comment by felipesanches** [comment]
Is this still an issue?

**Comment by davelab6** [comment]
Please test all fonts in the github.com/google/fonts repo and find out.

**Comment by davelab6** [comment]
@felipesanches did you find out?

**Comment by davelab6** [comment]
@felipesanches what is the status of this?

**Comment by davelab6** [comment]
I'm closing this, I'll reopen if I come across it again
