### ISSUE TITLE
Set up Travis for 0.1.0

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#773]
The current tool is broken in a couple of ways, so, after #772 is closed, lets get a travis setup rolling with known good font families - perhaps Cousine to start - so that we can prevent regressions; which at the most simple means continuing to pass known good fonts.

Perhaps this is the moment to leave the old codebase on a branch and move 0.1.0 to master.

**Comment by felipesanches** [comment]
The old codebase is tagged 0.0.15

I just merged the 0.1.0 branch into master.

**Comment by davelab6** [comment]
@felipesanches sounds good. https://travis-ci.org/googlefonts/fontbakery is passing so closing
