### ISSUE TITLE
Comparison tooling for updating families

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#774]
Per google/fonts 222, it would be good to be able to compare `ofl/family-old` and `/ofl/family` and see a few things, so that as families are updated, all the things that should be done in an update are taken care of. 

- [x] see filesize differences and warn if they are large
- [x] version number incremented
- [x] ttfautohint updated to at least latest stable version

I'll add other ideas here later

**Comment by felipesanches** [comment]
I'm auto-incrementing the major number. Is this the desired behaviour or should we auto-increment the minor version number?

**Comment by davelab6** [comment]
Minor! :)

**Comment by davelab6** [comment]
We also should not auto increment it on every run.

**Comment by felipesanches** [comment]
This is a new and independent script meant to be used only when updating families.

To avoid incrementing on every run I can add a --versionbump command line option, or something like that.

**Comment by davelab6** [comment]
sweet
