### ISSUE TITLE
panose check code is wrong

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#775]
panose check code is wrong, eg if the value is 3 and it is not a monospace font, it should not be autofixed. The font in https://github.com/enathu/kavivanar reproduces this.

**Comment by felipesanches** [comment]
"panose check code is wrong, eg if the value is 3 and it is not a monospace font, it should not be autofixed."

I think that what you mean with your previous statement is something like this (I'm not sure why, though), is this right?
```python
if name['OS/2'].panose.bProportion != PANOSE_PROPORTION_MODERN:
    assert_table_entry('OS/2', 'panose.bProportion', PANOSE_PROPORTION_ANY)
```

**Comment by felipesanches** [comment]
Please reopen the issue if the new implementation is still wrong.
