### ISSUE TITLE
NAME table license checker not working

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#778]
Similar to #777 with Kolar, I see

```
ERROR    HOTFIXED: License file OFL.txt exists but NameID value is not specified for that.  
```

But the NAME table of the originals IS correct, so this is buggy.

```
    <namerecord nameID="13" platformID="3" platEncID="1" langID="0x409">
      This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL
    </namerecord>
    <namerecord nameID="14" platformID="3" platEncID="1" langID="0x409">
      http://scripts.sil.org/OFL
    </namerecord>
```

**Comment by felipesanches** [comment]
"with a FAQ at" has a colon on the nameID 13 while it does not have a colon in our reference placeholder text. Should we be picky about it? If so, then the check is actually working :-)

**Comment by davelab6** [comment]
We should do what the majority of fonts in google/fonts do

**Comment by felipesanches** [comment]
I'm closing this given that it does work. It might perhaps be a bit more verbose though (which seems to be the root reason why it looked like wrong behaviour to you)
