### ISSUE TITLE
Version checker not working (minor)

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#780]
```
$ git clone https://github.com/hafontia/Assistant
$ ~/src/github.com/googlefonts/fontbakery/fontbakery-check-ttf.py Assistant/Fonts/TTF/*ttf;
...
ERROR HOTFIXED: Font version fields. Fixes: NAMEID_VERSION_STRING from Version 2.001 to Version 2.00099; | NAMEID_VERSION_STRING from Version 2.001 to Version 2.00099;
$
```
fontTools/TTX does something funny with floats or whatever so that 2.001 becomes 2.00099 and the current code doesn't understand this

**Comment by felipesanches** [comment]
Here I get: "INFO     OK: Font version fields."

Can you double-check it the issue persists with the current code from the tip of v0.1.0 branch ?

**Comment by felipesanches** [comment]
Works for me. Reopen the issue if you can describe how to cause the issue in a reproducible way.
