### ISSUE TITLE
OS/2 xAvgCharWidth autofix may be wrong

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#781]
@davelab6 said:

"OS/2 xAvgCharWidth autofix may be wrong, as in kavivanar the value is 418 which seems correct, but it is autofixed to 2278 I guess because the wide tamil glyphs make the 'real' value wider but fontforge is only counting latin glyphs for some reason. it would be best to figure out what that is and NOT autofix this value, only give an error if it is not as expected"

**Comment by felipesanches** [comment]
https://gist.github.com/jtanx/7715851

"For OS/2 table versions >= 3, take the sum of the advancement widths (from the hmtx table) of each glyph, iff the advancement width is greater than zero. Do integer division of this sum by the number of glyphs that had an advancement width > 0.

For versions < 3, follow a similar procedure, but weight according to: http://www.microsoft.com/typography/otspec/os2ver2.htm#acw, and only consider lowercase latin characters for the average."

**Comment by davelab6** [comment]
Thanks!

**Comment by davelab6** [comment]
@felipesanches what is the status of this?

**Comment by davelab6** [comment]
I think the next step is for you to implement the algo that jtanx described

**Comment by felipesanches** [comment]
At c70df187719ca8984b79b536d3e0f4867ac286eb I implemented support for OS/2 tables with version >=3. Should we support older versions of the table as well? We may simply skip the test in these cases, or we can error if version <3 or we can implement the check for the old tables. @davelab6 Which you prefer?

**Comment by felipesanches** [comment]
fyi: current implementation simply skips the check with a warning if table version < 3

**Comment by davelab6** [comment]
> Should we support older versions of the table as well?

Yes. Please implement the checks as described in https://gist.github.com/jtanx/7715851
