### ISSUE TITLE
Fix the Blacklist-related issues at fontbakery-build-fontmetadata.py

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#783]
```
$ git checkout f634f3679aaa8ea88ed2fde4f9188c182d717137
Previous HEAD position was 7145ce5... version bump to 0.0.15
HEAD is now at f634f36... compute: fix table image overflow
$ cd; 
$ python2 path/compute_font_metrics.py --files="something/*/*ttf" --existing=fonts/tools/font-metadata.csv -o font-metadata-new.csv ;
Traceback (most recent call last):
  File "src/github.com/googlefonts/fontbakery/tools/compute_font_metrics.py", line 460, in <module>
    main()
  File "src/github.com/googlefonts/fontbakery/tools/compute_font_metrics.py", line 195, in main
    ints = map_to_int_range(weights)
  File "src/github.com/googlefonts/fontbakery/tools/compute_font_metrics.py", line 143, in map_to_int_range
    min_value = float(weights_ordered[0])
IndexError: list index out of range
```

**Comment by felipesanches** [comment]
yes, I can reproduce the issue. I'll investigate how to fix it.

**Comment by felipesanches** [comment]
ok. I see that the script was renamed to tools/fontbakery-build-fontmetadata.py
on commit https://github.com/googlefonts/fontbakery/commit/23b306aae743bf63d294b737a193a38970056345

So it is still available on master, but with a different name and I can reproduce the issue on master as well with:

```
python tools/fontbakery-build-fontmetadata.py --files="../../github_google/fonts/*/*ttf" --existing=../../github_google/fonts/tools/font-metadata.csv -o /tmp/font-metadata-new.csv
```

I'll fix it in a while.

**Comment by davelab6** [comment]
from git master
$ git checkout master;
$ cd ~;
$ python2 path/fontbakery-build-fontmetadata.py --files="path/ofl/*/*ttf" --existing=fonts/tools/font-metadata.csv -o font-metadata-new.csv;
[1/112] path/ofl/family/Family-Regular.ttf...
...
Traceback (most recent call last):
  File "src/github.com/googlefonts/fontbakery/tools/fontbakery-build-fontmetadata.py", line 460, in <module>
    main()
  File "src/github.com/googlefonts/fontbakery/tools/fontbakery-build-fontmetadata.py", line 189, in main
    fontinfo = analyse_fonts(glob.glob(args.files))
  File "src/github.com/googlefonts/fontbakery/tools/fontbakery-build-fontmetadata.py", line 367, in analyse_fonts
    darkness, img_d = get_darkness(fontfile)
  File "src/github.com/googlefonts/fontbakery/tools/fontbakery-build-fontmetadata.py", line 419, in get_darkness
    text_width, text_height = font.getsize(TEXT)
  File "/usr/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 141, in getsize
    size, offset = self.font.getsize(text)
IOError: execution context too long
```

**Comment by felipesanches** [comment]
we used to postpone these problems with blacklisting, remember?

**Comment by felipesanches** [comment]
I recall that we already got the "IOError: execution context too long" error on some other fonts that we blacklisted in the past. Obviously we should fix the issue. But blacklisting the bad font can at least allow you to get the bulk of the rest of the fonts processed.

**Comment by davelab6** [comment]
Blacklisting helps :) 

```
[112/112] path/Family-Style.ttf...
Access http://127.0.0.1:5000/static/index.html

 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [14/Apr/2016 11:58:15] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [14/Apr/2016 11:58:15] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [14/Apr/2016 11:58:15] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [14/Apr/2016 11:58:23] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [14/Apr/2016 11:58:24] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [14/Apr/2016 11:58:25] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [14/Apr/2016 11:58:25] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [14/Apr/2016 11:58:26] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [14/Apr/2016 11:58:31] "GET /static/index.html HTTP/1.1" 404 -
127.0.0.1 - - [14/Apr/2016 11:58:33] "GET /static/index.html HTTP/1.1" 404 -
```

**Comment by davelab6** [comment]
http://127.0.0.1:5000/static/images/angle_2.png works, tho

**Comment by felipesanches** [comment]
haha! You deleted most files from the tools/static folder back at commit https://github.com/googlefonts/fontbakery/commit/23b306aae743bf63d294b737a193a38970056345

I'll bring them back!

**Comment by felipesanches** [comment]
OK. done. (commit 7cfba394e339b42e63a826503a666c819c23c3f2)
It is working on master branch now.

Please, reopen this issue if you get any further problem with the script.

**Comment by davelab6** [comment]
> reopen this issue if you get any further problem with the script

Lets track fixing the blacklist issues

**Comment by felipesanches** [comment]
This is all on the Google Fonts Tools repo now
