### ISSUE TITLE
fontbakery-build-fontmetadata.py Add 'unknown' output mode

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#785]
I need a new arg for fontbakery-build-fontmetadata.py that, given a set of TTFs and an existing font-metadata.csv file, it lists font files that do NOT have metadata. 

ie,  
take the list of all the TTFs in the repo,  
and the list of TTFs in the CSV,  
and subtract the 2nd list from the 1st

```
$ python2 src/github.com/googlefonts/fontbakery/tools/fontbakery-build-fontmetadata.py --files="fonts/*/*/*ttf" --existing=fonts/tools/font-metadata.csv -o newfont-metadata.csv --unknown;
```

The result is that the http://127.0.0.1:5000/static/index.html page only has a table showing the fonts that did not have metadata values before

**Comment by felipesanches** [comment]
ok, that sounds good!

**Comment by davelab6** [comment]
WIP @ https://github.com/googlefonts/fontbakery/commit/b974d9cdb2e66df4d5d2f323b7bb083302d118b5

**Comment by davelab6** [comment]
Currently it says:

```
$ python2 path/to/fontbakery/tools/fontbakery-build-fontmetadata.py --files="fonts/*/*/*ttf" --existing=fonts/tools/font-metadata.csv -o font-metadata-fonts-unknown.csv -m;

These files were removed from the list: ['ABeeZee:italic:400', 'ABeeZee:normal:400', ...
```

I would like it to say:


```
These files were removed from the list: 

```
fonts/ofl/abeezee/ABeeZee-Italic.ttf:ABeeZee:italic:400
fonts/ofl/abeezee/ABeeZee-Regular.ttf:ABeeZee:normal:400
```
