### ISSUE TITLE
fontbakery-build-fontmetadata.py Angle image col should update

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#786]
![Imgur](http://i.imgur.com/QWr7Thi.png)

After setting a row's `ANGLE_INT` value, then the row's `Image` col image is updated, but the `angle image` col image is not.

**Comment by felipesanches** [comment]
fixed at master (commit https://github.com/googlefonts/fontbakery/commit/0d53048c3dfc37438b1adc3b33709cdf454cfb1d)
