### ISSUE TITLE
OS/2 xAvgCharWidth calculation

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#788]
When checking a non-monospace font with git master, I always see something like,
```
ERROR    HOTFIXED: Font is not monospaced. Fixes: OS/2 xAvgCharWidth from 582 to 3284  
```
I think we should comment out this hotfix, because it seems all fonts fail it, and it isn't very important.

**Comment by davelab6** [comment]
Lets just comment it out for now

**Comment by felipesanches** [comment]
alright!
