### ISSUE TITLE
UnicodeDecodeError - move to python3

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#789]
I think we should move to python3, because suffering `UnicodeDecodeError`s is pretty unforgivable :)

```
$ python fontbakery-check-ttf.py ~/fonts/apache/opensans/OpenSans-Regular.ttf 
ERROR    HOTFIXED: fsType is zero. Fixes: OS/2 fsType from 8 to 0  
Traceback (most recent call last):
  File "fontbakery-check-ttf.py", line 1240, in <module>
    main()
  File "fontbakery-check-ttf.py", line 510, in main
    string = string.replace(mark, ascii_repl)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa9 in position 25: ordinal not in range(128)
$
```

**Comment by davelab6** [comment]
```
mkdir -p ~/src/github.com/itfoundry;
cd !$;
git clone https://github.com/itfoundry/kolar/;
cd kolar/products;
~/src/github.com/googlefonts/fontbakery/fontbakery-check-ttf.py *ttf;
ERROR     is missing a METADATA.pb file!  
ERROR     is missing a METADATA.pb file!  
ERROR     is missing a METADATA.pb file!  
ERROR     is missing a METADATA.pb file!  
ERROR     is missing a METADATA.pb file!  
ERROR     is missing a METADATA.pb file!  
Traceback (most recent call last):
  File "/Users/dcrossland/src/github.com/googlefonts/fontbakery/fontbakery-check-ttf.py", line 1982, in <module>
    main()
  File "/Users/dcrossland/src/github.com/googlefonts/fontbakery/fontbakery-check-ttf.py", line 610, in main
    string = string.replace(mark, ascii_repl)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 1: ordinal not in range(128)
```

**Comment by davelab6** [comment]
commit bd5e11030ef7f08a0bdf5fe53a3caf1e85167f8d works

commit f3852e144e2c331661516fc8473da2cd6e4b71a4 introduces the problem and the script stops working at that point

**Comment by felipesanches** [comment]
I commented out the broken test implementation so that you can use the tool. I'll address the issue and then bring back a fixed implementation of this test.

**Comment by davelab6** [comment]
Any luck?

**Comment by felipesanches** [comment]
I pushed a tentative fix earlier today. (commit bce483e3a5ed6883a3d3d820159b572fe064ea3d)

**Comment by khaledhosny** [comment]
What is wrong © etc. in name entries?

**Comment by davelab6** [comment]
AIUI the OpenType CFF table Copyright string can't accept it

**Comment by khaledhosny** [comment]
But the code is in the commit above is removing them from the name table not the CFF table.

**Comment by davelab6** [comment]
The focus is currently only TTFs; the point here is consistency

**Comment by khaledhosny** [comment]
I’m not sure I’m getting this right, the code above is removing © from Unicode name table entries where it is perfectly valid, and the rational is that CFF (a completely different table) can’t handle them? CFF values are redundant and no one is likely to ever see them, so there is no much consistency concern here. I suppose you are going to remove non-ASCII characters from copyright holders names as well, if not then this exercise is of very little value.

**Comment by davelab6** [comment]
Yes, the strings should be ascii 7 bit clean; authors names will be
replaced with "The $NAMED Project Authors" :)

**Comment by khaledhosny** [comment]
OK.

**Comment by davelab6** [comment]
I will check this

**Comment by felipesanches** [comment]
There's no remaining unicode error crasher. Actually no fonts in google fonts git repo are crashing the tool anymore. I tested them all.

**Comment by davelab6** [comment]
🎉
