### ISSUE TITLE
panose.bProportion check not right

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#790]
Checking a non-monospace font, I get

```
ERROR    HOTFIXED: Font is not monospaced. Fixes: OS/2 xAvgCharWidth from 1171 to 2740 | OS/2 panose.bProportion from 4 to 0  
```

A panose.bProportion value of 4 is suitable for a non-monospace font; only a value of 9 is incorrect.

**Comment by felipesanches** [comment]
Please reopen this in case it is still not quite right.
But I think it is OK now. So I'll close.

**Comment by davelab6** [comment]
I suggest assigning issues to me to verify and close

**Comment by felipesanches** [comment]
ok. good!

**Comment by felipesanches** [comment]
@davelab6 You left this one indefinitely open pending your review. But I'm pretty confident this is properly fixed. If you trust me, then close it, unless you still want to review it.

**Comment by davelab6** [comment]
Your logic in https://github.com/googlefonts/fontbakery/commit/9ec91302ee9aeb3fc4679e25f438219a4135db35 doesn't make sense to me.

**Comment by davelab6** [comment]
I will check this.

**Comment by felipesanches** [comment]
@davelab6  you need to check this.

**Comment by felipesanches** [comment]
This will be my next task after working on the Name Table checks (545). I need some feedback here.

**Comment by felipesanches** [comment]
@davelab6 I need your feedback here.
