### ISSUE TITLE
"ERROR    Font lacks the 'EURO SIGN' character.  "

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#794]
I see this error,

    ERROR    Font lacks the 'EURO SIGN' character.  

reported on files that definitely do have a U+20AC glyph encoded

**Comment by felipesanches** [comment]
Good to know. I was a bit uncertain about the implementation of that one. Thanks! I'll review it.

**Comment by felipesanches** [comment]
I fixed it at https://github.com/googlefonts/fontbakery/commit/0631c03e9246638ed9caff32afdafeb932a195b1
