### ISSUE TITLE
Ensure all code passes Google-style pylint

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#801]
These are things I would expect to see in a healthy code repository. Let's try to make FontBakery this good:
- [x] license badge
- [x] licensing info (LICENSE.txt file / license headers)
- [x] travis integration
- [x] There's a project website 
- [x] build state badge (Success vs. Failing)
- [x] issues are well tagged
- [x] issues are milestoned
- [x] Pull Requests are being actively merged / reviewed
- [x] There some documentation (at least a good README)
- [x] Code style passes linter (flake8) ? 
- [x] ~~Code style passes linter (https://github.com/google/yapf) ? ~~
- [x] ~~https://github.com/googlefonts/fontbakery/issues/838 Adopt Google Python Style)~~ (forget it)
- [ ] ~~https://github.com/googlefonts/fontbakery/issues/679~~ Ensure all code passes Google-style pylint

**Comment by davelab6** [comment]
Perhaps format in google style with https://github.com/google/yapf ?

**Comment by felipesanches** [comment]
https://github.com/googlefonts/fontbakery/issues/679 (Ensure all code passes Google-style pylint)

**Comment by felipesanches** [comment]
https://github.com/googlefonts/fontbakery/issues/838 (Adopt Google Python Style)

**Comment by davelab6** [comment]
License badge added in https://github.com/googlefonts/fontbakery/commit/74806bbc3a80e20200e5e1ff44e7381190a4b4cc

**Comment by felipesanches** [comment]
thanks, @davelab6 !

**Comment by davelab6** [comment]
>  There's a project website

the appspot website is good enough for now

**Comment by davelab6** [comment]
Seems all done
