### ISSUE TITLE
Run Travis on PRs

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#802]
Now that travis is set up to run flake8, it would be good to configure this repo to run travis and show the build pass/fail status on the pull request. I am the only admin for this repo, so please find the relevant docs so I can set this up :) 

(Originally posted as a comment in https://github.com/googlefonts/fontbakery/pull/799#issuecomment-223403089)

**Comment by felipesanches** [comment]
This has been working for a while now.
