### ISSUE TITLE
Bring back old tools as simple standalone scripts

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#806]
In b00539f @felipesanches has got rid of the old tools; lets bring them back as new, simple, standalone scripts, in the following order:

- [x] `fontbakery-metadata-vs-api.py`
- [x] `fontbakery-build-metadata.py`
- [x] `fontbakery-check-description.py`
- [x] `fontbakery-fix-ascii-fontmetadata.py`
- [x] `fontbakery-fix-familymetadata.py`
- [x] `fontbakery-fix-gasp.py`
- [x] `fontbakery-fix-glyph-private-encoding.py`
- [x] `fontbakery-fix-nameids.py`
- [x] `fontbakery-fix-panose.py`
- [x] `fontbakery-fix-weightclass.py`
- [x] `fontbakery-fix-widthclass.py`
- [x] `fontbakery-kern.py`
- [x] `fontbakery-crawl.py`
- [x] `fontbakery-stats-deva-per-day.py`
- [x] `fontbakery-build-font2ttf.py`
- [ ] `fontbakery-travis-deploy.py`
- [ ] `fontbakery-travis-init.py`
- [ ] `fontbakery-travis-secure.sh`
- [x] `fontbakery-check-upstream.py`(done at https://github.com/googlefonts/fontbakery/pull/807)

**Comment by richardfink** [comment]
What version of Python should I install to make this thing work now?  I've
lost track.

Windows, remember.  I'll deal with Mac as a separate issue.

- rich

**Comment by davelab6** [comment]
https://github.com/googlefonts/fontbakery/blob/master/fontbakery-check-ttf.py#L1
shows its python2, any version, although probably 2.7

**Comment by felipesanches** [comment]
fontbakery-kern.py does absolutely nothing:

https://github.com/googlefonts/fontbakery/blob/v0.0.15/tools/fontbakery-kern.py

**Comment by felipesanches** [comment]
closing this. The 3 travis-related tools are listed in a separate issue at: https://github.com/googlefonts/fontbakery/issues/808
