### ISSUE TITLE
Define the workflow for FontBakery Travis setup on third-party font repositories

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#808]
We don't build fonts. We only test them and generate a JSON file with the results of the tests. All automation should only involve invoking the fontbakery-check-ttf.py script and displaying the testsuite results in a web-browser. The other tools are meant for individual non-automated usage by the users themselves.

Do we still want to setup Travis to auto-commit on gh-pages of the font project repos?
If so, we may reuse portions of these 3 old travis management helper scripts that we had in FontBakery's old codebase:
- [ ] fontbakery-travis-deploy.py
- [ ] fontbakery-travis-init.py
- [ ] fontbakery-travis-secure.sh

**Comment by davelab6** [comment]
Yes, or the gh-pages branch of another repo

**Comment by davelab6** [comment]
But please postpone this until the actual checker is flawless

**Comment by felipesanches** [comment]
alright!

**Comment by felipesanches** [comment]
This is deprecated. We wont do it this way anymore since now everything goes in the container engine.
