### ISSUE TITLE
Fontbakery skips fontforge checks on AdobeBlank (otherwise it would hang)

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#811]
2c0b0682b231da12caa9a1e8781a6d13dd03fdb8 skips AdobeBlank on the fontforge tests in order to avoid the hang and to be able to run all the other checks.

We should investigate the issue in order to properly fix it, instead of simply blacklisting the troublesome font files.

**Comment by davelab6** [comment]
Blank is a weird font, so fine to blacklist

**Comment by felipesanches** [comment]
"Adobe Blank is a special-purpose OpenType font that maps all Unicode code points to non-spacing and non-marking glyphs"

I'll simply close this one as this is really a corner case weird font.

@davelab6 I'm curious to learn what is the practical purpose of such font.

**Comment by davelab6** [comment]
It is a great hack to prevent font fallback
