### ISSUE TITLE
Check for glyph names are confused by multiply encoded glyphs

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#820]
In https://github.com/khaledhosny/reem-kufi master I get:
```
ReemKufi-Regular.ttf: Glyph 0x00A0 is called "space": Change to "nbsp" or "uni00A0"
```

(which should be skipped anyway, see #819) but that glyph is used for both space and NBSP (`cmap` entries for both characters map to the same glyph) which is a common practice.

The code should detect such multiple mappings and accept the glyph name if it is good for one of them, or just give up since the name is bound to be “wrong” for all but one of them any way.

**Comment by davelab6** [comment]
Thanks for reporting! I agree. @felipesanches please update it to detect such multiple mappings and accept the glyph name if it is good for one of them

**Comment by felipesanches** [comment]
@khaledhosny I'm assigning this to you because I was not able to build your reem-kufi TTFs from source for checking (see https://github.com/khaledhosny/reem-kufi/issues/7). Can you help me validate that the pull request at https://github.com/googlefonts/fontbakery/pull/847 fixes the issue ?

**Comment by khaledhosny** [comment]
You can use the TTFs from https://github.com/khaledhosny/mada/releases/tag/v1.2 as well.

**Comment by khaledhosny** [comment]
I still get the same error even with #847 applied.

**Comment by m4rc1e** [comment]
Hey hey,

Yep, I still get this as well. 

Do we even need this [check](https://github.com/googlefonts/fontbakery/blob/master/fontbakery-check-ttf.py#L2934)?

**Comment by felipesanches** [comment]
@m4rc1e the issues for @khaledhosny seem to have been fixed by https://github.com/felipesanches/fontbakery/commit/d6d547d697745e7c13477f611d5c4f3dcab23002 (if not, let me know)

Can you point me to a specific font file that still triggers the problem?

**Comment by m4rc1e** [comment]
Hey @felipesanches 

Give this font a try:
[https://github.com/m4rc1e/The-Lobster-Font/tree/master/fonts/ttf](https://github.com/m4rc1e/The-Lobster-Font/tree/master/fonts/ttf)

I get this:
` Glyph name 'space' is attributed to more than a single codepoint: (0x9, 0x20, 0xd)`

Cheers,
Marc

**Comment by felipesanches** [comment]
I see...

that's TAB (0x9) SPACE (0x20) and CARRIAGE RETURN (0xD)
So I guess these are ok and shuld not be rteated as an error, right?

**Comment by davelab6** [comment]
No:)

**Comment by felipesanches** [comment]
@davelab6 what do you mean?

```
"No:)" == It should not be treated as error
```

or 

```
"No:)" == No, I disagree with what you just said :-)
```

**Comment by davelab6** [comment]
"It should not be treated as an error, no."

**Comment by felipesanches** [comment]
yeah... it seems that the real solution here is to simply drop the "Check glyphs have unique names" check as pointed out by @m4rc1e
