### ISSUE TITLE
Add option to skip checks specific to github.com/google/fonts

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#822]
I get two errors related to missing `METADATA.pb` file, do I really need to include one in my repos?

**Comment by davelab6** [comment]
You don't need to include it in your repo, but I need to include it in the github.com/google/fonts repo, and the tool's purpose is to check things are ready for that.

**Comment by khaledhosny** [comment]
An option to skip checks specific to github.com/google/fonts would be nice. I’d like to eventually have zero errors, so I can integrate it in my build scripts.

**Comment by davelab6** [comment]
Yep, I agree

**Comment by felipesanches** [comment]
@khaledhosny you now can avoid gfont-specific checks. Please let me know if there's any other error in your fonts that may be an issue in FontBakery :-)

I'll be happy to see FontBakery being used as part of larger toolsets, such as by integrating it into your build scripts.

**Comment by khaledhosny** [comment]
I still get this error with `-s`:
```
ERROR    '../my-fonts/mada/Mada-Bold.ttf' is missing a METADATA.pb file!
```
