### ISSUE TITLE
Check results contain binary data

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#824]
```
* HOTFIX: Font version fields. Fixes: NAMEID_VERSION_STRING from \00V\00e\00r\00s\00i\00o\00n\00 \001\00.\000\000\000 to \00V\00e\00r\00s\00i\00o\00n\00 \001\00.\000\00;
```

Looks like UCS-2 data escaped into the output, but should be encoded as UTF-8 before writing it out. This causes Gedit to misinterpret the file encoding:
![2016-07-07 04-59-43](https://cloud.githubusercontent.com/assets/93914/16641311/0ba5e7ec-4408-11e6-8afe-d8baddad91b9.png)

**Comment by davelab6** [comment]
@khaledhosny which file produced this? 

I wonder that python3 would handle this better by default...

**Comment by khaledhosny** [comment]
I tested with Reem Kufi and Mada.

**Comment by khaledhosny** [comment]
I think FontTools handles decoding name entries transparently now, so the code needs to just stop manually decoding it.

**Comment by davelab6** [comment]
That sounds like great news! :) 

@felipesanches the repos are here

https://github.com/khaledhosny/mada
https://github.com/khaledhosny/reem-kufi
