### ISSUE TITLE
Use the Microsoft validation tools if they are available

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#831]
Microsoft offers a libre font validation tool, and per https://github.com/Microsoft/Font-Validator/network it seems the most advanced version today is https://github.com/schriftgestalt/Font-Validator/

We should wrap this, similar to OTS and https://github.com/googlefonts/fontbakery/issues/445 
- [x] find out what the MSFontVal command line interface is like - if it exists, how to configure which of its tests to run
- [x] find out what the MSFontVal output format is like
- [x] detect if MS Font Validator is available and if so, run it on each font
- [x] find out how to install MS Font Validator into a travis instance so it is available to run

**Comment by HinTak** [comment]
Argh, I am slightly offended that you said the most advanced version today is schriftgestalt's. While he has one major extra, the Mac OS X wrapper, and it is a very good thing, the most advanced branch is https://github.com/HinTak/Font-Validator/tree/embedding-ironpython , I think, functionality-wise...

**Comment by HinTak** [comment]
or https://github.com/HinTak/Font-Validator/tree/hybrid+empy.2016-05-06 if you do not mind being slightly non-free...

**Comment by HinTak** [comment]
I wasn't too sure I want to merge the embedded python interpreter by default, but it is required for testing the details of the newly implemented rasterization test.

**Comment by HinTak** [comment]
The documementation for the command line interface (the message you get if you just type the command line blank):

https://github.com/HinTak/Font-Validator/blob/hybrid%2Bempy.2016-05-06/FontValidator/CmdLineInterface.cs#L200

**Comment by davelab6** [comment]
> Argh, I am slightly offended that you said the most advanced version today is schriftgestalt's. 

I apologies - that's what I inferred from the network graph, nothing more :) 

> While he has one major extra, the Mac OS X wrapper, and it is a very good thing, the most advanced branch is https://github.com/HinTak/Font-Validator/tree/embedding-ironpython , I think, functionality-wise...

Okay great, but does this make sense on a CLI GNU+Linux container environment?

**Comment by davelab6** [comment]
Looks like this is the command we want:

    FontValidator -file font.ttf -all-tables -report-stdout

**Comment by HinTak** [comment]
The rasterization test itself contains about a dozen parameters. From
https://github.com/HinTak/Font-Validator/blob/hybrid%2Bempy.2016-05-06/bin/scripting-examples/rast_parameters.py#L32
to
https://github.com/HinTak/Font-Validator/blob/hybrid%2Bempy.2016-05-06/bin/scripting-examples/rast_parameters.py#L64

You do not need the embedded python interpreter if you do not need to deviate from the default (or switch off/on specific parts). Most people do not need or want to switch them on/off/differently from the default. That's why I haven't merged it into master.

**Comment by felipesanches** [comment]
> if you do not mind being slightly non-free...

There's not such thing. It either is non-free or it ain't ;-)

**Comment by HinTak** [comment]
But yeah, it makes more sense to have it when one needs bulk testing...

**Comment by HinTak** [comment]
I know of one person who prefers "non-free now" vs "free later" :) ( https://github.com/HinTak/Font-Validator/issues/14#issuecomment-217437398 ). 

The embedded python interface is for testing like say, I want to just test for sub-pixel hinting at size 10 for every font in my hard disk (vs all three BW/Grey/ClearType modes + about 70 sizes, from size 4-72 + a few larger sizes, which are the default), or when I want to test the skew/stretch transforms. Most people would be testing for specific fonts, but all modes and all sizes, and most people do not want to or care about the skew/stretch transforms.

**Comment by HinTak** [comment]
Actually, if you have the CPU power to burn, I would suggest that you run the non-free MSFontVal variant on any freely available fonts (i.e. google's, but the whole /usr/share/fonts on a typical Linux box would do *very* well for me!) and send me the collection of reports afterwards. See my request earlier:

http://typedrawers.com/discussion/1658/old-ms-fontval-reports-to-spare-or-computer-time-to-make-new-ones

The non-free variant has been augmented with a command line interface, and can be driven on the command line . You still need wine (and a slightly unusual non-default config as that), but is scriptable and can be run headless.

Actually I have not tried running wine headless, but presumably it just needs a dummy X framebuffer even if it does.

**Comment by HinTak** [comment]
FontVal 2.0 was tagged and released on Jul 18. You'll still need a heavily patched freetype for it, so it is bundled for both Mac OS X and windows. The XML output report's schema is at 

https://github.com/HinTak/Font-Validator/blob/embedding-ironpython/GenerateFValData/GenerateFValData/helpitems.xsd

FWIW, the FreeType backend has gone beyond 2.0 since then and newer enhancements checks use of undocumented behaviors, agreement with maxp, and a lot more exotic errors and have added some FreeType specific checks also.

**Comment by felipesanches** [comment]
URL of the schema seems to have changed to https://github.com/HinTak/Font-Validator/blob/embedding-ironpython/GenerateFValData/helpitems.xsd

**Comment by felipesanches** [comment]
I've built FVal from source here on my computer and I am able to run it on the command line.

**Comment by HinTak** [comment]
> URL of the schema seems to have changed to https://github.com/HinTak/Font-Validator/blob/embedding-ironpython/GenerateFValData/helpitems.xsd

Oh, my mistake. https://github.com/Microsoft/Font-Validator/blob/master/GenerateFValData/helpitems.xsd works too. It is not expected to change at all, ever.

Mostly you want to do `mono bin/FontValidator.exe -all-tables -file <fontfile> ...`, and for casual trying-out use, just the addtional `-stdout` . 

Adding `+raster-tests` would give you the full test, which requires a modified freetype. It should auto-detect and tell you it does not work on your system, unless you are on windows/mac, within it bundled.

**Comment by felipesanches** [comment]
We can't run it on app engine because it relies on subprocess module which is unsupported. That's something we'll have to address somehow, but I'll leave it to be tracked by another issue. Working fine on the command line now.
