### ISSUE TITLE
Adjust brief to say fontbakery-check-ttf.py combines 3 checks (files, sets of files, and families) 

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#834]
I think the BRIEF set out having 1 tool that takes as input individual TTF files (section 2.1)

And then section 2.2 sets out a tools that checks a set of TTF files. 

And 2.5 sets out another tool that takes as input a directory, that contains TTF files + METADATA.pb file + DESCRIPTION file, and ensures they all align.

I think you need to split up https://github.com/googlefonts/fontbakery/blob/master/fontbakery-check-ttf.py to match what the BRIEF describes.

**Comment by davelab6** [comment]
On reflection, I think this is not very important, I think the current tool is fine. I'll update the BRIEF to reflect the tool.

**Comment by felipesanches** [comment]
done.
