### ISSUE TITLE
Semibold or SemiBold?

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#840]
Adobe (at least in the Source super family) uses Semibold and so did I in Mada (to make using Source Sans Pro simpler), but fontbakery aborts when it detects such file name. I’d rather not rename the font and keep my like simpler.

Also, isn’t aborting on non-canonical file name a bit too much?

**Comment by davelab6** [comment]
Nope! Sadly the OS X HFS+ file system is not case sensitive, but the Fonts API is, and that's a hard requirement.
