### ISSUE TITLE
PLACEHOLDER_LICENSING_TEXT is missing a colon

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#843]
Fontbakery wants the text to be:
```
This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at http://scripts.sil.org/OFL
```
But I think it should be:
```
This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL
```
(Notice the colon after `at`).

**Comment by davelab6** [comment]
I suspect you are right. It should be whatever the majority of existing
ttfs in google/fonts use.

**Comment by khaledhosny** [comment]
Of fonts at google/fonts that use similar format, 922 files have a colon after `at` and 52 don’t.

**Comment by felipesanches** [comment]
Does it also apply to the apache licensing text?

**Comment by felipesanches** [comment]
@khaledhosny Can you please verify if the apache licensing text also needs to have the missing colon? I also wonder about the missing "http://" in the apache text. Which is the most common wording for the Apache license ?

**Comment by davelab6** [comment]
Ttx -t name fonts/apace/*/*ttf

And grep

**Comment by khaledhosny** [comment]
Most Apache-licensed fonts on google/fonts just say `Licensed under the Apache License, Version 2.0`, but the few that provide a URL has a colon.

**Comment by davelab6** [comment]
@felipesanches how many fonts on google/fonts/apache say 

`Licensed under the Apache License, Version 2.0`

and how many say,

`Licensed under the Apache License, Version 2.0: <URL>`

?

**Comment by felipesanches** [comment]
I found roughtly 300 fonts with `Licensed under the Apache License, Version 2.0` in google fonts github repo (by grepping their name tables extracted with ttx)

I found none with the colon and a URL.

**Comment by davelab6** [comment]
Ok then I guess this is fine :)

**Comment by felipesanches** [comment]
I fixed the reference workding the check expects so that the hundreds of apache licensed fonts at the google fonts git repo will pass this check. This wording is, thus, our normative reference.
