### ISSUE TITLE
Rounding issue with calculating OS/2.xAvgCharWidth

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#855]
For Mada-Light.ttf, the sum of the widths/number of glyphs is 474.997 (174799/368), but fontbakery truncates it to 474 instead of rounding it to 475.

**Comment by davelab6** [comment]
Sounds like a bug to me :) @felipesanches should be a few chars to fix XD

**Comment by felipesanches** [comment]
thanks! It is really easy to fix. I'll add 0.5 before rounding (so that it rounds to the closest value intead of rounding to the largest possible integer below.

**Comment by davelab6** [comment]
That seems like a hack to make truncation like rounding but ok
