### ISSUE TITLE
Improve testing on Travis (add more sample font families to increase code testing coverage)

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#875]
I think the CI should exercise more of the code, ideally there should be at least one font testing each check.

**Comment by felipesanches** [comment]
Travis does run fontbakery on a single test font: Cousine-Bold

We could add a second one such as Mada, perhaps.

Also, we could run a family (Cousine-*.ttf and/or Mada*.ttf) instead of a single font, in order to cover the cross-family checks as well.

**Comment by davelab6** [comment]
@khaledhosny anything else to do here?

**Comment by khaledhosny** [comment]
Not exactly the kind of testing I had in mind, I was thinking more of units tests, also it seems that all it checks for is that the script does not crash not if there are any regressions.

**Comment by davelab6** [comment]
@graphicore has architected this and @felipesanches has been filling it out, so I'm closing this
