### ISSUE TITLE
fsSelection REGULAR

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#876]
The error message is not clear:
```
$ ./fontbakery-check-ttf.py -s --ghm ../mada/Mada-Black.ttf
…
ERROR    fsSelection REGULAR bit Changes that must be applied to this font: OS/2 fsSelection from 192 to 128
```
The assumes the only way to set fsSelection is by assigning it an integer, which is unlikely most of time since people will be editing it in some higher level way. It should instead say what the required functional change is, e.g. `fsSelection bit 6 (REGULAR) is unset but it should be set for this font`, or the other way around or in some other descriptive way.

**Comment by davelab6** [comment]
Completely agree
