### ISSUE TITLE
fsSelection for familes with more than 4 fonts

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#877]
```
$ ./fontbakery-check-ttf.py -s --ghm ../mada/Mada-Black.ttf 
…
ERROR    fsSelection REGULAR bit Changes that must be applied to this font: OS/2 fsSelection from 192 to 128
```

This seems wrong to me, the REGULAR bit should be set here since `Mada Black` is considered a family of its own (for the old Windows APIs that requires this). From https://www.microsoft.com/typography/otspec/name.htm:

> Font Family name. Up to four fonts can share the Font Family name, forming a font style linking group (regular, italic, bold, bold italic - as defined by OS/2.fsSelection bit settings).

So the fsSelection bits seem to be tied to this 4 fonts limitation, so the code should be checking name id 2 not name id 17 to determine whether a font is regular or not for this check.

If this is not the case, then I think ufo2ft needs to be fixed.

**Comment by davelab6** [comment]
I think you are right that the check should use id 2

**Comment by felipesanches** [comment]
Source of truth for the "Checking fsSelection REGULAR bit" check is the filename.

This check does not deal with name table entries at all.

**Comment by felipesanches** [comment]
I'm confused about the statement: "Mada Black is considered a family of its own"

The inference from filename is that "Mada Black" would be the BOLD face in a family called Mada.

@davelab6 is this Mada naming scheme canonical ?

**Comment by felipesanches** [comment]
Current master output when running with Mada-Black.ttf is:

```
~/devel/github_felipesanches/fontbakery/fontbakery-check-ttf.py -v Mada-Black.ttf
[...]
INFO     OK: OS/2 usWeightClass value looks good!  
ERROR    fsSelection REGULAR bit should be reset.
```

**Comment by khaledhosny** [comment]
See https://github.com/googlefonts/fontbakery/issues/878#issuecomment-236337737

**Comment by davelab6** [comment]
> @davelab6 is this Mada naming scheme canonical ?

Yes, `Mada-Black.ttf` is canoncial.

**Comment by davelab6** [comment]
> I'm confused about the statement: "Mada Black is considered a family of its own"

It means the id=1 is unique.

**Comment by davelab6** [comment]
We have a static, fixed, 1 to 18 font files in any family. Therefore I would like a dict with 18 correct fsSelection values mapped to the 18 font file keys, and a VERY simple check that says, if the filename is X then the fsSelection should be Y, otherwise its wrong.

**Comment by davelab6** [comment]
> `ERROR    fsSelection REGULAR bit should be reset.`

This is not a helpful message. Assuming Mada-Black.ttf has the fsSelection Regular bit set (which I believe is the right thing to do, so if it isn't set, @khaledhosny please set it :) then this should not error, and instead say,

`OK       fsSelection REGULAR bit is set correctly.`

If `Something-Black.ttf` does not have the Regular bit set, then the message should be

`ERROR    fsSelection REGULAR bit is not set, but should be.`

**Comment by felipesanches** [comment]
I did change the criteria for the fsSelection REGULAR bit check so that only Regular and non-RIBBI fonts will have the REGULAR bit set and the rest (all RIBBI, except Regular) will have REGULAR bit unset.

Please close this issue if this is correct.

**Comment by khaledhosny** [comment]
This check still seems to be wrong:
```
$ ./fontbakery-check-ttf.py -s ../mada/Mada-Black.ttf 
…
ERROR    OS/2 fsSelection REGULAR bit should be set.
```

But looking into the TTX dump, I see:
```xml
<fsSelection value="00000000 11000000"/> 
```

So bit 6 is actually set. The same happens with BOLD bit.

**Comment by davelab6** [comment]
No italic fonts should be marked as regular

**Comment by felipesanches** [comment]
thanks, Dave

**Comment by felipesanches** [comment]
> This check still seems to be wrong:
```
$ ./fontbakery-check-ttf.py -s ../mada/Mada-Black.ttf 
…
ERROR    OS/2 fsSelection REGULAR bit should be set.
```

Why is this wrong? Black is not RIBBI, so the fsSelection REGULAR but it should be set to 1. I'm saying this based on @khaledhosny description of the issue: "This seems wrong to me, the REGULAR bit should be set here since Mada Black is considered a family of its own"

**Comment by felipesanches** [comment]
oh! I see! You're saying that the even though the expected value is right, the detection is getting it wrong, that's it?

**Comment by khaledhosny** [comment]
Yes.

**Comment by felipesanches** [comment]
a-ha! Got it!

It was a missing cast to bool that was making the bit check return a wrong result.

**Comment by felipesanches** [comment]
Can you acknowledge it's good now, @khaledhosny ?

**Comment by khaledhosny** [comment]
Looks good now.

**Comment by felipesanches** [comment]
:-)
