### ISSUE TITLE
Specify and implement a "StyleName recommendation" check

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#878]
```
$ ./fontbakery-check-ttf.py -s ../mada/Mada-Black.ttf 
…
ERROR    Mada-Black.ttf: Warning: Windows-only Opentype-specific StyleName should be set to "Regular".
```

I have no idea what is “Windows-only Opentype-specific StyleName” or what to do with this error.

**Comment by davelab6** [comment]
Name record id 2.

Assign to me and ill review the error message. I agree they need urgent
improvement.

**Comment by felipesanches** [comment]
@davelab6 I re-wrote the log messages in this check based on @khaledhosny 's feedback at https://github.com/googlefonts/fontbakery/pull/884/commits/eb78cb27845d81d0627de36436ba22b62e6fafe8 and merged it into master. I'll leave this issue open for you to review it.

**Comment by felipesanches** [comment]
In addition to the wording of the log messages, there's also an inline "this seems unreliable" comment from you in this check. This check may still need some further improvement.

**Comment by felipesanches** [comment]
OK. I looked closer to things this test checks and it is not even clear what rule this is supposed to be validating.

This check involves name entries NAMEID_TYPOGRAPHIC_SUBFAMILY_NAME and NAMEID_FONT_SUBFAMILY_NAME. What are the relationships between these 2 name table entries that we would like to assert here?

The current implementation is non-sensical and I'll comment it out. We should only bring this back after we decide which rules we want to check here.

**Comment by felipesanches** [comment]
Also, not sure if "stylename recommendation" was the best description for the check.

@davelab6 and @khaledhosny What relations (if any) do we want to make sure exists between nameID=2 (SUBFAMILY_NAME) and nameID=17 (TYPOGRAPHIC_SUBFAMILY_NAME) ?

**Comment by khaledhosny** [comment]
Windows old font APIs allow only four fonts per family, so for any given family there can only be the following four fonts:

| Family (id=1) | Subfamily (id=2) | Full name (id=4) |
|---------------|------------------|------------------|
| Foo           | Regular          | Foo Regular      |
| Foo           | Bold             | Foo Bold         |
| Foo           | Italic           | Foo Italic       |
| Foo           | Bold Italic      | Foo Bold Italic  |

To support families was more than four fonts, typographic family name and typographic subfamily name have been introduced, and the extra fonts have to be structured like this:

| Family (id=1) | Subfamily (id=2) | Full name (id=4) | Typograpghic Family (id=16) | Typographic Subfamily (id=17) |
|---------------|------------------|------------------|-----------------------------|-------------------------------|
| Foo Light     | Regular          | Foo Light        | Foo                         | Light                         |
| Foo Medium    | Regular          | Foo Medium       | Foo                         | Medium                        |
| Foo Black     | Regular          | Foo Black        | Foo                         | Black                         |

So for the old APIs these are seen as separate families with just the regular style each, ad for newer APIs that support the typographic name they all belong to the Foo family. For the first four styles name ids 16 and 17 can be missing or identical to 2 and 4, respectively.

**Comment by davelab6** [comment]
> I looked closer to things this test checks and it is not even clear what rule this is supposed to be validating.

I think that's what I was saying with the inline code comment I made :)

> What relations (if any) do we want to make sure exists 

None. We have a small list of 1 to 18 possible files, and we can specify in a simple static way what the correct values are for each of them , and check them in a simple way.

**Comment by alexeiva** [comment]
In regard to @khaledhosny comments, these hotfixes look questionable to me:

<img width="1645" alt="screen shot 2016-07-31 at 17 42 55" src="https://cloud.githubusercontent.com/assets/16634089/17279612/8ece9834-5746-11e6-9199-17323a5f48fe.png">

Shouldn't `nameid 17` be unchanged?

```
"description": "StyleName recommendation",
        "log_messages": [
            "HOTFIX: Jura-Light.ttf: Warning: Windows-only Opentype-specific StyleName set to \"Regular\" as a default value. Please verify if this is correct."
        ],
        "result": "HOTFIX",
```

Not sure how to fix this error. It would be very helpful to have `nameid=` attributes in the error messages. 


```
 "description": "Does full font name begin with the font family name?",
        "log_messages": [
            "ERROR: Font family name 'Jura' does not begin with full font name 'Jura Light'"
        ],
        "result": "ERROR",

```

**Comment by felipesanches** [comment]
@alexeiva please update your fontbakery repo to latest master because these messagees were already fixed to include nameid values recently.

**Comment by alexeiva** [comment]
@felipesanches 

Yes, I see the new names, that's better. 
[FULL_FONT_NAME:MACHINTOSH]  typo: MACHINTOSH > MACINTOSH

Could you also include the name id numbers?, i.e [FULL_FONT_NAME:WINDOWS][nameid=2]

And then we need a documentation of nameids and what they correspond to in Glyphs App, i.e
FULL_FONT_NAME:WINDOWS > `postscriptFullName` 

I did some fixes in Jura, and ran the tests again. Some final comments on the error messages:

```
 "description": "Font names are consistent across platforms?",
        "ERROR: Entries in \"name\" table are not the same across specific platforms."

```
I believe this message would appear for all fonts larger than 4 styles?


---

```
"description": "Assure valid format for the main entries in the name table.",
	    "ERROR: [FULL_FONT_NAME:WINDOWS] entry: expected 'Jura Light' but got 'Jura-Light'"
```
Is there a custom parameter I can add to fix this in Glyphs?
I tried adding `postscriptFontName`, `postscriptFullName`custom parameters, but this generated even more errors. 

---

```
"description": "Checking fsSelection BOLD bit",
    "log_messages": [
        "ERROR: OS/2 fsSelection BOLD bit should be set."
    ],
    "result": "ERROR",
    "target": "/Users/alexei/github.com/alexeiva/jura/Jura-Bold.ttf"
```
Not sure why I get this message, I do have the Bold bit set:

<img width="465" alt="screen shot 2016-07-31 at 19 10 32" src="https://cloud.githubusercontent.com/assets/16634089/17279998/7b1252de-5752-11e6-97d6-b17a0ca02ff7.png">

**Comment by davelab6** [comment]
Sadly Font Bakery can not be trusted more than Glyphs. Do not set any
custom parameters for naming, just set the style name, weight, and
bold/italic check marks correctly.

**Comment by felipesanches** [comment]
we've been getting lots of feedback from you guys, and we're fixing everything you point out, so fontbakery will gradually become more and more trustworthy.

**Comment by alexeiva** [comment]
I couldn't make fb happy with any of the naming schemes's I tried.  But then I ran tests on published fonts like Merriweather, and WorkSans with similar errors. 

So I followed the naming scheme of said fonts, and will leave it like this. 

What I found helpful were the vertical metrics hotfixes. I simply copied the values from fixed ttf's to the source file. 

And the copyright test was helpful. I updated the notices so they are consistent with the 1st line of OFL.txt.

**Comment by felipesanches** [comment]
yeah... the naming scheme checks are still unreliable but I'm working on getting this right asap.

**Comment by alexeiva** [comment]
Thanks for your work, @felipesanches. Great to see this moving. 

You may want to use WorkSans/Cormorant as beacons — multiple style fonts with proper Glyphs naming. If their naming validates fb's tests, it would be reliable.

**Comment by felipesanches** [comment]
@alexeiva Have you already renamed DemiBold to SemiBold ? I have the impression that that's one of the things you still need to change in order to conform to canonical naming rules.

**Comment by felipesanches** [comment]
OK... I reviewed everything and concluded that the "StyleName recommendation" check as described here is basically redundant with another check we already have implemented in fontbakery, called "Assure valid format for the main entries in the name table."

I have tweaked it a bit ( based on this conversation and some feedback on notation as suggested by @alexeiva ) and tested it with Merriweather (from Google Fonts GitHub repo). The font passes all checks except this one:

```
"ERROR: [FULL_FONT_NAME(4):WINDOWS(3)] entry: expected 'Merriweather Regular' but got 'Merriweather'"
```

But this is meant to be this was as already requested earlier this week by @davelab6

**Comment by alexeiva** [comment]
DemiBold and Book were legacy names, which are served on GF as SemiBold and Regular. 
 
<img width="278" alt="screen shot 2016-07-31 at 21 36 57" src="https://cloud.githubusercontent.com/assets/16634089/17281065/f52690b2-5766-11e6-84ed-8bd9426c9417.png">

DemiBold and SemiBold are both 600 — it is a question of preference.
