### ISSUE TITLE
The check results report should be divided in sections per font

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#879]
Right now, when reading the markdown report for more than one files it is very hard to tell what font each error or warning is about.

**Comment by felipesanches** [comment]
Yes, I agree.

We already have the ability to distringuish that, by looking at the JSON output. Each entry has a "target" attribute that specifies which fontfile, METADATA.pb file or folder the check result refers to.

I can use that info to sort the check results and format the markdown output with the requested sections.

**Comment by davelab6** [comment]
I suggest an efficient way to get the output you want is to mock it up by
taking current output and editing it to be what you would ideally see as
the output. Then Felipe can work on it to match.

**Comment by felipesanches** [comment]
The approach suggested by dave would be great!

**Comment by khaledhosny** [comment]
Something like:

```markdown
# Fontbakery check results
## Mada-Black.ttf
### Checking OS/2 achVendID
* Warning: OS/2 VendorID is 'BLQ ' but this is not registered with Microsoft. You should register it at https://www.microsoft.com/typography/links/vendorlist.aspx

### substitute copyright, registered and trademark symbols in name table entries
* ERROR: NAMEID #0 contains symbol that should be replaced by '(c)'
* No need to substitute copyright, registered and trademark symbols in name table entries of this font.

### Checking fsSelection REGULAR bit
* ERROR: fsSelection REGULAR bit Changes that must be applied to this font: OS/2 fsSelection from 192 to 128

## Mada-Bold.ttf
### Checking OS/2 achVendID
* Warning: OS/2 VendorID is 'BLQ ' but this is not registered with Microsoft. You should register it at https://www.microsoft.com/typography/links/vendorlist.aspx

### substitute copyright, registered and trademark symbols in name table entries
* ERROR: NAMEID #0 contains symbol that should be replaced by '(c)'
* No need to substitute copyright, registered and trademark symbols in name table entries of this font.

### StyleName recommendation
* ERROR: Mada-Bold.ttf: Warning: Windows-only Opentype-specific StyleName should be set to "Regular".
```

**Comment by felipesanches** [comment]
looks good!

**Comment by felipesanches** [comment]
"No need to substitute copyright," is an OK message. I think the markdown report should include only ERROR and INFO messages. The OK messages would clutter the output making it harder to read. What do you think?

**Comment by davelab6** [comment]
Agree about verbose mode for ok messages
