### ISSUE TITLE
autofixing in-memory even if not persisting on disk

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#881]
I'm wondering whether or not I should run the autofix routines on the loaded font in-memory even if the user has not requested autofixing the file on disk.

Applying fixes in-memory may be good to avoid cascading multiple errors in the report.

A counter-example could be compilers such as GCC that can pedantically report several issues caused by a single silly semi-colon that a user may have missed in the source code.

I'm not really sure which strategy is the best here. I understand that GCC users are likely more comfortable with navigating the mess of error messages it can output. So I have the tendency to prefer applying in-memory auto-fixes to keep the error log clean and minimal for the type designers.

**Comment by davelab6** [comment]
Lint tools are used iterately until they do not error, so lots of messages
is fine. I don't think it is helpful at all to mess with the file in
memory.

**Comment by felipesanches** [comment]
alright, thanks
