### ISSUE TITLE
fontbakery-fix-gasp only modifies highest range

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#890]
Hello,

I've checked the [gf checklist spec](https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md) and it says 'The gasp should be set to 15'.  However, this script will only change the highest gasp range to 15:

`table.gaspRange[65535] = value`

Fonts can have many ranges. Do we care about those other ranges? should we only have 1 range and set it to 15?

Cheers,
Marc

**Comment by davelab6** [comment]
It may be a bug but I believe this sets 1 range for all sizes to 15

**Comment by m4rc1e** [comment]
Hey Dave,

When I view the whole function. I see it's only changing the value for the maximum key.

```
def fix(self, value=15):
    try:
        table = self.font.get('gasp')
        table.gaspRange[65535] = value
        self.saveit = True
    except:
        print('ER: {}: no table gasp'.format(self.fontpath))
```

I just ran the script and my suspicions were correct. When I look at the table with FontTools, we get this:

```
$ font = TTFont('Francoisone.ttf')
$ font['gasp'].gaspRange
{65535: 15, 19: 7, 7: 10}
```

If we only want 65535 set to 15. We have to remove all the other ranges.

Cheers,
Marc

**Comment by m4rc1e** [comment]
Ok, I've finally figured things out.

I didn't realise this tool was coupled with ttfautohint. We really need more docstrings to explain these things.

When I ran the font through ttfautohint with default settings. It dropped my existing gasp table and replaced it with a single range 0–65535.

I'll close this issue.

**Comment by davelab6** [comment]
TTFAutohint does the same thing this tool does, but in some fonts hinting doesn't make sense, and in this case I want to apply 'non hinting' to the fonts. 

There is some explanation of this in https://github.com/googlefonts/gf-docs/blob/master/HowToGenerateWebNativeFonts.md and https://github.com/googlefonts/gf-docs/blob/master/HowToGenerateWebNativeFontsWithFontForge.md and the script to set non hinting is in https://bitbucket.org/lassefister/old-googlefontdirectory/src/21142f3bf7ad39d89c1c682d30830494ef1c905c/tools/nonhinting/setnonhinting-fonttools.py?at=default&fileviewer=file-view-default

**Comment by davelab6** [comment]
TTFAutohint does what this tool is checking for, I mean

**Comment by davelab6** [comment]
@felipesanches please take an unhinted ttf, and make 2 versions, a ttfa'd font and a fb fix'd font, and compare the gasp tables, and post the results here

**Comment by anthrotype** [comment]
ttfautohint simply creates a new `gasp` table with a single range, and all the four bits set (which amounts to the decimal value 15 or `0b1111`).

so Marc is right, in the sense that fb should not update the existing gasp, but replace it with the desired value if it wants to do the same as TTA.

However, I don't think you want to set the gridfitting bits on in case the font is not hinted. They won't make any difference anyway, as there are no instructions to gridfit to.

**Comment by davelab6** [comment]
If there is no gasp table, then rendering is worse; maybe I'm confusing this with what the prep table code does.

**Comment by anthrotype** [comment]
> If there is no gasp table, then rendering is worse

I didn't mean you should drop the gasp; just that for unhinted fonts the flags `GASP_GRIDFIT` (`0x1` or '0b1') and `GASP_SYMMETRIC_GRIDFIT` (`0x4` or `0b100`) wouldn't make any difference if they are set or not, as these contain no glyf instructions required for gridfitting. The flags `GASP_DOGRAY` (`0x2` or `0b10`) and `GASP_SYMMETRIC_SMOOTHING` (`0x8` or `0b1000`) are enough for non hinted fonts.

**Comment by anthrotype** [comment]
the minimal `prep` code in the above linked script is to enable "dropout control" (`SCANCTRL[]` set to 511), and select the so-called "smart" dropout control including "stubs" (`SCANTYPE` with value `4`). 
See http://www.microsoft.com/typography/otspec/ttinst.htm, "The TrueType Instruction Set, Part 1", pages 63-66.

**Comment by felipesanches** [comment]
I hope this is good now :-)
