### ISSUE TITLE
Doc strings

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#891]
We need doc strings for each of these scripts. 

I didn't realise that fix-gasp was basically to correct the gasp after running ttfautohint.

Cheers,
Marc

**Comment by davelab6** [comment]
I agree we need docstrings for everything. 

fix-gasp does the same thing that ttfautohint does to the gasp table, but without adding goops of hint code.

**Comment by felipesanches** [comment]
I think we would first need to have some refactoring as described at https://github.com/googlefonts/fontbakery/issues/971#issuecomment-245797089 in order to add docstring to each test function(or method).

**Comment by m4rc1e** [comment]
Hey @felipesanches and @davelab6,

I would prefer FB didn't do hot fixes.

All errors should be fixed at the source imo.

My current workflow is to generate the fonts from Glyphsapp into an ofl repo structure, run FB and fix the errors in the source files until it clears FB (or as close as possible).

I've been working on a [script]((https://github.com/m4rc1e/mf-glyphs-scripts/blob/master/Fixes/fix_gf_spec.py)) which will fixsome of the constants for GlyphsApp sources. Its still draft.

@vmesel I understand you really wanted to tackle this issue, #971 . If the others agree that we should hot fix, then feel free to proceed. It may be better to wait until we've fixed the obvious errors due to the merge conflicts that will happen. In the meantime, I'm now testing large font families and coming across more FB related errors. I will post some up during this week. Please feel free to tackle them. They're well within your skill range and shouldn't take too long. I will provide links to all sources as well. Thank you for getting involved on this project ;)

Cheers,
Marc

**Comment by davelab6** [comment]
hotfixes are required for projects without sources and when there is no
time/resources for recreating sources.

**Comment by felipesanches** [comment]
Yes, I agree that hotfixes are bad and that everything should be fixed in the source files. But @davelab6 has got a point here, that sometimes, in very specific situations, hotfixes are needed. So deleting them all may be throwing away useful code.

**Comment by m4rc1e** [comment]
Alright, the no time constraint is a valid concern ;)

**Comment by davelab6** [comment]
> We need doc strings for each of these scripts.

This is still true :) This seems like it should be quick to do.

**Comment by felipesanches** [comment]
For the individual scripts, yes. For the main check-ttf script, no.

The problem with the check-ttf script is that it should (in my opinion) be restructured with one function per check and then (only then) each of these could have its own docstring.

**Comment by davelab6** [comment]
@m4rc1e what do you want?

**Comment by m4rc1e** [comment]
It's fine not to have a doc string for check-ttf.py. Felipe's suggestion is good. However, this is a lot of work. Better logging is more appropriate for this script imo.

I would really like them on the fix scripts, e.g fontbakery-fix-gasp.py could have.
```
'''
Set font gasp to 15, across all ranges. More info on can be found on the GF spec, https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md#gasp
'''
```

This pretty much summarises what the script is doing, without me having to read the code.

**Comment by davelab6** [comment]
Merging into #681
