### ISSUE TITLE
Review output styling 

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#893]
Alexei's thread in googlefonts-discuss suggests that I need to review the json and verbose args for fontbakery-check-ttf.py

- [x] OK messages should not appear in the json file unless the verbose flag is passed. 
- [x] json output should only appear when --json is passed
- [ ] perhaps the plain text output should be dropped and ghm output should be default, and work well as a plain text output

**Comment by felipesanches** [comment]
> perhaps the plain text output should be dropped and ghm output should be default, and work well as a plain text output

Plain text output already is the same content that gets optionally redirected to json and/or markdown.
I'm not sure what you mean by "dropping" it. Should terminal output be completely silent during checks?

Maybe the output should be a progress-bar followed by a summary? And then details can be seen on the output files.

Hmmm... I think I can experiment with this idea...
