### ISSUE TITLE
"version 3.001" vs "version 3.0099"

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#896]
On https://github.com/googlefonts/fontbakery/issues/892#issuecomment-236612925 @alexeiva and @davelab6 had this conversation:
> > Alexei: Something else I noticed: Is there something wrong with version 3.001 — why is it changed to 3.00099?
>
> Dave: I think this is a bug so I'm re-opening the issue; 3.00099 and 3.001 are equivalent but fontTools represents 3.0001 as 3.00099 for computer science number precision reasons. Font Bakery is simply confused here.

**Comment by felipesanches** [comment]
@alexeiva Can you tell me where to download a "Version 3.001" TTF of Jura so that I can replicate this issue and fix it ?

**Comment by alexeiva** [comment]
Here you go:

This bug may be true for other numbers too

The version numbers were set in Glyphs app. They may have been adjusted by glyphs during export. (Glyphs behaviour).
Regular: v3.001
Medium: v3.010
SemiBold: v3.100
Bold: v3.0099

[Archive.zip](https://github.com/googlefonts/fontbakery/files/398112/Archive.zip)

**Comment by felipesanches** [comment]
thanks

**Comment by felipesanches** [comment]
I inspected Jura-Bold.ttf with ttx and noticed that there are "3.099" entries originaly in the font tables.

Such as:

```
  <head>
    <!-- Most of this table will be recalculated by the compiler -->
    <tableVersion value="1.0"/>
    <fontRevision value="3.099"/>
```

and also:

```
    <namerecord nameID="3" platformID="1" platEncID="0" langID="0x0" unicode="True">
      3.099;CYRE;Jura-Bold
    </namerecord>
```

and:

```
    <namerecord nameID="5" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Version 3.099
    </namerecord>
```

and also this:

```
    <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
      3.099;CYRE;Jura-Bold
    </namerecord>
```

and this:

```
    <namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
      Version 3.099
    </namerecord>
```

**Comment by felipesanches** [comment]
> Dave: I think this is a bug so I'm re-opening the issue; 3.00099 and 3.001 are equivalent but fontTools represents 3.0001 as 3.00099 for computer science number precision reasons. Font Bakery is simply confused here. 

And I think this is a bug in some other tool used by @alexeiva prior to using fontbakery

**Comment by felipesanches** [comment]
Please reopen the issue if I'm wrong :-)

**Comment by davelab6** [comment]
3.00099 != 3.099

The error Alexei posted was,

> INFO     HOTFIXED: Font version fields. Fixes: NAMEID_VERSION_STRING from 'Version 3.001' to 'Version 3.00099;' | NAMEID_VERSION_STRING from 'Version 3.001' to 'Version 3.00099;' 

Did you reproduce this error?

**Comment by davelab6** [comment]
with the Regular (v3.001)?

**Comment by felipesanches** [comment]
Yes, I did reproduce it with Jura-Regular.ttf as well:

```
### Checking font version fields
* ERROR: Font version fields. Changes that must be applied to this font: NAMEID_VERSION_STRING from 'Version 3.001' to 'Version 3.00099' | NAMEID_VERSION_STRING from 'Version 3.001' to 'Version 3.00099'
```

And inspecting the same original Regular file with ttx I got:

```
  <head>
    <!-- Most of this table will be recalculated by the compiler -->
    <tableVersion value="1.0"/>
    <fontRevision value="3.00099"/>
```

and

```
    <namerecord nameID="3" platformID="1" platEncID="0" langID="0x0" unicode="True">
      3.001;CYRE;Jura-Regular
    </namerecord>
```
and also

```
    <namerecord nameID="5" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Version 3.001
    </namerecord>
```

**Comment by davelab6** [comment]
Right. `    <fontRevision value="3.00099"/>` is the accuracy thing I mentioned; it should be 3.001 and it really is that, so the error is unwanted.

**Comment by alexeiva** [comment]
Here are my steps on Marmelad.

1. Generate font in Glyphs with version 1.001
2. ttf > ttx
3. TTX [fontRevision](https://github.com/cyrealtype/Marmelad-Cyrillic/blob/master/Marmelad-Regular.ttx#L364)


```
<tableVersion value="1.0"/>
    <fontRevision value="1.00099"/>
```

4. 
However, [namerecord table](https://github.com/cyrealtype/Marmelad-Cyrillic/blob/master/Marmelad-Regular.ttx#L16638-L16717):

```
 <namerecord nameID="3" platformID="1" platEncID="0" langID="0x0" unicode="True">
      1.001;CYRE;Marmelad-Regular
    </namerecord>
...
<namerecord nameID="5" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Version 1.001
    </namerecord>
...
 <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
      1.001;CYRE;Marmelad-Regular
    </namerecord>
...
<namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
      Version 1.001
    </namerecord>
```

So I confirm that the version change is Glyphs behaviour, not a font-bakery bug.  I think font-bakery should not check`namerecord` === `fontRevision`.

Here is output from fb on ttf v.1.001

```
ERROR    Font version fields. Changes that must be applied to this font: NAMEID_VERSION_STRING from 'Version 1.001' to 'Version 1.00099' | NAMEID_VERSION_STRING from 'Version 1.001' to 'Version 1.00099'  
```

**Comment by davelab6** [comment]
> the version change is Glyphs behaviour, not a font-bakery bug

I'm pretty sure all font editors appear to do this, and its a fonttools behaviour, not a bug. 

https://docs.python.org/2/tutorial/floatingpoint.html

**Comment by davelab6** [comment]
Basically, if the fontRevision value doesn't match, try rounding it up, then seeking a match, and only then failing

**Comment by felipesanches** [comment]
sounds good!

**Comment by felipesanches** [comment]
I'll try the rounding before failing

**Comment by felipesanches** [comment]
This was a bit tricky but I think it works as expected now :+1:

**Comment by felipesanches** [comment]
Current code breaks with version strings such as "Version 4.5.1"

**Comment by davelab6** [comment]
> Current code breaks with version strings such as "Version 4.5.1"

Yeah, that may be found in the wild but I only want to see X.Y versions
