### ISSUE TITLE
Bring back --autofix argument on fontbakery-fix-vertical-metrics.py

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#897]
It seems there are tools from the last 0.0.15 release still missing :( 

I needed to use `fontbakery-fix-vertical-metrics.py` and found it missing, but I'd like to ensure all tools are available. 

https://github.com/googlefonts/fontbakery/blob/7145ce54594fb8b8de8f65e94bae5be76bdf07e3/tools/fontbakery-fix-vertical-metrics.py

**Comment by felipesanches** [comment]
old script was here:

https://github.com/googlefonts/fontbakery/blob/v0.0.15/tools/fontbakery-fix-vertical-metrics.py

it gives you command line params for setting specific values explicitely. I can quickly bring it back to master as is.

Aditionally it has got an autofix block of code that depends on the VFixer class. I'll have to look at this class more carefully later.

**Comment by felipesanches** [comment]
VMet and VMetFixer classes are here:

https://github.com/googlefonts/fontbakery/blob/v0.0.15/bakery_cli/fixers.py#L691-L739

**Comment by m4rc1e** [comment]
Hey Felipe,

I'm currently in the middle of writing a vertical metrics checker for Glyphsapp. This is based on 2 new  schemes we discussed in [Kalapi's thread](https://groups.google.com/forum/#!topic/googlefonts-discuss/W4PHxnLk3JY). It should be loose enough to incoporate into FB. I'll let you know when I upload.

Cheers,
Marc

**Comment by felipesanches** [comment]
nice :-)

**Comment by davelab6** [comment]
Sure, the logic is duplicated, but I still need the old tools that work
'surgically' on a few issues! :)

**Comment by m4rc1e** [comment]
Reopening this. 

Had a request from Edd Harrington at Colophon. He used to use the autofix option, https://github.com/googlefonts/fontbakery/blob/master/bin/fontbakery-fix-vertical-metrics.py#L256-L257

**Comment by davelab6** [comment]
Thanks Marc. I haven't been checking this but yes, I want all the old tools
to be available. See any others missing?

**Comment by felipesanches** [comment]
All scripts are now guaranteed to be available.

I'll keep this issue open since it still requires bringing back the --autofix argument to the fix-vertical font-metrics script.

**Comment by felipesanches** [comment]
(1) View vmetrics data:

![screenshot at 2017-10-18 17 30 45](https://user-images.githubusercontent.com/213676/31739363-613d6f82-b42c-11e7-8d98-ca06bda609a7.png)

(2) Run the vmetrics fontbakery test (**com.google.fonts/test/040**) and notice that the data has bad values as reported by all the FAILs:
![screenshot at 2017-10-18 17 32 24](https://user-images.githubusercontent.com/213676/31739423-9084f440-b42c-11e7-9b90-38f42dbcbd88.png)

(3) Then run the fix-vertical-metrics subcommand with --autofix
(4) And re-run test/040 to make sure we get all green PASS results :-D
![screenshot at 2017-10-18 17 41 11](https://user-images.githubusercontent.com/213676/31739448-aa938888-b42c-11e7-93b2-7ab3f4461b0f.png)

**Comment by felipesanches** [comment]
Hey, @m4rc1e ! Could you please ping Edd Harrington at Colophon and tell him that we got the --autofix option back so that he can use it again ?

cheers!

**Comment by davelab6** [comment]
I've done so

**Comment by felipesanches** [comment]
Thanks, @davelab6 !
