### ISSUE TITLE
expected subsets ordering on METADATA.pb

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#912]
This caught my attention today when running fb on Merriweather:

```
ERROR METADATA.pb subsets are not sorted in alphabetical order: Got ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext', 'menu'] and expected ['menu', 'cyrillic', 'cyrillic-ext', 'latin', 'latin-ext']
```

At first I thought that the criteria was to place "menu" as the first item and then all the rest in alphabetical order, but the error above was reported for Merriweather and it seems it is sorting all items and placing "menu" after "latin-ext" instead of as the first item.

Should we accept both ?

**Comment by davelab6** [comment]
The menu first thing was old; I'm not using whatever `add_font.py` outputs which is true alphabetical, so FB should reflect that: 

```
~/fonts/tools $ python add_font.py ../ofl/merriweather;
~/fonts/tools $ tail -n 5 ../ofl/merriweather/METADATA.pb;
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
```

**Comment by davelab6** [comment]
menu and latin should always be present, and if they aren't we should warn

**Comment by m4rc1e** [comment]
I'm still getting this error. 

It is present in 100% of the repos I've come across. I'm using add_font.py to generate METADATA.pb files. I've been ignoring it so far

Does the order really matter?

If it ain't broke, don't fix it comes to mind.

As @davelab6 said, it would be nice to check if 'Menu' and 'Latin' were present.

**Comment by felipesanches** [comment]
@davelab6 should the METADATA.pb of all old font projects be fixed to pass this check? Or should the check be dropped ?

**Comment by davelab6** [comment]
> It is present in 100% of the old repos I've come across. Yes, add_font.py does make it alphabetical.

Right - the old repos were made at a time when the menu and latin subsets were ordered first, but now that is not the case. They should be updated to be alphabetical.

**Comment by davelab6** [comment]
> should the METADATA.pb of all old font projects be fixed to pass this check? Or should the check be dropped ?

Yes, they should; but since it will be a bit of a pain, if you can write a specific fixer for this, I can schedule fixing in the future.

**Comment by felipesanches** [comment]
ok, cool! Lets automate that fix .-)

**Comment by davelab6** [comment]
> ok, cool! Lets automate that fix .-)

Yes, but later :)

> If it ain't broke, don't fix it comes to mind.

@m4rc1e please update the METADATA files that you touch to resolve this

**Comment by felipesanches** [comment]
ok

**Comment by m4rc1e** [comment]
> @m4rc1e please update the METADATA files that you touch to resolve this

Ok

**Comment by davelab6** [comment]
> Lets automate that fix :-)

So, to resolve this issue, FB should reorder the subsets if a METADATA exists with out-of-order subsets?

**Comment by felipesanches** [comment]
yep! That's what I intend to do. If FB detects an unordered list of subsets, then the METADATA.pb file should be rewritten by FB with the correct order.

**Comment by davelab6** [comment]
@m4rc1e do you think we need a singleton tool for this?

**Comment by m4rc1e** [comment]
@davelab6 I thought about writing this. 

Personally, I would prefer FB not to hot fix, unless you explicitly tell it to. Making this auto every time, feels incredibly dangerous. 

If we do add this as a hot fix option, there's no need for a standalone script. I'm cool either way.

I'm thinking we need some collection wide fixes in the google/fonts repo. Running the new ttfauothint on all fonts and reordering METADATA.pb, would significantly boost the quality all round.

**Comment by davelab6** [comment]
All autofixing is hidden behind an `--autofix` arg, but I think it would indeed be better to have all singleton autofix tools and a BFG shell script that can apply them all, and then zero linter-arg-based hotfix functionality. 

@felipesanches please make a singleton tool for this.

**Comment by felipesanches** [comment]
ok.

what is BFG?

**Comment by felipesanches** [comment]
you're talking about this? https://rtyley.github.io/bfg-repo-cleaner/

**Comment by davelab6** [comment]
https://en.wikipedia.org/wiki/BFG_(weapon)

**Comment by felipesanches** [comment]
Alrrrriiight !!1 :-)

**Comment by davelab6** [comment]
@felipesanches what is the current status of this?
