### ISSUE TITLE
fontbakery-build-metadata.py relies on old codebase

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#917]
we don't have the bakery_cli module anymore and it can be seen that it was just commented out in the latest code change I introduced while addressing issue #830 :

https://github.com/googlefonts/fontbakery/blob/514d17de5de19f37eff2777e0066199b71bc8a0f/fontbakery-build-metadata.py#L31-L33

**Comment by davelab6** [comment]
from bakery_cli.nameid_values import *

I think you can just inline these name ID values

    from bakery_cli.scripts import genmetadata

This is now https://github.com/googlefonts/fontbakery/blob/master/fontbakery-build-metadata.py

**Comment by davelab6** [comment]
Edit: oops I see my answer is nonsense. What I mean is: 

This is now https://github.com/googlefonts/fontbakery/blob/master/fontbakery-build-metadata.py so the guts of genmetadata.py need to be taken and placed into there - OR, they need to be abandoned, and replaced with `add_font.py` which is the new replacement for this script in the /google/fonts repo

**Comment by felipesanches** [comment]
if choosing the latter, should I simply drop  fontbakery-build-metadata.py deleting it from the repo and leave add_font.py hosted at /google/fonts ? Or would you want add_font.py to be redundantly hosted in fontbakery's repo as well?

**Comment by davelab6** [comment]
Yeah let's just drop it from here :)
