### ISSUE TITLE
Check space matches No break space

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#918]
Hello,

We need a test and possibly a fix script to make sure the metrics for space (uni 0020) and no break space (uni 00A0) match.

**Comment by felipesanches** [comment]
I think that the check "Whitespace glyphs have coherent widths?" already covers that kind of problem.

@m4rc1e Can you take a look at https://github.com/googlefonts/fontbakery/blob/514d17de5de19f37eff2777e0066199b71bc8a0f/fontbakery-check-ttf.py#L2095-L2124 to see if it provides what you're asking for?

**Comment by davelab6** [comment]
Agree w felipe

**Comment by m4rc1e** [comment]
Yep, it's covered. 

Thanks
