### ISSUE TITLE
Scripts that still rely on old code

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#922]
Just like in issue #917, there's also this other script that still depends on the old codebase: fontbakery-build-fontmetadata.py

```
Needs fontbakery
```

**Comment by felipesanches** [comment]
This expects portions of fontbakery to be loaded from installed modules. I think we should hardcode everything so that the user does not have to deal with this kind of silly issue.

**Comment by davelab6** [comment]
Agree
