### ISSUE TITLE
Move all inline "TODO" issues from source code to issue tracker

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#924]
so that we can better manage the tasks here.

**Comment by felipesanches** [comment]
This sounds like a meta-issue. I see nothing really special about this collection of issues other than the fact that their origin were inline comments in the source. No need to keep it open. We can work directly on each individual issue tracker entry.

**Comment by davelab6** [comment]
$ grep TODO fontbakery-check-ttf.py  | wc -l
      13
    $

**Comment by felipesanches** [comment]
You still see them there because I did not delete the comments. I simply attached the specific issue-url together with the original lines of TODO comments.

**Comment by davelab6** [comment]
Okay cool :)
