### ISSUE TITLE
Create script to convert commit messages into FONTLOG style entries

### ISSUE THREAD

**Issue by n8willis** [googlefonts/fontbakery#93]
(@n8willis started this issue but @davelab6 rewrote it)

Creating a user-friendly Fontlog at release time should be simple.

Version-control commit messages can be a great way to see what has changed. 

Cutting out the minor and irrelevant messages is less time consuming than going back through the commit history and manually recopying the same info, and is less error- and forgetfulness-proned. 

So a relatively simple AngularJS page should be made that makes it easy to update a FONTLOG by reviewing the git history... similar to our METADATA.json comparison page, with the existing FONTLOG on the left and a 2nd 50% wide column with all the commit messages. The commit messages would be fetched via the Github API when the user clicks a button, so the page loads instantly and the user triggers the action that can take a while. The commit messages should populate line by line as they are downloaded by the browser, similar to the dashboard table.

**Comment by felipesanches** [comment]
Migrating to https://github.com/googlefonts/tools/issues/17
