### ISSUE TITLE
DC: TODO: checker for proper italic names in name table

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#932]
```
    # ----------------------------------------------------
    # TODO: checker for proper italic names in name table
    # Dave Crossland said: THIS IS URGENT!
```

this is probably tightly related to issue #930 and #931 

(issue #924)

**Comment by vmesel** [comment]
@felipesanches what should be done? Want to help and got FontForge up and running on my macbook!

**Comment by davelab6** [comment]
Hi @vmesel :) This is a tricky one for a new contributor to tackle, it requires some understanding of context that would take longer to explain than for Felipe to fix directly :) If you'd like to contribute, I suggest https://github.com/googlefonts/fontbakery/issues/831 might be a good issue to work on

**Comment by vmesel** [comment]
@davelab6 it doesnt look like too creepy! I think you mean that the font file, in the header, has the name info, and if the name contains Italic, it should fill a new place in the table. Right?

**Comment by felipesanches** [comment]
@davelab6 I believe that the check called "Assure valid format for the main entries in the name table." already takes care of validating the correctness of all name table strings. The italic name entries are a specific case of that.

The "Assure valid format for the main entries in the name table." check starts at https://github.com/googlefonts/fontbakery/blob/7d284ab1777bc13bd48c500faacfa4f263c1a642/fontbakery-check-ttf.py#L971

Unless I am missing something, there's nothing left to be done here other than deleting this TODO comment from the source code.

**Comment by felipesanches** [comment]
@davelab6 if you agree, please close this issue.

I just deleted that comment from the sources.

I consider this an invalid issue unless there's some special check for italics that we still do not perform and I may be not aware of.
