### ISSUE TITLE
strip glyphs named .notdef .null (etc) from unusually_spaced_glyphs list

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#933]
https://github.com/googlefonts/fontbakery/blob/a02a4f01cb6f4664b91fa6d7c695bddf1187bd32/fontbakery-check-ttf.py#L1638-L1639

(issue #924)

**Comment by khaledhosny** [comment]
If the check is a bout a monospaced fonts, then the safest things is to make sure all glyphs unconditionally have the same width, otherwise setting isFixedPitch or bProportion can load to broken glyph widths on Windows at least.
