### ISSUE TITLE
log FontForge STDERR messages

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#934]
```
    # ----------------------------------------------------
    # TODO FontForge will sometimes say stuff on STDERR like
    # $ fontbakery-check-ttf.py ~/fonts/apache/cousine/Cousine-Regular.ttf
    #   The following table(s) in the font have been ignored by FontForge
    #     Ignoring 'VDMX' vertical device metrics table
    #   The glyph named circumflex is mapped to U+F031F.
    #   But its name indicates it should be mapped to U+02C6.
    # $
    #
    # We should detect this and if found, warn about that output.
    #
    # Felipe Sanches:
    # I've been inspecting the fontforge python module source code
    # and it seems that the leakage of stderr messages results from
    # an API design flaw in the module implementation.
    # I am not sure if we can hijack those prints. Maybe we would
    # actually need to modify fontforge code itself to achieve that.
    # I'll have to investigate it further in order to provide a
    # better informed analysis.
    #
    # Dave Crossland:
    # Then we can load the font via the command line instead of
    # with the python module, and grab the stderr that way
```

https://github.com/googlefonts/fontbakery/blob/a02a4f01cb6f4664b91fa6d7c695bddf1187bd32/fontbakery-check-ttf.py#L1750-L1770

(issue #924)

**Comment by felipesanches** [comment]
I'm trying to figure our how to use fontforge in a headless manner to perform these checks. I'm not sure fontforge can do the same as the python module via a command-line invocation. Perhaps it really can't. The command line parameters listed on the --help output does not seem to indicate this kind of capability.

**Comment by felipesanches** [comment]
It seems that there's no really useful data (for our purpose) in fontforge's console output:

```
felipe@guarana:~/devel/github_felipesanches/fontbakery$ fontforge ~/Downloads/FONTS/Carlito/Carlito-Italic.ttf 
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 22:30 BRT 24-Sep-2015-ML-D.
 Based on source from git with hash: fd9666ad5dd014c13d732ab4b053fa7737cea620
no xdefs_filename!
TESTING: getPixmapDir:/usr/local/share/fontforge/pixmaps
TESTING: getShareDir:/usr/local/share/fontforge
TESTING: GResourceProgramDir:/usr/local/bin
trying default theme:/usr/local/share/fontforge/pixmaps/resources
fontforge.hasUserInterface!
PyFF_onAppClosing() cnt:1
else argv[i]:/home/felipe/Downloads/FONTS/Carlito/Carlito-Italic.ttf
SplineFontPieceMeal() going unhinted...
python_call_onClosingFunctions_fe() f:0x7f6a95c25d70
webcollab closing...
felipe@guarana:~/devel/github_felipesanches/fontbakery$
```

**Comment by felipesanches** [comment]
There's a -c option that sounds promising, but I can't make it work. These are the instructions from the website at https://fontforge.github.io/cliargs.html :

```
-c script-string
    If FontForge's first (or second, if the first is -lang) argument is "-c" then the argument that follows will be treated as a string containing scripting commands, and those commands will be executed. All remaining arguments will be passed to the script.

        $ fontforge -c 'Open($1); Generate($2)' foo.sfd foo.ttf

    Will read a font from "foo.sfd" and then generate a truetype font from it called "foo.ttf" 
```

I thought I could perhaps do -c 'Open($1); Close($1)' but it fails to run:

```
  File "<string>", line 1
    from sys import argv; from fontforge import *; open($1)
                                                        ^
SyntaxError: invalid syntax
felipe@guarana:~/devel/github_felipesanches/fontbakery$
```

**Comment by felipesanches** [comment]
hey! I think I got it right now! :-D

Quite hacky :-P

```
felipe@guarana:~/devel/github_felipesanches/fontbakery$ fontforge --quiet -c "f = fontforge.open(sys.argv[1]); state = f.validate(); print state" ~/Downloads/FONTS/Carlito/Carlito-Italic.ttf 
36
felipe@guarana:~/devel/github_felipesanches/fontbakery$ 
```

**Comment by felipesanches** [comment]
ok, so this last command I came up with generates the numerical value that can be tested with the bit_masks for each of the checks, but it did not produce any STDERR messages... hmmm...

**Comment by felipesanches** [comment]
This afternoon I have tried to use the contextlib module to temporarily redirect the stderr stream of the imported fontforge module, as described at http://stackoverflow.com/questions/4675728/redirect-stdout-to-a-file-in-python/22434262#22434262

There were two major issues:

(1) The documentation of contextlib only lists a redirect_stdout method but not redirect_stderr (or even a more generic redirect_stream, for that matter!). But I found an issue on their bugtracker where people apparently discussed about precisely this problem and did indeed implement the complementary method: https://bugs.python.org/issue22389 Unfortunately such method does not seem to be available in contextlib on python 2 and we still have a few issues to solve in order to get Fontbakery working with python 3.

(2) I have then tried to approach the problem from another angle and tried using @contextmanager to create this snippet of stderr redirection code:

```python
    from contextlib import contextmanager
    @contextmanager
    def stderr_redirected(new_stderr):
        save_stderr = sys.stderr
        sys.stderr = new_stderr
        try:
            yield None
        finally:
            sys.stderr = save_stderr
```

But this did not work with the imported module. I noticed some people complaining about a similar issue here: http://stackoverflow.com/questions/14007262/redirect-stderr-of-an-imported-c-dll-to-an-arbitrary-file

**Comment by felipesanches** [comment]
oh yeah! I finally got it right without a hack! :-D

**Comment by felipesanches** [comment]
oh, well... it seems that handling stderr this way messes up with Travis understanding of the build status. Even though it passed all of the checks, it is now reporting it as a failed build :-P

**Comment by davelab6** [comment]
@felipesanches what was the final status of this? :)

**Comment by felipesanches** [comment]
All error messages output to stderr were temporarily redirected to an IOString buffer and then this was saved as messages in the fontbakery error log (results in both json and ghm output files).

After finishing the fontforge check, stderr redirection is undone so that all the rest of the program works as usual.
