### ISSUE TITLE
extend list of known_good_names (.notdef, .null, etc)

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#938]
```
    fb.new_check("Glyph names are all valid?")
    known_good_names = ['.notdef', '.null']
    bad_names = []
    # we should extend this list according to the opentype spec
```

https://github.com/googlefonts/fontbakery/blob/a02a4f01cb6f4664b91fa6d7c695bddf1187bd32/fontbakery-check-ttf.py#L2273-L2277

(issue #924)

**Comment by felipesanches** [comment]
At https://www.microsoft.com/typography/otspec/recom.htm we have:

```
NOTE: The PostScript glyph name must be no longer
than 31 characters, include only uppercase or
lowercase English letters, European digits, the 
period or the underscore, i.e. from the set [A-Za-z0-9_.]
and should start with a letter, except the special 
glyph name ".notdef" which starts with a period.
```

and at http://partners.adobe.com/public/developer/opentype/index_glyph2.html there's this:

```
A glyph name may be up to 31 characters in length, must 
be entirely comprised of characters from the following set:

    A-Z
    a-z
    0-9
    . (period)
    _ (underscore) 

and must not start with a digit or period.
The only exception is the special character ".notdef".

"twocents", "a1", and "_" are valid glyph names.
"2cents" and ".twocents" are not.
```

**Comment by felipesanches** [comment]
and currently we have:
```
    fb.new_check("Glyph names are all valid?")
    known_good_names = ['.notdef', '.null']
```

So I think we simply have to remove '.null' from the list of known good names and then we're settled with the single one expection to the "no name starting with a period" naming rule.

**Comment by felipesanches** [comment]
Unless someone can point me to a definitive list of exceptions to the rule, I'll assume that (as stated in the spec) '.notdef' is the only exception.

**Comment by felipesanches** [comment]
@davelab6 please review and close

**Comment by felipesanches** [comment]
I noticed that Jura-Regular.ttf does have the .null glyph. Should we accept it as valid even though (afaik) it is not mentioned in the spec ?

Or should Jura be fixed instead?

**Comment by davelab6** [comment]
See "First Four Glyphs in Fonts" section of https://www.microsoft.com/typography/otspec/recom.htm

Thus Jura should be fixed

**Comment by davelab6** [comment]
And we should have a test that they are there

**Comment by felipesanches** [comment]
ok, great!

So I'll bring back .null to the list of known_good_glyphnames

And Jura is perfectly fine.

**Comment by felipesanches** [comment]
@behdad Could you help me here? I don't know how to check for the presence of '.notdef' in a font using fonttools.

**Comment by behdad** [comment]
> @behdad Could you help me here? I don't know how to check for the presence of '.notdef' in a font using fonttools.

Like, check that glyph0 is named '.notdef'?

font.getGlyphOrder()[0] == '.notdef'

**Comment by felipesanches** [comment]
thanks, @behdad :+1:

**Comment by madig** [comment]
In OT 1.8, only `.notdef` is recommended now and the rest not mentioned.

**Comment by anthrotype** [comment]
.null is still mentioned in the CORL table spec. Apparently DirectWrite has some implementation detail that expects the glyph at index 1 be empty (non printable), but this only applies for CORL/CPAL color fonts, not all fonts.

If gid1 is non empty, then it will show up underneath all other color glyphs; this happens in Windows 10 on Google Chrome.

https://github.com/MicrosoftDocs/typography-issues/issues/346
