### ISSUE TITLE
Question: compare name table entries even if they have different encodings ?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#939]
```
    # ----------------------------------------------------
    fb.new_check("Does full font name begin with the font family name?")
    familyname = get_name_string(font, NAMEID_FONT_FAMILY_NAME)
    fullfontname = get_name_string(font, NAMEID_FULL_FONT_NAME)

    if not familyname:
      fb.error('Font lacks a NAMEID_FONT_FAMILY_NAME entry'
               ' in the name table.')
    elif not fullfontname:
      fb.error('Font lacks a NAMEID_FULL_FONT_NAME entry'
               ' in the name table.')
    # FIX-ME: I think we should still compare entries
    #         even if they have different encodings
    else:
      if not fullfontname.startswith(familyname):
        fb.error(" On the NAME table, the full font name"
                 " (NameID {} - FULL_FONT_NAME: '{}')"
                 " does not begin with font family name"
                 " (NameID {} - FONT_FAMILY_NAME:"
                 " '{}')".format(NAMEID_FULL_FONT_NAME,
                                 familyname,
                                 NAMEID_FONT_FAMILY_NAME,
                                 fullfontname))
      else:
        fb.ok('Full font name begins with the font family name.')
```

https://github.com/googlefonts/fontbakery/blob/a02a4f01cb6f4664b91fa6d7c695bddf1187bd32/fontbakery-check-ttf.py#L2402-L2414

@davelab6 I think we should still compare entries even if they have different encodings. Am I right here?

(issue #924)

**Comment by felipesanches** [comment]
I think that the real concern here is at:
https://github.com/googlefonts/fontbakery/blob/a02a4f01cb6f4664b91fa6d7c695bddf1187bd32/fontbakery-check-ttf.py#L438-L444

where the get_name_string function returns the first name entry with the nameid specified in its parameters.

So it seems that this function should return a list all entries with the specified nameid and then all code that relies on checking names would have to take care of evaluating the correctness of all entries instead of only the first one.

**Comment by davelab6** [comment]
Per https://github.com/googlefonts/fontbakery/issues/926 aren't there built in method for getting and setting namerecords?

**Comment by davelab6** [comment]
> it seems that this function should return a list all entries with the specified nameid and then all code that relies on checking names would have to take care of evaluating the correctness of all entries instead of only the first one.

Sounds right

**Comment by davelab6** [comment]
```
    # FIX-ME: I think we should still compare entries
    #         even if they have different encodings
    else:
      if not fullfontname.startswith(familyname):
        fb.error(" On the NAME table, the full font name"
                 " (NameID {} - FULL_FONT_NAME: '{}')"
                 " does not begin with font family name"
                 " (NameID {} - FONT_FAMILY_NAME:"
                 " '{}')".format(NAMEID_FULL_FONT_NAME,
                                 familyname,
                                 NAMEID_FONT_FAMILY_NAME,
                                 fullfontname))
```

I think this `fullfontname.startswith(familyname)` is wrong, because the comparison is with 
 
    familyname = get_name_string(font, NAMEID_FONT_FAMILY_NAME)

but should be

    familyname = get_name_string(font, NAMEID_TYPOGRAPHIC_FAMILY_NAME)

**Comment by davelab6** [comment]
But I'm just writing off the top of my head, I'm not totally sure
