### ISSUE TITLE
Can I use FontBakery on Windows?

### ISSUE THREAD

**Issue by vmesel** [googlefonts/fontbakery#946]
I'm trying to install all dependencies to install FontBakery but I cannot find it anywhere like python-fontforge?

Could someone help me?

The system is Windows 10, 16GB RAM, i5 processor

**Comment by felipesanches** [comment]
Have you figured it out, already?

Do you have specific questions about the dependencies?

**Comment by vmesel** [comment]
I havent figured it out, I need to find a way to get FontForge with extra tools on Windows. This is the first step...

**Comment by felipesanches** [comment]
@vmesel feel free to private message me if you need any further support.
