### ISSUE TITLE
ttfautohint version regex should not match line-breaks

### ISSUE THREAD

**Issue by vmesel** [googlefonts/fontbakery#957]
When running fontbakery with Carlito Font, the fontbakery-check-ttf.py is returning an error on the map split.

```
Traceback (most recent call last):
  File "fontbakery-check-ttf.py", line 3521, in <module>
    main()
  File "fontbakery-check-ttf.py", line 2379, in main
    ttfa_version):
  File "fontbakery-check-ttf.py", line 2356, in installed_version_is_newer
    installed = map(int, installed.split("."))
ValueError: invalid literal for int() with base 10: '5\nCopyright (C) 2011'
```

**Comment by vmesel** [comment]
str(installed) is returning:
```
1.5
Copyright (C) 2011
```
How the font file should return this information? Is this a local bug only?

**Comment by felipesanches** [comment]
this would be slightly better:

```
if "\n" in installed:
  installed = installed.split("\n")[0]
```

but there's still the issue that we're accepting this kind of format, which is kind of weird.
I think we should make this an error instead. What do you think, @davelab6 ? Should we have a check that detects this kind of bad entry? A test called something like: "Does version string contain copyright info?"

**Comment by vmesel** [comment]
I think we should check if the installed.split("\n")[0] is really a version number not the copyright test or any null field.

**Comment by felipesanches** [comment]
I have made it accept only the 1st line of the multiline version string. But I really think that we should consider this an error. The goal of fontbakery is to help in the quality assurance of a large set of font families. If only a couple fonts have this kind of malformed entries (or, in other words, entries with arbitrary formats) then these must really generate a warning or error that informs the user that the fields must conform to a more common and regular data format.

On the other hand, if you can show me that hundreds of font files have this sort of data format then we may add specific parsing rules for extracting the relevant info from such fields. It does not seem to be the case in here, though, so I'll close this issue as invalid.

@davelab6 You can reopen this issue if you think there's any value in spending more time with this.

**Comment by davelab6** [comment]
The version string should not have any linebreaks; that may be allowed in the spec but we should make it a requirement. 

It should also not have the copyright information. In the spec, any string can follow the version number itself, and there is a convention that a semicolon separates the version number from the following string. We can make that a requirement.

**Comment by felipesanches** [comment]
yeah, makes sense!

**Comment by felipesanches** [comment]
I think I'll tackle that with a check called "Name table antry continas line-break?" that errors if a line break is found in any entry.

**Comment by davelab6** [comment]
Since currently we get a traceback on a libre font, I'm bumping this to 0.1.0

**Comment by felipesanches** [comment]
ok, good!

**Comment by felipesanches** [comment]
This is actually a misunderstanding of the issue at hand.

The line-break and "Copyright" string after ttfautohint version number that leads to the crash described in the initial description of this issue actually comes from the "ttfautohint --version" subprocess output. It does not come from a name table entry!

So the issue here is in the subprocess output parsing regex which should not match multiple lines.

@vmesel are you running fontbakery on Windows, Mac or GNU ?

**Comment by vmesel** [comment]
Im running it on Mac OS X Yosemite.

**Comment by felipesanches** [comment]
Can you run it again with current master to see if the version is being correctly detected by the new regex, please?

**Comment by vmesel** [comment]
Running on the current master, everything seems to be fine, output on [Pastebin](http://pastebin.com/kBk0hg26)

**Comment by felipesanches** [comment]
alright!
