### ISSUE TITLE
IF Font license file not found, it should be an error?

### ISSUE THREAD

**Issue by vmesel** [googlefonts/fontbakery#960]
I'm trying to figure out [what this function](https://github.com/googlefonts/fontbakery/blob/master/fontbakery-check-ttf.py#L1452-L1506) does for the system. I noticed that it doesn't check/doesn't give an exception if the license file or the OFL license file is missing. Should we return an error when this happens?

**Comment by felipesanches** [comment]
@vmesel For bad fonts, the variable called "found" is False if no license file was found, or "multiple" if many were found.

Here's where we log an error related to the lack of font files:
https://github.com/googlefonts/fontbakery/blob/1a9537d2b9441784ba25c5fc8f0ab3ffe35013fc/fontbakery-check-ttf.py#L1359-L1361
