### ISSUE TITLE
Question: source of truth for font version ?

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#963]
I noticed this:

```
ERROR    Font version fields. Changes that must be applied to this font:
NAMEID_VERSION_STRING from 'Version 1.004' to 'Version 1.003' | NAMEID_VERSION_STRING from 'Version 1.004' to 'Version 1.003'
```

The hotfix is downgrading the font version by altering the version string in the name table because it is treating the font["head"].fontRevision entry as the source of truth.

I can see 3 possible approaches here:

* use font["head"].fontRevision as the source of truth (this is what the current implementation does)
* use NAMEID_VERSION_STRING as the source of truth
* use the max value of both of these entries as the source of truth

@davelab6 what would you conside the best approach?

**Comment by anthrotype** [comment]
nameID 5 is more important than head.fontRevision, IMO.

**Comment by davelab6** [comment]
I agree with Cosimo, the current approach is not ideal; I suggest to tell
both values and default fixer can use the max value of both of these
entries as the source of truth.

**Comment by vmesel** [comment]
I agree with @davelab6 it should be an ideal step to get the max value between both and set it as the source of truth.

**Comment by felipesanches** [comment]
@davelab6 I think this new implementation deals properly with the source of truth for font version. Please close the issue if you don't disagree.
