### ISSUE TITLE
Easier setup

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#998]
Hey folks,

This ranks as one of the worst installations I've ever had to do (worse than a tileserver). I would like to make a Docker image for lazy people. Would everyone be in favour of this?

Cheers,
Marc

**Comment by davelab6** [comment]
The script has a few dependencies but these should be tools any font designer has available, nothing fancy. What were your issues?

**Comment by davelab6** [comment]
But, still, 

    pip install -r requirements.txt

is what we should have

**Comment by m4rc1e** [comment]
Agreed, I'll add it later and amend the README

**Comment by felipesanches** [comment]
fixed at https://github.com/googlefonts/fontbakery/pull/1004/commits/950694fe685e7f711bc89c4739b81d20e3be8d8c
